### PR TITLE
BUG: do not use PyLong_FromLong for intp

### LINKED ISSUE #19034: Suspicious uses of `PyLong_FromLong`
See #19011.

Other suspicious uses of `PyLong_FromLong`:

https://github.com/numpy/numpy/blob/fb4ea911607a81ef6633b857122e34229075705e/numpy/core/src/multiarray/nditer_pywrap.c#L1530-L1531

https://github.com/numpy/numpy/blob/fb4ea911607a81ef6633b857122e34229075705e/numpy/core/src/multiarray/nditer_pywrap.c#L1559-L1560

### PR DESCRIPTION
**Pull request by mattip**
Fixes #19034 which is a continuation of #19011

### CODE REVIEW

File: numpy/core/src/multiarray/nditer_pywrap.c [hunk 1]
```diff
@@ -1557,7 +1557,7 @@ static PyObject *npyiter_multi_index_get(NewNpyArrayIterObject *self)
         }
         for (idim = 0; idim < ndim; ++idim) {
             PyTuple_SET_ITEM(ret, idim,
-                    PyLong_FromLong(multi_index[idim]));
+                    PyLong_FromSsize_t(multi_index[idim]));
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/nditer_pywrap.c:1560]: Really we should also be checking if `PyLong_FromSsize_t` returns `NULL` too, to avoid segfaults if a MemoryError occurs

Comment (seberg) [reply numpy/core/src/multiarray/nditer_pywrap.c:1560]: Its a bit of an odd one maybe, but might as well use `PyArray_IntTupleFromIntp` probably.

Comment (mattip) [reply numpy/core/src/multiarray/nditer_pywrap.c]: Adopted `PyArray_IntTupleFromIntp`, which properly checks `long long` and errors

**Review by eric-wieser — APPROVED** [review]

**Comment by seberg** [comment]
Thanks Matti and Eric.
