### PR TITLE
BUG: `np.loadtxt` return F_CONTIGUOUS ndarray if row size is too big

### LINKED ISSUE #26900: BUG: `np.loadtxt` return F_CONTIGUOUS ndarray if row size is too big
### Describe the issue:

If row size is too big in a text file, `np.loadtxt` will retrun a `np.ndarray` with `F_CONTIGUOUS` set.

### Reproduce the code example:

```python
import numpy as np

a = np.arange(25).reshape((-1, 5))
b = np.arange((1 << 14) + 2).reshape((-1, (1 << 13) + 1))

np.savetxt('a.txt', a)
np.savetxt('b.txt', b)

a = np.loadtxt('a.txt')
b = np.loadtxt('b.txt')
print(a.flags)
print(b.flags)

assert(b.tobytes('F') == b.copy().tobytes('F')) # error
```

### Error message:

```shell
C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[25], line 14
     11 print(a.flags)
     12 print(b.flags)
---> 14 assert(b.tobytes('F') == b.copy().tobytes('F'))

AssertionError:
```

### Python and NumPy Versions:

2.1.0.dev0+git20240708.735a477
3.12.4 (main, Jul  9 2024, 15:36:49) [GCC 11.4.0]

### Runtime Environment:

[{'numpy_version': '2.1.0.dev0+git20240708.735a477',
  'python': '3.12.4 (main, Jul  9 2024, 15:36:49) [GCC 11.4.0]',
  'uname': uname_result(system='Linux', node='hn00', release='5.15.0-105-generic', version='#115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024', machine='x86_64')},
 {'simd_extensions': {'baseline': [], 'found': [], 'not_found': []}},
 {'filepath': '/opt/intel/oneapi/mkl/2022.1.0/lib/intel64/libmkl_rt.so.2',
  'internal_api': 'mkl',
  'num_threads': 48,
  'prefix': 'libmkl_rt',
  'threading_layer': 'intel',
  'user_api': 'blas',
  'version': '2022.1-Product'},
 {'filepath': '/opt/intel/oneapi/compiler/2022.1.0/linux/compiler/lib/intel64_lin/libiomp5.so',
  'internal_api': 'openmp',
  'num_threads': 96,
  'prefix': 'libiomp',
  'user_api': 'openmp',
  'version': None}]

### Context for the issue:

`np.loadtxt` creates the `PyArrayObject` in `read_rows`, which reads a specific number of rows of the text file based on the allocated buffer size. If the row size was too big, `read_rows` might decide to read only one line (var `min_rows` below), and then `PyArray_SimpleNewFromDescr` would set both `F_CONTIGUOUS` and `C_CONTIGUOUS`. This results in an inconsistent behavior with what `loadtxt` does on small files.

code for context:
https://github.com/numpy/numpy/blob/6b2a3e08b4edb7737e1f7f39d4c6c71c42dfc07d/numpy/_core/src/multiarray/textreading/rows.c#L267-L300

### PR DESCRIPTION
**Pull request by determ1ne**
Closes #26900

### CODE REVIEW

**Comment by seberg** [comment]
Thanks for the PR/fix!  One thing is that the flags are actually correct if there is only a single row in the file (which we don't know at this point).
In that case, it can probably also go the other way (F contiguous isn't advertised, but a single row is both).

So I think the best way would be to just call `PyArray_UpdateFlags(self, NPY_ARRAY_F_CONTIGUOUS);` at the end once (or encode `rows > 1` there).

Also, to put it in timely, we always need a test to avoid regression in the future.

**Comment by determ1ne** [comment]
> Thanks for the PR/fix! One thing is that the flags are actually correct if there is only a single row in the file (which we don't know at this point). In that case, it can probably also go the other way (F contiguous isn't advertised, but a single row is both).
> 
> So I think the best way would be to just call `PyArray_UpdateFlags(self, NPY_ARRAY_F_CONTIGUOUS);` at the end once (or encode `rows > 1` there).
> 
> Also, to put it in timely, we always need a test to avoid regression in the future.

Thank you for your correction! I'll fix it up and write some tests for it.

File: numpy/_core/src/multiarray/textreading/rows.c [hunk 1]
```diff
@@ -480,6 +480,14 @@ read_rows(stream *s,
...
     }
 
+    /*
+     * If row_size is too big, F_CONTIGUOUS is always set
+     * as array was created for only one row of data.
+     * Clear the flag if more than one row was read.
+     */
+    if (row_count > 1) {
+        PyArray_CLEARFLAGS(data_array, NPY_ARRAY_F_CONTIGUOUS);
+    }
```
Comment (seberg) [inline numpy/_core/src/multiarray/textreading/rows.c:490]: I should have mentioned the other failure mode, since it is a bit hard to achieve:
```
assert np.loadtxt(["1 2", ""], ndmin=2).flags.f_contiguous
```
should succeed, but doesn't.  Thus to be perfectly right, we need to update the flags always, or add an else branch which sets it.

Maybe explain a bit more specific that depending on `row_size` the original array may or may not have been flagged as F_CONTIGUOUS, but that is wrong since the number of rows may have changed.  It is F_CONTIGUOUS exactly when `row_count <= 1`.

Comment (determ1ne) [reply numpy/_core/src/multiarray/textreading/rows.c]: Oops, sorry I didn't take it into consideration. Besides, it seems that even `np.loadtxt(["1 2"], ndmin=2).flags.f_contiguous` returns False. In this case, `row_count` still goes 2. I've added this sample into the test set.

File: doc/release/upcoming_changes/26901.changes.rst [hunk 2]
```diff
@@ -0,0 +1 @@
+* `numpy.loadtxt` no longer set `F_CONTIGUOUS` for text files with multiple rows and large row sizes.
```
Comment (seberg) [inline doc/release/upcoming_changes/26901.changes.rst:1]: This file isn't named correctly, I think it's `.change.`.  The change is a small/bug fix enough that we don't need it (but also OK to keep it).

We also have a Changelog, that just lists all PR titles, so not having a fragment here doesn't mean it's lost completely.

File: numpy/_core/tests/test_multiarray.py [hunk 3]
```diff
@@ -266,6 +266,52 @@ def test_void_align(self):
...
+
+        s = io.StringIO('\n'.join([d_short] * 5))
+        a = np.loadtxt(s, ndmin=2)
+        assert_(a.flags.c_contiguous)
+        assert_(a.flags.f_contiguous is False)
+
+        s = io.StringIO('\n'.join([d_long] * 5))
+        a = np.loadtxt(s, ndmin=2)
+        assert_(a.flags.c_contiguous)
+        assert_(a.flags.f_contiguous is False)
```
Comment (seberg) [inline numpy/_core/tests/test_multiarray.py:312]: If you are up to it, one thing that would be cute, is to write this as a `pytest.mark.parametrize` pattern, like:
```
@pytest.mark.parametrize("row", ["1.0 " * 5, "1.0 " * (1 << 16)])
@pytest.mark.parametrize("ndmin", [0, 2])
def test_xcontiguous_load_txt(self, row, ndmin):
```
To make the test much less repetitive.

As an aside: using `assert_()` is an ancient left-over pytest prefers `assert a.flags.c_contiguous`.  This file uses it a lot, so it's OK either way.

**Review by seberg — COMMENTED** [review]
Thanks looks good, but need to fix (or just delete) the release note entry file.

Would be better to make the test a bit more compact too as suggested.

File: numpy/_core/tests/test_multiarray.py (hunk 3 above)
Comment (determ1ne) [reply numpy/_core/tests/test_multiarray.py:312]: Fine, but pytest may fail if the parameter is too long, so `row_size` maybe a better option.

**Comment by seberg** [comment]
Thanks @determ1ne, let's put this in.
