### PR TITLE
BUG: clear only attribute errors in get_attr_string.h::maybe_get_attr

### LINKED ISSUE #14735: `warnings.filterwarnings` changes the behavior of `np.asarray`
Using `warnings.filterwarnings` with a numpy wrapper class changes the behavior of `np.asarray` (or rather `np.array`).

I believe the reason for this is the equivalent of an `except Exception` block (in the C code), since the warning base class `Warning` inherits from `Exception`.

Having `__len__` and `__getitem__` is not required to reproduce, but they make the difference a bit more obvious.

xref hgrecco/pint#892

### Reproducing code example:
```python
import warnings
import numpy as np

class NumpyWrapper:
    def __init__(self, array):
        self.array = array

    def __len__(self):
        return len(self.array)

    def __getitem__(self, *args, **kwargs):
        return type(self)(self.array.__getitem__(*args, **kwargs))

    def __getattr__(self, name):
        if name.startswith("__array_"):
            warnings.warn("object got converted", UserWarning)

        return getattr(self.array, name)

    def __repr__(self):
        return f"<Wrapper({self.array})>"

array = NumpyWrapper(np.arange(10))
print(repr(np.asarray(array))  # warning
# [0 1 2 3 4 5 6 7 8 9]
warnings.filterwarnings("error")
print(repr(np.asarray(array))  # no warning, but also no error
# [<Wrapper(0)> <Wrapper(1)> <Wrapper(2)> <Wrapper(3)> <Wrapper(4)>
#  <Wrapper(5)> <Wrapper(6)> <Wrapper(7)> <Wrapper(8)> <Wrapper(9)>]
```

### Numpy/Python version information:
numpy: 1.17.2
python: 3.7.3

### PR DESCRIPTION
**Pull request by keewis**
fixes #14735.

With this, filtered warnings (and all exceptions other than `AttributeError`) should be passed through. Though now raising `NotImplementedError` will also bubble up.

There are several issues with this fix and I'm not sure how to deal with them:
* I created a new test file named after the issue. This should probably go somewhere else, but I'm not sure where.
* I didn't find something similar, so I added a helper function to clear only a certain exception. Did I miss something?
* I'm also not sure whether the commentary / documentation of `maybe_get_attr` is still accurate (I didn't really understand what it meant).

Also, my knowledge of C is limited, so there may be obvious issues, especially with the signature of the helper.

@seberg, what do you think of this? I can confirm that the original issue can be avoided by explicitly adding `__array__` and warning there, so I don't have to depend on this.

### CODE REVIEW

File: numpy/core/src/common/get_attr_string.h [hunk 1]
```diff
@@ -39,6 +39,14 @@ _is_basic_python_type(PyTypeObject *tp)
     );
 }
 
+static NPY_INLINE void
+clear_exception(PyObject *exception)
+{
+    if (PyErr_Occurred() && PyErr_ExceptionMatches(exception)) {
```
Comment (eric-wieser) [inline numpy/core/src/common/get_attr_string.h]: Doesn't `PyErr_ExceptionMatches` already contain a check for `PyErr_Occurred`?

Comment (keewis) [reply numpy/core/src/common/get_attr_string.h]: I'm not sure. Reading the [docs](https://docs.python.org/3/c-api/exceptions.html#c.PyErr_ExceptionMatches), it seemed to me that the check is necessary.

File: numpy/core/src/common/get_attr_string.h [hunk 2]
```diff
@@ -63,7 +71,7 @@ maybe_get_attr(PyObject *obj, char *name)
     if (tp->tp_getattr != NULL) {
         res = (*tp->tp_getattr)(obj, name);
         if (res == NULL) {
```
Comment (eric-wieser) [inline numpy/core/src/common/get_attr_string.h]: nit: tempting to skip the new  function, and just add `&& PyErr_ExceptionMatches(PyExc_AttributeError)` to this `if` and the one below.

Comment (keewis) [reply numpy/core/src/common/get_attr_string.h]: I did the change, but the issue regarding `PyErr_ExceptionMatches` still remains.

**Comment by keewis** [comment]
the CI complains about me using the `"ignore"` filter, but I believe that is this case that filter is justified. What do I do to make the tests pass?

File: numpy/core/src/multiarray/ctors.c [hunk 3]
```diff
@@ -2351,7 +2351,11 @@ PyArray_FromStructInterface(PyObject *input)
 
     attr = PyArray_LookupSpecial_OnInstance(input, "__array_struct__");
     if (attr == NULL) {
-        return Py_NotImplemented;
+        if (PyErr_Occurred()) {
+            return NULL;
+        } else {
+            return Py_NotImplemented;
+        }
```
Comment (mattip) [inline numpy/core/src/multiarray/ctors.c]: Why don't you need to now change all the places `PyArray_LookupSpecial_OnInstance` and `PyArray_LookupSpecial_OnInstance` are called to check for errors?

File: numpy/core/src/common/get_attr_string.h (hunk 1 above)
Comment (eric-wieser) [reply numpy/core/src/common/get_attr_string.h]: You're right, the docs are pretty clear about that.

Comment (eric-wieser) [reply numpy/core/src/common/get_attr_string.h]: Ah, but tp_getattr isn't allowed to return null without setting an error, is it?

Comment (keewis) [reply numpy/core/src/common/get_attr_string.h]: well, `tp_getattr`seems to be deprecated, but [`tp_getattro`](https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_getattro)  is by default set to [`PyObject_GenericGetAttr()`](https://docs.python.org/3/c-api/object.html#c.PyObject_GenericGetAttr), which indeed raises an `AttributeError` on failure (but [`PyObject_GetAttr()`](https://docs.python.org/3/c-api/object.html#c.PyObject_GetAttr) does not mention raising). Without the `PyErr_Occurred` check the tests don't seem to fail, but that may be risky, especially if a custom function was put there (though I don't know how much of a risk). Ultimately it's not my call, I would be fine with either

File: numpy/core/src/multiarray/ctors.c (hunk 3 above)
Comment (keewis) [reply numpy/core/src/multiarray/ctors.c]: I don't know. This change was enough to make my tests pass, so I stopped with this. If you would like me to also change this for every other code path, I would need examples for triggering these paths to verify that my changes actually do something.

File: numpy/core/src/common/get_attr_string.h (hunk 1 above)
Comment (eric-wieser) [reply numpy/core/src/common/get_attr_string.h]: Doesn't look risky to me. _"`NULL` on failure`"_ means "with an exception set". If an exception weren't set, that would be noted explicitly (as it's very uncommon).

Comment (keewis) [reply numpy/core/src/common/get_attr_string.h]: So I should remove the check?

File: numpy/core/src/common/get_attr_string.h [hunk 4]
```diff
@@ -62,7 +62,7 @@ maybe_get_attr(PyObject *obj, char *name)
     /* Attribute referenced by (char *)name */
     if (tp->tp_getattr != NULL) {
         res = (*tp->tp_getattr)(obj, name);
-        if (res == NULL) {
+        if (res == NULL && PyErr_ExceptionMatches(PyExc_AttributeError)) {
             PyErr_Clear();
```
Comment (eric-wieser) [inline numpy/core/src/common/get_attr_string.h]: The comments on line 45-48 aren't really accurate any more

Comment (keewis) [reply numpy/core/src/common/get_attr_string.h]: what would I write instead? What is there right now is
> Stripped down version of PyObject_GetAttrString,  avoids lookups for None, tuple, and List objects, and doesn't create a PyErr since this code ignores it.
>
> This can be much faster then PyObject_GetAttrString where exceptions are not used by caller.

It still does not create a PyErr (directly, that is), but if `obj` raises something in either `__getattr__` or `__getattribute__` that is not an `AttributeError`, it gets passed through.

Also, I don't understand the second part because `PyObject_GetAttrString` may be referenced by `tp->tp_getattr` (if that is set – which it normally is not, so `tp->tp_getattro` and `PyObject_GenericGetAttr` are used). My understanding of python's C-API is limited though, so I may be wrong.

Comment (eric-wieser) [reply numpy/core/src/common/get_attr_string.h]: I went ahead and updated the comment myself

File: numpy/core/src/multiarray/ctors.c (hunk 3 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/ctors.c]: Unfortunately we do now need to change every call site to either handle it or call `PyErr_Clear()`, else you risk a `SystemError` occurring.

Comment (eric-wieser) [reply numpy/core/src/multiarray/ctors.c]: In the interest of speed, I suggest you:
* Create a new tracking issue, "propagate errors where appropriate from PyArray_LookupSpecial"
* Find every occurence of `PyArray_LookupSpecial` and `PyArray_LookupSpecial_OnInstance`, and in the `if (ret == NULL)` branch, add `PyErr_Clear();  // TODO[gh-XYZ]: propagate this?

Comment (keewis) [reply numpy/core/src/multiarray/ctors.c]: done, see #14801.

Could you look over the changes in `binop_override.h` and `arrayfunction_override.c`? I'm not sure about those, especially the change from `if (attr)` to `if (attr != NULL)`.

**Comment by keewis** [comment]
unless there are others, the only issue left is where to put the tests

File: numpy/core/src/multiarray/common.c [hunk 5]
```diff
@@ -419,6 +426,9 @@ PyArray_DTypeFromObjectHelper(PyObject *obj, int maxdims,
             goto fail;
         }
     }
+    else {
+        PyErr_Clear(); // TODO[GH14801]: propagate this?
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/common.c]:
```suggestion
        PyErr_Clear();  /* TODO[gh-14801]: propagate this if PyErr_Occured()? */
```

and all the others

File: numpy/core/src/multiarray/ctors.c (hunk 3 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/ctors.c]: Those changes are fine, thanks for checking. I think we could make the comments a little less cryptic, see my new comment thread below, marking this one as resolved.

File: numpy/core/src/multiarray/common.c (hunk 5 above)
Comment (keewis) [reply numpy/core/src/multiarray/common.c]: is this what you suggested?

**Review by eric-wieser — APPROVED** [review]
Looks great, thanks!

Will leave @mattip to sign off on pushing all the further decisions to gh-14801

File: numpy/core/src/multiarray/arrayfunction_override.c [hunk 6]
```diff
@@ -26,6 +26,7 @@ static PyObject *
 get_array_function(PyObject *obj)
 {
     static PyObject *ndarray_array_function = NULL;
+    static PyObject *array_function;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/arrayfunction_override.c]: This should not be static
```suggestion
    PyObject *array_function;
```

**Review by eric-wieser — CHANGES_REQUESTED** [review]

File: numpy/core/src/multiarray/arrayfunction_override.c (hunk 6 above)
Comment (keewis) [reply numpy/core/src/multiarray/arrayfunction_override.c]: sorry, I don't know too much about C, so I just copied the declaration of `ndarray_array_function`

Comment (eric-wieser) [reply numpy/core/src/multiarray/arrayfunction_override.c]: `static` means the variable is at a single location in memory, meaning that if multiple threads call this function at the same time, they can clobber each other. Python's Global Interpreter lock might mean this can't actually happen, but better safe than sorry. Thanks for the fix!

**Review by eric-wieser — APPROVED** [review]

**Comment by mattip** [comment]
Thanks @keewis
