### PR TITLE
MAINT: Refactor _new_sortlike and _new_argsortlike

### LINKED ISSUE #5441: BUG: Wrong sorting of byte-swapped complex arrays
A minimal (not)working example:

```
>>> a = np.array([1+3.j, 2+2.j, 3+1.j], dtype='<D')  # this is native on my system
>>> a.argsort()
array([0, 1, 2])
>>> a.sort()
>>> a
 array([ 1.+3.j,  2.+2.j,  3.+1.j])

>>> b = np.array([1+3.j, 2+2.j, 3+1.j], dtype='>D')  $ this is byteswapped
>>> b.argsort()
array([2, 1, 0])
>>> b.sort()
>>> b
array([ 3.+1.j,  2.+2.j,  1.+3.j])
```

The problem is in `_new_argsortlike` and `_new_sortlike` in `item_selection.c`: when the array is byteswapped, it is copied and swapped into a temporary buffer, but rather than using the `dtype`'s `copyswapn` function, this is implemented with some generic code that calls `_unaligned_strided_byte_copy` and `_strided_byte_swap` directly based on the `dtype`'s `elsize`. For complex arrays, byte-swapping therefore results in reversing both the real and imaginary part as a whole, i.e. it fixes the byte ordering, but swaps the real and imaginary parts.

This is very easy to fix, as mentioned above, by calling the `dtype`'s `copyswapn` function directly, thus letting it handle the internal structure of the dtype.

I found this out while working on an ambitious refactor of the sorting functionality, trying to get rid of the ugly global storage used in generic comparisons. If I cannot wrap the whole thing up in a couple of weeks, I'll submit a PR fixing this only, opened the issue mostly as a note to self.

### PR DESCRIPTION
**Pull request by jaimefrio**
Simplify the signature of both functions, remove code duplication
inside, add proper handling of byte-swapping for compound dtypes
(like complex, fixes #5441), and add functionality to deal with
dtypes containing Python object references. This last enhancement is
not needed for this PR, but supports subsequent ones.

### CODE REVIEW

**Comment by jaimefrio** [comment]
There are at least two or three more large commits to complete this:

1. Create npy_aquicksort, npy_amergesort and npy_aheapsort functions in npy_sort, and modify PyArray_ArgSort and PyArray_ArgPartition to always call _new_argsortlike, passing these functions in needed.
2. Modify npy_quicksort, npy_mergesort and npy_heapsort functions in npy_sort, and modify PyArray_Sort and PyArray_Partition to always call _new_sortlike, passing these functions if needed.
3. Add a comprehensive set of tests checking all combinations of contiguous/non-contiguous, swapped/not-swapped, with ref/without refs are properly sorted, argsorted, partitioned and argpartitioned.

They could be made separately as different PRs, or added as new commits to this same PR, you get to choose.

**Comment by njsmith** [comment]
I'm kinda busy running around like a chicken with its head cut off for
the next few weeks, so I probably won't review in any detail, but
multiple PRs is usually a good approach!

On Sat, Jan 17, 2015 at 12:17 AM, Jaime <notifications@github.com> wrote:
> There are at least two or three more large commits to complete this:
>
> Create npy_aquicksort, npy_amergesort and npy_aheapsort functions in
> npy_sort, and modify PyArray_ArgSort and PyArray_ArgPartition to always call
> _new_argsortlike, passing these functions in needed.
> Modify npy_quicksort, npy_mergesort and npy_heapsort functions in npy_sort,
> and modify PyArray_Sort and PyArray_Partition to always call _new_sortlike,
> passing these functions if needed.
> Add a comprehensive set of tests checking all combinations of
> contiguous/non-contiguous, swapped/not-swapped, with ref/without refs are
> properly sorted, argsorted, partitioned and argpartitioned.
>
> They could be made separately as different PRs, or added as new commits to
> this same PR, you get to choose.
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Nathaniel J. Smith
Postdoctoral researcher - Informatics - University of Edinburgh
http://vorpus.org

File: numpy/core/src/multiarray/item_selection.c [hunk 1]
```diff
@@ -787,255 +787,287 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
...
-        while (size--) {
-            if (part == NULL) {
-                if (sort(it->dataptr, N, op) < 0) {
+        else {
+            npy_intp pivots[NPY_MAX_PIVOT_STACK];
+            npy_intp npiv = 0;
+            npy_intp i;
+            for (i = 0; i < nkth; ++i) {
+                ret = part(bufptr, N, kth[i], pivots, &npiv, op);
+                if (ret < 0 || (hasrefs && PyErr_Occurred())) {
```
Comment (jaimefrio) [inline numpy/core/src/multiarray/item_selection.c]: This line probably deserves some explaining... The way `dtype->f->compare` is set up for object dtype's, under Python3, when comparing two uncomparable objects it returns a 0, i.e. considers them to be equal, so in principle the sorting continues all the way, although the result will be crap. So after sorting each 1D array, if our type has refs and hence the GIL has not been released, we check whether an error was raised, and return early if it is the case.

File: numpy/core/src/multiarray/item_selection.c [hunk 2]
```diff
@@ -787,255 +787,287 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
...
-                    }
-                }
+                copyswapn(buffer, elsize, it->dataptr, astride, N, swap, op);
             }
-            if (swap) {
-                _strided_byte_swap(buffer, (npy_intp) elsize, N, elsize);
+            bufptr = buffer;
+        }
+        else if (swap) {
+            /* If the array is swapped but contiguous, unswap in-place */
```
Comment (jaimefrio) [inline numpy/core/src/multiarray/item_selection.c]: Hmmm... I just realized this optimization could leave a contiguous, swapped array, unwapped if there was an error in the sorting routine, which is not good, will push a new commit to fix it.

**Comment by jaimefrio** [comment]
OK, I fixed the failing stuff, this should be ready for review now.

File: numpy/core/src/multiarray/item_selection.c [hunk 3]
```diff
@@ -787,255 +787,303 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
...
+         * rather than after copying to the buffer. Care would have to
+         * be taken to ensure that, if there is an error in the call to
+         * sort or part, the unswapping is still done before returning.
+         */
+
+        if (part == NULL) {
+            ret = sort(bufptr, N, op);
+            #if defined(NPY_PY3K)
+            /* Object comparisons may raise an exception in Python 3 */
+            if (hasrefs && PyErr_Occurred()) {
```
Comment (juliantaylor) [inline numpy/core/src/multiarray/item_selection.c]: NPY_PY3K could be put into the if ()
also preprocessor code is usually not indented

File: numpy/core/src/multiarray/item_selection.c [hunk 4]
```diff
@@ -787,255 +787,303 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
...
+                 * an unitialized valbuffer, or leak a reference to
+                 * each object item if initialized.
+                 *
+                 * So, first do the copy with no refcounting...
+                 */
+                 _unaligned_strided_byte_copy(valbuffer, elsize,
+                                              it->dataptr, astride, N, elsize);
+                /* ...then swap in-place if needed */
+                if (swap) {
+                    copyswapn(valbuffer, elsize, NULL, 0, N, swap, op);
```
Comment (juliantaylor) [inline numpy/core/src/multiarray/item_selection.c]: this block is the same as in sortlike, could be moved into a small function

**Comment by juliantaylor** [comment]
looks good with some minor style suggestions

File: numpy/core/src/multiarray/item_selection.c (hunk 4 above)
Comment (jaimefrio) [inline numpy/core/src/multiarray/item_selection.c]: I thought of it, but it would be a function with 9 or 10 parameters, unless we want to extract `hasrefs`, `copyswapn`, `elsize` and `swap` from `op` in each iteration.

File: numpy/core/src/multiarray/item_selection.c (hunk 3 above)
Comment (juliantaylor) [inline numpy/core/src/multiarray/item_selection.c]: hm its probably not defined in python2, nevermind then

File: numpy/core/src/multiarray/item_selection.c (hunk 4 above)
Comment (juliantaylor) [inline numpy/core/src/multiarray/item_selection.c]: hm right probably too many arguments for little code saved

File: numpy/core/src/multiarray/item_selection.c (hunk 3 above)
Comment (juliantaylor) [inline numpy/core/src/multiarray/item_selection.c]: or one could do a #if !PY3K #define PY3K 0, add three lines to remove 4 ;)
the indentation should be fixed regardless I think

**Comment by jaimefrio** [comment]
Ok, changed the indentatntion of the `#if`s, which I believe is what we settled on having to be changed.

**Comment by juliantaylor** [comment]
alright, merging thanks
