### PR TITLE
BUG: Add cpp atomic support

### LINKED ISSUE #28106: Building NumPy from source for Windows on ARM using Clang-cl compiler
Hello Developers,

- I am facing an issue while trying to build NumPy for Windows on ARM (WoA) using the Clang-cl compiler. Building NumPy from source requires C and C++ compilers with proper intrinsic support.
- Previously, I was able to successfully compile NumPy for WoA using the MSVC-optimized C/C++ CL compiler, enabling CPU baseline features that support ARM. 
- However, I encountered limitations with the MSVC C/C++ CL compiler, as it does not support certain CPU dispatcher features like ASIMDHP, ASIMDFHM, and SVE. Is there any specific reason why these CPU dispatch features are not supported for WoA in MSVC?
- Meanwhile, I attempted to compile NumPy for WoA using the clang-cl compiler (both from MSVC and LLVM toolchains) to check if the CPU dispatcher features would be enabled. While I found that, apart from SVE, all other test features—including baseline features—were supported, I ran into compilation errors due to unidentified instructions.

Steps to Reproduce

1. Clone the Source code of NumPy and checkout to latest branch
2. Install LLVM toolchain/MSVC clang toolset 
3. Remove the clang and clang++ from the bin directory to avoid conflicts 
4. Add the bin path at the top of environment path variable

Compilers used for compilation:
image

Error and Workaround:

1. While building meson_cpu target, got an error with respect to invalid operand "fstcw" in multiarray_tests_c source file. Upon going through source code, the fstcw is floating-point control instructions for x86 assembly. So I made workaround to make one more condition to check whether it is a ARM64 arch build. Then the build proceeded:
Screenshot 2025-01-06 123245
Workaround:
before:
image
After:
image

Issue:

1. Currently the build fails at 240+ targets while compiling meson_cpu due to unidentified assembly instructions:
image

Can anyone give some suggestions to overcome this issue? I need enable CPU dispatch support for NumPy on WoA to get better optimised version of NumPy.

Thanks!

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes #28106

This builds and passes the test on my Mac but let's see what the full CI says.

The code I'm adding is cribbed from CPython's `pyatomic.h` and `pyatomic_std.h`.

### CODE REVIEW

File: numpy/_core/src/common/npy_atomic.h [hunk 1]
```diff
@@ -9,11 +9,19 @@
...
+#ifdef __cplusplus
+    extern "C++" {
+        #include <atomic>
+    }
+    #define _NPY_USING_STD using namespace std
+    #define _Atomic(tp) atomic<tp>
+    #define STDC_ATOMICS
+#elif defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L \
     && !defined(__STDC_NO_ATOMICS__)
 // TODO: support C++ atomics as well if this header is ever needed in C++
```
Comment (ngoldbaum) [inline numpy/_core/src/common/npy_atomic.h:21]:
```suggestion
```

**Comment by charris** [comment]
Should we backport this?

**Comment by matthew-brett** [comment]
Nice - thanks! - with the fix at https://github.com/numpy/numpy/pull/28235, this allows the Numpy build to work without failure on WoA.

**Comment by ngoldbaum** [comment]
I think this should be safe to backport. I'd also like someone participating in the attached issue to test this on a WoA machine before merging this.

**Comment by charris** [comment]
Thanks Nathan.
