### PR TITLE
BUG: fix race initializing legacy dtype casts

### LINKED ISSUE #28048: BUG: Race adding legacy casts to custom dtype under free threading
### Describe the issue:

If the following code is run under Python 3.13.1t, it fails nondeterministically with `A cast was already added for <class 'numpy.dtype[bfloat16]'> -> <class 'numpy.dtypes.UInt8DType'>. (method: legacy_cast)`.

Note: `bfloat16` comes from https://github.com/jax-ml/ml_dtypes. To install `ml_dtypes`, check out the ml_dtypes source and use `python install .`. The current 313t wheel of `ml_dtypes` on pypi appears to be slightly broken (https://github.com/jax-ml/ml_dtypes/issues/245).

### Reproduce the code example:

```python
import concurrent.futures
import functools
import threading
import numpy as np
import ml_dtypes

num_threads = 10


def closure(b):
  b.wait()
  for _ in range(100):
    np.full((10, 10), 1, ml_dtypes.bfloat16)

with concurrent.futures.ThreadPoolExecutor(max_workers=num_threads) as executor:
  for i in range(100):
    b = threading.Barrier(num_threads)
    for _ in range(num_threads):
      executor.submit(functools.partial(closure, b))
```

### Error message:

```shell
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/google/home/phawkins/p/tsanvenv/lib/python3.13t/site-packages/numpy/_core/numeric.py", line 353, in full
  File "/usr/local/google/home/phawkins/p/tsanvenv/lib/python3.13t/site-packages/numpy/_core/numeric.py", line 353, in full
    multiarray.copyto(a, fill_value, casting='unsafe')
RuntimeError: A cast was already added for <class 'numpy.dtype[bfloat16]'> -> <class 'numpy.dtypes.UInt8DType'>. (method: legacy_cast)
    multiarray.copyto(a, fill_value, casting='unsafe')
RuntimeError: A cast was already added for <class 'numpy.dtype[bfloat16]'> -> <class 'numpy.dtypes.UInt8DType'>. (method: legacy_cast)
```

### Python and NumPy Versions:

2.3.0.dev0+git20241219.35b2c4a
3.13.1 experimental free-threading build (tags/v3.13.1:06714517797, Dec 15 2024, 15:38:01) [Clang 18.1.8 (11)]

### Runtime Environment:

[{'numpy_version': '2.3.0.dev0+git20241219.35b2c4a',
'python': '3.13.1 experimental free-threading build '
'(tags/v3.13.1:06714517797, Dec 15 2024, 15:38:01) [Clang 18.1.8 '
'(11)]',
'uname': uname_result(system='Linux', node='', release='', version='https://github.com/https://github.com/numpy/numpy/pull/1 SMP PREEMPT_DYNAMIC Debian 6.redacted (2024-10-16)', machine='x86_64')},
{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
'found': ['SSSE3',
'SSE41',
'POPCNT',
'SSE42',
'AVX',
'F16C',
'FMA3',
'AVX2'],
'not_found': ['AVX512F',
'AVX512CD',
'AVX512_KNL',
'AVX512_SKX',
'AVX512_CLX',
'AVX512_CNL',
'AVX512_ICL']}},
{'architecture': 'Zen',
'filepath': '/usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.27.so',
'internal_api': 'openblas',
'num_threads': 128,
'prefix': 'libopenblas',
'threading_layer': 'pthreads',
'user_api': 'blas',
'version': '0.3.27'}]

### Context for the issue:

Found when working on free-threading support in JAX.

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes #28048 

Locks `castingimpls` with a critical section when the `castingimpls` cache is empty before writing to the dict.

Because the critical section macros have braces, I refactored `PyArray_GetCastingImpl` into three functions that call each other. Only the "middle" function needs the critical section, so that reduces the pain of not being able to early return in a critical section a little bit.

I also added some comments because this took me quite a while to fully understand so future readers will hopefully be less confused.

Edit: there are also some unrelated fixes for the test infrastructure to avoid CI crashes and generate better debug output from CI jobs. Happy to do those separately if anyone requests.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
This is decently complicated but I added the backport candidate label because I think this only risky for the free-threaded build and it fixes an annoying Jax runtime crash that they can't really do anything about.

File: numpy/_core/src/multiarray/convert_datatype.c [hunk 1]
```diff
@@ -125,43 +103,104 @@ PyArray_GetCastingImpl(PyArray_DTypeMeta *from, PyArray_DTypeMeta *to)
             PyArray_VectorUnaryFunc *castfunc = PyArray_GetCastFunc(
                     from->singleton, to->type_num);
             if (castfunc == NULL) {
-                PyErr_Clear();
-                /* Remember that this cast is not possible */
-                if (PyDict_SetItem(NPY_DT_SLOTS(from)->castingimpls,
-                            (PyObject *) to, Py_None) < 0) {
-                    return NULL;
-                }
```
Comment (ngoldbaum) [inline numpy/_core/src/multiarray/convert_datatype.c:133]: `None` gets inserted into to castingimpls later on before exiting the critical section so there's no need to do it here

File: numpy/_core/src/multiarray/convert_datatype.c [hunk 2]
```diff
@@ -2021,6 +2060,11 @@ PyArray_AddCastingImplementation(PyBoundArrayMethodObject *meth)
 /**
  * Add a new casting implementation using a PyArrayMethod_Spec.
  *
+ * Using this function outside of module initialization without holding a
+ * critical section on the castingimpls dict may lead to a race to fill the
+ * dict. Use PyArray_GetGastingImpl to lazily register casts at runtime
+ * safely.
```
Comment (ngoldbaum) [inline numpy/_core/src/multiarray/convert_datatype.c:2066]: I manually verified that this function is only used during module initialization or inside the critical section I added in this PR

**Comment by ngoldbaum** [comment]
Looks like the 32 bit Windows failure is real 🙃, I'll convert this to draft while I fix CI...

**Comment by ngoldbaum** [comment]
Pushed a fix that should make ASAN and TSAN CI output more helpful. Also, yay, TSAN CI found a race condition!

**Comment by ngoldbaum** [comment]
Not sure why the 32 bit runners are unhappy, will have to come back to this.

**Comment by ngoldbaum** [comment]
It turns out the hangs and crashes on 32-bit runners were because of memory exhaustion, I think the latest push should pass all the CI.

File: numpy/_core/src/multiarray/convert_datatype.c [hunk 3]
```diff
@@ -125,43 +103,107 @@ PyArray_GetCastingImpl(PyArray_DTypeMeta *from, PyArray_DTypeMeta *to)
...
+    Py_END_CRITICAL_SECTION();
+    if (return_error) {
+        Py_XDECREF(res);
         return NULL;
     }
-    if (from == to) {
+    if (from == to && res == Py_None) {
         PyErr_Format(PyExc_RuntimeError,
                 "Internal NumPy error, within-DType cast missing for %S!", from);
-        Py_DECREF(res);
```
Comment (ngoldbaum) [inline numpy/_core/src/multiarray/convert_datatype.c:156]: Oops, this shouldn't have been deleted

**Comment by ngoldbaum** [comment]
> were because of memory exhaustion

Not quite right. 

At some arbitrary thread count that depends on the precise details of the memory allocation patterns of threads, Python will raise a runtime error saying that it can't spawn any more threads when you ask it to spawn a thread. Normally the exception to bubble up properly but the exception coming from `ThreadPoolExecutor.submit` triggered a latent deadlock bug in the implementation of `run_threaded`. Since the exception case didn't cancel the `threading.Barrier()`, the threads that did manage to get started hit the barrier and then hang.

The fix is to put the call to `ThreadPoolExecutor.submit` inside a `try/except` block that catches *all* exceptions and calls `barrier.abort()`. This makes sure the barrier is canceled and avoids the deadlock.

File: numpy/testing/_private/utils.py [hunk 4]
```diff
@@ -2734,9 +2734,16 @@ def run_threaded(func, max_workers=8, pass_count=False,
...
             if pass_count:
-                futures = [tpe.submit(func, i, *args) for i in range(max_workers)]
+                all_func_args = [(func, i, *args) for i in range(max_workers)]
             else:
-                futures = [tpe.submit(func, *args) for _ in range(max_workers)]
+                all_func_args = [(func, *args) for i in range(max_workers)]
+            try:
+                futures = [tpe.submit(*func_args) for func_args in
+                           all_func_args]
+            except BaseException:
```
Comment (ngoldbaum) [inline numpy/testing/_private/utils.py:2743]: On second though, `finally` is probably what I want

File: numpy/_core/src/multiarray/convert_datatype.c [hunk 5]
```diff
@@ -125,43 +103,108 @@ PyArray_GetCastingImpl(PyArray_DTypeMeta *from, PyArray_DTypeMeta *to)
...
                     from->singleton, to->type_num);
             if (castfunc == NULL) {
-                PyErr_Clear();
-                /* Remember that this cast is not possible */
-                if (PyDict_SetItem(NPY_DT_SLOTS(from)->castingimpls,
-                            (PyObject *) to, Py_None) < 0) {
-                    return NULL;
-                }
-                Py_RETURN_NONE;
+                    PyErr_Clear();
```
Comment (mhvk) [inline numpy/_core/src/multiarray/convert_datatype.c:106]: indentation now funny.

**Review by mhvk — COMMENTED** [review]
Not sure I can review this properly, but it looks good.

File: .github/workflows/compiler_sanitizers.yml [hunk 6]
```diff
@@ -111,6 +113,8 @@ jobs:
         pip install -r requirements/build_requirements.txt
         pip install -r requirements/ci_requirements.txt
         pip install -r requirements/test_requirements.txt
+        # xdist captures stdout/stderr, but we want the TSAN output
+        pip uninstall -y pytest-xdist
```
Comment (seberg) [inline .github/workflows/compiler_sanitizers.yml:117]: Didn't know xdist kicks in without `-n`, but seems good.

File: numpy/_core/src/multiarray/convert_datatype.c [hunk 7]
```diff
@@ -126,42 +104,107 @@ PyArray_GetCastingImpl(PyArray_DTypeMeta *from, PyArray_DTypeMeta *to)
...
+    if (res == NULL && !return_error) {
+        res = create_casting_impl(from, to);
+        if (res == NULL) {
+            return_error = 1;
+        }
+    }
+    if (!return_error &&
+        PyDict_SetItem(NPY_DT_SLOTS(from)->castingimpls,
+                       (PyObject *)to, res) < 0) {
+        return_error = 1;
```
Comment (seberg) [inline numpy/_core/src/multiarray/convert_datatype.c:164]: I think it would be slightly nicer to keep this inside the `res == NULL` branch (if it isn't we don't need to set it again).

The first if could go into an `else if (res == NULL)` (that includes this).
If you are than OK with using `Py_CLEAR(res)` on this line, you can delete `return_error` (with the funny thing that the first `if` does nothing).

To me that would look nicer, I think, but happy to keep this.

File: numpy/_core/src/multiarray/convert_datatype.c (hunk 2 above)
Comment (seberg) [reply numpy/_core/src/multiarray/convert_datatype.c:2070]: Thanks for checking.  I guess we are fine as long as we enforce that casts from/to a new DType must be registered at the DType creation.  (which is the enforced right now, since this is not public API)

File: numpy/testing/_private/utils.py [hunk 8]
```diff
@@ -2734,9 +2734,18 @@ def run_threaded(func, max_workers=8, pass_count=False,
...
+                all_args = [(func, *args) for i in range(max_workers)]
+            try:
+                n_submitted = 0
+                futures = []
+                for arg in all_args:
+                    futures.append(tpe.submit(*arg))
+                    n_submitted += 1
+            finally:
+                if n_submitted < max_workers and pass_barrier:
+                    barrier.abort()
```
Comment (seberg) [inline numpy/testing/_private/utils.py:2748]: I think this may be clearer to write as:
```
except:  # or BaseExecption if you prefer
    if pass_barrier:
        barrier.abort()
    raise
```
and avoid counting the `n_submitted` above.

**Review by seberg — APPROVED** [review]
Thanks Natahn!  LGTM.  The only behavior change, might be that we init the within castingimpl immediately now.  That seems OK.

If this is annoying someone in practice, I am OK with backporting this.

I left two comments about code cleanup, but I don't feel strongly about them.

File: numpy/testing/_private/utils.py (hunk 8 above)
Comment (ngoldbaum) [reply numpy/testing/_private/utils.py:2748]: > (but maybe I missed a subtlety?)

bare `except:` and `except BaseException` is the sort of thing that linters mark as a code smell or a naive reader in the future would replace with `except Exception` (which is wrong). I like`try/finally` because it matches the intention and uses a language feature that linters won't flag.

I can get rid of `n_submitted` and just check `len(futures)` though.

File: numpy/_core/src/multiarray/convert_datatype.c (hunk 7 above)
Comment (ngoldbaum) [reply numpy/_core/src/multiarray/convert_datatype.c]: Thanks, it is better to use `else if` if you can't early return. I'd rather keep the `return_error` since it makes things a little more explicit in the weird coding style you have to use inside critical sections.

**Comment by ngoldbaum** [comment]
Looks like all the CI failures are unrelated network issues.
