### PR TITLE
MAINT: add overlap checks to choose, take, put, putmask

### LINKED ISSUE #9293: Wrong output in take function
I encountered an error when i use the numpy.take function. 
test : 2D array (20000x128) with double values
P: integer vector 128 values in the range of [0...127] none are the same.
if i execute the following code everything works fine and as intended, no error.
`np.take(test, P, axis=1, mode='raise', out=test)`

if i execute
` np.take(test, P, axis=1, mode='wrap', out=test) ` 
 my output should be the same as in the other code, since i do not have any out-of-bounds indices. However, the output is different. Values are scrambled and appear multiple times although they are all different.  

if executed as `test =  np.take(test, P, axis=1, mode='wrap') ` the output is correct. 

same for: mode = 'clip'

numpy version 1.12.1
python version 2.7.13

### PR DESCRIPTION
**Pull request by ahaldane**
Fixes #9293, #6272 

This adds the overlap checks as suggested in  #6272 to `np.choose`, `np.take`, `np.put`, and `np.putmask`.

It is arguable whether or not this "fixes" #6272, since there are potentially more places overlap checks are needed, in particular in inplace operations. But at the very least this PR completes the checks listed by @seberg in #6272.

(Incidentally, I don't like that we always make a copy for `mode='raise'` in `np.take/put`. It defeats the point of having an `out` argument, which is to get no-copy performance!)

### CODE REVIEW

**Comment by mattip** [comment]
LGTM. 
Is `out` so rarely used with overlap that this issue was never reported by a user?

> Incidentally, I don't like that we always make a copy for mode='raise' in np.take/put. It defeats the point of having an out argument, which is to get no-copy performance!

Is there an open `ENH` issue for this?

**Comment by seberg** [comment]
The problem with "raise" is that it leaves the output array mutated when an error occurs (but not on the first index). So changing it could be seen as introducing a small issue itself.

Advanced indexing assignment currently has similar issues but will simply allow for such mutation, which is not really ideal in a sense (many paths will check the index first, but not all do IIRC, have to check).

File: numpy/core/src/multiarray/item_selection.c [hunk 1]
```diff
@@ -712,6 +727,14 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
                             "choose: invalid shape for output array.");
             goto fail;
         }
+
```
Comment (seberg) [inline numpy/core/src/multiarray/item_selection.c]: NIT: Extra empty line.

File: numpy/core/tests/test_multiarray.py [hunk 2]
```diff
@@ -4425,6 +4440,11 @@ def test_record_array(self):
         rec1 = rec.take([1])
         assert_(rec1['x'] == 5.0 and rec1['y'] == 4.0)
 
+    def test_out_overlap(self):
+        # gh-6272 check overlap on out
+        x = np.arange(5)
+        y = np.take(x, [1,2,3], out=x[2:5], mode='wrap')
+        assert_equal(y, np.array([1,2,3]))
```
Comment (seberg) [inline numpy/core/tests/test_multiarray.py]: NIT: spaces after comma.

**Review by seberg — APPROVED** [review]
Looks good to me as well. Could be merged as is, but maybe we should add a short release note in any case.

**Comment by ahaldane** [comment]
Fixed. I also tweaked the `np.take` and `np.choose` to clarify that `out` gives no performance benefit when `clip='raise'`.

Also, I notice in `np.put` that the logic for `clip='raise'` buffering is a no-op. That is, it looks like the intention was to make `np.put` buffer if `clip='raise'`, but the clause was inside an if-block that only runs if the input was non-contiguous, so in effect `np.put` usually runs unbuffered and will clobber the input even on exception.

That code should be cleaned up. My suggestion is to just remove the `clip='raise'` test and run unbuffered, even though that's a little inconsistent what `np.take` and `np.choose`. The major alternative is to make it buffer for `mode='raise'` but add a note in the docstring about it. Thoughts?

**Comment by seberg** [comment]
Hmm, can't say I care much which way we go on that function, both sounds fine to me (or even just leaving it, heh). For similarity with those other functions, I think I would tend slightly towards doing the copy, but contiguous input is probably the most common, so going the other way should actually be the smaller change.
But maybe my enthusiasm on these functions is a bit low anyway ;), I always think of them as solving what indexing already solves.

**Comment by seberg** [comment]
Thanks, I see, you fixed the documentation, sounds good to me. If nobody else has a comment, I will merge it tomorrow or so.

**Comment by seberg** [comment]
I guess this was ready to go in. Thanks Allan!
