### PR TITLE
BUG: Relax dtype identity check in reductions

### LINKED ISSUE #20699: BUG: possible problem with np.add.accumulate on 32-bit windows
### Describe the issue:

In astropy, there are several failures with numpy 1.22. Most seem related to precision issues, perhaps due to the intel short vector math library. Those we can fix. A very strange one is a failure on win32 only: https://github.com/astropy/astropy/runs/4680891863?check_suite_focus=true, with the most relevant bit being:
```
>                   raw_field[1:, 1] = (np.add.accumulate(raw_field[:-1, 0]) *
                                        dtype.itemsize)
E                   TypeError: the resolved dtypes are not compatible with add.accumulate. Resolved (dtype('int32'), dtype('int32'), dtype('int32'))
```
The crucial bit seems to be a call that should be the equivalent of (sorry, don't have a windows machine so cannot test directly...),
```
np.add.accumulate(np.arange(10, dtype='>i4'))
```
On linux, this does not give any errors, though I can get the same `TypeError` by passing in an explicit dtype,
```
np.add.accumulate(np.arange(10, dtype='>i4'), dtype=np.int32)
```
This same line does not give an error on numpy 1.21.5, so that suggests this problem has to do with the new ufunc/dtype machinery, perhaps doing a wrong inference of the dtype on win32? Hence, cc @seberg.

### Reproduce the code example:

```python
import numpy as np
np.add.accumulate(np.arange(10, dtype='>i4'))
```

### Error message:

_No response_

### NumPy/Python version information:

platform win32 -- Python 3.9.9
3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
Numpy: 1.22.0

### PR DESCRIPTION
**Pull request by seberg**
In some cases, e.g. ensure-native-byte-order will return not the
default, but a copy of the descriptor.

This (and maybe metadata) makes it somewhat annoying to ensure
exact identity between descriptors for reduce "operands" as
returned by the resolve-descirptors method of the ArrayMethod.

To avoid this problem, we check for no-casting (which implies
viewable with `offset == 0`) rather than strict identity.

Unfortunately, this means that descriptor resolution must be slightly
more careful, but in general this should all be perfectly well
defined.

Closes gh-20699

### CODE REVIEW

File: numpy/core/src/umath/ufunc_object.c [hunk 1]
```diff
@@ -2764,9 +2764,12 @@ reducelike_promote_and_resolve(PyUFuncObject *ufunc,
      * The first operand and output should be the same array, so they should
      * be identical.  The second argument can be different for reductions,
      * but is checked to be identical for accumulate and reduceat.
+     * Ideally, the type-resolver ensures that all are identical, but we do
+     * not enforce this here strictly.
```
Comment (mhvk) [inline numpy/core/src/umath/ufunc_object.c:2768]: I would add "strictly, since on windows this seems not to be guaranteed; see gh-20699"

**Review by mhvk — COMMENTED** [review]
This looks good, but also definitely needs a test case so that it doesn't recur!

**Comment by seberg** [comment]
I ran into an caching(?) issue during testing :/ will have to dig into that as well.

**Comment by seberg** [comment]
Well, that other issue is just that: another issue.

I added the test, arguably it is a bit of an indirect test, but at least it tests the most relevant and interesting error-path.

**Review by mhvk — APPROVED** [review]
Looks all good to me. Thanks, @seberg!

**Comment by mattip** [comment]
Thanks @seberg

**Comment by mattip** [comment]
After merging this to main, the debug test runs started segfaulting. @seberg any ideas?

https://github.com/numpy/numpy/actions/workflows/build_test.yml

**Comment by seberg** [comment]
Hummm, how come CI didn't notice that ahead of time?  It is an abort, so maybe likely be an assert gone wrong.

**Comment by seberg** [comment]
@charris, this one needs to be backported together with gh-20754 unfortunately.

**Comment by mhvk** [comment]
Just to note that this fixes another astropy issue, https://github.com/astropy/astropy/issues/12706. This one is in considerably more common code - @charris: would it be possible to do a relatively quick 1.22.1??

**Comment by seberg** [comment]
I think that would be fine, but there are one or two other issues and I was too distracted to make progress.  I was hoping I can fix both this week so we would be ready for a 1.22.1 at the end of the week or next.

But if it is much the same for Chuck, we can also just aim for a 1.22.2 soon after. IIRC the other issue was not found by anyone (but could be important!), and I don't really think we need to scramble about breaking numba (they just got 1.21 support recently).

**Comment by charris** [comment]
@mhvk I was planning on a rapid release. I'd like to see #20696 fixed, as well as several that @seberg is looking at, but we could push things a bit if they don't get fixed in a couple of days.

**Comment by mhvk** [comment]
OK, sounds good! It definitely doesn't hang on a week.
