### PR TITLE
BUG: Fix some multiarray leaks

### LINKED ISSUE #19287: Protential memory leak in function PyArray_CastScalarToCtype (a static analysis report)
### Reproducing code example:

**Static analysis results, no POC.**
This static analysis report has been manually reviewed, and I have tried my best to verify it.

### Error message:

The path provided by the static analyzer is as follows.

1. A new reference is returned from `PyArray_DescrFromScalar` and assigned to `descr` here.
https://github.com/numpy/numpy/blob/04ab04d93d4d7a4d241fe0ceb725436a8b6c8c2e/numpy/core/src/multiarray/scalarapi.c#L234

2. Function call to `PyArray_GetCastFunc` does not modify the reference count.
https://github.com/numpy/numpy/blob/04ab04d93d4d7a4d241fe0ceb725436a8b6c8c2e/numpy/core/src/multiarray/scalarapi.c#L235

3. Assume taking the true branch here.
https://github.com/numpy/numpy/blob/04ab04d93d4d7a4d241fe0ceb725436a8b6c8c2e/numpy/core/src/multiarray/scalarapi.c#L236

4. Function returned.
https://github.com/numpy/numpy/blob/04ab04d93d4d7a4d241fe0ceb725436a8b6c8c2e/numpy/core/src/multiarray/scalarapi.c#L237

5. The new reference pointed to by `descr` is not decreased on this path.

Similarly, the return on line 256 may also leave `descr` not decreased.
https://github.com/numpy/numpy/blob/04ab04d93d4d7a4d241fe0ceb725436a8b6c8c2e/numpy/core/src/multiarray/scalarapi.c#L256

### NumPy/Python version information:

Static analysis carried out on commit 04ab04d93.

### LINKED ISSUE #19288: Protential memory leak in function PyArray_DiscoverDTypeAndShape_Recursive (a static analysis report)
### Reproducing code example:

**Static analysis results, no POC.**
This static analysis report has been manually reviewed to verify its validity.

### Error message:

The path provided by the static analyzer is as follows.

1. A new reference is returned from `PySequence_Fast` and assigned to `seq` here.
https://github.com/numpy/numpy/blob/04ab04d93d4d7a4d241fe0ceb725436a8b6c8c2e/numpy/core/src/multiarray/array_coercion.c#L1075

2. Assume `seq` is not `NULL`, take the false branch.
https://github.com/numpy/numpy/blob/04ab04d93d4d7a4d241fe0ceb725436a8b6c8c2e/numpy/core/src/multiarray/array_coercion.c#L1076

3. Calling function `npy_new_coercion_cache`.
https://github.com/numpy/numpy/blob/04ab04d93d4d7a4d241fe0ceb725436a8b6c8c2e/numpy/core/src/multiarray/array_coercion.c#L1091

4. Assume `cache` is `NULL`.
https://github.com/numpy/numpy/blob/04ab04d93d4d7a4d241fe0ceb725436a8b6c8c2e/numpy/core/src/multiarray/array_coercion.c#L557

5. Returning from `npy_new_coercion_cache`.
https://github.com/numpy/numpy/blob/04ab04d93d4d7a4d241fe0ceb725436a8b6c8c2e/numpy/core/src/multiarray/array_coercion.c#L559

6. Return value is -1, take the true branch.
https://github.com/numpy/numpy/blob/04ab04d93d4d7a4d241fe0ceb725436a8b6c8c2e/numpy/core/src/multiarray/array_coercion.c#L1091

7. Returning from this function.
https://github.com/numpy/numpy/blob/04ab04d93d4d7a4d241fe0ceb725436a8b6c8c2e/numpy/core/src/multiarray/array_coercion.c#L1092

8. New reference pointed to be `seq` is leaked.

Similarly, the function call to `npy_new_coercion_cache` one line 987 may be the same case. Although, it is not reported by the analyzer.

### NumPy/Python version information:

Static analysis carried out on commit 04ab04d.

### LINKED ISSUE #19307: Protential memory leak in function PyInit__multiarray_umath (a static analysis report)
### Reproducing code example:

**Static analysis results, no POC.**
This static analysis report has been manually reviewed to verify its validity.

### Error message:

The path provided by the static analyzer is as follows.

1. Create module, a new reference is returned from `PyModule_Create` and pointed to by `m`
https://github.com/numpy/numpy/blob/04ab04d93d4d7a4d241fe0ceb725436a8b6c8c2e/numpy/core/src/multiarray/multiarraymodule.c#L4673

2. Goto `err` on error (apart from the first one where `m` is `NULL`). For example:
https://github.com/numpy/numpy/blob/04ab04d93d4d7a4d241fe0ceb725436a8b6c8c2e/numpy/core/src/multiarray/multiarraymodule.c#L4691

3. Returns `NULL` without decrease refcnt for `m`
https://github.com/numpy/numpy/blob/04ab04d93d4d7a4d241fe0ceb725436a8b6c8c2e/numpy/core/src/multiarray/multiarraymodule.c#L4910

### NumPy/Python version information:

Static analysis carried out on commit 04ab04d.

### PR DESCRIPTION
**Pull request by defoishugo**
Resolves #19307.
Resolves #19287.
Resolves #19288.

This merge request only adds some Py_(X)DECREF calls, so the reference count will be always decresed.
The reported cases where about very specific cases. There is no big leak, but it's always good to improve the general memory management.

### CODE REVIEW

File: numpy/core/src/multiarray/array_coercion.c [hunk 1]
```diff
@@ -1089,6 +1089,7 @@ PyArray_DiscoverDTypeAndShape_Recursive(
     }
     /* The cache takes ownership of the sequence here. */
     if (npy_new_coercion_cache(obj, seq, 1, coercion_cache_tail_ptr, curr_dims) < 0) {
+        Py_DECREF(seq);
```
Comment (seberg) [inline numpy/core/src/multiarray/array_coercion.c:1092]: This should be in `npy_new_coercion_cache` (a function that steals a reference also steals the reference on error).

**Review by seberg — COMMENTED** [review]
Thanks, looks good! Only that one one is fix is not quite at the right place.

File: numpy/core/src/multiarray/scalarapi.c [hunk 2]
```diff
@@ -234,6 +234,7 @@ PyArray_CastScalarToCtype(PyObject *scalar, void *ctypeptr,
     descr = PyArray_DescrFromScalar(scalar);
     castfunc = PyArray_GetCastFunc(descr, outcode->type_num);
     if (castfunc == NULL) {
+        Py_XDECREF(descr);
```
Comment (seberg) [inline numpy/core/src/multiarray/scalarapi.c:237]: Actually, this check should be done immediately, calling `PyArray_GetCastFunc` if `descr` is NULL is not going to work out.

File: numpy/core/src/multiarray/multiarraymodule.c [hunk 3]
```diff
@@ -4908,5 +4908,6 @@ PyMODINIT_FUNC PyInit__multiarray_umath(void) {
         PyErr_SetString(PyExc_RuntimeError,
                         "cannot load multiarray module.");
     }
+    Py_XDECREF(m);
```
Comment (charris) [inline numpy/core/src/multiarray/multiarraymodule.c:4911]: `m` may be uninitialized if `npy_cpu_init` fails. Maybe just put the module creation first?

**Comment by seberg** [comment]
@defoishugo gentle ping.  It is perfectly fine if the PR stays around for a long time, but since these are not very big changes maybe you have time to wrap it up?

**Comment by charris** [comment]
close/reopen

**Comment by charris** [comment]
Looks like the CI upgrade to Python 3.8.11 breaks the tests.

**Comment by seberg** [comment]
Just a bump in case someone has some time, I had fixed this up, so we should probably get it in.  It is pretty simple.

**Comment by mattip** [comment]
Thanks @defoishugo
