### PR TITLE
MAINT: travis-ci: Update CI scripts.

### LINKED ISSUE #15108: CI: pycparser install failure on one travis job
One of the Travis CI jobs fails to "pip install pycparser":

https://travis-ci.org/numpy/numpy/jobs/625256277#L390
(see under `./tools/travis-before-install.sh`).

It's the "python: 3.7, amd64, PYTHONOPTIMIZE=2 BLAS=None LAPACK=None ATLAS=None NPY_BLAS_ORDER=mkl,blis,openblas,atlas,accelerate,blas NPY_LAPACK_ORDER=MKL,OPENBLAS,ATLAS,ACCELERATE,LAPACK USE_ASV=1" one.

The `travis-before-install.sh` script is missing `set -e` on the top, so the failure is silent. Apparently the CI job still passes, but unclear if its working as it should currently.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
MAINT: travis-ci: Update CI scripts.

* Use `set -ex` in tools/travis-before-install.sh.
* Install build dependencies in tools/travis-before-install.sh.
* Update a comment about an additional option in CFLAGS when USE_DEBUG=1.
* Clear PYTHONOPTIMIZE when running `pip install -r test_requirements.txt`
  because version 2.19 of pycparser (a dependency of one of the packages
  in test_requirements.txt) does not provide a wheel, and the source tar
  file does not install correctly when Python's optimization level is set
  to strip docstrings (see https://github.com/eliben/pycparser/issues/291).
* Remove unnecessary calls of `pip install` in tools/travis-test.sh.

Closes gh-15108.

### CODE REVIEW

File: tools/travis-before-install.sh [hunk 1]
```diff
@@ -33,5 +33,9 @@ python -V
 popd
 
 pip install --upgrade pip setuptools
+# pycparser doesn't work with optimized Python builds that
+# strip out docstrings, so preemptively install pycparser
+# with PYTHONOPTIMIZE unset.
+PYTHONOPTIMIZE= pip install -v pycparser
```
Comment (seberg) [inline tools/travis-before-install.sh]:
```suggestion
PYTHONOPTIMIZE="" pip install -v pycparser
```
I am daft when it comes to bash. Can you ass the `set -e` on the top as well? If this is fixed in newer pycparser versions, maybe you can change comment to reflect that it will be OK to delete the line again?

File: tools/travis-before-install.sh [hunk 2]
```diff
@@ -33,5 +36,11 @@ python -V
 popd
 
 pip install --upgrade pip setuptools
+# pycparser 2.19 doesn't install correctly when Python's optimization level is
+# set to strip docstrings (see https://github.com/eliben/pycparser/issues/291),
+# so preemptively install pycparser with PYTHONOPTIMIZE unset.  If a future
+# version of pycparser doesn't have this problem, the following line can be
+# removed.
```
Comment (mattip) [inline tools/travis-before-install.sh]: I think the comment should mention that pycparser does not ship a wheel, so it must be built and building fails with PYTHONOPTIMIZE=2

File: tools/travis-before-install.sh [hunk 3]
```diff
@@ -33,5 +36,11 @@ python -V
...
+PYTHONOPTIMIZE="" pip install -v pycparser
 pip install -r test_requirements.txt
```
Comment (mattip) [inline tools/travis-before-install.sh]: Why not combine this with the next line `PYTHONOPTIMIZE= pip install -r test_requirements.txt`

Comment (WarrenWeckesser) [reply tools/travis-before-install.sh]: That turns off the optimize flags for all the packages in `test_requirements.txt`.  I guess that would OK.  Presumably the intent of using `PYTHONOPTIMIZE=2` is to test *numpy* when built with that setting, so we don't care how the packages in `test_requirements.txt` are built.

**Comment by WarrenWeckesser** [comment]
Updated with @mattip's suggestion to use `PYTHONOPTIMIZE="" pip install -r test_requirements.txt` instead of installing `pycparser` separately.

The shippable failure is not related to the PR.

**Comment by mattip** [comment]
LGTM. Line 381 in the [relevant build log](https://travis-ci.org/numpy/numpy/jobs/633960731?utm_medium=notification&utm_source=github_status) is now "clean" where previously it erred
```
Processing /home/travis/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511/pycparser-2.19-py2.py3-none-any.whl
```
But later on I see in line 4826 we again call `pip install -r test_requirements.txt`. I think this is redundant. It comes from [toosl/travis-test.sh](https://github.com/numpy/numpy/blob/v1.18.1/tools/travis-test.sh#L68). Should we remove it as part of this PR or in a separate one?

File: tools/travis-before-install.sh [hunk 4]
```diff
@@ -36,12 +36,5 @@ python -V
 popd
 
 pip install --upgrade pip setuptools
```
Comment (eric-wieser) [inline tools/travis-before-install.sh]: tools/travis-test.sh:145 seems to install `setuptools` a second time, unless I'm missing something

File: tools/travis-before-install.sh [hunk 5]
```diff
@@ -33,5 +36,6 @@ python -V
...
-pip install -r test_requirements.txt
+pip install Cython==0.29.14
```
Comment (eric-wieser) [inline tools/travis-before-install.sh]: We need to keep this in a text file in order for @dependabot to find it I think. Perhaps we need a `build_requires.txt`, which could also include a setuptools version?

File: tools/travis-before-install.sh (hunk 4 above)
Comment (WarrenWeckesser) [reply tools/travis-before-install.sh]: @eric-wieser, yes, I've noticed that the travis-ci scripts don't follow DRY very well.  `wheel` and `setuptools` are installed here and there.  Also, `cython` is in `test_requirement.txt`, but in fact `cython` is a build requirement.  I'm looking into this, so consider this PR to be WIP.

File: tools/travis-before-install.sh (hunk 5 above)
Comment (WarrenWeckesser) [reply tools/travis-before-install.sh]: The `requires` section in `pyproject.toml` lists the build requirements.  I just now getting up to speed on which tools actually use that file.  It would be nice if we could have that list in just one place.  (Python packaging... $%@#@#^$$*@#$!)

**Comment by eric-wieser** [comment]
Do you want to split this PR into the bit that sets the optimize flag so that we can merge that, and the bit trying to clean up all the repeated installations?

**Comment by WarrenWeckesser** [comment]
@eric-wieser, let's see if my latest update looks acceptable.  If so, we can keep this in one PR.

**Comment by WarrenWeckesser** [comment]
All green with the latest update.  The scripts now installs the build dependencies from `pyproject.toml`, and the redundant calls to `pip install` have been removed.

File: tools/travis-before-install.sh (hunk 4 above)
Comment (WarrenWeckesser) [reply tools/travis-before-install.sh]: I removed the redundant calls to `pip install` in the latest update.

File: tools/travis-test.sh [hunk 6]
```diff
@@ -48,7 +48,10 @@ setup_base()
   if [ -z "$USE_DEBUG" ]; then
     $PIP install -v . 2>&1 | tee log
   else
-    # Python3.5-dbg on travis seems to need this
+    pip install --upgrade setuptools toml
+    # Install the build dependencies from pyproject.toml.
+    pip install `python -c "import toml; req = toml.load('pyproject.toml')['build-system']['requires']; print(' '.join(req))"`
```
Comment (rgommers) [inline tools/travis-test.sh]: This is quite weird, overall it's less readable. Why do this?

Comment (WarrenWeckesser) [reply tools/travis-test.sh]: It installs the build dependencies from `pyproject.toml`.  That's where the list of dependencies now resides, correct?  (See https://github.com/numpy/numpy/pull/15275#discussion_r364186088)

It turns out I'm still iterating on this PR, so expect this to change shortly.  I'll still use this code snippet, but not here.

Comment (mattip) [reply tools/travis-test.sh]: pyproject.toml, which is a thing still in flux since there is not even an official toml reader in the stdlib, holds the build dependencies. The test_requirements.txt holds the test dependencies. I think for CI we should stick with the test dependencies and not mess with the toml file.

Comment (mattip) [reply tools/travis-test.sh]: using only the pyproject.toml will break dependabot.

Comment (WarrenWeckesser) [reply tools/travis-test.sh]: Which files does dependabot read?

Comment (WarrenWeckesser) [reply tools/travis-test.sh]: Partially answering my own question: dependabot looks at `test_requirements.txt`.  Does it read anything else?

**Comment by WarrenWeckesser** [comment]
Updated with a simpler set of changes.

File: tools/travis-before-install.sh [hunk 7]
```diff
@@ -32,6 +36,16 @@ python -V
...
+# 'setuptools', 'wheel' and 'cython' are build dependencies.  This information
+# is stored in pyproject.toml, but there is not yet a standard way to install
+# those dependencies with, say, a pip command, so we'll just hard-code their
+# installation here.  We only need to install them separately for the cases
+# where numpy is installed with setup.py. When pip is used, pip gets the build
+# dependencies from pyproject.toml.
+# We get the argument for 'cython' from test_requirements.txt to avoid
+# duplicating the version requirement stored there.
+pip install setuptools wheel `grep cython test_requirements.txt`
+
```
Comment (mattip) [inline tools/travis-before-install.sh]: Which run fails without this line?

Comment (WarrenWeckesser) [reply tools/travis-before-install.sh]: One or more of the `setup.py` installs... I think.  Let's find out...

Comment (WarrenWeckesser) [reply tools/travis-before-install.sh]: Actually, all the non-pip installs should fail, because travis-test.sh doesn't explicitly install cython.  The pip installs should work, because pip reads pyproject.toml and does a "private" install of the build requires that it find there.

Comment (WarrenWeckesser) [reply tools/travis-before-install.sh]: The two jobs that set `USE_WHEEL=1` and the one that sets `USE_DEBUG=1` fail to build numpy, because they build numpy by running `setup.py`, but cython is not installed.

Comment (mattip) [reply tools/travis-before-install.sh]: Maybe add that to the comment: `version requirement stored there.` -> `version requirement for the USE_WHEEL=1 and USE_DEBUG=1 builds.`

Comment (WarrenWeckesser) [reply tools/travis-before-install.sh]: Yeah, I can change that comment to be clearer.

The *version requirement* is for any build of numpy, not just those that set `USE_WHEEL` or `USE_DEBUG`.  I put that comment there as an attempt to explain why I get the cython package argument from `test_requirements.txt` instead of just writing

    pip install setuptools wheel cython

I'll work on better wording.

Even better would be to read the build requirements directly from pyproject.toml.  I had that in an earlier version of this PR, but I got the sense that it seemed too complicated.

(Unfortunately, we currently have the required version of cython hard-coded in three places: pyproject.toml, test_requirements.txt, and tools/cythonize.py.  Not sure it is worth the effort at the moment to fix that; even if it is, it can probably wait for a different PR.)

**Comment by WarrenWeckesser** [comment]
Slightly on-topic, if the topic is "clean up the travis-ci shell scripts"...

Currently the last few lines of `.travis.yml` are

    before_install:
      - ./tools/travis-before-install.sh

    script:
      - ./tools/travis-test.sh

    after_success:
      - ./tools/travis-upload-wheel.sh


The *only* thing we do in the `before_install` section is run a shell script, and then we run another shell script in the `script` section.  As far as I can tell, there is no need to have two scripts like this.  We could move the contents of `travis-before-install.sh` into the file `travis-test.sh` and eliminate the `before-install` section.

For now, this is just an observation.  I'm not going to make that change here, unless someone else agrees with that assessment and thinks it is worthwhile.

File: tools/travis-before-install.sh (hunk 7 above)
Comment (WarrenWeckesser) [reply tools/travis-before-install.sh]: I updated the comments.  Tests are running again...

**Comment by mattip** [comment]
Thanks @WarrenWeckesser
