### PR TITLE
BUG: random: Fix handling of a=0 for numpy.random.weibull.

### LINKED ISSUE #12371: BUG: random: np.random.weibull(a=0) sometimes returns inf.
Over in https://github.com/numpy/numpy/pull/8056, there was a test failure that appears to be a numpy bug.  The test that is failing is `TestRandomDist.test_weibull_0`, which is:

    def test_weibull_0(self):
        assert_equal(np.random.weibull(a=0), 0)
        assert_raises(ValueError, np.random.weibull, a=-0.)

The assertion `assert_equal(np.random.weibull(a=0), 0)` is failing, because sometimes `np.random.weibull(a=0)` returns `inf`:

```
In [36]: np.__version__
Out[36]: '1.15.4'

In [37]: np.random.seed(123)

In [38]: np.random.weibull(a=0, size=10)
Out[38]: array([inf,  0.,  0.,  0., inf,  0., inf, inf,  0.,  0.])
```
Those `inf` values should not be there.  I get the same result with the current master branch, `'1.16.0.dev0+e34f5bb'`.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
Before this fix, `np.random.weibull(a=0)` often returned inf (and
in theory could have returned 1).  It should only return 0.

Closes gh-12371.

### CODE REVIEW

File: numpy/random/mtrand/distributions.c [hunk 1]
```diff
@@ -650,6 +650,9 @@ double rk_pareto(rk_state *state, double a)
 
 double rk_weibull(rk_state *state, double a)
 {
+    if (a == 0.0) {
```
Comment (mattip) [inline numpy/random/mtrand/distributions.c]: What happens if a<0? The [documentation](http://www.numpy.org/devdocs/reference/generated/numpy.random.weibull.html) says "Should be greater than 0". Is that accurate, or should it be changed to "Must be greater than 0" and we should error for negative values (raise an error in the pyx file)?

Comment (WarrenWeckesser) [reply numpy/random/mtrand/distributions.c]: Negative values are handled in `RandomState.weibull` in `mtrand.pyx`, so the C function is never called with negative values.  For example,

```
In [39]: np.random.weibull(a=-0.0)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-39-ee6de7ad2cfe> in <module>()
----> 1 np.random.weibull(a=-0.0)

mtrand.pyx in mtrand.RandomState.weibull()

ValueError: a < 0
```

Comment (WarrenWeckesser) [reply numpy/random/mtrand/distributions.c]: I guess "Should be greater than zero" should have been changed to "Must be nonnegative" back when the code was changed to allow `a=0`.  I can change that now.

Comment (WarrenWeckesser) [reply numpy/random/mtrand/distributions.c]: I just pushed an update to the docstring.

**Review by mattip — APPROVED** [review]

**Comment by rkern** [comment]
LGTM.

**Comment by WarrenWeckesser** [comment]
I don't know what happened on that one test run on Travis CI that failed.  Something killed the test script?

**Comment by charris** [comment]
@WarrenWeckesser Travis times out pretty often these days, although I don't recall it dying in the middle of running the tests before. Seems like it should be unrelated to this PR in any case. Restarted just for the heck of it.

**Comment by charris** [comment]
Thanks Warren.
