### PR TITLE
BUG: bool(dtype) is True

### LINKED ISSUE #6294: odd boolean result for np.dtype
numpy 1.9.2

python objects should report a bool of `True` except for empty ones

```
In [1]: bool(1)
Out[1]: True

In [2]: bool([])
Out[2]: False

In [3]: bool(np.dtype('int64'))
Out[3]: False

In [4]: bool(np.dtype('float'))
Out[4]: False
```

https://github.com/libdynd/dynd-python/issues/353

### PR DESCRIPTION
**Pull request by jcrist**
Previously `bool(dtype(...))` would fallback to the default
implementation of `__nonzero__`, which checks if `len(object) > 0`.
Since `dtype` objects implement `__len__` as the number of record
fields, `bool` of scalar dtypes like `bool(dtype('i8'))` would evaluate
as `False`. This fixes that by implementing `__nonzero__` to always
return True.

Fixes #6294.

### CODE REVIEW

File: numpy/core/src/multiarray/descriptor.c [hunk 1]
```diff
@@ -3600,6 +3600,28 @@ arraydescr_richcompare(PyArray_Descr *self, PyObject *other, int cmp_op)
...
 
+static Py_ssize_t
+descr_nonzero(PyObject *self)
+{
+    /* `bool(np.dtype(...)) == True` for all dtypes. Needed to override default
+     * nonzero implementation, which checks if `len(object) > 0`. */
+    return 1;
+}
+
+static PyNumberMethods descr_as_number = {
```
Comment (charris) [inline numpy/core/src/multiarray/descriptor.c]: Not Python 3 compatible, see `doc/Py3K.rst.txt` or grep for examples.

Comment (jcrist) [inline numpy/core/src/multiarray/descriptor.c]: Thanks, fixed.

File: numpy/core/src/multiarray/descriptor.c [hunk 2]
```diff
@@ -3600,6 +3600,31 @@ arraydescr_richcompare(PyArray_Descr *self, PyObject *other, int cmp_op)
     return result;
 }
 
+static Py_ssize_t
+descr_nonzero(PyObject *self)
```
Comment (charris) [inline numpy/core/src/multiarray/descriptor.c]: Wrong return type. The CPython typedef is
```
typedef int (*inquiry)(PyObject *);
```

Comment (jcrist) [inline numpy/core/src/multiarray/descriptor.c]: Thanks. Should be good now.

**Comment by seberg** [comment]
Seems a small thing really, should we just put this in? The only thing I could find against is whether `V0` is True (since it has itemsize 0), but is a rather theoretical thing as well.

@jcrist maybe you can add a short mention to the 1.13 release notes (or am I overdoing release notes ;)).

**Comment by charris** [comment]
@seberg I don't have a problem with this, go ahead. A release note would be good, someone may actually be using current behavior to check for fields. Hmm, what is the recommended way to do that?

**Comment by seberg** [comment]
Hmmm, true, I guess you can check whether `dtype.fields is None` (or `.names`), or actually go back to checking `len(dtype)`, not sure what is best. A bit tricky to decide if any dtype should evaluate to False, hmmm.

**Comment by charris** [comment]
@seberg Yep, a grep turns up `if dtype.fields is None` and `if dtype fields`. Oh, oh, two ways of doing something in Python 8-)

**Comment by seberg** [comment]
Yeah, we should have a `.hasfields` just so there is something
"obvious" :))

**Comment by charris** [comment]
@jcrist Could you add something to the `doc/release/1.13.0-notes.rst`.

**Comment by jcrist** [comment]
Apologies for the delay here. I've added a release note.

**Comment by charris** [comment]
@jcrist Thanks.
