### PR TITLE
BUG: fix handling of copy keyword argument when calling __array__

### LINKED ISSUE #25916: `__array__` copy keyword changes incomplete
It's still very early in the morning and I may simply not be awake yet, but it looks to me like the `__array__` changes in gh-25168 are incomplete and don't have a regression test for the old signature:
```python
In [1]: import numpy as np

In [2]: class MyArr:
   ...:     def __init__(self, x):
   ...:         self._x = x
   ...:     def __array__(self, dtype=None):
   ...:         return self._x
   ...: 

In [3]: x = np.arange(3)

In [4]: np.asarray(x)
Out[4]: array([0, 1, 2])

In [5]: np.asarray(MyArr(x))
...
TypeError: MyArr.__array__() got an unexpected keyword argument 'copy'

In [6]: np.__version__
Out[6]: '2.0.0.dev0+git20240301.06b169b'
```

I didn't follow the review of the C code in detail, so I'm probably missing some details, but it doesn't look like the current implementation does what was intended. In particular:
- only pass along the new `copy` keyword if it's not the default value of `None`, to have a smaller impact,
- pass the actual True/False/None values; it now only passes `False` or `None` (`never_copy ? Py_False : Py_None;`),
- when retrying without the new keyword, the `dtype` keyword should still be passed, so the code should pop `copy` and retry with `kwargs` rather than passing NULL.

It looks like the changes should be along these lines (incomplete): 
```diff
$ git diff
diff --git a/numpy/_core/src/multiarray/ctors.c b/numpy/_core/src/multiarray/ctors.c
index 4b9c3add3f..897e141336 100644
--- a/numpy/_core/src/multiarray/ctors.c
+++ b/numpy/_core/src/multiarray/ctors.c
@@ -2442,26 +2442,46 @@ PyArray_FromArrayAttr_int(
 
     PyObject *copy = never_copy ? Py_False : Py_None;
     PyObject *kwargs = PyDict_New();
-    PyDict_SetItemString(kwargs, "copy", copy);
+
+    /*
+     * Only if the value of `copy` isn't the default one, we try to pass it
+     * along; for backwards compatibility we then retry if it fails because the
+     * signature of the __array__ method being called does not have `copy`.
+     */
+    int copy_passed = 0;
+    if (copy != Py_None) {
+        /* XXX: why can `copy` only be False or None, not True? */
+        copy_passed = 1;
+        PyDict_SetItemString(kwargs, "copy", copy);
+    }
     PyObject *args = descr != NULL ? PyTuple_Pack(1, descr) : PyTuple_New(0);
 
     new = PyObject_Call(array_meth, args, kwargs);
 
     if (PyErr_Occurred()) {
+        PyObject *errmsg_substr = PyUnicode_FromString(
+                "__array__() got an unexpected keyword argument 'copy'");
+        if (errmsg_substr == NULL) {
+            return NULL;
+        }
         PyObject *type, *value, *traceback;
         PyErr_Fetch(&type, &value, &traceback);
-        if (PyUnicode_Check(value) && PyUnicode_CompareWithASCIIString(value,
-                    "__array__() got an unexpected keyword argument 'copy'") == 0) {
+        if (PyUnicode_Check(value) && PyUnicode_Contains(value, errmsg_substr) > 0) {
             Py_DECREF(type);
             Py_XDECREF(value);
             Py_XDECREF(traceback);
+            Py_DECREF(errmsg_substr);
             if (PyErr_WarnEx(PyExc_UserWarning,
                              "__array__ should implement 'dtype' and 'copy' keywords", 1) < 0) {
                 return NULL;
             }
-            Py_SETREF(new, PyObject_Call(array_meth, args, NULL));
+            if (copy_passed) { /* try again */
+                PyDict_DelItemString(kwargs, "copy");
+                Py_SETREF(new, PyObject_Call(array_meth, args, kwargs));
+            }
         } else {
             PyErr_Restore(type, value, traceback);
+            Py_DECREF(errmsg_substr);
             return NULL;
         }
     }
```

Cc @mtsokol @ngoldbaum @seberg.

### PR DESCRIPTION
**Pull request by ngoldbaum**
Closes #25916.

This applies @rgommers draft changes from the issue description and adds a couple more fixes on top.

* Replaces internal usages of `never_copy` with `copy` that can be `-1` (corresponding to `None`), `0` (`False`), and `1` (`True`). This allows the array coercion machinery and `PyArray_FromArrayAttr_int` to support passing `copy=True` (although right now that will never happen).

* Only passes a copy keyword if copy is not the default value.

* Fixes a bug in checking for the error message

* Removes an incorrect usage of `Py_SetRef` (sorry about suggesting that in the first place 😬 )

* Fixes some reference counting issues

* Tests that the old deprecated calling convention still works.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
@oscarbenjamin it looks like there are still some sympy test failures with this PR applied, but I think they'll be fixed once scipy is updated (the failures have tracebacks that end in scipy).

```
FAILED sympy/physics/control/tests/test_control_plots.py::test_pole_zero - assert False
FAILED sympy/physics/quantum/tests/test_identitysearch.py::test_is_scalar_sparse_matrix - ValueError: Unable to avoid copy while creating an array from given array.
FAILED sympy/physics/quantum/tests/test_identitysearch.py::test_is_reducible - ValueError: Unable to avoid copy while creating an array from given array.
FAILED sympy/physics/quantum/tests/test_identitysearch.py::test_bfs_identity_search - ValueError: Unable to avoid copy while creating an array from given array.
FAILED sympy/physics/quantum/tests/test_identitysearch.py::test_bfs_identity_search_xfail - ValueError: Unable to avoid copy while creating an array from given array.
FAILED sympy/solvers/tests/test_simplex.py::test_lp - ImportError: cannot import name '_np' from 'sympy.solvers.inequalities' (/Users/goldbaum/D...
FAILED sympy/utilities/tests/test_lambdify.py::test_scipy_sparse_matrix - ValueError: Unable to avoid copy while creating an array.
```

(although not sure what's up with `test_control_plots` and `test_simplex`).

I tried testing scipy with this PR applied, but it looks like scipy isn't buildable at the moment because of the `descr-f` removal.

**Comment by oscarbenjamin** [comment]
Thanks @ngoldbaum. If changes are needed on SymPy's end then that's fine and I can make them. For now though perhaps the test failures in sympy are some measure of potential breakage that could be caused for other code.

File: numpy/_core/src/multiarray/ctors.c [hunk 1]
```diff
@@ -2440,36 +2447,59 @@ PyArray_FromArrayAttr_int(
...
+        PyObject *copy_obj = copy == 1 ? Py_True : Py_False;
+        PyDict_SetItemString(kwargs, "copy", copy_obj);
+    }
     PyObject *args = descr != NULL ? PyTuple_Pack(1, descr) : PyTuple_New(0);
 
     new = PyObject_Call(array_meth, args, kwargs);
 
-    if (PyErr_Occurred()) {
+    if (new == NULL) {
+        PyObject *errmsg_substr = PyUnicode_FromString(
```
Comment (charris) [inline numpy/_core/src/multiarray/ctors.c:2468]: We could make this a static variable if it makes a significant difference in speed.

Comment (charris) [reply numpy/_core/src/multiarray/ctors.c:2468]: Or maybe `PyUnicode_InternFromString`

**Comment by charris** [comment]
Not clear what is going on with the `Linux SIMD tests / without optimizations`, I think copy should be recognized as a keyword and it didn't fail before. Maybe the problem is with something else called with the keyword.

**Comment by ngoldbaum** [comment]
I can't reproduce that failure locally, but I see that it's running on python `3.12-dev`, which seems odd now that python 3.12 is out. Let's see what happens if I use the release python version.

File: numpy/_core/src/multiarray/ctors.c (hunk 1 above)
Comment (ngoldbaum) [reply numpy/_core/src/multiarray/ctors.c]: done

**Comment by ngoldbaum** [comment]
Hmm, nope. I just tried running python 3.12.1 and I can reproduce this there though. I guess an API changed...

**Comment by ngoldbaum** [comment]
It looks like on Python 3.12, the exception object you get back from `PyErr_Fetch` doesn't pass `PyUnicode_Check`, so I updated the implementation to explicitly convert the exception object into a string, which seems to work on 3.11 and 3.12. Hopefully that makes all the CI happy.

**Comment by ngoldbaum** [comment]
(we should probably add more CI coverage on python 3.12 if that's the only runner on that version)

**Comment by charris** [comment]
Thanks Nathan, good sleuthing.

> I guess an API changed

Nasty.  But I guess we can understand :)

**Comment by rgommers** [comment]
Thanks a lot for the quick fix Nathan!

File: numpy/_core/src/multiarray/ctors.c [hunk 2]
```diff
@@ -2440,36 +2447,65 @@ PyArray_FromArrayAttr_int(
...
+            Py_DECREF(str_value);
+        }
+        if (new == NULL) {
             PyErr_Restore(type, value, traceback);
+            Py_DECREF(kwargs);
             return NULL;
         }
     }
 
+    Py_DECREF(kwargs);
```
Comment (mtsokol) [inline numpy/_core/src/multiarray/ctors.c:2506]: Should we have `Py_DECREF(args);` next to `kwargs`? Similarly to: https://github.com/numpy/numpy/blob/9d69a62cdc734e9fae074a9242aa1b00eceafcd4/numpy/_core/src/multiarray/arrayfunction_override.c#L240

Comment (mtsokol) [reply numpy/_core/src/multiarray/ctors.c:2506]: And this is the only comment that I have.

File: doc/release/upcoming_changes/25168.change.rst [hunk 3]
```diff
@@ -7,3 +7,15 @@ Now `numpy.array` and `numpy.asarray` support three values for ``copy`` paramete
...
+-----------------------------------------------------------------------
+
+NumPy will pass ``copy`` to the ``__array__`` special method in situations where
+it would be set to a non-default value (e.g. in a call to
+``np.asarray(some_object, copy=False)``). Currently, if an
+unexpected keyword argument error is raised after this, NumPy will print a
+warning and re-try without the ``copy`` keyword argument. Implementations of
+objects implementing the ``__array__`` protocol should accept a ``copy`` keyword
+argument with the same meaning as when passed to `numpy.array` or
+`numpy.asarray`.
```
Comment (jorisvandenbossche) [inline doc/release/upcoming_changes/25168.change.rst:21]: Happy to move it to a new issue, but thinking through how to update some `__array__` implementations, I am wondering: what are the expectations from numpy how an `__array__` implementations handles this keyword fully or partially? 

When `copy=True` is being passed, does numpy assume that the `__array__` implementation already made that copy? But what if the implementation defers dtype casting to numpy (which is currently possible), then it might be a waste to already copy up front?

Comment (rgommers) [reply doc/release/upcoming_changes/25168.change.rst:21]: Great question. Worth a new issue indeed I think.

> But what if the implementation defers dtype casting to numpy (which is currently possible)

Deprecated though, right? The signature should already have included the `dtype` keyword, even though it was still working to not have that.

> then it might be a waste to already copy up front?

What we want to achieve I think is that only a single copy is ever made. We can have two now in many cases, because the other library may copy from its internal implementation into an array, and then numpy will make another copy. The only way to get it right is for the other library to do the copy if `copy=True`, and for numpy not to do so if the method call including `copy=True` succeeded.

Comment (jorisvandenbossche) [reply doc/release/upcoming_changes/25168.change.rst:21]: Created https://github.com/numpy/numpy/issues/25941, in case you want to move over your comments as well
