### PR TITLE
BUG: Fix undefined behaviour induced by bad `__array_wrap__`

### LINKED ISSUE #8507: Malformed __array_wrap__ causes SystemError
Or sometimes even a python crash. Demo:

```python
>>> class Foo(np.ndarray):
...   def __array_wrap__(self, obj): pass
>>> f = np.zeros(2).view(Foo)
>>> f + 1
SystemError: <ufunc 'add'> returned NULL without setting an error
# sometimes: nasal demons
```

### PR DESCRIPTION
**Pull request by eric-wieser**
This fixes #8507.

The semantics of `__array_wrap__` are now that if the return value is None, the argument passed in is assumed as the return value.

The previous semantics were to segfault.

### CODE REVIEW

**Comment by mhvk** [comment]
Nice find! Though I think it is better just to fail, so that someone realises it is a mistake. At least, I can just imagine writing code but forgetting to return the object, and trying and trying and never getting it to work -- would be so frustrating! And since presently it does fail too, it would not introduce regressions.

File: numpy/core/src/umath/ufunc_object.c [hunk 1]
```diff
@@ -4405,6 +4406,7 @@ ufunc_generic_call(PyUFuncObject *ufunc, PyObject *args, PyObject *kwds)
             }
             else if (res == Py_None) {
                 Py_DECREF(res);
+                retobj[i] = (PyObject *)mps[j];
```
Comment (mhvk) [inline numpy/core/src/umath/ufunc_object.c]: I think just `goto fail;` here (see main comment)

**Comment by mhvk** [comment]
Also, once we have decided on what the path should be, a test case and an entry in the 1.12.1 release notes.....  Thanks!

File: numpy/core/src/umath/ufunc_object.c (hunk 1 above)
Comment (eric-wieser) [inline numpy/core/src/umath/ufunc_object.c]: It'd need a `PyExc_SetString` too though, right?

**Comment by eric-wieser** [comment]
> Though I think it is better just to fail, so that someone realises it is a mistake.

Yeah, i think I agree with you, and just did it this way because that seemed like what the original author was aiming for.

`ValueError("__array_wrap__ did not return a value")` seem reasonable as a message?

also while we're at it, can we put a deprecation warning in the missing `context` argument codepath?

**Comment by eric-wieser** [comment]
Actually, can't we just allow it to return `None`?

**Comment by mhvk** [comment]
Since it is possible to return anything at all, I think I agree `None` should not really be an exception to that rule. So then the solution is to just remove the whole if-statement, right? That has the nice side-benefit of making the normal path just a little bit faster.

**Comment by mhvk** [comment]
p.s. As for deprecating the no-context part: definitely a different PR (since it doesn't fix any bugs, so would go in 1.13, not 1.12.1). Not completely sure it is worth it, though -- given the comparison with `NULL`, this is a fast path for the regular case and I'm not sure it is worth the churn (especially since we should have our new & shiny `__array_func__` in the not-too-distant future...).

**Comment by eric-wieser** [comment]
> So then the solution is to just remove the whole if-statement, right?

Yep, done

> definitely a different PR

Agreed

>  Not completely sure it is worth it, though

File: numpy/core/tests/test_umath.py [hunk 2]
```diff
@@ -1422,6 +1422,18 @@ def __array_wrap__(self, arr, context):
         a = A()
         self.assertRaises(RuntimeError, ncu.maximum, a, a)
 
+    def test_none_wrap(self):
+
```
Comment (mhvk) [inline numpy/core/tests/test_umath.py]: Add a comment here that this is a regression check ensuring that if `None` is returned, it doesn't crash the system (linking back to the issue and PR; convention seems to be `gh-nnnn`).

File: numpy/core/tests/test_umath.py [hunk 3]
```diff
@@ -1422,6 +1422,18 @@ def __array_wrap__(self, arr, context):
...
+        class A(object):
+            def __array__(self):
+                return np.zeros(1)
+
+            def __array_wrap__(self, arr, context):
```
Comment (mhvk) [inline numpy/core/tests/test_umath.py]: not important here, but convention is to use `context=None`, since the caller does not have to put in any context. Since you need to edit anyway...

**Comment by mhvk** [comment]
@charris - this PR is a bug fix for 1.12, and should presumably be mentioned in the release notes, but there is no `1.12.1-notes.rst` file yet; should one just use, e.g., `1.11.3-notes.rst` as a template?

**Comment by charris** [comment]
@mhvk The merged fixes will be found by a script and added to the 1.12.1 release notes with a linked to the relevant PR. Unless you think more explanation is needed that should suffice. I've created the initial release notes just in case, but you will need to rebase this to see them.

**Comment by mhvk** [comment]
OK, thanks for the clarification. In that case, @eric-wieser, I think this is ready to go in after you've made the two small changes I requested in-line (you can use `[skip ci]`, since this will not affect the tests).

File: numpy/core/tests/test_umath.py (hunk 3 above)
Comment (eric-wieser) [inline numpy/core/tests/test_umath.py]: This is not the only place where this is missing in this file, so I'll leave the others to keep this patch small

**Comment by eric-wieser** [comment]
> (you can use [skip ci], since this will not affect the tests).

Presumably then, I should not squash my commits?

**Comment by mhvk** [comment]
@eric-wieser - arrgghh - my astropy background, where we do not worry about the number of commits, is showing through. Since for numpy the changelog is partially generated automatically, based on commits, I guess it is indeed much bettter to just have a single commit (unless there really are different pieces to a puzzle). So, could you squash?

**Comment by charris** [comment]
@mhvk I'm thinking of putting the PRs in the changlog instead of commits/merges. Note that the last posted release notes contained  PRs with a link. These days you can also do squash and merge and our script also picks that up. Just make sure that the summary line and commit message are appropriate and the summary line ends with `(pr number)` as it currently does by default.

**Comment by eric-wieser** [comment]
Ok, squashed

**Comment by mhvk** [comment]
Great, merging...

**Comment by eric-wieser** [comment]
This needs a rebase on 1.12.1, right?

**Comment by mhvk** [comment]
I *think* the backporting gets done in separate PRs -- @charris??

**Comment by eric-wieser** [comment]
Yep, it definitely goes in a separate PR. Not sure if it's automated, in which case this needs to stay on the radar

**Comment by juliantaylor** [comment]
something I like to do with bugfixes intended for backporting from the beginning is to rebase them onto the merge base between the maintenance branch and the master branch.
That way the same commit can be merged into both branches which saves you pushing a new branch (just create another PR from the same branch) and allows using git tag --contains command to see which tags/branches contain a bugfix

on the bugfix branch:

    git rebase --onto $(git merge-base master maintenance/1.12.x)
HEAD^

I usually do it, but others not so it is optional.

**Comment by eric-wieser** [comment]
Yep, that would have been a good idea. Too late now though...
