### PR TITLE
BUG: fix instability of structured dtype hash

### LINKED ISSUE #5715: record dtype hashing is fragile
When pickling and unpickling a record type, hash equality can fail sporadically (tested under Python 3.4). If you take this script:

```
import pickle
import numpy as np

ty = np.dtype([('a', np.float64),
               ('b', np.int32),
               ('c', np.complex64),
               ('d', (np.str, 5))])

newty = pickle.loads(pickle.dumps(ty))
assert hash(newty) == hash(ty), (ty == newty, ty.fields, newty.fields)
```

and run it in a loop (e.g. `while python nprecbug.py; do :; done`), eventually you'll hit a failure:

```
Traceback (most recent call last):
  File "nprecbug.py", line 12, in <module>
    assert hash(newty) == hash(ty), (ty == newty, ty.fields, newty.fields)
AssertionError: (True, mappingproxy({'b': (dtype('int32'), 8), 'd': (dtype('<U5'), 20), 'a': (dtype('float64'), 0), 'c': (dtype('complex64'), 12)}), mappingproxy({'b': (dtype('int32'), 8), 'c': (dtype('complex64'), 12), 'a': (dtype('float64'), 0), 'd': (dtype('<U5'), 20)}))
```

As you can see, `__hash__` seems to be sensitive to the ordering of fields in the mappingproxy. By contrast, `__eq__` does the right thing.

### PR DESCRIPTION
**Pull request by pitrou**
The hash value of a structured dtype was dependent on iteration order
of the fields mapping, which could make (in rare conditions) two
equal dtypes hash to different values.  We now consider the fields
in deterministic order, according to the names property.

Closes #5715.

(note this PR also removes a few oddities in reference counting)

### CODE REVIEW

File: numpy/core/src/multiarray/hashdescr.c [hunk 1]
```diff
@@ -104,18 +103,24 @@ static int _array_descr_builtin(PyArray_Descr* descr, PyObject *l)
...
-static int _array_descr_walk_fields(PyObject* fields, PyObject* l)
+static int _array_descr_walk_fields(PyObject *names, PyObject* fields, PyObject* l)
 {
-    PyObject *key, *value, *foffset, *fdescr;
+    PyObject *key, *value, *foffset, *fdescr, *ftitle;
     Py_ssize_t pos = 0;
     int st;
 
-    while (PyDict_Next(fields, &pos, &key, &value)) {
+    for (pos = 0; pos < PyTuple_GET_SIZE(names); pos++) {
```
Comment (jaimefrio) [inline numpy/core/src/multiarray/hashdescr.c]: Shouldn't we explicitly check that `names` is indeed a tuple before calling `PyTuple_GET_SIZE` and `PyTuple_GET_ITEM` below?

Comment (pitrou) [inline numpy/core/src/multiarray/hashdescr.c]: The PyTuple_Check() call is done in _array_descr_walk() below (similar to the PyDict_Check() call for the fields).

File: numpy/core/src/multiarray/hashdescr.c [hunk 2]
```diff
@@ -224,7 +230,12 @@ static int _array_descr_walk(PyArray_Descr* descr, PyObject *l)
                         "(Hash) fields is not a dict ???");
                 return -1;
             }
-            st = _array_descr_walk_fields(descr->fields, l);
+            if (!PyTuple_Check(descr->names)) {
```
Comment (jaimefrio) [inline numpy/core/src/multiarray/hashdescr.c]: Oh, so here is the check I was missing before... I think it will be clearer if we moved this one into `_array_descr_walk_fields`. Perhaps we can also move the check for `fields` into it?

**Comment by pitrou** [comment]
Ok, I've now moved the type checks around.

**Comment by jaimefrio** [comment]
Thanks, the code now LGTM. Before merging, my only potential concern, and this is mostly out of ignorance, is whether we should be worried that hash values change between versions, which they will once we merge this PR. Am I being overly cautious here?

**Comment by pitrou** [comment]
Well, hash values were already unpredictable because they were based on iteration order of the fields dict. If anything, this PR makes them more stable :-)
But, to answer your question more generally, specific hash values are never an API guarantee. Also, recent Python versions randomize them to avoid DOS attacks on dictionaries by creating intentional collision chains.

**Comment by jaimefrio** [comment]
OK, I'm taking your word (and Travis') for it. ;-) Thanks for the third time today!

**Comment by pitrou** [comment]
Thank you!
