### PR TITLE
BUG: Allow no-op clearing of void dtypes

### LINKED ISSUE #23277: BUG: clearing of array data too aggressive after gh-22924
### Describe the issue:

#22924 introduced failures in astropy (and likely in pandas). It is almost certainly to do with zero-length object dtype arrays; pure numpy example below.

### Reproduce the code example:

```python
import numpy as np
np.recarray((0,), dtype="O") 
# rec.array([],
#           dtype=|V8)
exit()
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Internal error, tried to fetch clear function for the user dtype '' without fields or subarray (legacy support).
```

### Runtime information:

1.25.0.dev0+802.g5f04e748b
3.11.1 (main, Dec 31 2022, 10:23:59) [GCC 12.2.0]

### Context for the issue:

See https://github.com/numpy/numpy/pull/22924#issuecomment-1444854769 and below.

### PR DESCRIPTION
**Pull request by seberg**
Some void dtypes think they contain objects but don't.  Instead of playing whack-a-mole to see if that can be fixed, simply make the clearing a no-op here for them.
User dtypes are weirder, it should be OK to pass through.

Fixes the error message and use write-unraisable.

Closes gh-23277

### CODE REVIEW

File: numpy/core/src/multiarray/arrayobject.c [hunk 1]
```diff
@@ -455,7 +455,9 @@ array_dealloc(PyArrayObject *self)
     if ((fa->flags & NPY_ARRAY_OWNDATA) && fa->data) {
         /* Free any internal references */
         if (PyDataType_REFCHK(fa->descr)) {
-            PyArray_ClearArray(self);
+            if (PyArray_ClearArray(self) < 0) {
```
Comment (mhvk) [inline numpy/core/src/multiarray/arrayobject.c:458]: Just to check I understand: to write a test for this, one would have to have a clearing function that actually misbehaves, correct? And the actual array object here is no longer accessible, hence `NULL`?

File: numpy/core/src/multiarray/dtype_traversal.c [hunk 2]
```diff
@@ -454,10 +454,21 @@ npy_get_clear_void_and_legacy_user_dtype_loop(
         }
         return 0;
     }
+    else if (dtype->type_num == NPY_VOID) {
+        /* 
+         * Void dtypes can have "ghosts" of objects marking the dtype because
```
Comment (mhvk) [inline numpy/core/src/multiarray/dtype_traversal.c:459]: Should we have a separate issue to remind us to fix this?

**Review by mhvk — APPROVED** [review]
Looks good!

File: numpy/core/src/multiarray/arrayobject.c (hunk 1 above)
Comment (seberg) [reply numpy/core/src/multiarray/arrayobject.c:458]: Yes, it shouldn't be possible to reach this, but without the fix, you do.

File: numpy/core/src/multiarray/dtype_traversal.c (hunk 2 above)
Comment (seberg) [reply numpy/core/src/multiarray/dtype_traversal.c:459]: One point is, that so long we allow you to view a structured array as a bytes/unstructured void, this has to stay in place.

**Comment by charris** [comment]
Thanks Sebastian.

File: numpy/core/src/multiarray/dtype_traversal.c (hunk 2 above)
Comment (mhvk) [reply numpy/core/src/multiarray/dtype_traversal.c:459]: Yes, I guess that makes sense - actually quite a mess if there is an object underneath. But, for another time!
