### PR TITLE
BUG: Create complex scalars from real and imaginary parts

### LINKED ISSUE #19125: cdouble does not take 2 arguments
cdouble does not take 2 arguments as described in https://numpy.org/devdocs/reference/arrays.scalars.html#numpy.cdouble

Original use case was to use `cdouble(real_values_ndarray, imag_values_ndarray)`

This may be a documentation issue instead of a code issue, if this behavior was not intended to be used.

### Reproducing code example:

```python
import numpy as np
np.cdouble(1,1)
```

### Error message:

TypeError: function takes at most 1 argument (2 given)

### NumPy/Python version information:

1.20.3
3.8.8 (default, Mar 12 2021, 19:49:08) 
[GCC 5.4.0 20160609]

Also tested on various other numpy / python versions, np <1.20.1, 1.15.0, 1.14, 1.17.3> python <3.8.0, 3.7, 3.5, 2.7.12>

### PR DESCRIPTION
**Pull request by ngoldbaum**
fixes gh-19125

If anyone has an idea for how to generalize this for `np.clongdouble` I'm all ears. I couldn't come up with a straightforward way to do that. I can't go through python complex numbers for `clongdouble` because the cast from `clongdouble` to `complex` is unsafe. Proposing this PR as-is without that support because extended precision types like `clongdouble` are already kind of an odd duck.

### CODE REVIEW

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 1]
```diff
@@ -2923,8 +2923,36 @@ static PyObject *
...
     PyObject *obj = NULL;
+#if defined(_@TYPE@_IS_CDOUBLE) || defined(_@TYPE@_IS_CFLOAT)
+    static char *kwnames[] = {"", "", NULL};  /* positional-only */
+    static char *parse_error = "Could not convert arguments into a complex scalar. '%R' given.";
+    PyObject *real_obj = NULL;
+    PyObject *imag_obj = NULL;
+    if (PyArg_ParseTupleAndKeywords(args, kwds, "|OO", kwnames, &real_obj, &imag_obj)) {
+        if (imag_obj == NULL) {
+            obj = real_obj;
+            Py_XINCREF(obj);
```
Comment (seberg) [inline numpy/core/src/multiarray/scalartypes.c.src:2934]: The refcounting for this is off below, hard to fix without a `goto finish` or so probably.  Might be easier to just include the scalar creation/assignment in the branch directly (duplicating some code)...

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 2]
```diff
@@ -2923,8 +2923,36 @@ static PyObject *
...
+        }
+        else if (PyNumber_Check(real_obj) && PyNumber_Check(imag_obj)) {
+            if (PyComplex_Check(real_obj) || PyComplex_Check(imag_obj)) {
```
Comment (seberg) [inline numpy/core/src/multiarray/scalartypes.c.src:2937]: OK, without this we would allow `np.complex128(numpy_complex, numpy_complex)`, although it would give a warning.  I don't have a strong opinion on the need, I agree, this is mainly about accepting the trivial case of `np.complex128(3., 4)` with python scalars anyway.

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 3]
```diff
@@ -2923,8 +2923,36 @@ static PyObject *
...
+                return NULL;
+            }
+            obj = PyComplex_Type.tp_new(&PyComplex_Type, args, NULL);
+            if (obj == NULL) {
+                return NULL;
+            }
+        }
+        else {
+            PyErr_Format(PyExc_TypeError, parse_error, args);
+            return NULL;
```
Comment (seberg) [inline numpy/core/src/multiarray/scalartypes.c.src:2948]: My slight preference would be to put the error paths first, then no indent for the successful one.

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 4]
```diff
@@ -2923,8 +2923,36 @@ static PyObject *
...
+        }
+        else if (PyNumber_Check(real_obj) && PyNumber_Check(imag_obj)) {
+            if (PyComplex_Check(real_obj) || PyComplex_Check(imag_obj)) {
+                PyErr_Format(PyExc_TypeError, parse_error, args);
+                return NULL;
+            }
+            obj = PyComplex_Type.tp_new(&PyComplex_Type, args, NULL);
+            if (obj == NULL) {
+                return NULL;
+            }
```
Comment (seberg) [inline numpy/core/src/multiarray/scalartypes.c.src:2944]: While annoying, duplicating the scalar creation may be easier here?  Something like this (but I am not sure the cast is actually valid, may have to cast real/imag separately. 
```
npy_@name@ val = PyComplex_AsCComplex(obj);  // does that work, since its struct-like
// Need to fetch the typecode.  Note that this can't actually fail
// (unlike the code below makes you believe).
PyObject *robj = PyArray_Scalar(&val, typecode, NULL);
Py_DECREF(py_complex);
return robj;
```

**Review by seberg — COMMENTED** [review]
I am fine with adding this, this code needs more love, but its tricky and supporting this for complex64 and complex128 seems like a safe thing to do (not hard to keep supporting if there is a refactor).

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 3 above)
Comment (ngoldbaum) [reply numpy/core/src/multiarray/scalartypes.c.src:2947]: Refactored so the error case comes first.

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 4 above)
Comment (ngoldbaum) [reply numpy/core/src/multiarray/scalartypes.c.src]: Unfortunately Numpy at the moment allows any array-like to be passed to the scalar initializers (and there are tests for it), which means I'd first need to re-implement the array-like coercion logic in `PyArray_FromAny` to get this to work.

```
In [2]: np.complex128([1, 2, 3, 4])
Out[2]: array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [3]: np.complex128(b"1+4j")
Out[3]: (1+4j)
```

I think it's better to just avoid the early return and re-use the logic in the rest of this function that goes through `PyArray_FromAny`.

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 1 above)
Comment (ngoldbaum) [reply numpy/core/src/multiarray/scalartypes.c.src]: Can you explain a bit more what the refcounting issue is? I think with the latest push everything is correct. 

We `INCREF` `obj` if it gets assigned to `real_obj`, but then a decref happens after `obj` gets used in `PyArray_FromAny`. There's an early return before that in the `obj == NULL` case, but then in that case we can't have any refcounting errors because `obj` is `NULL`.

There was a refcounting issue in the original version of this PR if getting the typecode failed, but as you pointed out in another comment, that's impossible given the way it's written. I deleted the error case and left a comment that it can't fail to make that clearer.

Comment (seberg) [reply numpy/core/src/multiarray/scalartypes.c.src]: Ah, yes you are right, I thought there were more error paths, but there is mainly that `obj == NULL` block.

**Comment by seberg** [comment]
I will put this in, thanks @ngoldbaum.  I will not that I think this chunk of code needs a heavy-handed rewrite while being open to just break some stuff and keeping these fallbacks probably only where it's too difficult to decide how to just delete (i.e. possibly strings).
