### PR TITLE
BUG: add a specialized loop for boolean matmul

### LINKED ISSUE #14439: matmul @ of boolean arrays gives inconsistent results
Since the matrix A is its own square, the loop below should be infinite, but it terminates after 8 iterations. If `A = A.dot(A)` is use in place of `A = A @ A`, the loop is infinite as expected.

### Reproducing code example:

```python
import numpy as np

A = M = np.array([[ True, False],[True,True]])
i = 0
while (A == M).all():
    i += 1
    print(i, "A == M")
    A = A @ A
print(A)

# 1 A == M
# 2 A == M
# 3 A == M
# 4 A == M
# 5 A == M
# 6 A == M
# 7 A == M
# 8 A == M
# [[ True False]
#  [False  True]]
```

### Numpy/Python version information:

1.16.0rc1 3.7.2 (default, Jan  3 2019, 02:55:40) 
[GCC 8.2.0]

### PR DESCRIPTION
**Pull request by mattip**
Fixes gh-14439

Not sure whether this should be labelled a bug or a regression, since the original matmul was based on dot and so most likely worked properly. If a regression the test should move to the proper place.

### CODE REVIEW

File: numpy/core/src/umath/matmul.c.src [hunk 1]
```diff
@@ -266,7 +264,45 @@ NPY_NO_EXPORT void
...
+    ob_p  = os_p * dp;
 
+    for (m = 0; m < dm; m++) {
+        for (p = 0; p < dp; p++) {
+            *(npy_bool *)op = NPY_FALSE;
+            for (n = 0; n < dn; n++) {
+                npy_bool val1 = (*(npy_bool *)ip1);
+                npy_bool val2 = (*(npy_bool *)ip2);
+                if (val1 != 0 && val2 != 0) {
+                    *(npy_bool *)op = NPY_TRUE;
```
Comment (mattip) [inline numpy/core/src/umath/matmul.c.src]: in [`BOOL_dot`](https://github.com/numpy/numpy/blob/v1.17.2/numpy/core/src/multiarray/arraytypes.c.src#L3527) there is a break here since we do not need to traverse more of the inner (`dn`) loop once `op` is set to `NPY_TRUE`. However this would require a different style of inner-loop pointer incrementing. Is it worth the effort?

Comment (seberg) [reply numpy/core/src/umath/matmul.c.src]: Not sure, my guess is that it could might a difference, but boolean matmul is probably super rare. So I do not think it is high priority, and we could wait for someone to complain about the difference in speed. But can't you do:
```
                ip2 += is2_n * (dn - n);
	        ip1 += is1_n * (dn - n);
                break;
```
Which seems OK?

About the tests: My personal opinion is that the regression tests are never the best place to put things. Just the lazy place for bug fixes, and even that is more of a historic thing and we do not use it much anymore.

File: numpy/core/tests/test_multiarray.py [hunk 2]
```diff
@@ -6276,6 +6276,13 @@ def __mul__(self, other):
         with assert_raises(TypeError):
             b = np.matmul(a, a)
 
+    def test_matmul_bool(self):
+        # gh-14439
+        a = np.array([[1, 0],[1, 1]], dtype=bool)
+        assert np.max(a.view(np.int8)) == 1
+        b = np.matmul(a, a)
+        # matmul with boolean output should always be 0, 1
+        assert np.max(b.view(np.int8)) == 1
```
Comment (seberg) [inline numpy/core/tests/test_multiarray.py]: Could be nice to have a larger than 2x2 array as well I guess. And while we are at it, ensure:
```
np.matmul(np.empty((2, 0), dtype=np.bool_), np.empty(0, dtype=np.bool_))
```
gives `[False, False]` (that is what dot gives, I assume it is correct, heh).

Comment (eric-wieser) [reply numpy/core/tests/test_multiarray.py]: Should probably view as `uint8` here, since currently this test won't detect `-1`

**Comment by charris** [comment]
> original matmul was based on dot

If cblas couldn't be used, it was done with einsum
```
In [11]: a                                                                      
Out[11]: 
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]: einsum('ij,jk', a, a).view(int8)                                       
Out[12]: 
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)
```

**Comment by seberg** [comment]
Put release note label, but since this is going to be backported and the backports have the shortlist, and it is pretty obvious, maybe that is unnecessary.

File: numpy/core/tests/test_multiarray.py (hunk 2 above)
Comment (mattip) [reply numpy/core/tests/test_multiarray.py]: fixed `uint8`, added more tests. `np.empty` gives uninitialized memory, used `np.zeros` instead.

File: numpy/core/src/umath/matmul.c.src (hunk 1 above)
Comment (mattip) [reply numpy/core/src/umath/matmul.c.src]: added temporary pointer variables to allow early break out of inner loop.

**Comment by charris** [comment]
There are compiler warnings...

**Comment by mattip** [comment]
grr. We should move the compiler-warning-check code from `tools/travis-test.sh` to `runtests.py` so failures will show up locally, and so that grep can be tested.

**Comment by mattip** [comment]
tests pass

File: numpy/core/src/umath/matmul.c.src (hunk 1 above)
Comment (seberg) [reply numpy/core/src/umath/matmul.c.src]: OK, looks good to me. I think it is ready to merge, could try to nitpick, but not worth it ;). To be honest, I think the temp version is maybe clearer anyway.
