### PR TITLE
BUG: Fix reference leakage for output arrays in reduction functions

### LINKED ISSUE #29355: BUG: Memory leak using `out=` parameter in numpy version 2.3
### Describe the issue:

There seems to be a memory leak introduced in numpy 2.3.0.  I've noticed this when using `numpy.cumsum` with the `out=` parameter.  It looks as if data for the array passed in the `out` parameter is not being released. 

### Reproduce the code example:

```python
import numpy as np
import pytest

# (also needs pytest-memray installed)

@pytest.mark.limit_leaks("100 KB")
def test_does_not_leak() -> None:
    for _ in range(100):
        size = 1000
        x = np.ones(size, np.float64)
        v = np.empty(size, np.float64)
        np.cumsum(x, out=v)
```

### Error message:

```shell
Test was allowed to leak 100.0KiB per location but at least one location leaked more
----------------------------------------------------------------------------------------------------- memray-leaked-memory ------------------------------------------------------------------------------------------------------
List of leaked allocations:
    - 781.2KiB allocated here:
        default_malloc:<unknown>:0
        PyDataMem_UserNEW:<unknown>:0
        PyArray_NewFromDescr_int:<unknown>:0
        PyArray_Empty_int:<unknown>:0
        array_empty:<unknown>:0
        ...
```

### Python and NumPy Versions:

Tested on python 3.11
numpy:
   * numpy 2.3.0 leaks
   * numpy 2.2.6 does not leak

### Runtime Environment:

```
>>> numpy.show_runtime()
[{'numpy_version': '2.3.0',
  'python': '3.11.13 (main, Jun  9 2025, 16:09:23) [GCC 13.1.1 20230614 (Red '
            'Hat 13.1.1-4)]',
  'uname': uname_result(system='Linux', node='ab21b3c99130', release='6.6.87.2-microsoft-standard-WSL2', version='#1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL',
                                    'AVX512_SPR']}},
 {'architecture': 'Haswell',
  'filepath': '/dependencies/opt/bb/lib/python3.11/site-packages/numpy.libs/libscipy_openblas64_-56d6093b.so',
  'internal_api': 'openblas',
  'num_threads': 22,
  'prefix': 'libscipy_openblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.29'}]
```

### Context for the issue:

This is problematic for long running python services, as it can result in unbounded memory growth and eventual service failure.

### PR DESCRIPTION
**Pull request by MaanasArora**
Fixes #29355.

We already increment a reference to `out` in `_set_out_array` (in `ufunc_object.c`):

```
c
static int
_set_out_array(PyObject *obj, PyArrayObject **store)
{
    ...
    Py_INCREF(obj);
    *store = (PyArrayObject *)obj;

    return 0;
    ...
}
```

This PR removes additional increments and adds a missing decrement that caused the memory leakage.

### CODE REVIEW

**Comment by VinothkumarS79** [comment]
static int
_set_out_array(PyObject *obj, PyArrayObject **store)
{
    if (*store != NULL) {
        Py_DECREF(*store);  // Release the previous reference
    }
    Py_INCREF(obj);
    *store = (PyArrayObject *)obj;

    return 0;
}





If there's any chance obj isn't guaranteed to be a PyArrayObject, you might want to add:

if (!PyArray_Check(obj)) {
    PyErr_SetString(PyExc_TypeError, "Expected a NumPy array");
    return -1;
}

File: numpy/_core/src/umath/ufunc_object.c [hunk 1]
```diff
@@ -3035,9 +3032,6 @@ PyUFunc_Reduceat(PyUFuncObject *ufunc, PyArrayObject *arr, PyArrayObject *ind,
         return NULL;
     }
 
-    /* Take a reference to out for later returning */
-    Py_XINCREF(out);
```
Comment (seberg) [inline numpy/_core/src/umath/ufunc_object.c]: Thanks!  I would prefer to keep the incref (somewhere in the function).

Removing the XINCREF here is correct and actually convenient!  But it means the function takes one reference to `out` (if passed) and returns one new reference.  Returning a new reference is obvious, but that means you have `+1-1`, i.e. the `-1` is "stealing" the original reference.

But reference count stealing tends to be a bit confusing, largely on account it not very being common, so I would prefer to avoid introducing it (unless it is an `**out` API, where `out` is mutated/replaced in-place).
Also with alternative Python implementations and free-threading, reference stealing is a pattern that often needs to be avoided.

---

That is, re-add a decref in the calling code instead (I/we probably lost it when working on `array_wrap` improvements).
(Or never take a reference, since `out=` is currently always an ndarray already.)

We could add an explicit test as well via `sys.getrefcount()` (needs disabling on PyPy), almost surprised we don't have one.

Comment (seberg) [reply numpy/_core/src/umath/ufunc_object.c]: One way to do almost the same as here, is to use:
```
Py_XSETREF(out, function(..., out, ...));
```
at the call-site.

Comment (MaanasArora) [reply numpy/_core/src/umath/ufunc_object.c]: Thanks for the pointers / context! That makes sense. I've reverted the reference stealing and instead readjusted some of the incref code to be a bit clearer (hopefully) and added a decref to `PyUFunc_GenericReduction`. Adding a test to check the reference counts!

Comment (MaanasArora) [reply numpy/_core/src/umath/ufunc_object.c]: I've reverted to using `XINCREF`--we need the reference for the promotion! (and also seems clearer, actually). Also added a test.

File: numpy/_core/tests/test_ufunc.py [hunk 2]
```diff
@@ -3003,6 +3003,36 @@ def test_reduce_casterrors(offset):
...
+    assert count == sys.getrefcount(arr)
+
+    # with `out=` the reference count is not changed
+    out = np.empty((), dtype=np.int32)
+    np.add.reduce(arr, dtype=np.int32, out=out, initial=0)
+    assert count == sys.getrefcount(arr)
+
+    out = np.empty(arr.shape, dtype=np.int32)
+    np.add.accumulate(arr, dtype=np.int32, out=out)
+    assert count == sys.getrefcount(arr)
```
Comment (seberg) [inline numpy/_core/tests/test_ufunc.py:3034]: You want to check the refcount on `out` (also)

File: numpy/_core/src/umath/ufunc_object.c [hunk 3]
```diff
@@ -3727,6 +3727,8 @@ PyUFunc_GenericReduction(PyUFuncObject *ufunc,
     if (ret == NULL) {
         goto fail;
     }
+    
+    Py_XDECREF(out);
```
Comment (seberg) [inline numpy/_core/src/umath/ufunc_object.c:3731]: This looks good, but also needed on error.

**Review by seberg — COMMENTED** [review]
LGTM, two minor fixes needed.

File: numpy/_core/tests/test_ufunc.py (hunk 2 above)
Comment (MaanasArora) [reply numpy/_core/tests/test_ufunc.py:3034]: Done!

File: numpy/_core/src/umath/ufunc_object.c (hunk 3 above)
Comment (MaanasArora) [reply numpy/_core/src/umath/ufunc_object.c:3731]: Done, thanks!

**Review by seberg — APPROVED** [review]
Thanks for the fix and good new tests!
