### PR TITLE
BUG: Raise TypeError on ternary power

### LINKED ISSUE #8805: BUG: Modular exponentiation fails silently
Raised in #8804. Modular power gives an incorrect result (due to not being implemented). Instead, it should error

    >>> pow(np.arange(10), 10, 3)
    array([         0,          1,       1024,      59049,    1048576,
              9765625,   60466176,  282475249, 1073741824, 3486784401])

### PR DESCRIPTION
**Pull request by eric-wieser**
... until we implement it in #8804. Fixes #8805

### CODE REVIEW

**Comment by eric-wieser** [comment]
This commit doesn't touch `gentype_power` - I can't work out a way to test that either

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 1]
```diff
@@ -149,11 +149,17 @@ gentype_free(PyObject *v)
 
 
 static PyObject *
-gentype_power(PyObject *m1, PyObject *m2, PyObject *NPY_UNUSED(m3))
+gentype_power(PyObject *m1, PyObject *m2, PyObject *modulo)
 {
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]: It's not entirely clear why this function exists - it seems to re-implement the op/rop dispatch that `PyNumber_Power` handles?

File: numpy/core/src/multiarray/number.c [hunk 2]
```diff
@@ -614,10 +614,14 @@ fast_scalar_power(PyArrayObject *a1, PyObject *o2, int inplace)
...
 static PyObject *
-array_power(PyArrayObject *a1, PyObject *o2, PyObject *NPY_UNUSED(modulo))
+array_power(PyArrayObject *a1, PyObject *o2, PyObject *modulo)
 {
-    /* modulo is ignored! */
     PyObject *value;
+    if (modulo != Py_None) {
+        /* modular exponentiation is not implemented (gh-8804) */
+        Py_INCREF(Py_NotImplemented);
+        return Py_NotImplemented;
```
Comment (MSeifert04) [inline numpy/core/src/multiarray/number.c]: why not just [`Py_RETURN_NOTIMPLEMENTED`](https://docs.python.org/3/c-api/object.html#c.Py_RETURN_NOTIMPLEMENTED)

Comment (eric-wieser) [inline numpy/core/src/multiarray/number.c]: Because right now we don't use that anywhere in numpy, so there's probably a consistency argument.

Do you want to make a PR that fixes this numpy-wide?

Comment (eric-wieser) [inline numpy/core/src/multiarray/number.c]: There's some strange code in `ctors.c` which does't `Py_INCREF` Py_NotImplemented, but I guess that's ok because the things that consume it don't `DECREF` in those cases either

Comment (eric-wieser) [inline numpy/core/src/multiarray/number.c]: Better answer - [`Py_RETURN_NOTIMPLEMENTED` is not available in 2.7](https://bugs.python.org/issue12724)

Comment (MSeifert04) [inline numpy/core/src/multiarray/number.c]: oups, that's a good argument 😅

**Review by mhvk — APPROVED** [review]
Looks good to me, no comments at all.

**Comment by charris** [comment]
Thanks Eirc.
