### PR TITLE
BUG: Ensure too many advanced indices raises an exception

### LINKED ISSUE #18145: Indexing a 1D array with a boolean tuple of length > 32 raises SIGABRT
Indexing an array with a boolean tuple of length >= 33 causes a stack overflow, whereas tuples of length <= 32 do not. I ran into this with some [contributed] code that expected list-like masks and got tuples instead. While there are probably few situations where you would want to index like this, it's probably better to check the input and raise an exception than to take down the whole process.

### Reproducing code example:

```python
import numpy as np

target = np.empty(2)
mask = tuple(True for _ in range(33))

target[mask]
```

### Error message:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff6c66633a libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff6c722e60 libsystem_pthread.dylib`pthread_kill + 430
    frame #2: 0x00007fff6c5ed8a2 libsystem_c.dylib`__abort + 139
    frame #3: 0x00007fff6c5c7d7b libsystem_c.dylib`__stack_chk_fail + 100
    frame #4: 0x0000000102901df2 _multiarray_umath.cpython-38-darwin.so`PyArray_MapIterNew + 5858
    frame #5: 0x00000001028f9da2 _multiarray_umath.cpython-38-darwin.so`array_subscript + 2370
    frame #6: 0x000000010016c978 python`_PyEval_EvalFrameDefault + 12152
    frame #7: 0x0000000100167de4 python`_PyEval_EvalCodeWithName + 564
    frame #8: 0x00000001001ed896 python`PyRun_FileExFlags + 358
    frame #9: 0x00000001001ecfd1 python`PyRun_SimpleFileExFlags + 577
    frame #10: 0x000000010021662f python`pymain_run_file + 463
    frame #11: 0x0000000100215b96 python`pymain_run_python + 534
    frame #12: 0x0000000100215925 python`Py_RunMain + 37
    frame #13: 0x00000001002170f1 python`pymain_main + 49
    frame #14: 0x00000001000012e8 python`main + 56
    frame #15: 0x00007fff6c51ecc9 libdyld.dylib`start + 1
    frame #16: 0x00007fff6c51ecc9 libdyld.dylib`start + 1
```

### NumPy/Python version information:

1.19.1 3.8.4 | packaged by conda-forge | (default, Jul 17 2020, 14:54:34)
[Clang 10.0.0 ]

### PR DESCRIPTION
**Pull request by seberg**
The number of indices is limited to 2*MAXDIMS currently to allow
mixing integer indices, e.g. with new indices `np.newaxis` (one
removes output dimensions, the other adds new ones).
This means that more than MAXDIMS advanced indices can be passed
on to the advanced indexing machinery (`MapIterNew`), which did
not check for this possibility.

Closes gh-18145

### CODE REVIEW

File: numpy/core/src/multiarray/mapping.c [hunk 1]
```diff
@@ -2369,6 +2369,19 @@ mapiter_fill_info(PyArrayMapIterObject *mit, npy_index_info *indices,
             }
         }
 
+        /* Before contunuing, ensure that there are not too fancy indices */
+        if (indices[i].type & HAS_FANCY) {
+            assert(indices[i].type == HAS_FANCY ||
```
Comment (charris) [inline numpy/core/src/multiarray/mapping.c:2374]: Is this needed?

Comment (seberg) [reply numpy/core/src/multiarray/mapping.c:2374]: Hmm, no, you are right. This assert is obviously always true, I confused myself and thought it might not be obvious, so I added it...

File: numpy/core/src/multiarray/mapping.c [hunk 2]
```diff
@@ -2369,6 +2369,19 @@ mapiter_fill_info(PyArrayMapIterObject *mit, npy_index_info *indices,
...
+                   indices[i].type == HAS_0D_BOOL);
```
Comment (seberg) [inline numpy/core/src/multiarray/mapping.c:2375]:
```suggestion
```

**Comment by charris** [comment]
Thanks Sebastian.
