### PR TITLE
BUG 4381 Longdouble from string without precision loss

### LINKED ISSUE #4381: BUG:  not assigning full precision values to longdouble scalars
If you try to set a longdouble scalar with a string, it appears to go through Python's normal string-parsing and therefore gets converted to a C double rather than a long double:

In [19]: numpy.longdouble("1.12345678901234567890")
Out[19]: 1.1234567890123456912

Note the loss of those last couple digits.

In [20]: numpy.float("1.12345678901234567890")
Out[20]: 1.1234567890123457

In [21]: numpy.longdouble("1.12345678901234567890") - numpy.float("1.12345678901234567890")
Out[21]: 0.0

And so internally they are identical.

One solution to this is a special case for longdoubles and to use strtold() to do the conversion.

Cheers,

Scott

### PR DESCRIPTION
**Pull request by aarchiba**
Fixes #4381 using sscanf. Also adds tests for #2376 and related loss of precision in string conversions.

### CODE REVIEW

**Comment by jaimefrio** [comment]
Python 3 is not your friend: it's complaining about a mismatch in the 19th decimal!

**Comment by njsmith** [comment]
Awesome, and looks good to me modulo test failures...

**Comment by juliantaylor** [comment]
probably won't work on windows, though there should be some other function with a different name which does the same.

**Comment by juliantaylor** [comment]
Oh no I confused this with strtoll which we fixed a while ago. Still should be tested on windows.

**Comment by aarchiba** [comment]
I don't have access to a Windows machine. With MSVC I think we have double==long double, which means this just has to not break anything. I know even less about Intel and other compilers on Windows. But shouldn't Travis check those?

**Comment by njsmith** [comment]
Travis is Linux only, unfortunately. There are other services like appveyor
that could be used in principle, but no one has done the work to set them
up for numpy yet, so in practice we mostly ignore windows ourselves and
then heroic people show up with Windows patches before each release.
.
In principle windows could do something horrible like have decided to error
out on long double specifiers in scanf (because who needs them, eh?), but I
don't think this fear should block merging this -- it's not really any more
risky than most PRs, and if it does happen then the fix would be easy.

**Comment by aarchiba** [comment]
See the discussion on bug #4381 for details, but locales are going to be a problem for this code. It is unclear how to work around the problem.

**Comment by njsmith** [comment]
Ugh, right, sscanf is also locale sensitive and everything is terrible.
.
I guess we might be able to get away with using sscanf_l these days?
Someone would have to double check that it's on whatever the oldest
supported osx version is, and also centos5, because I think that's
effectively the oldest Linux we support. But it might well be on both by
now; it's been around a while.
.
Also, we should probably add a test to Travis checking that the test suite
passes even in some locale with as many weird settings as possible, because
there's a lot of room here for bugs that silently give the wrong answer in
a way that we devs might never notice until it eats someone's data. (See:
how close we came to merging this PR.)

**Comment by aarchiba** [comment]
The _l functions would solve the problem, if present; that would probably imply strtold_l as well.

Fortunately foreign locale I/O is tested, for floats, in test_print.py and test_multiarray.py.

**Comment by njsmith** [comment]
My concern is that it sounds like the changes in this PR were broken in foreign locales, but we didn't notice because whatever tests we have aren't enough to catch it... maybe this just means extending those tests to make sure they cover all the different float widths?

**Comment by aarchiba** [comment]
That's just a shortcoming of this PR. All the other float widths go through Python's float object, so there is no need to test them separately. So did long doubles, which is why they lose precision upon conversion. The only thing to check is str/repr of long doubles, because that is supposed to retain full precision and therefore must have its own conversion code. %-printing, format(), and conversion from strings potentially suffer the same problem, but at the moment they go through floats.

**Comment by aarchiba** [comment]
The _l functions appeared in Darwin 8.0, FreeBSD 9.1, and were added to glibc in 1997, as far as I can tell. I would be astonished if they were missing from any Linux system people were still using. Windows I don't know about.

**Comment by njsmith** [comment]
Sweet. Windows we can live without (possibly with some annoying #ifdef)
given its lack of longdouble.

On Sun, Aug 16, 2015 at 1:28 AM, Anne Archibald <notifications@github.com>
wrote:

> The _l functions appeared in Darwin 8.0, FreeBSD 9.1, and were added to
> glibc in 1997, as far as I can tell. I would be astonished if they were
> missing from any Linux system people were still using. Windows I don't know
> about.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/pull/6199#issuecomment-131503743>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by aarchiba** [comment]
Okay, mostly what is needed now is to correctly detect whether strtold_l is available. I have all the ifdefs in place but I currently just unconditionally define it. Presumably it should be defined, if appropriate, in numpy/config.h, but I don't know how that is made.

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 1]
```diff
@@ -309,6 +317,85 @@ static int
...
+     * if it's not a string, we want to fall back to other
+     * approaches. In python 2, that happens when we try to
+     * convert the string to a C string. In python 3, we have
+     * to use a two-step conversion process, via bytes; the
+     * not-a-string situation gets triggered on conversion to 
+     * bytes, but we want to make sure bytes objects get 
+     * handled too, because python accepts bytes as input to
+     * float() (why?).
+     */
+#if PY_MAJOR_VERSION >= 3
```
Comment (aarchiba) [inline numpy/core/src/multiarray/arraytypes.c.src]: I have no experience with the python C API so I couldn't figure out how to write version-agnostic string code. But I think an ifdef is probably necessary to handle both byte and string objects in python 3.

Comment (charris) [inline numpy/core/src/multiarray/arraytypes.c.src]: Look in `numpy/core/include/numpy/py3_compat.h` for string routines. The ones available are the union of the py3k and py2k functions. My guess you will need to check for unicode and convert it to a byte string, then use `PyString_AS_STRING` to get the c ascii version.

The detection of `strtold_l` would be part of the configuration, which you can find scattered about in `numpy/core/setup_common.py`, `numpy/core/setup.py` and `numpy/core/bscript`. I haven't checked the check function to see if they will work with those particular functions. It might be easier to just copy the functions and make a library, but it looks like even `dtoa.c` has platform dependent bits.

**Comment by aarchiba** [comment]
I'm not sure how to debug the bento build, since I haven't had any luck getting bento to work on my machine. It looks like bento is detecting strtold_l but not #defining the correct macro, but I can't see inside the generated config.h.

**Comment by charris** [comment]
Yeah, bento makes things difficult. Current waf crashes bento on my setup (Fedora 22) and can't find atlas in any case. @rgommers Thoughts? I'd like to take another shot at removing bento from numpy, it doesn't buy much for speed, doesn't support all optimizations, and AFAIK, you are the only person who wants to keep it.

**Comment by rgommers** [comment]
> Yeah, bento makes things difficult. Current waf crashes bento on my setup (Fedora 22) and can't find atlas in any case. @rgommers Thoughts? I'd like to take another shot at removing bento from numpy, it doesn't buy much for speed, doesn't support all optimizations, and AFAIK, you are the only person who wants to keep it.

@cournape wants to keep it as well, but given that he's put Bento development on hold, I'm OK with this. I think it's a shame that we're going back to a single build system that no one likes, believes in as a future-proof solution or even wants to maintain - but I don't really have the time and energy required to improve that situation. So go ahead.

**Comment by pv** [comment]
Also, are the one-file builds still really necessary? That's also
something that could be scrapped...

**Comment by njsmith** [comment]
IIRC the one file builds are right now the only way to make cpython+numpy
static binaries. (Or part of the only way, I assume this requires
additional hacks as well.) There are other options that probably would work
(e.g. using objcopy,
http://mail.scipy.org/pipermail/numpy-discussion/2012-July/063120.html),
but I don't think anyone's tried. Probably because no one who statically
links numpy ever talks to us about it, so it's hard to know what matters or
how to support them...

**Comment by aarchiba** [comment]
Don't kill bento support on my account. If it comes to that I can submit debugging code to Travis.

**Comment by charris** [comment]
@aarchiba It's not you, it's me ;) The topic comes up regularly because we all run into the same difficulty supporting two build systems. If David were still working regularly to maintain and improve Bento there would be no problem, but he is out earning a living and having a life. While I agree with Ralf that a better system is desirable, in practice is more difficult to maintain the Bento build than the distutils version, and Bento has not fully supported Numpy for a while.

@rgommers If we decide at some point that there is a better build system I'll happily support it. @mwiebe chose CMake as the least evil alternative, but he doesn't *like* it. @eric-s-raymond likes scons, but David had to work hard, including upstream fixes, to get it working with numpy. It's an unfortunate situation and I don't know what the future holds, but I think we can keep distutils limping along for a few more years.

**Comment by charris** [comment]
I've posted to the list a proposal to remove Bento support.

**Comment by njsmith** [comment]
All build systems are terrible; it's like choosing between thumbscrews and the rack. The sooner one comes to terms with this reality the happier one will be.

I think the key enabler for better python build systems will be when it becomes possible to tell pip 'here's a script that when run will spit out a wheel, treat it as a black box otherwise'. Then one can stop worrying about distutils entirely, let pip worry about actually installing, etc., and just write a script/makefile/whatever to do this one well defined thing.

**Comment by rgommers** [comment]
> in practice is more difficult to maintain the Bento build than the distutils version

Since this thread may be referenced in the future a correction: this isn't actually the case. The only reason you see it that way is that ``numpy.distutils`` is much more heavily used and therefore gets more regular fixes. But it's harder to fix something in ``numpy.distutils``, due to worse architecture. And ``distutils`` patches not getting merged into Python makes that even worse (recent example: http://bugs.python.org/issue16296).

File: numpy/core/tests/test_longdouble.py [hunk 2]
```diff
@@ -0,0 +1,69 @@
+from __future__ import division, absolute_import, print_function
+
+import sys
+import locale
+import nose
```
Comment (charris) [inline numpy/core/tests/test_longdouble.py]: Looks unused.

File: numpy/core/tests/test_longdouble.py [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+    run_module_suite, assert_, assert_equal, dec, assert_raises
+)
+from test_print import in_foreign_locale
+
+longdouble_longer_than_double = (np.finfo(np.longdouble).eps
+                                 < np.finfo(np.double).eps)
+
+def test_scalar_extraction():
+    """Confirm that extracting a value doesn't convert to python float"""
+    o = 1+np.finfo(np.longdouble).eps
```
Comment (charris) [inline numpy/core/tests/test_longdouble.py]: Spaces around `+`, etc. Might want to run pep8 over this for style.

File: numpy/core/tests/test_longdouble.py [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+    assert_(repr(o) != '1')
+
+def test_repr_roundtrip():
+    o = 1+np.finfo(np.longdouble).eps
+    assert_equal(np.longdouble(repr(o)),o,
+                 "repr was %s" % repr(o))
+
+def test_unicode():
+    if sys.version_info < (3,):
+        np.longdouble(unicode("1.2"))
```
Comment (charris) [inline numpy/core/tests/test_longdouble.py]: Can use `sixu(...)` for this for Python version independence.
```
from numpy.compat import sixu
```

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 5]
```diff
@@ -309,6 +314,79 @@ static int
 
 /**end repeat**/
 
+#ifdef HAVE_STRTOLD_L
+static NPY_INLINE npy_longdouble string_to_long_double(PyObject*op)
```
Comment (charris) [inline numpy/core/src/multiarray/arraytypes.c.src]: Style
```
static NPY_INLINE npy_longdouble
string_to_long_double(...)
```
See `doc/C_STYLE_GUIDE.rst.txt`.

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 6]
```diff
@@ -309,6 +314,79 @@ static int
...
+    }
+    s = PyBytes_AsString(b);
+
+    if (s) {
+        locale_t clocale;
+        errno = 0; 
+        clocale = newlocale(LC_ALL_MASK, "C", NULL);
+        if (!clocale) {
+            PyErr_Format(PyExc_ValueError,
+                         "could not convert string to long double: unable to set up C locale (%s)",
```
Comment (charris) [inline numpy/core/src/multiarray/arraytypes.c.src]: 79 characters max in line.

Comment (charris) [inline numpy/core/src/multiarray/arraytypes.c.src]: Note `"is " "merged"` to `"is merged"`.

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 7]
```diff
@@ -309,6 +314,79 @@ static int
...
 
+#ifdef HAVE_STRTOLD_L
+static NPY_INLINE npy_longdouble string_to_long_double(PyObject*op)
+{
+    char *s;
+    char *end;
+    npy_longdouble temp;
+    PyObject* b;
+
+    /* This weird structure is to make the error handling work:
```
Comment (charris) [inline numpy/core/src/multiarray/arraytypes.c.src]: Blank line at beginniing of comment.

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 8]
```diff
@@ -309,6 +314,79 @@ static int
...
+    if (!b) {
+        /* Wasn't a string. Maybe it was a bytes? */
+        PyErr_Clear();
+        b = op;
+        Py_XINCREF(b);
+    }
+    s = PyBytes_AsString(b);
+
+    if (s) {
+        locale_t clocale;
```
Comment (charris) [inline numpy/core/src/multiarray/arraytypes.c.src]: Could put initialization on same line. Blank line after declaration.

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 9]
```diff
@@ -309,6 +314,79 @@ static int
...
+     * if it's not a string, we want to fall back to other
+     * approaches. In python 2, that happens when we try to
+     * convert the string to a C string. In python 3, we have
+     * to use a two-step conversion process, via bytes; the
+     * not-a-string situation gets triggered on conversion to 
+     * bytes, but we want to make sure bytes objects get 
+     * handled too, because python accepts bytes as input to
+     * float() (why?).
+     */
+    b = PyUnicode_AsUTF8String(op);
```
Comment (charris) [inline numpy/core/src/multiarray/arraytypes.c.src]: Could use the version independent unicode check before conversion. Is UTF8 what we want/need?

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 10]
```diff
@@ -309,6 +314,79 @@ static int
...
+        if (!clocale) {
+            PyErr_Format(PyExc_ValueError,
+                         "could not convert string to long double: unable to set up C locale (%s)",
+                         strerror(errno));
+            Py_XDECREF(b);
+            return 0;
+        }
+
+        temp = strtold_l(s, &end, clocale);
+
```
Comment (charris) [inline numpy/core/src/multiarray/arraytypes.c.src]: Perhaps excessive white space here.

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 11]
```diff
@@ -309,6 +314,79 @@ static int
...
+        freelocale(clocale);
+        
+        if (end==s || *end) {
+            PyErr_Format(PyExc_ValueError,
```
Comment (charris) [inline numpy/core/src/multiarray/arraytypes.c.src]: I tend to break the style guide for these and just indent the following line 4 spaces to get more room for strings.

File: numpy/core/tests/test_longdouble.py [hunk 12]
```diff
@@ -0,0 +1,69 @@
...
+    o = 1+np.finfo(np.longdouble).eps
+    assert_(repr(o) != '1')
+
+def test_repr_roundtrip():
+    o = 1+np.finfo(np.longdouble).eps
+    assert_equal(np.longdouble(repr(o)),o,
+                 "repr was %s" % repr(o))
+
+def test_unicode():
+    if sys.version_info < (3,):
```
Comment (charris) [inline numpy/core/tests/test_longdouble.py]: Maybe `sys.version_info[0] < 3`.

File: numpy/core/src/multiarray/arraytypes.c.src (hunk 9 above)
Comment (aarchiba) [inline numpy/core/src/multiarray/arraytypes.c.src]: I'm worried about duck typing. Basically if the input is string-like enough, I want it to get turned into a string. Unfortunately on python 2 non-unicode strings go through two conversions, so maybe a check would be better.

And if the string isn't ASCII it's not a valid number, but if this fails (by UnicodeError) we fall through to conversion via a python float, whereas if this succeeds we report an inability to convert from strtold. So UTF-8 avoids conversion failures here.

**Comment by aarchiba** [comment]
@charris I've heard that line before. But if I can figure out how to run bento I am willing to fix this patch to work with it, so that the removing-bento issue becomes orthogonal to the fixing-longdouble issue.

**Comment by aarchiba** [comment]
The Bento problem is currently: https://github.com/cournape/Bento/issues/147 , outstanding bug since last November.

**Comment by charris** [comment]
@aarchiba Don't worry about it. A similar incident triggered dropping support for Python 2.4 and 2.5. I think Nathaniel summed up the problem nicely, "I just feel that we shouldn't maintain two build systems
unless we're actively planning to get rid of one of them". Maintaining two build systems just isn't a good use of developer time and presents a barrier to new developers.

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 13]
```diff
@@ -309,6 +314,81 @@ static int
...
+                         "could not convert string to long double: "
+                         "unable to set up C locale (%s)",
+                         strerror(errno));
+            Py_XDECREF(b);
+            return 0;
+        }
+        temp = strtold_l(s, &end, clocale);
+        freelocale(clocale);
+        if (end==s || *end) {
```
Comment (charris) [inline numpy/core/src/multiarray/arraytypes.c.src]: Spaces around `==`.

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 14]
```diff
@@ -309,6 +314,81 @@ static int
 
 /**end repeat**/
 
+#ifdef HAVE_STRTOLD_L
+static NPY_INLINE npy_longdouble
+string_to_long_double(PyObject*op)
```
Comment (charris) [inline numpy/core/src/multiarray/arraytypes.c.src]: Space after `PyObject`.

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 15]
```diff
@@ -309,6 +314,81 @@ static int
...
+     * if it's not a string, we want to fall back to other
+     * approaches. In python 2, that happens when we try to
+     * convert the string to a C string. In python 3, we have
+     * to use a two-step conversion process, via bytes; the
+     * not-a-string situation gets triggered on conversion to
+     * bytes, but we want to make sure bytes objects get
+     * handled too, because python accepts bytes as input to
+     * float() (why?).
+     */
+    b = PyUnicode_AsUTF8String(op);
```
Comment (charris) [inline numpy/core/src/multiarray/arraytypes.c.src]: I'm still bothered by this. I think It would be cleaner and more direct to check for unicode type with `PyUnicode_Check`, which function is available in all the python versions. You can also use `PyBytes_Check` from `npy_3kcompat.h`., so maybe something like
```
if (PyUnicode_Check(op)) {
    op = PyUnicode_AsUTF8String(op);
}
if (PyBytes_Check(op) {
    do strtold_l stuff;
}
else {
    fallback;
}
```

File: numpy/core/tests/test_longdouble.py [hunk 16]
```diff
@@ -0,0 +1,121 @@
...
+@dec.knownfailureif(longdouble_longer_than_double, "BUG #2376")
+def test_percent():
+    o = 1 + np.finfo(np.longdouble).eps
+    assert_("%.40g" % o != '1')
+
+
+@dec.knownfailureif(longdouble_longer_than_double, "BUG #2376")
+def test_fromstring():
+    o = 1 + np.finfo(np.longdouble).eps
+    s = (" "+repr(o))*5
```
Comment (charris) [inline numpy/core/tests/test_longdouble.py]: Spaces around `+`.

File: numpy/core/tests/test_longdouble.py [hunk 17]
```diff
@@ -0,0 +1,121 @@
...
+    assert_equal(np.fromstring(s, sep=" ", dtype=np.longdouble), a,
+                 err_msg="reading '%s'" % s)
+
+
+@dec.knownfailureif(longdouble_longer_than_double, "BUG #2376")
+def test_loadtxt():
+    o = 1 + np.finfo(np.longdouble).eps
+    f = NamedTemporaryFile(mode="wt")
+    for i in range(5):
+        f.write(repr(o)+"\n")
```
Comment (charris) [inline numpy/core/tests/test_longdouble.py]: Spaces around `+`.

File: numpy/core/tests/test_longdouble.py [hunk 18]
```diff
@@ -0,0 +1,121 @@
...
+    a = np.array([o]*5)
+    assert_equal(np.loadtxt(f.name, dtype=np.longdouble), a)
+
+
+@dec.knownfailureif(longdouble_longer_than_double, "BUG #2376")
+def test_fromfile():
+    o = 1 + np.finfo(np.longdouble).eps
+    f = NamedTemporaryFile(mode="wt")
+    for i in range(5):
+        f.write(repr(o)+"\n")
```
Comment (charris) [inline numpy/core/tests/test_longdouble.py]: See above.

File: numpy/core/tests/test_longdouble.py [hunk 19]
```diff
@@ -0,0 +1,121 @@
...
+                             sep="\n"),
+                 a,
+                 err_msg=repr(open(f.name,"rt").read()))
+
+@dec.knownfailureif(longdouble_longer_than_double, "BUG #2376")
+def test_array_repr():
+    o = 1 + np.finfo(np.longdouble).eps
+    a = np.array([o])
+    b = np.array([1],dtype=np.longdouble)
+    assert_(repr(a)!=repr(b))
```
Comment (charris) [inline numpy/core/tests/test_longdouble.py]: Missing space(s) around `!=`.

File: numpy/core/tests/test_longdouble.py [hunk 20]
```diff
@@ -0,0 +1,121 @@
...
+                             dtype=np.longdouble,
+                             sep="\n"),
+                 a,
+                 err_msg=repr(open(f.name,"rt").read()))
+
+@dec.knownfailureif(longdouble_longer_than_double, "BUG #2376")
+def test_array_repr():
+    o = 1 + np.finfo(np.longdouble).eps
+    a = np.array([o])
+    b = np.array([1],dtype=np.longdouble)
```
Comment (charris) [inline numpy/core/tests/test_longdouble.py]: Space after ','.

File: numpy/core/tests/test_longdouble.py [hunk 21]
```diff
@@ -0,0 +1,121 @@
+from __future__ import division, absolute_import, print_function
+
+import locale
+from io import StringIO
```
Comment (charris) [inline numpy/core/tests/test_longdouble.py]: StringIO looks unused.

**Comment by charris** [comment]
Some style nitpicks.

**Comment by charris** [comment]
Closing & reopening to see if that gets rid of bento test.

**Comment by aarchiba** [comment]
Looking around, there are other places where long doubles are parsed - in particular, fromfile and fromstring both do their own parsing distinct from the constructor. Since they're in a different C file, I think I need to move my parsing code into NumpyOS, as a publicly-accessible service - both string-to-longdouble and file-to-longdouble (obviously sharing code). If we run into portability problems, currently it just falls back to going vie doubles, but eventually it might make sense to include a strtold implementation - GNU uses a version of dtoa parameterized over types to get float, double, long double, and quad.

**Comment by charris** [comment]
`numpyos` does look like the place where this should go.

**Comment by pv** [comment]
AFAIK numpyos is where the rest of the custom float parsing routines are...

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 22]
```diff
@@ -309,6 +308,53 @@ static int
...
 
+static NPY_INLINE npy_longdouble
+string_to_long_double(PyObject*op)
+{
+    char *s;
+    char *end;
+    npy_longdouble temp;
+    PyObject* b;
+
+    if (PyUnicode_Check(op)) {
```
Comment (aarchiba) [inline numpy/core/src/multiarray/arraytypes.c.src]: Checking here (as opposed to a duck-typed conversion) saves a string->unicode->string conversion on python 2. But given the error handling and the need to convert to a C string, it's easier to just convert the bytes to a C string and fall back to python conversion if that fails. EAFAP.

**Comment by aarchiba** [comment]
I am not able to replicate the failure on my own machine, so I'm afraid there will be a string of debugging pushes as I try to use Travis to debug the problem. I'm open to suggestions for how to replicate the python3.2 USE_DEBUG Travis run on my machine.

File: numpy/core/tests/test_longdouble.py [hunk 23]
```diff
@@ -0,0 +1,158 @@
...
+    assert_equal(np.genfromtxt(f.name, dtype=np.longdouble), a)
+    f.close()
+
+def test_fromfile():
+    o = 1 + np.finfo(np.longdouble).eps
+    f = NamedTemporaryFile(mode="wt")
+    for i in range(5):
+        f.write(repr(o) + "\n")
+    f.flush()
+    a = np.array([o]*5)
```
Comment (charris) [inline numpy/core/tests/test_longdouble.py]: This works for strings also
```
In [1]: 'hi'*5
Out[1]: 'hihihihihi'
```
which you could use above.

**Comment by charris** [comment]
Don't know what is going on there. Note that it may be easier to use StringIO and BytesIO than temporary files. IIRC, the latter can be tricky on windows. Might be worth looking at `numpy/lib/tests/test_io.py` to see how things are done there.

**Comment by aarchiba** [comment]
Sadly fromfile doesn't work with StringIO; you need an actual OS-level file descriptor.

**Comment by aarchiba** [comment]
Actually commit 6b356e6 is probably a standalone fix to bug #1481

File: numpy/core/src/multiarray/arraytypes.c.src (hunk 22 above)
Comment (charris) [inline numpy/core/src/multiarray/arraytypes.c.src]: Mostly I think it makes it easier to follow the code, otherwise six of one, half dozen of the other.

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 24]
```diff
@@ -309,6 +308,53 @@ static int
...
+        b = PyUnicode_AsUTF8String(op);
+        if (!b) {
+            return 0;
+        }
+    } else {
```
Comment (charris) [inline numpy/core/src/multiarray/arraytypes.c.src]:
```
}
else {
```

File: numpy/core/src/multiarray/ctors.c [hunk 25]
```diff
@@ -45,7 +45,16 @@ static int
 fromstr_next_element(char **s, void *dptr, PyArray_Descr *dtype,
                      const char *end)
 {
-    int r = dtype->f->fromstr(*s, dptr, s, dtype);
+    char *e = *s;
+    int r = dtype->f->fromstr(*s, dptr, &e, dtype);
+    /* fromstr always returns 0 for basic dtypes */
```
Comment (charris) [inline numpy/core/src/multiarray/ctors.c]: Multiline comments like so.
```
/*
 * blah
 */
```

**Comment by charris** [comment]
Looks about ready. Could you squash the commits? Note that github doesn't notify on branch updates, so it helps to make a comment.

What was the fix for the failing test?

**Comment by aarchiba** [comment]
Squash down to one, or to a few meaningful ones?

The failing test was testing tofile's behaviour with a specific separator but looking for a specific string representation (3.51 -> '3.51'). Python 2.6 didn't repr 3.51 as '3.51' but as 3.5099...98. So for that test I checked the commas and that the numbers round-tripped correctly. The next test tests what happens with a specific number of digits; that one I didn't need to change.

**Comment by aarchiba** [comment]
I would like to make "{0:.40f}".format(o) preserve the accuracy (no way to fix %, array printing already does) but that requires a conversion from format() strings to %-sequences, which will be a decidedly nontrivial function. So I'll make it a separate PR.

**Comment by charris** [comment]
Something like 1-3 commits, use your judgment. There are no  rules for that.

**Comment by aarchiba** [comment]
Squashed down to one commit.

**Comment by charris** [comment]
> If the function strtod_l is not available, almost none of this will work, and many tests will fail.

That is `strtold_l`, right? Hmm, we need to figure out a way around this. Is there a simple failing test that would serve to indicate the presence of strtold_l that could be used to skip failing tests?

**Comment by charris** [comment]
If there is no easy check, I'm thinking we really ought to have the defined macros somewhere accessible, say in numpy.__config__, but that is another project. If that looks like the proper solution this can go in and we can fix it up later.

**Comment by aarchiba** [comment]
A quick hack checks whether the constructor loses precision lets me set a variable. But yes, it would be nice if the results of config.h also got made visible at the python level.

**Comment by charris** [comment]
OK, in it goes. Thanks Anne. I spent so much time nitpicking that I was beginning to feel bad, thanks for your patience ;)

File: numpy/core/src/multiarray/numpyos.c [hunk 26]
```diff
@@ -451,6 +458,17 @@ NumPyOS_ascii_strtod(const char *s, char** endptr)
...
+    /*
+     * It is unclear why this function needs locale information.
+     * The goal is to do locale-independent parsing. This function
+     * contains code to stop the parsing early if an unusual decimal
+     * point is encountered and then pass the string so far to
+     * NumPyOS_ascii_strtod_plain, which will also stop if an unusual
+     * decimal point is encountered. The only case I can think of
+     * where this would matter is if the decimal separator were
+     * something that could occur in the middle of a valid number,
+     * in which case this function does the wrong thing.
```
Comment (pv) [inline numpy/core/src/multiarray/numpyos.c]: Under Python 2.6, PyOS_ascii_strtod refuses to parse the string at all, and returns an error instead of "1" which was the correct best-efforts result.

Comment (pv) [inline numpy/core/src/multiarray/numpyos.c]: If this was not clear from the comment below, it perhaps should be updated.

**Comment by pv** [comment]
The PyOS_ascii_strod issue seems to affect the long double parser:
```
>>> import sys
>>> sys.version_info
(2, 6, 8, 'final', 0)
>>> import numpy as np
>>> import locale
>>> locale.setlocale(locale.LC_ALL, 'fi_FI.UTF-8')
'fi_FI.UTF-8'
>>> np.fromstring('1,2345', sep=' ', dtype=np.longdouble)
array([], dtype=float128)
```

**Comment by pv** [comment]
Sorry, scratch that, I had some wrong version compiled. It does work,
```
np.fromstring('1,2345', sep=' ', dtype=np.double)
array([ 1.])
```

**Comment by aarchiba** [comment]
@charris well, I was getting embarrassed about all the stupid mistakes. Thanks for the attention, I'm getting my fingers retrained to numpy's coding style.

**Comment by charris** [comment]
@pv Looks like edits don't trigger github notifications either. What do you think needs to be done for the `strtold_l` not available case?

**Comment by aarchiba** [comment]
@pv I tried where possible to fall back to existing code. I have written basically that test in #6264 and can confirm that it works if I disable the strtod_l path. Also only the basic precision-loss test fails; the rest are knownfail.

**Comment by pv** [comment]
@aarchiba: did you try it on Python 2.6 (the only version affected, note you need the french locale available) --- I get test failures on that if I disable the `strtold_l` path? The easiest fix would be to call `NumPyOS_ascii_strtod` instead of `NumPyOS_ascii_strtod_plain` in the fallback path.

Without the `strtold_l` in addition to `test_longdouble.test_fromstring_foreign_sep` and `test_longdouble.test_fromstring_foreign_value` failures I also get
```
======================================================================
FAIL: test_longdouble.test_repr_roundtrip
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../numpy/core/tests/test_longdouble.py", line 36, in test_repr_roundtrip
    "repr was %s" % repr(o))
  File ".../numpy/testing/utils.py", line 354, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal: repr was 1.0000000000000000001
 ACTUAL: 1.0
 DESIRED: 1.0000000000000000001
```

**Comment by aarchiba** [comment]
The ``test_repr_roundtrip`` failure is intentional: users who lose precision should be informed about it. But all the other tests are switched off, so they're not swamped with test failures. I could turn this one off too, but then people without strtold_l would have no warning about a silent loss of precision that doesn't apply to other, more normal platforms. And they're presumably using long doubles because they know they need the extra precision. The important question is: how common is a missing strtold_l going to be? It's been around a long time.

**Comment by njsmith** [comment]
The simplest approach would just be to impose a hard dependency on
strtold_l, and deal with the fallout if/when someone finds a platform where
this causes compilation to fail...

On Fri, Aug 28, 2015 at 3:50 PM, Anne Archibald <notifications@github.com>
wrote:

> The test_repr_roundtrip failure is intentional: users who lose precision
> should be informed about it. But all the other tests are switched off, so
> they're not swamped with test failures. I could turn this one off too, but
> then people without strtold_l would have no warning about a silent loss of
> precision that doesn't apply to other, more normal platforms. And they're
> presumably using long doubles because they know they need the extra
> precision. The important question is: how common is a missing strtold_l
> going to be? It's been around a long time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/pull/6199#issuecomment-135905653>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by jaimefrio** [comment]
I'm getting the exact same failure as @pv on master using OS X Yosemite. Should I just get used to seeing it because it is a legit failure on this platform? I'm guessing a sizeable amount of development happens on OS X, so this may produce a lot of noise.

**Comment by aarchiba** [comment]
@jaimefrio that is obviously not okay. But Yosemite should have strtold_l. I have noticed that config.h is not always regenerated; could you try wiping your build directory and building again? If you still get test failures please file a bug report.

**Comment by jaimefrio** [comment]
Ah, much better now! ;-) A clean build did the trick for me. Thanks!
