### PR TITLE
ENH: Allow NEP 42 dtypes to use np.save and np.load

### LINKED ISSUE #24110: ENH: dtype API needs a hook in np.save and np.load
Currently if you try to use `np.save` and `np.load` with a new-style dtype, you'll get this error:

```
from stringdtype import StringDType
import numpy as np

arr = np.array(["hello", "world"], dtype=StringDType)
np.savez("arr.npz", arr)
with np.load("arr.npz") as data:
    larr = data['arr_0']
print(larr)
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/.pyenv/versions/3.10.9-debug/lib/python3.10/site-packages/numpy/lib/format.py:661, in _read_array_header(fp, version, max_header_size)
    660 try:
--> 661     dtype = descr_to_dtype(d['descr'])
    662 except TypeError as e:

File ~/.pyenv/versions/3.10.9-debug/lib/python3.10/site-packages/numpy/lib/format.py:306, in descr_to_dtype(descr)
    304 if isinstance(descr, str):
    305     # No padding removal needed
--> 306     return numpy.dtype(descr)
    307 elif isinstance(descr, tuple):
    308     # subtype, will always have a shape descr[1]

TypeError: data type '|\x0016' not understood

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
Cell In[10], line 7
      5 np.savez("arr.npz", arr)
      6 with np.load("arr.npz") as data:
----> 7     larr = data['arr_0']
      8 print(larr)

File ~/.pyenv/versions/3.10.9-debug/lib/python3.10/site-packages/numpy/lib/npyio.py:253, in NpzFile.__getitem__(self, key)
    251 if magic == format.MAGIC_PREFIX:
    252     bytes = self.zip.open(key)
--> 253     return format.read_array(bytes,
    254                              allow_pickle=self.allow_pickle,
    255                              pickle_kwargs=self.pickle_kwargs,
    256                              max_header_size=self.max_header_size)
    257 else:
    258     return self.zip.read(key)

File ~/.pyenv/versions/3.10.9-debug/lib/python3.10/site-packages/numpy/lib/format.py:786, in read_array(fp, allow_pickle, pickle_kwargs, max_header_size)
    784 version = read_magic(fp)
    785 _check_version(version)
--> 786 shape, fortran_order, dtype = _read_array_header(
    787         fp, version, max_header_size=max_header_size)
    788 if len(shape) == 0:
    789     count = 1

File ~/.pyenv/versions/3.10.9-debug/lib/python3.10/site-packages/numpy/lib/format.py:664, in _read_array_header(fp, version, max_header_size)
    662 except TypeError as e:
    663     msg = "descr is not a valid dtype descriptor: {!r}"
--> 664     raise ValueError(msg.format(d['descr'])) from e
    666 return d['shape'], d['fortran_order'], dtype

ValueError: descr is not a valid dtype descriptor: '|\x0016'
```

So at a minimum we need to update these functions to save the correct descriptor metadata to allow reconstructing the descriptor in `np.load`. 

For stringdtype we need sidecar storage, which might need a new revision to the [`npy` file format spec](https://numpy.org/doc/stable/reference/generated/numpy.lib.format.html#module-numpy.lib.format) to add extra metadata for the sidecar storage. However as a first pass we could just re-use the flag that's already in the file format spec that indicate the array data are stored in an inline pickle file.

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes #24110 

First, this makes it so that by default NEP 42 dtypes can't be pickled unless the dtype has a pickle implementation. Currently numpy will pickle them, but won't be able to unpickle them because the type code written to disk is invalid. Erroring is an improvement over writing corrupt files, I think.

Second, if a type *can* be pickled, this makes it so that `np.save` will save the array using pickle and will lie that the dtype is object (see @rkern's [suggestion](https://github.com/numpy/numpy/issues/24110#issuecomment-1624061648)). I've made it so if this happens a UserWarning will get printed. Unfortunately there's no way to indicate in the file that this really isn't an object array, so I can't do much on the load side to detect when this happens. Hopefully the `UserWarning` at save time is enough? I think adding a way to indicate in the file that we're not really storing an object array would require a revision to the `npy` file format, which ideally I'd like to avoid.

Last, added a pickle implementation to the scaled float test dtype and then added a test doing a round-trip save and load with a scale float array.

### CODE REVIEW

**Comment by seberg** [comment]
Tests are unhappy.  @rkern would you prefer more here?  I would be fine with doing this this even if it is not ideal; since I don't think it blocks the right solution and there is that warning anyway.
(Also, this does seem like the right thing to do for a DType which fails to implement whatever future solution we implement.)

**Comment by rkern** [comment]
Yeah, I think it's a fine short-term workaround. The warnings are appreciated.

**Comment by ngoldbaum** [comment]
> Tests are unhappy.

Good now, I was unknowingly using a too-new pytest feature.

File: numpy/core/src/umath/_scaled_float_dtype.c [hunk 1]
```diff
@@ -194,13 +194,76 @@ sfloat_get_scaling(PyArray_SFloatDescr *self, PyObject *NPY_UNUSED(args))
...
+
+    PyTuple_SET_ITEM(ret, 1, PyTuple_New(0));
+
+    state = PyTuple_New(1);
+
+    PyTuple_SET_ITEM(state, 0, PyFloat_FromDouble(self->scaling));
+
+    PyTuple_SET_ITEM(ret, 2, state);
+
+    return ret;
```
Comment (seberg) [inline numpy/core/src/umath/_scaled_float_dtype.c:237]:
```suggestion
    return Py_BuildValue("(O(d))", Py_TYPE(self), self->scaling);
```
Happy to monkey-patch numpy in the test, but then lets keep this simple.  (I don't generally love `Py_BuildValue`, but it can be nice and short.)

File: numpy/core/src/umath/_scaled_float_dtype.c [hunk 2]
```diff
@@ -194,13 +194,76 @@ sfloat_get_scaling(PyArray_SFloatDescr *self, PyObject *NPY_UNUSED(args))
...
+        return NULL;
+    }
+
+    double scaling = PyFloat_AsDouble(PyTuple_GET_ITEM(args, 0));
+
+    self->scaling = scaling;
+
+    Py_RETURN_NONE;
+}
+
```
Comment (seberg) [inline numpy/core/src/umath/_scaled_float_dtype.c:255]:
```suggestion
```
No need for setstate either.

File: numpy/core/src/umath/_scaled_float_dtype.c [hunk 3]
```diff
@@ -194,13 +194,76 @@ sfloat_get_scaling(PyArray_SFloatDescr *self, PyObject *NPY_UNUSED(args))
...
 PyMethodDef sfloat_methods[] = {
     {"scaled_by",
          (PyCFunction)python_sfloat_scaled_copy, METH_O,
         "Method to get a dtype copy with different scaling, mainly to "
         "avoid having to implement many ways to create new instances."},
     {"get_scaling",
         (PyCFunction)sfloat_get_scaling, METH_NOARGS, NULL},
+    {"__setstate__",
+       (PyCFunction)sfloat___setstate__, METH_O, NULL},
```
Comment (seberg) [inline numpy/core/src/umath/_scaled_float_dtype.c:264]:
```suggestion
```

**Review by seberg — COMMENTED** [review]
I think the test/SF reduce implementation can be drastically simplified.  The rest looks nice good though, thanks.
