### PR TITLE
BUG: Remove unnecessary copying and casting from out array in choose

### LINKED ISSUE #22237: BUG: `choose` does an unnecessary cast of the initial `out` values
### Describe the issue:

Choose (I think) always overwrites all values in the output.  It is thus unnecessary to cast a given `out` to the resulting dtype (if a cast is necesssary).

This can lead to spurious warnings as given in the below example

### Reproduce the code example:

```python
import numpy as np

a = np.arange(3)
b = np.ones((3, 3), dtype=np.int64)

out = np.array([np.nan, np.nan, np.nan])

np.choose(a, b, out=out)
```

### Error message:

```shell
/home/sebastian/forks/numpy/build/testenv/lib/python3.9/site-packages/numpy/core/fromnumeric.py:57: RuntimeWarning: invalid value encountered in cast
  return bound(*args, **kwds)
```

### NumPy/Python version information:

All versions up to 1.24-dev will do the unnecessary cast, but only the current dev gives the spurious warning.
(We have a typing test that could run into this randomly, although I am changing it in a different PR)

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by MaanasArora**
Resolves #22237.

This PR does not copy the existing `out` array in `np.choose`, instead creating the new output array from scratch and copying it back manually.

Thank you for reviewing!

### CODE REVIEW

**Comment by MaanasArora** [comment]
@ngoldbaum Added the test, thanks! It fails in `main` and passes in this branch.

File: numpy/_core/src/multiarray/item_selection.c [hunk 1]
```diff
@@ -1137,7 +1116,7 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
     PyDataMem_FREE(mps);
     if (out != NULL && out != obj) {
         Py_INCREF(out);
-        PyArray_ResolveWritebackIfCopy(obj);
+        PyArray_CopyAnyInto(out, obj);
```
Comment (ngoldbaum) [inline numpy/_core/src/multiarray/item_selection.c:1119]: This can fail so you need to check the failure case. The same bug existed in the code you're updating - `ResolveWritebackIfCopy` also returns -1 on failure.

**Review by ngoldbaum — COMMENTED** [review]
Just one small nitpick. I thought carefully about reference counts and didn't see any issues.

@seberg can you give this a once-over once the failure case for `CopyAnyInto` gets handled and hit the merge button assuming you don't see any additional issues?

File: numpy/_core/src/multiarray/item_selection.c (hunk 1 above)
Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c]: I added a simple failure check; hopefully that is sufficient. Thank you!

File: numpy/_core/src/multiarray/item_selection.c [hunk 2]
```diff
@@ -1137,7 +1116,10 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
     PyDataMem_FREE(mps);
     if (out != NULL && out != obj) {
         Py_INCREF(out);
-        PyArray_ResolveWritebackIfCopy(obj);
+        if (PyArray_CopyAnyInto(out, obj) != 0) {
```
Comment (ngoldbaum) [inline numpy/_core/src/multiarray/item_selection.c:1119]:
```suggestion
        if (PyArray_CopyAnyInto(out, obj) < 0) {
```

Slightly more defensive in case another non-error return code is added in the future (almost certainly won't happen but a good defensive programming habit to get into).

Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c]: That makes sense; I made this change, thanks.

File: numpy/_core/src/multiarray/item_selection.c [hunk 3]
```diff
@@ -1044,24 +1029,18 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
...
-        if (clipmode == NPY_RAISE) {
-            /*
-             * we need to make sure and get a copy
-             * so the input array is not changed
-             * before the error is called
-             */
-            flags |= NPY_ARRAY_ENSURECOPY;
-        }
-        Py_INCREF(dtype);
-        obj = (PyArrayObject *)PyArray_FromArray(out, dtype, flags);
```
Comment (seberg) [inline numpy/_core/src/multiarray/item_selection.c:1063]: Hmmmm, agree that this fixes the issue.  There is somewhat large downside, though: If the user passed an array that does full-fill all the requirements (not using clipmode raise, C-contiguous and aligned, and identical dtype), then we will now always do an unnecessary copy.

And that is a bit unfortunate, because it means that passing `out=...` never saves anythign compared to just assigning manually.

Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c:1063]: Ah right, in the case where flags is 0, we saved the copy on PyArray_FromArray, and that optimization is missing now. That indeed somewhat defeats the point of the optimization.

I'll revert the logic to the previous implementation and instead move around the conditions to include a check for the dtype. Thanks!

Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c:1063]: I modified the code to create a new array only when the dtype is different. Doesn't look too nice honestly, but is a commonsense way to optimize given our constraints.

**Comment by ngoldbaum** [comment]
Maybe also another test to make sure the unnecessary copy the old approach triggered doesn't happen?

**Comment by MaanasArora** [comment]
Not entirely sure if there's a convenient way to test for that in pytest? Even in the previous approach, there would probably be no 'sign' of a copy when the array is overwriten.

File: numpy/_core/src/multiarray/item_selection.c (hunk 3 above)
Comment (ngoldbaum) [reply numpy/_core/src/multiarray/item_selection.c:1070]: You could create a set of inputs to the function that trigger that bypass this code path on current `main` (e.g. by creating an `ip` array that is not C contiguous), and in that case check to make sure that a copy doesn't happen. You can check the `base` attribute of an ndarray to see if it's a view or copy:

```
In [1]: import numpy as np

In [2]: arr = np.array([1, 2, 3])

In [3]: newarr = arr[:2]

In [4]: newarr
Out[4]: array([1, 2])

In [5]: newarr.base
Out[5]: array([1, 2, 3])

In [6]: newarr.base is arr
Out[6]: True
```

Comment (ngoldbaum) [reply numpy/_core/src/multiarray/item_selection.c:1070]: And for a copy:

```
In [7]: newarr.copy()
Out[7]: array([1, 2])

In [8]: newarr.copy().base is None
True
```

Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c:1070]: Oh thank you for the guidance! That makes sense--on this.

Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c:1070]: Hmm. So on creating a test:

```python
def test_gh_28206():
    # no copy should be made in this case
    a = np.arange(3)
    b = np.ones((3, 3), dtype=np.int64)
    out = np.ones(3, dtype=np.int64)

    np.choose(a, b, out=out)
    assert out.base is not None
```

It fails on both the main branch and the new branch. It seems that by using `PyArray_FromArray`, we may be using the same buffer, creating neither a view nor a copy?

Comment (ngoldbaum) [reply numpy/_core/src/multiarray/item_selection.c:1070]: Hmm, so maybe it's not so east to test this:

```
In [1]: a = np.arange(3)
   ...: b = np.ones((3, 3), dtype=np.int64)

In [2]: out = np.empty_like(a)

In [3]: id(out)
Out[3]: 4363385904

In [4]: old_out = out

In [5]: ret = np.choose(a, b, out=out)

In [6]: id(out)
Out[6]: 4363385904

In [7]: old_out is out
Out[7]: True

In [8]: ret is out
Out[8]: True

In [9]: a = np.arange(3, dtype=np.int32)
   ...: b = np.ones((3, 3), dtype=np.int32)

In [10]: out = np.empty(3, dtype=np.int64)

In [11]: id(out)
Out[11]: 4364077264

In [12]: ret = np.choose(a, b, out=out)

In [13]: out
Out[13]: array([1, 1, 1])

In [14]: out.dtype
Out[14]: dtype('int64')

In [15]: id(out)
Out[15]: 4364077264

In [16]: out.base

In [17]: ret.dtype
Out[17]: dtype('int64')

In [18]: ret is out
Out[18]: True
```

Looking at the code, the return object is set to `out` and `out`'s descriptor gets replaced, so I guess this is all expected.

Never mind about the test.

@seberg do you see any issues with the new approach here after your last suggestion?

**Comment by MaanasArora** [comment]
Sorry about the accidental changes--I'll be more careful with Git

File: numpy/_core/src/multiarray/item_selection.c [hunk 4]
```diff
@@ -1067,7 +1069,18 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
             flags |= NPY_ARRAY_ENSURECOPY;
         }
         Py_INCREF(dtype);
-        obj = (PyArrayObject *)PyArray_FromArray(out, dtype, flags);
+        if (!PyArray_EquivTypes(dtype, PyArray_DESCR(out))) {
+            obj = (PyArrayObject *)PyArray_NewFromDescr(Py_TYPE(out),
```
Comment (seberg) [inline numpy/_core/src/multiarray/item_selection.c:1073]: I don't think there is any reason to use `Py_TYPE(out)` here, just pass `NULL` and get a base-class array, I think.

(There _is_ a subtle issue here about that, I think, in that ufuncs would ensure they call `__array_wrap__` when done and we don't.  But this a completely different issue!)

File: numpy/_core/src/multiarray/item_selection.c (hunk 3 above)
Comment (seberg) [reply numpy/_core/src/multiarray/item_selection.c:1070]: This looks correct to me.  But now we can (and should) simplify it more.  We used the flags to enforce a copy when (please double check):
1. The dtype doesn't match
2. The array is not contiguous or not aligned
3. There is a memory overlap.

I really don't think point 2 matters.  You have covered the dtype now explicitly.  Which leaves the memory overlap, which we can just also take this branch!

File: numpy/_core/src/multiarray/item_selection.c [hunk 5]
```diff
@@ -1067,7 +1069,18 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
...
+                                                        NULL, NULL, 0,
+                                                        (PyObject *)out);
+            is_newarr = 1;
+        }
+        else {
+            obj = (PyArrayObject *)PyArray_FromArray(out, dtype, flags);
+        }
     }
 
     if (obj == NULL) {
```
Comment (seberg) [inline numpy/_core/src/multiarray/item_selection.c:1086]: Can't comment lower, but we should adjust the `PyArray_GetDTypeTransferFunction` to use `PyArray_DESCR(obj)` for the second dtype.

There is a subtle thing that i.e. `StringDType` can be equivalent but _not_ identical (which is totally fine!).
(I.e. this code _should_ currently lead to crashes if used on the new `StringDType`, I believe.  New tests for that would be awesome, but I am happy to overlook that.)

File: numpy/_core/src/multiarray/item_selection.c [hunk 6]
```diff
@@ -1144,7 +1157,17 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
     PyDataMem_FREE(mps);
     if (out != NULL && out != obj) {
         Py_INCREF(out);
-        PyArray_ResolveWritebackIfCopy(obj);
+        int success;
+        if (is_newarr) {
+            success = PyArray_CopyAnyInto(out, obj);
```
Comment (seberg) [inline numpy/_core/src/multiarray/item_selection.c:1162]: In theory, you could set the base-object to your allocation above and set to use `WritebackIfCopy` even with your custom allocation.  But, TBH, I think a direct copy is actually clearer (frankly, I am not sure if we couldn't use it in half the places `ResolveWritebackIfCopy` is used ;)).

**Review by seberg — COMMENTED** [review]
Thanks a lot, yes I think this is correct now!  I also think we can simplify things more, by just adding a `must_copy` flag and using your new branch then unconditionally.

File: numpy/_core/src/multiarray/item_selection.c (hunk 4 above)
Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c:1073]: Makes sense thanks, but looking at the doc for `PyArray_NewFromDescr`, should we pass `&PyArray_Type` instead? `NULL` causes a `ValueError`.

File: numpy/_core/src/multiarray/item_selection.c (hunk 3 above)
Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c:1070]: Oh forgot about `clipmode=raise`. So, we have three conditions: dtype, memory overlap, and clipmode raise. Thinking about how to simplify that.

File: numpy/_core/src/multiarray/item_selection.c (hunk 4 above)
Comment (seberg) [reply numpy/_core/src/multiarray/item_selection.c:1073]: Yes, of course.  Somehow thought it accepted NULL as PyArray_Type there.

File: numpy/_core/src/multiarray/item_selection.c (hunk 5 above)
Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c:1086]: I adjusted the function, and added a test for `StringDType`, which does not crash now!

File: numpy/_core/tests/test_multiarray.py [hunk 7]
```diff
@@ -1984,6 +1984,14 @@ def test_choose(self):
         y = np.choose([0, 0, 0], [x[:3], x[:3], x[:3]], out=x[1:4], mode='wrap')
         assert_equal(y, np.array([0, 1, 2]))
 
+        # gh-28206 test new StringDType casting
+        x = np.array(['a', 'b', 'c'], dtype=np.dtypes.StringDType())
+        y = np.array(['abc', 'def', 'ghi'], dtype=np.dtypes.StringDType())
```
Comment (seberg) [inline numpy/_core/tests/test_multiarray.py:1989]: Subtle thing, but make sure to include a long string (otherwise you can't trigger the path which might have crashed).

File: numpy/_core/src/multiarray/item_selection.c (hunk 4 above)
Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c:1073]: I made the change but it seems to fail a regression test `test_attributes` that tests for an identical `info` string assigned to the out array.

File: numpy/_core/src/multiarray/item_selection.c (hunk 6 above)
Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c:1163]: I see--good to know!

File: numpy/_core/tests/test_multiarray.py (hunk 7 above)
Comment (MaanasArora) [reply numpy/_core/tests/test_multiarray.py:1989]: Actually that still seems to crash, thanks for noticing. I think `PyArray_ConvertToCommonType` (it seems to be a backward compatibility function) does not cast properly to a common scenario for `StringDType`, and `EquivTypes` passes the `dtype` unchanged--so, we end up with the `dtype` only for the first array. Should we do a promotion of some sort if the types are equivalent? Or perhaps, for now, we can ensure they are _identical_?

File: numpy/_core/src/multiarray/item_selection.c (hunk 4 above)
Comment (seberg) [reply numpy/_core/src/multiarray/item_selection.c:1073]: Maybe push, but may not look at it today. I really don't see why it matters since `obj` is never returned to the user!  (And not understanding that worries me more than the change ;)).

File: numpy/_core/src/multiarray/item_selection.c [hunk 8]
```diff
@@ -1144,7 +1158,17 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
...
+        }
+        else {
+            success = PyArray_ResolveWritebackIfCopy(obj);
+        }
+        if (success < 0) {
+            Py_DECREF(obj);
+            goto fail;
```
Comment (seberg) [inline numpy/_core/src/multiarray/item_selection.c:1170]: Just noticed: this is wrong!  At this point the code already did most/all cleanup and doing that again will cause crashes.  So you just need to do a straight `return NULL`.

File: numpy/_core/src/multiarray/item_selection.c (hunk 4 above)
Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c:1073]: No problem at all, thanks for the feedback. Yes, it is a bit confusing...

File: numpy/_core/src/multiarray/item_selection.c (hunk 5 above)
Comment (seberg) [reply numpy/_core/src/multiarray/item_selection.c:1086]: Honestly, I thought this may be a new issue.  But it is clearly an existing bug and maybe the best thing is to just leave it out here.

I suppose `CastToCommonType` is buggy, in that it should ensure identical (view-castable), which we have a helper for now.
(I.e. replacing an `EquivTypes` with the new helper, but I forgot that helpers name :))

File: numpy/_core/src/multiarray/item_selection.c (hunk 3 above)
Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c:1070]: Just pushed this!

File: numpy/_core/src/multiarray/item_selection.c [hunk 9]
```diff
@@ -1064,10 +1062,29 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
...
+                                                        multi->dimensions,
+                                                        NULL, NULL, 0,
+                                                        (PyObject *)out);
+        }
+        else {
+            int flags = NPY_ARRAY_CARRAY |
+                        NPY_ARRAY_WRITEBACKIFCOPY |
+                        NPY_ARRAY_FORCECAST;
+
+            obj = (PyArrayObject *)PyArray_FromArray(out, dtype, flags);
```
Comment (seberg) [inline numpy/_core/src/multiarray/item_selection.c:1086]: This branch should now never copy, so the only thing it should be doing is check for `PyArray_FailUnlessWriteable`.  That also means you don't need the writeback-if-copy branch below.

(We can check that earlier also, since it doesn't make sense to wait until the last copy for this to fail in the other branch either.)

File: numpy/_core/src/multiarray/item_selection.c [hunk 10]
```diff
@@ -1144,7 +1162,16 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
...
     if (out != NULL && out != obj) {
         Py_INCREF(out);
-        PyArray_ResolveWritebackIfCopy(obj);
+        int success;
+        if (is_newarr) {
+            success = PyArray_CopyAnyInto(out, obj);
+        }
+        else {
+            success = PyArray_ResolveWritebackIfCopy(obj);
+        }
```
Comment (seberg) [inline numpy/_core/src/multiarray/item_selection.c:1171]: And thus, you never need this branch here either.

**Review by seberg — COMMENTED** [review]
Thanks, but one more iteration, I think.  The idea here was to always manually copy out rather than use any auto-setup via `PyArray_FromArray` and that final writebackifcopy finalization.

So, I think both should be gone at the end, because otherwise it is confusing when what happenes.

File: numpy/_core/src/multiarray/item_selection.c [hunk 11]
```diff
@@ -1028,6 +1028,7 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
     }
     dtype = PyArray_DESCR(mps[0]);
 
+    int is_newarr = 0;
```
[the remark this answers is not in the document]
Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c]: I used `copy_existing_out`, which hopefully isn't too clumsy!

File: numpy/_core/src/multiarray/item_selection.c (hunk 9 above)
Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c]: Makes sense, thanks! Addressed this.

File: numpy/_core/src/multiarray/item_selection.c (hunk 10 above)
Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c]: This as well.

File: numpy/_core/src/multiarray/item_selection.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c]: Wait, wasn't `is_newarr` maybe more fitting as it _also_ applies when the array is created from scratch (in `out == NULL`)? It seems to be a special case of `out != NULL && obj != out` _after_ `out` is assigned. I'll do `out_newarr` maybe?

[the remark this answers is not in the document]
Comment (seberg) [reply numpy/_core/src/multiarray/item_selection.c]: Maybe, in my mind it doesn't apply to `out == NULL`, because to me it tells us if we need to copy back at the end (as well).

[the remark this answers is not in the document]
Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c]: Ah okay, what about `copy_out`? Since it's not user passed...

File: numpy/_core/src/multiarray/item_selection.c (hunk 4 above)
Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c]: Oops, I think I was editing the wrong line! Things work fine now, pushed. Thanks.

File: numpy/_core/src/multiarray/item_selection.c [hunk 12]
```diff
@@ -1038,7 +1038,7 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
                                                     multi->dimensions,
                                                     NULL, NULL, 0,
                                                     (PyObject *)ap);
-        out_newarr = 1;
+        copy_out = 1;
```
Comment (seberg) [inline numpy/_core/src/multiarray/item_selection.c:1041]:
```suggestion
```

File: numpy/_core/src/multiarray/item_selection.c [hunk 13]
```diff
@@ -1052,9 +1050,11 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
             goto fail;
         }
 
+        PyArray_FailUnlessWriteable(out, "output array");
```
Comment (seberg) [inline numpy/_core/src/multiarray/item_selection.c:1053]: Can you please add a test for this, because this doesn't work, you need an error return check and deal with that (this is not C++ with exceptions).

File: numpy/_core/src/multiarray/item_selection.c [hunk 14]
```diff
@@ -1064,10 +1064,25 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
...
+        if (copy_out) {
+            obj = (PyArrayObject *)PyArray_NewFromDescr(&PyArray_Type,
+                                                        dtype,
+                                                        multi->nd,
+                                                        multi->dimensions,
+                                                        NULL, NULL, 0,
+                                                        (PyObject *)out);
+        }
+        else {
+            obj = (PyArrayObject *)PyArray_FromArray(out, dtype, 0);
```
Comment (seberg) [inline numpy/_core/src/multiarray/item_selection.c:1084]: Please _only_ incref here and assign to `obj`.  We rely on that being true now.

File: numpy/_core/src/multiarray/item_selection.c (hunk 12 above)
Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c:1041]: Oh yes, your naming suggestion makes total sense now 😓 I'll change that back too, thanks!

File: numpy/_core/src/multiarray/item_selection.c (hunk 13 above)
Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c]: Ah yes sorry, fixed this, adding a test now.

File: numpy/_core/src/multiarray/item_selection.c (hunk 14 above)
Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c:1085]: Sorry, just to be clear, this would be the `dtype`? Made that change.

File: numpy/_core/src/multiarray/item_selection.c (hunk 13 above)
Comment (MaanasArora) [reply numpy/_core/src/multiarray/item_selection.c]: Test is pushed.

File: numpy/_core/src/multiarray/item_selection.c [hunk 15]
```diff
@@ -1064,10 +1065,25 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
...
+            Py_INCREF(dtype);
+            obj = (PyArrayObject *)PyArray_NewFromDescr(&PyArray_Type,
+                                                        dtype,
+                                                        multi->nd,
+                                                        multi->dimensions,
+                                                        NULL, NULL, 0,
+                                                        (PyObject *)out);
+        }
+        else {
+            obj = (PyArrayObject *)PyArray_FromArray(out, dtype, 0);
```
Comment (seberg) [inline numpy/_core/src/multiarray/item_selection.c:1085]:
```suggestion
            obj = (PyArrayObject *)Py_NewRef(out);
```

File: numpy/_core/src/multiarray/item_selection.c [hunk 16]
```diff
@@ -1144,7 +1161,11 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
     PyDataMem_FREE(mps);
     if (out != NULL && out != obj) {
         Py_INCREF(out);
```
Comment (seberg) [inline numpy/_core/src/multiarray/item_selection.c:1163]:
```suggestion
    if (copy_existing_out) {
```

File: numpy/_core/src/multiarray/item_selection.c [hunk 17]
```diff
@@ -1052,9 +1049,13 @@ PyArray_Choose(PyArrayObject *ip, PyObject *op, PyArrayObject *out,
             goto fail;
         }
 
+        if (PyArray_FailUnlessWriteable(out, "output array") < 0) {
+            return NULL;
```
Comment (seberg) [inline numpy/_core/src/multiarray/item_selection.c:1053]:
```suggestion
            goto fail;
```

**Review by seberg — APPROVED** [review]
LGTM, modulo some refactors (e.g. error refcounting was wrong).
