### PR TITLE
BUG,ENH: fix pickling user-scalars by allowing non-format buffer export 

### LINKED ISSUE #17294: __reduce__ no longer works on user defined types
I'm migrating from 1.13.3 to 1.17.4 and calling `__reduce__` no longer works on our user defined types.  Ultimately this stops me being able to pickle these objects.  I've verified this problem is still present in the latest release 1.19.2 and the latest master.

### Reproducing code example:
This can be demonstrated with the rational user defined type that is provided with numpy
```
python3
>>> import numpy.core._rational_tests
>>> numpy.core._rational_tests.rational(1,2).__reduce__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: cannot include dtype 'r' in a buffer
```

On 1.13.3 this worked fine
```
python3
>>> import numpy.core.test_rational
>>> numpy.core.test_rational.rational(1,2).__reduce__()
(<built-in function scalar>, (dtype(rational), b'\x01\x00\x00\x00\x01\x00\x00\x00'))
```

### Numpy/Python version information:
1.17.4 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0]

### Analysis

Looks like this arises from migrating to the new buffer protocol in https://github.com/numpy/numpy/pull/10564 involving @vanossj and @eric-wieser   This invokes a different code path that calls _buffer_format_string and this does not support user defined types.  In fact, PyObject_GetBuffer is being called with PyBUF_SIMPLE so it won't even use the results from _buffer_format_string.

One possible fix is to support user defined types in buffer.c:_buffer_format_string 

From
```
        default:
            PyErr_Format(PyExc_ValueError,
                         "cannot include dtype '%c' in a buffer",
                         descr->type);
            return -1;
        }
```
To
```
        default:
            if (PyTypeNum_ISUSERDEF(descr->type_num))
            {
                if (_append_char(str, descr->kind) < 0) return -1;
                break;
            }            
            PyErr_Format(PyExc_ValueError,
                         "cannot include dtype '%c' in a buffer",
                         descr->type);
            return -1;
        }
```

### PR DESCRIPTION
**Pull request by seberg**
This should close gh-17294 by allowing to export buffers for user defined types if the buffer export does not ask for the FORMAT to be filled it.

The diff is based on top of gh-16936 (which touches the same code), so marking it as draft.

### CODE REVIEW

File: numpy/core/src/multiarray/buffer.c [hunk 1]
```diff
@@ -538,9 +577,10 @@ _buffer_info_cmp(_buffer_info_t *a, _buffer_info_t *b)
     Py_ssize_t c;
     int k;
 
-    c = strcmp(a->format, b->format);
-    if (c != 0) return c;
-
+    if (a->format != NULL && b->format != NULL) {
+        c = strcmp(a->format, b->format);
+        if (c != 0) return c;
+    }
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/buffer.c:583]: Hmm, this looks risky - are you sure it shouldn't be:
```suggestion
    /* null format sorts before empty string */
    c = (a->format != NULL) - (b->format != NULL);
    if (c != 0) return c;
    
    if (a->format != NULL && b->format != NULL) {
        c = strcmp(a->format, b->format);
        if (c != 0) return c;
    }
```
Otherwise `NULL` is considered equal to arbitrary strings, and equality is not transitive

File: numpy/core/src/multiarray/buffer.c [hunk 2]
```diff
@@ -706,7 +771,9 @@ array_getbuffer(PyObject *obj, Py_buffer *view, int flags)
     }
 
     /* Fill in information */
-    info = _buffer_get_info(obj);
+    info = _buffer_get_info(obj,
+            (flags & PyBUF_F_CONTIGUOUS) == PyBUF_F_CONTIGUOUS,
+            (flags & PyBUF_FORMAT) == PyBUF_FORMAT);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/buffer.c:776]: it's looking increasingly like maybe we should just pass in the full flags argument

File: numpy/core/src/multiarray/buffer.c (hunk 1 above)
Comment (seberg) [reply numpy/core/src/multiarray/buffer.c:583]: Yes, should be correct. if the format is `NULL` it seems OK to replace it with any other format. Now if the old (first) format is `NULL`, we will replace the `NULL` with the actual (second) format.  If the second format is `NULL`, format is ignored completely, so it is fine as well.

Comment (seberg) [reply numpy/core/src/multiarray/buffer.c:583]: An empty string would indicate that the itemsize is 0 in the exported buffer, I guess. A size change could seem problematic, but I do not think so.

In theory, changing the itemsize might be dangerous, but it is explicitly stored in the exported buffer info, so while it could be dangerous from a buffer user perspective, I do not think it is dangerous for having incorrect information inside the exported buffer information.

File: numpy/core/src/multiarray/buffer.c (hunk 2 above)
Comment (seberg) [reply numpy/core/src/multiarray/buffer.c:776]: Hmmm, fair point, could pass in the flags.

File: numpy/core/src/multiarray/buffer.c (hunk 1 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/buffer.c:583]: Where does this replacing of `NULL` happen?

Comment (seberg) [reply numpy/core/src/multiarray/buffer.c:583]: https://github.com/numpy/numpy/pull/17295/files#diff-761c5d4c611d2cd411341182fcee883dR662

File: numpy/core/src/multiarray/buffer.c (hunk 2 above)
Comment (mattip) [reply numpy/core/src/multiarray/buffer.c:776]: Is this still relevant?

Comment (seberg) [reply numpy/core/src/multiarray/buffer.c]: Changed it and rebased. The rebase means the code changed slightly here (basically, I undid a bit of fixup that I did in the other PR to make this one easier, because I got it wrong...).

**Comment by seberg** [comment]
Test failure on 32bit linux looks real. Going to restart out of curiosity if it is reproducible (since I have currently no idea why it would fail).

<details> <summary> Failure </summary>

```
=================================== FAILURES ===================================
_______ TestNewBufferProtocol.test_export_and_pickle_user_dtype[scalar] ________

self = <numpy.core.tests.test_multiarray.TestNewBufferProtocol object at 0xec9d1238>
obj = rational(1,2), error = <class 'TypeError'>

    @pytest.mark.parametrize(["obj", "error"], [
            pytest.param(np.array([1, 2], dtype=rational), ValueError, id="array"),
            pytest.param(rational(1, 2), TypeError, id="scalar")])
    def test_export_and_pickle_user_dtype(self, obj, error):
        # User dtypes should export successfully when FORMAT was not requested.
        with pytest.raises(error):
            _multiarray_tests.get_buffer_info(obj, ("STRIDED", "FORMAT"))
    
        _multiarray_tests.get_buffer_info(obj, ("STRIDED",))
    
        # This is currently also necessary to implement pickling:
        res = pickle.loads(pickle.dumps(obj))
>       assert_array_equal(res, obj)
E       AssertionError: 
E       Arrays are not equal
E       
E       Mismatched elements: 1 / 1 (100%)
E       Max absolute difference: rational(255,514)
E       Max relative difference: rational(255,257)
E        x: array(rational(1,257), dtype=rational)
E        y: array(rational(1,2), dtype=rational)

error      = <class 'TypeError'>
obj        = rational(1,2)
res        = rational(1,257)
self       = <numpy.core.tests.test_multiarray.TestNewBufferProtocol object at 0xec9d1238>

../../venv/lib/python3.8/site-packages/numpy/core/tests/test_multiarray.py:7159: AssertionError
```

File: numpy/core/src/multiarray/scalarapi.c [hunk 3]
```diff
@@ -168,7 +168,7 @@ scalar_value(PyObject *scalar, PyArray_Descr *descr)
      * Use the alignment flag to figure out where the data begins
      * after a PyObject_HEAD
      */
-    memloc = (npy_intp)scalar;
+    memloc = (uintptr_t)scalar;
```
Comment (seberg) [inline numpy/core/src/multiarray/scalarapi.c:171]: Seems like this casting to signed was the problem (and I first thought it can't be because the denominator is stored as a `denom - 1` here making the `2` a `1`...

If the value is too large, it would be a negative which breaks the rounding (and also means that a previously aligned value looks unaligned).

**Comment by seberg** [comment]
Should we aim to backport this? It does fix an older regression.

**Comment by mattip** [comment]
Does this need any documentation changes? I don't think pickling a user-scalar is very common, but will this impact any of the serialization protocols?

**Comment by seberg** [comment]
Hmm, this fixes two things:

1. Exporting buffers without a requested format now always works
2. The fix about user-scalars is a regression. If it was not, I am not sure I would worry about it.

**Comment by seberg** [comment]
Ah, I guess its important to note that allowing buffers to always be exported only affects datetime and user-dtypes, so is a pretty niche thing, could add a release notes anyway...
