### PR TITLE
BUG: `OBJECT_to_*` should check for errors

### LINKED ISSUE #11993: Python 3.7 can cast object to complex type
### Reproducing code example:

```python
import numpy as np
print(np.__version__)
arr = np.array(['AAAAA', 18465886.0, 18465886.0], dtype=object)
print(arr.astype(np.complex64))
print(arr.astype(np.complex64)) 
```

### Error message:
Python3.6 works as I would expect (complains that it cannot convert a string to complex dtype)
```
$ python3.6 test.py 
1.16.0.dev0+7fcba41
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    print(arr.astype(np.complex64))
TypeError: must be real number, not str
```
Python3.7 converts it to a complex type and then errors if you try to do it again
```
$ python3.7 test.py 
1.16.0.dev0+7fcba41
[-6.3090155e-31+4.558e-41j  1.8465886e+07+0.000e+00j
  1.8465886e+07+0.000e+00j]
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    print(arr.astype(np.complex64)) 
TypeError: must be real number, not str
```
### Numpy/Python version information:
```
>>> import sys
>>> sys.version
'3.7.0b3 (default, Mar 30 2018, 04:35:22) \n[GCC 7.3.0]'
>>> import numpy as np
>>> np.__version__
'1.16.0.dev0+7fcba41'
```

### PR DESCRIPTION
**Pull request by ahaldane**
Fixes #11993

The problem was `OBJECT_to_*` did not quit on error, and the error was cleared by subsequent calls (in `PyArray_IsScalar` in `CDOUBLE_setitem`, it seems). Probably in python3.7 they must have added a call to `PyErr_Clear` somewhere, which exposed this bug.

### CODE REVIEW

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 1]
```diff
@@ -1489,10 +1489,14 @@ OBJECT_to_@TOTYPE@(void *input, void *output, npy_intp n,
 
     for (i = 0; i < n; i++, ip++, op += skip) {
         if (*ip == NULL) {
-            @TOTYPE@_setitem(Py_False, op, aop);
+            if (@TOTYPE@_setitem(Py_False, op, aop)) {
```
Comment (charris) [inline numpy/core/src/multiarray/arraytypes.c.src]: `func(...) < 0` is the preferred idiom for these checks. I assume an error is set on failure and checked somewhere down the call chain?

**Comment by charris** [comment]
LGTM apart from a stylistic nit.

**Comment by charris** [comment]
Thanks Allan.
