### PR TITLE
DEP: Deprecate coercion to subarray dtypes

### LINKED ISSUE #17173: Regression in array creation `np.array([...], dtype='(2,2)f4')` RuntimeError  (Zarr testsuite )
### Reproducing code example:

This is used as a test case in the Zarr codebase, it seem to be failing since #16200

```
import numpy as np
a = np.array([((0, 1),
                       (1, 2)),
                      ((1, 2),
                       (2, 3)),
                      ((2, 3),
                       (3, 4))], dtype='(2,2)f4')
```
### Error message:

```python
In [1]: import numpy as np
   ...: a = np.array([((0, 1),
   ...:                        (1, 2)),
   ...:                       ((1, 2),
   ...:                        (2, 3)),
   ...:                       ((2, 3),
   ...:                        (3, 4))], dtype='(2,2)f4')
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-0a6ed20baa50> in <module>
      5                        (2, 3)),
      6                       ((2, 3),
----> 7                        (3, 4))], dtype='(2,2)f4')

RuntimeError: Inconsistent object during array creation? Content of sequences changed (now too shallow).
```

### Numpy/Python version information:

```
2cfcf56cd1f9465871e355620465b0b734f1f56c is the first bad commit
commit 2cfcf56cd1f9465871e355620465b0b734f1f56c
Author: Sebastian Berg <sebastian@sipsolutions.net>
Date:   Fri May 8 09:13:57 2020 -0500

    WIP: Seems pretty good, but needs cleaning up...

:040000 040000 45409277bf118ad5a5e9badfd37f5522f26841b2 7186520518984483cbae2f28001fe883855df00f M	numpy
```

Multiple Pythons (3.7, 3.8), Multiple OS (Mac, Linux), though I bisected only on Linux/3.7.

I

### PR DESCRIPTION
**Pull request by seberg**
When coercing to subarray dtypes, e.g. using `np.array(obj, dtype)`,
but also `arr.astype(dtype)`, the behaviour was only well defined
with tuple inputs, but not with array-like inputs.
In particular, `arr.astype(dtype)` had arguably surprising behaviour
of not converting by element, but rather attempting (and often failing)
to broadcast `arr` to the result array with added dimensions.

This deprecates all of these cases, the main issue would be for users
relying on stranger inputs with broadcasted tuples contained in
sequences:
```
np.array([((0, 1), (1, 2)), ((2,),)], dtype='(2,2)f4')
```

In most cases, where the tuples have the correct output shape,
the new base dtype can be directly used since the discovered shape
should match.
However, there is no work-around for the above case.

Closes gh-17173

### CODE REVIEW

**Comment by seberg** [comment]
In a sense, the arguably correct solution would be to only do the "dimension absorbing" step **after** doing all the assignment (reshaping/viewing the array before returning).  The problem is that this changes the behaviour of current array-likes the same way as in the `arr.astype()` case.  But, if we want to go there, it may be possible to do a `FutureWarning` instead, and keep a nested list-of-tuples unchanged.  The scalar case is another ugly wart:
```
In [2]: np.array(3, dtype="(5)i,")                                                                                      
Out[2]: array([ 3,  0,  0,  0, 32], dtype=int32)
```
since it returns uninitialized memory :(.

File: numpy/core/src/multiarray/ctors.c [hunk 1]
```diff
@@ -1367,6 +1367,160 @@ PyArray_GetArrayParamsFromObject(PyObject *NPY_UNUSED(op),
...
+/*
+ * This function is a legacy implementation to retain subarray dtype
+ * behaviour in array coercion. The behaviour here makes sense if tuples
+ * of matching dimensionality are being coerced. Due to the difficulty
+ * that the result is ill-defined for lists of array-likes, this is deprecated.
+ *
+ * WARNING: Do not use this function, it exists purely to support a deprecated
+ *          code path.
+ */
+static int
```
Comment (seberg) [inline numpy/core/src/multiarray/ctors.c:1379]: In case it isn't obvious from the comment. Do not review this function, it is a straight copy from the 1.19.x branch.

**Comment by mattip** [comment]
Putting this in. We may need to revert the deprecation if real use cases arise.

**Comment by mattip** [comment]
Thanks @seberg

**Comment by pllim** [comment]
Hello. `astropy` sees this deprecation warning while attempting to parse VO table. Any advise on how to mitigate this warning on our end? Please see astropy/astropy#10815 for more information. Thank you!
