### PR TITLE
BUG: introduce PyArray_SafeCast to fix issues around stringdtype views

### LINKED ISSUE #26140: BUG: creating an array that shares memory with a stringdtype array can fail
The following test case will fail on `main`:

```
import numpy as np
# strings long enough to live in the arena
string_list = ["abc", "def", "ghi" * 10, "A¢☃€ 😊" * 100, "Abc" * 1000, "DEF"]
arr = np.array(string_list, dtype=np.dtypes.StringDType())
arr_rev = np.array(string_list[::-1], dtype=np.dtypes.StringDType())

arr_view = np.array(arr, copy=None, dtype=arr_rev.dtype)
np.testing.assert_array_equal(arr, arr_view)
```

This is happening because of the code path here:

https://github.com/numpy/numpy/blob/6d4a0f74e89ac4a015742be896e99142a78c5a10/numpy/_core/src/multiarray/multiarraymodule.c#L1612-L1636

In the test case, `oldtype != dtype`, so we enter the path that calls `NewFromDescrAndBase` with the user-provided dtype. The problem is the user-provided dtype doesn't know anything about the arena that lives on the original dtype, so blindly accepting the user-provided dtype and passing it to `NewFromDescrAndBase` corrupts the arena.

I think a way to fix this would be to call `finalize_descr` on the user-provided DType to get a fresh descriptor if its already owned by the array, and then force the user-provided dtype to share allocators with the original dtype. We could also copy the arena, but that goes against the user desire to not have a copy.

Another way to handle this is to make stringdtype *always* copy in this situation, and error if someone passes `copy=False`. 

_Originally posted by @ngoldbaum in https://github.com/numpy/numpy/issues/26082#issuecomment-2021391412_

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes #26140.

This is a minimal implementation of a new function that generalizes `PyArray_EquivTypes`.

### CODE REVIEW

File: numpy/_core/src/multiarray/multiarraymodule.c [hunk 1]
```diff
@@ -1481,6 +1481,26 @@ PyArray_EquivTypes(PyArray_Descr *type1, PyArray_Descr *type2)
...
+{
+    if (!PyArray_EquivTypes(type1, type2)) {
+        return 0;
+    }
+    // a view of a stringdtype array has a corrupt arena, unless
+    // type1 and type2 are exactly the same object
+    if ((type1 != type2) && (type1->kind == 'T')) {
+        return 0;
+    }
+    return 1;
```
Comment (seberg) [inline numpy/_core/src/multiarray/multiarraymodule.c:1500]: Need to dig slightly deeper and use this pattern: https://github.com/numpy/numpy/blob/51fd714301f5fff8f8d6068951e0fdd44e98415d/numpy/_core/src/umath/ufunc_object.c#L790-L812

Making this not be string dtype specific!

Comment (ngoldbaum) [reply numpy/_core/src/multiarray/multiarraymodule.c:1500]: ah nice and then I can control how `view_offset` gets set in `string_to_string_resolve_descriptors`, that seems much more idiomatic

Comment (ngoldbaum) [reply numpy/_core/src/multiarray/multiarraymodule.c]: So this idea doesn't quite work as cleanly as I'd hoped. If I set `view_offset != 0` in `string_to_string_resolve_descriptors`, there's an assert that triggers if `casting == NPY_NO_CASTING`:

https://github.com/numpy/numpy/blob/e1bf1d635016a0118f7d77bf8931071a2c74ad20/numpy/_core/src/multiarray/convert_datatype.c#L465-L482

In the latest version I'm about to push I guard that `assert` with an if statement that checks for stringdtype, but that seems unsatisfying. Maybe the correct thing is for stringdtype to set e.g. `NPY_EQUIV_CASTING` for casts with distinct allocators, but when I tried doing that it broke reductions and I couldn't see a clear path forward on fixing that, because the check for valid reductions relies on `PyArray_EquivTypes`, which enfoces `NPY_NO_CASTING` as the minimum casting level:

https://github.com/numpy/numpy/blob/e1bf1d635016a0118f7d77bf8931071a2c74ad20/numpy/_core/src/umath/ufunc_object.c#L2394-L2411

Maybe we need a new casting level between `NO_CASTING` and `EQUIV_CASTING` for this case where data can live outside the array buffer on the descriptor?

Comment (seberg) [reply numpy/_core/src/multiarray/multiarraymodule.c]: I think we can probably just remove the assert, just need to make sure to not document anywhere that no-casting *implies* view (I doubt we use it anywhere, but not sure).  It used to, for these strings it can't since they use a whole new mechanism for storage... that seems fine.
(you could keep the assert together with checking that the dtype implements the hook for fixing the dtype in the array creation call, given that reason.)

**Comment by charris** [comment]
What is the status of this?

**Comment by ngoldbaum** [comment]
I think it just needs another round of review. It’s not critical for the RC but it would be good to have it in.

File: numpy/_core/src/multiarray/multiarraymodule.c [hunk 2]
```diff
@@ -1481,6 +1481,49 @@ PyArray_EquivTypes(PyArray_Descr *type1, PyArray_Descr *type2)
...
+         * `PyArray_Descr *`.  We assume that `type(type(type(arbitrary_obj))`
+         * is always in practice `type` (this is the type of the metaclass),
+         * but for our descriptors, `type(type(descr))` is DTypeMeta.
+         *
+         * In that case, we just return False.  There is a possibility that
+         * this actually _worked_ effectively (returning 1 sometimes).
+         * We ignore that possibility for simplicity; it really is not our bug.
+         */
+        return 0;
+    }
```
[the remark this answers is not in the document]
Comment (seberg) [reply numpy/_core/src/multiarray/multiarraymodule.c:1511]: I think we can remove it, as it I am very certain it was fixed in boost python a while ago.

File: numpy/_core/src/multiarray/multiarraymodule.c [hunk 3]
```diff
@@ -1481,6 +1481,49 @@ PyArray_EquivTypes(PyArray_Descr *type1, PyArray_Descr *type2)
...
+    NPY_CASTING safety = PyArray_GetCastInfo(type1, type2, NULL, &view_offset);
+    if (safety < 0) {
+        PyErr_Clear();
+        return 0;
+    }
+    if (view_offset != 0) {
+        return 0;
+    }
+    /* If casting is "no casting" this dtypes are considered equivalent. */
+    return PyArray_MinCastSafety(safety, NPY_NO_CASTING) == NPY_NO_CASTING;
```
[the remark this answers is not in the document]
Comment (seberg) [reply numpy/_core/src/multiarray/multiarraymodule.c:1523]: Fair, could add that as a code comment if you like.

File: numpy/_core/src/multiarray/stringdtype/casts.c [hunk 4]
```diff
@@ -79,7 +79,8 @@ string_to_string_resolve_descriptors(PyObject *NPY_UNUSED(self),
         return NPY_UNSAFE_CASTING;
     }
 
-    *view_offset = 0;
+    // views are only legal between descriptors that share allocators (e.g. the same object)
+    *view_offset = descr0->allocator != descr1->allocator;
```
Comment (seberg) [inline numpy/_core/src/multiarray/stringdtype/casts.c:83]: This is wrong. You must set it to 0 or leave it unchanged! (Intp min, I think)

File: numpy/_core/src/multiarray/multiarraymodule.c [hunk 5]
```diff
@@ -1481,6 +1481,49 @@ PyArray_EquivTypes(PyArray_Descr *type1, PyArray_Descr *type2)
 }
 
 
+/*
+ * This function returns true if a view can be safely created
+ * between the two types. This implies that PyArray_EquivTypes
+ * is true as well.
+ */
+NPY_NO_EXPORT unsigned char
+PyArray_ViewableTypes(PyArray_Descr *type1, PyArray_Descr *type2)
```
Comment (seberg) [inline numpy/_core/src/multiarray/multiarraymodule.c:1490]: Maybe we can encode the equiv in the name? Or pass in the cast safety? Passing it in would make it work in the ufunc code I think.

But if not its OK.

**Review by seberg — APPROVED** [review]
This is good, but the view offset **needs fixing**.  I cannot review if other places using eqivtypes shojld be using this meaning, right now.

Its maybe subtle but only really affects strings, so with that fix happy to see it in. (Other comments could wait).

File: numpy/_core/src/multiarray/multiarraymodule.c [hunk 6]
```diff
@@ -1609,7 +1652,11 @@ _array_fromobject_generic(
 
         /* One more chance for faster exit if user specified the dtype. */
         oldtype = PyArray_DESCR(oparr);
-        if (PyArray_EquivTypes(oldtype, dtype)) {
+        unsigned char viewable = PyArray_ViewableTypes(oldtype, dtype);
```
Comment (seberg) [inline numpy/_core/src/multiarray/multiarraymodule.c:1655]: The equiv cast may not matter, but then a single field struct to non-struct could return views... not today, I guess

**Comment by ngoldbaum** [comment]
Thanks for the prompt to refactor so I could use it in `ufunc_object.c`, the result is a bit more understandable and hopefully more useful.

Now instead of `PyArray_ViewableTypes`, I'm calling the new function `PyArray_SafeCast`, which is a generalization of `PyArray_EquivTypes` that accepts the minimum casting safety and also allows callers to see the view_offset value. I was able to use this new function in the trivial ufunc loop setup code.

**Comment by ngoldbaum** [comment]
Even though sebastian approved this, probably worth one more round of review before merging after the last commit.

File: numpy/_core/src/multiarray/multiarraymodule.h [hunk 7]
```diff
@@ -21,4 +21,9 @@ NPY_VISIBILITY_HIDDEN extern PyObject * npy_ma_str_convert_if_no_array;
 NPY_VISIBILITY_HIDDEN extern PyObject * npy_ma_str_cpu;
 NPY_VISIBILITY_HIDDEN extern PyObject * npy_ma_str_array_err_msg_substr;
 
+NPY_NO_EXPORT npy_intp
```
Comment (mhvk) [inline numpy/_core/src/multiarray/multiarraymodule.h:24]: Is this the right module to define it in? I know `PyArray_EquivTypes` is here, but maybe `casts.c` makes more sense?

File: numpy/_core/src/umath/ufunc_object.c [hunk 8]
```diff
@@ -806,8 +807,8 @@ check_for_trivial_loop(PyArrayMethodObject *ufuncimpl,
                  * can  force cast to bool)
                  */
             }
-            else if (PyArray_MinCastSafety(safety, casting) != casting) {
-                return 0;  /* the cast is not safe enough */
+            else if (is_safe != 1) {
```
Comment (mhvk) [inline numpy/_core/src/umath/ufunc_object.c:810]: Just `!is_safe`?

File: numpy/_core/tests/test_stringdtype.py [hunk 9]
```diff
@@ -458,6 +458,23 @@ def test_creation_functions():
     assert np.empty(3, dtype="T")[0] == ""
 
 
+def test_create_with_copy_none(string_list):
+    arr = np.array(string_list, dtype=StringDType())
+    arr_rev = np.array(string_list[::-1], dtype=StringDType())
```
Comment (mhvk) [inline numpy/_core/tests/test_stringdtype.py:463]: Could you add a comment here, like `# Create a copy with the same dtype but its own allocator`

**Review by mhvk — COMMENTED** [review]
Looks good. Mostly just queries/requests for clarification

File: numpy/_core/src/multiarray/multiarraymodule.c [hunk 10]
```diff
@@ -1481,6 +1464,33 @@ PyArray_EquivTypes(PyArray_Descr *type1, PyArray_Descr *type2)
 }
 
 
+/*
+ * This function returns true if the two types can be safely cast at
+ * *minimum_safety* casting level. Sets the view_offset if that is set
+ * for the cast. If ignore_error is 1, errors in cast setup are ignored.
+ */
+NPY_NO_EXPORT npy_intp
```
[the remark this answers is not in the document]
Comment (ngoldbaum) [reply numpy/_core/src/multiarray/multiarraymodule.c:1472]: Thanks, remnant of an older version that unconditionally ignored errors.

**Comment by ngoldbaum** [comment]
All review comments should be resolved now

File: numpy/_core/src/umath/ufunc_object.c (hunk 8 above)
Comment (ngoldbaum) [reply numpy/_core/src/umath/ufunc_object.c:809]: This one actually needs to specifically compare with 1, because `is_safe` can be negative here without the error indicator being set above.

Worth adding a comment you think?

Comment (ngoldbaum) [reply numpy/_core/src/umath/ufunc_object.c:809]: specifically `test_trivial_loop_invalid_cast` fails if I apply your suggestion

File: numpy/_core/src/multiarray/ctors.c [hunk 11]
```diff
@@ -1921,8 +1923,13 @@ PyArray_FromArray(PyArrayObject *arr, PyArray_Descr *newtype, int flags)
...
            /* If a writeable array was requested, and arr is not */
            ((flags & NPY_ARRAY_WRITEABLE) &&
-                   (!(arrflags & NPY_ARRAY_WRITEABLE))) ||
-           !PyArray_EquivTypes(oldtype, newtype);
+                   (!(arrflags & NPY_ARRAY_WRITEABLE)));
+
+    if (!copy) {
+        npy_intp view_offset;
+        npy_intp is_safe = PyArray_SafeCast(oldtype, newtype, &view_offset, NPY_NO_CASTING, 1);
+        copy = copy || !(is_safe && (view_offset != NPY_MIN_INTP));
```
Comment (mhvk) [inline numpy/_core/src/multiarray/ctors.c:1931]: My suggestion was imperfect: this can be `copy = !(is_safe...` since we know `copy` is false.

File: numpy/_core/src/umath/ufunc_object.c (hunk 8 above)
Comment (mhvk) [reply numpy/_core/src/umath/ufunc_object.c:809]: Ah, yes, I missed that the constraint above also checked the error, sorry.

**Review by mhvk — APPROVED** [review]
Looks good! A suggestion for a tiny further improvement in-line, though probably barely worth the CI since the compiler will likely do it already.

**Comment by ngoldbaum** [comment]
Pulling this one in, thanks for the review!
