### PR TITLE
BUG: Let 0-D arrays of Python timedelta convert to np.timedelta64.

### LINKED ISSUE #11151: BUG: Cannot convert 0d object array to timedelta
```python
>>> import datetime
>>> np.array(datetime.timedelta(seconds=20)).astype(np.timedelta64)
TypeError: len() of unsized object
```

### PR DESCRIPTION
**Pull request by tylerjereddy**
Fixes #11151.

It is now possible to convert 0 dimensional `datetime.timedelta` NumPy object arrays to `np.timedelta64` 0 dimensional NumPy arrays. 

The linked issue does not specify other 0 dimensional NumPy object array-related datetime issues so this patch initially aims only to fix that specific reported scenario, but I've added a comment in the C source suggesting that other 0 dimensional object array type checks / handling might be needed in the future.

### CODE REVIEW

File: numpy/core/src/multiarray/datetime.c [hunk 1]
```diff
@@ -3746,6 +3746,27 @@ recursive_find_object_datetime64_type(PyObject *obj,
     }
 }
 
+/* handler function for PyDelta values
```
Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: We generally prefer the first line of these to be blank,
```
/*
 * blah
 */
```

File: numpy/core/src/multiarray/datetime.c [hunk 2]
```diff
@@ -3746,6 +3746,27 @@ recursive_find_object_datetime64_type(PyObject *obj,
...
+ * which may also be in a 0 dimensional
+ * NumPy array
+ */
+static int
+delta_checker(PyObject *obj,
+	      PyArray_DatetimeMetaData *meta)
```
Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: the function header fits nicely on a single line.

File: numpy/core/src/multiarray/datetime.c [hunk 3]
```diff
@@ -3746,6 +3746,27 @@ recursive_find_object_datetime64_type(PyObject *obj,
...
+{
+    PyArray_DatetimeMetaData tmp_meta;
+
+    tmp_meta.base = NPY_FR_us;
+    tmp_meta.num = 1;
+
+    /* Combine it with 'meta' */
+    if (compute_datetime_metadata_greatest_common_divisor(meta,
```
Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: might as well move all the arguments to the next line
```
if (compute_datetime_metadata_greatest_common_divisor(
        meta, &tmp_meta, meta, 0, 0) < 0) {
```

File: numpy/core/src/multiarray/datetime.c [hunk 4]
```diff
@@ -3783,6 +3804,29 @@ recursive_find_object_timedelta64_type(PyObject *obj,
         else if (arr_dtype->type_num != NPY_OBJECT) {
             return 0;
         }
+        else {
+            Py_ssize_t ndim;
+            ndim = PyArray_NDIM((PyArrayObject *)obj);
+            if (ndim == 0) {
+                /* special handling of 0 dimensional
```
Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: See above.

Comment (charris) [reply numpy/core/src/multiarray/datetime.c]: might also justify a bit to lessen the number of lines.

File: numpy/core/src/multiarray/datetime.c [hunk 5]
```diff
@@ -3783,6 +3804,29 @@ recursive_find_object_timedelta64_type(PyObject *obj,
...
+                 * NumPy object arrays, which may be
+                 * indexed to retrieve their single
+                 * object using [()], but not by using
+                 * __getitem__(integer) approaches
+                 */
+                PyObject *item, *meth, *args;
```
Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: Blank line after declarations.

File: numpy/core/src/multiarray/datetime.c [hunk 6]
```diff
@@ -3783,6 +3804,29 @@ recursive_find_object_timedelta64_type(PyObject *obj,
...
+                meth = PyObject_GetAttrString(obj, "__getitem__");
+                args = Py_BuildValue("(())");
+                item = PyObject_CallObject(meth, args);
+                /* NOTE: may need other type checks
```
Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: See above.

File: numpy/core/src/multiarray/datetime.c [hunk 7]
```diff
@@ -3783,6 +3804,29 @@ recursive_find_object_timedelta64_type(PyObject *obj,
         else if (arr_dtype->type_num != NPY_OBJECT) {
             return 0;
         }
+        else {
+            Py_ssize_t ndim;
+            ndim = PyArray_NDIM((PyArrayObject *)obj);
```
Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: Blank line after declarations.
The return type of `PyArray_NDIM` is `int`, any reason to change that?

Comment (charris) [reply numpy/core/src/multiarray/datetime.c]: I note that up above `arr` is already the cast of `obj`, so why not
```
            if (PyArray_NDIM(arr) == 0) {
```

File: numpy/core/src/multiarray/datetime.c [hunk 8]
```diff
@@ -3746,6 +3746,27 @@ recursive_find_object_datetime64_type(PyObject *obj,
     }
 }
 
+/*
+ * handler function for PyDelta values
+ * which may also be in a 0 dimensional
+ * NumPy array
+ */
+static int
+delta_checker(PyObject *obj, PyArray_DatetimeMetaData *meta)
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/datetime.c]: Why does this function not touch `obj`?

Comment (tylerjereddy) [reply numpy/core/src/multiarray/datetime.c]: The function is nothing more than a container for the code I abstracted from the original function because it is now duplicated.

I think a lot of the datetime handling happens at a metadata level & can indeed just remove the `obj` argument here I think.

**Comment by charris** [comment]
Thanks Tyler.
