### PR TITLE
MAINT: More cleanup of einsum

### LINKED ISSUE #11221: BUG: Wrong error reporting in einsum
See this example:

```
>>> a = np.ones((3, 3, 4, 5, 6))
>>> b = np.ones((3, 4, 5))
>>> np.einsum('aabcb,abc', a, b)
ValueError: dimensions in operand 0 for collapsing index 'c' don't match (4 != 6)
```

The `4 != 6` mismatch is for collapsing index `'b'`, not `'c'`.

This is due to `get_combined_dims_view` in `einsum.c.src` overwriting the labels array as it parses it to remove duplicates, see [here](https://github.com/numpy/numpy/blob/maintenance/1.14.x/numpy/core/src/multiarray/einsum.c.src#L2212)

So by the time the mismatch in the 5th dimension is detected, the `'b'` in position 3 has been overwritten by the `'c'` in position 4, leading to the wrong reporting.

### PR DESCRIPTION
**Pull request by jaimefrio**
Somewhat simplifies the code inside get_single_op_view, moves logic out of the main einsum function loop, and fixes #11221.

### CODE REVIEW

File: numpy/core/src/multiarray/einsum.c.src [hunk 1]
```diff
@@ -2103,96 +2102,108 @@ get_single_op_view(PyArrayObject *op, int  iop, char *labels,
...
+_no_labels_are_negative(char *labels, int ndim)
+{
+    int idim;
+
+    for (idim = 0; idim < ndim; ++idim) {
+        /*
+         * The char type may be either signed or unsigned, we
+         * need it to be signed here.
+         */
+        int label  = (signed char)labels[idim];
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/einsum.c.src]: nit: extra space here

File: numpy/core/src/multiarray/einsum.c.src [hunk 2]
```diff
@@ -2103,96 +2102,108 @@ get_single_op_view(PyArrayObject *op, int  iop, char *labels,
     return 0;
 }
 
+static int
+_no_labels_are_negative(char *labels, int ndim)
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/einsum.c.src]: Maybe just pass a `signed char*` instead?

File: numpy/core/src/multiarray/einsum.c.src [hunk 3]
```diff
@@ -2092,83 +2091,101 @@ get_single_op_view(PyArrayObject *op, int  iop, char *labels,
...
+static int
+_no_labels_are_negative(signed char *labels, int ndim)
+{
+    int idim;
+
+    for (idim = 0; idim < ndim; ++idim) {
+        /*
+         * The char type may be either signed or unsigned, we
+         * need it to be signed here.
+         */
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/einsum.c.src]: This comment might make more sense above the function definition

File: numpy/core/src/multiarray/einsum.c.src [hunk 4]
```diff
@@ -2092,83 +2091,101 @@ get_single_op_view(PyArrayObject *op, int  iop, char *labels,
...
+        int label = labels[idim];
+
+        if (label < 0) {
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/einsum.c.src]: Could just write `if (labels[idim] < 0)` here, now that there's no casting to worry about

File: numpy/core/src/multiarray/einsum.c.src [hunk 5]
```diff
@@ -2092,83 +2091,101 @@ get_single_op_view(PyArrayObject *op, int  iop, char *labels,
     return 0;
 }
 
+static int
+_no_labels_are_negative(signed char *labels, int ndim)
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/einsum.c.src]: I'd maybe prefer `_any_labels_are_negative`, and then use it with a preceding `!`. Functions with inverted names are a little confusing - also `any` is common python terminology

File: numpy/core/src/multiarray/einsum.c.src [hunk 6]
```diff
@@ -2092,83 +2091,101 @@ get_single_op_view(PyArrayObject *op, int  iop, char *labels,
...
+ * original array is reference increased and returned unchanged.
+ */
 static PyArrayObject *
 get_combined_dims_view(PyArrayObject *op, int iop, char *labels)
 {
     npy_intp new_strides[NPY_MAXDIMS];
     npy_intp new_dims[NPY_MAXDIMS];
-    int idim, ndim, icombine, combineoffset;
+    int idim, icombine;
     int icombinemap[NPY_MAXDIMS];
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/einsum.c.src]: Any chance you could comment `icombinemap`, assuming you've worked out what it does?

File: numpy/core/src/multiarray/einsum.c.src [hunk 7]
```diff
@@ -2092,83 +2091,101 @@ get_single_op_view(PyArrayObject *op, int  iop, char *labels,
...
         /*
          * The char type may be either signed or unsigned, we
          * need it to be signed here.
          */
         int label = (signed char)labels[idim];
-        /* If this label says to merge axes, get the actual label */
+        npy_intp dim = PyArray_DIM(op, idim);
+        npy_intp stride = PyArray_STRIDE(op, idim);
+
+        /* A repeated label, find the original one and merge them. */
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/einsum.c.src]: This would make more sense to me with the `if` and `else` swapped - since that way the write to `icombinemap` is seen before the read from it.

File: numpy/core/src/multiarray/einsum.c.src [hunk 8]
```diff
@@ -2092,83 +2091,101 @@ get_single_op_view(PyArrayObject *op, int  iop, char *labels,
...
+    }
 
+    /* Create a view of the operand with the compressed dimensions. */
     Py_INCREF(PyArray_DESCR(op));
     ret = (PyArrayObject *)PyArray_NewFromDescr(
-                            Py_TYPE(op),
-                            PyArray_DESCR(op),
-                            ndim, new_dims, new_strides,
+                            Py_TYPE(op), PyArray_DESCR(op),
+                            icombine, new_dims, new_strides,
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/einsum.c.src]: This will conflict with #11246 (but not in a difficult way)

File: numpy/core/src/multiarray/einsum.c.src [hunk 9]
```diff
@@ -2092,83 +2091,101 @@ get_single_op_view(PyArrayObject *op, int  iop, char *labels,
...
-        }
-        else {
-            combineoffset = 0;
-            if (icombine != idim) {
-                labels[icombine] = labels[idim];
-            }
-            icombinemap[idim] = icombine;
-        }
-        /* If the label is 0, it's an unlabeled broadcast dimension */
-        if (label == 0) {
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/einsum.c.src]: Why did this case go away?

**Comment by charris** [comment]
Needs a rebase.

File: numpy/core/src/multiarray/einsum.c.src (hunk 9 above)
Comment (jaimefrio) [reply numpy/core/src/multiarray/einsum.c.src]: Because icombinemap is set to zero, it didn't really do anything different than for any other non-negative label.

**Comment by jaimefrio** [comment]
PTAL. I think I have addressed all of Eric's comments, which included the need for a rebase.

**Comment by mattip** [comment]
Tests now fail, somehting went wrong with the rebase?

**Comment by jaimefrio** [comment]
Yes, the combined dimension view was being created with the same number of dimensions as the original array, instead of the proper value, using uninitialised memory for the sizes and strides of the extra dimensions. That is now fixed, lets see if Travis agrees...

**Comment by mattip** [comment]
CI passes, any additional comments?

**Comment by mattip** [comment]
@jaimefrio ping, waiting for your reaction

**Comment by mattip** [comment]
@jaimefrio, @eric-wieser can this go in as-is?

**Comment by mattip** [comment]
@jaimefrio, @eric-wieser can this go in as-is?

**Comment by eric-wieser** [comment]
Yep, no behavior change here. Will take one more pass of review, but probably is already fine

**Review by eric-wieser — APPROVED** [review]

**Comment by mattip** [comment]
Thanks @jaimefrio and reviewers
