### PR TITLE
BUG: Fix string/bytes to complex assignment

### LINKED ISSUE #16909: 1.19.0 cannot convert string into complex number
numpy 1.19.0 cannot convert string to complex number.
However, numpy 1.18.1 can perform the codes below correctly

### Reproducing code example:

```python
import numpy as np
list = ['3+4j', '1.23+4.56j', '0.123-1.234j', '0.234+0.456j', '1.123+0.432j']
np.array(list).astype(np.complex)
```

### Error message:
Traceback (most recent call last):
  File "\<stdin\>", line 1, in \<module\>
TypeError: must be real number, not numpy.str_

### Numpy/Python version information:
numpy version: 1.19.0
python version: 3.7.6

### PR DESCRIPTION
**Pull request by seberg**
This was a regression, which happened because of discrepencies
between setting a single item from a string (which was not possible)
and casting from a string to array (which was possible before).
The seconnd code path changed, relying on the former behaviour, which
broke it. This fixes the issue by bringing the second branch in line.

Closes gh-16909

---

I think this is definitely correct on master.  Its probably fine for 1.19.x, but implicitly allows also setting a single item from a string as mentioned in the issue.

### CODE REVIEW

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 1]
```diff
@@ -302,9 +302,42 @@ static int
...
+            pycomplex = PyComplex_Type.tp_new(&PyComplex_Type, args, NULL);
+            Py_DECREF(args);
+            if (pycomplex == NULL) {
+                return -1;
+            }
+            oop = PyComplex_AsCComplex(pycomplex);
+            Py_DECREF(pycomplex);
+            if (error_converting(oop.real)) {
+                return -1;
+            }
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/arraytypes.c.src:336]:
```suggestion
            PyObject *args;
            if (PyBytes_Check(op)) {
                /* The complex constructor expects unicode */
                PyObject *unicode = PyUnicode_FromEncodedObject(op, NULL, NULL);
                if (unicode == NULL) {
                    return -1;
                }
                args = PyTuple_Pack(1, unicode);
                Py_DECREF(unicode);
            }
            else {
                args = PyTuple_Pack(1, op);
            }
            if (args == NULL) {
                return -1;
            }
            PyObject *pycomplex = PyComplex_Type.tp_new(&PyComplex_Type, args, NULL);
            Py_DECREF(args);
            if (pycomplex == NULL) {
                return -1;
            }
            oop = PyComplex_AsCComplex(pycomplex);
            Py_DECREF(pycomplex);
            if (error_converting(oop.real)) {
                return -1;
            }
```

Comment (charris) [reply numpy/core/src/multiarray/arraytypes.c.src:336]: @eric-wieser  This just move the declaration of `pycomplex`, right?

Comment (eric-wieser) [reply numpy/core/src/multiarray/arraytypes.c.src:336]: Yes, and `unicode`. Github is doing a lousy job of showing that diff.

Comment (charris) [reply numpy/core/src/multiarray/arraytypes.c.src:336]: I prefer the shorter lines

Comment (eric-wieser) [reply numpy/core/src/multiarray/arraytypes.c.src:336]: My ordered preference is:
```C
PyObject *unicode = PyUnicode_FromEncodedObject(op, NULL, NULL);
```
then
```C
PyObject *unicode =
    PyUnicode_FromEncodedObject(op, NULL, NULL);
```
then
```C
PyObject *unicode;
unicode = PyUnicode_FromEncodedObject(op, NULL, NULL);
```

At any rate, the C99 style is the first one, and these lines are not that long anyway.

Comment (seberg) [reply numpy/core/src/multiarray/arraytypes.c.src:336]: Dunno, I don't care much either way, part of the reason I did this was indeed longer than 80 char lines, plus I guess right now I don't like your second option too much, I guess just not used to it.

**Comment by charris** [comment]
Thanks Sebastian.
