### PR TITLE
BUG: Fix handling by ``unique`` of signed zero in complex types.

### LINKED ISSUE #30123: BUG: issue detected with hash based unique changes for complex dtypes
Downstream in SciPy Matt reported some test failures where the shapes of arrays had suddenly changed for operations involving complex dtype arrays: https://github.com/scipy/scipy/issues/23902.

I just performed the `git` bisection of SciPy `main` against NumPy, leading to:

```
fa84b04c51ae903caf8bcff66e47f74b514582af is the first bad commit
commit fa84b04c51ae903caf8bcff66e47f74b514582af
Author: Koki Watanabe <56009584+math-hiyoko@users.noreply.github.com>
Date:   Thu Oct 30 10:48:47 2025 +0900

    ENH: np.unique: support hash based unique for complex dtype (#29537)
```

I'll see if I can help a little more than that, but don't have a ton of bandwidth at the moment.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
When hashing a complex type, convert any real or imaginary part from -0.0 to 0.0 before computing the hash.

Closes gh-30123.

### CODE REVIEW

**Comment by jorenham** [comment]
this addresses #30123, right?

**Comment by WarrenWeckesser** [comment]
The failures of the nightly OpenBLAS job and the macOS x86-64 conda job look like CI infrastructure issues.
The failure of the `ubuntu_UBSAN` job is https://github.com/numpy/numpy/issues/30115.

There is a performance cost for this fix:
```
% spin bench -t Unique.time_unique_value -c

[...see below for full output...]

| Change   | Before [779929c4] <main>   | After [ce985b9f] <unique-complex-signed-zeros>   |   Ratio | Benchmark (Parameter)                                                              |
|----------|----------------------------|--------------------------------------------------|---------|------------------------------------------------------------------------------------|
| +        | 2.82±0.01ms                | 3.04±0.01ms                                      |    1.08 | bench_lib.Unique.time_unique_values(200000, 10.0, 0.2, <class 'numpy.complex128'>) |
| +        | 1.13±0ms                   | 1.20±0.01ms                                      |    1.06 | bench_lib.Unique.time_unique_values(200000, 90.0, 0.2, <class 'numpy.complex128'>) |

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE DECREASED.
```

<details>
<summary>Full benchmark output</summary>

```
% spin bench -t Unique.time_unique_value -c
$ cd benchmarks
$ asv continuous --factor 1.05 --bench Unique.time_unique_value 779929c42dd5dfa32f07f1311233abea9f026310 ce985b9fef911389ed255adb67d300ea778e7d79
· Creating environments
· Discovering benchmarks.
·· Uninstalling from virtualenv-py3.13-Cython-build-packaging
·· Building ce985b9f <unique-complex-signed-zeros> for virtualenv-py3.13-Cython-build-packaging...............
·· Installing ce985b9f <unique-complex-signed-zeros> into virtualenv-py3.13-Cython-build-packaging.
· Running 2 total benchmarks (2 commits * 1 environments * 1 benchmarks)
[ 0.00%] · For numpy commit 779929c4 <main> (round 1/2):
[ 0.00%] ·· Building for virtualenv-py3.13-Cython-build-packaging..
[ 0.00%] ·· Benchmarking virtualenv-py3.13-Cython-build-packaging
[25.00%] ··· Running (bench_lib.Unique.time_unique_values--).
[25.00%] · For numpy commit ce985b9f <unique-complex-signed-zeros> (round 1/2):
[25.00%] ·· Building for virtualenv-py3.13-Cython-build-packaging..
[25.00%] ·· Benchmarking virtualenv-py3.13-Cython-build-packaging
[50.00%] ··· Running (bench_lib.Unique.time_unique_values--).
[50.00%] · For numpy commit ce985b9f <unique-complex-signed-zeros> (round 2/2):
[50.00%] ·· Benchmarking virtualenv-py3.13-Cython-build-packaging
[75.00%] ··· bench_lib.Unique.time_unique_values                                                                                                              ok
[75.00%] ··· ============ ============== ======================= =============== ================== ============================
             --                                                                               dtype                             
             --------------------------------------------------- ---------------------------------------------------------------
              array_size   percent_nans   percent_unique_values   numpy.float64   numpy.complex128   StringDType(na_object=nan) 
             ============ ============== ======================= =============== ================== ============================
                 200           10.0                0.2             5.50±0.01μs      4.01±0.01μs             5.11±0.01μs         
                 200           10.0                20.0            7.94±0.03μs      5.31±0.03μs             9.21±0.07μs         
                 200           90.0                0.2             5.32±0.03μs      2.76±0.01μs             4.43±0.02μs         
                 200           90.0                20.0            5.42±0.05μs      3.11±0.02μs             5.58±0.02μs         
                200000         10.0                0.2             3.24±0.01ms      3.04±0.01ms             4.47±0.02ms         
                200000         10.0                20.0            6.61±0.04ms      9.07±0.03ms             18.3±0.04ms         
                200000         90.0                0.2             1.07±0.02ms      1.20±0.01ms             2.49±0.02ms         
                200000         90.0                20.0            1.23±0.04ms      3.00±0.01ms             7.35±0.06ms         
             ============ ============== ======================= =============== ================== ============================

[75.00%] · For numpy commit 779929c4 <main> (round 2/2):
[75.00%] ·· Building for virtualenv-py3.13-Cython-build-packaging..
[75.00%] ·· Benchmarking virtualenv-py3.13-Cython-build-packaging
[100.00%] ··· bench_lib.Unique.time_unique_values                                                                                                              ok
[100.00%] ··· ============ ============== ======================= =============== ================== ============================
              --                                                                               dtype                             
              --------------------------------------------------- ---------------------------------------------------------------
               array_size   percent_nans   percent_unique_values   numpy.float64   numpy.complex128   StringDType(na_object=nan) 
              ============ ============== ======================= =============== ================== ============================
                  200           10.0                0.2             5.49±0.01μs      3.84±0.01μs             5.10±0.01μs         
                  200           10.0                20.0            7.90±0.01μs      5.13±0.01μs             9.12±0.04μs         
                  200           90.0                0.2             5.34±0.02μs      2.68±0.01μs             4.45±0.01μs         
                  200           90.0                20.0            5.39±0.01μs      3.01±0.01μs             5.59±0.01μs         
                 200000         10.0                0.2             3.25±0.09ms      2.82±0.01ms               4.45±0ms          
                 200000         10.0                20.0            6.58±0.01ms      8.65±0.03ms              18.4±0.1ms         
                 200000         90.0                0.2             1.03±0.04ms        1.13±0ms              2.48±0.02ms         
                 200000         90.0                20.0            1.21±0.02ms      2.88±0.03ms             7.45±0.08ms         
              ============ ============== ======================= =============== ================== ============================

| Change   | Before [779929c4] <main>   | After [ce985b9f] <unique-complex-signed-zeros>   |   Ratio | Benchmark (Parameter)                                                              |
|----------|----------------------------|--------------------------------------------------|---------|------------------------------------------------------------------------------------|
| +        | 2.82±0.01ms                | 3.04±0.01ms                                      |    1.08 | bench_lib.Unique.time_unique_values(200000, 10.0, 0.2, <class 'numpy.complex128'>) |
| +        | 1.13±0ms                   | 1.20±0.01ms                                      |    1.06 | bench_lib.Unique.time_unique_values(200000, 90.0, 0.2, <class 'numpy.complex128'>) |

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE DECREASED.
```

</details>

File: numpy/_core/src/multiarray/unique.cpp [hunk 1]
```diff
@@ -51,7 +52,16 @@ size_t hash_complex(const T *value, npy_bool equal_nan) {
...
+
+    std::complex<S> tmp = *reinterpret_cast<const std::complex<S> *>(value);
+    // Get rid of -0.0 in tmp.
+    if (value_real == 0) {
+        tmp.real(0.0);
+    }
+    if (value_imag == 0) {
+        tmp.imag(0.0);
+    }
+    const unsigned char* value_bytes = reinterpret_cast<const unsigned char*>(&tmp);
```
Comment (math-hiyoko) [inline numpy/_core/src/multiarray/unique.cpp]:
```suggestion
    value_real = (value_real == 0.0) ? NPY_PZERO : value_real;
    value_imag = (value_imag == 0.0) ? NPY_PZERO : value_imag;
    S value_array[2] = {value_real, value_imag};
    const unsigned char* value_bytes = reinterpret_cast<const unsigned char*>(value_array);
```

Instead of creating a new complex value, it might be more efficient to construct the array (and buffer) directly from the real and imaginary parts after normalizing -0.0 to +0.0.
After applying this change, the benchmark results showed "BENCHMARKS NOT SIGNIFICANTLY CHANGED".

File: numpy/_core/src/multiarray/unique.cpp [hunk 2]
```diff
@@ -51,7 +52,16 @@ size_t hash_complex(const T *value, npy_bool equal_nan) {
...
     size_t hash = npy_fnv1a(value_bytes, sizeof(T));
```
Comment (math-hiyoko) [inline numpy/_core/src/multiarray/unique.cpp]:
```suggestion
    value_real = (value_real == NPY_NZERO) ? NPY_PZERO : value_real;
    value_imag = (value_imag == NPY_NZERO) ? NPY_PZERO : value_imag;
    S value_array[2] = {value_real, value_imag};
    const unsigned char* value_bytes = reinterpret_cast<const unsigned char*>(value_array);
    size_t hash = npy_fnv1a(value_bytes, sizeof(S) * 2);
```

Instead of creating a new complex value, it might be more efficient to construct the array (and buffer) directly from the real and imaginary parts after normalizing -0.0 to +0.0.
After applying this change, the benchmark results showed "BENCHMARKS NOT SIGNIFICANTLY CHANGED".

File: numpy/_core/src/multiarray/unique.cpp [hunk 3]
```diff
@@ -76,6 +86,11 @@ size_t hash_complex_clongdouble(const npy_clongdouble *value, npy_bool equal_nan
     #if defined(HAVE_LDOUBLE_INTEL_EXTENDED_12_BYTES_LE) || \
         defined(HAVE_LDOUBLE_INTEL_EXTENDED_16_BYTES_LE) || \
         defined(HAVE_LDOUBLE_MOTOROLA_EXTENDED_12_BYTES_BE)
+
+    // Get rid of -0.0.
+    value_real = (value_real == 0.0) ? 0.0 : value_real;
+    value_imag = (value_imag == 0.0) ? 0.0 : value_imag;
```
Comment (math-hiyoko) [inline numpy/_core/src/multiarray/unique.cpp]:
```suggestion
    value_real = (value_real == NPY_NZEROL) ? NPY_PZEROL : value_real;
    value_imag = (value_imag == NPY_NZEROL) ? NPY_PZEROL : value_imag;
```
Using NPY_PZEROL macro may be better.

File: numpy/_core/src/multiarray/unique.cpp [hunk 4]
```diff
@@ -101,8 +116,17 @@ size_t hash_complex_clongdouble(const npy_clongdouble *value, npy_bool equal_nan
...
+    // Get rid of -0.0 in tmp.
+    if (value_real == 0) {
+        tmp.real(0.0);
+    }
+    if (value_imag == 0) {
+        tmp.imag(0.0);
+    }
     constexpr size_t SIZEOF_BUFFER = NPY_SIZEOF_CLONGDOUBLE;
-    const unsigned char* buffer = reinterpret_cast<const unsigned char*>(value);
+    const unsigned char* buffer = reinterpret_cast<const unsigned char*>(&tmp);
```
Comment (math-hiyoko) [inline numpy/_core/src/multiarray/unique.cpp]:
```c++
    value_real = (value_real == NPY_NZEROL) ? NPY_PZEROL : value_real;
    value_imag = (value_imag == NPY_NZEROL) ? NPY_PZEROL : value_imag;
    npy_longdouble value_array[2] = {value_real, value_imag};
    constexpr size_t SIZEOF_BUFFER = sizeof(npy_longdouble) * 2;
    const unsigned char* buffer = reinterpret_cast<const unsigned char*>(value_array);
```
Same as https://github.com/numpy/numpy/pull/30125/files#r2483136556

File: numpy/_core/src/multiarray/unique.cpp (hunk 2 above)
Comment (WarrenWeckesser) [reply numpy/_core/src/multiarray/unique.cpp]: Thanks @math-hiyoko, I'll take a look. I was just iterating a bit after my initial quick hacks and noticed some potential optimizations.

Comment (WarrenWeckesser) [reply numpy/_core/src/multiarray/unique.cpp]: I tried this, but I got pretty much the same performance penalty for the complex double precision case (m2 macbook, clang 18.1.8).  Are you sure you committed your suggested change before running the benchmark?

Comment (WarrenWeckesser) [reply numpy/_core/src/multiarray/unique.cpp]: (Argh... I just experienced https://github.com/orgs/community/discussions/10369, which is why a comment from two days ago is just appearing now.)

File: numpy/_core/src/multiarray/unique.cpp (hunk 3 above)
Comment (WarrenWeckesser) [reply numpy/_core/src/multiarray/unique.cpp]: Testing for NPY_NZEROL is equivalent to testing for 0.0.  If we actually wanted to check that the input was -0.0, we would need something that explicitly checks the sign bit.  I don't think that is worth it.

Comment (WarrenWeckesser) [reply numpy/_core/src/multiarray/unique.cpp]: I did change the code to use the macro when setting the values, but to be honest, I don't think it is actually better than just using the literal.

File: numpy/_core/src/multiarray/unique.cpp (hunk 2 above)
Comment (math-hiyoko) [reply numpy/_core/src/multiarray/unique.cpp]: > I tried this, but I got pretty much the same performance penalty for the complex double precision case (m2 macbook, clang 18.1.8). Are you sure you committed your suggested change before running the benchmark?

Please try applying the suggested change _and_ removing `#include <complex>` before running the benchmark.
In my environment, the benchmark results changed noticeably depending on whether `#include <complex>` was present.

File: numpy/_core/src/multiarray/unique.cpp (hunk 3 above)
Comment (math-hiyoko) [reply numpy/_core/src/multiarray/unique.cpp]: I think it’s ultimately a matter of preference, so please go with what you like.

File: numpy/_core/src/multiarray/unique.cpp (hunk 2 above)
Comment (WarrenWeckesser) [reply numpy/_core/src/multiarray/unique.cpp]: Interesting!  OK, I double-checked: when I ran the benchmark with your suggested change, I was working with a new branch off of 779929c42dd5dfa32f07f1311233abea9f026310 that included only your suggestion, so `#include <complex>` was not in `unique.cpp`.

I'm away from my Linux computer for the day, so I have only run the benchmark on an m2 Macbook.  I can check the behavior on Linux tomorrow.

**Comment by ngoldbaum** [comment]
@math-hiyoko can you give this another look?

**Comment by math-hiyoko** [comment]
The other parts of the changes look great.

File: numpy/_core/src/multiarray/unique.cpp (hunk 2 above)
Comment (WarrenWeckesser) [reply numpy/_core/src/multiarray/unique.cpp]: Here are the timings that I get on my Linux machine (popos, gcc 11.4.0).  The comparisons are against commit 779929c4, which was `main` when the PR was created.  I modified `.spin/cmds` to reduce the `--factor` argument of `asv` to 1.01 for more visibility of the changes.  Note that the commit with @math-hiyoko's suggestion doesn't include the addition of the benchmark with 0 nans (second parameter of `time_unique_values) that I have in the PR.

It looks like this PR has slightly better performance.

*Edit: removed benchmark results for dtypes that are not complex128.*

This PR:

```
| Change   | Before [779929c4] <old-main>   | After [2180847e] <unique-complex-signed-zeros>   |   Ratio | Benchmark (Parameter)                                                            |
|----------|--------------------------------|--------------------------------------------------|---------|----------------------------------------------------------------------------------|
| +        | 7.56±0.09μs                    | 7.73±0.04μs                                      |    1.02 | bench_lib.Unique.time_unique_values(200, 0.0, 0.2, <class 'numpy.complex128'>)   |
| +        | 8.87±0.05μs                    | 9.08±0.03μs                                      |    1.02 | bench_lib.Unique.time_unique_values(200, 0.0, 20.0, <class 'numpy.complex128'>)  |
```

Suggestion by @math-hiyoko:

```
| Change   | Before [779929c4] <old-main>   | After [52b78310] <suggestion>   |   Ratio | Benchmark (Parameter)                                                            |
|----------|--------------------------------|---------------------------------|---------|----------------------------------------------------------------------------------|
| +        | 8.46±0.1μs                     | 9.06±0.03μs                     |    1.07 | bench_lib.Unique.time_unique_values(200, 10.0, 20.0, <class 'numpy.complex128'>) |
| +        | 7.27±0.07μs                    | 7.74±0.06μs                     |    1.06 | bench_lib.Unique.time_unique_values(200, 10.0, 0.2, <class 'numpy.complex128'>)  |
| +        | 4.47±0.01μs                    | 4.62±0.02μs                     |    1.03 | bench_lib.Unique.time_unique_values(200, 90.0, 0.2, <class 'numpy.complex128'>)  |
```

Comment (math-hiyoko) [reply numpy/_core/src/multiarray/unique.cpp]: Thank you for the thorough analysis.
In that case, let’s proceed with your implementation.

**Comment by ngoldbaum** [comment]
OK great, is this ready to merge then?

**Comment by WarrenWeckesser** [comment]
> ... is this ready to merge then?

From my perspective, yes.

**Comment by ngoldbaum** [comment]
In it goes, thanks!

**Comment by WarrenWeckesser** [comment]
Thanks @math-hiyoko, @ngoldbaum.
