### PR TITLE
BUG: add bounds-checking to in-place string multiply

### LINKED ISSUE #29011: TYP/CI: MacOS typing tests are sometimes segfaulting
See https://github.com/numpy/numpy/actions/runs/15138432787/job/42555808050?pr=29007

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes #29011. 

Re-do of #29056 without any backwards-incompatible changes.

Adds bounds-checking to the string multiply core, since in-place multiply via `*=` can bypass the code that constructs output buffers in `np.strings.multiply`.

### CODE REVIEW

File: numpy/_core/src/umath/string_ufuncs.cpp [hunk 1]
```diff
@@ -175,6 +175,12 @@ string_multiply(Buffer<enc> buf1, npy_int64 reps, Buffer<enc> out)
         return;
     }
 
+    size_t width = out.buffer_width();
+    size_t pad = 0;
+    if (width < len1*reps) {
```
Comment (seberg) [inline numpy/_core/src/umath/string_ufuncs.cpp:180]:
```suggestion
    if (reps > NPY_MAX_SSIZE_T  // ssize_t is enough here
        || npy_mul_sizes_with_overflow(len1, reps, &width)
        || width > out.buffer_width()) {
            width = out.buffer_width;
```
Admittedly this is tedious and pedantic, but maybe we should do overflow checks?  `npy_mul_sizes_with_overflow` uses `ssize_t` inputs, which is safe here but may require casting to tell the compiler about that.  (Or just using the `size_t` version.)
I suppose `NPY_UNLIKELY()` will be irrelevant here.

File: numpy/_core/src/umath/string_ufuncs.cpp [hunk 2]
```diff
@@ -166,26 +167,44 @@ string_add(Buffer<enc> buf1, Buffer<enc> buf2, Buffer<enc> out)
...
     }
-    else {
-        for (npy_int64 i = 0; i < reps; i++) {
-            buf1.buffer_memcpy(out, len1);
-            out += len1;
-        }
-        out.buffer_fill_with_zeros_after_index(0);
+
+    size_t newlen;
+    if (NPY_UNLIKELY(npy_mul_with_overflow_size_t(&newlen, reps, len1) < 0) || newlen > PY_SSIZE_T_MAX) {
```
Comment (seberg) [inline numpy/_core/src/umath/string_ufuncs.cpp:187]:
```suggestion
    if (NPY_UNLIKELY(npy_mul_with_overflow_size_t(&newlen, reps, len1) != 0) || newlen > PY_SSIZE_T_MAX) {
```
I think this one isn't technically an error return, but a "has overflown" return...  Maybe the test should run into the overflow path, but `newlen > PY_SSIZE_T_MAX` also kicks in due to fun overflows?

Overflow error or memory error is both fine to me (for this branch I would also be OK with just using the `width < newlen` path).

**Review by seberg — APPROVED** [review]
Anyway, LGTM modulo that one `!=`, thanks for fixing also the other similar but unrelated branch!
