### PR TITLE
BUG,DEP: Allow (arg-)partition to accept `uint64` indices 

### LINKED ISSUE #19832: BUG: `partition`/`argpartition` do not accept `uint64` indices
The `partition` and `argpartition` functions currently raise when the `kth` indices are supplied as a `uint64` array-like.

The functions in question check that the indice-type can safelly be cast to `intp`, which of course will fail in the case of `uint64`. I'm not quite sure how the likes of `__getitem__` and `take` do manage to deal with `uint64`, but there it seems to work just fine. 

https://github.com/numpy/numpy/blob/b3a66e88b005c4ca783c11e5d934451b7ca72477/numpy/core/src/multiarray/item_selection.c#L1295-L1299

### Example
``` python
In [1]: import numpy as np

In [2]: ar = np.arange(10)

In [3]: ar.partition(np.uint64(5))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-fee31ee69481> in <module>
----> 1 ar.partition(np.uint64(5))

TypeError: Partition index must be integer
```

### NumPy/Python version information:

```
1.22.0.dev0+997.g8e4e40f60
3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:36:15) 
[Clang 11.1.0 ]
```

### PR DESCRIPTION
**Pull request by BvB93**
Closes https://github.com/numpy/numpy/issues/19832

This PR introduces two changes: 
* It fixes an issue wherein the partition functions would previously not accept `uint64` indices, an issue caused by what was effectively a `np.can_cast(kth, np.intp, casting="same_kind")` check.
* The same casting-check would previously allow booleans to pass through, converting them to `np.intp` and thus treating them as normal numerical indices. The passing of booleans to the `kth` parameter has now been deprecated.

### CODE REVIEW

File: numpy/core/src/multiarray/item_selection.c [hunk 1]
```diff
@@ -1292,7 +1292,14 @@ partition_prep_kth_array(PyArrayObject * ktharray,
...
 
-    if (!PyArray_CanCastSafely(PyArray_TYPE(ktharray), NPY_INTP)) {
+    if (PyArray_ISBOOL(ktharray)) {
+        /* 2021-09-29, NumPy 1.22 */
+        if (DEPRECATE(
+                "Passing booleans as partition index is deprecated") < 0) {
+            return NULL;
+        }
+    }
+    else if (!PyArray_ISINTEGER(ktharray)) {
```
Comment (seberg) [inline numpy/core/src/multiarray/item_selection.c:1302]: OK, I think we may have to switch hat over to a same-kind casting (possibly with a time exception).  But it is what indexing currently uses, so I think it is fine.  (This would not allow custom user integer DTypes.)

File: numpy/core/src/multiarray/item_selection.c [hunk 2]
```diff
@@ -1292,7 +1292,14 @@ partition_prep_kth_array(PyArrayObject * ktharray,
     npy_intp * kth;
     npy_intp nkth, i;
 
-    if (!PyArray_CanCastSafely(PyArray_TYPE(ktharray), NPY_INTP)) {
+    if (PyArray_ISBOOL(ktharray)) {
+        /* 2021-09-29, NumPy 1.22 */
+        if (DEPRECATE(
+                "Passing booleans as partition index is deprecated") < 0) {
```
Comment (seberg) [inline numpy/core/src/multiarray/item_selection.c:1298]: Can you add the NumPy version in the message?  Just for completeness sake (could just be a parantheses at the end, I guess, like `(warning added in NumPy 1.22)`.  I know that most older warnings don't have it, but it is nice, I think.

**Review by seberg — APPROVED** [review]
This looks good to me, thanks!  I am happy with deprecating bools as well, since the new behaviour would mirror indexing.
(Just in case someone wonders:  The casting can lead to integer overflows during the cast in theory, this is something we have to live with right now unfortunately, we do the same in indexing.)

File: numpy/core/src/multiarray/item_selection.c (hunk 2 above)
Comment (BvB93) [reply numpy/core/src/multiarray/item_selection.c]: Sure thing; done as of https://github.com/numpy/numpy/pull/20000/commits/fd00a92a0d4793076533bf4cef23a1876fadf0fb.

File: numpy/core/src/multiarray/item_selection.c (hunk 1 above)
Comment (BvB93) [reply numpy/core/src/multiarray/item_selection.c:1303]: For future refernce: I wonder what would be the best way of dealing with custom user integer DTypes?
Considering `PyArray_ISINTEGER` is too strict and `np.can_cast(..., casting="same_kind")` won't even accept all the standard numpy integer dtypes.

Comment (BvB93) [reply numpy/core/src/multiarray/item_selection.c:1303]: > All NumPy integers should pass fine?

Ah, to clarify: I was talking specifically about `np.uint64` in the `can_cast` example.

> If same-kind casting doesn't do the trick, we could also consider adding an abstract `Indexer` DType that users have to register or implement promotion with.

I could see this potentially being usefull, as this would also make it easier to differentiate between (user-defined) bool dtypes.

Comment (BvB93) [reply numpy/core/src/multiarray/item_selection.c:1303]: Ugh, you're completelly right.
I may have accidently mixed up "safe" and "same_kind" in my head...

**Comment by seberg** [comment]
Thanks Bas, if no-one else has any concerns, lets put this in!  (I suppose we should probably ping the mailing list very briefly about this, but I feel it is just a formality.)
