### PR TITLE
Clear signaling NaN exceptions

### LINKED ISSUE #7838: numpy.isfinite and isnan throw mysterious invalid  value warning when encountering nan sometimes
Hard to reproduce. I attached an array where this happens:

```{python}
import numpy as np
np.seterr(all='raise')
a = np.load('weird_array.npy')
print(a.shape, a.dtype)
for i, val in enumerate(a):
    try:
        np.isfinite(np.array(val, ndmin=1))
    except:
        strange_index = i
        print(type(val))
        print(val.__class__.__name__)
        print(i)
        print(val)

print(np.isfinite(a[strange_index]))

```

Results in:

```
<class 'numpy.float64'>
float64
1023450
nan
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    print(np.isfinite(a[strange_index]))
FloatingPointError: invalid value encountered in isfinite
```

[weird_array.zip](https://github.com/numpy/numpy/files/365889/weird_array.zip)

### PR DESCRIPTION
**Pull request by pslacerda**
Seems that the float point exceptions raised when operating with signaling NaN has little meaning after some loops. But why clear the error status also from SIMD specialized loops , isn't it the same?

Fixes #7838, but exceptions still happen:

``` python
import numpy as np
np.seterr(all='raise')
a = np.load('weird_array.npy')
np.isfinite(a)
```

Results in

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    np.isfinite(a)
FloatingPointError: invalid value encountered in isfinite
```

### CODE REVIEW

File: numpy/core/src/umath/loops.c.src [hunk 1]
```diff
@@ -1644,6 +1644,7 @@ NPY_NO_EXPORT void
             const @type@ in1 = *(@type@ *)ip1;
             *((npy_bool *)op1) = @func@(in1) != 0;
         }
+        npy_clear_floatstatus();
```
Comment (juliantaylor) [inline numpy/core/src/umath/loops.c.src]: this needs to be one line lower, otherwise it will not cover the simd case. That function runs the code and only returns false if simd could not be used.

**Comment by juliantaylor** [comment]
a test would be good, you can probably use the byte pattern from gh-8049 for it.
Also please amend your bug message with a BUG: in front of the subject, see 8049

**Comment by pslacerda** [comment]
No idea on what are you talking.

**Comment by juliantaylor** [comment]
still, you did everything correct :D 
thanks
