### PR TITLE
BUG: timedelta64 now accepts NumPy ints

### LINKED ISSUE #7617: timedelta64 only accepts int timedeltas
timedelta64 only accepts timedeltas of type int; it does not support timedeltas of other int types, such as int64.

### PR DESCRIPTION
**Pull request by tylerjereddy**
Fixes #7617

I should (probably) add more tests & maybe account for the duplication logic (another branch of the C function adjusted here uses that block too) by abstracting to a "helper" function.

### CODE REVIEW

**Comment by charris** [comment]
Testing failure Looks like travis messing up. Grrr.

**Comment by charris** [comment]
They may have changed their testing environment, although why it only affects the one test escapes me.

**Comment by tylerjereddy** [comment]
Yeah, not sure what is going on with that test; restarting certainly doesn't seem helpful.

**Comment by charris** [comment]
I'm going to try closing and reopening to see if that makes a difference.

File: numpy/core/src/multiarray/datetime.c [hunk 1]
```diff
@@ -2846,6 +2846,16 @@ convert_pyobject_to_timedelta(PyArray_DatetimeMetaData *meta, PyObject *obj,
         return 0;
     }
     else {
+        if (PyArray_IsScalar(obj, Integer)) {
```
Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: Can't this be done as `else if` with the error return alone in an `else` section?

**Comment by charris** [comment]
Looks like the test is missing a path.

**Comment by tylerjereddy** [comment]
I tried to address the revisions & rebase on latest master for ci issue; let's see what it says I guess.

**Comment by charris** [comment]
> rebase on latest master for ci issue

I'm not convinced I actually fixed it, it may be that there is a badly configured machine out there and we are having a lucky streak of not running on it.

File: numpy/core/tests/test_datetime.py [hunk 2]
```diff
@@ -260,6 +260,21 @@ def test_datetime_array_find_type(self):
...
+    ("s"), ("ms"), ("us"), ("ns"), ("ps"),
+    ("fs"), ("as"), ("generic") ])
+    def test_timedelta_np_int_construction(self, unit):
+        # regression test for gh-7617
+        if unit != "generic":
+            assert_equal(np.timedelta64(np.int64(123), unit),
+                         np.timedelta64(123, unit))
+        else:
+            assert_equal(np.timedelta64(np.int64(123)),
+                         np.timedelta64(123))
```
Comment (eric-wieser) [inline numpy/core/tests/test_datetime.py]: I'm not sure allowing default units to be impliedis a good idea. Is there precedent for this in `datetime64`?

Comment (tylerjereddy) [reply numpy/core/tests/test_datetime.py]: Can you clarify? `np.timedelta64(123)` already casts to the default `m8` in the master branch; the code to handle a `np.int64(123)` in the same way is just duplicating that logic for another kind of integer input--it is an actual copy-paste of code for regular Python integer handling farther up.

**Comment by tylerjereddy** [comment]
One issue may simply be that we're hesitant to bake in new support for things in datetime64; I've tried to hold off on any more datetime64 PRs beyond the initial batch from a few weeks ago.

File: numpy/core/src/multiarray/datetime.c [hunk 3]
```diff
@@ -2845,6 +2845,16 @@ convert_pyobject_to_timedelta(PyArray_DatetimeMetaData *meta, PyObject *obj,
         *out = NPY_DATETIME_NAT;
         return 0;
     }
+    else if (PyArray_IsScalar(obj, Integer)) {
```
Comment (shoyer) [inline numpy/core/src/multiarray/datetime.c]: Move this branch up, next to the branch handling "raw integers" on line 2661?

**Review by shoyer — APPROVED** [review]
Looks good to me, thanks!

File: numpy/core/src/multiarray/datetime.c (hunk 3 above)
Comment (tylerjereddy) [reply numpy/core/src/multiarray/datetime.c]: This causes test failures in my hands -- I'm guessing other types of inputs get drawn in to the branch too early if moved up there.

**Comment by nicoabie** [comment]
@tylerjereddy @shoyer I don't see this pull request in the changelogs. I'm currently running with v1.15.4 and it fails if I attempt to convert a int64 into a timedelta. is this possible? Thanks in advance

**Comment by shoyer** [comment]
I don't think this was backported to the NumPy 1.15 branch. You'll need to wait for NumPy 1.16 (maybe only a few weeks?)

**Comment by nicoabie** [comment]
@shoyer thanks for the fast response. I thought It should be there because it was merged prior to v1.15.3 but I have no problem to wait, I'll just wrap it with `int()`. Thanks again!
