### PR TITLE
BUG: Raise when unravel_index, ravel_multi_index are given empty input

### LINKED ISSUE #7165: np.unravel_index() does not accept empty inputs
I would expect a tuple of empty outputs back. I get the following:

```
>>> np.unravel_index([], (10, 12))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Iterator operand 0 dtype could not be cast from dtype('float64') to dtype('int64') according to the rule 'same_kind'
```

This does not seem to be a regression, as I can see this with numpy v1.9.2, but it does seem silly.

### PR DESCRIPTION
**Pull request by mattip**
Fixes #7165. Replaces #7170.

Adds tests and fixes for `unravel_index`, `ravel_multi_index` when the input is an empty list. The strategy in #7170 relied on internal use of `PyArray_DTypeFromObject`. But we can proactively use it with a minimal `int` type (I used `NPY_BOOL` as the most basic type) to determine the dtype of the object while restricting the possibilities to `int` dtypes before calling `PyArray_FromAny`.

Also added a small refactor of privately used sequence_to_arrays to put output values at the end of the paramter list and use a goto to reduce duplicate code.

### CODE REVIEW

File: numpy/core/src/multiarray/compiled_base.c [hunk 1]
```diff
@@ -825,29 +830,32 @@ static int sequence_to_arrays(PyObject *seq,
...
-                op[i] = NULL;
-            }
-            return -1;
+            goto fail;
         }
-
-        op[i] = (PyArrayObject *)PyArray_FROM_O(item);
+        Py_INCREF(dtype);
+        if (PyArray_DTypeFromObject(item, NPY_MAXDIMS, &dtype) < 0) {
+            goto fail;
```
Comment (mattip) [inline numpy/core/src/multiarray/compiled_base.c]: PyArray_DTypeFromObject does not fail. Perhaps we could improve the error message by detecting a non-integer dtype here. Currently the error is raised later with `TypeError: Iterator operand 0 dtype could not be cast from dtype('float64') to dtype('int64') according to the rule 'same_kind'`

File: numpy/core/src/multiarray/compiled_base.c [hunk 2]
```diff
@@ -1169,7 +1179,16 @@ arr_unravel_index(PyObject *self, PyObject *args, PyObject *kwds)
...
     if (!PyArray_Check(indices0)) {
-        indices = (PyArrayObject*)PyArray_FROM_O(indices0);
+        /* ensure dtype is int-based */
+        PyArray_Descr *dtype_guess = PyArray_DescrFromType(NPY_BOOL);
+        if (dtype_guess == NULL) {
+            goto fail;
+        }
+        Py_INCREF(dtype_guess);
+        if (PyArray_DTypeFromObject(indices0, NPY_MAXDIMS, &dtype_guess) < 0) {
+            goto fail;
```
Comment (mattip) [inline numpy/core/src/multiarray/compiled_base.c]: See other comment, `PyArray_DTypeFromObject` does not fail.

File: numpy/core/src/multiarray/compiled_base.c (hunk 1 above)
Comment (mattip) [reply numpy/core/src/multiarray/compiled_base.c]: improved error message

**Comment by mattip** [comment]
strange that no-one ran into the bad macro in b2ddbd6 before

File: numpy/core/src/multiarray/compiled_base.c [hunk 3]
```diff
@@ -825,29 +830,36 @@ static int sequence_to_arrays(PyObject *seq,
...
         }
-
-        op[i] = (PyArrayObject *)PyArray_FROM_O(item);
+        Py_INCREF(dtype);
+        if (PyArray_DTypeFromObject(item, NPY_MAXDIMS, &dtype) < 0) {
+            goto fail;
+        }
+        if (!(PyDataType_ISINTEGER(dtype) || PyDataType_ISBOOL(dtype))) {
+            PyErr_SetString(PyExc_TypeError, "only int indices permitted");
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/compiled_base.c]: We should look to deprecate booleans here

File: numpy/core/src/multiarray/compiled_base.c [hunk 4]
```diff
@@ -1169,7 +1182,16 @@ arr_unravel_index(PyObject *self, PyObject *args, PyObject *kwds)
     unravel_size = PyArray_MultiplyList(dimensions.ptr, dimensions.len);
 
     if (!PyArray_Check(indices0)) {
-        indices = (PyArrayObject*)PyArray_FROM_O(indices0);
+        /* prefer int dtype */
+        PyArray_Descr *dtype_guess = PyArray_DescrFromType(NPY_BOOL);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/compiled_base.c]: I'd just use `NPY_INTP` here

**Comment by eric-wieser** [comment]
I'm not in favor of making `np.unravel_index([])` succeed. I think that for any numpy call `np.func(array_like)`, it should be identical to invoking `np.func(np.asarray(array_like))`. This patch violates that expectation.

I would be in favor of trying to improve the error message

**Comment by mattip** [comment]
> I would be in favor of trying to improve the error message

Made use of empty sequences fail with an error message (improvements welcome) 
"empty sequence implies float indices which are not allowed"

File: numpy/core/src/multiarray/compiled_base.c (hunk 2 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/compiled_base.c]: What do you mean by this comment?

File: numpy/core/src/multiarray/compiled_base.c [hunk 5]
```diff
@@ -1169,7 +1187,23 @@ arr_unravel_index(PyObject *self, PyObject *args, PyObject *kwds)
...
+        }
+        if (dtype_guess == NULL) {
+            if (PySequence_Check(indices0) && PySequence_Size(indices0) == 0) {
+                PyErr_SetString(PyExc_TypeError,
+                                "empty sequence implies float indices "
+                                "which are not allowed");
+            }
+            else if (!PyErr_Occurred()) {
+                PyErr_SetString(PyExc_RuntimeError, "unknown error occurred");
+            }
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/compiled_base.c]: This seems like it should never happen, and we should leave python to raise the usual `SystemError` here if it does

Comment (mattip) [reply numpy/core/src/multiarray/compiled_base.c]: codecov agrees with you, those lines were never hit. Removing.

File: numpy/core/src/multiarray/compiled_base.c [hunk 6]
```diff
@@ -825,29 +828,45 @@ static int sequence_to_arrays(PyObject *seq,
...
+            goto fail;
+        }
+        if (PyArray_DTypeFromObject(item, NPY_MAXDIMS, &dtype) < 0) {
+            goto fail;
+        }
+        if (dtype == NULL) {
+            if (PySequence_Check(item) && PySequence_Size(item) == 0) {
+                PyErr_SetString(PyExc_TypeError,
+                                "empty sequence implies float indices "
+                                "which are not allowed");
```
[the remark this answers is not in the document]
Comment (mattip) [reply numpy/core/src/multiarray/compiled_base.c]: Changed to "empty sequence implies float indices which are not allowed. Wrap them with 'np.array(indices, dtype=np.intp)'"

File: numpy/core/src/multiarray/compiled_base.c [hunk 7]
```diff
@@ -806,16 +806,19 @@ arr_interp_complex(PyObject *NPY_UNUSED(self), PyObject *args, PyObject *kwdict)
...
 static int sequence_to_arrays(PyObject *seq,
-                                PyArrayObject **op, int count,
-                                char *paramname)
+                              char *paramname,
+                              int count,
+                              PyArrayObject **op
+                              )
 {
     int i;
+    PyObject *item = NULL;
```
[the remark this answers is not in the document]
Comment (mattip) [reply numpy/core/src/multiarray/compiled_base.c]: Adopted, at the price of `DECREF`s before `goto fail`

[the remark this answers is not in the document]
Comment (eric-wieser) [reply numpy/core/src/multiarray/compiled_base.c]: A loop-local label is another solution to this kind of problem

[the remark this answers is not in the document]
Comment (eric-wieser) [reply numpy/core/src/multiarray/compiled_base.c]: (but probably not a worthwhile one

File: numpy/core/src/multiarray/compiled_base.c (hunk 2 above)
Comment (mattip) [reply numpy/core/src/multiarray/compiled_base.c]: In a previous version we fed in a `dtype_guess`, so `PyArray_DTypeFromObject` would not fail. Now we feed in NULL, so the comment is out of date

File: numpy/core/src/multiarray/compiled_base.c [hunk 8]
```diff
@@ -1169,7 +1186,20 @@ arr_unravel_index(PyObject *self, PyObject *args, PyObject *kwds)
...
+        /* prefer int dtype */
+        PyArray_Descr *dtype_guess = NULL;
+        if (PyArray_DTypeFromObject(indices0, NPY_MAXDIMS, &dtype_guess) < 0) {
+            goto fail;
+        }
+        if (dtype_guess == NULL) {
+            if (PySequence_Check(indices0) && PySequence_Size(indices0) == 0) {
+                PyErr_SetString(PyExc_TypeError,
+                                "empty sequence implies float indices "
+                                "which are not allowed");
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/compiled_base.c]: This message and the below one should match the ones in ravel_multi_index

File: numpy/core/src/multiarray/compiled_base.c [hunk 9]
```diff
@@ -803,17 +803,25 @@ arr_interp_complex(PyObject *NPY_UNUSED(self), PyObject *args, PyObject *kwdict)
...
- * seq       - Input Python object, usually a tuple but any sequence works.
- * op        - Where the arrays are placed.
- * count     - How many arrays there should be (errors if it doesn't match).
- * paramname - The name of the parameter that produced 'seq'.
+ * seq         - Input Python object, usually a tuple but any sequence works.
+ * paramname   - The name of the parameter that produced 'seq'.
+ * count       - How many arrays there should be (errors if it doesn't match).
+ * op          - Where the arrays are placed.
  */
 static int sequence_to_arrays(PyObject *seq,
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/compiled_base.c]: This function name and its docs should be changed to indicate that it handles arrays of indices / that they must be integers / something like that

File: numpy/core/src/multiarray/compiled_base.c [hunk 10]
```diff
@@ -803,17 +803,25 @@ arr_interp_complex(PyObject *NPY_UNUSED(self), PyObject *args, PyObject *kwdict)
     return NULL;
 }
 
+
+#define EMPTY_SEQUENCE_ERR_MSG "indices must be integral: the provided " \
+    "empty sequence was inferred as float. Wrap it with " \
+    "'np.array(indices, dtype=np.intp)'"
+
+#define NON_INTEGRAL_ERROR_MSG "only int indices permitted"
```
[the remark this answers is not in the document]
Comment (mattip) [reply numpy/core/src/multiarray/compiled_base.c]: changed

File: numpy/core/src/multiarray/compiled_base.c (hunk 9 above)
Comment (mattip) [reply numpy/core/src/multiarray/compiled_base.c]: changed

**Comment by mattip** [comment]
@eric-wieser can you re-review the changes here?

File: numpy/core/src/multiarray/compiled_base.c [hunk 11]
```diff
@@ -825,29 +834,42 @@ static int sequence_to_arrays(PyObject *seq,
...
             }
             Py_DECREF(item);
-            return -1;
+            goto fail;
         }
-
+        if (!(PyDataType_ISINTEGER(dtype) || PyDataType_ISBOOL(dtype))) {
+            PyErr_SetString(PyExc_TypeError, NON_INTEGRAL_ERROR_MSG);
+            Py_DECREF(item);
+            goto fail;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/compiled_base.c]: Need to `DECREF` dtype here, I think

**Comment by eric-wieser** [comment]
It seems like you could extract an `as_intp_array` helper function from both of these functions, rather than duplicating the logic in slightly different ways.

File: numpy/core/src/multiarray/compiled_base.c (hunk 11 above)
Comment (mattip) [reply numpy/core/src/multiarray/compiled_base.c]: Added

**Comment by mattip** [comment]
> It seems like you could extract an as_intp_array helper function from both of these functions

@eric-wieser it has been so long that I lost the context of this comment. Which two functions?

File: numpy/core/src/multiarray/compiled_base.c (hunk 1 above)
Comment (mattip) [reply numpy/core/src/multiarray/compiled_base.c]: removed in a later commit

File: numpy/core/src/multiarray/compiled_base.c (hunk 3 above)
Comment (mattip) [reply numpy/core/src/multiarray/compiled_base.c]: removed in a later commit

File: numpy/core/src/multiarray/compiled_base.c (hunk 4 above)
Comment (mattip) [reply numpy/core/src/multiarray/compiled_base.c]: removed in a later commit

**Comment by mattip** [comment]
@eric-wieser any more changes needed?

**Comment by mattip** [comment]
ping

**Comment by mattip** [comment]
@eric-wieser ping

**Comment by eric-wieser** [comment]
I'd recommend you use the "request a review" button in future. The problem is I see these pings when I don't have time to process them, and have no easy way of finding them again when I do have it.

File: numpy/core/src/multiarray/compiled_base.c [hunk 12]
```diff
@@ -825,29 +834,44 @@ static int sequence_to_arrays(PyObject *seq,
...
+        if (!(PyDataType_ISINTEGER(dtype) || PyDataType_ISBOOL(dtype))) {
+            PyErr_SetString(PyExc_TypeError, NON_INTEGRAL_ERROR_MSG);
+            Py_DECREF(dtype);
+            Py_DECREF(item);
+            goto fail;
+        }
+        op[i] = (PyArrayObject *)PyArray_FromAny(item, dtype, 0, 0, 0, NULL);
         Py_DECREF(item);
+        if (op[i] == NULL) {
+            Py_DECREF(dtype);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/compiled_base.c]: I think this double-decrefs, `PyArray_FromAny` (probably) steals a reference

**Comment by eric-wieser** [comment]
Expanding on the old comment

I'm requesting that you merge these two pieces of code:
```C
if (!PyArray_Check(indices0)) {
    /* prefer int dtype */
    PyArray_Descr *dtype_guess = NULL;
    if (PyArray_DTypeFromObject(indices0, NPY_MAXDIMS, &dtype_guess) < 0) {
        goto fail;
    }
    if (dtype_guess == NULL) {
        if (PySequence_Check(indices0) && PySequence_Size(indices0) == 0) {
            PyErr_SetString(PyExc_TypeError, EMPTY_SEQUENCE_ERR_MSG);
        }
        goto fail;
    }
    indices = (PyArrayObject*)PyArray_FromAny(indices0, dtype_guess, 0, 0, 0, NULL);
    if (indices == NULL) {
        goto fail;
    }
}
else {
    indices = (PyArrayObject *)indices0;
    Py_INCREF(indices);
}

if (!(PyArray_ISINTEGER(indices) || PyArray_ISBOOL(indices))) {
    /* ensure dtype is int-based */
    PyErr_SetString(PyExc_TypeError, NON_INTEGRAL_ERROR_MSG);
    goto fail;
}
```

```C
if (PyArray_DTypeFromObject(item, NPY_MAXDIMS, &dtype) < 0) {
    Py_DECREF(item);
    goto fail;
}
if (dtype == NULL) {
    if (PySequence_Check(item) && PySequence_Size(item) == 0) {
        PyErr_SetString(PyExc_TypeError, EMPTY_SEQUENCE_ERR_MSG);
    }
    Py_DECREF(item);
    goto fail;
}
if (!(PyDataType_ISINTEGER(dtype) || PyDataType_ISBOOL(dtype))) {
    PyErr_SetString(PyExc_TypeError, NON_INTEGRAL_ERROR_MSG);
    Py_DECREF(dtype);
    Py_DECREF(item);
    goto fail;
}
op[i] = (PyArrayObject *)PyArray_FromAny(item, dtype, 0, 0, 0, NULL);
```

to

```C
PyArrayObject* as_int_array(PyObject *obj) {
    PyArrayObject *ret;

    if (!PyArray_Check(obj)) {
        /* prefer int dtype */
        PyArray_Descr *dtype_guess = NULL;
        if (PyArray_DTypeFromObject(obj, NPY_MAXDIMS, &dtype_guess) < 0) {
            return NULL;
        }
        if (dtype_guess == NULL) {
            if (PySequence_Check(obj) && PySequence_Size(obj) == 0) {
                PyErr_SetString(PyExc_TypeError, EMPTY_SEQUENCE_ERR_MSG);
            }
            return NULL;
        }
        ret = (PyArrayObject*)PyArray_FromAny(obj, dtype_guess, 0, 0, 0, NULL);
        if (ret == NULL) {
            return NULL;
        }
    }
    else {
        ret = (PyArrayObject *)obj;
        Py_INCREF(ret);
    }

    if (!(PyArray_ISINTEGER(ret) || PyArray_ISBOOL(ret))) {
        /* ensure dtype is int-based */
        PyErr_SetString(PyExc_TypeError, NON_INTEGRAL_ERROR_MSG);
        return NULL;
    }

    return ret;
}
```
```C
indices = as_int_array(indices0)
```
```C
op[i] = as_int_array(item);
```

I don're care about the `as_int_array` name, there's probably a better name

File: numpy/core/src/multiarray/compiled_base.c (hunk 12 above)
Comment (mattip) [reply numpy/core/src/multiarray/compiled_base.c]: fixed. It seems this comes up often enough I should have a pre-commit hook to find these.

**Comment by mattip** [comment]
> requesting that you merge these two pieces of code

done, as `astype_anyint`

File: numpy/core/src/multiarray/compiled_base.c [hunk 13]
```diff
@@ -832,17 +832,62 @@ arr_interp_complex(PyObject *NPY_UNUSED(self), PyObject *args, PyObject *kwdict)
...
+        }
+    }
+    else {
+        ret = (PyArrayObject *)obj;
+        Py_INCREF(ret);
+    }
+
+    if (!(PyArray_ISINTEGER(ret) || PyArray_ISBOOL(ret))) {
+        /* ensure dtype is int-based */
+        PyErr_SetString(PyExc_TypeError, NON_INTEGRAL_ERROR_MSG);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/compiled_base.c]: Missing decref of `ret`

File: numpy/core/src/multiarray/compiled_base.c [hunk 14]
```diff
@@ -854,29 +899,26 @@ static int sequence_to_arrays(PyObject *seq,
     }
 
     for (i = 0; i < count; ++i) {
+        PyArray_Descr *dtype = NULL;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/compiled_base.c]: numpy/core/src/multiarray/compiled_base.c:902:24: warning: unused variable ‘dtype’

File: numpy/core/src/multiarray/compiled_base.c (hunk 13 above)
Comment (mattip) [reply numpy/core/src/multiarray/compiled_base.c]: fixed

File: numpy/core/src/multiarray/compiled_base.c (hunk 14 above)
Comment (mattip) [reply numpy/core/src/multiarray/compiled_base.c]: fixed

**Review by eric-wieser — APPROVED** [review]
Looks good now, thanks!
