### PR TITLE
BUG: Fix ndarray.tofile large file corruption in append mode

### LINKED ISSUE #8329: numpy.ndarray.tofile creates a corrupt file for large arrays in append file mode
When saving a large array (>= 2,097,152 doubles), the `tofile` function creates a file twice the size of the data, and the first half of the file is all zeros. This occurs only in the append file mode (`"ab"`).

My system:
```
Linux 4.8.10-1-ARCH x86_64
Python 3.5.2
numpy.version.version == '1.11.2'
```

Code to reproduce:
```python
import numpy

def foo(n, file, mode):
    m = numpy.random.rand(n)
    open(file, "wb").close() # delete old file contents
    f = open(file, mode)
    m.tofile(f)
    f.close()

    n = numpy.fromfile(open(file, "rb"))
    print("correct" if numpy.array_equal(m, n) else "incorrect")

foo(2097151, "f1", "ab") # correct
foo(2097152, "f2", "ab") # incorrect
foo(2097152, "f3", "wb") # correct```

### PR DESCRIPTION
**Pull request by potocpav**
Fixes by using the flag `FALLOC_FL_KEEP_SIZE` (=1) in the `fappend` call.

Fixes #8329

### CODE REVIEW

**Comment by charris** [comment]
Works for me. @juliantaylor Comment?

File: numpy/core/src/multiarray/convert.c [hunk 1]
```diff
@@ -46,7 +46,7 @@ npy_fallocate(npy_intp nbytes, FILE * fp)
     }
     /* btrfs can take a while to allocate making release worthwhile */
     NPY_BEGIN_ALLOW_THREADS;
-    r = fallocate(fileno(fp), 0, npy_ftell(fp), nbytes);
+    r = fallocate(fileno(fp), 1, npy_ftell(fp), nbytes);
```
Comment (juliantaylor) [inline numpy/core/src/multiarray/convert.c]: should have a comment that this is FALLOC_FL_KEEP_SIZE needed for the case of files opened in append mode

**Comment by juliantaylor** [comment]
might be a good idea to flush the file descriptor too, in case there might be some unexpected interactions between the call and unwritten data in the descriptor.

**Comment by juliantaylor** [comment]
a test writing two arrays to an append mode file would also be good, similar to the above test but without the seek.

**Comment by potocpav** [comment]
@juliantaylor I added a `fflush` call **before** the `fappend` call. Is that what you had in mind?

**Comment by juliantaylor** [comment]
yes, thank you. Can you still squash the two commits please.

**Comment by potocpav** [comment]
Sure, done.

**Comment by juliantaylor** [comment]
thanks
