### PR TITLE
BUG: add.reduce gives wrong results for arrays with funny strides

### LINKED ISSUE #9876: sum gives wrong result for structured arrays
```python
>>> a = np.zeros(1000, dtype=[('a', np.int64), ('b', np.float64), ('c', np.int32)])
>>> a['b'].sum()
0.0
>>> a['a'] = np.arange(1, 1+len(a))
>>> a['b'].sum()  # expecting 0 here
1.7060846163323196e-309
>>> 
```
all works fine if I change last one field to int64
```python
>>> a = np.zeros(1000, dtype=[('a', np.int64), ('b', np.float64), ('c', np.int64)])
>>> a['a'] = np.arange(1, 1+len(a))
>>> a['b'].sum()
0.0
```

```python
>>> np.__version__
'1.13.3'
>>> sys.version
'3.6.1 (default, May 30 2017, 02:29:58) \n[GCC 6.3.0 20170516]'
```
Debian stable 32bit

### PR DESCRIPTION
**Pull request by ahaldane**
Fixes #9876, which turns out to be a long-standing bug going back to at least 1.11.

The calculations in `pairwise_sum_@TYPE@` assumed that the stride of an array was always a multiple of its itemsize, but this is not always the case (see test case).

This PR fixes this by working with `char*` arrays and then casting to `ftype*` pointers before dereferencing them, allowing us to access memory locations which are not a multiple of the itemsize. See [this comment](https://github.com/numpy/numpy/issues/9876#issuecomment-337779071) for some more details.

This was heavily optimized code. I am fairly sure I did not break the optimizations (ie, the prefetch lines) though.

### CODE REVIEW

**Comment by charris** [comment]
Note that some architectures require that the items be aligned, SPARC for instance.

@juliantaylor Thoughts?

**Comment by ahaldane** [comment]
By the time this function is called, all the elements of the array should be guaranteed to be aligned (according to the C compiler and numpy), so there is no risk of misaligned access. Rather, the problem was an incorrect stride calculation.

File: numpy/core/src/umath/loops.c.src [hunk 1]
```diff
@@ -1642,26 +1642,26 @@ pairwise_sum_@TYPE@(@dtype@ *a, npy_uintp n, npy_intp stride)
...
-            r[7] += @trf@(a[(i + 7) * stride]);
+            NPY_PREFETCH(&a[(i + 512) * stride], 0, 3);
+            r[0] += @trf@(*((@dtype@*)&a[(i + 0) * stride]));
+            r[1] += @trf@(*((@dtype@*)&a[(i + 1) * stride]));
+            r[2] += @trf@(*((@dtype@*)&a[(i + 2) * stride]));
+            r[3] += @trf@(*((@dtype@*)&a[(i + 3) * stride]));
+            r[4] += @trf@(*((@dtype@*)&a[(i + 4) * stride]));
+            r[5] += @trf@(*((@dtype@*)&a[(i + 5) * stride]));
+            r[6] += @trf@(*((@dtype@*)&a[(i + 6) * stride]));
+            r[7] += @trf@(*((@dtype@*)&a[(i + 7) * stride]));
```
Comment (eric-wieser) [inline numpy/core/src/umath/loops.c.src]: Might be cleaner as `*(@dtype@ *)(a + (i + 7) * stride)`

File: numpy/core/src/umath/loops.c.src [hunk 2]
```diff
@@ -1642,26 +1642,26 @@ pairwise_sum_@TYPE@(@dtype@ *a, npy_uintp n, npy_intp stride)
...
+        r[2] = @trf@(*((@dtype@*)&a[2 * stride]));
+        r[3] = @trf@(*((@dtype@*)&a[3 * stride]));
+        r[4] = @trf@(*((@dtype@*)&a[4 * stride]));
+        r[5] = @trf@(*((@dtype@*)&a[5 * stride]));
+        r[6] = @trf@(*((@dtype@*)&a[6 * stride]));
+        r[7] = @trf@(*((@dtype@*)&a[7 * stride]));
 
         for (i = 8; i < n - (n % 8); i += 8) {
             /* small blocksizes seems to mess with hardware prefetch */
-            NPY_PREFETCH(&a[(i + 512 / sizeof(a[0])) * stride], 0, 3);
```
Comment (eric-wieser) [inline numpy/core/src/umath/loops.c.src]: @charris, this is a good indication that the 512 used for prefetching that I picked up in #9705 was meant to measure bytes, not items

**Comment by eric-wieser** [comment]
> This was heavily optimized code. I am fairly sure I did not break the optimizations (ie, the prefetch lines) though.

It might be worth branching on whether `stride % itemsize == 0` at some level, and repeating the loop in both branches.

File: numpy/core/src/umath/loops.c.src (hunk 1 above)
Comment (charris) [reply numpy/core/src/umath/loops.c.src]: That does look better. Also up above.

Comment (charris) [reply numpy/core/src/umath/loops.c.src]: And down below.

**Comment by ahaldane** [comment]
Updated to use pointer arithmetic. I wasn't sure what you meant about special-casing the `stride % itemsize == 0` case.

Also, in case anyone is curious, here is the disassembled `pairwise_sum_DOUBLE` on an x64 system, which appears to properly prefetch and use vectorized instructions:
<details>
<summary>Click to expand</summary>

```assembly_x86
Dump of assembler code for function pairwise_sum_DOUBLE:
   0x000000000017044d <+0>:	push   %rbp
   0x000000000017044e <+1>:	mov    %rsp,%rbp
   0x0000000000170451 <+4>:	sub    $0xa0,%rsp
   0x0000000000170458 <+11>:	mov    %rdi,-0x88(%rbp)
   0x000000000017045f <+18>:	mov    %rsi,-0x90(%rbp)
   0x0000000000170466 <+25>:	mov    %rdx,-0x98(%rbp)
   0x000000000017046d <+32>:	mov    %fs:0x28,%rax
   0x0000000000170476 <+41>:	mov    %rax,-0x8(%rbp)
   0x000000000017047a <+45>:	xor    %eax,%eax
   0x000000000017047c <+47>:	cmpq   $0x7,-0x90(%rbp)
   0x0000000000170484 <+55>:	ja     0x1704e0 <pairwise_sum_DOUBLE+147>
   0x0000000000170486 <+57>:	pxor   %xmm0,%xmm0
   0x000000000017048a <+61>:	movsd  %xmm0,-0x70(%rbp)
   0x000000000017048f <+66>:	movq   $0x0,-0x78(%rbp)
   0x0000000000170497 <+74>:	jmp    0x1704c9 <pairwise_sum_DOUBLE+124>
   0x0000000000170499 <+76>:	mov    -0x78(%rbp),%rax
   0x000000000017049d <+80>:	imul   -0x98(%rbp),%rax
   0x00000000001704a5 <+88>:	mov    %rax,%rdx
   0x00000000001704a8 <+91>:	mov    -0x88(%rbp),%rax
   0x00000000001704af <+98>:	add    %rdx,%rax
   0x00000000001704b2 <+101>:	movsd  (%rax),%xmm0
   0x00000000001704b6 <+105>:	movsd  -0x70(%rbp),%xmm1
   0x00000000001704bb <+110>:	addsd  %xmm1,%xmm0
   0x00000000001704bf <+114>:	movsd  %xmm0,-0x70(%rbp)
   0x00000000001704c4 <+119>:	addq   $0x1,-0x78(%rbp)
   0x00000000001704c9 <+124>:	mov    -0x78(%rbp),%rax
   0x00000000001704cd <+128>:	cmp    %rax,-0x90(%rbp)
   0x00000000001704d4 <+135>:	ja     0x170499 <pairwise_sum_DOUBLE+76>
   0x00000000001704d6 <+137>:	movsd  -0x70(%rbp),%xmm0
   0x00000000001704db <+142>:	jmpq   0x1708c1 <pairwise_sum_DOUBLE+1140>
   0x00000000001704e0 <+147>:	cmpq   $0x80,-0x90(%rbp)
   0x00000000001704eb <+158>:	ja     0x17084b <pairwise_sum_DOUBLE+1022>
   0x00000000001704f1 <+164>:	mov    -0x88(%rbp),%rax
   0x00000000001704f8 <+171>:	movsd  (%rax),%xmm0
   0x00000000001704fc <+175>:	movsd  %xmm0,-0x50(%rbp)
   0x0000000000170501 <+180>:	mov    -0x98(%rbp),%rdx
   0x0000000000170508 <+187>:	mov    -0x88(%rbp),%rax
   0x000000000017050f <+194>:	add    %rdx,%rax
   0x0000000000170512 <+197>:	movsd  (%rax),%xmm0
   0x0000000000170516 <+201>:	movsd  %xmm0,-0x48(%rbp)
   0x000000000017051b <+206>:	mov    -0x98(%rbp),%rax
   0x0000000000170522 <+213>:	add    %rax,%rax
   0x0000000000170525 <+216>:	mov    %rax,%rdx
   0x0000000000170528 <+219>:	mov    -0x88(%rbp),%rax
   0x000000000017052f <+226>:	add    %rdx,%rax
   0x0000000000170532 <+229>:	movsd  (%rax),%xmm0
   0x0000000000170536 <+233>:	movsd  %xmm0,-0x40(%rbp)
   0x000000000017053b <+238>:	mov    -0x98(%rbp),%rdx
   0x0000000000170542 <+245>:	mov    %rdx,%rax
   0x0000000000170545 <+248>:	add    %rax,%rax
   0x0000000000170548 <+251>:	add    %rdx,%rax
   0x000000000017054b <+254>:	mov    %rax,%rdx
   0x000000000017054e <+257>:	mov    -0x88(%rbp),%rax
   0x0000000000170555 <+264>:	add    %rdx,%rax
   0x0000000000170558 <+267>:	movsd  (%rax),%xmm0
   0x000000000017055c <+271>:	movsd  %xmm0,-0x38(%rbp)
   0x0000000000170561 <+276>:	mov    -0x98(%rbp),%rax
   0x0000000000170568 <+283>:	shl    $0x2,%rax
   0x000000000017056c <+287>:	mov    %rax,%rdx
   0x000000000017056f <+290>:	mov    -0x88(%rbp),%rax
   0x0000000000170576 <+297>:	add    %rdx,%rax
   0x0000000000170579 <+300>:	movsd  (%rax),%xmm0
   0x000000000017057d <+304>:	movsd  %xmm0,-0x30(%rbp)
   0x0000000000170582 <+309>:	mov    -0x98(%rbp),%rdx
   0x0000000000170589 <+316>:	mov    %rdx,%rax
   0x000000000017058c <+319>:	shl    $0x2,%rax
   0x0000000000170590 <+323>:	add    %rdx,%rax
   0x0000000000170593 <+326>:	mov    %rax,%rdx
   0x0000000000170596 <+329>:	mov    -0x88(%rbp),%rax
   0x000000000017059d <+336>:	add    %rdx,%rax
   0x00000000001705a0 <+339>:	movsd  (%rax),%xmm0
   0x00000000001705a4 <+343>:	movsd  %xmm0,-0x28(%rbp)
   0x00000000001705a9 <+348>:	mov    -0x98(%rbp),%rdx
   0x00000000001705b0 <+355>:	mov    %rdx,%rax
   0x00000000001705b3 <+358>:	add    %rax,%rax
   0x00000000001705b6 <+361>:	add    %rdx,%rax
   0x00000000001705b9 <+364>:	add    %rax,%rax
   0x00000000001705bc <+367>:	mov    %rax,%rdx
   0x00000000001705bf <+370>:	mov    -0x88(%rbp),%rax
   0x00000000001705c6 <+377>:	add    %rdx,%rax
   0x00000000001705c9 <+380>:	movsd  (%rax),%xmm0
   0x00000000001705cd <+384>:	movsd  %xmm0,-0x20(%rbp)
   0x00000000001705d2 <+389>:	mov    -0x98(%rbp),%rdx
   0x00000000001705d9 <+396>:	mov    %rdx,%rax
   0x00000000001705dc <+399>:	shl    $0x3,%rax
   0x00000000001705e0 <+403>:	sub    %rdx,%rax
   0x00000000001705e3 <+406>:	mov    %rax,%rdx
   0x00000000001705e6 <+409>:	mov    -0x88(%rbp),%rax
   0x00000000001705ed <+416>:	add    %rdx,%rax
   0x00000000001705f0 <+419>:	movsd  (%rax),%xmm0
   0x00000000001705f4 <+423>:	movsd  %xmm0,-0x18(%rbp)
   0x00000000001705f9 <+428>:	movq   $0x8,-0x68(%rbp)
   0x0000000000170601 <+436>:	jmpq   0x1707a1 <pairwise_sum_DOUBLE+852>
   0x0000000000170606 <+441>:	mov    -0x68(%rbp),%rax
   0x000000000017060a <+445>:	add    $0x200,%rax
   0x0000000000170610 <+451>:	imul   -0x98(%rbp),%rax
   0x0000000000170618 <+459>:	mov    %rax,%rdx
   0x000000000017061b <+462>:	mov    -0x88(%rbp),%rax
   0x0000000000170622 <+469>:	add    %rdx,%rax
   0x0000000000170625 <+472>:	prefetcht0 (%rax)
   0x0000000000170628 <+475>:	movsd  -0x50(%rbp),%xmm1
   0x000000000017062d <+480>:	mov    -0x68(%rbp),%rax
   0x0000000000170631 <+484>:	imul   -0x98(%rbp),%rax
   0x0000000000170639 <+492>:	mov    %rax,%rdx
   0x000000000017063c <+495>:	mov    -0x88(%rbp),%rax
   0x0000000000170643 <+502>:	add    %rdx,%rax
   0x0000000000170646 <+505>:	movsd  (%rax),%xmm0
   0x000000000017064a <+509>:	addsd  %xmm1,%xmm0
   0x000000000017064e <+513>:	movsd  %xmm0,-0x50(%rbp)
   0x0000000000170653 <+518>:	movsd  -0x48(%rbp),%xmm1
   0x0000000000170658 <+523>:	mov    -0x68(%rbp),%rax
   0x000000000017065c <+527>:	add    $0x1,%rax
   0x0000000000170660 <+531>:	imul   -0x98(%rbp),%rax
   0x0000000000170668 <+539>:	mov    %rax,%rdx
   0x000000000017066b <+542>:	mov    -0x88(%rbp),%rax
   0x0000000000170672 <+549>:	add    %rdx,%rax
   0x0000000000170675 <+552>:	movsd  (%rax),%xmm0
   0x0000000000170679 <+556>:	addsd  %xmm1,%xmm0
   0x000000000017067d <+560>:	movsd  %xmm0,-0x48(%rbp)
   0x0000000000170682 <+565>:	movsd  -0x40(%rbp),%xmm1
   0x0000000000170687 <+570>:	mov    -0x68(%rbp),%rax
   0x000000000017068b <+574>:	add    $0x2,%rax
   0x000000000017068f <+578>:	imul   -0x98(%rbp),%rax
   0x0000000000170697 <+586>:	mov    %rax,%rdx
   0x000000000017069a <+589>:	mov    -0x88(%rbp),%rax
   0x00000000001706a1 <+596>:	add    %rdx,%rax
   0x00000000001706a4 <+599>:	movsd  (%rax),%xmm0
   0x00000000001706a8 <+603>:	addsd  %xmm1,%xmm0
   0x00000000001706ac <+607>:	movsd  %xmm0,-0x40(%rbp)
   0x00000000001706b1 <+612>:	movsd  -0x38(%rbp),%xmm1
   0x00000000001706b6 <+617>:	mov    -0x68(%rbp),%rax
   0x00000000001706ba <+621>:	add    $0x3,%rax
   0x00000000001706be <+625>:	imul   -0x98(%rbp),%rax
   0x00000000001706c6 <+633>:	mov    %rax,%rdx
   0x00000000001706c9 <+636>:	mov    -0x88(%rbp),%rax
   0x00000000001706d0 <+643>:	add    %rdx,%rax
   0x00000000001706d3 <+646>:	movsd  (%rax),%xmm0
   0x00000000001706d7 <+650>:	addsd  %xmm1,%xmm0
   0x00000000001706db <+654>:	movsd  %xmm0,-0x38(%rbp)
   0x00000000001706e0 <+659>:	movsd  -0x30(%rbp),%xmm1
   0x00000000001706e5 <+664>:	mov    -0x68(%rbp),%rax
   0x00000000001706e9 <+668>:	add    $0x4,%rax
   0x00000000001706ed <+672>:	imul   -0x98(%rbp),%rax
   0x00000000001706f5 <+680>:	mov    %rax,%rdx
   0x00000000001706f8 <+683>:	mov    -0x88(%rbp),%rax
   0x00000000001706ff <+690>:	add    %rdx,%rax
   0x0000000000170702 <+693>:	movsd  (%rax),%xmm0
   0x0000000000170706 <+697>:	addsd  %xmm1,%xmm0
   0x000000000017070a <+701>:	movsd  %xmm0,-0x30(%rbp)
   0x000000000017070f <+706>:	movsd  -0x28(%rbp),%xmm1
   0x0000000000170714 <+711>:	mov    -0x68(%rbp),%rax
   0x0000000000170718 <+715>:	add    $0x5,%rax
   0x000000000017071c <+719>:	imul   -0x98(%rbp),%rax
   0x0000000000170724 <+727>:	mov    %rax,%rdx
   0x0000000000170727 <+730>:	mov    -0x88(%rbp),%rax
   0x000000000017072e <+737>:	add    %rdx,%rax
   0x0000000000170731 <+740>:	movsd  (%rax),%xmm0
   0x0000000000170735 <+744>:	addsd  %xmm1,%xmm0
   0x0000000000170739 <+748>:	movsd  %xmm0,-0x28(%rbp)
   0x000000000017073e <+753>:	movsd  -0x20(%rbp),%xmm1
   0x0000000000170743 <+758>:	mov    -0x68(%rbp),%rax
   0x0000000000170747 <+762>:	add    $0x6,%rax
   0x000000000017074b <+766>:	imul   -0x98(%rbp),%rax
   0x0000000000170753 <+774>:	mov    %rax,%rdx
   0x0000000000170756 <+777>:	mov    -0x88(%rbp),%rax
   0x000000000017075d <+784>:	add    %rdx,%rax
   0x0000000000170760 <+787>:	movsd  (%rax),%xmm0
   0x0000000000170764 <+791>:	addsd  %xmm1,%xmm0
   0x0000000000170768 <+795>:	movsd  %xmm0,-0x20(%rbp)
   0x000000000017076d <+800>:	movsd  -0x18(%rbp),%xmm1
   0x0000000000170772 <+805>:	mov    -0x68(%rbp),%rax
   0x0000000000170776 <+809>:	add    $0x7,%rax
   0x000000000017077a <+813>:	imul   -0x98(%rbp),%rax
   0x0000000000170782 <+821>:	mov    %rax,%rdx
   0x0000000000170785 <+824>:	mov    -0x88(%rbp),%rax
   0x000000000017078c <+831>:	add    %rdx,%rax
   0x000000000017078f <+834>:	movsd  (%rax),%xmm0
   0x0000000000170793 <+838>:	addsd  %xmm1,%xmm0
   0x0000000000170797 <+842>:	movsd  %xmm0,-0x18(%rbp)
   0x000000000017079c <+847>:	addq   $0x8,-0x68(%rbp)
   0x00000000001707a1 <+852>:	mov    -0x90(%rbp),%rax
   0x00000000001707a8 <+859>:	and    $0xfffffffffffffff8,%rax
   0x00000000001707ac <+863>:	mov    %rax,%rdx
   0x00000000001707af <+866>:	mov    -0x68(%rbp),%rax
   0x00000000001707b3 <+870>:	cmp    %rax,%rdx
   0x00000000001707b6 <+873>:	ja     0x170606 <pairwise_sum_DOUBLE+441>
   0x00000000001707bc <+879>:	movsd  -0x50(%rbp),%xmm1
   0x00000000001707c1 <+884>:	movsd  -0x48(%rbp),%xmm0
   0x00000000001707c6 <+889>:	addsd  %xmm0,%xmm1
   0x00000000001707ca <+893>:	movsd  -0x40(%rbp),%xmm2
   0x00000000001707cf <+898>:	movsd  -0x38(%rbp),%xmm0
   0x00000000001707d4 <+903>:	addsd  %xmm2,%xmm0
   0x00000000001707d8 <+907>:	addsd  %xmm0,%xmm1
   0x00000000001707dc <+911>:	movsd  -0x30(%rbp),%xmm2
   0x00000000001707e1 <+916>:	movsd  -0x28(%rbp),%xmm0
   0x00000000001707e6 <+921>:	addsd  %xmm0,%xmm2
   0x00000000001707ea <+925>:	movsd  -0x20(%rbp),%xmm3
   0x00000000001707ef <+930>:	movsd  -0x18(%rbp),%xmm0
   0x00000000001707f4 <+935>:	addsd  %xmm3,%xmm0
   0x00000000001707f8 <+939>:	addsd  %xmm2,%xmm0
   0x00000000001707fc <+943>:	addsd  %xmm1,%xmm0
   0x0000000000170800 <+947>:	movsd  %xmm0,-0x60(%rbp)
   0x0000000000170805 <+952>:	jmp    0x170837 <pairwise_sum_DOUBLE+1002>
   0x0000000000170807 <+954>:	mov    -0x68(%rbp),%rax
   0x000000000017080b <+958>:	imul   -0x98(%rbp),%rax
   0x0000000000170813 <+966>:	mov    %rax,%rdx
   0x0000000000170816 <+969>:	mov    -0x88(%rbp),%rax
   0x000000000017081d <+976>:	add    %rdx,%rax
   0x0000000000170820 <+979>:	movsd  (%rax),%xmm0
   0x0000000000170824 <+983>:	movsd  -0x60(%rbp),%xmm1
   0x0000000000170829 <+988>:	addsd  %xmm1,%xmm0
   0x000000000017082d <+992>:	movsd  %xmm0,-0x60(%rbp)
   0x0000000000170832 <+997>:	addq   $0x1,-0x68(%rbp)
   0x0000000000170837 <+1002>:	mov    -0x68(%rbp),%rax
   0x000000000017083b <+1006>:	cmp    %rax,-0x90(%rbp)
   0x0000000000170842 <+1013>:	ja     0x170807 <pairwise_sum_DOUBLE+954>
   0x0000000000170844 <+1015>:	movsd  -0x60(%rbp),%xmm0
   0x0000000000170849 <+1020>:	jmp    0x1708c1 <pairwise_sum_DOUBLE+1140>
   0x000000000017084b <+1022>:	mov    -0x90(%rbp),%rax
   0x0000000000170852 <+1029>:	shr    %rax
   0x0000000000170855 <+1032>:	mov    %rax,-0x58(%rbp)
   0x0000000000170859 <+1036>:	andq   $0xfffffffffffffff8,-0x58(%rbp)
   0x000000000017085e <+1041>:	mov    -0x98(%rbp),%rdx
   0x0000000000170865 <+1048>:	mov    -0x58(%rbp),%rcx
   0x0000000000170869 <+1052>:	mov    -0x88(%rbp),%rax
   0x0000000000170870 <+1059>:	mov    %rcx,%rsi
   0x0000000000170873 <+1062>:	mov    %rax,%rdi
   0x0000000000170876 <+1065>:	callq  0x17044d <pairwise_sum_DOUBLE>
   0x000000000017087b <+1070>:	movsd  %xmm0,-0xa0(%rbp)
   0x0000000000170883 <+1078>:	mov    -0x90(%rbp),%rax
   0x000000000017088a <+1085>:	sub    -0x58(%rbp),%rax
   0x000000000017088e <+1089>:	mov    -0x98(%rbp),%rdx
   0x0000000000170895 <+1096>:	mov    %rdx,%rcx
   0x0000000000170898 <+1099>:	imul   -0x58(%rbp),%rcx
   0x000000000017089d <+1104>:	mov    -0x88(%rbp),%rdx
   0x00000000001708a4 <+1111>:	add    %rdx,%rcx
   0x00000000001708a7 <+1114>:	mov    -0x98(%rbp),%rdx
   0x00000000001708ae <+1121>:	mov    %rax,%rsi
   0x00000000001708b1 <+1124>:	mov    %rcx,%rdi
   0x00000000001708b4 <+1127>:	callq  0x17044d <pairwise_sum_DOUBLE>
   0x00000000001708b9 <+1132>:	addsd  -0xa0(%rbp),%xmm0
   0x00000000001708c1 <+1140>:	mov    -0x8(%rbp),%rax
   0x00000000001708c5 <+1144>:	xor    %fs:0x28,%rax
   0x00000000001708ce <+1153>:	je     0x1708d6 <pairwise_sum_DOUBLE+1161>
   0x00000000001708d0 <+1155>:	callq  *0x2a2cea(%rip)        # 0x4135c0
   0x00000000001708d6 <+1161>:	leaveq 
   0x00000000001708d7 <+1162>:	retq   
End of assembler dump.
```
</details>

**Comment by eric-wieser** [comment]
I mean something like
```
if(stride % itemsize == 0) {
    float *f_ptr = char_ptr;
    stride /= itemsize;
    // do unrolled loops with f_ptr
}
else {
    // do unrolled loops with char_ptr
}
```
with the thinking that the compiler might be able to use more efficient vectorizations for semi-contiguous data.

Probably not worth doing unless we see a performance regression though.

**Comment by charris** [comment]
Assembly dumps are the beginning of wisdom 8-)

File: numpy/core/src/umath/loops.c.src [hunk 3]
```diff
@@ -1642,26 +1642,26 @@ pairwise_sum_@TYPE@(@dtype@ *a, npy_uintp n, npy_intp stride)
...
-            r[0] += @trf@(a[(i + 0) * stride]);
-            r[1] += @trf@(a[(i + 1) * stride]);
-            r[2] += @trf@(a[(i + 2) * stride]);
-            r[3] += @trf@(a[(i + 3) * stride]);
-            r[4] += @trf@(a[(i + 4) * stride]);
-            r[5] += @trf@(a[(i + 5) * stride]);
-            r[6] += @trf@(a[(i + 6) * stride]);
-            r[7] += @trf@(a[(i + 7) * stride]);
+            NPY_PREFETCH(a + (i + 512) * stride, 0, 3);
```
Comment (charris) [inline numpy/core/src/umath/loops.c.src]: After the original, I think this should be `NPY_PREFETCH(a + (i + 512 / sizeof(@dtype@)) * stride, 0, 3);` . I don't know that it makes much difference in practice.

Comment (ahaldane) [reply numpy/core/src/umath/loops.c.src]: Yeah I think you're right. This confused me since when comparing the original and new versions, not only are we changing `a`'s type, but we are also redefining the `stride` variable to reflect the stride in bytes rather than the stride in `itemsize`s. 

The original code referred to memory position (in bytes) `a + (i + 512 / sizeof(a[0])) * (stride/sizeof(a[0]))  * sizeof(a[0])` where that last `sizeof` term accounts for C array indexing behavior for a pointer of dtype type, and where `stride` is the array stride in bytes. 

In the new code, we use a `char*` pointer, so should absorb the last sizeof into the expression, which should give  `a + (i + 512 / sizeof(@dtype@)) * stride` as you said.

File: numpy/core/src/umath/loops.c.src [hunk 4]
```diff
@@ -2420,26 +2418,26 @@ pairwise_sum_@TYPE@(@ftype@ *rr, @ftype@ * ri, @ftype@ * a, npy_uintp n,
...
-            NPY_PREFETCH(&a[(i + 512 / sizeof(a[0])) * stride], 0, 3);
-            r[0] += a[(i + 0) * stride];
-            r[1] += a[(i + 0) * stride + 1];
-            r[2] += a[(i + 2) * stride];
-            r[3] += a[(i + 2) * stride + 1];
-            r[4] += a[(i + 4) * stride];
-            r[5] += a[(i + 4) * stride + 1];
-            r[6] += a[(i + 6) * stride];
-            r[7] += a[(i + 6) * stride + 1];
+            NPY_PREFETCH(a + (i + 512) * stride, 0, 3);
```
Comment (charris) [inline numpy/core/src/umath/loops.c.src]: See above.

File: numpy/core/src/umath/loops.c.src (hunk 3 above)
Comment (charris) [inline numpy/core/src/umath/loops.c.src]: See above

**Comment by ahaldane** [comment]
Fixed. 

I tried special-casing the `stride == sizeof(@fdtype@)` case but saw no improvement, so didn't add it.

File: numpy/core/src/umath/loops.c.src (hunk 3 above)
Comment (charris) [reply numpy/core/src/umath/loops.c.src]: Honestly, I think this is the sort of thing a good compiler should handle as part of loop optimization. It's all a bit fuzzy, with optimum depending on latency and other execution factors. Getting it wrong can even have a negative impact.

Comment (eric-wieser) [reply numpy/core/src/umath/loops.c.src]: I think my [earlier comment](https://github.com/numpy/numpy/pull/9887#discussion_r145600166) was perhaps correct after all then

**Comment by charris** [comment]
Thanks Allan, and kudos for tracking that down
