### PR TITLE
BUG, ENH: Access `PyArrayMultiIterObject` fields using macros.

### LINKED ISSUE #24649: BUG: Cython 3 pyd file doesn't allow access to multiterobject fields
_Originally posted by @zoj613 in https://github.com/numpy/numpy/issues/16986#issuecomment-1706708621_

The cython 3 `.pyd` file is a bit more restrictive, with the aim of being more compatible with the opaque structs probably:  It removed some struct fields, e.g. from the `numpy.broadcast` cdef class.

Some of these fields, however, are required and we don't actually have a macro version that users can use instead (unlike the `.pyd` file suggests).
We could just add those fields for now.  Alternatively, we could add the macro's and use the properties in the `.pyd` file to avoid explicit access.
(This would not change things for now, but will make it a bit easier to make the struct truly opaque in some future version.)

---

The missing fields probably mean that the legacy multi-iterator is effectively not usable from Cython in Cython 3.

### PR DESCRIPTION
**Pull request by zoj613**
Adds macros to the C-API for accessing `PyArrayMultiIterObject` fields. At the Cython level, these macros can be used to access fields of a `np.broadcast` type. This is to restore Cython 0.29.X functionality that was lost in #16986 where the fields of `np.broadcast` could no longer be accessed directly.

closes #24649

Cc @seberg, Is there a testing framework for the C-API somewhere? I searched and could not see how one would test the added macros.

### CODE REVIEW

File: numpy/core/include/numpy/ndarraytypes.h [hunk 1]
```diff
@@ -1282,6 +1282,14 @@ typedef struct {
 #define PyArray_MultiIter_NOTDONE(multi)                \
         (_PyMIT(multi)->index < _PyMIT(multi)->size)
 
+#define PyArray_MultiIter_SIZE(multi) (_PyMIT(multi)->size)
+#define PyArray_MultiIter_NDIM(multi) (_PyMIT(multi)->nd)
+#define PyArray_MultiIter_INDEX(multi) (_PyMIT(multi)->index)
+#define PyArray_MultiIter_NUMITER(multi) (_PyMIT(multi)->numiter)
+#define PyArray_MultiIter_DIMS(multi) (_PyMIT(multi)->dimensions)
+#define PyArray_MultiIter_ITERS(multi) (_PyMIT(multi)->iters)
```
Comment (seberg) [inline numpy/core/include/numpy/ndarraytypes.h:1290]: At some point inline functions were preferred.  I don't actually know there is a good reason for that although I like functions.  @mattip do you know a reason?

File: numpy/__init__.cython-30.pxd [hunk 2]
```diff
@@ -542,6 +542,12 @@ cdef extern from "numpy/arrayobject.h":
     void* PyArray_MultiIter_DATA(broadcast multi, npy_intp i) nogil
     void PyArray_MultiIter_NEXTi(broadcast multi, npy_intp i) nogil
     bint PyArray_MultiIter_NOTDONE(broadcast multi) nogil
+    npy_intp PyArray_MultiIter_SIZE(broadcast multi) nogil
+    int PyArray_MultiIter_NDIM(broadcast multi) nogil
+    npy_intp PyArray_MultiIter_INDEX(broadcast multi) nogil
+    int PyArray_MultiIter_NUMITER(broadcast multi) nogil
+    npy_intp* PyArray_MultiIter_DIMS(broadcast multi) nogil
+    void** PyArray_MultiIter_ITERS(broadcast multi) nogil
```
Comment (seberg) [inline numpy/__init__.cython-30.pxd:550]: I think we indeed need those, but we should also add `@property` using them so that you can keep using `bcast.size` and `bcast.shape` as you did before in cython.
(you can search the file for other properties, this is a new feature in Cython 3, that will be very useful to rely on for us in the future.)

**Comment by seberg** [comment]
Thanks!  Sorry, about testing, this is mainly a Cython problem right now.  There are some Cython tests in `core/test/test_cython.py` which use files from `core/test/examples/cython`.  Adding such a test would make sense I think.
Then we can test the attributes access working directly (which will pass after adding the property code).

**Comment by seberg** [comment]
It is a bit weird to add new macros in a backport for cython, but I think we need to backport this to allow projects using this (for better or worse) to transition to cython 3.

File: numpy/__init__.cython-30.pxd (hunk 2 above)
Comment (zoj613) [reply numpy/__init__.cython-30.pxd:580]: Added in 611f15deb81108f0846b630dc2e13d9d33f989e0

**Comment by zoj613** [comment]
Could you take another look when you can @seberg. I addressed the above comments and added tests as suggested.

File: numpy/__init__.pxd [hunk 3]
```diff
@@ -500,6 +500,12 @@ cdef extern from "numpy/arrayobject.h":
     void* PyArray_MultiIter_DATA(broadcast multi, npy_intp i) nogil
     void PyArray_MultiIter_NEXTi(broadcast multi, npy_intp i) nogil
     bint PyArray_MultiIter_NOTDONE(broadcast multi) nogil
+    npy_intp PyArray_MultiIter_SIZE(broadcast multi) nogil
+    int PyArray_MultiIter_NDIM(broadcast multi) nogil
+    npy_intp PyArray_MultiIter_INDEX(broadcast multi) nogil
+    int PyArray_MultiIter_NUMITER(broadcast multi) nogil
+    npy_intp* PyArray_MultiIter_DIMS(broadcast multi) nogil
+    void** PyArray_MultiIter_ITERS(broadcast multi) nogil
```
Comment (seberg) [inline numpy/__init__.pxd:508]: @mattip do you have an opinion about adding Macros?  We could make it static inline functions, I guess.

Adding the structs would maybe make following up with making the struct opaque easier.  Although, unless we change the layout now we would need to wait for a 3.0 "please recompile" release again.
(Unless we make some of these proper functions in the function table.)

(TBH, I am not sure if it is worth it, although the structs are limited to 32 dims and 32 iterators for not very good reasons probably.)

Comment (mattip) [reply numpy/__init__.pxd:508]: I don't think we should touch the cython 0.29.x file, and at some point would prefer we deprecate cython<3.0 use.

**Comment by mattip** [comment]
Is your code using these constructs public? I wonder if there is a better way to use the MultiIter than to expose these internals.

**Comment by zoj613** [comment]
> Is your code using these constructs public? I wonder if there is a better way to use the MultiIter than to expose these internals.

Yes, it is used in several places here: https://github.com/zoj613/polyagamma/blob/main/polyagamma/_polyagamma.pyx

I thought the addition of macros to access information would be considered better than direct access to the struct fields? Also, is there a reason why the Array Iterator API from [here](https://numpy.org/doc/stable/reference/c-api/iterator.html) is not part of the public API? I would have preferred that over using `PyArray_MultiIter_*` but it doesn't appear to be accessible via Cython.

File: numpy/core/include/numpy/ndarraytypes.h [hunk 4]
```diff
@@ -1282,6 +1282,14 @@ typedef struct {
 #define PyArray_MultiIter_NOTDONE(multi)                \
         (_PyMIT(multi)->index < _PyMIT(multi)->size)
 
+#define PyArray_MultiIter_SIZE(multi) (_PyMIT(multi)->size)
+#define PyArray_MultiIter_NDIM(multi) (_PyMIT(multi)->nd)
+#define PyArray_MultiIter_INDEX(multi) (_PyMIT(multi)->index)
+#define PyArray_MultiIter_NUMITER(multi) (_PyMIT(multi)->numiter)
+#define PyArray_MultiIter_DIMS(multi) (_PyMIT(multi)->dimensions)
+#define PyArray_MultiIter_ITERS(multi) ((void **)_PyMIT(multi)->iters)
```
Comment (mattip) [inline numpy/core/include/numpy/ndarraytypes.h:1290]: Could we make these static functions instead?

**Comment by mattip** [comment]
> I thought the addition of macros to access information would be considered better than direct access to the struct fields?

Macros are indeed better than direct access, but even better for flexibility are getter/setter functions, even if they are statically defined. They at least provide some typing information.

> Also, is there a reason ...

I don't think there was ever a demand for it. 

I am not sure I understand how we "removed `np.broadcast` from the 0.29.x cython pxd file in #16986", as the motivation for this PR. All I see is the removal of `extern` from [the declaration](https://github.com/numpy/numpy/pull/16986/files#diff-0c9530af3cdf8705361e0aad1f2f7c3addc6a70a9c51c4643217eccb5ee406b8R227). I think this PR should do the minimum to restore the property access via `broadcast.numiter` and friends for cython 3.0+

**Comment by zoj613** [comment]
> I am not sure I understand how we "removed `np.broadcast` from the 0.29.x cython pxd file in #16986", as the motivation for this PR. All I see is the removal of `extern` from [the declaration](https://github.com/numpy/numpy/pull/16986/files#diff-0c9530af3cdf8705361e0aad1f2f7c3addc6a70a9c51c4643217eccb5ee406b8R227). I think this PR should do the minimum to restore the property access via `broadcast.numiter` and friends for cython 3.0+

In https://github.com/numpy/numpy/pull/16986#issuecomment-1706708621 I mentioned that the ability to access the fields (either directly or indirectly) of a `np.broadcast` object is lost in the cython3 init file, compared to the functionality provided by the init file of cython 0.29.X. If you look at https://github.com/scoder/numpy/blob/df769ef591f8a21f8e39ee30c80e09d1b7e0a705/numpy/__init__.cython-30.pxd#L230-L232, you will notice that the fields no longer exist for `np.broadcast`. That is the motivation for this PR: To restore that functionality by either direct access (via @property functions) or/and using the macros/functions defined in https://github.com/numpy/numpy/pull/24658/files/6ab7f384e927fb3d7afea0fa69b2ee88c9d353ee#diff-1e081d27e4d07ed1eaa8fe4af755d81de8c1dc062c919559b9678788dfc691f3 .

File: numpy/core/include/numpy/ndarraytypes.h (hunk 4 above)
Comment (zoj613) [reply numpy/core/include/numpy/ndarraytypes.h]: Done in [`1ead1e5` (#24658)](https://github.com/numpy/numpy/pull/24658/commits/1ead1e5d720f74b16ab42231c97e3dadb1c9428f)

File: numpy/__init__.pxd (hunk 3 above)
Comment (zoj613) [reply numpy/__init__.pxd]: Reverted in [`fe86e38` (#24658)](https://github.com/numpy/numpy/pull/24658/commits/fe86e382757c781bb7e0ae5eeb51558e9102b394)

**Comment by zoj613** [comment]
Tests are failing now due to 
```
../numpy/core/include/numpy/ndarraytypes.h:1322:1: error: ‘PyArray_MultiIter_ITERS’ defined but not used [-Werror=unused-function]
 1322 | PyArray_MultiIter_ITERS(PyArrayMultiIterObject *multi)
      | ^~~~~~~~~~~~~~~~~~~~~~~
../numpy/core/include/numpy/ndarraytypes.h:1315:1: error: ‘PyArray_MultiIter_DIMS’ defined but not used [-Werror=unused-function]
 1315 | PyArray_MultiIter_DIMS(PyArrayMultiIterObject *multi)
      | ^~~~~~~~~~~~~~~~~~~~~~
../numpy/core/include/numpy/ndarraytypes.h:1308:1: error: ‘PyArray_MultiIter_NDIM’ defined but not used [-Werror=unused-function]
 1308 | PyArray_MultiIter_NDIM(PyArrayMultiIterObject *multi)
      | ^~~~~~~~~~~~~~~~~~~~~~
../numpy/core/include/numpy/ndarraytypes.h:1301:1: error: ‘PyArray_MultiIter_INDEX’ defined but not used [-Werror=unused-function]
 1301 | PyArray_MultiIter_INDEX(PyArrayMultiIterObject *multi)
      | ^~~~~~~~~~~~~~~~~~~~~~~
../numpy/core/include/numpy/ndarraytypes.h:1294:1: error: ‘PyArray_MultiIter_SIZE’ defined but not used [-Werror=unused-function]
 1294 | PyArray_MultiIter_SIZE(PyArrayMultiIterObject *multi)
      | ^~~~~~~~~~~~~~~~~~~~~~
../numpy/core/include/numpy/ndarraytypes.h:1287:1: error: ‘PyArray_MultiIter_NUMITER’ defined but not used [-Werror=unused-function]
 1287 | PyArray_MultiIter_NUMITER(PyArrayMultiIterObject *multi)
```
Any suggestions on what we can do here to make tests pass since these are not directly used in the C source? @seberg

**Comment by seberg** [comment]
You can use the new API and we can add it (not backport).  I would have guess that hte few times someone wanted it, they added it to their own file because they didn't want to wait for upstream to have it anyway (which doesn't mean you can't add it here, too).

**Comment by zoj613** [comment]
> You can use the new API and we can add it (not backport). I would have guess that hte few times someone wanted it, they added it to their own file because they didn't want to wait for upstream to have it anyway (which doesn't mean you can't add it here, too).

Skimming through https://numpy.org/doc/stable/reference/c-api/iterator.html, it looks like this would be great as a separate PR so as to not block this one. I am happy to open one that adds the new iterator API to Cython.

**Review by seberg — APPROVED** [review]
I thought we had already put this in.  For some reason force pushing a rebase to fix the merge conflict isn't working for me, though?!

@zoj613 could you maybe rebase?  Sorry about that.  Otherwise, this should just go in IMO @charris.

**Comment by zoj613** [comment]
> I thought we had already put this in. For some reason force pushing a rebase to fix the merge conflict isn't working for me, though?!
> 
> @zoj613 could you maybe rebase? Sorry about that. Otherwise, this should just go in IMO @charris.

Could you try again? I think I had to toggle the "Allow edits and access to secrets by maintainers" option

**Comment by seberg** [comment]
> Could you try again? I think I had to toggle the "Allow edits and access to secrets by maintainers" option

Thanks, worked.

**Comment by charris** [comment]
This doesn't backport easily. There are failing tests, the names of have changed (_build) making comparisons. I can probably fix things given time, but it would be easier to forego the backport.

**Comment by charris** [comment]
Took this off the backport list.
