### PR TITLE
API: Fix structured dtype cast-safety, promotion, and comparison

### LINKED ISSUE #15494: BUG: concatenate of structured dtypes does not check field orders match
When concatenating, or stacking a list of recarrays, I encountered unexpected outcome when there are empty recarrays with a different column ordering.  In such a case, np.concatenate mixes up the column-key to value assignments. The issue is not present with empty recarrays in general. Only when the ordering of the columns is different from the ordering in the non empty recarray.  I did not expect the ordering of the columns to matter.

### Reproducing code example:

```python
import numpy as np


def assert_as_expected(final_recarray):
    assert len(final_recarray) == 1
    assert final_recarray["a"][0] == 1
    assert final_recarray["b"][0] == 2


A = ("a", "<i8")
B = ("b", "<i8")
a1b2 = np.rec.array(obj=[(1, 2)],     dtype=[A, B])
a_b_ = np.rec.array(obj=np.array([]), dtype=[A, B])
b_a_ = np.rec.array(obj=np.array([]), dtype=[B, A])

fine = [
    a1b2,
    a_b_,
]

evil = [
    a1b2,
    b_a_,
]

assert_as_expected(np.concatenate(fine))
assert_as_expected(np.concatenate(evil))  # <-- fails

```

### Error message:

No warning. No exception. Just unexpected outcome.

### Numpy/Python version information:
```
1.17.2 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
```

### PR DESCRIPTION
**Pull request by seberg**
This PR replaces the old gh-15509 implementing proper type promotion
for structured voids.  It further fixes the casting safety to consider
casts with equivalent field number and matching order as "safe"
and if the names, titles, and offsets match as "equiv".

The change perculates into the void comparison, and since it fixes
the order, it removes the current FutureWarning there as well.

This addresses https://github.com/liberfa/pyerfa/issues/77
and replaces gh-15509 (the implementation has changed too much).

Fixes gh-15494  (and probably a few more)

Co-authored-by: Allan Haldane <allan.haldane@gmail.com>

---

Ping @ahaldane, @mhvk.  The tests will fail right now.  And we have to decide a few things, and probably one more change that is necessary here:

- [x] The tests fail, because the old PR included a test which ensured that the promotion result is always a packed struct.  I think this makes sense, but we further should ensure the promotion result is always native byte order (the old code probably did this also).  The new code doesn't call "promotion" because both descriptors are identical.  This calls `ensure_nbo`.  My plan for `ensure_nbo(descr)` is to actually call a new `DType.ensure_canonical(descr)` (for native dtypes, this will just do the same as `ensure_nbo`) but for structured ones it would: Recursively call `ensure_canonical` and drop offsets.  (Fixing the test failure)  *This should be simple, but requires adding the new slot to the DType, I will probably just do this soon.*  
- [x] I removed the `FutureWarning` from the void comparison path.  This means we have to decide wether void comparisons should ever return an array of `False` if the types they include mismatch.  Or if they should raise an error.  Note that most field mismatches will still raise a `FutureWarning` (since it will call `self[field1_self] == other[field1_other]` which will give a warning when the types are not comparable.  This is thus only about the explicit error messages below.  (Or alternatively, keep the warning for now, even if it is very strange for dtypes that can promote to not also compare.)
- [x] We need to improve test coverage (at least in all those points that coverage points too)

**As such this is currently draft, although all changes should be good, there are some things missing.  But I decided to have a look since gh-15509 is outdated now and it might be tricky to resurrect it without knowing the new layout well.**

**EDIT: Currently based off gh-19346**

### CODE REVIEW

File: numpy/core/src/multiarray/convert_datatype.c [hunk 1]
```diff
@@ -3162,10 +3162,25 @@ can_cast_fields_safety(PyArray_Descr *from, PyArray_Descr *to)
...
+    }
+    else if (from->elsize < to->elsize) {
+        casting = PyArray_MinCastSafety(casting, NPY_SAFE_CASTING);
+    }
+
     Py_ssize_t field_count = PyTuple_Size(from->names);
     if (field_count != PyTuple_Size(to->names)) {
-        /* TODO: This should be rejected! */
-        return NPY_UNSAFE_CASTING;
+        return -1;
```
Comment (mhvk) [inline numpy/core/src/multiarray/convert_datatype.c:3183]: Yay! (as long as `np.zeros((), dtype)` continues to work!)

File: numpy/core/tests/test_dtype.py [hunk 2]
```diff
@@ -151,11 +151,11 @@ def test_field_order_equality(self):
                       'formats': ['i4', 'f4'],
                       'offsets': [0, 4]})
         y = np.dtype({'names': ['B', 'A'],
-                      'formats': ['f4', 'i4'],
+                      'formats': ['i4', 'f4'],
                       'offsets': [4, 0]})
         assert_equal(x == y, False)
-        # But it is currently an equivalent cast:
-        assert np.can_cast(x, y, casting="equiv")
+        # This is an safe cast (not equiv) due to the different names:
```
Comment (mhvk) [inline numpy/core/tests/test_dtype.py:157]: This is a really tricky example, as the way it was written, it described exactly the same bytes in memory, but just with a different order. With the change to use field order, I guess it makes sense that, as written, it would become "unsafe" (integer to float and vice versa). Might it be good to keep that as an example?

And then also insert the new example, where, because it is by field order, it is "safe".

**Review by mhvk — COMMENTED** [review]
This all looks quite clear, but there is one point that probably needs to be clarified. Currently, the docstring for `np.promote_types` states:
```
Returns the data type with the smallest size and smallest scalar
kind to which both ``type1`` and ``type2`` may be safely cast.
```
But for structured dtypes, this PR insists names match, which implies `casting='equiv'`.

This does seem intentional, but I think it is good to ensure it is the right decision. Should `np.promote_types` correspond to `casting='safe'` instead? Looking back at #15494, which concerns the concatenation of two arrays with the same dtype but different names, it is not obvious to me that should be disallowed (though I'd definitely expect the output dtype have names from the dtype of the first array). 

Note that I'm far from sure what the right answer is. But if it is disallowed, we should clarify this in the docs for `promote_types`. And more generally it might make sense to have some overview of when and how field names are used!

p.s. Probably too unrelated: should the following work without a copy?
```
a = np.array([(1., 2.), (3., 4.)], dtype=[('a', 'f8'), ('b', 'f8')])
a.astype([('b', 'f8'), ('a', 'f8')], copy=False)
```

**Comment by mhvk** [comment]
Hmm, it seems the answer to my question about the behaviour of `promote_types` was already given by @ahaldane in https://github.com/numpy/numpy/issues/15494#issuecomment-581398363:
> It seems like we want for two dtypes with different field names but same field dtypes:
> * can be cast to each other
> * cannot be promoted to a common type unambiguously
>
> So can_cast should succeed, but promote_types should fail. Does that make sense?

I think "unambigously" is key here - with name mismatches, one has to pick, which means the result is ambiguous (and it breaks the symmetry promise of `np.promote_types`). So, this PR should include an update to the `np.promote_types` docstring...

@seberg - could you also include in this PR the changelog entry and doc updates to `structured_arrays.py` from #15509? They help understand what is being done!

On the larger scheme, mostly out of curiosity: is the goal that eventually the `DType` classes themselves can tell how promotion/casting should be done? I.e., that if one wanted to have a pure by-order or by-name dtype, one could implemented this?

**Comment by seberg** [comment]
Yes, sorry, I should have copied over the doc changes/change log from the other PR and expanded on that, its a bit too raw right now here!   (And I thought adding the `ensure_canonical` is a bit more straight forward.)

---

About the "safe" casting... My opinion is that the documentation should be updated.  And I can probably do that even ignoring this PR.  I have given up on the idea that the common dtype (promotion) *derives* from casting.  I honestly think its a fallacy.  The two are related, but distinct.

Rather the properties of `P = promote_types(A, B)` are:

* Both `A` and `B` must (should?) safely cast to `P`.  (It seems surprising if we allow violating this.  But arguable we already *do* with `promote_types(int64, float64) -> float64` which is not *really* a safe cast.  The main reason we call it a safe cast is just to make promotion work – because it previously relied on safe casting.)
* We do *not* guarantee this is the "smallest".  This is *typical* and guaranteed for vanilla NumPy, but not a generic rule!
  * If a user adds an `int24` both `uint16` and `int16` can safely cast to it.  But `promote_types(uint16, int16)` *must* continue to return `int32`!
* If `A` can "equiv" cast to `B`, then I suppose we have some strong rules:
  * `P` must exist.
  * `P` can "equiv" cast to `B`
  * `B` can "equiv" cast to `P`
  * (`P` may be `B`, or `B.copy()` or `B.ensure_canonical()` – the last one is a byte-swap or removal offsets/padding.)

Ensuring this is the job of the type promotion (i.e. the DType implementer has to take care).  But in that definition type promotion can be more strict.

---

> p.s. Probably too unrelated: should the following work without a copy?
> ```
> a = np.array([(1., 2.), (3., 4.)], dtype=[('a', 'f8'), ('b', 'f8')])
> a.astype([('b', 'f8'), ('a', 'f8')], copy=False)
> ```

It is absolutely related!  But the fix/change itself is mostly orthongal.  We have to modify `arr.astype()` to use the following logic:
```
casting = get_casting_safety(self.dtype, new_dtype)
if casting == "no":
    # the current branch, should maybe use `self.dtype is new_dtype`, though!
    return self
if casting & cast_is_view:
    # new branch!
    return self.view(new_dype)
else:
    # create new array and cast
```
The changes here are designed so that that if we do that change, your example will also be no-copy.

---

> is the goal that eventually the DType classes themselves can tell how promotion/casting should be done? I.e., that if one wanted to have a pure by-order or by-name dtype, one could implemented this?

This is already the case.  But you don't have the public API to "recurse" into arbitrary dtypes well (e.g. to write the casting functions).  So you could write such a new DType today, but you have to do it in NumPy.
Making enough of that public needs more careful though than most of the API, so I think it is longer term than general user DTypes.  On the other hand, I am also not sure that it is actually problematic to just develop those as part of NumPy!  "Dynamically" structured DTypes are maybe just special enough :).

**Comment by mhvk** [comment]
That really helps! I also like your proposed logic for `astype`, using the (hidden) viewable casting.

p.s. I think `ensure_canonical` is a good idea.

File: numpy/core/_internal.py [hunk 3]
```diff
@@ -433,6 +433,37 @@ def _copy_fields(ary):
...
+        raise TypeError("invalid type promotion")
+
+    # If the lengths all match, assume the titles (if existing) match the
+    # names.
+    if not len(dt1.names) == len(dt1.fields) == len(dt2.fields):
+        raise TypeError(
+            "NumPy currently does not support promotion with field titles.")
+
+    return dtype([(name, promote_types(dt1[name], dt2[name]))
+                  for name in dt1.names])
```
Comment (seberg) [inline numpy/core/_internal.py:465]: Jeesh, I realized that this is actually incorrect.  What is missing is something like `align=dt1.isalignedstruct or dt2.isalignedstruct`.

Is that what we want? Preserve alignment if one is aligned, or drop alignment when one is not aligned?

File: doc/release/upcoming_changes/19226.compatibility.rst [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+* ``"safe"`` allows mismatching field names and titles
+* The cast safety is limited by the cast safety of each included
+  field.
+* The order of fields is used to decide cast safety of each
+  individual field.  Previously, the field names were used and
+  only unsafe casts were possible when names mismatched.
+
+The main important change here is that name mismatches are now
+considered "safe" casts.
+
```
Comment (mattip) [inline doc/release/upcoming_changes/19226.compatibility.rst:85]: This seems too long for a release note. Could it instead summarize the change and point to some more permanent documentation that discusses the details of casting for structured arrays?

File: numpy/core/src/multiarray/convert_datatype.c [hunk 5]
```diff
@@ -897,22 +897,6 @@ promote_types(PyArray_Descr *type1, PyArray_Descr *type2,
...
-{
-    if (PyArray_ISNBO(type->byteorder)) {
-        Py_INCREF(type);
-        return type;
-    }
-    else {
-        return PyArray_DescrNewByteorder(type, NPY_NATIVE);
-    }
-}
-
```
Comment (mattip) [inline numpy/core/src/multiarray/convert_datatype.c:915]: This is no longer needed for non-structured arrays?

Comment (seberg) [reply numpy/core/src/multiarray/convert_datatype.c:915]: It is just moved, but maybe I should limit the change a bit (since this is perfectly fine for most NumPy builtin dtypes).  In any case, it is actually a change of one of the previous PRs that would have to go in first.

Comment (mhvk) [reply numpy/core/src/multiarray/convert_datatype.c:915]: See #19345

File: doc/release/upcoming_changes/19226.compatibility.rst (hunk 4 above)
Comment (mhvk) [reply doc/release/upcoming_changes/19226.compatibility.rst:85]: :+1: - but the text is very good, so do use it! Including in `np.result_types` and `np.promote_types` docstrings.

File: numpy/core/_internal.py (hunk 3 above)
Comment (mhvk) [reply numpy/core/_internal.py]: I agree with your choice of preserving alignment when one is aligned.

**Comment by seberg** [comment]
Code wise, this should be mostly ready now.  I narrowed the special case in `promote_types` (I have not much love for that, but I have no better idea).  I need to reorganize the docs with the release notes and review the old comments though.

**Comment by mhvk** [comment]
@seberg - sounds good. Probably easiest to review once the doc changes are ready too...

**Comment by seberg** [comment]
@ahaldane just a ping in case you have time to have a look on the logic, or whether the tests make sense.  (I think it would be good to include this in the upcoming release and branching is looming, to finally get us all the way on "order", rather than "names" with structured dtypes.)

File: doc/release/upcoming_changes/19226.compatibility.rst (hunk 4 above)
Comment (rossbar) [reply doc/release/upcoming_changes/19226.compatibility.rst:39]: This was at least partially addressed in 14601c and 9967058, but should be checked to see if those changes are sufficient!

**Review by rossbar — APPROVED** [review]
This LGTM, though I mostly focused on the Python components + tests!

**Comment by mattip** [comment]
The linting "errors" are fine to ignore. Thanks @seberg

**Comment by Kongpcmail** [comment]
> This PR replaces the old [gh-15509](https://github.com/numpy/numpy/pull/15509) implementing proper type promotion for structured voids. It further fixes the casting safety to consider casts with equivalent field number and matching order as "safe" and if the names, titles, and offsets match as "equiv".
> 
> The change perculates into the void comparison, and since it fixes the order, it removes the current FutureWarning there as well.
> 
> This addresses [liberfa/pyerfa#77](https://github.com/liberfa/pyerfa/issues/77) and replaces [gh-15509](https://github.com/numpy/numpy/pull/15509) (the implementation has changed too much).
> 
> Fixes [gh-15494](https://github.com/numpy/numpy/issues/15494) (and probably a few more)
> 
> Co-authored-by: Allan Haldane [allan.haldane@gmail.com](mailto:allan.haldane@gmail.com)
> 
> Ping @ahaldane, @mhvk. The tests will fail right now. And we have to decide a few things, and probably one more change that is necessary here:
> 
> * [x]  The tests fail, because the old PR included a test which ensured that the promotion result is always a packed struct.  I think this makes sense, but we further should ensure the promotion result is always native byte order (the old code probably did this also).  The new code doesn't call "promotion" because both descriptors are identical.  This calls `ensure_nbo`.  My plan for `ensure_nbo(descr)` is to actually call a new `DType.ensure_canonical(descr)` (for native dtypes, this will just do the same as `ensure_nbo`) but for structured ones it would: Recursively call `ensure_canonical` and drop offsets.  (Fixing the test failure)  _This should be simple, but requires adding the new slot to the DType, I will probably just do this soon._
> * [x]  I removed the `FutureWarning` from the void comparison path.  This means we have to decide wether void comparisons should ever return an array of `False` if the types they include mismatch.  Or if they should raise an error.  Note that most field mismatches will still raise a `FutureWarning` (since it will call `self[field1_self] == other[field1_other]` which will give a warning when the types are not comparable.  This is thus only about the explicit error messages below.  (Or alternatively, keep the warning for now, even if it is very strange for dtypes that can promote to not also compare.)
> * [x]  We need to improve test coverage (at least in all those points that coverage points too)
> 
> **As such this is currently draft, although all changes should be good, there are some things missing. But I decided to have a look since [gh-15509](https://github.com/numpy/numpy/pull/15509) is outdated now and it might be tricky to resurrect it without knowing the new layout well.**
> 
> **EDIT: Currently based off [gh-19346](https://github.com/numpy/numpy/pull/19346)**
