### PR TITLE
BUG: Fix repeat, accumulate for strings and accumulate API logic

### LINKED ISSUE #27709: BUG: Accumulation uses wrong logic to decide GIL release
### Describe the issue:

`generic_wrapped_legacy_loop` calls `PyErr_Occurred`, which requires the GIL: https://github.com/numpy/numpy/blob/98464cc0cbc1f211482a0756ded305bed1599f18/numpy/_core/src/umath/legacy_array_method.c#L99

This function can be called from `PyUFunc_Accumulate` in a context where the GIL has been released: https://github.com/numpy/numpy/blob/98464cc0cbc1f211482a0756ded305bed1599f18/numpy/_core/src/umath/ufunc_object.c#L2925

We may release the GIL for a large array if https://github.com/numpy/numpy/blob/98464cc0cbc1f211482a0756ded305bed1599f18/numpy/_core/src/umath/ufunc_object.c#L2919C25-L2919C42 `PyDataType_REFCHK(descrs[0])` is true, but that's not a sufficient test: a legacy dtype, even those that do not require reference counting may lead to `generic_wrapped_legacy_loop` being called. In the repro below, this happens with `ml_dtypes.bfloat16`, from the `ml-dtypes` pip package.

### Reproduce the code example:

```python
In [1]: import numpy as np, ml_dtypes
In [2]: x = np.zeros((999999,), ml_dtypes.bfloat16)
In [3]: np.cumsum(x)
Segmentation fault: 11
```

### Error message:

```shell
Segfault. If Python is built with debugging enabled, then we received a `PyGILState_Check` error from `PyErr_Occurred`.
```

### Python and NumPy Versions:

2.1.3
3.12.3 (main, May 30 2024, 08:00:27) [Clang 15.0.0 (clang-1500.3.9.4)]

### Runtime Environment:

n/a

### Context for the issue:

Running TensorFlow's tests under NumPy 2.1.3.

### PR DESCRIPTION
**Pull request by seberg**
This fixes three (actually four) things:
1. `needs_api` was wrongly overwritten, this was just a line not deleted earlier.
2. Accumulate didn't allow string dtypes because it only allowed objects with references, this fixes it and adds a test.
3. `repeat` was just broken with string dtype... I guess there was no actual test.
4. `repeat` internals passed on `cast_info` not by reference. I guess that isn't a bug, but it's weird.

Tests cover things relatively well, although things like GIL release being right is of course harder to test.

Closes gh-27709

---

Wouldn't be surprised if it fixes another string bug out there somewhere, since `repeat` was broken.

### CODE REVIEW

**Comment by seberg** [comment]
I suppose deleting that error is stretching it for backport, so if we want to backport the other fixes (dunno if it's important), could split it out.

**Comment by charris** [comment]
>  if we want to backport the other fixes (dunno if it's important), could split it out.

I'm inclined to backport, but a bit nervous about introducing new bugs :) I am planning one more 2.1 release with just a few bug fixes and it would be nice to get the string dtypes to a more finished state.

**Comment by seberg** [comment]
The very safe thing for backport is to only keeping the removal of:
```
            needs_api = PyDataType_REFCHK(descrs[0]);
```
in the `ufunc` changes.  I suppose I can follow up with a manual backport also.

**Review by mhvk — COMMENTED** [review]
Looks good to me - code is definitely clearer. My only comment is about passing on `cast_info` directly, whether that might perhaps have been for optimization.

File: numpy/_core/src/multiarray/item_selection.c [hunk 1]
```diff
@@ -815,44 +815,44 @@ static NPY_GCC_OPT_3 int
 npy_fastrepeat(
     npy_intp n_outer, npy_intp n, npy_intp nel, npy_intp chunk,
     npy_bool broadcast, npy_intp* counts, char* new_data, char* old_data,
-    npy_intp elsize, NPY_cast_info cast_info, int needs_refcounting)
+    npy_intp elsize, NPY_cast_info *cast_info, int needs_custom_copy)
 {
-    if (!needs_refcounting) {
+    if (!needs_custom_copy) {
         if (chunk == 1) {
```
[the remark this answers is not in the document]
Comment (seberg) [reply numpy/_core/src/multiarray/item_selection.c:821]: Yes, this is about auto-inlining different versions.  `cast_info` isn't used for that fast-path decision, so I don't think it matters how it is passed on.  I think it is a simple typo/slip.

Thought about using `cast_info->func == NULL` for that, but I was worried that compiler may not be smart enough to resolve that.

File: numpy/_core/src/umath/ufunc_object.c [hunk 2]
```diff
@@ -2829,18 +2837,17 @@ PyUFunc_Accumulate(PyUFuncObject *ufunc, PyArrayObject *arr, PyArrayObject *out,
...
+                if (copy_info.func(
+                        &copy_info.context, &dataptr_copy[1], &one,
+                        &stride_copy[1], copy_info.auxdata) < 0) {
+                    NPY_END_THREADS;
+                    goto fail;
+                }
             }
             else {
-                memmove(dataptr_copy[0], dataptr_copy[1], itemsize);
+                memmove(dataptr_copy[2], dataptr_copy[1], itemsize);
```
Comment (ngoldbaum) [inline numpy/_core/src/umath/ufunc_object.c:2850]: why this change for the non-cast case?

File: numpy/_core/src/multiarray/item_selection.c [hunk 3]
```diff
@@ -785,21 +785,21 @@ static NPY_GCC_OPT_3 inline int
 npy_fastrepeat_impl(
     npy_intp n_outer, npy_intp n, npy_intp nel, npy_intp chunk,
     npy_bool broadcast, npy_intp* counts, char* new_data, char* old_data,
-    npy_intp elsize, NPY_cast_info cast_info, int needs_refcounting)
+    npy_intp elsize, NPY_cast_info *cast_info, int needs_custom_copy)
```
Comment (ngoldbaum) [inline numpy/_core/src/multiarray/item_selection.c:788]: good catch on the struct copy here that almost definitely wasn't intended

File: numpy/_core/src/multiarray/item_selection.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (ngoldbaum) [reply numpy/_core/src/multiarray/item_selection.c:821]: might be worth adding a comment that this exists purely to trick the compiler into inlining things.

**Review by ngoldbaum — COMMENTED** [review]
Awesome thanks so much for working on this! I left a question but after we clear that up let's merge this ASAP.

File: numpy/_core/src/umath/ufunc_object.c (hunk 2 above)
Comment (seberg) [reply numpy/_core/src/umath/ufunc_object.c:2850]: Just because for the other path `dataptr_copy` entries 1 and 2 are more natural (due to ordering), so I thought it is clearer to use also 1 and 2 here.

File: numpy/_core/src/umath/ufunc_object.c [hunk 4]
```diff
@@ -2889,15 +2896,14 @@ PyUFunc_Accumulate(PyUFuncObject *ufunc, PyArrayObject *arr, PyArrayObject *out,
...
+            const npy_intp one = 1;
+            const npy_intp strides[2] = {itemsize, itemsize};
+            if (copy_info.func(
+                    &copy_info.context, &dataptr_copy[1], &one,
+                    strides, copy_info.auxdata) < 0) {
+                goto fail;
+            }
         }
         else {
             memmove(dataptr_copy[0], dataptr_copy[1], itemsize);
```
Comment (ngoldbaum) [inline numpy/_core/src/umath/ufunc_object.c:2909]:
```suggestion
            memmove(dataptr_copy[2], dataptr_copy[1], itemsize);
```

Just to make it match the other branch you changed here. I was confused last Friday but then I see now that 2 and 0 are the same pointer.

**Review by ngoldbaum — APPROVED** [review]
Thanks again for working on this and fixing up loose ends for StringDType.

Just one suggestion which you can take or leave and self-merge :)

File: numpy/_core/src/umath/ufunc_object.c (hunk 4 above)
Comment (seberg) [reply numpy/_core/src/umath/ufunc_object.c]: Ah, thanks, missed that.  Better to make it uniform!

**Comment by charris** [comment]
@seberg Are you going to do a backport?
