### PR TITLE
ENH: restore unpack bit lookup table

### LINKED ISSUE #13537: document or fix unpackbits performance regression
https://github.com/numpy/numpy/pull/12962 removed the lookup table for unpack bits causing a factor 8 performance regression:

```
       before           after         ratio
     [08b17aee]       [e6227a03]
     <v1.16.3^0>       <master>  
+      5.80±0.5μs         46.4±1μs     8.00  bench_core.UnpackBits.time_unpackbits
+         120±2μs         911±20μs     7.58  bench_core.UnpackBits.time_unpackbits_axis1

```

While the function is probably not that critical for performance the change is of rather large magnitude and should probably be added to the release notes.

As for fixing to simplify the code one could just bitswap the data, well performing functions for that could be generally useful and might even be worth exposing (e.g. blosc has code for that).

### PR DESCRIPTION
**Pull request by juliantaylor**
Restores the good performance of unpackbits we had since 1.13.

Closes gh-13537

### CODE REVIEW

File: numpy/core/src/multiarray/compiled_base.c [hunk 1]
```diff
@@ -1788,6 +1791,35 @@ unpack_bits(PyObject *input, int axis, PyObject *count_obj, char order)
...
+            v_b |= (npy_uint64)((j &   8) ==   8) << 24;
+            v_b |= (npy_uint64)((j &  16) ==  16) << 32;
+            v_b |= (npy_uint64)((j &  32) ==  32) << 40;
+            v_b |= (npy_uint64)((j &  64) ==  64) << 48;
+            v_b |= (npy_uint64)((j & 128) == 128) << 56;
+
+            /* for bitorder little the lookup table is just byte swapped */
+            v_l = npy_bswap8(v_b);
+
+            /* the table is stored as big endian, swap the native integer */
```
Comment (juliantaylor) [inline numpy/core/src/multiarray/compiled_base.c]: it is probably a little odd that we store the table in big endian as the most common platform is little endian
it was like that originaly as the packbit worked in "big endian" bits, now that it can do both should we change the lookup table to be stored in little endian?

Comment (eric-wieser) [reply numpy/core/src/multiarray/compiled_base.c]: +1 from me

Comment (eric-wieser) [reply numpy/core/src/multiarray/compiled_base.c]: Wait, isn't the lookup table already little endian, with the low-order bits at the lowest byte of `v_b`?

File: numpy/core/src/multiarray/compiled_base.c [hunk 2]
```diff
@@ -1703,6 +1703,9 @@ pack_bits(PyObject *input, int axis, char order)
 static PyObject *
 unpack_bits(PyObject *input, int axis, PyObject *count_obj, char order)
 {
+    static int unpack_init = 0;
+    static npy_uint64 unpack_lookup_l[256];
+    static npy_uint64 unpack_lookup_b[256];
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/compiled_base.c]: can you remove the endianness dependence by making the definition `npy_uint8[256][8]`? Does that have any effect on performance?

File: numpy/core/src/multiarray/compiled_base.c (hunk 1 above)
Comment (juliantaylor) [reply numpy/core/src/multiarray/compiled_base.c]: little and big endian are a bit confusing in this context, what is relevant is that the byte pattern of the lookup table is the _same_ on both endianess platforms.
endianess is only relevant when interpreting the bytes as integer which is not done by this function it only extends a byte to 8 bytes and integer is simply the datatype used to construct the bytes.
I'll change the comments to say fixed endian.

File: numpy/core/src/multiarray/compiled_base.c (hunk 2 above)
Comment (juliantaylor) [reply numpy/core/src/multiarray/compiled_base.c]: yes that could be done, but lookup table construction then becomes two looks instead of one. Might be less readable.

Comment (juliantaylor) [reply numpy/core/src/multiarray/compiled_base.c]: though removing endian mentions from the code might be worth it
I'll update.

Comment (juliantaylor) [reply numpy/core/src/multiarray/compiled_base.c]: done

File: numpy/core/src/multiarray/compiled_base.c [hunk 3]
```diff
@@ -1788,6 +1791,24 @@ unpack_bits(PyObject *input, int axis, PyObject *count_obj, char order)
...
+     * expanded to 1/0 bytes
+     */
+    if (unpack_init == 0) {
+        npy_uint64 j;
+        for (j=0; j < 256; j++) {
+            npy_uint64 k;
+            for (k=0; k < 8; k++) {
+                npy_uint8 v = (j & (1 << k)) == (1 << k);
+                unpack_lookup_b[j][7 - k] = v;
+                /* for bitorder little the lookup table is byte swapped */
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/compiled_base.c]: I'd be tempted to attach this comment to bitorder big, since that's the one with the more complex expression

File: numpy/core/src/multiarray/compiled_base.c [hunk 4]
```diff
@@ -1703,6 +1703,9 @@ pack_bits(PyObject *input, int axis, char order)
 static PyObject *
 unpack_bits(PyObject *input, int axis, PyObject *count_obj, char order)
 {
+    static int unpack_init = 0;
+    static npy_uint8 unpack_lookup_l[256][8];
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/compiled_base.c]: Valuable to tell GCC to align these as 8?

File: numpy/core/src/multiarray/compiled_base.c [hunk 5]
```diff
@@ -1788,6 +1791,24 @@ unpack_bits(PyObject *input, int axis, PyObject *count_obj, char order)
...
     }
 
+    /*
+     * setup lookup table under GIL, 256 8 byte blocks representing 8 bits
+     * expanded to 1/0 bytes
+     */
+    if (unpack_init == 0) {
+        npy_uint64 j;
+        for (j=0; j < 256; j++) {
+            npy_uint64 k;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/compiled_base.c]: This can be a uint8, right? Or perhaps a intp, since it's an array index. Not that it really matters...

**Comment by eric-wieser** [comment]
Looks a lot clear to me as the array, thanks!

File: numpy/core/src/multiarray/compiled_base.c (hunk 4 above)
Comment (juliantaylor) [reply numpy/core/src/multiarray/compiled_base.c]: gcc should do that by itself, at least on 64 bit platforms
also if it does not, we are using memcpy to access this on a 8 byte boundary (so we don't need to care about output alignment) so it won't break even if it is not.

one could enforce it portably be making this a int64 variable as before and casting back to char in the init loop, should we do that?

File: numpy/core/src/multiarray/compiled_base.c [hunk 6]
```diff
@@ -1788,6 +1791,24 @@ unpack_bits(PyObject *input, int axis, PyObject *count_obj, char order)
...
+            for (k=0; k < 8; k++) {
+                npy_uint8 v = (j & (1 << k)) == (1 << k);
+                unpack_lookup_b[j][7 - k] = v;
```
Comment (hameerabbasi) [inline numpy/core/src/multiarray/compiled_base.c]: Is it possible to detect endian-ness and initialize just one table, or do we need both on a given platform?

Comment (hameerabbasi) [reply numpy/core/src/multiarray/compiled_base.c]: Also, is it possible to change the access rather than changing the table? Might be a bit more maintainable.

**Review by hameerabbasi — APPROVED** [review]
Looks good to me overall, some minor changes!

File: numpy/core/src/multiarray/compiled_base.c (hunk 6 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/compiled_base.c]: No, we need both to support the two modes of unpack bits. Platform endianness is irrelevant.

Comment (eric-wieser) [reply numpy/core/src/multiarray/compiled_base.c]: Creating two tables is done so both can be memcopy'd

File: numpy/core/src/multiarray/compiled_base.c (hunk 4 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/compiled_base.c]: I'm worried only about performance here, I agree it'll do the right thing with or without alignment.

I don't think the c standard requires GCC to align this, but perhaps it's clever enough to anyway. You could perhaps declare it an array of unions of u8[8] and u64, which would also allow you to construct one table from the other using bswap, and is a little cleaner that doing the casting you're suggesting.

File: numpy/core/src/multiarray/compiled_base.c (hunk 6 above)
Comment (juliantaylor) [reply numpy/core/src/multiarray/compiled_base.c]: one could byteswap from one table, but that is about 60% slower than a second table.
two extra kb of memory usage should not really matter for typical numpy applications though as the function is not that important and the slowdown would be in the new option only it could be considered

Comment (juliantaylor) [reply numpy/core/src/multiarray/compiled_base.c]: updated to do that, a bit slower but probably fine

Comment (hameerabbasi) [reply numpy/core/src/multiarray/compiled_base.c]: The comment about changing access still holds.

**Review by mattip — APPROVED** [review]
Thanks for un-reverting these changes and even improving on them. IMO this is about as far as we want to go with this now

File: numpy/core/src/multiarray/compiled_base.c [hunk 7]
```diff
@@ -1810,39 +1831,75 @@ unpack_bits(PyObject *input, int axis, PyObject *count_obj, char order)
         unsigned const char *inptr = PyArray_ITER_DATA(it);
         char *outptr = PyArray_ITER_DATA(ot);
 
-        if (order == 'b') {
-            for (index = 0; index < in_n; index++) {
-                for (i = 0; i < 8; i++) {
-                    *outptr = ((*inptr & (128 >> i)) != 0);
-                    outptr += out_stride;
+        if (out_stride == 1) {
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/compiled_base.c]: Aside: If you're feeling adventurous - you might be able to make a similar optimization for `out_stride == -1`

File: numpy/core/src/multiarray/compiled_base.c [hunk 8]
```diff
@@ -1810,39 +1831,75 @@ unpack_bits(PyObject *input, int axis, PyObject *count_obj, char order)
...
+                for (index = 0; index < in_n; index++) {
+                    npy_uint64 v = unpack_lookup.uint64[*inptr];
+                    memcpy(outptr, &v, 8);
+                    outptr += 8;
+                    inptr += in_stride;
+                }
+            }
+            else {
+                for (index = 0; index < in_n; index++) {
+                    npy_uint64 v = unpack_lookup.uint64[*inptr];
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/compiled_base.c]: With the `union` change above, this becomes `unpack_lookup_big[*inptr].uint64`

File: numpy/core/src/multiarray/compiled_base.c [hunk 9]
```diff
@@ -1703,6 +1703,11 @@ pack_bits(PyObject *input, int axis, char order)
 static PyObject *
 unpack_bits(PyObject *input, int axis, PyObject *count_obj, char order)
 {
+    static int unpack_init = 0;
+    static union {
+        npy_uint8  bytes[256][8];
+        npy_uint64 uint64[256];
```
[the remark this answers is not in the document]
Comment (juliantaylor) [reply numpy/core/src/multiarray/compiled_base.c]: makes sense, done

File: numpy/core/src/multiarray/compiled_base.c [hunk 10]
```diff
@@ -1703,6 +1703,11 @@ pack_bits(PyObject *input, int axis, char order)
...
+    } unpack_lookup;
```
[the remark this answers is not in the document]
Comment (juliantaylor) [reply numpy/core/src/multiarray/compiled_base.c]: done

File: numpy/core/src/multiarray/compiled_base.c (hunk 7 above)
Comment (juliantaylor) [reply numpy/core/src/multiarray/compiled_base.c]: I'm not sure that can even happen as the output is allocated by the same function and should not have negative strides
but even if its probably unnecessary to have that little extra in the code, use cases are unlikely

File: numpy/core/src/multiarray/compiled_base.c [hunk 11]
```diff
@@ -1810,39 +1835,75 @@ unpack_bits(PyObject *input, int axis, PyObject *count_obj, char order)
...
+            else if (out_pad) {
+                memset(outptr, 0, out_pad);
             }
         }
         else {
-            for (index = 0; index < in_n; index++) {
-                for (i = 0; i < 8; i++) {
+            if (order == 'b') {
+                for (index = 0; index < in_n; index++) {
+                    for (i = 0; i < 8; i++) {
```
Comment (mhvk) [inline numpy/core/src/multiarray/compiled_base.c]: Wouldn't it make sense to still use the lookup table even for stride != 1 (i.e., replace the `memcpy`, not the table reading).

Comment (juliantaylor) [reply numpy/core/src/multiarray/compiled_base.c]: probably, I never bothered testing as it is probably an edge case, though as we are updating it we might as well go all the way

Comment (mattip) [reply numpy/core/src/multiarray/compiled_base.c]: If the proposed changes will take more than a day or two, perhaps we should merge this as-is with a comment for future improvements, since the deadline for 1.17 is soon

Comment (juliantaylor) [reply numpy/core/src/multiarray/compiled_base.c]: I probably won't get to do it, imo this can be merged now

Comment (seberg) [reply numpy/core/src/multiarray/compiled_base.c]: Anything holding this up? Otherwise I will make a pass and merge soon (or probably Matti beats me to it ;)).

Comment (charris) [reply numpy/core/src/multiarray/compiled_base.c]: LGTM. The suggestion to use the table for the strided case is good, but can go in later, we need the fix for 1.17.
