### PR TITLE
BUG: allow pickling generic datetime

### LINKED ISSUE #9159: "Generic" datetime dtype fails unpickling
```
>>> pickle.loads(pickle.dumps(np.dtype('M8[us]')))
dtype('<M8[us]')
>>> pickle.loads(pickle.dumps(np.dtype('M8')))
Traceback (most recent call last):
  File "<ipython-input-39-858e4161b56d>", line 1, in <module>
    pickle.loads(pickle.dumps(np.dtype('M8')))
TypeError: Invalid datetime unit "generic" in metadata
```

### PR DESCRIPTION
**Pull request by pitrou**
Fixes #9159

### CODE REVIEW

File: numpy/core/src/multiarray/datetime.c [hunk 1]
```diff
@@ -1761,6 +1762,9 @@ parse_datetime_unit_from_string(char *str, Py_ssize_t len, char *metastr)
                 return NPY_FR_as;
         }
     }
+    else if (allow_generic && !strcmp(str, "generic")) {
```
Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: You need to check `len` here, the string is not necessarily zero terminated, so maybe something like
```
else if (allow_generic && len == 7 && !strncmp(str, "generic", 7))
```

Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: I'm curious as to where "generic" is set.

Comment (pitrou) [inline numpy/core/src/multiarray/datetime.c]: I'm surprised the string is not necessarily zero-terminated, though I'll take your word for it :-)

Comment (pitrou) [inline numpy/core/src/multiarray/datetime.c]: It's set somewhere in `dtype.__reduce__`. I haven't tried to investigate further.

Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: > I'm surprised the string is not necessarily zero-terminated, though I'll take your word for it :-)

The function may be called with substrings, which is why `len` is there.

Comment (pitrou) [inline numpy/core/src/multiarray/datetime.c]: > The function may be called with substrings, which is why len is there.

Ok, fixed.

Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: Also curious as to why "generic" is not allowed? Thinking a bit more, I think my suggestion is not correct if `len` is not 7.  What is supposed to be there for a valid generic time? But maybe
```
else if (allow_generic && !(len == 7 && strncmp(str, "generic", 7))
```

File: numpy/core/src/multiarray/datetime.c [hunk 2]
```diff
@@ -1761,6 +1762,9 @@ parse_datetime_unit_from_string(char *str, Py_ssize_t len, char *metastr)
                 return NPY_FR_as;
         }
     }
+    else if (allow_generic && len == 7 && !strncmp(str, "generic", 7)) {
```
Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: See other comments, I think this is probably still incorrect.

Comment (pitrou) [inline numpy/core/src/multiarray/datetime.c]: Not sure why? The clause is only true if the length is equal to 7 _and_ the 7 bytes compare equal to "generic".

Comment (pitrou) [inline numpy/core/src/multiarray/datetime.c]: (the tests pass, by the way)

Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: Which is to say, what is the correct value of `len` for a generic type?

Comment (pitrou) [inline numpy/core/src/multiarray/datetime.c]: Er... if we're expecting "generic", then certainly it should be 7? I'm not sure I understand your question...

Comment (pitrou) [inline numpy/core/src/multiarray/datetime.c]: And "generic" is the value registered in the `_datetime_strings` array for generic datetime units.

Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: If it is zero, the fix probably belongs elsewhere. I think as is too many things may be interpreted as generic. Could maybe be tested by trying to generate datetimes with invalid types with length > 2 and != 7.

Comment (pitrou) [inline numpy/core/src/multiarray/datetime.c]: You've lost me. Why "should" it be zero?

Comment (pitrou) [inline numpy/core/src/multiarray/datetime.c]: Perhaps it would be simpler to tell me your preference here. I do not feel qualified to make design decisions for the Numpy core team.

Comment (eric-wieser) [inline numpy/core/src/multiarray/datetime.c]: Wouldn't `strncmp(str, "generic", len)` be best here?

Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: So this works and is simpler
```
    else if (len == 7 && strncmp(str, "generic", 7) == 0) {
        return NPY_FR_GENERIC;
    }
```
Note that you can now do
```
In [4]: np.dtype('M8[generic]')
Out[4]: dtype('<M8')
```
So the question is, why did you have `allow_generic`? Note that the error messages are also incorrect for substrings as they expect null terminated strings.

Comment (pitrou) [inline numpy/core/src/multiarray/datetime.c]: It seemed there was probably a reason to disallow `m8[generic]` instead of `m8`. In any case, it didn't sound like a good idea to make parsing more lenient in a bugfix release.

Comment (pitrou) [inline numpy/core/src/multiarray/datetime.c]: > Note that the error messages are also incorrect for substrings as they expect null terminated strings.

That's not really relevant to this PR, though.

Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: Not sure why that would be a problem, generic is already defined in `_datetime_strings`, which is where I think is comes from in the pickle.

Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: Just for reference, this is what I have
```
diff --git a/numpy/core/src/multiarray/datetime.c b/numpy/core/src/multiarray/datetime.c
index 3cf9a2b..049ce33 100644
--- a/numpy/core/src/multiarray/datetime.c
+++ b/numpy/core/src/multiarray/datetime.c
@@ -1716,7 +1716,8 @@ datetime_type_promotion(PyArray_Descr *type1, PyArray_Descr *type2)
 /*
  * Converts a substring given by 'str' and 'len' into
  * a date time unit enum value. The 'metastr' parameter
- * is used for error messages, and may be NULL.
+ * is used for error messages, and may be NULL. Note that
+ * str may not be \0 terminated.
  *
  * Generic units have no representation as a string in this form.
  *
@@ -1761,12 +1762,18 @@ parse_datetime_unit_from_string(char *str, Py_ssize_t len, char *metastr)
                 return NPY_FR_as;
         }
     }
+    else if (len == 7 && strncmp(str, "generic", 7) == 0) {
+        return NPY_FR_GENERIC;
+    }
 
     /* If nothing matched, it's an error */
     if (metastr == NULL) {
+        char unit[10] = {0};
+
+        strncpy(unit, src, sizeof(unit)/sizeof(char) - 1);
         PyErr_Format(PyExc_TypeError,
-                "Invalid datetime unit \"%s\" in metadata",
-                str);
+                "Invalid datetime unit \"%s\" %d in metadata",
+                unit);
     }
     else {
         PyErr_Format(PyExc_TypeError,
```

Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: Although there are several other spots with error message errors, so that can probably be omitted here.

Comment (pitrou) [inline numpy/core/src/multiarray/datetime.c]: > Not sure why that would be a problem

I'm not sure either, but I'm not germane to the design decisions that were made, which is why I was cautious with this.
The argument of not changing accepted input in a bugfix release sounds more serious to me, what do you think?

Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: What bugfix release? The PR is against master.

Comment (pitrou) [inline numpy/core/src/multiarray/datetime.c]: It's a bugfix, so I was expecting it to be backported at some point?

Comment (seberg) [inline numpy/core/src/multiarray/datetime.c]: Since it allows something that was an error before and never worked (I guess), we normally would never consider it a bugfix I think. Unless there is some other very good reason in this specific case?

Comment (pitrou) [inline numpy/core/src/multiarray/datetime.c]: Pickling non-generic datetime dtypes works, so the fact that pickling generic datetime dtypes fails really fails like a bug rather than a deliberate decision, no? `descriptor.c` has a dedicated `_get_pickleabletype_from_datetime_metadata` function after all, it's just that it didn't work in all cases.

Comment (seberg) [inline numpy/core/src/multiarray/datetime.c]: Yes, but even bug fixes are not typically backported unless they are regressions or relatively severe, a "it never worked for 10 years and errors out" bug does not fall into that category most likely.

Comment (pitrou) [inline numpy/core/src/multiarray/datetime.c]: Fair enough.

**Comment by pitrou** [comment]
Ok, so I've now removed `allow_generic`.

**Comment by charris** [comment]
Thanks @pitrou .
