### PR TITLE
BUG: fix ``f2py`` tests to work with v2 API

### LINKED ISSUE #26917: numpy/f2py/tests/test_array_from_pyobj.py skips all tests due to use of legacy dtype API
There is a try/except in the f2py util testing code that masks compilation errors:

https://github.com/numpy/numpy/blob/abeca76c5ca956d4bfa27e01fa4988c211ba8444/numpy/f2py/tests/util.py#L329-L332

If I delete that, all the tests in `test_array_from_pyobj.py` fail with the following compilation error:

```
/Users/goldbaum/Documents/numpy/build-install/usr/lib/python3.13/site-packages/numpy/f2py/tests/src/array_from_pyobj/wrapmodule.c:118:44: error: no member named 'alignment' in 'struct _PyArray_Descr'
                       PyArray_DESCR(arr)->alignment,
                       ~~~~~~~~~~~~~~~~~~  ^
```

The try/except seems like a bad idea but I guess it's there for a reason for distutils support. Probably worth seeing if there are other tests like this.

### PR DESCRIPTION
**Pull request by paddyroddy**
Fixes #26917. I've also modernised/improved the code in the relevant test files.

CI was failing prior to a4bd4a899c9ac7530e00955e6dca4d575ded2a2d due to compiler errors in CI. Obviously not ideal reinstating this, but locally on my `macOS 14.5 arm64` all tests pass with `spin test -m full`.

### CODE REVIEW

**Comment by seberg** [comment]
Yeah, what we would need is detecting whether compilation should work first, and then compile only (rather than just trying to compile the actual module).

@charris, I guess this is maybe the last thing for a 2.0.1?

File: numpy/f2py/tests/src/array_from_pyobj/wrapmodule.c [hunk 1]
```diff
@@ -115,7 +115,7 @@ static PyObject *f2py_rout_wrap_attrs(PyObject *capi_self,
                        PyArray_DESCR(arr)->type,
                        PyArray_TYPE(arr),
                        PyArray_ITEMSIZE(arr),
-                       PyArray_DESCR(arr)->alignment,
+                       PyDataType_ALIGNMENT(arr),
```
Comment (paddyroddy) [inline numpy/f2py/tests/src/array_from_pyobj/wrapmodule.c:118]: Core change

File: numpy/f2py/tests/util.py [hunk 2]
```diff
@@ -328,7 +342,7 @@ def build_meson(source_files, module_name=None, **kwargs):
     # compiler stack is on the CI
     try:
         backend.compile()
-    except:
+    except subprocess.CalledProcessError:
```
Comment (paddyroddy) [inline numpy/f2py/tests/util.py:345]: Better than a bare `except`

**Comment by seberg** [comment]
Thanks for fixing this, @paddyroddy seems I forgot to ask for that:  But could you please undo the "non core" changes?
I wouldn't care about auto-fixing whitespaces on touched files, but sweeping auto fixing of things like list comprehensions should be a dedicated PR.

**Comment by seberg** [comment]
Seems `f2py` just isn't linted, see `tools.linter.py`.  Dunno if that could be made more precise, I suspect there is a reason it isn't, but it could be that whitespace cleanups over time have made it more manageable.

**Comment by seberg** [comment]
Thanks, merging since we should backport this for 2.0.1.  I did remove all the "non-core" changes from the PR, however.

**Comment by paddyroddy** [comment]
> Thanks, merging since we should backport this for 2.0.1. I did remove all the "non-core" changes from the PR, however.

Cool, no problem. Sorry I've been on holiday that past week.
