### PR TITLE
MAINT: add PyArray_ZeroContiguousBuffer helper and use it in PyArray_Resize

### LINKED ISSUE #26859: BUG: crash after resize on a StringDType array
### Describe the issue:

Dear numpy team,
A simple `StringDType` array resize seems to corrupt memory:
```
    import numpy as np
    from numpy.dtypes import StringDType
    a = np.array([''], dtype=StringDType())
    a.resize(2) # corrupts memory at a[1]
    print(a[1]) # crashes or raises MemoryError or whatever
```
I think this is because `PyArray_Resize` fearlessly writes a PyObject pointer into the array when a dtype has the `NPY_ITEM_REFCOUNT` flag set:
```
    PyObject *zero = PyLong_FromLong(0);
    char* optr = PyArray_BYTES(self) + oldnbytes;
    Py_INCREF(zero);
    memcpy(optr, &zero, sizeof(zero));
```
I suspect `PyArray_Resize` should do this only when the dtype is `NPY_OBJECT`,
but I leave it to the experts who know all the implications.
Thanks!

### Reproduce the code example:

```python
import numpy as np
from numpy.dtypes import StringDType
a = np.array([''], dtype=StringDType())
a.resize(2)
print(a[1])
```

### Error message:

```shell
>>> print(a[1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError: Failed to load string in StringDType getitem
```

### Python and NumPy Versions:

numpy 2.0.0
python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]

### Runtime Environment:

_No response_

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes #26859

### CODE REVIEW

File: numpy/_core/src/multiarray/shape.c [hunk 1]
```diff
@@ -141,8 +141,9 @@ PyArray_Resize(PyArrayObject *self, PyArray_Dims *newshape, int refcheck,
     }
 
     if (newnbytes > oldnbytes && PyArray_ISWRITEABLE(self)) {
-        /* Fill new memory with zeros */
-        if (PyDataType_FLAGCHK(PyArray_DESCR(self), NPY_ITEM_REFCOUNT)) {
+        /* Fill new memory with zeros (PyLong zero for object arrays) */
+        if (PyDataType_ISLEGACY(PyArray_DESCR(self)) &&
+            PyDataType_FLAGCHK(PyArray_DESCR(self), NPY_ITEM_REFCOUNT)) {
```
Comment (seberg) [inline numpy/_core/src/multiarray/shape.c:146]: Sorry, but I think we have to fix this properly one way or another.  Resize (for worse probably) effectively uses `zeros()` logic when expanding the array.

Zeros logic is implemented now with:
```
        PyArrayMethod_GetTraverseLoop *get_fill_zero_loop =
            NPY_DT_SLOTS(NPY_DTYPE(descr))->get_fill_zero_loop;
        if (get_fill_zero_loop != NULL) {
            if (get_fill_zero_loop(
                    NULL, descr, 1, descr->elsize, &(fill_zero_info.func),
                    &(fill_zero_info.auxdata), &zero_flags) < 0) {
                goto fail;
            }
        }
```
etc., see `PyArray_NewFromDescr_int`.  We have to aim for consolidating these paths or the mess this is will never go away.  In particularly that internal `_putzero` shouldn't exist!
(It must be a duplicate or probably triplicate of some fill zero function!)

**Comment by seberg** [comment]
> Does this need a release note? I don't see how anyone could have been using this.

I don't think it particularly needs a release note.  Resizing is relatively niche and this is the brand-new StringDType...

> I think just zero-filling the new entries (what happens in the else branch of this if statement)

That would mean that only object is supposed to be the odd-one out.  The problem with that choice, is that it means we have one more way to initialize the array when it comes to structured data.  So I am wondering if it isn't better to just say "its zerod" (which for almost all DTypes is just the memset anyway!).

File: numpy/_core/src/multiarray/shape.c (hunk 1 above)
Comment (ngoldbaum) [reply numpy/_core/src/multiarray/shape.c:146]: Thanks! I forgot about this API but you're right it's clearly the correct thing to use.

Comment (seberg) [reply numpy/_core/src/multiarray/shape.c:146]: One thing that may be nice would be to create a `PyArray_ZeroFillBuffer()` helper similar to the `PyArray_ClearBuffer()` one.

**Comment by ngoldbaum** [comment]
The last push adds a new `PyArray_ZeroBuffer` helper and uses it in `PyArray_Resize`.

File: numpy/_core/src/multiarray/refcount.c [hunk 2]
```diff
@@ -56,6 +56,51 @@ PyArray_ClearBuffer(
...
+ * logical error and should not happen for a data type that has
+ * been set up correctly.
+ */
+NPY_NO_EXPORT int
+PyArray_ZeroBuffer(
+        PyArray_Descr *descr, char *data,
+        npy_intp stride, npy_intp size, int aligned)
+{
+    if (!PyDataType_REFCHK(descr)) {
+        return 0;
```
Comment (seberg) [inline numpy/_core/src/multiarray/refcount.c:76]: There are two problems here IMO:
* The refcheck isn't correct quite correct.  While I would say it is best if `memset(..., 0, ...)` is the bit pattern for the zeroed buffer, I don't think we need to encode that here (nor do we in the array creation path).
* With the refcheck the functino is in theory not fuzzy, but still not great IMO.  It should guarantee zeroing, but it doesn't.
  Doing that probably means making it `PyArray_ZeroContiguousBuffer()` so that `memset()` is trivial.  I suspect that is OK, this is mainly a helper after all.
  (And to proof that point, this part is currently incorrect in the code here.)

It is unfortunate that we can't re-use such a helper in the creation code since we need to malloc/calloc there, so the logic is reversed.  I don't see a good solution for that unless we want to put two helpers next to each other here.  Maybe just a comment there, that it mirrors this function?

File: numpy/_core/src/multiarray/stringdtype/dtype.c [hunk 3]
```diff
@@ -584,6 +584,20 @@ stringdtype_get_clear_loop(void *NPY_UNUSED(traverse_context),
...
+                               int NPY_UNUSED(aligned),
+                               npy_intp NPY_UNUSED(fixed_stride),
+                               PyArrayMethod_TraverseLoop **out_loop,
+                               NpyAuxData **NPY_UNUSED(out_auxdata),
+                               NPY_ARRAYMETHOD_FLAGS *flags)
+{
+    *flags = NPY_METH_NO_FLOATINGPOINT_ERRORS;
+    *out_loop = &stringdtype_clear_loop;
+    return 0;
+}
```
Comment (seberg) [inline numpy/_core/src/multiarray/stringdtype/dtype.c:599]: You don't need this, nor is it correct.  What you need is what I mentioned above:  Gracefully keep the promise that we will use `memset` as the zeroing logic when there is no custom implementation.

**Review by seberg — CHANGES_REQUESTED** [review]

**Comment by ngoldbaum** [comment]
I got rid of the `REFCHK`, renamed the new function to `PyArray_ZeroContiguousBuffer`, and made it default to a `memset(data, 0, size)` if there isn't a custom zero-filling function. Let me know if you had something different in mind.

File: numpy/_core/src/multiarray/refcount.c [hunk 4]
```diff
@@ -56,6 +56,61 @@ PyArray_ClearBuffer(
...
+    if (get_fill_zero_loop != NULL) {
+        if (get_fill_zero_loop(
+                    NULL, descr, aligned, descr->elsize, &(zero_info.func),
+                    &(zero_info.auxdata), &flags_unused) < 0) {
+            goto fail;
+        }
+    }
+    else {
+        npy_intp nbytes;
+        if (!npy_mul_sizes_with_overflow(&nbytes, size, stride)) {
```
Comment (seberg) [inline numpy/_core/src/multiarray/refcount.c:91]: I would be happier with _not_ checking it here, TBH (not because I mind it here, but because I don't want to clutter more code with cargo-culted checks).
A valid NumPy buffer cannot overflow this so if this happens there would be a missing check earlier.  Maybe an `assert` instead if you like to clarify it?

After all, just like ufuncs/other functions the `zero_info.func` is not and should not be required to check this as well.

**Review by seberg — APPROVED** [review]
Thanks, this LGTM now.  One smaller comment and suggest to mention `np.zeros` for clarity, since that is much more concrete than "abstract zeroing".

**Comment by ngoldbaum** [comment]
Thanks for the reviews!

**Comment by egesip** [comment]
Thank you Nathan, thank you Sebastian!
