### PR TITLE
BUG, MAINT: Stop using the error-prone deprecated Py_UNICODE apis

### LINKED ISSUE #3258: BUG: np.unicode_ scalars misbehave on narrow builds
Follows on from #1123

I'm assigning a numpy.unicode_ to a slice of array of numpy.unicode_ and see the following:
```python
In [85]: l = np.array([u'blah',u'blah',u'blah'])

In [87]: type(l[0])
Out[87]: numpy.unicode_

In [88]: v = np.unicode_('bubu')

In [89]: l[0] = v

In [90]: l
Out[90]: 
array([u'bubu', u'blah', u'blah'], 
      dtype='<U4')

In [91]: l[1:3] = v

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
In [92]: l
Out[92]: 
array([u'bubu', u'\uf500\udc62\uf500\udc62\u8d00\udc00',
       u'\uf500\udc62\uf500\udc62\u8d00\udc00'], 
      dtype='<U4')
<<<<<<<<<<<< I consider this a problem

In [93]: {k: v for k, v in sysconfig.get_config_vars().items() if 'unicode' in k.lower()}
Out[93]: 
{'PY_UNICODE_TYPE': 'unsigned short',
 'Py_UNICODE_SIZE': 2,
 'Py_USING_UNICODE': 1,
 'UNICODE_OBJS': 'Objects/unicodeobject.o Objects/unicodectype.o'}

In [94]: np.**version**
Out[94]: '1.7.1'
```
```
$ uname -a
Linux ... 2.6.32-279.19.1.el6.x86_64 #1 SMP Wed Dec 19 07:05:20 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
```
On a wide unicode build I can do the same with no problem:
```python
In [81]: l = np.array([u'blah',u'blah',u'blah'])

In [82]: type(l[0])
Out[82]: numpy.unicode_

In [83]: v = np.unicode_('bubu')

In [84]: l[0] = v

In [85]: l
Out[85]: 
array([u'bubu', u'blah', u'blah'], 
      dtype='<U4')

In [86]: l[1:3] = v

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
In [87]: l
Out[87]: 
array([u'bubu', u'bubu', u'bubu'], 
      dtype='<U4')
<<<<<<<<<<<<<<<<<<<<<<<<<<<< this works fine

In [88]: {k: v for k, v in sysconfig.get_config_vars().items() if 'unicode' in k.lower()}
Out[88]: 
{'PY_UNICODE_TYPE': 0,
 'Py_UNICODE_SIZE': 4,
 'Py_USING_UNICODE': 1,
 'UNICODE_OBJS': 'Objects/unicodeobject.o Objects/unicodectype.o'}

In [89]: np.**version**
Out[89]: '1.7.1'
```
```
(my27py)pavel@pavel-ThinkPad-T520:~$ uname -a
Linux pavel-ThinkPad-T520 3.2.0-40-generic #64-Ubuntu SMP Mon Mar 25 21:22:10 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

### LINKED ISSUE #15363: Accessing elements of an array with `dtype="U"` may raise `UnicodeDecodeError`
### Reproducing code example:

```python
import sys
import numpy as np

arr = np.zeros(shape=1, dtype="U1")
for i in range(1, sys.maxunicode + 1):
    arr[0] = chr(i)
    arr[0]
```

### Error message:

```python-traceback
In [35]: arr = np.zeros(shape=1, dtype="U1")
    ...: for i in range(1, sys.maxunicode + 1):
    ...:     arr[0] = chr(i)
    ...:     arr[0]
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-35-5a43f3fdb19c> in <module>
      2 for i in range(1, sys.maxunicode + 1):
      3     arr[0] = chr(i)
----> 4     arr[0]

UnicodeDecodeError: 'utf-32-le' codec can't decode bytes in position 0-3: 
	code point in surrogate code point range(0xd800, 0xe000)
```

For some later codepoints the message is instead `code point not in range(0x110000)` (false, as the problematic codepoints are all `<= 0xdfff`).  For extra bonus fun some affected code points are `< 0xd800`, and not all surrogate characters are affected.

### Numpy/Python version information:

Numpy 1.17.4  
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]

### PR DESCRIPTION
**Pull request by eric-wieser**
These APIs work with either UCS2 or UCS4, depending on the value of `Py_UNICODE_WIDE`.
After python 3.3, there's a better way to handle this type of thing, which means we no longer have to care about this.

Fixes gh-3258
Fixes gh-15363

### CODE REVIEW

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 1]
```diff
@@ -2644,12 +2652,6 @@ STRING_nonzero (char *ip, PyArrayObject *ap)
     return nonz;
 }
 
-#ifdef Py_UNICODE_WIDE
-#define PyArray_UCS4_ISSPACE Py_UNICODE_ISSPACE
-#else
-#define PyArray_UCS4_ISSPACE(ch) Py_STRING_ISSPACE((char)ch)
-#endif
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/arraytypes.c.src]: Pretty sure this was a bug, but constructing a failing string is non-trivial

File: numpy/core/src/multiarray/buffer.c [hunk 2]
```diff
@@ -832,11 +832,6 @@ gentype_getbuffer(PyObject *self, Py_buffer *view, int flags)
     descr = PyArray_DescrFromScalar(self);
     view->buf = (void *)scalar_value(self, descr);
     elsize = descr->elsize;
-#ifndef Py_UNICODE_WIDE
-    if (descr->type_num == NPY_UNICODE) {
-        elsize >>= 1;
-    }
-#endif
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/buffer.c]: This code is unreachable for unicode anyway, it seems - but this change still makes it more correct

File: numpy/core/src/multiarray/common.c [hunk 3]
```diff
@@ -162,19 +162,16 @@ PyArray_DTypeFromObjectHelper(PyObject *obj, int maxdims,
             PyObject *temp;
 
             if (string_type == NPY_STRING) {
-                if ((temp = PyObject_Str(obj)) == NULL) {
+                if ((temp = PyObject_Bytes(obj)) == NULL) {
                     goto fail;
                 }
-                itemsize = PyUnicode_GetLength(temp);
+                itemsize = PyBytes_Size(temp);
             }
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/common.c]: This looked plain wrong, so I changed it. No idea how this code is hit

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 4]
```diff
@@ -390,6 +390,10 @@ format_@name@(@type@ val, npy_bool scientific,
  * over-ride repr and str of array-scalar strings and unicode to
  * remove NULL bytes and then call the corresponding functions
  * of string and unicode.
+ * 
+ * FIXME:
+ *   is this really a good idea?
+ *   stop using Py_UNICODE here.
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]: See #15477

**Comment by Zac-HD** [comment]
Is this the patch you mentioned for #15363?  If so the example there would be a nice regression test :smile:

**Comment by eric-wieser** [comment]
It is indeed - unfortunately, it segfaults and I don't yet know why

**Comment by eric-wieser** [comment]
It's not the cause of the segfault, but it turns out that using `PyUnicode_New(size,  0x10ffff)` is not legal unless I actually write a character greater than `0x10000` to the underlying buffer. Otherwise `str.__eq__` behaves incorrectly.

**Comment by charris** [comment]
Welcome to the swamp :)

**Comment by eric-wieser** [comment]
@mattip, any idea why this fails on PyPI? https://dev.azure.com/numpy/numpy/_build/results?buildId=8052&view=logs&j=cb7817a0-aed9-5b1b-ffdb-285e933f569f&t=713c0b5c-565d-5b6b-cd58-66e4f64bd786&l=3737

It looks as though pypi has an incorrect implementation of `PyUnicode_FromKindAndData`

File: numpy/core/tests/test_multiarray.py [hunk 5]
```diff
@@ -7854,6 +7854,37 @@ def test_null_inside_bstring_array_is_truthy(self):
...
 
 
+class TestUnicodeEncoding:
+    """
+    Tests for encoding related bugs, such as UCS2 vs UCS4, round-tripping
+    issues, etc
+    """
+    @pytest.mark.xfail(IS_PYPY, reason=
+        "PyPy overloads this, and uses `.decode('utf-32-le')` without "
+        "`errors='surrogatepass'`")
```
Comment (eric-wieser) [inline numpy/core/tests/test_multiarray.py]: https://bitbucket.org/pypy/pypy/issues/3165

**Comment by eric-wieser** [comment]
@Zac-HD: Regression test added

File: numpy/core/tests/test_multiarray.py (hunk 5 above)
Comment (mattip) [reply numpy/core/tests/test_multiarray.py]: Is CPython allowing you to create a unicode character `c` where `ord(c) >= sys.maxunicode`?

Comment (eric-wieser) [reply numpy/core/tests/test_multiarray.py]: Good point, I should include a test for that.

Comment (eric-wieser) [reply numpy/core/tests/test_multiarray.py]: With this patch:
```
>>> x = np.array(bytes([255]*4)).view('U1')
>>> x[()]
SystemError: invalid maximum character passed to PyUnicode_New
```
Before this patch:
```
>>> x = np.array(bytes([255]*4)).view('U1')
>>> x[()]
UnicodeDecodeError: 'utf-32-le' codec can't decode bytes in position 0-3: code point not in range(0x110000)
```

Comment (eric-wieser) [reply numpy/core/tests/test_multiarray.py]: We could revert back to using `PyUnicode_DecodeUTF32(..., "surrogatepass")`, but that would be a lot slower, for very little value.

Comment (seberg) [reply numpy/core/tests/test_multiarray.py]: Sounds strange enough that I would not worry (I did follow it too closely). If only the error type changes (even if SystemError is a bit annoying), I would not worry. If there are more corner case changes along strange things like surrogates, lets just mention it in the release notes.

Comment (eric-wieser) [reply numpy/core/tests/test_multiarray.py]: Yeah, it's only the error type that changes. We could catch the exception and replace it if we wanted - or perhaps just change `PyUnicode_FromKindAndData` to raise `UnicodeDecodeError` if it discovers a codepoint that is too large.

Comment (mattip) [reply numpy/core/tests/test_multiarray.py]: > This fails on PyPy

Should now be fixed since the PyPy CI run uses the latest nightly, and the bug was fixed there.

Comment (eric-wieser) [reply numpy/core/tests/test_multiarray.py]: I removed the commit that added the xfail, let's see...

Comment (eric-wieser) [reply numpy/core/tests/test_multiarray.py]: That did the trick, thanks!

**Comment by mattip** [comment]
LGTM

**Comment by eric-wieser** [comment]
I have two possible worries with this patch:

* `np.str_` scalars may get a little more memory intensive.
* Making `np.str_` support the buffer interface might allow silent conversion to `bytes` where previously none was allowed. I haven't found a case of this yet.

If reviewers can constructs possible corner cases for this second point, it would be helpful.

**Comment by eric-wieser** [comment]
> I haven't found a case of this yet.

Here's one such case, which used to error, but now assigns the UCS4 codepoints directly:
```python
>>> a = np.zeros(1, 'V8')
>>> a[:] = 'te'
>>> a
array([b'\x74\x00\x00\x00\x65\x00\x00\x00'], dtype='|V8')
```
I don't think this is any weirder than the behavior of `a[:] = 1.0`, which assigns the float bits to the void element.

**Comment by eric-wieser** [comment]
And another one:
```
>>> a = np.str_("test")
>>> b"%s" % a
 b't\x00\x00\x00e\x00\x00\x00s\x00\x00\x00t\x00\x00\x00'
```

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 6]
```diff
@@ -476,18 +472,29 @@ UNICODE_setitem(PyObject *op, void *ov, void *vap)
     else if ((temp=PyObject_Str(op)) == NULL) {
         return -1;
     }
-    ptr = PyUnicode_AS_UNICODE(temp);
-    if ((ptr == NULL) || (PyErr_Occurred())) {
+
+    /* needs to be in canonical form for PyUnicode_GET_LENGTH below */
+    if (PyUnicode_READY(temp) < 0) {
```
Comment (seberg) [inline numpy/core/src/multiarray/arraytypes.c.src]: I was curious if it is really necessary, but the cpython code is not that quickly figured out :). Nvm, lets just have it there in any case.

**Review by seberg — COMMENTED** [review]
The changes look good to me, although I did not look super closely. I think the Length discovery in the dtype discovery code was correct before. Was worried for a second about the delayed initialization, but it seems fine.
As for supporting the buffer interface... Yeah, it should mostly be strange with respect to void (and maybe including buffered) datatypes. But overall, it should be strange enough that it does not matter. I suppose we could mention it in the release notes.

File: numpy/core/src/multiarray/arraytypes.c.src (hunk 6 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/arraytypes.c.src]: I could switch to the non-macro form of `GetLength` here, this is a remnant of a broken strategy.

File: numpy/core/src/multiarray/common.c (hunk 3 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/common.c]: Do you mean S3 or U3 here?

File: numpy/core/src/multiarray/buffer.c (hunk 2 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/buffer.c]: Update: by adding the buffer interface to Unicode in the second commit, this became reachable.

File: numpy/core/src/multiarray/common.c (hunk 3 above)
Comment (seberg) [reply numpy/core/src/multiarray/common.c]: Sorry, use `b"as"` above, and it will be "S3" not U3.

Comment (eric-wieser) [reply numpy/core/src/multiarray/common.c]: Yeah, you're right - with this change the resulting array is type objects instead of bytes.

Arguably the current behavior is nonsense because coercion of arbitrary objects to bytes is a python 2 thing, python 3 should be pushing the user to pick encodings.

I'll roll back these lines.

Comment (eric-wieser) [reply numpy/core/src/multiarray/common.c]: Rolled back this change, and added some comments to make the original intent a little clearer.

File: numpy/core/src/multiarray/arraytypes.c.src (hunk 6 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/arraytypes.c.src]: Made that switch

Comment (seberg) [reply numpy/core/src/multiarray/arraytypes.c.src]: Not sure what is better, but whatever, this is good :).

File: numpy/core/src/multiarray/common.c (hunk 3 above)
Comment (seberg) [reply numpy/core/src/multiarray/common.c]: Thanks, I obviously agree that this only makes sense on Python 2, but OTOH, the switch is much less clear in the NumPy world...

**Comment by eric-wieser** [comment]
Updated with a test of `memoryview(np.str_)`

File: numpy/core/defchararray.py [hunk 7]
```diff
@@ -2679,25 +2679,6 @@ class adds the following functionality:
...
-                obj = obj.encode('utf_32')
-            else:
-                obj = str(obj)
-        else:
-            # Let the default Unicode -> string encoding (if any) take
-            # precedence.
-            obj = bytes(obj)
-
         return chararray(shape, itemsize=itemsize, unicode=unicode,
                          buffer=obj, order=order)
```
Comment (eric-wieser) [inline numpy/core/defchararray.py]: This code never made sense in the first place, as `chararray.__new__` has an identity crisis over whether it's trying to be `np.ndarray.__new__` or `np.array`, and accepts `str` objects in place of the `buffer`.

**Comment by mattip** [comment]
The test failure is the windows heisenbug. I will put this in soon if there are no objections.

File: numpy/core/include/numpy/arrayscalars.h [hunk 8]
```diff
@@ -135,7 +135,13 @@ typedef struct {
 } PyScalarObject;
 
 #define PyStringScalarObject PyStringObject
-#define PyUnicodeScalarObject PyUnicodeObject
+#define PyStringScalarObject PyStringObject
+typedef struct {
+        /* note that the PyObject_HEAD macro lives right here */
+        PyUnicodeObject base;
+        Py_UCS4 *obval;
+} PyUnicodeScalarObject;
```
Comment (hameerabbasi) [inline numpy/core/include/numpy/arrayscalars.h]: Do we need to worry about ABI changes here?

Comment (mattip) [reply numpy/core/include/numpy/arrayscalars.h]: We could check sizeof(PyUnicodeObject) == sizeof(PyUnicodeScalarObject.base) at import

Also this should hit the release note.

Comment (eric-wieser) [reply numpy/core/include/numpy/arrayscalars.h]: @mattip, your comment suggests an attempt at resilience to cpython ABI changes, which is something we don't care about because we already require recompilation against every version of python.

What hameer is point out is that anyone allocating subclassing our scalars in C (why would anyone do that), or allocating a PyUnicodeScalarObject on the stack (impossible to do without poking at CPython internals) will notice that our struct changed size.

Comment (hameerabbasi) [reply numpy/core/include/numpy/arrayscalars.h]: It was mentioned in the meeting that there's an API change here if you access the slots as well.

Comment (eric-wieser) [reply numpy/core/include/numpy/arrayscalars.h]: The slots were all private CPython implementation details, so anyone accessing them was already fending for themselves

Comment (seberg) [reply numpy/core/include/numpy/arrayscalars.h]: Ah, so API is no issue, and I fully agree that the ABI (size change) is absurd to give much heed to... We could note it in the release notes, but thinking about it more, I am not even sure that makes any sense.

Comment (hameerabbasi) [reply numpy/core/include/numpy/arrayscalars.h]: If they’re private, I’m okay with putting this in.

**Comment by seberg** [comment]
Thanks for the threat Matti, and thanks Eric. Had another glance over and it looks good to me, so putting it in. The test takes around half a second on my computer. A bit slow, but probably fine (and easily changed later).
