### PR TITLE
BUG: Unpickled void scalars should be contiguous

### LINKED ISSUE #7140: Void scalars lose their contiguity when pickled and unpickled
Running the following:

```python
import numpy as np
from pickle import loads, dumps

dt = np.dtype([('a', np.int32), ('b', np.float32)])
record = np.zeros(1, dt)[0]
print(record.flags)
print(loads(dumps(record)).flags)
```

Gives the output:

```
$ python contigdemo.py 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```

The unpickled record has lost its C- and F-contiguity - I would have expected this to be retained.

### PR DESCRIPTION
**Pull request by gmarkall**
Void scalars are both C- and Fortran-contiguous, so pickling and
unpickling them should result in a new void scalar that also has
these flags set. Fixes #7140.

### CODE REVIEW

File: numpy/core/src/multiarray/scalarapi.c [hunk 1]
```diff
@@ -799,7 +799,7 @@ PyArray_Scalar(void *data, PyArray_Descr *descr, PyObject *base)
             Py_INCREF(descr);
             vobj->obval = NULL;
             Py_SIZE(vobj) = itemsize;
-            vobj->flags = NPY_ARRAY_BEHAVED | NPY_ARRAY_OWNDATA;
+            vobj->flags = NPY_ARRAY_CARRAY | NPY_ARRAY_F_CONTIGUOUS | NPY_ARRAY_OWNDATA;
```
Comment (juliantaylor) [inline numpy/core/src/multiarray/scalarapi.c]: what is the reason you removed `NPY_ARRAY_BEHAVED`? (aligned and writeable)

Comment (gmarkall) [inline numpy/core/src/multiarray/scalarapi.c]: `NPY_ARRAY_CARRAY` is C-contiguous and behaved: https://github.com/numpy/numpy/blob/master/numpy/core/include/numpy/ndarraytypes.h#L861

Comment (seberg) [inline numpy/core/src/multiarray/scalarapi.c]: OK, can you please make sure there is a test for this as well though, or add one if there is not?

Comment (gmarkall) [inline numpy/core/src/multiarray/scalarapi.c]: I can - I will look at this now.

Comment (gmarkall) [inline numpy/core/src/multiarray/scalarapi.c]: Removing the aligned and writeable flags didn't cause any test failures, so I've added checks for both of them to the `test_pickle_3` test as well.

**Comment by juliantaylor** [comment]
thanks!

File: numpy/core/src/multiarray/scalarapi.c (hunk 1 above)
Comment (charris) [inline numpy/core/src/multiarray/scalarapi.c]: Some alignment features only matter on Sun hardware. I don't know if that affects this or not.

Comment (gmarkall) [inline numpy/core/src/multiarray/scalarapi.c]: I don't have access to any Sun hardware (I presume SPARC machines?) but I think I've avoided changing the aligned flag here - is there anything else I can look into related to this?

Comment (juliantaylor) [inline numpy/core/src/multiarray/scalarapi.c]: that should't be necessary, alignment should be handled correctly and if well deal with it when it causes a problem
most platforms don't care about alignment anyway, at worst you have software handling and some slowdown which is irrelevant for scalars.
