### PR TITLE
ENH: ufuncs can take a tuple of arrays as 'out' kwarg

### LINKED ISSUE #4752: BUG cannot specify second output to ufunc as keyword argument
Currently, it does not seem possible to pass on an array to catch the second output of a `ufunc` via a keyword parameter:
```
a1 = np.array([1.])
a2 = np.array([1.])
np.modf(1.333, out=a1, out2=a2)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-9ca83f6d80bd> in <module>()
----> 1 np.modf(1.333, out=a1, out2=a2)

ValueError: cannot specify 'out' as both a positional and keyword argument
```

One can do `np.modf(1.333, out=a1)`, which works as expected. If one gives instead `np.modf(1.333, out2=a2)`, the first part is assigned to `a2`.  (Note that the documentation suggests to use `out1, out2`, but any characters after `out` simply seem to be skipped.)

It would seem good to have the option of giving these as keyword arguments.  One solution might be to have it be consistent with the usage in `__numpy_ufunc__`, i.e., one would give `np.modf(values, out=(a1, a2))`.

### PR DESCRIPTION
**Pull request by jaimefrio**
Closes #4752

### CODE REVIEW

**Comment by jaimefrio** [comment]
As discussed in #4752 this is currently failing the tests, because these expect ufuncs with multiple returns to accept a single array in the `out` kwarg to be used for the first of the returns.

**Old behavior**
* Inputs are the `nin` first positional arguments
* Outputs are the next `nout` positional arguments.
* If less than `nout` are provided, they default to `None` (i.e. allocated by iterator)
* If no output array has been provided positionally, then the first output array can be provided with the `out` keyword argument.

**New behavior**
* Positional inputs are unchanged
* If no output array has been provided positionally, then:
  * the `out` keyword argument can be a tuple of exactly `nout` items, which must all either be arrays or `None`.
  * if `nout == 1`, then a single array or `None` can also be passed as the `out` keyword argument.

**Changes to maintain backwards compatibility**
* Allow a single array or None to be passed as the `out` keyword argument (if no positional output arrays have been provided), even if `nout > 1`, and use it for the first array.

**Comment by jaimefrio** [comment]
OK, this seems to be working now. I still need to document the new behavior, and since I also had to make changes to the array wrapping might be a good idea to add some tests for that. But I'd appreciate a first review.

File: numpy/core/src/umath/ufunc_object.c [hunk 1]
```diff
@@ -960,35 +976,69 @@ static int get_ufunc_arguments(PyUFuncObject *ufunc,
...
+                            for(i = 0; i < nout; ++i) {
+                                PyObject *val = PyTuple_GET_ITEM(value, i);
+                                if (_check_out_array(val, out_op+nin+i) < 0) {
+                                    goto fail;
+                                }
+                            }
+                        }
+                        else if (nout == 1) {
+                            /* Can be an array if it only has one output */
+                            if (_check_out_array(value, out_op+nin) < 0) {
```
Comment (mhvk) [inline numpy/core/src/umath/ufunc_object.c]: Overall, to the extent I can judge, this looks good and clearer than the code that was present. A perhaps nitpick is that I think assignments inside if functions make the code less clear than it could be otherwise. I would suggest replacing this stanza (and similar ones) with something like the following:
```
array_ok = _set_out_array(value, out_op+nin)
if (array_ok < 0) {
    ...
```
Here, I also changed the name to ensure it is clear what the function does; it could also be `_check_and_set_out_array` or `_set_out_array_if_not_None` or so).

File: numpy/core/src/umath/ufunc_object.c [hunk 2]
```diff
@@ -4043,45 +4125,41 @@ _find_array_wrap(PyObject *args, PyObject *kwds,
...
-        obj = NULL;
-        if (j < nargs) {
-            obj = PyTuple_GET_ITEM(args, j);
-            /* Output argument one may also be in a keyword argument */
-            if (i == 0 && obj == Py_None && kwds != NULL) {
-                obj = PyDict_GetItem(kwds, npy_um_str_out);
-            }
+
+    if (nin == nargs && kwds != NULL &&
+                        (obj = PyDict_GetItem(kwds, npy_um_str_out))) {
```
Comment (mhvk) [inline numpy/core/src/umath/ufunc_object.c]: Here also I would suggest taking the assignment out of the `if` statement and then simply doing another `if`.

File: numpy/core/src/umath/ufunc_object.c (hunk 1 above)
Comment (jaimefrio) [inline numpy/core/src/umath/ufunc_object.c]: Good suggestion on the name of the function, will change. But single function calls inside an if statement, when the return isn't needed elsewhere, are everywhere in the numpy code base, and in general in all Python C extensions, starting with the `if (!PyArg_ParseTupleAndKeywords...) {return NULL;}` in [the python.org tutorial on C extensions](https://docs.python.org/2/extending/extending.html#keyword-parameters-for-extension-functions).

I really think that adding a variable is unnecessary bulk in this case, so am going to stand my ground on that one, unless there is an overwhelming opinion against.

File: numpy/core/src/umath/ufunc_object.c (hunk 2 above)
Comment (jaimefrio) [inline numpy/core/src/umath/ufunc_object.c]: This makes more sense, I don't like it much either, although it makes the branching structure very compact. Will rethink it, see if I can come up with something better.

File: numpy/core/src/umath/ufunc_object.c (hunk 1 above)
Comment (mhvk) [inline numpy/core/src/umath/ufunc_object.c]: Not being used very much to `C` I'm happy to follow convention -- though this particular piece of code did not seem to follow it originally.  Anyway, I think that with the name change it will be much more obvious that the main action is something being *set*, not just *checked*.

**Comment by jaimefrio** [comment]
I have incorporated some of Marten's suggestions, and added some more tests to validate the wrapping behavior. Documenting the new behavior is the only thing left, but the code itself should be almost ready to go.

**Comment by jaimefrio** [comment]
I have made some changes, to properly report the error when the tuple does not have as many items as output arguments. I have also added some testing for the proper errors being raised. I think now only the documentation part is left.

**Comment by jaimefrio** [comment]
Ok, have added the documentation changes too. I think it is ready to go.

File: doc/source/reference/ufuncs.rst [hunk 3]
```diff
@@ -299,7 +299,20 @@ advanced usage and will not typically be used.
...
     .. versionadded:: 1.6
 
-    The first output can provided as either a positional or a keyword parameter.
+    The first output can be provided as either a positional or a keyword
+    parameter. Keyword 'out' arguments are incompatible with positional
+    ones.
+
+    ..versionadded:: 1.10
+
+    The 'out' keyword argument is now expected to be a tuple with one entry
```
Comment (mhvk) [inline doc/source/reference/ufuncs.rst]: I'd delete "now" here. Documentation should aim at those without previous knowledge; the `versionadded` will be enough for those who did know.

File: numpy/core/tests/test_umath.py [hunk 4]
```diff
@@ -36,35 +36,137 @@ def test_e(self):
...
+
+    def test_out_wrap_subok(self):
+        class ArrayWrap(np.ndarray):
+            __array_priority__ = 10
+            def __new__(cls, arr):
+                return np.asarray(arr).view(cls).copy()
+            def __array_wrap__(self, arr, context):
+                return arr.view(type(self))
+
+        for b in (True, False):
```
Comment (mhvk) [inline numpy/core/tests/test_umath.py]: How about renaming `b` to `subok`?

**Comment by mhvk** [comment]
Looks good! Only two very minor comments.

**Comment by jaimefrio** [comment]
Minor but sensible, should be corrected in the latest push.

File: numpy/core/src/umath/ufunc_object.c [hunk 5]
```diff
@@ -878,23 +910,7 @@ static int get_ufunc_arguments(PyUFuncObject *ufunc,
...
-                return -1;
-            }
-            Py_INCREF(obj);
-            out_op[i] = (PyArrayObject *)obj;
-        }
-        else {
-            PyErr_SetString(PyExc_TypeError,
-                            "return arrays must be "
-                            "of ArrayType");
+        if (_set_out_array(obj, out_op+i) < 0) {
```
Comment (charris) [inline numpy/core/src/umath/ufunc_object.c]: Space around `+`.

File: numpy/core/src/umath/ufunc_object.c [hunk 6]
```diff
@@ -960,35 +976,73 @@ static int get_ufunc_arguments(PyUFuncObject *ufunc,
...
                     }
                     break;
                 case 'o':
-                    /* First output may be specified as a keyword parameter */
-                    if (strncmp(str,"out",3) == 0) {
-                        if (out_op[nin] != NULL) {
+                    /*
+                     * Output arrays may be specified as a keyword argument,
+                     * either as a single array (or None) for single output
+                     * ufuncs, or as a tuple of arrays (or Nones).
```
Comment (charris) [inline numpy/core/src/umath/ufunc_object.c]: I'd leave of the parenthesis around `or None`, and maybe `and Nones` instead.

File: numpy/core/src/umath/ufunc_object.c [hunk 7]
```diff
@@ -960,35 +976,73 @@ static int get_ufunc_arguments(PyUFuncObject *ufunc,
...
-                            PyArrayObject *value_arr = (PyArrayObject *)value;
-                            if (PyArray_FailUnlessWriteable(value_arr, name) < 0) {
+                        if (PyTuple_Check(value)) {
+                            if (PyTuple_GET_SIZE(value) != nout) {
+                                PyErr_SetString(PyExc_ValueError,
+                                        "The 'out' tuple must have exactly "
+                                        "one entry per ufunc output");
+                                goto fail;
+                            }
+                            /* 'out' must be a tuple of arrays */
```
Comment (charris) [inline numpy/core/src/umath/ufunc_object.c]: and Nones.

File: numpy/core/src/umath/ufunc_object.c [hunk 8]
```diff
@@ -960,35 +976,73 @@ static int get_ufunc_arguments(PyUFuncObject *ufunc,
...
+                            for(i = 0; i < nout; ++i) {
+                                PyObject *val = PyTuple_GET_ITEM(value, i);
+                                if (_set_out_array(val, out_op+nin+i) < 0) {
+                                    goto fail;
+                                }
+                            }
+                        }
+                        else if (nout == 1) {
+                            /* Can be an array if it only has one output */
+                            if (_set_out_array(value, out_op+nin) < 0) {
```
Comment (charris) [inline numpy/core/src/umath/ufunc_object.c]: Spaces around `+`.

File: numpy/core/src/umath/ufunc_object.c [hunk 9]
```diff
@@ -960,35 +976,73 @@ static int get_ufunc_arguments(PyUFuncObject *ufunc,
...
-                            PyErr_SetString(PyExc_TypeError,
-                                            "return arrays must be "
-                                            "of ArrayType");
-                            goto fail;
+                            /*
+                             * If the deprecated behavior is ever removed,
+                             * keep only the else branch of this if-else
+                             */
+                            if (PyArray_Check(value) || value == Py_None) {
+                                if (DEPRECATE("passing a single array to the "
```
Comment (charris) [inline numpy/core/src/umath/ufunc_object.c]: Might want to scatter a `\n` or two in the message.

**Comment by charris** [comment]
Few style nitpicks, otherwise LGTM. Does this affect #5566?

**Comment by jaimefrio** [comment]
Fixed.

About #5566, I don't think it affects it, since the code seems to already be considering the possibility of `out` being a tuple of arrays. Can you confirm, @cowlicks?

**Comment by charris** [comment]
Thanks Jaime. Noticed a few more places needing spaces, but I think we should make a script to find those and do a general cleanup at some point.

**Comment by juliantaylor** [comment]
thanks this is great, I think using tuple makes much more sense, makes me wonder why was this not originally done like this.

though now: ufunc(x, out=x, out2=y)` only raises an warning while previously it raised a value error:

```python
x = np.arange(9)
o1 = np.empty(9)
o2 = np.empty(9, dtype=np.int32)
np.frexp(x, out=o1, out2=o2)

ValueError: cannot specify 'out' as both a positional and keyword argument
```

**Comment by jaimefrio** [comment]
Should we be more strict in the checking of `'out'` being just `'out'`?

**Comment by njsmith** [comment]
> Should we be more strict in the checking of 'out' being just 'out'?

+10

**Comment by jaimefrio** [comment]
I'm not sure why the code uses `strncmp` and not directly `strcmp`, which is all it would take to do proper checking. Am I missing something?

**Comment by njsmith** [comment]
I guess it's either an ancient thinko, or else maybe someone was planning
to actually support out1=, out2=, like the docstrings say, but then got
distracted halfway through. Either way it doesn't much matter at this
point...

**Comment by mhvk** [comment]
:+1: to checking `out` properly; it definitely confused me the first time I encountered it.

**Comment by jaimefrio** [comment]
Take a look at #5659 .
