### PR TITLE
BUG: don't silence warnings in ufunc.reduce

### LINKED ISSUE #8954: ufunc.reduce hides warnings
Arguments that would cause `ufunc.__call__` to throw a warning seem to not do so when passed to `ufunc.reduce`:

Bug or feature?
```python
In [24]: np.minimum(*[1, np.nan])
RuntimeWarning: invalid value encountered in minimum
Out[24]: nan

In [25]: np.minimum.reduce([1, np.nan])
Out[25]: nan

# not just minimum
In [28]: np.divide(*[1, 0])
RuntimeWarning: divide by zero encountered in true_divide
Out[28]: inf

In [29]: np.divide.reduce([1, 0])
Out[29]: inf
```

### PR DESCRIPTION
**Pull request by eric-wieser**
Needed a file of helper functions so that this was actually visible in `reduction.c`. This move is in the first commit.

Fix itself is trivial once things are visible.

Fixes #8954

### CODE REVIEW

File: numpy/core/src/umath/extobj.c [hunk 1]
```diff
@@ -0,0 +1,310 @@
+#define PY_SSIZE_T_CLEAN
+#include <Python.h>
+
+#include "npy_pycompat.h"
+
+#include "extobj.h"
+#define NPY_NO_DEPRECATED_API NPY_API_VERSION
+#include <numpy/ufuncobject.h>
+#include "ufunc_object.h"  /* for npy_um_str_pyvals_name */
```
Comment (eric-wieser) [inline numpy/core/src/umath/extobj.c]: Is there a right order for this includes?

**Comment by eric-wieser** [comment]
Tests fail right now because we're now being warned about more things. Most of these are correct (ie, testing nan behavior), and need test updates.

I don't think these should warn at all when invoked with `(1, np.nan)` or `.reduce([1, np.nan])`, since they are designed to explicitly handle `nan`s:

* np.minimum
* np.maximum
* np.fmin
* np.fmax

However, I don't know how to disable the warnings there.

Also, one test fails due to an overflow that was silenced! Which raises a good point - overflow in `np.sum` is something we really should have been catching

**Comment by eric-wieser** [comment]
Ok, all fixed I think. Probably easiest to review this commit-by-commit, since the first refactor is noisy

**Comment by juliantaylor** [comment]
maximum/minimum should warn, nan's may lead to unexpected results. We also have the nanmax/nanmin functions for these.

**Comment by eric-wieser** [comment]
What's the history behind having both `fmax` and `nanmax`?

**Comment by eric-wieser** [comment]
@juliantaylor: Ok, warnings are now only squashed in fmin and fmax

**Comment by charris** [comment]
Needs rebase.

**Comment by charris** [comment]
> What's the history behind having both fmax and nanmax?

`fmax` is a binary ufunc implementing the standard C fmax function. The nanmax function uses it via the reduce method when it can, but see the note in the implementation. It might can be changed now that `__array_ufunc__` is in.

```
Upon successful completion, these functions shall return the maximum numeric value of their arguments.

If just one argument is a NaN, the other argument shall be returned.
```

**Comment by eric-wieser** [comment]
@charris: Rebased

File: numpy/core/src/umath/extobj.c [hunk 2]
```diff
@@ -0,0 +1,317 @@
...
+    if (extobj == NULL) {
+        extobj = get_global_ext_obj();
+    }
+    if (_extract_pyvals(extobj, ufunc_name,
+                        buffersize, errormask, NULL) < 0) {
+        return -1;
+    }
+
+    return 0;
+}
```
Comment (mhvk) [inline numpy/core/src/umath/extobj.c]: Missing end of line.

File: numpy/core/src/umath/extobj.h [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+/********************/
+#define USE_USE_DEFAULTS 1
+/********************/
+
+#if USE_USE_DEFAULTS==1
+NPY_NO_EXPORT int
+ufunc_update_use_defaults(void);
+#endif
+
+#endif
```
Comment (mhvk) [inline numpy/core/src/umath/extobj.h]: Missing end of line.

File: numpy/core/src/umath/reduction.c [hunk 4]
```diff
@@ -436,6 +437,7 @@ PyArray_InitializeReduceResult(
  * loop        : The loop which does the reduction.
  * data        : Data which is passed to assign_identity and the inner loop.
  * buffersize  : Buffer size for the iterator. For the default, pass in 0.
+ * errormask   : forwarded from _get_bufsize_errmask
```
Comment (mhvk) [inline numpy/core/src/umath/reduction.c]: Since it comes after `funcname` in the signature, move it below it here as well.

File: numpy/core/src/umath/reduction.h [hunk 5]
```diff
@@ -149,6 +149,7 @@ PyUFunc_ReduceWrapper(PyArrayObject *operand, PyArrayObject *out,
                       int subok,
                       PyArray_AssignReduceIdentityFunc *assign_identity,
                       PyArray_ReduceLoopFunc *loop,
-                      void *data, npy_intp buffersize, const char *funcname);
+                      void *data, npy_intp buffersize, const char *funcname,
+                      int errormask);
```
Comment (mhvk) [inline numpy/core/src/umath/reduction.h]: Add `errormask` to the description above as well.

**Review by mhvk — COMMENTED** [review]
Mostly nitpicks, but also warnings in the compilation:
```
    numpy/core/src/umath/ufunc_object.c:3619:15: warning: unused variable 'out_obj' [-Wunused-variable]

    numpy/core/src/umath/reduction.c:562:5: warning: implicit declaration of function 'PyUFunc_clearfperr' [-Wimplicit-function-declaration]
```
I think the first is likely a result of the rebase; the definition can be removed from l.3619, as it is moved to 3655.

The second I'm not sure about; a missing include perhaps?

**Comment by eric-wieser** [comment]
Don't understand how this patch could have introduced the warning about `out_obj`, since the diff doesn't even contain that word, but all your nitpicks are fair

**Comment by eric-wieser** [comment]
Nitpicks addressed, but still not sure about that missing function prototype. Works fine on MSVC though...

**Comment by mhvk** [comment]
This now looks all OK. The one remaining question is whether this is worth backporting. Including the MAINT commits, it is a bit of a large code shuffle, but it does fix a bug. @charris?

**Comment by charris** [comment]
@mhvk That's a lot of code. If the bug is long standing I would leave it for 1.14. I'm OK with backporting fixes to `__array_ufunc__`,  but this doesn't look to qualify for that.

I'm going to release the 1.13.0 final at the beginning of next week.

**Comment by eric-wieser** [comment]
> That's a lot of code. 

Not really - almost all of it is just moving code from one file to another. I agree though, this isn't terribly deserving of a backport

File: numpy/core/src/umath/extobj.c [hunk 6]
```diff
@@ -0,0 +1,317 @@
...
+#define NO_IMPORT_ARRAY
+
+#include "npy_pycompat.h"
+
+#include "extobj.h"
+#include "numpy/ufuncobject.h"
+
+#include "ufunc_object.h"  /* for npy_um_str_pyvals_name */
+
+#if USE_USE_DEFAULTS==1
```
Comment (charris) [inline numpy/core/src/umath/extobj.c]: Spaces around operators.

File: numpy/core/src/umath/extobj.c [hunk 7]
```diff
@@ -0,0 +1,317 @@
...
+ */
+NPY_NO_EXPORT int
+ufunc_update_use_defaults(void)
+{
+    PyObject *errobj = NULL;
+    int errmask, bufsize;
+    int res;
+
+    PyUFunc_NUM_NODEFAULTS += 1;
+    res = PyUFunc_GetPyValues("test", &bufsize, &errmask, &errobj);
```
Comment (charris) [inline numpy/core/src/umath/extobj.c]: "test"?

File: numpy/core/src/umath/extobj.c [hunk 8]
```diff
@@ -0,0 +1,317 @@
...
+    /* don't need C API for a simple print */
+    if (method == UFUNC_ERR_PRINT) {
+        if (*first) {
+            fprintf(stderr, "Warning: %s encountered in %s\n", errtype, name);
+            *first = 0;
+        }
+        return 0;
+    }
+
+    NPY_ALLOW_C_API;
```
Comment (charris) [inline numpy/core/src/umath/extobj.c]: Does this buy anything? A small speedup in errorhandling, which should be rare, doesn't seem worth it.

Comment (charris) [inline numpy/core/src/umath/extobj.c]: NVM

File: numpy/core/src/umath/extobj.c (hunk 7 above)
Comment (eric-wieser) [inline numpy/core/src/umath/extobj.c]: Beats me - again, just a maintenance change, moving this from the other file

**Comment by eric-wieser** [comment]
Quoting the first commit:

> Apart from the includes, everything here is just a direct move - there are no code changes

I'd rather not open the can of poorly-documented worms that is how `extobj` actually works

File: numpy/core/src/umath/extobj.c (hunk 6 above)
Comment (eric-wieser) [inline numpy/core/src/umath/extobj.c]: Again, this is verbatim from the other file.

**Comment by eric-wieser** [comment]
@charris: Any other remarks here?

**Comment by charris** [comment]
Nope, might as well put it in. Thanks Eric.

**Comment by rgommers** [comment]
Please do not backport this - no need, and it will show warnings in the scipy test suite (and other packages probably) for released versions of scipy for which the test suite should be clean.
