### PR TITLE
BUG: Fix `np.einsum` errors on Power9 Linux and z/Linux

### LINKED ISSUE #14692: BUG: Fix np.einsum errors on Power9 Linux and z/Linux.
An array index fails on Power9 Linux and z/Linux.

PR follows this issue, but not sure that x86 will be happy with the proposed fix

### Reproducing code example:

```
(qdev_venv) [linux1@jwoehr1 Qiskit]$ python
Python 3.6.8 (default, Jun 11 2019, 14:52:20) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> tensor = np.random.rand(10, 10, 10, 10)
>>> np.einsum('ijij->', tensor)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in einsum
  File "/home/linux1/work/Qiskit/qdev_venv/lib64/python3.6/site-packages/numpy/core/einsumfunc.py", line 1356, in einsum
    return c_einsum(*operands, **kwargs)
ValueError: dimensions in operand 0 for collapsing index 'þ' don't match (-1419377904 != 10)
>>> 
```

### Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in einsum
  File "/home/linux1/work/Qiskit/qdev_venv/lib64/python3.6/site-packages/numpy/core/einsumfunc.py", line 1356, in einsum
    return c_einsum(*operands, **kwargs)
ValueError: dimensions in operand 0 for collapsing index 'þ' don't match (-1419377904 != 10)
```
### Numpy/Python version information:

1.17.2 3.6.8 (default, Jun 11 2019, 14:52:20) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

### PR DESCRIPTION
**Pull request by jwoehr**
BUG: fixes #14692 on Power 9 and z/Linux

### CODE REVIEW

**Comment by seberg** [comment]
So clang-tidy warns about: `out_labels[ndim++] = label;` (line 1946)  and `i = out_label - output_labels;` (line 2055) and ` axes[i] = match - labels;` (line 2232) (narrowing casts) sorry for the missing code lines. I have no idea if those are actually particularly problematic, but thought I would mention.

**Comment by jwoehr** [comment]
> So clang-tidy warns about: `out_labels[ndim++] = label;` (line 1946) and `i = out_label - output_labels;` (line 2055) and ` axes[i] = match - labels;` (line 2232) (narrowing casts). I have no idea if those are actually particularly problematic, but thought I would mention.

I will explore this tomorrow. Thank you for all your help!

**Comment by mattip** [comment]
Every fix should have a test case. I am not sure we need 4d4cc4d, can you add a test that fails before and passes after to prove it is required? The fix in 68861de is definitely needed for np.einsum('abab', x).

File: numpy/core/src/multiarray/einsum.c.src [hunk 1]
```diff
@@ -2021,7 +2021,7 @@ get_single_op_view(PyArrayObject *op, char *labels,
          * The char type may be either signed or unsigned, we
          * need it to be signed here.
          */
-        label = (signed char)labels[idim];
+        label = labels[idim];
```
Comment (mattip) [inline numpy/core/src/multiarray/einsum.c.src]: Why this change?

File: numpy/core/src/multiarray/einsum.c.src [hunk 2]
```diff
@@ -2135,7 +2135,7 @@ get_combined_dims_view(PyArrayObject *op, int iop, char *labels)
          * The char type may be either signed or unsigned, we
          * need it to be signed here.
          */
-        int label = (signed char)labels[idim];
+        int label = labels[idim];
```
Comment (mattip) [inline numpy/core/src/multiarray/einsum.c.src]: Why this change?

Comment (jwoehr) [reply numpy/core/src/multiarray/einsum.c.src]: @mattip we did that because it made it work on s390x and power9.
Of course it broke x86_64!
I thought I had reverted to a clean copy of master and made your change.
Now I think I made a MisTeAk :)
I will look at what I did and push again.

**Comment by mattip** [comment]
The test should be added to `numpy/core/tests/test_einsum.py`, maybe next to `test_einsum_fixed_collapsingbug`. Note that `random.rand(10, 10, 10, 10)` should be spelled `random.random_sample((10, 10, 10, 10))`. The test should mention the issues gh-14692 and gh-12689.

**Comment by jwoehr** [comment]
> The test should be added to `numpy/core/tests/test_einsum.py`, maybe next to `test_einsum_fixed_collapsingbug`. Note that `random.rand(10, 10, 10, 10)` should be spelled `random.random_sample((10, 10, 10, 10))`. The test should mention the issues [gh-14692](https://github.com/numpy/numpy/issues/14692) and [gh-12689](https://github.com/numpy/numpy/issues/12689).

If it passes testing, I'll add that, thanks, @mattip

**Comment by jwoehr** [comment]
> Note that `random.rand(10, 10, 10, 10)` should be spelled `random.random_sample((10, 10, 10, 10))`.

Hmm, this does not work:
```
tensor = np.random.random_sample(10, 10, 10, 10)
  File "mtrand.pyx", line 370, in numpy.random.mtrand.RandomState.random_sample
TypeError: random_sample() takes at most 1 positional argument (4 given)
```

**Comment by mattip** [comment]
Are you sure you used my code? It looks different to me.

**Comment by mattip** [comment]
The [documented developer workflow](https://numpy.org/devdocs/dev/index.html#test-coverage) is to add tests as part of the development process. I find it helpful to:
- reproduce a failure locally from the CLI with `python runtests.py --python` which will compile and use a HEAD version of numpy
- add a test that fails when run locally with `python runtests.py -t path/to/changed-file`
- add a fix and verify that the test suite runs locally with `python runtests.py`
- push the test and the fix together.

This makes sure your fix is correct and prevents unneeded CI runs. In this case, I needed to dive in with gdb to find out exactly what was going wrong so a test was critical to find the missing cast.

**Comment by jwoehr** [comment]
> Are you sure you used my code? It looks different to me.

aha :) Lots of parentheses

**Comment by jwoehr** [comment]
w/r/t the test case, does it have to test some kind of result, or is it enough that the failure is that an exception is thrown?

File: numpy/core/tests/test_einsum.py [hunk 3]
```diff
@@ -700,6 +700,12 @@ def test_einsum_fixed_collapsingbug(self):
         y2 = x[idx[:, None], idx[:, None], idx, idx]
         assert_equal(y1, y2)
 
+    def test_einsum_failed_on_p9_and_s390x(self):
+        # Issues gh-14692 and gh-12689
+        # Bug with signed vs unsigned char errored on power9 and s390x Linux
+        tensor = np.random.random_sample((10, 10, 10, 10))
+        print(np.einsum('ijij->', tensor))
+
```
Comment (mattip) [inline numpy/core/tests/test_einsum.py]: Maybe (please check locally before pushing)
```
x = np.einsum('ijij->', tensor)
y = tensor.trace(axis1=0, axis2=2).trace()
assert_equal(x, y)
```

Comment (WarrenWeckesser) [reply numpy/core/tests/test_einsum.py]: With floating point, you can't be sure that `x` and `y` will be *exactly* equal.  Use `assert_allclose` with an appropriately small tolerance, or use an integer array for `tensor` (assuming the test doesn't actually depend on the data type of the array).

Comment (jwoehr) [reply numpy/core/tests/test_einsum.py]: Done; tested on x86_64, power9, and s390x; and pushed.

**Comment by mattip** [comment]
Thanks @jwoehr
