### PR TITLE
BUG,ENH: Fix generic scalar infinite recursion issues 

### LINKED ISSUE #26767: BUG: Segmentation fault when doing a "Bitwise OR" on a `np.longdouble` with a `None` value
### Describe the issue:

I was working on Pynguin, an automated unit test generation tool for Python, and the tool found that Numpy creates a segmentation fault when doing a "Bitwise OR" on a `np.longdouble` with a `None` value.

### Reproduce the code example:

```python
import numpy

numpy.longdouble() | None
```

### Error message:

```shell
Segmentation fault (core dumped)
```

### Python and NumPy Versions:

2.0.0
3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0]

### Runtime Environment:

[{'numpy_version': '2.0.0',
  'python': '3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0]',
  'uname': uname_result(system='Linux', node='lucas-hp', release='6.8.11-200.fc39.x86_64', version='#1 SMP PREEMPT_DYNAMIC Sun May 26 20:05:41 UTC 2024', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Zen',
  'filepath': '/home/lucas/.conda/envs/pynguin-for-ML-libraries/lib/python3.10/site-packages/numpy.libs/libscipy_openblas64_-99b71e71.so',
  'internal_api': 'openblas',
  'num_threads': 12,
  'prefix': 'libscipy_openblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.27'}]

### Context for the issue:

It's not a particularly serious bug, but an exception is thrown when the same code is run with a `np.double`, so fixing the bug might be a good idea to make it more user-friendly in the event of a user error and to make it more consistent with other Numpy types.

### PR DESCRIPTION
**Pull request by seberg**
This reorganizes the avoidance of infinite recursion to happen
in the generic scalar fallback, rather than attempting to do so
(badly) in the scalarmath, where it only applies to longdouble
to begin with.

This was also needed for the follow up to remove special handling
of python scalar subclasses.

Closes gh-26767

### CODE REVIEW

File: numpy/_core/src/multiarray/scalartypes.c.src [hunk 1]
```diff
@@ -219,11 +368,75 @@ gentype_multiply(PyObject *m1, PyObject *m2)
...
+         *       calling it would fail a (niche) test because an array is
+         *       returned in one of the fast-paths.
+         *       (once NumPy propagates 0-D arrays, this is irrelevant)
+         */
+        PyObject *res;
+        if (self == m1) {
+            res = PyArray_GenericBinaryFunction(m1, other_op, n_ops.power);
+        }
+        else {
+            res = PyArray_GenericBinaryFunction(other_op, m2, n_ops.power);
```
Comment (seberg) [inline numpy/_core/src/multiarray/scalartypes.c.src:428]: I started calling the ufunc directly now.  This has advantages and disadvantages, but overall: I don't think it should matter much and besides working around `power` oddities felt pretty sane.

(Not done yet for the comparison, where it might also make sense eventually)

File: numpy/_core/tests/test_scalarmath.py [hunk 2]
```diff
@@ -918,6 +922,15 @@ def test_longdouble_operators_with_obj(sctype, op):
         pass
 
 
+@pytest.mark.parametrize("op", [operator.add, operator.pow, operator.sub])
+@pytest.mark.parametrize("sctype", [np.longdouble, np.clongdouble])
+def test_longdouble_with_arrlike(sctype, op):
+    # As of NumPy 2.1, longdouble behaves like other types and can coerce
+    # e.g. lists.  (Not necessarily better, but consistent.)
+    assert_array_equal(op(sctype(3), [1, 2]), op(3, np.array([1, 2])))
+    assert_array_equal(op([1, 2], sctype(3)), op(np.array([1, 2]), 3))
```
Comment (seberg) [inline numpy/_core/tests/test_scalarmath.py:931]: So yes, the new paths aligns longdouble with others here.  I could guess at this not being right, that would remove the array conversion step.

(It may mean deciding that one test in gh-26905, just can't pass, because we simply cannot deal with subclasses of Python floats even if they get converted to a float array later.  Although, it can go either way, since you can still convert but *only* allow the `was_scalar` path.)

File: numpy/_core/src/multiarray/scalartypes.c.src [hunk 3]
```diff
@@ -164,33 +152,194 @@ gentype_generic_method(PyObject *self, PyObject *args, PyObject *kwds,
...
+
+    /*
+     * If we are here, we need to operate on Python scalars.  In general
+     * that would just fails since NumPy doesn't know the other object!
+     *
+     * However, NumPy (historically) often makes this work magically because
+     * it object ufuncs end up casting to object with `.item()` and that may
+     * returns Python type often (e.g. float for float32, float64)!
+     * Retrying then succeeds. So if (and only if) `self.item()` returns a new
+     * type, we can safely attempt the operation (again) with that.
```
Comment (ngoldbaum) [inline numpy/_core/src/multiarray/scalartypes.c.src:236]:
```suggestion
     * However, NumPy (historically) made this often work magically because
     * ufuncs for object dtype end up casting to object with `.item()`. This in
     * turn ofthen returns a Python type (e.g. float for float32, float64)!
     * Retrying then succeeds. So if (and only if) `self.item()` returns a new
     * type, we can safely attempt the operation (again) with that.
```

Just some english cleanups

File: numpy/_core/src/multiarray/scalartypes.c.src [hunk 4]
```diff
@@ -164,33 +152,194 @@ gentype_generic_method(PyObject *self, PyObject *args, PyObject *kwds,
...
+     */
+    PyObject *self_item = PyObject_CallMethodNoArgs(self, npy_interned_str.item);
+    if (self_item == NULL) {
+        return -1;
+    }
+    if (Py_TYPE(self_item) != Py_TYPE(self)) {
+        /* self_item can be used to retry the operation */
+        *self_op = self_item;
+        return 0;
+    }
```
Comment (ngoldbaum) [inline numpy/_core/src/multiarray/scalartypes.c.src:246]: don't you leak `self_item` if you get to this last `return 0`? Maybe also in the case where you assign it to `self_op`, I haven't looked at how reference counting works in the caller.

File: numpy/_core/src/umath/scalarmath.c.src [hunk 5]
```diff
@@ -1262,12 +1263,9 @@ static PyObject *
              * also integers that are too large to convert to `long`), or
              * even a subclass of a NumPy scalar (currently).
              *
-             * Generally, we try dropping through to the array path here,
-             * but this can lead to infinite recursions for (c)longdouble.
+             * We drop through to the generic path here which checks for the
+             * (c)longdouble infinite recursion problem.
```
Comment (ngoldbaum) [inline numpy/_core/src/umath/scalarmath.c.src:1267]: Might make sense to just refer to this as the "infinite recursion problem", without special casing longdouble anymore. Maybe also leave a gh-XXXX reference.

File: numpy/_core/tests/test_scalarmath.py [hunk 6]
```diff
@@ -875,8 +876,8 @@ def test_operator_object_left(o, op, type_):
 
 
 @given(sampled_from(objecty_things),
-       sampled_from(reasonable_operators_for_scalars),
-       sampled_from(types))
+       sampled_from(reasonable_operators_for_scalars + [operator.xor]),
```
Comment (ngoldbaum) [inline numpy/_core/tests/test_scalarmath.py:879]: Does stuff break if you add xor to `reasonable_operators_for_scalars`? If not i'd just add it there. If so, maybe a comment explaining why only xor here?

**Review by ngoldbaum — COMMENTED** [review]
I don't have a lot of context for the details here, but I think removing special cases for longdoubles makes a lot of sense, and the logic behind the retrying for object arrays is explained in a lot of detail.

Sorry for taking so long to look at this.

File: numpy/_core/tests/test_scalarmath.py (hunk 6 above)
Comment (seberg) [reply numpy/_core/tests/test_scalarmath.py:879]: I'll think a bit if I can think of a change. I think that would be a rename of the variable and not a comment here.

File: numpy/_core/src/umath/scalarmath.c.src (hunk 5 above)
Comment (seberg) [reply numpy/_core/src/umath/scalarmath.c.src]: For this file only longouble is problematic, but fair, removed it and added some references.

**Comment by ngoldbaum** [comment]
We chatted about this at the triage meeting and I got some extra context about why we're doing this.

**Comment by mroeschke** [comment]
I _think_ this broke a use case in pandas where arithmetic should have delegated to `__array_ufunc__`?

```python
In [3]: class Array:
   ...:     def __array_ufunc__(self, ufunc, method, *inputs, **kwargs):
   ...:         return 1
   ...: 

In [4]: np.timedelta64(120,'m') + Array()
Out[4]: 1

In [5]: np.__version__
Out[5]: '1.26.4'
```

```python
In [3]: class Array:
   ...:     def __array_ufunc__(self, ufunc, method, *inputs, **kwargs):
   ...:         return 1
   ...: 

In [4]: np.timedelta64(120,'m') + Array()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[4], line 1
----> 1 np.timedelta64(120,'m') + Array()

TypeError: unsupported operand type(s) for +: 'datetime.timedelta' and 'Array'

In [5]: np.__version__
Out[5]: '2.1.0.dev0+git20240802.0469e1d'
```

**Comment by seberg** [comment]
Hah, yes it defers still, but if you don't implement `__radd__` then the ufunc is never called now.  Hmmm...

**Comment by seberg** [comment]
OK, there are two problems, here (the second is even more subtle I guess):
1. If the other object has the `__array_ufunc__` attribute, we promise that the ufunc is called (unless we already deferred because it is `None`).  It might be nice to incorporate that into the macro, but that seems more tedious than worth it.
   Basically, the implementations all work on the assumption that if we don't defer, we quickly end up calling the ufunc.  This PR broke that assumption partially because that is necessary to break recursion.
2. There is a subtle issue that converting the array early might lose the `__array_wrap__` information.  I doubt there is a great solution for that, since I don't want to duplicate logic.  Since this is already fast-path for most cases, not sure if there is a need to worry about the "unnecessary" array conversion.

**Comment by seberg** [comment]
OK, gh-27117 should fix 1.  I looked at 2. a bit closer and I think it's not worth worrying about it, because the only way one could think it matters is for things that have the exact scalar array-priority, which is weird.
Otherwise, I suppose it could matter for scalar subclasses that define a priority, but we never supported that anyway.  (Which seems fine to me: subclassing them is bound to create inconsistencies all over the place anyway.)

**Comment by mroeschke** [comment]
At least from the pandas side, issue 2. shouldn't be significant since there's only one use of `__array_wrap__` which doesn't have significant logic to it.
