### PR TITLE
BUG: Fix empty_like to respect shape=()

### LINKED ISSUE #15880: empty_like does not respect the shape argument if it is ()
The [`empty_like` function](https://numpy.org/devdocs/reference/generated/numpy.empty_like.html) recently learnt a `shape` argument in gh-13046.

However, this argument is not always respected:
```python
>>> a = np.zeros(2)
>>> np.empty_like(a, shape=4).shape
(4,)
>>> np.empty_like(a, shape=()).shape
(2,)  # bug
```

### PR DESCRIPTION
**Pull request by eric-wieser**
Previously this was treated the same as shape=None.

Fixes gh-15880.

### CODE REVIEW

File: numpy/core/src/multiarray/multiarraymodule.c [hunk 1]
```diff
@@ -1856,14 +1856,16 @@ array_empty_like(PyObject *NPY_UNUSED(ignored), PyObject *args, PyObject *kwds)
     NPY_ORDER order = NPY_KEEPORDER;
     PyArrayObject *ret = NULL;
     int subok = 1;
-    PyArray_Dims shape = {NULL, 0};
+    /* -1 is a special value meaning "not specified" */
+    PyArray_Dims shape = {NULL, -1};
+    PyObject *shape_obj = Py_None;
```
Comment (mattip) [inline numpy/core/src/multiarray/multiarraymodule.c]: warning: unused variable ‘shape_obj’ [-Wunused-variable]

**Review by pentschev — APPROVED** [review]
Thanks for catching and fixing this @eric-wieser !

**Comment by mattip** [comment]
Thanks @eric-wieser
