### PR TITLE
API,BUG,DEP: treat trailing comma as a tuple and thus a structured dtype.

### LINKED ISSUE #25429: BUG: dtype() handles single-length comma-separated fields as scalar
### Describe the issue:

`np.dtype("i,") == np.dtype("i")` (note the comma).  Is this designed?  It feels like the former should result in a structure with one field, whereas the latter should result in a scalar.  Same as how python handles parentheses in tuples, i.e. `(val)` is interpreted differently than `(val,)`

### Reproduce the code example:

```python
import numpy as np

arr = np.empty((1,), dtype="i,")
arr[0] = (5,)
```

### Error message:

```shell
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'tuple'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: setting an array element with a sequence.
```

### Python and NumPy Versions:

python :`'3.10.11 (main, Apr  5 2023, 14:15:30) [GCC 7.5.0]'`
numpy: `1.24.1`

### Runtime Environment:

[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/home/jmsh/github/gen-experiments/env/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 64,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]

### Context for the issue:

I'm implementing a version of `np.argmax` that accepts a `axis: None or int or tuple of ints` in the way that `np.max` does.  But I also unravel the index from an into into a tuple.  I store the tuples in an array of dtype as `arr.ndim * "i,"`.

I know there's other ways of [constructing a dtype](https://numpy.org/doc/stable/reference/arrays.dtypes.html) if I manually name the fields `"f0", "f1", ...`.  So not a big priority.

### PR DESCRIPTION
**Pull request by mhvk**
Previously, `np.dtype("i")` and `np.dtype("i,")` were treated as identical, even though `np.dtype("i,i")` creates a structured dtype with two fields.  Now, `np.dtype("i,")` will create a structured dtype as well, with a single field.

At the same time, the use of `np.dtype("(2)i,")` to create a subarray with 2 elements is deprecated; one should use `np.dtype("(2,)i")` or `np.dtype("2i")` instead.  This is consistent with `np.dtype("(2)i")` raising an exception; in that sense, the previously allowed usage was a bug.

fixes #25429

### CODE REVIEW

**Comment by mhvk** [comment]
Added a release note...

File: numpy/_core/src/multiarray/descriptor.c [hunk 1]
```diff
@@ -726,32 +726,34 @@ _convert_from_list(PyObject *obj, int align)
...
-    PyObject *listobj;
+    PyObject *parsed;
     PyArray_Descr *res;
-    PyObject *_numpy_internal;
+    static PyObject *_numpy_internal = NULL;
     assert(PyUnicode_Check(obj));
-    _numpy_internal = PyImport_ImportModule("numpy._core._internal");
     if (_numpy_internal == NULL) {
-        return NULL;
+        _numpy_internal = PyImport_ImportModule("numpy._core._internal");
```
Comment (seberg) [inline numpy/_core/src/multiarray/descriptor.c:734]: Would be a bit nicer via:
```
npy_cache_import("numpy._core._internal", "_commastring", &_commastring);
```
And calling it with:
```
PyObject_CallOneArg(_commanstring, obj);
```

File: numpy/_core/src/multiarray/descriptor.c [hunk 2]
```diff
@@ -726,32 +726,34 @@ _convert_from_list(PyObject *obj, int align)
...
-                "_commastring is not returning a list with len >= 1");
-        Py_DECREF(listobj);
-        return NULL;
+    if (PyUnicode_Check(parsed)
+        || (PyTuple_Check(parsed) && PyTuple_GET_SIZE(parsed) == 2)) {
+        res = _convert_from_any(parsed, align);
     }
-    if (PyList_GET_SIZE(listobj) == 1) {
-        res = _convert_from_any(PyList_GET_ITEM(listobj, 0), align);
+    else if (PyList_Check(parsed) && PyList_GET_SIZE(parsed) >= 1) {
```
Comment (seberg) [inline numpy/_core/src/multiarray/descriptor.c:747]:
```suggestion
    else if (PyList_Check(parsed)) {
```
I suppose length 0 is impossible here anyway?  I suspect we could remove the size check.

File: numpy/_core/tests/test_dtype.py [hunk 3]
```diff
@@ -436,6 +443,14 @@ def test_subarray_list(self, obj, dtype, expected):
 
         assert_array_equal(res, expected)
 
+    def test_parenthesized_single_number(self):
+        with pytest.raises(TypeError, match="not understood"):
+            np.dtype("(2)f4")
+
+        with pytest.warns(DeprecationWarning,
+                          match="parenthesized single number"):
+            np.dtype("(2)f4,")
```
Comment (seberg) [inline numpy/_core/tests/test_dtype.py:452]: Would be nice as a Deprecation test case, mainly because that also raises the error, thus covering the error path.  But, it does also look all good anyway.

File: doc/release/upcoming_changes/25434.change.rst [hunk 4]
```diff
@@ -0,0 +1,15 @@
+Cleanup of initialization of ``numpy.dtype`` with strings with commas
```
Comment (seberg) [inline doc/release/upcoming_changes/25434.change.rst:1]: I guess the `(2,)` deprecation may be a bit because we only trigger this parsing when there is a comma somewhere?
Anyway, I am a bit ambivalent to it, but also don't worry about it (someone can still be annoyed and undo it anyway).

**Review by seberg — APPROVED** [review]
Thanks LGTM, just nits, this is OK to put in to me.

If someone has an idea to shorten the release note, I wouldn't mind.
Otherwise, I am ambivalent towards the deprecation, but at least if it is tedious to make `(2)i` (without any comma, I think it takes a different code path!) work, neither do I care.

I would appreciate cleaning up the C-calling code a bit (cache `_commastring` not the module).

(To me the Python side parsing code looks a bit overly complicated, but not a problem here...)

File: numpy/_core/src/multiarray/descriptor.c (hunk 1 above)
Comment (mhvk) [reply numpy/_core/src/multiarray/descriptor.c:734]: Yes, of course, should have thought of that!

File: numpy/_core/src/multiarray/descriptor.c (hunk 2 above)
Comment (mhvk) [reply numpy/_core/src/multiarray/descriptor.c:747]: I think the length checks were mainly meant to guard against silly mistakes in the python code. My sense would be to leave it in.

File: doc/release/upcoming_changes/25434.change.rst (hunk 4 above)
Comment (mhvk) [reply doc/release/upcoming_changes/25434.change.rst:1]: Yes, the path only gets hit if there is a comma in the string. If "(2)i" was normally acceptable, I would definitely have let it be, but since it is not, I think we might as well go for slightly more logical. And I agree we can undo it if it causes too many problems.

File: numpy/_core/tests/test_dtype.py (hunk 3 above)
Comment (mhvk) [reply numpy/_core/tests/test_dtype.py:452]: I added a deprecation test case and a comment here. Let me know if this is what you had in mind.

**Review by seberg — APPROVED** [review]
Thanks, LGTM now.  Will wait a bit in case someone has a comment or just feels like pressing the green button :).

**Comment by ngoldbaum** [comment]
Thanks @mhvk!
