### PR TITLE
BUG: longdouble(int) does not work

### LINKED ISSUE #9968: BUG: `np.longdouble(2**1024)` overflows due to intermediate float cast
Should be relatively straightforward to fix this - the dumb implementation would be to just to cast to string first, as this works fine:

```
>>> np.longdouble(2**1024)
OverflowError: int too large to convert to float
>>> np.longdouble(str(2**1024))
1.7976931348623159077e+308
```

### PR DESCRIPTION
**Pull request by eric-wieser**
Fixes gh-9968

Needs tests yet, which I can't write without access to a platform with `longdouble` having higher precision than `double`.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Rebased. This code has a deeply worrying heisenbug in MSVC...

File: numpy/core/src/common/npy_longdouble.c [hunk 1]
```diff
@@ -94,3 +95,77 @@ npy_longdouble_to_PyLong(npy_longdouble ldval)
...
+    /* Extra characters at the end of the string, or nothing parsed */
+    if (end == cstr || *end) {
+        PyErr_Format(PyExc_RuntimeError,
+                     "Could not parse long as longdouble: %s",
+                     cstr);
+        return -1;
+    }
+
+    // Without this line, MSVC produces garbage (optimizes out result!?)
+    printf("Double form is %f\n", (double) result);
```
Comment (eric-wieser) [inline numpy/core/src/common/npy_longdouble.c]: I kid you not. Without this, `np.longdouble(0)` returns `-104892023.0`.

Comment (eric-wieser) [reply numpy/core/src/common/npy_longdouble.c]: In even more frightening news, replacing this line with:
```
// Without this line, MSVC produces garbage (optimizes out result!?)
printf("abc\n");
return result;
```

Causes `np.longdouble(x)` to always return `4.0`, which is `len('abc\n')`.

Comment (mattip) [reply numpy/core/src/common/npy_longdouble.c]: could the compiler output from [godbot](https://godbolt.org/) help work out what is going on?

Comment (tylerjereddy) [reply numpy/core/src/common/npy_longdouble.c]: This appears to be because the function prototype was not available before the function was called in `arraytypes.c.src`, which caused just as much chaos on my Mac until I added the appropriate `include` there, which I've now pushed in with my initial adjustments.

I suggest we might benefit from `warning: implicit declaration of function` into a compiler error--looks like this warning is effectively understating a break in C99 standard.

File: numpy/core/getlimits.py [hunk 2]
```diff
@@ -156,8 +156,8 @@ def _register_known_types():
 
     # Known parameters for IEEE 754 128-bit binary float
     ld = ntypes.longdouble
-    epsneg_f128 = exp2(ld(-113))
-    tiny_f128 = exp2(ld(-16382))
+    epsneg_f128 = 2 ** -113.0
```
Comment (tylerjereddy) [inline numpy/core/getlimits.py]: @eric-wieser can I actually do this? I also noticed we have `exp2l` buried somewhere--regardless `getlimits.py` is having issues with these exp2 calls involving long double.

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 3]
```diff
@@ -30,6 +30,7 @@
 #include <emmintrin.h>
 #endif
 
+#include "npy_longdouble.h"
```
Comment (tylerjereddy) [inline numpy/core/src/multiarray/arraytypes.c.src]: without this, adding `printf` or even calling code multiple times caused stability issues; I think we should just make it an error if the function prototype isn't available

File: numpy/core/src/common/npy_longdouble.c [hunk 4]
```diff
@@ -94,3 +95,88 @@ npy_longdouble_to_PyLong(npy_longdouble ldval)
...
+                     cstr,
+                     strerror(errno_save));
+        return -1;
+    }
+
+    /*
+    / NOTE: the block below was causing an error in
+    / 10 tests in numpy/ma/tests/test_core.py:
+    / RuntimeError: Could not parse long as longdouble: True
+    */
```
Comment (tylerjereddy) [inline numpy/core/src/common/npy_longdouble.c]: Maybe need to adjust the code below for masked array handling?

**Review by tylerjereddy — COMMENTED** [review]
There will still be a few unit test failures left in CI after my revision push, but hopefully this dislodges some of the blocking issues here--in particular, the nasty bug with the function prototype inclusion preventing sane debugging.

I'm expecting 3 test failures related to fpe underflow expectations & things in `getlimits.py`, which Eric can probably solve with more confidence than I.

**Comment by tylerjereddy** [comment]
Yeah, just seeing 3 test failures on Windows / Mac now in CI, so this should hopefully be easier to get over the line now.

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 5]
```diff
@@ -328,6 +329,17 @@ string_to_long_double(PyObject*op)
     npy_longdouble temp;
     PyObject* b;
 
+    /* Convert python long objects to a longdouble, without precision or range
+     * loss via a double.
+     */
+    if (PyLong_Check(op)
+#if !defined(NPY_PY3K)
+        || PyInt_Check(op)
+#endif
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/arraytypes.c.src]: I think we just need to avoid running this code-path for booleans (and adding a test for `np.longdouble(True)`)

File: numpy/core/getlimits.py (hunk 2 above)
Comment (eric-wieser) [reply numpy/core/getlimits.py]: No, this will underflow and produce 0 on all platforms if you don't cast an operand to longdouble

File: numpy/core/src/multiarray/arraytypes.c.src (hunk 3 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/arraytypes.c.src]: Good catch! Please do make this a compilation error!

File: numpy/core/getlimits.py (hunk 2 above)
Comment (tylerjereddy) [reply numpy/core/getlimits.py]: Reverted -- no longer causes issues, thanks.

File: numpy/core/src/common/npy_longdouble.c (hunk 4 above)
Comment (tylerjereddy) [reply numpy/core/src/common/npy_longdouble.c]: resolved with proper bool handling noted in commit message

File: numpy/core/src/multiarray/arraytypes.c.src (hunk 5 above)
Comment (tylerjereddy) [reply numpy/core/src/multiarray/arraytypes.c.src]: yes! that worked! I guess because of bools in masked arrays or something like that!

**Comment by tylerjereddy** [comment]
All tests pass locally & all conversations marked as resolved after applying Eric's revisions to my revisions. Fingers crossed for the CI to agree.

**Comment by tylerjereddy** [comment]
Remaining CI failures can be summarized as:

1 test fails with the following on platforms where `np.longdouble==np.double`:
`RuntimeWarning: overflow encountered in conversion from python long`

A DEBUG build has a problem with `epsneg_f128 = exp2(ld(-113))`.
`untimeError: Could not parse long as longdouble:` followed by a bunch of strange characters

File: numpy/core/tests/test_longdouble.py [hunk 6]
```diff
@@ -205,3 +206,28 @@ def test_fromstring_foreign_sep(self):
...
+    # for large integer input
+    with warnings.catch_warnings(record=True) as w:
+        warnings.filterwarnings('always', '', RuntimeWarning)
+        # can be inf==inf on some platforms
+        assert np.longdouble(int_val) == np.longdouble(str_val)
+        # we can't directly compare the int and
+        # max longdouble value on all platforms
+        if np.allclose(np.finfo(np.longdouble).max,
+                       np.finfo(np.double).max) and w:
+            assert w[0].category is RuntimeWarning
```
Comment (tylerjereddy) [inline numpy/core/tests/test_longdouble.py]: This seemed to help on Windows in my hands. Basically, we check for a warning on platforms where longdouble simple isn't big enough to handle the test. It'll typically produce something like `inf==inf` for the big test case, so I think can avoid having to skip / xfail.

File: numpy/core/src/common/npy_longdouble.c [hunk 7]
```diff
@@ -94,3 +95,82 @@ npy_longdouble_to_PyLong(npy_longdouble ldval)
...
+    }
+    else if (errno_save) {
+        PyErr_Format(PyExc_RuntimeError,
+                     "Could not parse python long as longdouble: %s (%s)",
+                     cstr,
+                     strerror(errno_save));
+        return -1;
+    }
+
+    /* Extra characters at the end of the string, or nothing parsed */
```
Comment (tylerjereddy) [inline numpy/core/src/common/npy_longdouble.c]: @eric-wieser could DEBUG mode be putting extra characters in here somewhere? I still need to debug that from the Travis fail we're seeing.

I couldn't reproduce on my mac earlier, but I'm not entirely clear on the right CFLAGS or whatever to induce the issue, and if the issue is portable to clang.

**Review by tylerjereddy — COMMENTED** [review]
Revised to hopefully fix 1 test failure, although CI may be confused by issues discussed in #13448.

Still expecting DEBUG mode fail on Travis--discussed briefly in a review comment.

**Comment by tylerjereddy** [comment]
One other thought here, since we don't see the Azure 32-bit failure (ran before the merge of #13449), is that Azure may be doing branch instead of merge tests?

**Comment by eric-wieser** [comment]
> RuntimeError: Could not parse long as longdouble: followed by a bunch of strange characters

I think it's a lifetime problem, and I have a local fix for it. Will attempt to merge with your fixes at some point...

**Comment by tylerjereddy** [comment]
Ok, that sounds good. I see that Azure is actually doing merges, so that's good too.

**Comment by tylerjereddy** [comment]
Great, thanks Eric

Would be good if our line cov data eventually covers more than 1 platform, but the few "missing" error handling lines in the new C function were hit during the review / debugging of this PR at various stages anyway, so we can be pretty confident they are hit on Windows / Power8 in CI, etc.
