### PR TITLE
BUG: Prevent attempted broadcasting of 0-D output operands in ufuncs

### LINKED ISSUE #21673: BUG: Segmentation fault for ufunc with output with wrong shape
### Describe the issue:

A strange bug in astropy - https://github.com/astropy/astropy/issues/13283 - boils down to the example below giving a segmentation fault. To trigger the bug, one of the two arguments need to be scalar; if one replaces with `[1.]` in the example, one gets the correct broadcasting error.

### Reproduce the code example:

```python
import numpy as np
np.add(1., [1., 2.], out=np.empty(()))
```

### Error message:

```shell
Segmentation fault
```

### NumPy/Python version information:

1.21.5 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
1.22.4 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]

According to https://github.com/astropy/astropy/issues/13283, the bug was introduced in numpy 1.21

### PR DESCRIPTION
**Pull request by seberg**
Attempting to broadcast causes crashes when we later check for self
overlap of the output operand (assuming it is 1-D).
But it would also crash if the operation was done, the issue is
not rejecting the broadcasting right-away.

Closes gh-21673

### CODE REVIEW

File: numpy/core/src/umath/ufunc_object.c [hunk 1]
```diff
@@ -1243,7 +1243,7 @@ try_trivial_single_output_loop(PyArrayMethod_Context *context,
         int op_ndim = PyArray_NDIM(op[iop]);
 
         /* Special case 0-D since we can handle broadcasting using a 0-stride */
-        if (op_ndim == 0) {
+        if (op_ndim == 0 && iop != nin) {
```
Comment (mhvk) [inline numpy/core/src/umath/ufunc_object.c:1246]: Should be `iop < nin`, I think, to ensure this doesn't bite ufuncs with more than one output (though I don't think there is any for which it is relevant; I don't think one can trigger the bug for single-input ufuncs, so `np.modf` seems safe)

File: numpy/core/tests/test_ufunc.py [hunk 2]
```diff
@@ -799,6 +799,20 @@ def test_out_broadcasts(self):
...
+                (np.ones((4, 3)), np.empty((4, 1)))],
+            ids=["(1,)->()", "(2,)->(1,)", "(4, 3)->(4, 1)"])
+    def test_out_broadcast_errors(self, arr, out):
+        # Output is (currently) allowed to broadcast inputs, but it cannot be
+        # smaller than the actual result.
+        with pytest.raises(ValueError, match="non-broadcastable"):
+            np.positive(arr, out=out)
+
+        with pytest.raises(ValueError, match="non-broadcastable"):
+            np.add(np.ones(()), arr, out=out)
```
[the remark this answers is not in the document]
Comment (mhvk) [reply numpy/core/tests/test_ufunc.py:814]: The issue indeed seems to require a scalar input - so it cannot be triggered for single-input ufuncs.

**Review by mhvk — COMMENTED** [review]
Looks good! Only a small future-proof suggestion.

File: numpy/core/src/umath/ufunc_object.c (hunk 1 above)
Comment (seberg) [reply numpy/core/src/umath/ufunc_object.c]: Yeah, the fast-path is only ever used for single outputs right now, but it is definitely the better spelling.

File: numpy/core/tests/test_ufunc.py (hunk 2 above)
[the remark this answers is not in the document]
Comment (mhvk) [reply numpy/core/tests/test_ufunc.py:814]: No, it just depends on me drawing conclusions without testing correctly... 
```
In [3]: np.modf([1.5, 2.], out=(np.empty(()), np.empty(())))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 np.modf([1.5, 2.], out=(np.empty(()), np.empty(())))

ValueError: non-broadcastable output operand with shape () doesn't match the broadcast shape (2,)

In [4]: np.positive([1.5, 2.], out=np.empty(()))
Segmentation fault
```

File: numpy/core/src/umath/ufunc_object.c (hunk 1 above)
Comment (mhvk) [reply numpy/core/src/umath/ufunc_object.c]: Ah, that explains it, then!

**Review by mhvk — APPROVED** [review]
Looks all good now!

**Comment by charris** [comment]
Thanks Sebastian.
