### PR TITLE
DEP,BUG: Finalize subarray dtype FutureWarning and fix its assignment

### LINKED ISSUE #23083: BUG: Assign scalars into new arrays with subarray dims fails for higher dimensions
### Describe the issue:

Scalar values don't broadcast correctly when creating an array with a sub-array dtype.

For example, this works as expected:
```python
>>> import numpy as np
>>> np.__version__
'1.24.1'
>>> np.array([0, 1, 2], dtype=('<i8', (3,)))
array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])
```
But these do not:
```python
>>> np.array([[0, 1, 2]], dtype=('<i8', (3,)))
array([[[                   0,                    0,
                            0],
        [                   1,  4672486039879745776,
         -1080498730957541302],
        [                   2,  5549843219359026209,
                   4311806977]]])
>>> np.array([[0], [1], [2]], dtype=('<i8', (3,)))
array([[[                   0,                    0,
                            0]],

       [[                   1,  4672486039879745776,
         -1080498730957541302]],

       [[                   2,  5549843219359026209,
                   4311806977]]])
```

### Reproduce the code example:

```python
import numpy as np

a = np.array([[0, 1, 2]], dtype=('<i8', (3,)))
expected = np.array([0, 1, 2], dtype=('<i8', (3,)))[np.newaxis, :, :]
np.testing.assert_array_equal(a, expected)

b = np.array([[0], [1], [2]], dtype=('<i8', (3,)))
expected = np.array([0, 1, 2], dtype=('<i8', (3,)))[:, np.newaxis, :]
np.testing.assert_array_equal(a, expected)
```

### Error message:

```shell
>>> np.testing.assert_array_equal(a, expected)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/erik/miniconda3/envs/np/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 983, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "/home/erik/miniconda3/envs/np/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/erik/miniconda3/envs/np/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 862, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

Mismatched elements: 6 / 9 (66.7%)
Max absolute difference: 4905783429429202131
Max relative difference: 4.90578343e+18
 x: array([[[                  0,     140460087864352,    5330496813138160],
        [                  1, 4905783429429202132,   58565490347611344],
        [                  2,                   0,                  80]]])
 y: array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]]])
```

### Runtime information:

```python
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.24.1
3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0]
>>> print(numpy.show_runtime())
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': ['AVX512_KNL', 'AVX512_KNM']}}]
None
```

### Context for the issue:

It's an interesting edgecase🙃 

I expect sub-array dtypes to be important "user-defined types" for some users of [`python-graphblas`](https://github.com/python-graphblas/python-graphblas/), and we defer to numpy when creating arrays of these types.

### PR DESCRIPTION
**Pull request by seberg**
This PR should be reviewed in multiple steps, because I included a first commit which is pretty simple, but an important refactor:

* The first maintenance commit changes `PyArray_NewFromDescr_int` to use a flags object as a last thing (because I didn't want to pass 3 flags).  It then adds a third flag which denotes that we know the dtype is good.  That flag is generally only considered valid for creating a view, but for those it makes a lot of sense (and implies/side-steps the S0 allowing flag, which we still need, but is probably more of a stop-gap).
* A small follow-up, because it made a check/code path obsoltete in `ufunc.resolve_dtypes`
* The DEP commit:  This removes an old Deprecation which is related to the first part.  When a `dtype=` is given in array or astype calls, that cast was previously performed _after_ absorbing subarray dimensions in some code paths.  This is not the case anymore now.

As mentioned in the commit message.  The combination of the two commits not only expires the FutureWarning, it also closes gh-23083.

### CODE REVIEW

File: numpy/core/src/multiarray/ctors.c [hunk 1]
```diff
@@ -644,45 +643,54 @@ PyArray_NewFromDescr_int(
...
+                PyArray_DESCR_REPLACE(descr);
+                if (descr == NULL) {
+                    return NULL;
+                }
+                if (descr->type_num == NPY_STRING) {
+                    nbytes = descr->elsize = 1;
+                }
+                else {
+                    nbytes = descr->elsize = sizeof(npy_ucs4);
+                }
```
Comment (seberg) [inline numpy/core/src/multiarray/ctors.c:693]: This whole change is just one indentation level.

**Review by ngoldbaum — APPROVED** [review]
This looks like a good cleanup! I agree the new enum is much clearer than the old boolean flags at the end of `PyArray_NewFromDescr_int`'s signature.

I only looked carefully at the structural changes to that function since I was working there recently and didn't look closely at the behavior changes that finalizing the deprecations leads to.

File: numpy/core/src/multiarray/mapping.c [hunk 2]
```diff
@@ -889,13 +889,13 @@ get_view_from_index(PyArrayObject *self, PyArrayObject **view,
...
     Py_INCREF(PyArray_DESCR(self));
-    *view = (PyArrayObject *)PyArray_NewFromDescrAndBase(
+    *view = (PyArrayObject *)PyArray_NewFromDescr_int(
             ensure_array ? &PyArray_Type : Py_TYPE(self),
             PyArray_DESCR(self),
             new_dim, new_shape, new_strides, data_ptr,
             PyArray_FLAGS(self),
             ensure_array ? NULL : (PyObject *)self,
-            (PyObject *)self);
+            (PyObject *)self, _NPY_ARRAY_ENSURE_DTYPE_IDENTITY);
```
Comment (mattip) [inline numpy/core/src/multiarray/mapping.c:898]: nice

**Review by mattip — APPROVED** [review]

**Comment by mattip** [comment]
Thanks @seberg. This is a nice cleanup and refactor of a clunky interface

**Comment by seberg** [comment]
Thanks for the review.  This was started a bit ago, so I will note it but I really don't think we should worry:  I think there is one code path were the deprecation was missing.

That code-path should do complete and utter nonsense though (due to the way broadcasting works), which is why I want to just not worry about it.

(A new `(array_shape + subarray_shape)` doesn't broadcast sensibly with `(array_shape)` except in very strange arguably buggy ways.  So I will consider that last path a bug-fix really.)
