### PR TITLE
BUG: move reduction initialization to ufunc initialization

### LINKED ISSUE #28041: BUG: Race in computing initial value for reductions under free-threading
### Describe the issue:

With:
* CPython 3.13 built with the GIL disabled, using thread-sanitizer under clang,
* NumPy 2.3.0dev commit 35b2c4a68e786cf7afd0c9cfc5feed41541db663 built with thread-sanitizer and clang

thread sanitizer reports a race constructing the cached initial value for a reducer.

You may need to run the example a few times, but it reproduced first time for me.

### Reproduce the code example:

```python
import concurrent.futures
import threading
import numpy as np

num_threads = 8


x = np.arange(1000)
b = threading.Barrier(num_threads)
def closure():
  b.wait()
  np.sum(x)

with concurrent.futures.ThreadPoolExecutor(max_workers=num_threads) as executor:
  for _ in range(num_threads):
    executor.submit(closure)
```

### Error message:

```shell
WARNING: ThreadSanitizer: data race (pid=4069590)
  Write of size 8 at 0x7f6412728ef8 by thread T135:
    #0 get_initial_from_ufunc legacy_array_method.c (_multiarray_umath.cpython-313t-x86_64-linux-gnu.so+0x3de246) (BuildId: a138a702a237ca030803af4168ee423ada9702f7)
    #1 PyUFunc_ReduceWrapper <null> (_multiarray_umath.cpython-313t-x86_64-linux-gnu.so+0x3e0426) (BuildId: a138a702a237ca030803af4168ee423ada9702f7)
    #2 PyUFunc_Reduce ufunc_object.c (_multiarray_umath.cpython-313t-x86_64-linux-gnu.so+0x3f0349) (BuildId: a138a702a237ca030803af4168ee423ada9702f7)
    #3 PyUFunc_GenericReduction ufunc_object.c (_multiarray_umath.cpython-313t-x86_64-linux-gnu.so+0x3efffa) (BuildId: a138a702a237ca030803af4168ee423ada9702f7)
    #4 ufunc_reduce ufunc_object.c (_multiarray_umath.cpython-313t-x86_64-linux-gnu.so+0x3ed841) (BuildId: a138a702a237ca030803af4168ee423ada9702f7)
    #5 cfunction_vectorcall_FASTCALL_KEYWORDS /usr/local/google/home/phawkins/p/cpython/Objects/methodobject.c:441:24 (python3.13+0x28a010) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #6 _PyVectorcall_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:273:16 (python3.13+0x1eb293) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #7 _PyObject_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:348:16 (python3.13+0x1eb293)
    #8 PyObject_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:373:12 (python3.13+0x1eb315) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #9 _PyEval_EvalFrameDefault /usr/local/google/home/phawkins/p/cpython/Python/generated_cases.c.h:1355:26 (python3.13+0x3e46e2) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #10 _PyEval_EvalFrame /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_ceval.h:119:16 (python3.13+0x3de62a) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #11 _PyEval_Vector /usr/local/google/home/phawkins/p/cpython/Python/ceval.c:1811:12 (python3.13+0x3de62a)
    #12 _PyFunction_Vectorcall /usr/local/google/home/phawkins/p/cpython/Objects/call.c (python3.13+0x1eb61f) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #13 _PyObject_VectorcallTstate /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_call.h:168:11 (python3.13+0x1eafaa) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #14 PyObject_Vectorcall /usr/local/google/home/phawkins/p/cpython/Objects/call.c:327:12 (python3.13+0x1eafaa)
    #15 dispatcher_vectorcall arrayfunction_override.c (_multiarray_umath.cpython-313t-x86_64-linux-gnu.so+0x22d22b) (BuildId: a138a702a237ca030803af4168ee423ada9702f7)
    #16 _PyObject_VectorcallTstate /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_call.h:168:11 (python3.13+0x1eafaa) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #17 PyObject_Vectorcall /usr/local/google/home/phawkins/p/cpython/Objects/call.c:327:12 (python3.13+0x1eafaa)
    #18 _PyEval_EvalFrameDefault /usr/local/google/home/phawkins/p/cpython/Python/generated_cases.c.h:813:23 (python3.13+0x3e24fb) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #19 _PyEval_EvalFrame /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_ceval.h:119:16 (python3.13+0x3de62a) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #20 _PyEval_Vector /usr/local/google/home/phawkins/p/cpython/Python/ceval.c:1811:12 (python3.13+0x3de62a)
    #21 _PyFunction_Vectorcall /usr/local/google/home/phawkins/p/cpython/Objects/call.c (python3.13+0x1eb61f) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #22 _PyObject_VectorcallTstate /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_call.h:168:11 (python3.13+0x1ef5ef) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #23 method_vectorcall /usr/local/google/home/phawkins/p/cpython/Objects/classobject.c:70:20 (python3.13+0x1ef5ef)
    #24 _PyVectorcall_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:273:16 (python3.13+0x1eb293) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #25 _PyObject_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:348:16 (python3.13+0x1eb293)
    #26 PyObject_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:373:12 (python3.13+0x1eb315) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #27 thread_run /usr/local/google/home/phawkins/p/cpython/./Modules/_threadmodule.c:337:21 (python3.13+0x564292) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #28 pythread_wrapper /usr/local/google/home/phawkins/p/cpython/Python/thread_pthread.h:243:5 (python3.13+0x4bd637) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)

  Previous write of size 8 at 0x7f6412728ef8 by thread T131:
    #0 get_initial_from_ufunc legacy_array_method.c (_multiarray_umath.cpython-313t-x86_64-linux-gnu.so+0x3de246) (BuildId: a138a702a237ca030803af4168ee423ada9702f7)
    #1 PyUFunc_ReduceWrapper <null> (_multiarray_umath.cpython-313t-x86_64-linux-gnu.so+0x3e0426) (BuildId: a138a702a237ca030803af4168ee423ada9702f7)
    #2 PyUFunc_Reduce ufunc_object.c (_multiarray_umath.cpython-313t-x86_64-linux-gnu.so+0x3f0349) (BuildId: a138a702a237ca030803af4168ee423ada9702f7)
    #3 PyUFunc_GenericReduction ufunc_object.c (_multiarray_umath.cpython-313t-x86_64-linux-gnu.so+0x3efffa) (BuildId: a138a702a237ca030803af4168ee423ada9702f7)
    #4 ufunc_reduce ufunc_object.c (_multiarray_umath.cpython-313t-x86_64-linux-gnu.so+0x3ed841) (BuildId: a138a702a237ca030803af4168ee423ada9702f7)
    #5 cfunction_vectorcall_FASTCALL_KEYWORDS /usr/local/google/home/phawkins/p/cpython/Objects/methodobject.c:441:24 (python3.13+0x28a010) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #6 _PyVectorcall_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:273:16 (python3.13+0x1eb293) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #7 _PyObject_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:348:16 (python3.13+0x1eb293)
    #8 PyObject_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:373:12 (python3.13+0x1eb315) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #9 _PyEval_EvalFrameDefault /usr/local/google/home/phawkins/p/cpython/Python/generated_cases.c.h:1355:26 (python3.13+0x3e46e2) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #10 _PyEval_EvalFrame /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_ceval.h:119:16 (python3.13+0x3de62a) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #11 _PyEval_Vector /usr/local/google/home/phawkins/p/cpython/Python/ceval.c:1811:12 (python3.13+0x3de62a)
    #12 _PyFunction_Vectorcall /usr/local/google/home/phawkins/p/cpython/Objects/call.c (python3.13+0x1eb61f) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #13 _PyObject_VectorcallTstate /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_call.h:168:11 (python3.13+0x1eafaa) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #14 PyObject_Vectorcall /usr/local/google/home/phawkins/p/cpython/Objects/call.c:327:12 (python3.13+0x1eafaa)
    #15 dispatcher_vectorcall arrayfunction_override.c (_multiarray_umath.cpython-313t-x86_64-linux-gnu.so+0x22d22b) (BuildId: a138a702a237ca030803af4168ee423ada9702f7)
    #16 _PyObject_VectorcallTstate /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_call.h:168:11 (python3.13+0x1eafaa) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #17 PyObject_Vectorcall /usr/local/google/home/phawkins/p/cpython/Objects/call.c:327:12 (python3.13+0x1eafaa)
    #18 _PyEval_EvalFrameDefault /usr/local/google/home/phawkins/p/cpython/Python/generated_cases.c.h:813:23 (python3.13+0x3e24fb) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #19 _PyEval_EvalFrame /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_ceval.h:119:16 (python3.13+0x3de62a) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #20 _PyEval_Vector /usr/local/google/home/phawkins/p/cpython/Python/ceval.c:1811:12 (python3.13+0x3de62a)
    #21 _PyFunction_Vectorcall /usr/local/google/home/phawkins/p/cpython/Objects/call.c (python3.13+0x1eb61f) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #22 _PyObject_VectorcallTstate /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_call.h:168:11 (python3.13+0x1ef5ef) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #23 method_vectorcall /usr/local/google/home/phawkins/p/cpython/Objects/classobject.c:70:20 (python3.13+0x1ef5ef)
    #24 _PyVectorcall_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:273:16 (python3.13+0x1eb293) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #25 _PyObject_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:348:16 (python3.13+0x1eb293)
    #26 PyObject_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:373:12 (python3.13+0x1eb315) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #27 thread_run /usr/local/google/home/phawkins/p/cpython/./Modules/_threadmodule.c:337:21 (python3.13+0x564292) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #28 pythread_wrapper /usr/local/google/home/phawkins/p/cpython/Python/thread_pthread.h:243:5 (python3.13+0x4bd637) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
```

### Python and NumPy Versions:

2.3.0.dev0+git20241219.35b2c4a
3.13.1 experimental free-threading build (tags/v3.13.1:06714517797, Dec 15 2024, 15:38:01) [Clang 18.1.8 (11)]

### Runtime Environment:

[{'numpy_version': '2.3.0.dev0+git20241219.35b2c4a',
  'python': '3.13.1 experimental free-threading build '
            '(tags/v3.13.1:06714517797, Dec 15 2024, 15:38:01) [Clang 18.1.8 '
            '(11)]',
  'uname': uname_result(system='Linux', node='<redacted>', release='<redacted>', version='#1 SMP PREEMPT_DYNAMIC Debian 6.redacted (2024-10-16)', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Zen',
  'filepath': '/usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.27.so',
  'internal_api': 'openblas',
  'num_threads': 128,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.27'}]

### Context for the issue:

Found when working on free-threading support in JAX.

### LINKED ISSUE #28122: BUG: data race in f2py callback tests on free-threaded build
To reproduce this you need to build CPython and NumPy from source with thread sanitizer. See [here](https://py-free-threading.github.io/debugging/#compile-free-threaded-cpython-with-tsan) for more details on how to do that.

If you run the f2py callback tests, you'll see the following warnings reported:

<details>

```
± CC=/opt/homebrew/opt/llvm/bin/clang CXX=/opt/homebrew/opt/llvm/bin/clang++ spin test -- -sv numpy/f2py/tests/test_callback.py
python(32402,0x1f6dfc240) malloc: nano zone abandoned due to inability to reserve vm space.
Invoking `build` prior to running tests:
$ /Users/goldbaum/.pyenv/versions/3.13t-dev-tsan/bin/python vendored-meson/meson/meson.py compile -C build
python(32457,0x1f6dfc240) malloc: nano zone abandoned due to inability to reserve vm space.
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /Users/goldbaum/.pyenv/versions/3.13t-dev-tsan/bin/ninja -C /Users/goldbaum/Documents/numpy/build
ninja: Entering directory `/Users/goldbaum/Documents/numpy/build'
[1/1] Generating numpy/generate-version with a custom command
Saving version to numpy/version.py
$ /Users/goldbaum/.pyenv/versions/3.13t-dev-tsan/bin/python vendored-meson/meson/meson.py install --only-changed -C build --destdir ../build-install
$ export PYTHONPATH="/Users/goldbaum/Documents/numpy/build-install/usr/lib/python3.13t/site-packages"
$ /Users/goldbaum/.pyenv/versions/3.13t-dev-tsan/bin/python -P -c 'import numpy'
python(32488,0x1f6dfc240) malloc: nano zone abandoned due to inability to reserve vm space.
$ cd /Users/goldbaum/Documents/numpy/build-install/usr/lib/python3.13t/site-packages
$ /Users/goldbaum/.pyenv/versions/3.13t-dev-tsan/bin/python -P -m pytest -m 'not slow' -sv numpy/f2py/tests/test_callback.py
python(32490,0x1f6dfc240) malloc: nano zone abandoned due to inability to reserve vm space.
=========================================================== test session starts ===========================================================
platform darwin -- Python 3.13.1+, pytest-8.3.4, pluggy-1.5.0 -- /Users/goldbaum/.pyenv/versions/3.13t-dev-tsan/bin/python
cachedir: .pytest_cache
hypothesis profile 'np.test() profile' -> database=None, deadline=None, print_blob=True, derandomize=True, suppress_health_check=[HealthCheck.data_too_large, HealthCheck.filter_too_much, HealthCheck.too_slow, HealthCheck.large_base_example, HealthCheck.function_scoped_fixture, HealthCheck.differing_executors]
rootdir: /Users/goldbaum/Documents/numpy
configfile: pytest.ini
plugins: hypothesis-6.123.2, xdist-3.6.1
collected 18 items / 7 deselected / 11 selected

numpy/f2py/tests/test_callback.py::TestF77Callback::test_docstring PASSED
numpy/f2py/tests/test_callback.py::TestF77Callback::test_string_callback PASSED
numpy/f2py/tests/test_callback.py::TestF77Callback::test_string_callback_array PASSED
numpy/f2py/tests/test_callback.py::TestF77Callback::test_threadsafety ==================
WARNING: ThreadSanitizer: data race (pid=32490)
  Atomic read of size 8 at 0x000165cbda48 by thread T5:
    #0 PyObject_Vectorcall call.c:327 (libpython3.13t.dylib:arm64+0x803f4)
    #1 _PyEval_EvalFrameDefault generated_cases.c.h:1502 (libpython3.13t.dylib:arm64+0x25f41c)
    #2 _PyEval_Vector ceval.c:1807 (libpython3.13t.dylib:arm64+0x2552cc)
    #3 _PyFunction_Vectorcall call.c (libpython3.13t.dylib:arm64+0x80aa8)
    #4 method_vectorcall classobject.c:70 (libpython3.13t.dylib:arm64+0x84714)
    #5 _PyObject_Call call.c:348 (libpython3.13t.dylib:arm64+0x806ec)
    #6 PyObject_Call call.c:373 (libpython3.13t.dylib:arm64+0x80784)
    #7 thread_run _threadmodule.c:337 (libpython3.13t.dylib:arm64+0x3b6e40)
    #8 pythread_wrapper thread_pthread.h:243 (libpython3.13t.dylib:arm64+0x320c88)

  Previous write of size 8 at 0x000165cbda48 by thread T4:
    #0 type_ready typeobject.c:8206 (libpython3.13t.dylib:arm64+0x17382c)
    #1 PyType_Ready typeobject.c:8266 (libpython3.13t.dylib:arm64+0x16d56c)
    #2 _PyObject_GenericGetAttrWithDict object.c:1655 (libpython3.13t.dylib:arm64+0x120690)
    #3 PyObject_GenericGetAttr object.c:1747 (libpython3.13t.dylib:arm64+0x120570)
    #4 fortran_getattr fortranobject.c:429 (_test_callback_TestF77Callback_ext_module.cpython-313t-darwin.so:arm64+0x9354)
    #5 PyObject_GetOptionalAttrString object.c:1364 (libpython3.13t.dylib:arm64+0x11f1ec)
    #6 PyObject_HasAttrStringWithError object.c:1140 (libpython3.13t.dylib:arm64+0x11ef94)
    #7 PyObject_HasAttrString object.c:1149 (libpython3.13t.dylib:arm64+0x11f488)
    #8 create_cb_arglist _test_callback_TestF77Callback_ext_modulemodule.c:269 (_test_callback_TestF77Callback_ext_module.cpython-313t-darwin.so:arm64+0x69a8)
    #9 f2py_rout__test_callback_TestF77Callback_ext_module_t _test_callback_TestF77Callback_ext_modulemodule.c:1291 (_test_callback_TestF77Callback_ext_module.cpython-313t-darwin.so:arm64+0x4f2c)
    #10 fortran_call fortranobject.c (_test_callback_TestF77Callback_ext_module.cpython-313t-darwin.so:arm64+0x9c84)
    #11 _PyObject_MakeTpCall call.c:242 (libpython3.13t.dylib:arm64+0x7f870)
    #12 PyObject_Vectorcall call.c:327 (libpython3.13t.dylib:arm64+0x804c8)
    #13 _PyEval_EvalFrameDefault generated_cases.c.h:1502 (libpython3.13t.dylib:arm64+0x25f41c)
    #14 _PyEval_Vector ceval.c:1807 (libpython3.13t.dylib:arm64+0x2552cc)
    #15 _PyFunction_Vectorcall call.c (libpython3.13t.dylib:arm64+0x80aa8)
    #16 method_vectorcall classobject.c:70 (libpython3.13t.dylib:arm64+0x84714)
    #17 _PyObject_Call call.c:348 (libpython3.13t.dylib:arm64+0x806ec)
    #18 PyObject_Call call.c:373 (libpython3.13t.dylib:arm64+0x80784)
    #19 thread_run _threadmodule.c:337 (libpython3.13t.dylib:arm64+0x3b6e40)
    #20 pythread_wrapper thread_pthread.h:243 (libpython3.13t.dylib:arm64+0x320c88)

  Location is global 'PyFortran_Type' at 0x000165cbd990 (_test_callback_TestF77Callback_ext_module.cpython-313t-darwin.so+0x15a48)

  Thread T5 (tid=39377788, running) created by main thread at:
    #0 pthread_create <null> (libclang_rt.tsan_osx_dynamic.dylib:arm64+0x31050)
    #1 do_start_joinable_thread thread_pthread.h:290 (libpython3.13t.dylib:arm64+0x31f8f4)
    #2 PyThread_start_joinable_thread thread_pthread.h:314 (libpython3.13t.dylib:arm64+0x31f738)
    #3 do_start_new_thread _threadmodule.c:1849 (libpython3.13t.dylib:arm64+0x3b69ec)
    #4 thread_PyThread_start_joinable_thread _threadmodule.c:1972 (libpython3.13t.dylib:arm64+0x3b5aa8)
    #5 cfunction_call methodobject.c:540 (libpython3.13t.dylib:arm64+0x115600)
    #6 _PyObject_MakeTpCall call.c:242 (libpython3.13t.dylib:arm64+0x7f870)
    #7 PyObject_Vectorcall call.c:327 (libpython3.13t.dylib:arm64+0x804c8)
    #8 _PyEval_EvalFrameDefault generated_cases.c.h:1502 (libpython3.13t.dylib:arm64+0x25f41c)
    #9 _PyEval_Vector ceval.c:1807 (libpython3.13t.dylib:arm64+0x2552cc)
    #10 _PyFunction_Vectorcall call.c (libpython3.13t.dylib:arm64+0x80aa8)
    #11 method_vectorcall classobject.c:70 (libpython3.13t.dylib:arm64+0x84714)
    #12 _PyObject_Call call.c:348 (libpython3.13t.dylib:arm64+0x806ec)
    #13 PyObject_Call call.c:373 (libpython3.13t.dylib:arm64+0x80784)
    #14 _PyEval_EvalFrameDefault generated_cases.c.h:1355 (libpython3.13t.dylib:arm64+0x25fe5c)
    #15 _PyEval_Vector ceval.c:1807 (libpython3.13t.dylib:arm64+0x2552cc)
    #16 _PyFunction_Vectorcall call.c (libpython3.13t.dylib:arm64+0x80aa8)
    #17 _PyObject_VectorcallDictTstate call.c:146 (libpython3.13t.dylib:arm64+0x7f604)
    #18 _PyObject_Call_Prepend call.c:504 (libpython3.13t.dylib:arm64+0x810f0)
    #19 slot_tp_call typeobject.c:9533 (libpython3.13t.dylib:arm64+0x17b194)
    #20 _PyObject_MakeTpCall call.c:242 (libpython3.13t.dylib:arm64+0x7f870)
    #21 PyObject_Vectorcall call.c:327 (libpython3.13t.dylib:arm64+0x804c8)
    #22 _PyEval_EvalFrameDefault generated_cases.c.h:1502 (libpython3.13t.dylib:arm64+0x25f41c)
    #23 _PyEval_Vector ceval.c:1807 (libpython3.13t.dylib:arm64+0x2552cc)
    #24 _PyFunction_Vectorcall call.c (libpython3.13t.dylib:arm64+0x80aa8)
    #25 _PyObject_VectorcallDictTstate call.c:146 (libpython3.13t.dylib:arm64+0x7f604)
    #26 _PyObject_Call_Prepend call.c:504 (libpython3.13t.dylib:arm64+0x810f0)
    #27 slot_tp_call typeobject.c:9533 (libpython3.13t.dylib:arm64+0x17b194)
    #28 _PyObject_Call call.c:361 (libpython3.13t.dylib:arm64+0x80694)
    #29 PyObject_Call call.c:373 (libpython3.13t.dylib:arm64+0x80784)
    #30 _PyEval_EvalFrameDefault generated_cases.c.h:1355 (libpython3.13t.dylib:arm64+0x25fe5c)
    #31 _PyEval_Vector ceval.c:1807 (libpython3.13t.dylib:arm64+0x2552cc)
    #32 _PyFunction_Vectorcall call.c (libpython3.13t.dylib:arm64+0x80aa8)
    #33 _PyObject_VectorcallDictTstate call.c:146 (libpython3.13t.dylib:arm64+0x7f604)
    #34 _PyObject_Call_Prepend call.c:504 (libpython3.13t.dylib:arm64+0x810f0)
    #35 slot_tp_call typeobject.c:9533 (libpython3.13t.dylib:arm64+0x17b194)
    #36 _PyObject_MakeTpCall call.c:242 (libpython3.13t.dylib:arm64+0x7f870)
    #37 PyObject_Vectorcall call.c:327 (libpython3.13t.dylib:arm64+0x804c8)
    #38 _PyEval_EvalFrameDefault generated_cases.c.h:1502 (libpython3.13t.dylib:arm64+0x25f41c)
    #39 _PyEval_Vector ceval.c:1807 (libpython3.13t.dylib:arm64+0x2552cc)
    #40 _PyFunction_Vectorcall call.c (libpython3.13t.dylib:arm64+0x80aa8)
    #41 _PyObject_VectorcallDictTstate call.c:146 (libpython3.13t.dylib:arm64+0x7f604)
    #42 _PyObject_Call_Prepend call.c:504 (libpython3.13t.dylib:arm64+0x810f0)
    #43 slot_tp_call typeobject.c:9533 (libpython3.13t.dylib:arm64+0x17b194)
    #44 _PyObject_MakeTpCall call.c:242 (libpython3.13t.dylib:arm64+0x7f870)
    #45 PyObject_Vectorcall call.c:327 (libpython3.13t.dylib:arm64+0x804c8)
    #46 _PyEval_EvalFrameDefault generated_cases.c.h:1502 (libpython3.13t.dylib:arm64+0x25f41c)
    #47 _PyEval_Vector ceval.c:1807 (libpython3.13t.dylib:arm64+0x2552cc)
    #48 _PyFunction_Vectorcall call.c (libpython3.13t.dylib:arm64+0x80aa8)
    #49 _PyObject_VectorcallDictTstate call.c:146 (libpython3.13t.dylib:arm64+0x7f604)
    #50 _PyObject_Call_Prepend call.c:504 (libpython3.13t.dylib:arm64+0x810f0)
    #51 slot_tp_call typeobject.c:9533 (libpython3.13t.dylib:arm64+0x17b194)
    #52 _PyObject_MakeTpCall call.c:242 (libpython3.13t.dylib:arm64+0x7f870)
    #53 PyObject_Vectorcall call.c:327 (libpython3.13t.dylib:arm64+0x804c8)
    #54 _PyEval_EvalFrameDefault generated_cases.c.h:1502 (libpython3.13t.dylib:arm64+0x25f41c)
    #55 PyEval_EvalCode ceval.c:597 (libpython3.13t.dylib:arm64+0x254fbc)
    #56 builtin_exec bltinmodule.c.h:556 (libpython3.13t.dylib:arm64+0x24f920)
    #57 cfunction_vectorcall_FASTCALL_KEYWORDS methodobject.c:441 (libpython3.13t.dylib:arm64+0x11491c)
    #58 PyObject_Vectorcall call.c:327 (libpython3.13t.dylib:arm64+0x8042c)
    #59 _PyEval_EvalFrameDefault generated_cases.c.h:813 (libpython3.13t.dylib:arm64+0x25e624)
    #60 _PyEval_Vector ceval.c:1807 (libpython3.13t.dylib:arm64+0x2552cc)
    #61 _PyFunction_Vectorcall call.c (libpython3.13t.dylib:arm64+0x80aa8)
    #62 _PyObject_Call call.c:348 (libpython3.13t.dylib:arm64+0x806ec)
    #63 PyObject_Call call.c:373 (libpython3.13t.dylib:arm64+0x80784)
    #64 pymain_run_module main.c:349 (libpython3.13t.dylib:arm64+0x3362a4)
    #65 Py_RunMain main.c:776 (libpython3.13t.dylib:arm64+0x3359a4)
    #66 pymain_main main.c:806 (libpython3.13t.dylib:arm64+0x336040)
    #67 Py_BytesMain main.c:830 (libpython3.13t.dylib:arm64+0x336118)
    #68 main <null> (python3.13:arm64+0x100003ec4)

  Thread T4 (tid=39377787, running) created by main thread at:
    #0 pthread_create <null> (libclang_rt.tsan_osx_dynamic.dylib:arm64+0x31050)
    #1 do_start_joinable_thread thread_pthread.h:290 (libpython3.13t.dylib:arm64+0x31f8f4)
    #2 PyThread_start_joinable_thread thread_pthread.h:314 (libpython3.13t.dylib:arm64+0x31f738)
    #3 do_start_new_thread _threadmodule.c:1849 (libpython3.13t.dylib:arm64+0x3b69ec)
    #4 thread_PyThread_start_joinable_thread _threadmodule.c:1972 (libpython3.13t.dylib:arm64+0x3b5aa8)
    #5 cfunction_call methodobject.c:540 (libpython3.13t.dylib:arm64+0x115600)
    #6 _PyObject_MakeTpCall call.c:242 (libpython3.13t.dylib:arm64+0x7f870)
    #7 PyObject_Vectorcall call.c:327 (libpython3.13t.dylib:arm64+0x804c8)
    #8 _PyEval_EvalFrameDefault generated_cases.c.h:1502 (libpython3.13t.dylib:arm64+0x25f41c)
    #9 _PyEval_Vector ceval.c:1807 (libpython3.13t.dylib:arm64+0x2552cc)
    #10 _PyFunction_Vectorcall call.c (libpython3.13t.dylib:arm64+0x80aa8)
    #11 method_vectorcall classobject.c:70 (libpython3.13t.dylib:arm64+0x84714)
    #12 _PyObject_Call call.c:348 (libpython3.13t.dylib:arm64+0x806ec)
    #13 PyObject_Call call.c:373 (libpython3.13t.dylib:arm64+0x80784)
    #14 _PyEval_EvalFrameDefault generated_cases.c.h:1355 (libpython3.13t.dylib:arm64+0x25fe5c)
    #15 _PyEval_Vector ceval.c:1807 (libpython3.13t.dylib:arm64+0x2552cc)
    #16 _PyFunction_Vectorcall call.c (libpython3.13t.dylib:arm64+0x80aa8)
    #17 _PyObject_VectorcallDictTstate call.c:146 (libpython3.13t.dylib:arm64+0x7f604)
    #18 _PyObject_Call_Prepend call.c:504 (libpython3.13t.dylib:arm64+0x810f0)
    #19 slot_tp_call typeobject.c:9533 (libpython3.13t.dylib:arm64+0x17b194)
    #20 _PyObject_MakeTpCall call.c:242 (libpython3.13t.dylib:arm64+0x7f870)
    #21 PyObject_Vectorcall call.c:327 (libpython3.13t.dylib:arm64+0x804c8)
    #22 _PyEval_EvalFrameDefault generated_cases.c.h:1502 (libpython3.13t.dylib:arm64+0x25f41c)
    #23 _PyEval_Vector ceval.c:1807 (libpython3.13t.dylib:arm64+0x2552cc)
    #24 _PyFunction_Vectorcall call.c (libpython3.13t.dylib:arm64+0x80aa8)
    #25 _PyObject_VectorcallDictTstate call.c:146 (libpython3.13t.dylib:arm64+0x7f604)
    #26 _PyObject_Call_Prepend call.c:504 (libpython3.13t.dylib:arm64+0x810f0)
    #27 slot_tp_call typeobject.c:9533 (libpython3.13t.dylib:arm64+0x17b194)
    #28 _PyObject_Call call.c:361 (libpython3.13t.dylib:arm64+0x80694)
    #29 PyObject_Call call.c:373 (libpython3.13t.dylib:arm64+0x80784)
    #30 _PyEval_EvalFrameDefault generated_cases.c.h:1355 (libpython3.13t.dylib:arm64+0x25fe5c)
    #31 _PyEval_Vector ceval.c:1807 (libpython3.13t.dylib:arm64+0x2552cc)
    #32 _PyFunction_Vectorcall call.c (libpython3.13t.dylib:arm64+0x80aa8)
    #33 _PyObject_VectorcallDictTstate call.c:146 (libpython3.13t.dylib:arm64+0x7f604)
    #34 _PyObject_Call_Prepend call.c:504 (libpython3.13t.dylib:arm64+0x810f0)
    #35 slot_tp_call typeobject.c:9533 (libpython3.13t.dylib:arm64+0x17b194)
    #36 _PyObject_MakeTpCall call.c:242 (libpython3.13t.dylib:arm64+0x7f870)
    #37 PyObject_Vectorcall call.c:327 (libpython3.13t.dylib:arm64+0x804c8)
    #38 _PyEval_EvalFrameDefault generated_cases.c.h:1502 (libpython3.13t.dylib:arm64+0x25f41c)
    #39 _PyEval_Vector ceval.c:1807 (libpython3.13t.dylib:arm64+0x2552cc)
    #40 _PyFunction_Vectorcall call.c (libpython3.13t.dylib:arm64+0x80aa8)
    #41 _PyObject_VectorcallDictTstate call.c:146 (libpython3.13t.dylib:arm64+0x7f604)
    #42 _PyObject_Call_Prepend call.c:504 (libpython3.13t.dylib:arm64+0x810f0)
    #43 slot_tp_call typeobject.c:9533 (libpython3.13t.dylib:arm64+0x17b194)
    #44 _PyObject_MakeTpCall call.c:242 (libpython3.13t.dylib:arm64+0x7f870)
    #45 PyObject_Vectorcall call.c:327 (libpython3.13t.dylib:arm64+0x804c8)
    #46 _PyEval_EvalFrameDefault generated_cases.c.h:1502 (libpython3.13t.dylib:arm64+0x25f41c)
    #47 _PyEval_Vector ceval.c:1807 (libpython3.13t.dylib:arm64+0x2552cc)
    #48 _PyFunction_Vectorcall call.c (libpython3.13t.dylib:arm64+0x80aa8)
    #49 _PyObject_VectorcallDictTstate call.c:146 (libpython3.13t.dylib:arm64+0x7f604)
    #50 _PyObject_Call_Prepend call.c:504 (libpython3.13t.dylib:arm64+0x810f0)
    #51 slot_tp_call typeobject.c:9533 (libpython3.13t.dylib:arm64+0x17b194)
    #52 _PyObject_MakeTpCall call.c:242 (libpython3.13t.dylib:arm64+0x7f870)
    #53 PyObject_Vectorcall call.c:327 (libpython3.13t.dylib:arm64+0x804c8)
    #54 _PyEval_EvalFrameDefault generated_cases.c.h:1502 (libpython3.13t.dylib:arm64+0x25f41c)
    #55 PyEval_EvalCode ceval.c:597 (libpython3.13t.dylib:arm64+0x254fbc)
    #56 builtin_exec bltinmodule.c.h:556 (libpython3.13t.dylib:arm64+0x24f920)
    #57 cfunction_vectorcall_FASTCALL_KEYWORDS methodobject.c:441 (libpython3.13t.dylib:arm64+0x11491c)
    #58 PyObject_Vectorcall call.c:327 (libpython3.13t.dylib:arm64+0x8042c)
    #59 _PyEval_EvalFrameDefault generated_cases.c.h:813 (libpython3.13t.dylib:arm64+0x25e624)
    #60 _PyEval_Vector ceval.c:1807 (libpython3.13t.dylib:arm64+0x2552cc)
    #61 _PyFunction_Vectorcall call.c (libpython3.13t.dylib:arm64+0x80aa8)
    #62 _PyObject_Call call.c:348 (libpython3.13t.dylib:arm64+0x806ec)
    #63 PyObject_Call call.c:373 (libpython3.13t.dylib:arm64+0x80784)
    #64 pymain_run_module main.c:349 (libpython3.13t.dylib:arm64+0x3362a4)
    #65 Py_RunMain main.c:776 (libpython3.13t.dylib:arm64+0x3359a4)
    #66 pymain_main main.c:806 (libpython3.13t.dylib:arm64+0x336040)
    #67 Py_BytesMain main.c:830 (libpython3.13t.dylib:arm64+0x336118)
    #68 main <null> (python3.13:arm64+0x100003ec4)

SUMMARY: ThreadSanitizer: data race call.c:327 in PyObject_Vectorcall

```

</details>

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes https://github.com/numpy/numpy/issues/28041.

Because the reduction initialization happens during ufunc initialization, this means that ufunc initialization now depends on the allocator context variables being initialized, so I moved those initialization steps up before ufunc initialization in the main `_multiarray_umath` module initialization function.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
I'm also relying on the existing tests for reductions to cover this refactor - any suggestions for new tests?

File: numpy/_core/src/umath/legacy_array_method.c [hunk 1]
```diff
@@ -294,24 +294,7 @@ get_initial_from_ufunc(
...
-         * unnecessary convert 0 and 1.)
-         */
-        Py_SETREF(identity_obj, PyObject_CallFunctionObjArgs(
-                     (PyObject *)&PyLongArrType_Type, identity_obj, NULL));
-        if (identity_obj == NULL) {
-            return -1;
-        }
-    }
-    else if (context->descriptors[0]->type_num == NPY_OBJECT
-            && !reduction_is_empty) {
```
Comment (seberg) [inline numpy/_core/src/umath/legacy_array_method.c:314]: Feels like moving this splits things even more maybe.

Maybe we can split this function to take `ufunc` and `descr` only (to avoid `context`, but we can also keep it this way and just abuse a `context`).

Then you can keep this here, and below only call the new function, something like:
```
if (PyTypeNum_ISNUMBER(bound_res->dtypes[0]->type_num)) {
    /* Cache our numerical reduce identity/initial to use `copy_cached_initial` */
    if (get_initial_from_ufunc(ufunc, bound_res->dtypes[0], bound_res->method->legacy_initial) < 0) {
        /* error */
    }
    bound_res->method->get_reduction_initial = &copy_cached_initial;
}
```
(It can already be simplified to write directly into the cache rather than via an allocation.)

About tests: I don't think new tests are needed, initials are well used and there is no subtlety here around default vs. initial.

Comment (ngoldbaum) [reply numpy/_core/src/umath/legacy_array_method.c:314]: > I don't think new tests are needed, initials are well used and there is no subtlety here around default vs. initial.

Thanks for the confirmation and the code suggestions! I think I'll add the multithreaded test case in the issue report, that way this data race has a regression test when I add TSAN CI in a followup.

**Comment by ngoldbaum** [comment]
Refactored to call `get_initial_from_ufunc` during ufunc init, which indeed is a lot simpler and doesn't repeat as much code. There is a bit of extra boilerplate because I needed to heap-allocate a `descrs` array, but that's better than copy/pasting and is pretty straightforward.

Also added a test.

File: numpy/_core/src/umath/legacy_array_method.c [hunk 2]
```diff
@@ -427,11 +420,67 @@ PyArray_NewLegacyWrappingArrayMethod(PyUFuncObject *ufunc,
...
+        char *initial =
+                PyMem_Calloc(1, bound_res->dtypes[0]->singleton->elsize);
+
+        if (initial == NULL) {
+            PyErr_NoMemory();
+            return NULL;
+        }
+
+        PyArray_Descr **descrs = PyMem_Calloc(ufunc->nin + ufunc->nout,
+                                              sizeof(PyArray_Descr *));
```
[the remark this answers is not in the document]
Comment (seberg) [reply numpy/_core/src/umath/legacy_array_method.c:441]: But more importantly.  We only ever use the initial value for reductions.  So I think you might as well hard-code all of this (if you like up to the knowledge that `get_initial_form_ufunc()` only usees `descrs[0]` anyway).

So make `descrs[3]` or just `&singleton`...  (of course only enter the branch if `nin == 2` and `nout == 1`)

File: numpy/_core/src/umath/legacy_array_method.c [hunk 3]
```diff
@@ -427,11 +420,67 @@ PyArray_NewLegacyWrappingArrayMethod(PyUFuncObject *ufunc,
...
+        }
+
+        PyMem_Free(initial);
+        PyMem_Free(descrs);
+    }
+
+
     Py_INCREF(res);
     Py_DECREF(bound_res);
+
```
Comment (seberg) [inline numpy/_core/src/umath/legacy_array_method.c:484]: `bound_res` isn't decref'ed in the errors above.  But once we remove all of the uneeded allocations, at least there is only one error path left.

File: numpy/_core/src/umath/legacy_array_method.c [hunk 4]
```diff
@@ -427,11 +420,67 @@ PyArray_NewLegacyWrappingArrayMethod(PyUFuncObject *ufunc,
...
+            descrs[i] = bound_res->dtypes[i]->singleton;
+        }
+
+        PyArrayMethod_Context context = {
+                (PyObject *)ufunc,
+                bound_res->method,
+                descrs,
+        };
+
+        int ret = get_initial_from_ufunc(&context, 0, initial);
```
[the remark this answers is not in the document]
Comment (seberg) [reply numpy/_core/src/umath/legacy_array_method.c:462]: I think `PyArray_Pack` must support unaligned memory, so I think this is OK.

**Review by seberg — COMMENTED** [review]
Thanks, nice to keep things together.  I still think it would be good to agressively simplify the new code, unless I am missing something?

Nice that you have a threading test!  (I am almost wondering if there is some pytest plugin that would run each tests N times in parallel, or if that could be a fun project... but, we certainly have a few bad test that might not survive that :), although a plugin could use a `pytest.mark` to run them only once)

**Comment by ngoldbaum** [comment]
> I am almost wondering if there is some pytest plugin that would run each tests N times in parallel

There's [pytest-run-parallel](https://github.com/Quansight-Labs/pytest-run-parallel) which SciPy is using heavily. Using it in NumPy may discover some things but I suspect it will mostly detect use of global state in tests and the signal-to-noise ratio may not be great. In particular the Python `warnings` module isn't thread-safe, so for SciPy the majority of the work ended up being skipping tests that use warnings filters - and there are a lot of tests for warnings!

For now I'm just adding one-off multithreaded tests for specific issues as I find them.

Thanks for the review!

**Review by seberg — APPROVED** [review]
Thanks, LGTM to me now, let's put it in.

**Comment by hawkinsp** [comment]
> > I am almost wondering if there is some pytest plugin that would run each tests N times in parallel
> 
> There's [pytest-run-parallel](https://github.com/Quansight-Labs/pytest-run-parallel) which SciPy is using heavily. Using it in NumPy may discover some things but I suspect it will mostly detect use of global state in tests and the signal-to-noise ratio may not be great. In particular the Python `warnings` module isn't thread-safe, so for SciPy the majority of the work ended up being skipping tests that use warnings filters - and there are a lot of tests for warnings!
> 
> For now I'm just adding one-off multithreaded tests for specific issues as I find them.
> 
> Thanks for the review!

There are ways to work around that (e.g. https://github.com/jax-ml/jax/pull/25626/files#diff-10c9477e1279e29626a5bbb8dccc529723495114f796523371741f472fc28e23) if you're sufficiently motivated. But it might be best just to wait for something like https://github.com/python/cpython/pull/128300 to land upstream.
