### PR TITLE
BUG: Fix <complex 0>^{non-zero}

### LINKED ISSUE #18378: Incorrect result when computing 0^{complex number}
```py
>>> (0)**np.array([1-1j])
array([nan+nanj])
>>> (0)**torch.tensor([1-1j])
tensor([0.+0.j])
```

The correct answer here can be worked out by using limits and comes out to be 0 in the case Re(z)> 0, where z is the complex exponent. Please check out this stack exchange answer: https://math.stackexchange.com/questions/2087100/is-zero-to-the-power-of-an-imaginary-number-still-zero which explains this in detail.

### PR DESCRIPTION
**Pull request by prithvitewatia**
The IEEE standard 754 2008 is used in the development of floating-point libraries.  
The 0^0 case is discussed in [Wikipedia](https://en.wikipedia.org/wiki/Zero_to_the_power_of_zero#IEEE_floating-point_standard).
For the case of 0^non-zero, the result is the same as that of C99.  
Side note: C99 for negative real in complex powers generates inf + nan but we are generating nan + nan as  
it is consistent with our previous warning. 
Resolves #18378.

### CODE REVIEW

File: numpy/core/src/npymath/npy_math_complex.c.src [hunk 1]
```diff
@@ -445,28 +445,22 @@ npy_cpow@c@ (@ctype@ a, @ctype@ b)
...
-             * unlike for reals, c0**p, with `p` negative is in general
-             * ill-defined.
-             *
-             *     c0**z with z complex is also ill-defined.
-             */
-            r = npy_cpack@c@(NPY_NAN@C@, NPY_NAN@C@);
-
-            /* Raise invalid */
-            tmp -= NPY_INFINITY@C@;
-            ar = tmp;
```
Comment (eric-wieser) [inline numpy/core/src/npymath/npy_math_complex.c.src:468]: Why did you remove these lines?

Comment (prithvitewatia) [reply numpy/core/src/npymath/npy_math_complex.c.src:468]: @eric-wieser Because this whole section was handling code of complex(0,0) to power complex numbers and negative numbers. Since we are already returning Complex(Nan, Nan)  which is a valid result, I don't think we do not need to raise invalid. Please tell me if I am wrong?

Comment (seberg) [reply numpy/core/src/npymath/npy_math_complex.c.src:468]: If we are producing a new NaN, we need to set/raise invalid. If one of the inputs was already NaN (for complex that is either complex or real part technically), we do _not_ warn/raise.

File: numpy/core/tests/test_umath.py [hunk 2]
```diff
@@ -692,6 +692,25 @@ def assert_complex_equal(x, y):
...
+
+        with np.errstate(invalid="ignore"):
+            #real part and imaginary part both greater than zero
+            assert_complex_equal(np.power(zero,1+4j),zero)
+            #real part greater than zero imag part less than zero
+            assert_complex_equal(np.power(zero,2-3j),zero)
+            #real part less than zero imag part greater than zero
+            assert_complex_equal(np.power(zero,-1+1j),cnan)
+            #real part less than zero imag part less than zero
+            assert_complex_equal(np.power(zero,-2-3j),cnan)
```
Comment (seberg) [inline numpy/core/tests/test_umath.py:712]: Can you split these out and use `pytest.warns()`? That way it is explicitly about which case gives warnings and which does not. (and the test will notify it if it does not work properly due to a change or weird platform)

**Comment by prithvitewatia** [comment]
@eric-wieser @seberg I have made the changes. Please review my pull request.

**Comment by prithvitewatia** [comment]
@eric-wieser  @seberg friendly reminder. I don't mean to bother you but you haven't reviewed my pull request since the last changes. Please take a look.

**Comment by seberg** [comment]
A couple of notes. Sorry, I have to dig into some things or I won't make progress there.  I thin kthis goes in the right direction, but I wonder if we can't simplify the code quite a bit.

1. Could you try to make sure to follow the C and python style guide. I.e. no missing spaces, multi-line comments styled as:
   ```
    /* 
     * Thi sis a multiline
     * comment
     */
   ```
2. Can you check if assuming `#ifdef HAVE_CPOW@C@` is always true is OK? It *should* be, since cpow is part of C99.
3. I am surprised that the integer special case is worthwhile for up to `-100` to `+100`! (side-note) 
4.  It would be cool if we could skip these "corner cases" in the fast-path `if` block and just fall through to the system `cpow` (see point 2.).  Then we don't have to worry about it (although chances are that clang will come around and be buggy...)
5. Don't do warning captures of tests that don't produce warnings, it is unnecessary.  Use `match=` with `pytest.warns` if you want to check the warning message context. It is typically unnecessary to use `with pytest.warns(...) as rec`

**Comment by prithvitewatia** [comment]
@seberg I have checked cpow in C99 and C11 and both are present and working fine. Also could you please explain your third point as I am not able to understand it?

**Comment by seberg** [comment]
Cool, thanks, sorry very briefly. This code block optimizes integer powers:

https://github.com/numpy/numpy/blob/a1572242c9d1a578ce142407fce8d8ddd9e925d7/numpy/core/src/npymath/npy_math_complex.c.src#L470-L506

And the last part optimizes all between -100 and 100, although I can't say I understand the algorithm, so it probably makes sense :).

**Comment by prithvitewatia** [comment]
@seberg  friendly reminder. I have made the changes please take a look.

**Comment by charris** [comment]
close/reopen

**Comment by eric-wieser** [comment]
Can you update the PR description to reference the bit of the IEEE standard that says this is correct behavior?

**Comment by prithvitewatia** [comment]
@eric-wieser I have made the changes. Please take a look.

**Comment by prithvitewatia** [comment]
@seberg friendly reminder. Please review my pull request.

**Comment by prithvitewatia** [comment]
@seberg I apologize for tagging you again and again but you haven't reviewed my pull request. I just wanted to remind you in case it slipped.

**Comment by prithvitewatia** [comment]
@seberg friendly reminder. Please review my Pull request.

File: numpy/core/src/npymath/npy_math_complex.c.src [hunk 3]
```diff
@@ -445,28 +445,26 @@ npy_cpow@c@ (@ctype@ a, @ctype@ b)
...
 
-    if (br == 0. && bi == 0.) {
-        return npy_cpack@c@(1., 0.);
-    }
-    if (ar == 0. && ai == 0.) {
-        if (br > 0 && bi == 0) {
-            return npy_cpack@c@(0., 0.);
+    /*Checking if in a^b, if b is zero.
+    If a is not zero then by definition of logarithm a^0 is one.
+    If a is also zero then as per IEEE 0^0 is best defined as 1.*/
```
Comment (seberg) [inline numpy/core/src/npymath/npy_math_complex.c.src:450]: Can you please fix the comment to conform to NumPy style? (Everywhere)

File: numpy/core/src/npymath/npy_math_complex.c.src [hunk 4]
```diff
@@ -445,28 +445,26 @@ npy_cpow@c@ (@ctype@ a, @ctype@ b)
...
+    if(br == 0. && bi == 0.){
```
Comment (seberg) [inline numpy/core/src/npymath/npy_math_complex.c.src:451]: Space after the `if` and afer ther `)` throughout.

File: numpy/core/src/npymath/npy_math_complex.c.src [hunk 5]
```diff
@@ -445,28 +445,26 @@ npy_cpow@c@ (@ctype@ a, @ctype@ b)
...
+        return npy_cpack@c@(1.,0.);
+    }
+    /*Here it is already tested that for a^b, b is not zero.
+    So we are checking behaviour of a.*/
```
Comment (seberg) [inline numpy/core/src/npymath/npy_math_complex.c.src:455]: I don't think thois comment is necessary?  It might make sense in the "generating an invalid" branch below.

File: numpy/core/src/npymath/npy_math_complex.c.src [hunk 6]
```diff
@@ -445,28 +445,26 @@ npy_cpow@c@ (@ctype@ a, @ctype@ b)
...
+        If not the result is undefined as it blows up or oscillates.*/
+        if(br > 0){
+            return npy_cpack@c@(0.,0.);
         }
-        else {
-            volatile @type@ tmp = NPY_INFINITY@C@;
-            /*
-             * NB: there are four complex zeros; c0 = (+-0, +-0), so that
-             * unlike for reals, c0**p, with `p` negative is in general
-             * ill-defined.
```
Comment (seberg) [inline numpy/core/src/npymath/npy_math_complex.c.src:460]: Ok this NB might point to something I had missed, after removing all our custom handling (lets ignore the warnings there, they may be glibc warning too much):
```
In [39]: np.power(0-0j, 1-1j)
<ipython-input-39-4592e7f77c06>:1: RuntimeWarning: divide by zero encountered in power
  np.power(0-0j, 1-1j)
Out[39]: 0j

In [40]: np.power(0-0j, 1+1j)
<ipython-input-40-a7fd9d0e2031>:1: RuntimeWarning: divide by zero encountered in power
  np.power(0-0j, 1+1j)
Out[40]: -0j
```
i.e. the result actually (subtly) depends on the imaginary part in the branch above.  I expect that is the reason why we had the `bi == 0` check there previously.

File: numpy/core/src/npymath/npy_math_complex.c.src [hunk 7]
```diff
@@ -445,28 +445,26 @@ npy_cpow@c@ (@ctype@ a, @ctype@ b)
...
-
-            /* Raise invalid */
-            tmp -= NPY_INFINITY@C@;
-            ar = tmp;
-            return r;
+        else{
+            //Generating an invalid
+            volatile @type@ tmp=NPY_INFINITY@C@;
+            tmp-=NPY_INFINITY@C@;
+            ar=tmp;
```
Comment (seberg) [inline numpy/core/src/npymath/npy_math_complex.c.src:466]: Please fix the spaces here again, no operators without spaces around them.

**Review by seberg — COMMENTED** [review]
Sorry, I am still confused about the warning flags a bit. And now also about the +0 and -0 dependency, which the (deleted) `NB:` comment allures too.

**Comment by seberg** [comment]
Otherwise, the main thing is that it would be nice if you can clean up the code to adher to NumPy C-style.

File: numpy/core/src/npymath/npy_math_complex.c.src (hunk 5 above)
Comment (prithvitewatia) [reply numpy/core/src/npymath/npy_math_complex.c.src:455]: @seberg Could you please explain what do you mean by generating an invalid as I am not able to understand it

File: numpy/core/src/npymath/npy_math_complex.c.src (hunk 6 above)
Comment (prithvitewatia) [reply numpy/core/src/npymath/npy_math_complex.c.src:460]: @seberg The check for bi==0 is already in place with br==0 just like before. (Line 448 in original file and Line 451 in pull request file)

Comment (seberg) [reply numpy/core/src/npymath/npy_math_complex.c.src:460]: No, there is no check for `bi == 0` when `br != 0`.  If `br > 0` and `bi != 0` the sign of the result can still change, as my example shows I think. Even though the value is always 0.

The old NB comment tries to point that out.  I don't know what should happen exactly, but if we delete that comment (confusing as it is), we should either get the signs right or replace it with an arguement that it is OK to get the sign wrong because of XY.

File: numpy/core/src/npymath/npy_math_complex.c.src (hunk 5 above)
Comment (seberg) [reply numpy/core/src/npymath/npy_math_complex.c.src:455]: I mean moving it down to the branch where you return NaN manually.  Maybe its a bit of a code layout thing in the diff, but I think that branch is the place where you may want to point out that `0^0` is already handled.

Comment (prithvitewatia) [reply numpy/core/src/npymath/npy_math_complex.c.src:455]: All right got it. Thanks

File: numpy/core/src/npymath/npy_math_complex.c.src (hunk 6 above)
Comment (prithvitewatia) [reply numpy/core/src/npymath/npy_math_complex.c.src:460]: @seberg I need to check if it is ok to get signs wrong or what can be done to make the signs right. I might need some time though.

Comment (seberg) [reply numpy/core/src/npymath/npy_math_complex.c.src:460]: Thanks, its complicated :(, I wish it was easier to get this stuff right...

File: numpy/core/src/npymath/npy_math_complex.c.src (hunk 7 above)
Comment (prithvitewatia) [reply numpy/core/src/npymath/npy_math_complex.c.src:466]: @seberg Here is what I found.  
The first section discusses how the complex exponentiation is done.  
Second section deals with the sign.  

**Complex Exponentiation**
If z and w are two complex numbers then  
z^w = e^{w*(ln|z|+i\*arg(z} \*e^{i\*w\*(2\*n\*pi)}
which means that z^w is multivalued. We call the value at ```n=0``` the principle value.  
Now, here I will discuss the case of 0^{non-zero complex number} which is related to our issue.  
0^w = e^{w \* (ln(0) + i\*arg(0,0))}\*e^{ i\*w\*(2\*n *pi)}  
Lets call this equation 1.  
Now arg is calculated with the help of atan2. Mathematically undefined but is realized in computer languages.
As we are considering C language, for unsigned 0, we get the output as 0. For signed numbers, we get the
output 0, pi, -0, -pi. This is demonstrated with the following C program.  

```C
#include<stdio.h>
#include<math.h>

int main(){
    double a=atan2(0,0);
    double b=atan2(+0.0,+0.0);
    double c=atan2(+0.0,-0.0);
    double d=atan2(-0.0,+0.0);
    double e=atan2(-0.0,-0.0);
    printf("%lf\n%lf\n%lf\n%lf\n%lf\n",a,b,c,d,e);
    return 0;
}
```

Output  
```
0.000000
0.000000
3.141593
-0.000000
-3.141593
```
Therefore e^{i\*arg(0,0)} will be +1 or -1 depending upon values of ar and ai (0 but still signed).  
Now, let's spilt equation 1 into three parts.  
Part 1: e^{ w\*ln|0| } (ln|0| = -inf)  
Part 2: e^{ i\*arg(0,0) }= ±1  
Part 3: e^{ i\*w*(2n*pi)}  
For complex number w , we get 4 cases
br = 0, bi != 0  
br != 0, bi = 0
br = 0, bi != 0
br != 0, bi != 0  
The case for br=0 and bi=0 leads to 0^0 which is defined to be 1 by IEEE.  
For case br != 0, bi = 0, we have
```
    if br > 0 we have
        Part 1= e^{ br* -inf }= 0
        Part2 = ±1 (actual sign depending on signs of ar and ai)
        Part3 = dont care 
        Result = ±0
    if br < 0  we have 
        Part 1= e^{ br*-inf }= inf
        Part 2= ±1 
        Part 3= oscillates between positive and negative value
        Therefore this leads to indeterminate form of inf*0 and
        the result is undefined . (This might also expalin why C 
        generates (inf,nan) as its output when encountered with 
        such values. In our case we generate (nan,nan).
```
For br = 0, bi != 0  
```
    if bi > 0
        Part 1: e^{ i*bi*-inf}
        which can be written as
        cos(bi*-inf)+isin(bi*-inf)
        which is undefined.
        Part 2: don't care
        Part 3: don't care
        Result: undefined
    if bi < 0
        Same as above because this time we get
        +inf instead of minus inf.
```
For br !=0 and bi != 0  
```
    Part 1: e^{ w * -inf}
    =e^{br*-inf} * e^{i*bi*-inf} (w=br + i*bi)
    Therefore if br > 0 this goes down to 0
    if not, the result oscillates and is undifined.
    Part 2 and 3 are dont care.
```
All the cases are summarized in the table below  
|      | bi < 0 | bi = 0 | bi > 0 |
|------|--------|--------|--------|
|br < 0|  undef |  undef |  undef |
|br = 0|  undef |    1   |  undef |
|br > 0|    0   |    0   |    0   |  

        Value of 0 ^ {complex}
Note: 0s are signed.

Combining with the complex exponentiation table  
|                   | exp = 0 |  exp = non-zero |
|-------------------|---------|-----------------|
|mantissa = 0       |    1    |    Table above  |
|mantissa = non-zero|    1    | Already handled |

**As we learned that complex exponentiation is multi-valued and the actual**
**signs depend on many factors such as signs of ar and ai and whether the API**
**is selecting principle value or not. Also 0+0i, 0-0i,-0+0i and -0-0i correspond**
**to the same point on the complex plane. So as long the result is 0 it mathematically**
**does not affect the result**  

I am ready to go with whatever you suggest. If you suggest going with signs (the resulting 0 contains sign opposite of bi as the C program below shows.)
I will make changes in the code accordingly. If you say its fine just make the code according to numpy C style I will do that.
```C
#include<stdio.h>
#include<math.h>
#include<complex.h>

int main(){
    complex mantissa[]={ 0.0+0.0*I, 0.0-0.0*I, -0.0+0.0*I, -0.0-0.0*I};
    complex exponents[]={1.0+1.0*I, 1.0-1.0*I, -1.0+1.0*I, -1.0-1.0*I};
    for(int i=0;i<4;i++){
        for(int j=0;j<4;j++){
            complex c=cpow(mantissa[i],exponents[j]);
            printf("%lf + %lf *I\n",creal(c),cimag(c));
        }
    }
    return 0;
}
```
Output:
```
0.000000 + -0.000000 *I
0.000000 + 0.000000 *I
inf + -nan *I
inf + -nan *I
0.000000 + -0.000000 *I
0.000000 + 0.000000 *I
inf + -nan *I
inf + -nan *I
0.000000 + -0.000000 *I
0.000000 + 0.000000 *I
inf + -nan *I
inf + -nan *I
0.000000 + -0.000000 *I
0.000000 + 0.000000 *I
inf + -nan *I
inf + -nan *I
```
**References:**
[Complex Eponentiation](https://brilliant.org/wiki/complex-exponentiation/#:~:text=Complex%20exponentiation%20extends%20the%20notion,y%20is%20a%20complex%20number.)  
[atan2](https://en.wikipedia.org/wiki/Atan2#Realizations_of_the_function_in_common_computer_languages)

Comment (seberg) [reply numpy/core/src/npymath/npy_math_complex.c.src:466]: Sorry for taking a while to respond.  That anlysis sounds great, and `atan2` is a seems like a very good "basis" to make a decision of here I think, thanks!  (I have not followed every step, I admit)

My feeling is that we should try to preserve the signs for the 0 return.  And the fact that GCC gives a floating point warnings seems like a small issue in glibc?  After all, `atan2` makes a point of getting this right as well.  Also the old code-comment to me reads like: Let's return NaN, because the sign means that returning 0 would not be quite right.

So my personal judgment would be: return the correct sign here, in the special case!  And IIRC the rest already looked good.  I double checked the C99 standard, but could not find anything relevant (the `cpow` documentation is pretty much a stub).

I think we should open an issue on gcc/glibc about the warning flags being set for those signed 0 returns.  In the best case scenario we learn something new. In the other best case scenario glibc stops giving spurious warnings ;).

Comment (seberg) [reply numpy/core/src/npymath/npy_math_complex.c.src:466]: Ah GLIBC issue of course, I have opened a bug report, hopefully in the right place here: https://sourceware.org/bugzilla/show_bug.cgi?id=27875

**Comment by prithvitewatia** [comment]
@seberg Friendly reminder. I have made the changes. Please review my Pull request.

File: numpy/core/src/npymath/npy_math_complex.c.src [hunk 8]
```diff
@@ -445,29 +445,46 @@ npy_cpow@c@ (@ctype@ a, @ctype@ b)
...
+     * br and bi. The result is either 0 (in magnitude) or 
+     * undefined ( or 1 for br=bi=0 and independent of ar and ai
+     * but that case is handled above).
+     */
+    else if (ar == 0. && ai == 0.) {
+        /* If br > 0 then result is 0 but contains sign opposite
+         * of bi.
+         * Else the result is undefined and we return (nan,nan)
+         */
+         if ( br > 0) {
```
Comment (seberg) [inline numpy/core/src/npymath/npy_math_complex.c.src:467]:
```suggestion
         if (br > 0) {
```

File: numpy/core/src/npymath/npy_math_complex.c.src [hunk 9]
```diff
@@ -445,29 +445,46 @@ npy_cpow@c@ (@ctype@ a, @ctype@ b)
...
-            return r;
-        }
+    /*
+     * If mantissa is zero, then result depends upon values of 
+     * br and bi. The result is either 0 (in magnitude) or 
+     * undefined ( or 1 for br=bi=0 and independent of ar and ai
+     * but that case is handled above).
+     */
+    else if (ar == 0. && ai == 0.) {
+        /* If br > 0 then result is 0 but contains sign opposite
```
Comment (seberg) [inline numpy/core/src/npymath/npy_math_complex.c.src:463]:
```suggestion
        /* 
         * If br > 0 then result is 0 but contains sign opposite
```

File: numpy/core/tests/test_umath.py [hunk 10]
```diff
@@ -701,6 +701,31 @@ def assert_complex_equal(x, y):
...
+        #Complex powers with positive real part will not generate a warning
+        assert_complex_equal(np.power(zero, 1+4j), zero)
+        assert_complex_equal(np.power(zero, 2-3j), zero)
+        #Testing zero values when real part is greater than zero
+        assert_complex_equal(np.power(zero, 1+1j), -zero)
+        assert_complex_equal(np.power(zero, 1+0j), -zero)
+        assert_complex_equal(np.power(zero, 1-1j), zero)
+        #Complex powers will negative real part or 0 (provided imaginary 
+        # part is not zero) will generate a NAN and hence a RUNTIME warning
+        with pytest.warns(expected_warning=RuntimeWarning):
```
Comment (seberg) [inline numpy/core/tests/test_umath.py:722]: This one should be either repeated every time (alternatively, make it a `pytest.mark.parameterize`).  Of you need to add `as r` or so, and then check the number of warnings.  Otherwise, we only test that at least one of these warned.

File: numpy/core/src/npymath/npy_math_complex.c.src [hunk 11]
```diff
@@ -445,29 +445,46 @@ npy_cpow@c@ (@ctype@ a, @ctype@ b)
...
+         * Else the result is undefined and we return (nan,nan)
+         */
+         if ( br > 0) {
+             if (bi < 0) {
+                 return npy_cpack@c@(0., 0.);
+             }
+             else {
+                 return npy_cpack@c@(0., -0.);
+             }
+
```
Comment (seberg) [inline numpy/core/src/npymath/npy_math_complex.c.src:474]:
```suggestion
```

**Review by seberg — COMMENTED** [review]
Just some nits and the tightening the tests. Otherwise, I think this is good to go in. Thanks!

File: numpy/core/tests/test_umath.py (hunk 10 above)
Comment (prithvitewatia) [reply numpy/core/tests/test_umath.py:795]: @seberg I am sorry but I am not able to understand your line ``` Of you need to add as r```. Did you mean in line 772 I add 
```python
with pytest.warns(expected_warning=RuntimeWarning) as r:
    # run all my tests here
#check all warnings by using len(r) == number of tests written above.
```

File: numpy/core/src/npymath/npy_math_complex.c.src (hunk 11 above)
Comment (prithvitewatia) [reply numpy/core/src/npymath/npy_math_complex.c.src:475]: @seberg I have made the changes please review my pull request.

**Review by seberg — APPROVED** [review]
Thanks, looks good to me now.  I am considering if we should add a release note, but in general, I think it can go in as-is.

**Comment by seberg** [comment]
You have to add a brief `rst` file to `doc/release/upcoming_changes`.  The `README.txt` lists the categories.   Probably be an `improvement` or `compatibility` if you think users might actually notice.  (There is currently only one example because 1.21 was just branched.)

**Comment by prithvitewatia** [comment]
@seberg Please review the release note. Thanks 😄

**Comment by prithvitewatia** [comment]
@seberg Thanks for enhancing the release note 😄 . I also thought of adding this note but then thought this is documentation related so I didn't add added it in the release note. 
I am sorry I also missed that we are not checking at negative zero in the inputs. I think that all the tests should be done for four cases of zero input in the mantissa { (0., 0.), (0.,-0.),(-0.,0.),(-0.,-0.) }.
I will fix these issues in the next commit.
Also, I will check for -0. using ```np.signbit```.
Many thanks for reminding me 🤝 .

**Comment by prithvitewatia** [comment]
@seberg While trying to fix the issues mentioned I found something.
```python
>>>import numpy as np
>>>zeros = np.array([0.0+0.0j,0.0-0.0j,-0.0+0.0j,-0.0-0.0j])
>>>zeros
array([ 0.+0.j,  0.+0.j,  0.+0.j, -0.+0.j])
>>>check_zero = np.array([0.0j])
>>>for zero in zeros:
    if zero != check_zero:
        print(zero)
        
>>>
```
It prints nothing which means we don't need to explicitly check for -0. Please tell me if I am wrong somewhere.  

-------
For the sign checking the case of returned zero ```np.signbit``` does not support complex arguments. It gives the following error. 
```
>>> np.signbit(np.array([0.0j]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ufunc 'signbit' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
It even does not work for this.
```
>>> np.signbit(0.0j)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ufunc 'signbit' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
Also, since -zero == np.array([-0.0j]) is True I think we can be pretty sure that that returned sign returned is correct. So I think the code does not require any changes. 😃

**Comment by prithvitewatia** [comment]
@seberg @eric-wieser could you please merge my pull request.

File: doc/release/upcoming_changes/18535.improvement.rst [hunk 12]
```diff
@@ -0,0 +1,8 @@
+Fix power of complex zero
+-------------------------
+``np.power`` now returns the correct result for ``0^{non-zero}``
```
Comment (mattip) [inline doc/release/upcoming_changes/18535.improvement.rst:3]: Hmm, does this now exceed 80 columns?
```suggestion
``np.power`` now returns a IEEE 754-compliant result for ``0^{non-zero}``
```

File: doc/release/upcoming_changes/18535.improvement.rst [hunk 13]
```diff
@@ -0,0 +1,8 @@
...
+for complex numbers.  Note that the value is only defined when
+the real part of the exponent is larger than zero.
+Previously, NaN was returned unless the imaginary part was strictly
+zero.  Now the correct zero value is returned, with the sign bit
```
Comment (mattip) [inline doc/release/upcoming_changes/18535.improvement.rst:7]:
```suggestion
zero.  Now a zero value is returned, with the sign bit
```

**Comment by mattip** [comment]
Just a nit about "correct" vs "standards compliant", feel free to ignore if you disagree.

File: doc/release/upcoming_changes/18535.improvement.rst (hunk 12 above)
Comment (seberg) [reply doc/release/upcoming_changes/18535.improvement.rst:3]: I wish I had the reference to check that IEEE even says it explicitly (for complex power, not for normal power).  I do know that the C99 bails on `cpow` (at least for warnings), because it is so complicated...

**Comment by charris** [comment]
Is everyone happy with this?

**Comment by seberg** [comment]
Sorry, I lost track on this, I have to look at it with some leisure and fresh eyes.

**Comment by charris** [comment]
@seberg Is this an improvement?

**Comment by seberg** [comment]
Yeah, I would call it an enhancement more than a bug fix, considering that most C math library implementations don't seem to standardize it.

**Comment by prithvitewatia** [comment]
@seberg Could you please tell me why you have shifted this from the 1.22 release milestone to the 1.23 release milestone?

**Comment by mattip** [comment]
In the triage meeting we discussed this. There is no real consensus what the "correct" answer should be. If someone could confirm that IEEE 754-2019 actually provides a clear answer that would be helpful.

**Comment by scratchmex** [comment]
I would like to add some parts of [754-2019 - IEEE Standard for Floating-Point Arithmetic](https://ieeexplore.ieee.org/document/8766229) for reference.

image


image

**Comment by scratchmex** [comment]
> @seberg Thanks for enhancing the release note 😄 . I also thought of adding this note but then thought this is documentation related so I didn't add added it in the release note. I am sorry I also missed that we are not checking at negative zero in the inputs. I think that all the tests should be done for four cases of zero input in the mantissa { (0., 0.), (0.,-0.),(-0.,0.),(-0.,-0.) }. I will fix these issues in the next commit. Also, I will check for -0. using `np.signbit`. Many thanks for reminding me 🤝 .

You can apply `np.signbit` to `a.real` or `a.imag`. The complex does not have signs.

**Comment by scratchmex** [comment]
The general expression for  is



For `a<=0` the result should be a nan complex `nan +nan j` as said [here](https://math.stackexchange.com/questions/2087100/is-zero-to-the-power-of-an-imaginary-number-still-zero/4297912) by taking the limit. This is because  is not defined (have multiple values) for `a<0`. For `a=0` it is also not defined but it is useful computationally to think it as 1. The problem with that is that  is also not defined (multiples values) so we use `nan` in this case.

When `a>0`, the real and imaginary part approaches zero in an oscillating way, that is because of the `sin` and `cos`. In that regard, the sign of the zero cannot be determined so we need to impose some convention. My suggestion is to keep the positive sign regardless of the sign of `b`. That is mimicking the following example where we cannot determine the sign either but they keep it as being positive.

image

Being said that, I consider the following table should be implemented:

| | a<=0 | a>0 |
| --- | --- | --- |
|  | `nan + nan j` | `0 + 0 j`

File: numpy/core/src/npymath/npy_math_complex.c.src [hunk 14]
```diff
@@ -445,29 +445,48 @@ npy_cpow@c@ (@ctype@ a, @ctype@ b)
...
+              * (nan, nan)
+              */
+              volatile @type@ tmp = NPY_INFINITY@C@;
+              r = npy_cpack@c@(NPY_NAN@C@, NPY_NAN@C@);
+
+              /* Raise invalid */
+              tmp -= NPY_INFINITY@C@;
+              ar = tmp;
+              return r;
+         }
```
Comment (scratchmex) [inline numpy/core/src/npymath/npy_math_complex.c.src:489]:
```suggestion
        /* else we are in the case where the
         * real part of b is negative (br<0).
         * Here we should return a complex nan
         * and raise FloatingPointError: invalid value...
         */
         
         /* Raise invalid value by calling inf - inf*/
          volatile @type@ tmp = NPY_INFINITY@C@;
          tmp -= NPY_INFINITY@C@;
          ar = tmp;
          
          r = npy_cpack@c@(NPY_NAN@C@, NPY_NAN@C@);
          return r;
```

Comment (scratchmex) [reply numpy/core/src/npymath/npy_math_complex.c.src:489]: I am not familiarized with the internals that much. I have some questions

- why do we need `inf` to be `volatile`?
- why do we need to save the `inf-inf` value to `ar`?

File: numpy/core/tests/test_umath.py [hunk 15]
```diff
@@ -789,6 +789,32 @@ def assert_complex_equal(x, y):
                 assert_complex_equal(np.power(zero, -p), cnan)
             assert_complex_equal(np.power(zero, -1+0.2j), cnan)
 
+    # Testing 0^{Non-zero} issue 18378
+    def test_zero_power_nonzero(self):
+        zero = np.array([0.0j])
```
Comment (scratchmex) [inline numpy/core/tests/test_umath.py:794]:
```suggestion
        zero = np.array([0.0+0.0j])
```

File: numpy/core/tests/test_umath.py [hunk 16]
```diff
@@ -789,6 +789,32 @@ def assert_complex_equal(x, y):
                 assert_complex_equal(np.power(zero, -p), cnan)
             assert_complex_equal(np.power(zero, -1+0.2j), cnan)
 
+    # Testing 0^{Non-zero} issue 18378
+    def test_zero_power_nonzero(self):
```
Comment (scratchmex) [inline numpy/core/tests/test_umath.py:793]: this test should be merged with the latter because the latter also is related to testing powers of zeros and actually test some cases of the type nan

File: numpy/core/tests/test_umath.py [hunk 17]
```diff
@@ -789,6 +789,32 @@ def assert_complex_equal(x, y):
...
+        def assert_complex_equal(x, y):
+            assert_array_equal(x.real, y.real)
+            assert_array_equal(x.imag, y.imag)
+
+        #Complex powers with positive real part will not generate a warning
+        assert_complex_equal(np.power(zero, 1+4j), zero)
+        assert_complex_equal(np.power(zero, 2-3j), zero)
+        #Testing zero values when real part is greater than zero
+        assert_complex_equal(np.power(zero, 1+1j), -zero)
+        assert_complex_equal(np.power(zero, 1+0j), -zero)
```
Comment (scratchmex) [inline numpy/core/tests/test_umath.py:806]:
```suggestion
        assert_complex_equal(np.power(zero, 1+1j), zero)
        assert_complex_equal(np.power(zero, 1+0j), zero)
```

**Review by scratchmex — COMMENTED** [review]
Here are my humble comments.

File: numpy/core/tests/test_umath.py (hunk 17 above)
Comment (prithvitewatia) [reply numpy/core/tests/test_umath.py:806]: @scratchmex Thank you for the comments. If maintainers agree to make these changes then I can add another commit applying those changes. 😄

Comment (scratchmex) [reply numpy/core/tests/test_umath.py:806]: @seberg ping

**Comment by mattip** [comment]
@seberg care to take another look? I think we should try to get this in soon

File: numpy/core/src/npymath/npy_math_complex.c.src (hunk 14 above)
Comment (mattip) [reply numpy/core/src/npymath/npy_math_complex.c.src:490]: @prithvitewatia do you have an answer?

File: numpy/core/tests/test_umath.py (hunk 15 above)
Comment (mattip) [reply numpy/core/tests/test_umath.py:794]: @scratchmex I think this is better the way it was originally

File: numpy/core/tests/test_umath.py (hunk 17 above)
Comment (mattip) [reply numpy/core/tests/test_umath.py:806]: @prithvitewatia I committed some of the changes, others are waiting for responses. Please refactor or comment.

File: numpy/core/src/npymath/npy_math_complex.c.src (hunk 14 above)
Comment (seberg) [reply numpy/core/src/npymath/npy_math_complex.c.src:490]: The `inf - inf` and the volatile is reasonable, although I am not sure it is the best way to spell it.  Maybe we should just use `npy_set_floatstatus_invalid()`, since that is clearer.  The volatile would prevent the compiler from doing the calculation at compile time, which would remove the floating pointer error flags.

The reason that for me this is hard to pick up, is that I think, the branch-cuts were right in the last version with `-0` or not, but I have never seen an IEEE or C standard for *complex* (rather than real) numbers.  So, we have to make a call here and it would be nice to have a second reference somewhere to make that call.

**Comment by charris** [comment]
close/reopen

**Comment by charris** [comment]
I think we can ignore the circleci failure, should go away on merge.  Everyone OK with merging this?

**Comment by prithvitewatia** [comment]
> I think we can ignore the circleci failure, should go away on merge. Everyone OK with merging this?

Yes 😄 .

**Comment by mattip** [comment]
There is an open request for changes and an open question about how sure we are that the result is compliant with a known standard. I think this is the root of the problem:
> I have never seen an IEEE or C standard for complex (rather than real) numbers. So, we have to make a call here and it would be nice to have a second reference somewhere to make that call.

Is there a reference from a standard or from some other programming language (not just from a wiki page)?

**Comment by leofang** [comment]
Isn't there a std::complex in C++...?

**Comment by seberg** [comment]
OK, lets not worry about the exact branch-cut.  The fact is C99 doesn't seem to standardize that cut clearly, most implementation do return `1+0j`.

> Isn't there a std::complex in C++...?

yes, but it doesn't really detail the behaviour all that clearly here, it even specifically bails and allows giving incorrect FPE warnings IIRC.

**Comment by charris** [comment]
This is the only outstanding issue for 1.13.0. Where do we stand?

**Comment by mattip** [comment]
@prithvitewatia has not responded to requests for changes.

**Comment by prithvitewatia** [comment]
> @prithvitewatia has not responded to requests for changes.

@mattip I am sorry, I missed your earlier comments and saw them just now. Since this is a busy week for me as I have my university exams could you all please wait till the weekend. I will try to make changes as soon as possible.

**Comment by charris** [comment]
I am just going to branch without worrying about this, It goes in when it goes in :)

**Comment by charris** [comment]
The circleci problem should go away when merged or rebased. @prithvitewatia gentle ping.

**Comment by prithvitewatia** [comment]
> The circleci problem should go away when merged or rebased. @prithvitewatia gentle ping.

Hi @charris, sorry for the delay. I've committed the suggestions and rebased with the latest main now.

**Comment by charris** [comment]
@seberg Are you good with this?

**Comment by seberg** [comment]
Sorry, I am burned on this.  I would like someone else to make up their mind carefully and then, yes I am happy.  But I am not Kahan and all standards I am aware of bail on this beyond saying `cexp(c*clog(x))` is an acceptable implementation (meaning that e.g. warnings are allowed to be off in these corner cases).
Right now, the status is that we do not return `0-0j` (signed zeros) unlike a previous version.  The release note seems to still refer to the previous version.

**Comment by charris** [comment]
> I am burned on this.

Sorry :)  I just wanted to get it off the 1.24 checklist, and away it goes.

File: doc/release/upcoming_changes/18535.improvement.rst [hunk 18]
```diff
@@ -0,0 +1,8 @@
+Fix power of complex zero
+-------------------------
+``np.power`` now returns a IEEE 754-compliant result for ``0^{non-zero}``
```
Comment (mattip) [inline doc/release/upcoming_changes/18535.improvement.rst:3]:
```suggestion
``np.power`` now returns a different result for ``0^{non-zero}``
```

File: doc/release/upcoming_changes/18535.improvement.rst [hunk 19]
```diff
@@ -0,0 +1,8 @@
...
+for complex numbers.  Note that the value is only defined when
+the real part of the exponent is larger than zero.
+Previously, NaN was returned unless the imaginary part was strictly
+zero.  Now a zero value is returned, with the sign bit
+set.  The return value is either ``0+0j`` or ``0-0j``.
```
Comment (mattip) [inline doc/release/upcoming_changes/18535.improvement.rst:8]:
```suggestion
zero.  The return value is either ``0+0j`` or ``0-0j``.
```

File: numpy/core/src/npymath/npy_math_complex.c.src [hunk 20]
```diff
@@ -445,29 +445,43 @@ npy_cpow@c@ (@ctype@ a, @ctype@ b)
     @type@ bi = npy_cimag@c@(b);
     @ctype@ r;
 
+    /*
+     * Checking if in a^b, if b is zero.
+     * If a is not zero then by definition of logarithm a^0 is 1.
+     * If a is also zero then as per IEEE 754 0^0 is best defined as 1.
```
Comment (mattip) [inline numpy/core/src/npymath/npy_math_complex.c.src:451]:
```suggestion
     * If a is also zero then 0^0 is best defined as 1.
```

**Comment by prithvitewatia** [comment]
@mattip gentle ping. I have updated the PR according to changes suggested. Please take a look.

**Comment by mattip** [comment]
Thanks @prithvitewatia
