### PR TITLE
BUG: Fixes #7395, operator.index now fails on numpy.bool_

### LINKED ISSUE #7395: np.bool_.__index__ should error
`operator.index` correctly raises an error on boolean arrays:

```
In [6]: operator.index(np.array(True))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-a4163d1794ac> in <module>()
----> 1 operator.index(np.array(True))

TypeError: only integer arrays with one element can be converted to an index
```

But on a boolean scalar, it incorrectly succeeds:

```
In [7]: operator.index(np.bool_(True))
Out[7]: 1
```

The latter should be an error (possibly with some deprecation period).

### PR DESCRIPTION
**Pull request by eric-wieser**
Rebase of @emilienkofman's #7420, along with added test and release notes. The description from there is

> Attempt to fix the bug described in #7395. If this needs a depreciation warning I can change the Err to Warning and maybe add a test (?)

### CODE REVIEW

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 1]
```diff
@@ -2843,7 +2843,9 @@ static PyNumberMethods @name@_arrtype_as_number;
 static PyObject *
 bool_index(PyObject *a)
 {
-    return PyInt_FromLong(PyArrayScalar_VAL(a, Bool));
+    PyErr_SetString(PyExc_TypeError,
```
Comment (mhvk) [inline numpy/core/src/multiarray/scalartypes.c.src]: Instead of raising an error here, isn't it easier to remove this whole definition and not define (or explicitly set to `NULL`; not sure) `PyBoolArrType_Type.tp_as_number->nb_index`? (it is currently defined in L4114).

**Review by mhvk — COMMENTED** [review]
Wondering about the one comment; less code is better...

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 1 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/scalartypes.c.src]: Yeah, good catch

**Comment by eric-wieser** [comment]
@mhvk: Addressed. Does this want a deprecation cycle? We already hit `operator.index(array(True))` in a previous release

**Comment by seberg** [comment]
Unless this is a big bug somewhere, the default should be to go through the deprecation I think.

**Comment by eric-wieser** [comment]
@seberg: Changed to a deprecation

**Comment by charris** [comment]
Fixed merge conflict and merged. Thanks Eric.
