### PR TITLE
BUG: ``PyDataMem_SetHandler`` check capsule name

### LINKED ISSUE #26137: ENH: `PyDataMem_SetHandler` should check whether the capsule is valid
The capsule must be named `mem_handler` (or nothing will work), but that is not checked at registration time.

It would be good to check at registration time to help users who accidentally misname it (I.e. me ;)).

### PR DESCRIPTION
**Pull request by luxedo**
Closes https://github.com/numpy/numpy/issues/26137.

Tests capsule name and sets `PyErr` if not valid:
```c
    if (!PyCapsule_IsValid(handler, MEM_HANDLER_CAPSULE_NAME)) {
        PyErr_SetString(PyExc_ValueError, "Capsule must be named 'mem_handler'")
        return NULL;
    }
```

### CODE REVIEW

**Comment by luxedo** [comment]
WIP

Got wrong capsule name in tests:
image

**Comment by seberg** [comment]
If you look at what is failing, you should find that it is failing when `SetHandler` is called with `handler=NULL`.

**Comment by luxedo** [comment]
I placed the mem_handler check after the null check and all the tests pass now

**Comment by seberg** [comment]
LGTM, adding that constant seems fine also (it's used in at least one more place, but OK).  Would you be up for adding a test?  The memory handler tests should be easy to expand to do that I suspect and it's nice to add one, if just to cover the code.

**Comment by luxedo** [comment]
I have made a few changes given your last feedback:
1. Add `MEM_HANDLER_CAPSULE_NAME` to the header file as a `#define` following the other example in `npy_dlpack`: https://github.com/numpy/numpy/blob/da5a7797265f74405670a11f2b0d4ff01e2ee380/numpy/_core/src/common/npy_dlpack.h#L8
2. Rename `"mem_handler"` to `MEM_HANDLER_CAPSULE_NAME` in `multiarraymodule.c`.
3. Add `"mem_handler"` check branch test

File: numpy/_core/src/multiarray/alloc.c [hunk 1]
```diff
@@ -427,6 +431,10 @@ PyDataMem_SetHandler(PyObject *handler)
     if (handler == NULL) {
         handler = PyDataMem_DefaultHandler;
     }
+    if (!PyCapsule_IsValid(handler, MEM_HANDLER_CAPSULE_NAME)) {
+        PyErr_SetString(PyExc_ValueError, "Capsule must be named 'mem_handler'");
```
Comment (luxedo) [inline numpy/_core/src/multiarray/alloc.c:435]: Does it make sense to throw this exception? This will only run under the hood right?

If it doesn't make sense, what's the appropriate way to handle this?

P.S: This is my first time reading numpy's C code.

File: numpy/_core/tests/test_mem_policy.py [hunk 2]
```diff
@@ -46,6 +46,16 @@ def get_module(tmp_path):
              Py_DECREF(secret_data);
              return old;
          """),
+        ("set_wrong_capsule_name_data_policy", "METH_NOARGS", """
+             PyObject *secret_data =
```
Comment (luxedo) [inline numpy/_core/tests/test_mem_policy.py:50]: I used the same `struct` for the secret_data_policy. Is this ok or should I create a struct just for this test?

Comment (seberg) [inline numpy/_core/tests/test_mem_policy.py:50]:
```suggestion
             PyObject *wrong_name_capsule =
```

File: numpy/_core/tests/test_mem_policy.py [hunk 3]
```diff
@@ -46,6 +46,16 @@ def get_module(tmp_path):
...
+                 PyCapsule_New(&secret_data_handler, "not_mem_handler", NULL);
+             if (secret_data == NULL) {
+                 return NULL;
+             }
+             PyObject *old = PyDataMem_SetHandler(secret_data);
+             Py_DECREF(secret_data);
```
Comment (seberg) [inline numpy/_core/tests/test_mem_policy.py:56]:
```suggestion
             if (wrong_name_capsule == NULL) {
                 return NULL;
             }
             PyObject *old = PyDataMem_SetHandler(wrong_name_capsule);
             Py_DECREF(wrong_name_capsule);
```

File: numpy/_core/tests/test_mem_policy.py (hunk 2 above)
Comment (seberg) [reply numpy/_core/tests/test_mem_policy.py:50]: That's can be anything here really.  But let's rename the object (will just apply the suggestion though).

File: numpy/_core/src/multiarray/alloc.c (hunk 1 above)
Comment (seberg) [reply numpy/_core/src/multiarray/alloc.c:435]: Yes, I think this is fine, no reason to bike-shed the error type.

**Review by seberg — APPROVED** [review]
Thanks for the test follow up!
