### PR TITLE
BUG: Fix missing intrinsics for windows/arm64 target 

### LINKED ISSUE #20930: BUG: Win/Arm64 targets broken due to missing __popcnt intrinsics
### Describe the issue:

Numpy is broken for windows/arm64 target due to the use of __popcnt and its variants. Those intrinsics are not available with arm64 msvc intrinsics

https://docs.microsoft.com/en-us/cpp/intrinsics/popcnt16-popcnt-popcnt64?view=msvc-170

### Reproduce the code example:

```python
pip install .
```

### Error message:

_No response_

### NumPy/Python version information:

1.23.0.dev0+534.g49f9feeba 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 18:46:00) [MSC v.1929 64 bit (ARM64)]

### PR DESCRIPTION
**Pull request by niyas-sait**
Fixes #20930

__popcnt and variants are not available for arm64 msvc intrinsic so use numpy population count implementation for win/arm64 targets.

https://docs.microsoft.com/en-us/cpp/intrinsics/arm64-intrinsics?view=msvc-170

### Test Result

16356 passed, 649 skipped, 1296 deselected, 18 xfailed, 1 xpassed in 245.28s (0:04:05)

### CODE REVIEW

File: numpy/core/src/npymath/npy_math_internal.h.src [hunk 1]
```diff
@@ -887,7 +887,7 @@ npy_popcountu@c@(npy_@type@ a)
 /* use built-in popcount if present, else use our implementation */
 #if (defined(__clang__) || defined(__GNUC__)) && NPY_BITSOF_@STYPE@ >= 32
     return __builtin_popcount@c@(a);
-#elif defined(_MSC_VER) && NPY_BITSOF_@STYPE@ >= 16
+#elif defined(_MSC_VER) && NPY_BITSOF_@STYPE@ >= 16 && !defined(_M_ARM64)
```
Comment (ganesh-k13) [inline numpy/core/src/npymath/npy_math_internal.h.src:890]: Thanks for the fix! I'm not aware of ARM(hence I missed it), but should we add `_M_ARM` as well?

Comment (nsait-linaro) [reply numpy/core/src/npymath/npy_math_internal.h.src:890]: Done!

**Review by ganesh-k13 — APPROVED** [review]

**Comment by charris** [comment]
Thanks @nsait-linaro .
