### PR TITLE
BUG: Fixed crash on self-referential dtypes

### LINKED ISSUE #15301: np.dtype hangs on self-referential dtypes
Malicious, but:
```python
>>> l = []
>>> l.append(('a', l))
>>> np.dtype(l)
# hangs, probably also stackoverflow
```
Should raise a RecursionError.

### PR DESCRIPTION
**Pull request by ganesh-k13**
## Changes:
Fixed crash on self-referential dtypes

resolves #15301

### Note:
Hey, still new here, some things I had doubts on:
1. Want to add a bit of UT, where do I do that?
2. Willing to change the error string if required.
3. I return NULL, hopefully we free all the objects, else please let me know if any cleanup required.

### After Fix:
```
>>> l = []                                                                                                                                                                      
>>> l.append(('a', l))                                                                  
>>> np.dtype(l)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RecursionError: maximum recursion depth exceeded while trying to create self-referential dtypes
```

cc: @eric-wieser

### CODE REVIEW

File: numpy/core/src/multiarray/descriptor.c [hunk 1]
```diff
@@ -241,6 +241,10 @@ is_datetime_typestr(char const *type, Py_ssize_t len)
 static PyArray_Descr *
 _convert_from_tuple(PyObject *obj, int align)
 {
+    if (Py_EnterRecursiveCall(
+            " while trying to create self-referential dtypes" ) != 0) {
+        return NULL;
+    }
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c:247]: Instead of putting this code in four places, can you put it in the function that calls `_convert_from_tuple`?

Comment (eric-wieser) [reply numpy/core/src/multiarray/descriptor.c:247]: (which I think is `_convert_from_any`)

**Review by eric-wieser — CHANGES_REQUESTED** [review]
You need to call `LeaveRecursiveCall` too, otherwise the stack will just keep growing and python will throw the error on all dtypes

File: numpy/core/src/multiarray/descriptor.c (hunk 1 above)
Comment (ganesh-k13) [reply numpy/core/src/multiarray/descriptor.c:247]: Yeah you are right Eric, but seems like `_tuple`, `_list`, `_dict`, etc also calls `_convert_from_any`, which in turns calls it(the issue basically), let me refactor a bit, will get back.

**Comment by ganesh-k13** [comment]
Yeah thanks @eric-wieser, seems like a few UT is failing as well, will check them as well, thanks.

File: numpy/core/src/multiarray/descriptor.c (hunk 1 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/descriptor.c:247]: One way to think about it is to draw out the callgraph, and make sure you cut every loop with a recursive call check. What you have here works fine (and is what I originally suggested), but it may be easier to handle it you cut the loop somewhere else.

The advantage of what you have here is that you can tailor the message to each function.

Comment (ganesh-k13) [reply numpy/core/src/multiarray/descriptor.c]: Hey @eric-wieser , I took the best of both methods and added sperate interceptors. Let me know if this idea is ok, thanks.

**Comment by ganesh-k13** [comment]
@eric-wieser any more changes needed?

File: numpy/core/src/multiarray/descriptor.c [hunk 2]
```diff
@@ -1493,43 +1494,63 @@ _convert_from_any(PyObject *obj, int align)
...
+        goto convert_done;
     }
     else if (PyTuple_Check(obj)) {
         /* or a tuple */
-        return _convert_from_tuple(obj, align);
+        if (Py_EnterRecursiveCall(
+            " while trying to create self-referential tuple dtypes" ) == 0) {
+            convert_ret = _convert_from_tuple(obj, align);
+        }
+        goto convert_done;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c:1509]: This logic is wrong - it should be:
```suggestion
        if (Py_EnterRecursiveCall(
            " while trying to create self-referential tuple dtypes" ) != 0) {
            return NULL;
        }
        PyObject *ret = _convert_from_tuple(obj, align);
        Py_LeaveRecursiveCall();
        return ret;
```
`Py_LeaveRecursiveCall` must not be called if `Py_EnterRecursiveCall` fails.

Comment (ganesh-k13) [reply numpy/core/src/multiarray/descriptor.c:1509]: Oh sorry @eric-wieser , I'll read up a little more and apply the changes. Thanks a lot 👍

File: numpy/core/src/multiarray/descriptor.c [hunk 3]
```diff
@@ -1493,19 +1493,47 @@ _convert_from_any(PyObject *obj, int align)
         return ret;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c:1493]: Line 1491 needs a recursion check too

File: numpy/core/src/multiarray/descriptor.c [hunk 4]
```diff
@@ -1493,19 +1493,47 @@ _convert_from_any(PyObject *obj, int align)
...
     }
     else if (PyUnicode_Check(obj)) {
-        return _convert_from_str(obj, align);
+        if (Py_EnterRecursiveCall(
+             " while trying to convert the given data type from "
+             "str object" ) != 0) {
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c:1498]:
```suggestion
             " while trying to convert the given data type from "
             "a str object" ) != 0) {
```
same throughout

File: numpy/core/src/multiarray/descriptor.c (hunk 3 above)
Comment (ganesh-k13) [reply numpy/core/src/multiarray/descriptor.c:1493]: Oh sorry for missing this, will add

Comment (ganesh-k13) [reply numpy/core/src/multiarray/descriptor.c:1493]: On the same note, what is a way to trigger recursion limit with str, I want to add UT for it. @eric-wieser

**Comment by ganesh-k13** [comment]
Is there a way to retrigger the pipeline? There was a temporary 504 on a download link. I am rebasing for now.

**Comment by ganesh-k13** [comment]
Also does it makes sense to move https://github.com/numpy/numpy/blob/a5aae4f4cd852b64f5f36e8c225895b3a2113c48/numpy/core/src/multiarray/descriptor.c#L111-L116
from there to `_convert_from_any` function https://github.com/numpy/numpy/blob/a5aae4f4cd852b64f5f36e8c225895b3a2113c48/numpy/core/src/multiarray/descriptor.c#L1515

Just to maitain uniformity?

File: numpy/core/src/multiarray/descriptor.c (hunk 3 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/descriptor.c:1499]: Actually, I don't think this case can ever happen - so you can remove the recursion checks for string and for bytes

File: numpy/core/src/multiarray/descriptor.c [hunk 5]
```diff
@@ -1488,24 +1488,58 @@ _convert_from_any(PyObject *obj, int align)
...
+        return ret;
     }
     else if (PyDict_Check(obj) || PyDictProxy_Check(obj)) {
         /* or a dictionary */
-        return _convert_from_dict(obj, align);
+        if (Py_EnterRecursiveCall(
+                " while trying to convert the given data type from"
+                " a dict object" ) != 0) {
+            return NULL;
+        }
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c:1539]: It would be good to add a test for this case too.

File: numpy/core/tests/test_dtype.py [hunk 6]
```diff
@@ -767,6 +767,19 @@ def test1(self):
             ('yi', np.dtype((a, (3, 2))))])
         assert_dtype_equal(c, d)
 
+    def test_array_recursion(self):
```
Comment (eric-wieser) [inline numpy/core/tests/test_dtype.py:770]:
```suggestion
    def test_list_recursion(self):
```

**Review by eric-wieser — COMMENTED** [review]
I think I have a test for tuples too:

```python
In [17]: d = np.int32

In [18]: for i in range(100000):
    ...:     d = (d, (1,))
    ...:

In [19]: dt = np.dtype(d)  # crash
```

**Comment by ganesh-k13** [comment]
Oh that's nice, thanks. I was just looking for ways.

**Review by eric-wieser — APPROVED** [review]
This now looks great to me, thanks!

**Comment by eric-wieser** [comment]
> Also does it makes sense to move ... just to maintain uniformity

I wouldn't worry too much - I'm still not sure which way is better, so am inclined to leave it for the next person who refactors this code to decide.

**Comment by ganesh-k13** [comment]
Thanks a lot for the review @eric-wieser 👍
