### PR TITLE
BUG,DEP: Fix writeable flag setting for arrays without base

### LINKED ISSUE #481: segfault in _IsWriteable when data is not owned
The following, albeit slightly contrived, example causes a segfault in _IsWriteable.

foo.pyx:

``` python
from libc.stdlib cimport malloc
import numpy as np
cimport numpy as np

np.import_array()

def test(n):

    cdef np.npy_intp _n = n
    cdef void * data

    data = <void *>malloc(_n * sizeof(double))

    return np.PyArray_SimpleNewFromData(1, &_n, np.NPY_DOUBLE, data)
```

test.py:

``` python
import pyximport
pyximport.install()
import foo

a = foo.test(10)
b = a.reshape((5,2))
b.setflags(write=True)
```

`python test.py` -> segmentation fault

Here's _IsWriteable (with unnecessary bits removed).

``` c
NPY_NO_EXPORT npy_bool
_IsWriteable(PyArrayObject *ap)
{
    PyObject *base=PyArray_BASE(ap);
....
    /* If we own our own data, then no-problem */
    if ((base == NULL) || (PyArray_FLAGS(ap) & NPY_ARRAY_OWNDATA)) {
        return NPY_TRUE;
    }
 ....
    while(PyArray_Check(base)) {
        if (PyArray_CHKFLAGS((PyArrayObject *)base, NPY_ARRAY_OWNDATA)) {
            return (npy_bool) (PyArray_ISWRITEABLE((PyArrayObject *)base));
        }
        base = PyArray_BASE((PyArrayObject *)base);
    }

...
}
```

a.setflags(write=True) works because

ap == a
base == NULL

and we hit the first condition (base is NULL or we own the data)

b.setflags(write=True) doesn't work because
ap == b
base == a
b.flags['OWNDATA'] == False

so we go into the loop:
base doesn't own the data either, so we try and find the base of a, which is NULL, and PyArray_Check(NULL) is a segfault.

I think the fix is

``` patch
diff --git a/numpy/core/src/multiarray/common.c b/numpy/core/src/multiarray/common.c
index 7b8177c..60a58f6 100644
--- a/numpy/core/src/multiarray/common.c
+++ b/numpy/core/src/multiarray/common.c
@@ -628,6 +628,9 @@ _IsWriteable(PyArrayObject *ap)
             return (npy_bool) (PyArray_ISWRITEABLE((PyArrayObject *)base));
         }
         base = PyArray_BASE((PyArrayObject *)base);
+        if (!base) {
+            return NPY_TRUE;
+        }
     }

     /*
```

But I'm not sure which of returning True or False is correct.

### PR DESCRIPTION
**Pull request by seberg**
This also deprecates setting a non-writeable array to writeable if
that array does not own its data (and has no base object to check if
the memory may be writeable). (Deprecation on Python side only)

Closes gh-481

---

Well, this was probably a waste of time, thought it would be quicker, but should be reasonable in any case...

### CODE REVIEW

**Comment by seberg** [comment]
I may add a fix for Mattis PR here probably (with a test), but if someone reviews it before that, will just open a new PR afterwards.

File: numpy/core/src/multiarray/_multiarray_tests.c.src [hunk 1]
```diff
@@ -848,6 +848,24 @@ get_buffer_info(PyObject *NPY_UNUSED(self), PyObject *args)
...
+        return NULL;
+    }
+
+    flags = writeable ? NPY_ARRAY_WRITEABLE : 0;
+    /* Create an empty array (which points to a random place) */
+    return PyArray_NewFromDescr(&PyArray_Type, PyArray_DescrFromType(NPY_INTP),
+                                1, &zero, NULL, &zero, flags, NULL);
+}
+
+
```
Comment (mattip) [inline numpy/core/src/multiarray/_multiarray_tests.c.src]: Needs a comment what is the purpose of this function, it is a bit obscure at first glance.

File: numpy/core/src/multiarray/methods.c [hunk 2]
```diff
@@ -2546,6 +2546,22 @@ array_setflags(PyArrayObject *self, PyObject *args, PyObject *kwds)
...
+                if ((PyArray_BASE(self) == NULL) &&
+                            !PyArray_CHKFLAGS(self, NPY_ARRAY_OWNDATA) &&
+                            !PyArray_CHKFLAGS(self, NPY_ARRAY_WRITEABLE)) {
+                    /* 2017-05-03, NumPy 1.17.0 */
+                    if (DEPRECATE("making a non-writeable array writeable "
+                                  "is deprecated for arrays without a base "
+                                  "which do not own their data.") < 0) {
+                        return NULL;
+                    }
+                }
```
Comment (mattip) [inline numpy/core/src/multiarray/methods.c]: The new deprecation should appear in the release notes

**Comment by seberg** [comment]
Add some docs and release notes (only changes).

File: doc/release/1.17.0-notes.rst [hunk 3]
```diff
@@ -33,6 +33,16 @@ The internal use of these functions has been refactored and there are better
 alternatives. Relace ``exec_command`` with `subprocess.Popen` and
 ``temp_file_name`` with `tempfile.mkstemp`.
 
+Writeable flag of C-API wrapped arrays
+--------------------------------------
+When an array is created from the C-API to wrap already existing data and
+the array does not own its data (frees it after destruction) it will not be
+possible to switch its writeable flag to ``True`` in the future.
```
Comment (mattip) [inline doc/release/1.17.0-notes.rst]: Maybe clearer to state the reason:

"When an array is created from the C-API to wrap a pointer to data, the only indication we have of the read-write nature of the data is the ``writeable`` flag set during creation. It is dangerous to force the flag to ``writeable``.  In the future it will not be possible to switch the writeable flag to ``True``.

Comment (seberg) [reply doc/release/1.17.0-notes.rst]: Yeah, that is better, added a "from python" at the end.

**Comment by mattip** [comment]
Thanks @seberg, this also closes the second-oldest open issue!
