### PR TITLE
BUG: Fixes random.noncentral_chisquare when 0 < df <= 1

### LINKED ISSUE #5766: Cannot generate random variates from noncentral chi-square distribution with dof = 1
The issue is a duplicate of scipy/scipy#4720 

The [document](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.noncentral_chisquare.html#numpy.random.noncentral_chisquare)  suggests that the parameter _degree of freedom_ should be `df >= 1` to use `numpy.random.noncentral_chisquare`. However, taking `df = 1` raises error. 

```python
import numpy as np
df = 1
nc = 2
np.random.noncentral_chisquare(df, nc)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-7c9f3f6a3a16> in <module>()
----> 1 np.random.noncentral_chisquare(df, nc)

mtrand.pyx in mtrand.RandomState.noncentral_chisquare (numpy/random/mtrand/mtrand.c:15618)()

ValueError: df <= 0
```

It makes me suspect that the random variate generation of the noncentral chi-square distribution with degree of freedom `df` and noncentrality parameter `nc` is implemented in numpy using a method similar to the following.
```python
np.random.chisquare(df-1) + (np.random.standard_normal()+np.sqrt(nc))**2
```
However, this method is valid only for the case where `df > 1` because with `df = 1`, it needs to generate a chi-square random variate with degree of freedom 0, which is not mathematically well-defined.

On the other hand, noncentral chi-square distribution is indeed mathematically well-defined for all `df > 0`. It simply requires a different algorithm for random variate generation if `0 < df <= 1`, such as the following one: 
```python
np.random.chisquare(df + 2*np.random.poisson(nc / 2.0))
```

### PR DESCRIPTION
**Pull request by behzadnouri**
Closes #5766.

For sanity check, this is a comparison of theoretical cumulant-generating function and the emprical one at 3 different values for degree of freedom:

```
# cumulant-generating function
cgf = lambda t, df, nonc: nonc * t / (1 - 2*t) - .5 * df * np.log(1 - 2*t)

size, nonc = 1 << 26, .01
t = np.linspace(-.5, .5, 50, endpoint=False)

for df in .1, .5, .9:
    a = np.random.noncentral_chisquare(df, nonc, size)
    y = np.fromiter((np.exp(a * x).mean(axis=0) for x in t[1::3]), 'f8')
    l, = plt.plot(t, cgf(t, df, nonc), label='df: {}'.format(df))
    plt.plot(t[1::3], np.log(y), l.get_color() + 'o', label='_nolegend_')
```

ffig2

same plots with `nonc = 2`:
ffig3

### CODE REVIEW

**Comment by charris** [comment]
This looks correct to me, at least in a quick comparison with the Wikipedia formula, but I'd like some assurance from someone more familiar with the area. @rkern @njsmith Thoughts? I also wonder why the original cannot be made to work with the extended range of df? Also, what accounts for the deviation at the right ends of the graphs? Does it get better if more samples are used?

File: numpy/random/mtrand/distributions.c [hunk 1]
```diff
@@ -218,11 +218,17 @@ double rk_chisquare(rk_state *state, double df)
...
+    if(1 < df)
+    {
+        const double Chi2 = rk_chisquare(state, df - 1);
+        const double N = rk_gauss(state) + sqrt(nonc);
+        return Chi2 + N*N;
+    }
+    else
+    {
+        const long i = 2L * rk_poisson(state, nonc / 2.0);
+        return rk_chisquare(state, df + i);
```
Comment (charris) [inline numpy/random/mtrand/distributions.c]: Might be clearer to move the multiplication by `2L` down into the function call, i.e.
```
return rk_chisquare(state, df + 2 * i);
```

**Comment by behzadnouri** [comment]
> why the original cannot be made to work with the extended range of df?

If `df < 1`, the original path ultimately calls into `log` function with a negative value; I also tested how the CGF will look like, and it does not match the theoretical one

> Also, what accounts for the deviation at the right ends of the graphs?

The CGF function goes to infinity as `t` approaches `0.5`, so it should be harder to capture that with a finite sample.

> Does it get better if more samples are used?

I expect that it does; but, that is how far I can push the sample size with the memory on my laptop.

File: numpy/random/mtrand/mtrand.pyx [hunk 2]
```diff
@@ -2201,7 +2201,7 @@ cdef class RandomState:
         Parameters
         ----------
         df : int
-            Degrees of freedom, should be >= 1.
+            Degrees of freedom, should be > 0.
```
Comment (charris) [inline numpy/random/mtrand/mtrand.pyx]: Should note that `df == 1` is only available in numpy 1.10 or greater. Hmm... maybe something like
```
Degrees of freedom, must be > 0 as of NumPy 1.10,
must be > 1 for earlier versions.
```

**Comment by charris** [comment]
Merged. Thanks @behzadnouri .
