### PR TITLE
BUG: Fix comparison for empty structured arrays

### LINKED ISSUE #21739: BUG: `==` and `!=` fail on empty structured array if there is a nontrivially shaped field
### Describe the issue:

In some corner cases an empty structured array does not compare equal to itself in the testing routines.

### Reproduce the code example:

```python
import numpy as np

a = np.zeros(0, [('a', '<f8', (1,))])
np.testing.assert_equal(a, a) # ok
np.testing.assert_array_equal(a, a) # ok

a = np.zeros(1, [('a', '<f8', (1, 1))])
np.testing.assert_equal(a, a) # ok
np.testing.assert_array_equal(a, a) # ok

a = np.zeros(0, [('a', '<f8', (1, 1))])
np.testing.assert_equal(a, a) # fails
np.testing.assert_array_equal(a, a) # fails
```

### Error message:

```shell
ValueError                                Traceback (most recent call last)
File ~/Documents/Programmi/python3102venv/lib/python3.10/site-packages/numpy/testing/_private/utils.py:792, in assert_array_compare(comparison, x, y, err_msg, verbose, header, precision, equal_nan, equal_inf)
    790     return
--> 792 val = comparison(x, y)
    794 if isinstance(val, bool):

ValueError: cannot reshape array of size 0 into shape (0,newaxis)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Input In [30], in <cell line: 12>()
      9 np.testing.assert_array_equal(a, a) # ok
     11 a = np.zeros(0, [('a', '<f8', (1, 1))])
---> 12 np.testing.assert_equal(a, a) # fails
     13 np.testing.assert_array_equal(a, a)

    [... skipping hidden 2 frame]

File ~/Documents/Programmi/python3102venv/lib/python3.10/site-packages/numpy/testing/_private/utils.py:852, in assert_array_compare(comparison, x, y, err_msg, verbose, header, precision, equal_nan, equal_inf)
    848 header = f'error during assertion:\n\n{efmt}\n\n{header}'
    850 msg = build_err_msg([x, y], err_msg, verbose=verbose, header=header,
    851                     names=('x', 'y'), precision=precision)
--> 852 raise ValueError(msg)

ValueError: 
error during assertion:

Traceback (most recent call last):
  File "/Users/giacomo/Documents/Programmi/python3102venv/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 792, in assert_array_compare
    val = comparison(x, y)
ValueError: cannot reshape array of size 0 into shape (0,newaxis)


Arrays are not equal
 x: array([], dtype=[('a', '<f8', (1, 1))])
 y: array([], dtype=[('a', '<f8', (1, 1))])
```

### NumPy/Python version information:

1.21.5 3.10.2 (v3.10.2:a58ebcc701, Jan 13 2022, 14:50:16) [Clang 13.0.0 (clang-1300.0.29.30)]

### PR DESCRIPTION
**Pull request by postmalloc**
Fixes #21739

When empty structured arrays with nontrivially shaped fields are
compared, the reshape operation invoked fails. Instead of reshaping
using -1, computing the new dimension manually solves the problem.

### CODE REVIEW

File: numpy/core/src/multiarray/arrayobject.c [hunk 1]
```diff
@@ -766,7 +766,15 @@ _void_compare(PyArrayObject *self, PyArrayObject *other, int cmp_op)
                         memcpy(dimensions, PyArray_DIMS((PyArrayObject *)temp),
                                sizeof(npy_intp)*result_ndim);
                     }
-                    dimensions[result_ndim] = -1;
+
+                    /*
+                    * Compute the new dimension size manually 
+                    * (instead of reshaping with -1) to avoid division by zero.
```
Comment (seberg) [inline numpy/core/src/multiarray/arrayobject.c:772]: Might just say that `-1` will not work when the array is empty (gh-18519).  Division by zero seems is the cause for the failure, but it not the problematic condition at this place (the empty array is).

Otherwise, looks great though!  A small update would be great, or we may just put it in (or do a small update).

File: numpy/core/tests/test_multiarray.py [hunk 2]
```diff
@@ -1244,6 +1244,17 @@ def test_subarray_comparison(self):
         # The main importance is that it does not return True:
         with pytest.raises(TypeError):
             x == y
+
```
Comment (seberg) [inline numpy/core/tests/test_multiarray.py:1247]: I would also slightly prefer to make a new test function here.  We have a lot of very long functions, but long test functions are not very convenient (when they fail cryptically).

**Review by seberg — COMMENTED** [review]
Two small nitpicks, but generally looks good to go in, thanks!

File: numpy/core/src/multiarray/arrayobject.c (hunk 1 above)
Comment (postmalloc) [reply numpy/core/src/multiarray/arrayobject.c]: Updated the comment, thanks!

File: numpy/core/src/multiarray/arrayobject.c [hunk 3]
```diff
@@ -766,7 +766,15 @@ _void_compare(PyArrayObject *self, PyArrayObject *other, int cmp_op)
                         memcpy(dimensions, PyArray_DIMS((PyArrayObject *)temp),
                                sizeof(npy_intp)*result_ndim);
                     }
-                    dimensions[result_ndim] = -1;
+
+                    /*
+                    * Compute the new dimension size manually, as reshaping
+                    * with -1 does not work on empty arrays.
+                    */
```
Comment (seberg) [inline numpy/core/src/multiarray/arrayobject.c:773]:
```suggestion
                     * Compute the new dimension size manually, as reshaping
                     * with -1 does not work on empty arrays.
                     */
```

**Comment by seberg** [comment]
Thanks @postmalloc.  Eric mentioned overflow on the issue.  I am not going to worry about it, since that would mean an invalid `dtype` that should be impossible to create.
(Plus, an incorrect result should additionally be caught by `NewShape`/reshape.)

**Comment by InessaPawson** [comment]
Hi-five on merging your first pull request to NumPy, @postmalloc! We hope you stick around! Your choices aren’t limited to writing code – you can review pull requests, help us stay on top of new and old  issues, develop educational material, work on our website, add or improve graphic design, create marketing materials, translate website content, write grant proposals, and help with other fundraising initiatives. For more info, check out: https://numpy.org/contribute
Also, consider joining our mailing list. This is a great way to connect with other cool people in our community and be part of important conversations that affect the development of NumPy: https://mail.python.org/mailman/listinfo/numpy-discussion
