### PR TITLE
BUG/ENH: Fix fast index loops for 1-el array / allow scalar value

### LINKED ISSUE #23178: BUG: New indexed loops give segmentation fault for 1-element 1-d values
### Describe the issue:

New indexed loops give segmentation fault for 1-element 1-d values.

My guess is that the step size `isb` for `value` for this case should be set to 0.

### Reproduce the code example:

```python
import numpy as np
r = np.zeros(1000)
i = np.repeat(np.arange(999, 1, -1, dtype=np.intp), 100)
np.add.at(r, i, np.ones(1))
```

### Error message:

```shell
# Segmentation fault

gdb --args python3 ~/x.py -g --python

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6f71775 in DOUBLE_add_indexed (__NPY_UNUSED_TAGGEDcontext=<optimized out>, args=<optimized out>, dimensions=<optimized out>, steps=<optimized out>, 
    __NPY_UNUSED_TAGGEDfunc=<optimized out>) at numpy/core/src/umath/loops_arithm_fp.dispatch.c.src:177
177             *indexed = *indexed @OP@ *(@type@ *)value;
```

### Runtime information:

```
In [1]: import sys, numpy; print(numpy.__version__); print(sys.version)
1.25.0.dev0+597.gc4c0bbd36
3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]

In [2]: print(numpy.show_runtime())
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'numpy_version': '1.25.0.dev0+597.gc4c0bbd36',
  'python': '3.9.2 (default, Feb 28 2021, 17:03:44) \n[GCC 10.2.1 20210110]',
  'uname': uname_result(system='Linux', node='swan.astro.utoronto.ca', release='5.10.0-20-amd64', version='#1 SMP Debian 5.10.158-2 (2022-12-13)', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX'],
                      'not_found': ['F16C',
                                    'FMA3',
                                    'AVX2',
                                    'AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]
None
```

### Context for the issue:

Found while trying to add complex loops.

### PR DESCRIPTION
**Pull request by mhvk**
Fixes #23178 and also ensures that regular scalar values take the fast path for the index loops (like `np.add.at`).

EDIT: new timings:
```
In [2]: import numpy as np; c = np.zeros(1000, complex); r = c.view(float); i = np.repeat(np.arange(999, 1, -1, dtype=np.intp), 100); np.__version__
Out[2]: '1.25.0.dev0+597.gc4c0bbd36'

In [3]: %timeit np.add.at(r, i, np.ones(1))
324 µs ± 3.97 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [4]: %timeit np.add.at(r, i, np.ones(()))
324 µs ± 2.88 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [5]: %timeit np.add.at(r, i, 1.)
317 µs ± 690 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [6]: %timeit np.add.at(r, i, 1)
8.55 ms ± 39.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
Last one is slow because of the need for casting (maybe can be special-cased too, but for another time!)

EDIT2: for comparison on the same machine,
```
In [3]: %timeit np.bincount(i)
264 µs ± 1.48 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

### CODE REVIEW

**Comment by mattip** [comment]
LGTM. I don't understand the windows PyPy underflow warning in `np.floor`. I doubt it is connected, but maybe there is some lack of clearing error state somewhere?

File: numpy/core/src/umath/ufunc_object.c [hunk 1]
```diff
@@ -5915,7 +5915,12 @@ trivial_at_loop(PyArrayMethodObject *ufuncimpl, NPY_ARRAYMETHOD_FLAGS flags,
         steps[2] = 0;
     } else {
         args[2] = (char *)PyArray_DATA(op2_array);
-        steps[2] = PyArray_STRIDE(op2_array, 0);
+        if (PyArray_NDIM(op2_array) == 0
```
Comment (mhvk) [inline numpy/core/src/umath/ufunc_object.c:5918]: This was incorrectly `PyArray_DIMS` -- maybe the failure was related. Anyway, now fixed.

**Comment by seberg** [comment]
Thanks, the fix and generalization look right.  It is a bit confusing that we create the "broadcast iterator" above, but it is only used to check whether shapes are compatible at all.
