### PR TITLE
API,BUG: Fix scalar handling in array-interface allowing NULL pointers

### LINKED ISSUE #26037: BUG: Cannot create zero-length array-like object via __array_interface__ providing null pointer as data
### Describe the issue:

I am trying to create a custom array-like object that stores zero-length one-dimensional array using `__array_interface__`. As the array is zero-length and therefore does not contain any data, I provide a null pointer as the `data` field of `__array_interface__` (i.e. `"data": (0, False)`). Then my object is seemingly treated as a scalar by `np.array`, despite the fact that `shape` is `(0,)`. If I provide anything different from 0 as the data, everything works.

### Reproduce the code example:

```python
import numpy as np

class TestArray:
    def __init__(self):
        self.__array_interface__ = {
            "data": (0, False),
            "strides": None,
            "descr": [("", "<f8")],
            "typestr": "<f8",
            "shape": (0,),
            "version": 3,
        }

np.array(TestArray())
```

### Error message:

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[24], line 1
----> 1 np.array(TestArray())

TypeError: float() argument must be a string or a real number, not 'TestArray'
```

### Python and NumPy Versions:

1.26.1
3.11.6 (main, Oct  2 2023, 13:45:54) [GCC 12.3.0]

### Runtime Environment:

_No response_

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by seberg**
This fixes the scalar handling in the array-interface and also a bug in the shape handling error path.

In theory it breaks code that used NULL to trigger the scalar path, but this path was:
1. Completely undocumented, and
2. correctly triggered by *ommitting* the data field instead.

I didn't remove/deprecate the scalar path in this PR, maybe we should. But, I do think we can ignore that theoretical use-case since it is nonsensical.

Closes gh-26037

### CODE REVIEW

File: numpy/_core/src/multiarray/ctors.c [hunk 1]
```diff
@@ -2366,18 +2368,32 @@ PyArray_FromInterface(PyObject *origin)
...
+         * could probably just deprecate (or just remove it in a 3.0 version).
+         */
         if (PyArray_SIZE(ret) > 1) {
             PyErr_SetString(PyExc_ValueError,
                     "cannot coerce scalar to array with size > 1");
             Py_DECREF(ret);
             goto fail;
         }
-        if (PyArray_SETITEM(ret, PyArray_DATA(ret), origin) < 0) {
+        if (PyArray_Pack(PyArray_DESCR(ret), PyArray_DATA(ret), origin) < 0) {
```
Comment (seberg) [inline numpy/_core/src/multiarray/ctors.c:2382]: This probably doesn't matter in practice, but could matter for new dtypes in principle.  It's just the right way now.

File: numpy/_core/src/multiarray/ctors.c [hunk 2]
```diff
@@ -2229,12 +2230,10 @@ PyArray_FromInterface(PyObject *origin)
         /* Shape must be specified when 'data' is specified */
         int result = PyDict_ContainsString(iface, "data");
         if (result < 0) {
-            Py_DECREF(attr);
             return NULL;
         }
         else if (result == 1) {
             Py_DECREF(iface);
-            Py_DECREF(attr);
```
Comment (seberg) [inline numpy/_core/src/multiarray/ctors.c:2237]: This is a plain bug-fix, it could (and maybe should) be backported.  In this branch `attr` is explicitly still `NULL`, since `result == 0`.

Comment (ngoldbaum) [reply numpy/_core/src/multiarray/ctors.c:2237]: I agree. This must have been a bug from the `GetItemRef` migration. Care to make a backport PR for this?

**Review by ngoldbaum — APPROVED** [review]
Makes sense to me!

File: numpy/_core/src/multiarray/ctors.c (hunk 2 above)
Comment (seberg) [reply numpy/_core/src/multiarray/ctors.c:2237]: Yes, done in https://github.com/numpy/numpy/pull/29350

**Comment by seberg** [comment]
OK, one approval seems good enough.  If anyone thinks that this weird NULL scalar path is actually used out there, let me know and I am happy to revert if needed.
(Although, even if it is used by one user, they should probably just adapt.)
