### PR TITLE
ENH: Check for floating point exceptions in dot

### LINKED ISSUE #14925: BUG: Dot product does not check for floating point warning flags
The `dot` function (unlike ufuncs, and the ufunc based `matmul`, `@`) does not check for floating point warning/error flags. It would probably better if it would, although it is likely not high priority. The example being:

```
np.dot([1,1], [-np.inf, np.inf])
```
Which should be setting the CPU invalid value produced flag on the NaN result, but it is not caught by NumPy.

(phased out from gh-14788)

### PR DESCRIPTION
**Pull request by rtimpe**
Currently dot does not check for floating point exceptions, while similar functions (such as multiply and matmul) do.  Add these checks for consistency.

Note that certain types of floating point exceptions are still not caught:
- Multiplications of 0 with nan or inf are ignored (see #27902)
- Integer overflows are ignored.  These aren't true floating point exceptions, but the behavior is inconsistent with scalar multiply, i.e.
```
>>> np.int16(32000) * np.int16(3)
<python-input-7>:1: RuntimeWarning: overflow encountered in scalar multiply
  np.int16(32000) * np.int16(3)
np.int16(30464)
>>> np.dot(np.int16(32000), np.int16(3))
np.int16(30464)
```

Fixes #14925

### CODE REVIEW

File: numpy/_core/src/multiarray/multiarraymodule.c [hunk 1]
```diff
@@ -958,6 +958,20 @@ PyArray_MatrixProduct(PyObject *op1, PyObject *op2)
...
+    int errmask = 0;
+    if (_get_bufsize_errmask(NULL, &errmask) < 0) {
+        return -1;
+    }
+    if (_check_ufunc_fperr(errmask, func_name) < 0) {
+        return -1;
+    }
+
+    return 0;
+}
```
Comment (seberg) [inline numpy/_core/src/multiarray/multiarraymodule.c:973]: Please use `PyUFunc_GiveFloatingpointErrors`, you can find the rest of the pattern elsewhere (e.g. in scalar math).

File: numpy/_core/src/multiarray/multiarraymodule.c [hunk 2]
```diff
@@ -1008,11 +1022,17 @@ PyArray_MatrixProduct2(PyObject *op1, PyObject *op2, PyArrayObject* out)
         return NULL;
     }
 
+    npy_clear_floatstatus();
```
Comment (seberg) [inline numpy/_core/src/multiarray/multiarraymodule.c:1025]: I would prefer pairing this with the GIL release (i.e. very targeted around the place of interest).

That probably means moving it into `cblas_matrixproduct`.

File: numpy/_core/src/multiarray/multiarraymodule.c [hunk 3]
```diff
@@ -1008,11 +1022,17 @@ PyArray_MatrixProduct2(PyObject *op1, PyObject *op2, PyArrayObject* out)
...
+
 #if defined(HAVE_CBLAS)
     if (PyArray_NDIM(ap1) <= 2 && PyArray_NDIM(ap2) <= 2 &&
             (NPY_DOUBLE == typenum || NPY_CDOUBLE == typenum ||
              NPY_FLOAT == typenum || NPY_CFLOAT == typenum)) {
-        return cblas_matrixproduct(typenum, ap1, ap2, out);
+        PyObject *res = cblas_matrixproduct(typenum, ap1, ap2, out);
+        if (check_fperr("dot") < 0) {
+            return NULL;
```
Comment (seberg) [inline numpy/_core/src/multiarray/multiarraymodule.c:1033]: Just to note, this is also incorrect of course:  You would have to throw away `res` here, but you are leaking it.

**Review by seberg — COMMENTED** [review]
Thanks for looking into it, seems like a good small improvement.  Could note it as a very brief "change" in the relase note, although I don't think it mattre much.

File: numpy/_core/src/multiarray/multiarraymodule.c (hunk 2 above)
Comment (rtimpe) [reply numpy/_core/src/multiarray/multiarraymodule.c]: I moved this to `cblas_matrixproduct` but I'm not sure if it's quite what you want.  Do you want this immediately before (or after?) the GIL release, or just closer to where the actual work is being done?

**Comment by rtimpe** [comment]
I'm not sure what's causing the CI failure, but it doesn't seem to be related to my PR.  Or am I missing something?

**Comment by mattip** [comment]
I restarted the s390x build.

File: numpy/_core/tests/test_multiarray.py [hunk 4]
```diff
@@ -3345,6 +3345,29 @@ def test_dot(self):
         a.dot(b=b, out=c)
         assert_equal(c, np.dot(a, b))
 
+    @pytest.mark.skipif(IS_WASM, reason="no wasm fp exception support")
+    def test_dot_errstate(self):
```
Comment (seberg) [inline numpy/_core/tests/test_multiarray.py:3349]: Small nit:  Could you parametrize this to include `half` and/or `longdouble` (just because they currently take the other code paths and can set the warnings).

The point is that double/float should effectively always take the first branch, that way we should cover both error paths.

**Review by seberg — COMMENTED** [review]
Thanks, LGTM!  A small nit that we should extend the test a bit, I think.

Not super important here, but you could add a `change` or `improvement` release note if you like (see `docs/release/upcoming_changes/README.rst`).

(Unrelated... I am half wondering if we couldn't fold most of this to use the `matmul` ufunc as a whole or just its loops.  That would also have the information that no floating point errors can happen.  But I am not worried about it much, matmuls on integers isn't all that common.)

**Comment by rtimpe** [comment]
> (Unrelated... I am half wondering if we couldn't fold most of this to use the `matmul` ufunc as a whole or just its loops. That would also have the information that no floating point errors can happen. But I am not worried about it much, matmuls on integers isn't all that common.)

I can look into this, if it would be of interest.  I picked this bug as a good way to get started with numpy development, and I was thinking of applying similar fixes to some of the other functions in the multiarray module (assuming they have similar bugs, which I haven't looked into yet).  Do you have a preference on what would be more useful?

**Comment by seberg** [comment]
Thanks for the follow-up, let's give this a shot!

**Comment by tylerjereddy** [comment]
Note: required a small number of shims downstream, but not too bad I don't think.
