### PR TITLE
BUG: Potential fix for divmod(1.0, 0.0) to raise divbyzero and return inf

### LINKED ISSUE #14900: BUG: `__floordiv__` gives NaN and invalid warning for `1//0`
The `__floordiv__` and `__mod__` operators do not raise an exception for zero division with `np.errstate(divide='raise')`, instead replacing those instances with `nan` as if `errstate` is in the default state.

```python
import numpy as np
x = np.ones((3, 3))
y = np.zeros((3, 3))

with np.errstate(divide='raise'):
    fdiv = x // y # expecting exception
    mod = x % y # expecting exception
```

Numpy: 1.17.3

### PR DESCRIPTION
**Pull request by anirudh2290**
This potentially fixes: https://github.com/numpy/numpy/issues/14900 . This is currently WIP until discussion concludes on #14900. According to IEEE754 standard this 1 / 0 double division should return inf. Note: currently in numpy, np.divmod(1.0, 0.0) and np.divmod(1, 0) don't return consistent results, its (inf, nan) for former and (0, 0) for latter. 

I have currently limited the change to floating point divmod. This will require more changes for int_ ~~divmod to return (inf, nan) (probably has back. compatibility implications) ,~~ I am guessing here : https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/loops.c.src#L909

EDIT: inf cannot be returned for int_ divmod , we have to choose between current behavior and raising an error.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Let's limit this PR to the float case, as that has a fairly trivial "correct" behavior (match `floor_divide` and `mod`)

**Comment by anirudh2290** [comment]
@eric-wieser I agree, we can limited this to float for now. I sent out an email on the list for a discussion about the same.

**Comment by seberg** [comment]
I somewhat expect we need to check for `!b` first, and/or change this in `divmod`. New tests could be nice to make it easier to see what actually changed here. Interesting, but I guess not important `p.divmod(4, np.finfo(np.float64).tiny)` returns `(inf, 0)` and sets both overflow and divide by zero flags.

**Comment by anirudh2290** [comment]
> p.divmod(4, np.finfo(np.float64).tiny) returns (inf, 0) and sets both overflow and divide by zero flags. 

isn't this expected ? as i raised in the mailing list, I was not sure about whether divmod should set both flags. I thought that since it does both div and mod operations it should set both flags . the ieee754 standard doesnt make a specific comment about this particular operation insists that division or remainder individually should set only one flag.

**Comment by anirudh2290** [comment]
The test failures seem to be because of https://github.com/numpy/numpy/issues/16220 and 1.0/0.0 operations not raising invalid warning on mac. I was looking for platform specific tests that omit macOS, but couldnt find any. Is this the first time we are encountering this ?

File: numpy/core/src/umath/loops.c.src [hunk 1]
```diff
@@ -2346,8 +2350,18 @@ HALF_floor_divide(char **args, npy_intp const *dimensions, npy_intp const *steps
...
+        float fh1 = npy_half_to_float(in1);
+        float fh2 = npy_half_to_float(in2);
+        float div, modf;
+
+        if (!fh2) {
+            div = fh1 / fh2;
+            *((npy_half *)op1) = npy_float_to_half(div);
+        } else {
+            div = npy_divmodf(fh1, fh2, &modf);
+            *((npy_half *)op1) = npy_float_to_half(div);
```
Comment (anirudh2290) [inline numpy/core/src/umath/loops.c.src:2363]: i know this is a bit uglier than before, but had to move the `npy_half_divmod` to these functions, to make float16 work.

Comment (anirudh2290) [reply numpy/core/src/umath/loops.c.src:2363]: This is likely caused by the clang compiler on mac os  likely because clang doesnt implement annex F of C standard, I think this is still open. (https://bugs.llvm.org/show_bug.cgi?id=17005)

Comment (seberg) [reply numpy/core/src/umath/loops.c.src:2363]: Not sure we have to work around compiler shortcomings/bugs, but its also not wrong to do. We had similar issues with windows±SSE before for example, IIRC.

If you want to skip tests, I think `platform.python_compiler()` should probably work here?

**Comment by anirudh2290** [comment]
just so that people don't get misled by this (since I put the comment in the wrong place).

> This is likely caused by the clang compiler on mac os likely because clang doesn't implement annex F of C standard, I think this is still open. (https://bugs.llvm.org/show_bug.cgi?id=17005)

the above comment is for the current ci failures on mac with clang. It fails because it doesn't raise the invalid warning on clang builds, since clang doesn't set the invalid flag for 1.0 % 0.0 operations.

File: numpy/core/src/umath/loops.c.src (hunk 1 above)
Comment (anirudh2290) [reply numpy/core/src/umath/loops.c.src:2363]: thank you Sebastian, for your inputs ! i think i will skip the test for now. 

> Note that NumPy is developed mainly using GNU compilers. Compilers from other vendors such as Intel, Absoft, Sun, NAG, Compaq, Vast, Portland, Lahey, HP, IBM, Microsoft are only supported in the form of community feedback, and may not work out of the box. GCC 4.x (and later) compilers are recommended.

This is what the devdocs (https://numpy.org/devdocs/user/building.html) says: do we want to change this given that we now test on clang  in the CI ?

Comment (mattip) [reply numpy/core/src/umath/loops.c.src:2363]: On macOS, clang is the default compiler. On windows we build with MSVC.

Comment (anirudh2290) [reply numpy/core/src/umath/loops.c.src:2363]: @mattip should i change the dev docs to reflect that ?

Comment (seberg) [reply numpy/core/src/umath/loops.c.src:2363]: Yeah, I think we should mention clang and msvc as major compilers there, intel maybe too, but I am not sure. I am not even sure GCC 4.x is still reasonably new to be honest.

Comment (anirudh2290) [reply numpy/core/src/umath/loops.c.src:2363]: yes gcc 4.x is pretty old, but since we still use it in our CI good to mention 4.x and later in docs.

Comment (mattip) [reply numpy/core/src/umath/loops.c.src:2363]: > Not sure we have to work around compiler shortcomings/bugs,

If we want the error to appear reliably, we should be using one of the `npy_set_floatstatus_` variants rather than skipping the test. If we don't care, then skipping the test is fine.

Comment (seberg) [reply numpy/core/src/umath/loops.c.src:2363]: Right, maybe that is better and yeah, we have done that in a few places. Would probably be good to put it behind a compiler directive to only use it when necessary. (Its too bad we won't notice when it gets fixed, unless we go through the trouble and put it into the conftests...).

Comment (anirudh2290) [reply numpy/core/src/umath/loops.c.src:2363]: yes that sounds like a good idea. so if i understand correctly:i should use #ifdef __clang__  wherever i use 1.0/0.0 in my code currently to set status and continue with what I currently have for non clang compilers. I am wondering if the npy_set_floatstatus_ work for clang though ? also if we are going to call this flag, what do we set these values to if not nan and infs (the NPY_INFINITY and NPY_NAN i doubt can be used on all platforms.)

**Comment by anirudh2290** [comment]
Any idea on where I should be looking to fix this CI error : "ValueError: path is on mount 'D:', start on mount 'C:'". It happened twice in this PR, most likely not related to this PR.

**Comment by seberg** [comment]
No, its failing everywhere today... I thought we fixed something along these lines on master recently, but apparently not, or not robustly.

**Comment by anirudh2290** [comment]
np.fmod(1.0, 0.0) I think will likely fail on Macos. I have added tests for fmod to check. not that its in the divmod code path but maybe good to fix.

Current status: 

Operator | Warning Message | warning after code change | Result | Result After code change | Works as expected on MacOS
-- | -- | -- | -- | -- | --
np.divmod(1.0, 0.0) | Invalid | Invalid and Dividebyzero | nan, nan | inf, nan | Yes
np.fmod(1.0, 0.0) | Invalid | Invalid | nan | nan | No?
np.floor_divide(1.0, 0.0) | Invalid | dividebyzero | nan | inf | Yes
np.remainder(1.0, 0.0) | Invalid | Invalid | nan | nan | Yes

**Comment by anirudh2290** [comment]
I have addressed the np.fmod issue that i mentioned above , opening this up for review.

**Comment by charris** [comment]
divmod is a can of worms, so be careful. The present version may look complicated, but the simple ways are not compatible with Python nor guarantee the proper relationship between `%` and `remainder`. I haven't looked closely, but suspect you are reviving the old implementation that we had to get rid of. There are a couple of long threads about this from several years ago.

**Comment by charris** [comment]
Might be worth checking if Python has updated their implementation.

**Comment by charris** [comment]
See #7258.

**Comment by anirudh2290** [comment]
> Might be worth checking if Python has updated their implementation.

Actually i checked that, somewhat superficially, didnt look like they did. I looked at #7258 before, I will take another look at it to make sure I am not making the same mistakes again.

**Comment by anirudh2290** [comment]
hi @charris, i did check the pr  #7258. maybe i am missing something but it doesnt look like the earlier approach is similar to what we have here. that pr seems to be implementing divmod similar to python implementation and using that for remainder and floor_divide instead of earlier approach which was to use floor function and divide. This PR just special cases the edge cases like np.divmod(1.0, 0.0) or np.floor_divide(1.0, 0.0) or np.floor_div(np.inf, np.inf) and other similar use cases. for default it just goes through the divmod function. the changes in divmod also are only for divide by zero use case, others aren't touched.

File: numpy/core/tests/test_umath.py [hunk 2]
```diff
@@ -357,20 +402,47 @@ def test_float_remainder_corner_cases(self):
...
+                assert_(np.isnan(fmod), 'dt: %s, fmod: %s' % (dt, fmod))
+                assert_(np.isnan(rem), 'dt: %s, rem: %s' % (dt, rem))
+                rem = np.remainder(finf, finf)
+                fmod = np.fmod(finf, fone)
+                assert_(np.isnan(rem), 'dt: %s, rem: %s' % (dt, rem))
+                assert_(np.isnan(fmod), 'dt: %s, fmod: %s' % (dt, fmod))
+                rem = np.remainder(finf, fzer)
+                fmod = np.fmod(finf, fzer)
                 assert_(np.isnan(rem), 'dt: %s, rem: %s' % (dt, rem))
+                assert_(np.isnan(fmod), 'dt: %s, fmod: %s' % (dt, fmod))
```
Comment (seberg) [inline numpy/core/tests/test_umath.py:445]: Can just keep it, but in the future, I personally would go with the a simple `assert`. This was useful in nose, but pytest is already overly verbose anyway, the message adds nothing.

File: numpy/core/tests/test_umath.py [hunk 3]
```diff
@@ -344,6 +357,38 @@ def test_float_remainder_roundoff(self):
...
+            assert_raises(FloatingPointError, np.divmod, finf, fzero)
+        with np.errstate(invalid='raise'):
+            assert_raises(FloatingPointError, np.fmod, fone, fzero)
+
+    def test_float_remainder_overflow(self):
+        a = np.finfo(np.float64).tiny
+        with np.errstate(over='ignore', invalid='ignore'):
+            div, mod = np.divmod(4, a)
+            np.isinf(div)
+            assert_(mod == 0)
```
Comment (seberg) [inline numpy/core/tests/test_umath.py:390]: Should we test that these warnings are given, or did that fail on some hardware?

**Review by seberg — COMMENTED** [review]
Thanks looks good to me, I doubt there is another approach but to check for these values specifically and the tests look pretty thorough although I did not yet go through in depth. Probably will have to take another look before merging, sorry if that makes it a multi-pass review.

**Comment by anirudh2290** [comment]
> Thanks looks good to me, I doubt there is another approach but to check for these values specifically and the tests look pretty thorough although I did not yet go through in depth. Probably will have to take another look before merging, sorry if that makes it a multi-pass review.

Thanks @seberg for the review !! will address the comments later today or tomorrow. I am totally fine with the multi-pass review.

File: numpy/core/tests/test_umath.py (hunk 3 above)
Comment (anirudh2290) [reply numpy/core/tests/test_umath.py:390]: we ensure the errors invalid and dividebyzero are raised for divmod in line 370 to 373. Is this what you are looking for ?

File: numpy/core/tests/test_umath.py (hunk 2 above)
Comment (anirudh2290) [reply numpy/core/tests/test_umath.py:445]: sure, noted!

File: numpy/core/tests/test_umath.py (hunk 3 above)
Comment (seberg) [reply numpy/core/tests/test_umath.py:390]: Yeah, I guess I meant the specific case for `tiny`.

File: numpy/core/src/npymath/npy_math_internal.h.src [hunk 4]
```diff
@@ -635,11 +703,14 @@ npy_divmod@c@(@type@ a, @type@ b, @type@ *modulus)
     @type@ div, mod, floordiv;
 
     mod = npy_fmod@c@(a, b);
-
     if (!b) {
+        div = a / b;
+        if (a) {
```
[the remark this answers is not in the document]
Comment (anirudh2290) [reply numpy/core/src/npymath/npy_math_internal.h.src:710]: yeah good point. I don't actually remember now why I didnt check for nan. The current code before this change, doesnt signal anything on divmod(nan, 0). Maybe that was the correct behavior and it should be a quiet nan, also seems to be compatible with IEEE 754.

>  I.e. if isnan(result): see_if_we_need_to_set_errors with the assumption that we have to set errors very rarely.

do you mean checking "div" for isnan here ? probably need to change it for the other wrappers for divmod, and fmod too.

[the remark this answers is not in the document]
Comment (seberg) [reply numpy/core/src/npymath/npy_math_internal.h.src:710]: Yes, its more of a curiosity whether that might be slightly quicker (you only need to check one value in most cases).

Signalling NaNs are a bit annoying, I am not sure we really support them to be honest...

[the remark this answers is not in the document]
Comment (anirudh2290) [reply numpy/core/src/npymath/npy_math_internal.h.src:710]: > Signalling NaNs are a bit annoying, I am not sure we really support them to be honest...

I thought in numpy context signalling nans means raising the invalid error. maybe i am misunderstanding ?

**Comment by anirudh2290** [comment]
I guess I messed up with the rebase here. Let me try and fix this.

File: numpy/core/src/npymath/npy_math_internal.h.src [hunk 5]
```diff
@@ -635,11 +711,14 @@ npy_divmod@c@(@type@ a, @type@ b, @type@ *modulus)
     @type@ div, mod, floordiv;
 
     mod = npy_fmod@c@(a, b);
```
Comment (anirudh2290) [inline numpy/core/src/npymath/npy_math_internal.h.src:713]: The current failures in CI are because of this line. The CI in windows seems to be using GCC-8. I tried with GCC-8 and GCC-9 and on both, this line sets the invalid flag and raises error on python side. on GCC-5.4 (which was my default) it didnt set a flag and just set the result to nan. Looking for advice here, should we try to workaround the compiler behavior for GCC-8 and GCC-9, to stick to existing numpy behavior which we have for earlier compiler versions ? CON: Makes code slightly more convoluted. PRO: Will provide uniform behavior across different numpy builds.
( We already went down this path since we are trying to make it consistent on clang with the npy_set_floatstatus_divbyzero changes)

Comment (anirudh2290) [reply numpy/core/src/npymath/npy_math_internal.h.src:722]: i have added nan checks, so that this provides uniform builds, atleast for the CI.

**Comment by rgommers** [comment]
This looks about ready, is it good to go from your perspective @anirudh2290?

**Comment by anirudh2290** [comment]
Thanks for the ping @rgommers ! From my perspective this was ready. Although, the pytorch PR related to raising a domain error for integer np.fmod(1, 0) operations is something this PR doesn't address. 

It addresses the changes given in this table: 


Operator | Warning Message | warning after code change | Result | Result After code change | Works as expected on MacOS
-- | -- | -- | -- | -- | --
np.divmod(1.0, 0.0) | Invalid | Invalid and Dividebyzero | nan, nan | inf, nan | Yes
np.fmod(1.0, 0.0) | Invalid | Invalid | nan | nan | No? Yes
np.floor_divide(1.0, 0.0) | Invalid | dividebyzero | nan | inf | Yes
np.remainder(1.0, 0.0) | Invalid | Invalid | nan | nan | Yes


It also addresses some behavior changes between different compiler versions for nan or inf usages in these operations. Earlier, this was compiler dependent, now we force set the invalid and divide by zero flags for the operations in the table and it should behave uniformly when compiled with gcc-5 or gcc-8 / gcc-9 for example.

**Comment by charris** [comment]
This could use a release note under `compatibility` since it changes behavior.

**Comment by seberg** [comment]
Yeah, this should really be good. There were some smaller reorganization tries I was curious about, but never went down the road, I will try to put that on my TODO list to finish this off.

**Comment by charris** [comment]
@anirudh2290 Could you add a release note? Look in `doc/release/upcoming_changes` to see how it is done.

**Comment by charris** [comment]
I like to make the table part of the release notes. Pandoc translates it to rst without problems but I'd like to check the result first. Anyone know a good linux viewer for rst?

**Comment by mattip** [comment]
@charris: try pasting the text below into https://livesphinx.herokuapp.com/
```
From my perspective this was ready. 
Although, the pytorch PR related to raising a domain error for integer np.fmod(1, 0) 
operations is something this PR doesn't address. 

It addresses the changes given in this table: 

.. list-table:: Some effective title
   :widths: 10 10 25 20 25 10
   :header-rows: 1

   * - Operator
     - Warning Message
     - Result
     - warning after code change
     - Result After code change
     - Works as expected on MacOS
   * - np.divmod(1.0, 0.0)
     - Invalid 
     - Invalid and Dividebyzero
     - nan, nan
     - inf, nan
     - Yes
   * - np.fmod(1.0, 0.0)
     - Invalid 
     - Invalid
     - nan
     - nan
     - No? Yes
   * - np.floor_divide(1.0, 0.0)
     - Invalid 
     - dividebyzero
     - nan
     - inf
     - Yes
   * - np.remainder(1.0, 0.0)
     - Invalid 
     - Invalid
     - nan
     - nan
     - Yes


It also addresses some behavior changes between different compiler versions for nan
or inf usages in these operations. Earlier, this was compiler dependent, now we force
set the invalid and divide by zero flags for the operations in the table and it should behave
 uniformly when compiled with gcc-5 or gcc-8 / gcc-9 for example.
```

**Comment by charris** [comment]
Putting this in, I'll make another PR for the release note.

**Comment by anirudh2290** [comment]
Apologies for missing the notification here. Thank you for merging this @charris :)
