### PR TITLE
BUG: Fix segfault in PyArray_OrderConverter

### LINKED ISSUE #7475: BUG: segfault in PyArray_OrderConverter with non-ASCII unicode value
Passing a unicode string that cannot be converted to ASCII to `PyArray_OrderConverter` segfaults:

```Python
>>> a = np.arange(5)
>>> a.flatten(u'\xe2')
```

The issue seems to be the `Py_DECREF` [here](https://github.com/numpy/numpy/blob/maintenance/1.11.x/numpy/core/src/multiarray/conversion_utils.c#L541) on an object that is NULL when the previous call to `PyUnicode_AsASCIIString` failed.

### PR DESCRIPTION
**Pull request by simongibbons**
This fixes a bug in PyArray_OrderConverter where
if a unicode string is passed in which cannot
be converted to ASCII then Py_DECREF would
be called on a null pointer.

Fixes #7475

### CODE REVIEW

File: numpy/core/src/multiarray/conversion_utils.c [hunk 1]
```diff
@@ -535,6 +535,13 @@ PyArray_OrderConverter(PyObject *object, NPY_ORDER *val)
         PyObject *tmp;
         int ret;
         tmp = PyUnicode_AsASCIIString(object);
+        if(tmp == NULL) {
```
Comment (jaimefrio) [inline numpy/core/src/multiarray/conversion_utils.c]: Space missing after `if`.

**Comment by jaimefrio** [comment]
Mostly LGTM, small format nitpick aside. When looking at this I was surprised to find out that a `TypeError` is being raised if you e.g. pass in `order='J'`, when the sensible thing seems to be a `ValueError`as you are doing.

**Comment by simongibbons** [comment]
Cool I've changed that, do you want me to switch to a `TypeError` to ensure consistency, or change the other case to a `ValueError` (although that could break some peoples code...)

**Comment by jaimefrio** [comment]
I think it has to be a `ValueError`, so lets not break this to conform to some past mistake. Changing the other may be trickier, and would probably require a deprecation cycle, so I wouldn't worry about it in this PR: go ahead and squash your commits and I'll be happy to merge it.

**Comment by simongibbons** [comment]
Squashed.

**Comment by jaimefrio** [comment]
Thanks Simon!
