### PR TITLE
BUG: Fix float128 FPE handling on ARM64 with Clang compiler

### LINKED ISSUE #26910: BUG: Failed to build from source
## Describe the issue:

Hi. I tried to build NumPy from source with clang. While this journey I found few problems:
- failed tests
- linking problems
- crashed compiler

Enjoy the report

## Reproduce the code example:

- Clone repo:
```shell
$ git clone --recursive --branch=v2.0.0 git@github.com:numpy/numpy.git
$ cd numpy
```

- Add Dockerfile:
```Dockerfile
# https://stackoverflow.com/a/54386573
# GCC_ASAN_PRELOAD_PATH=$(gcc -print-file-name=libasan.so)
# CLANG_ASAN_PRELOAD_PATH=$(clang -print-file-name=libclang_rt.asan-x86_64.so)


ARG ENV="ubuntu_gcc_env"

FROM ubuntu:24.04 as ubuntu_env
RUN apt-get update -y && \
    apt-get install -y \
        gfortran \
        liblapack-dev \
        libopenblas-dev \
        pkg-config \
        python3-dbg \
        python3-dev \
        python3-dev \
        python3-pip \
        python3-venv



FROM ubuntu_env as ubuntu_gcc_env
RUN apt-get install -y \
        gcc \
        g++



FROM ubuntu_gcc_env as ubuntu_gcc_asan_env
ENV CFLAGS="-g -O0 -fsanitize=address" \
    CCFLAGS="-g -O0 -fsanitize=address" \
    CXXFLAGS="-g -O0 -fsanitize=address" \
    CPPFLAGS="-g -O0 -fsanitize=address" \
    LDFLAGS="-fsanitize=address" \
    LD_PRELOAD="/usr/lib/gcc/aarch64-linux-gnu/13/libasan.so" \
    ASAN_OPTIONS="detect_leaks=0" 



FROM ubuntu_gcc_env as ubuntu_gcc_hwasan_env
ENV CFLAGS="-g -O0 -fsanitize=hwaddress" \
    CCFLAGS="-g -O0 -fsanitize=hwaddress" \
    CXXFLAGS="-g -O0 -fsanitize=hwaddress" \
    CPPFLAGS="-g -O0 -fsanitize=hwaddress" \
    LDFLAGS="-fsanitize=hwaddress" \
    # LD_PRELOAD="/usr/lib/gcc/aarch64-linux-gnu/13/libhwasan.so" \
    ASAN_OPTIONS="detect_leaks=0" \
    HWASAN_OPTIONS="detect_leaks=0"



FROM ubuntu_env as ubuntu_clang18_env
RUN apt-get install -y \
        clang \
        clang-tools \
        lld
RUN rm /usr/bin/ld && \
    ln -s /usr/bin/ld.lld /usr/bin/ld
ENV CC=clang \
    CXX=clang++



FROM ubuntu_clang18_env as ubuntu_clang18_asan_env
ENV CFLAGS="-g -O0 -fsanitize=address -shared-libsan" \
    CCFLAGS="-g -O0 -fsanitize=address -shared-libsan" \
    CXXFLAGS="-g -O0 -fsanitize=address -shared-libsan" \
    CPPFLAGS="-g -O0 -fsanitize=address -shared-libsan" \
    LDFLAGS="-fsanitize=address -shared-libsan" \
    LD_PRELOAD="/usr/lib/llvm-18/lib/clang/18/lib/linux/libclang_rt.asan-aarch64.so" \
    ASAN_OPTIONS="detect_leaks=0"



FROM ubuntu_clang18_env as ubuntu_clang18_hwasan_env
ENV CFLAGS="-g -O0 -fsanitize=hwaddress -shared-libsan" \
    CCFLAGS="-g -O0 -fsanitize=hwaddress -shared-libsan" \
    CXXFLAGS="-g -O0 -fsanitize=hwaddress -shared-libsan" \
    CPPFLAGS="-g -O0 -fsanitize=hwaddress -shared-libsan" \
    LDFLAGS="-fsanitize=hwaddress -shared-libsan" \
    LD_PRELOAD="/usr/lib/llvm-18/lib/clang/18/lib/linux/libclang_rt.hwasan-aarch64.so" \
    ASAN_OPTIONS="detect_leaks=0" \
    HWASAN_OPTIONS="detect_leaks=0"



FROM ubuntu_env as ubuntu_clang19_env
RUN apt-get install -y \
    lsb-release \
    wget \
    software-properties-common \
    gnupg
RUN wget https://apt.llvm.org/llvm.sh && \
    chmod +x llvm.sh && \
    ./llvm.sh 19 && \
    ln -s /usr/bin/lld-19 /usr/local/bin/lld && \
    ln -s /usr/bin/clang-19 /usr/local/bin/clang && \
    ln -s /usr/bin/clang++-19 /usr/local/bin/clang++ && \
    rm /usr/bin/ld && \
    ln -s /usr/lib/llvm-19/bin/ld.lld /usr/bin/ld
ENV CC=clang \
    CXX=clang++




FROM ubuntu_clang19_env as ubuntu_clang19_asan_env
ENV CFLAGS="-g -O0 -fsanitize=address -shared-libsan" \
    CCFLAGS="-g -O0 -fsanitize=address -shared-libsan" \
    CXXFLAGS="-g -O0 -fsanitize=address -shared-libsan" \
    CPPFLAGS="-g -O0 -fsanitize=address -shared-libsan" \
    LDFLAGS="-fsanitize=address -shared-libsan" \
    LD_PRELOAD="/usr/lib/llvm-19/lib/clang/19/lib/linux/libclang_rt.asan-aarch64.so" \
    ASAN_OPTIONS="detect_leaks=0"




FROM ubuntu_clang19_env as ubuntu_clang19_hwasan_env
ENV CFLAGS="-g -O0 -fsanitize=hwaddress -shared-libsan" \
    CCFLAGS="-g -O0 -fsanitize=hwaddress -shared-libsan" \
    CXXFLAGS="-g -O0 -fsanitize=hwaddress -shared-libsan" \
    CPPFLAGS="-g -O0 -fsanitize=hwaddress -shared-libsan" \
    LDFLAGS="-fsanitize=hwaddress -shared-libsan" \
    LD_PRELOAD="/usr/lib/llvm-19/lib/clang/19/lib/linux/libclang_rt.hwasan-aarch64.so" \
    ASAN_OPTIONS="detect_leaks=0" \
    HWASAN_OPTIONS="detect_leaks=0"



FROM ${ENV} as build_env
COPY . /src
WORKDIR /src
RUN python3 -m venv /venv && \
    . /venv/bin/activate && \
    pip3 install -r requirements/all_requirements.txt
```

- Add docker-compose.yaml:
```yaml
version: '3.8'

services:
  ubuntu_gcc_env:
    build:
      target: build_env
      args:
        ENV: ubuntu_gcc_env

  ubuntu_gcc_asan_env:
    build:
      target: build_env
      args:
        ENV: ubuntu_gcc_asan_env

  ubuntu_gcc_hwasan_env:
    build:
      target: build_env
      args:
        ENV: ubuntu_gcc_hwasan_env

  ubuntu_clang18_env:
    build:
      target: build_env
      args:
        ENV: ubuntu_clang18_env

  ubuntu_clang18_asan_env:
    build:
      target: build_env
      args:
        ENV: ubuntu_clang18_asan_env

  ubuntu_clang18_hwasan_env:
    build:
      target: build_env
      args:
        ENV: ubuntu_clang18_hwasan_env

  ubuntu_clang19_env:
    build:
      target: build_env
      args:
        ENV: ubuntu_clang19_env

  ubuntu_clang19_asan_env:
    build:
      target: build_env
      args:
        ENV: ubuntu_clang19_asan_env

  ubuntu_clang19_hwasan_env:
    build:
      target: build_env
      args:
        ENV: ubuntu_clang19_hwasan_env
```
- Build images
```
$ docker compose build
```
- Run commands in environment
```shell
$ source /venv/bin/activate
$ spin build
$ spin test
```

## Versions

```shell
$ gcc --version
gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```shell
$ python3 --version
Python 3.12.3
```

```shell
$ clang --version
Ubuntu clang version 18.1.3 (1ubuntu1)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

```shell
$ clang --version
Ubuntu clang version 19.0.0 (++20240709081800+2c42c2263dc6-1~exp1~20240709201923.273)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-19/bin
```

```shell
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

```shell
$ docker version
Client:
 Cloud integration: v1.0.35+desktop.13
 Version:           26.1.1
 API version:       1.45
 Go version:        go1.21.9
 Git commit:        4cf5afa
 Built:             Tue Apr 30 11:44:56 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.30.0 (149282)
 Engine:
  Version:          26.1.1
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.9
  Git commit:       ac2de55
  Built:            Tue Apr 30 11:48:04 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.31
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### ubuntu_gcc_env
OK
```shell
$ docker compose run ubuntu_gcc_env
$ source /venv/bin/activate
$ spin build 
OK
$ spin test
43233 passed, 890 skipped, 2785 deselected, 58 xfailed, 5 xpassed in 97.26s (0:01:37)
```

### ubuntu_gcc_asan_env
Stops with no reason
```shell
$ docker compose run ubuntu_gcc_asan_env
$ source /venv/bin/activate
$ spin build 
OK
$ spin test
Invoking `build` prior to running tests:
$ /venv/bin/python3 vendored-meson/meson/meson.py compile -C build
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /venv/bin/ninja -C /src/build
ninja: Entering directory `/src/build'
[1/1] Generating numpy/generate-version with a custom command
Saving version to numpy/version.py
$ /venv/bin/python3 vendored-meson/meson/meson.py install --only-changed -C build --destdir ../build-install
$ export PYTHONPATH="/src/build-install/usr/lib/python3/dist-packages"
$ /venv/bin/python3 -P -c 'import numpy'
$ export PYTHONPATH="/src/build-install/usr/lib/python3/dist-packages"
$ cd /src/build-install/usr/lib/python3/dist-packages
$ /venv/bin/python3 -m pytest --rootdir=/src/build-install/usr/lib/python3/dist-packages -m 'not slow' numpy
===================================================================================================== test session starts =====================================================================================================
platform linux -- Python 3.12.3, pytest-7.4.0, pluggy-1.5.0
rootdir: /src/build-install/usr/lib/python3/dist-packages
configfile: ../../../../../pytest.ini
plugins: cov-4.1.0, hypothesis-6.81.1, xdist-3.6.1
collected 46970 items / 2785 deselected / 1 skipped / 44185 selected

numpy/_core/tests/test__exceptions.py
numpy/_core/tests/test_abc.py
numpy/_core/tests/test_api.py
numpy/_core/tests/test_argparse.py
numpy/_core/tests/test_array_coercion.py .............................................................x................................................................................................................
```

### ubuntu_gcc_hwasan_env
Timeout (still waiting, ~12h)
```shell
$ docker compose run ubuntu_gcc_hwasan_env
$ source venv/bin/activate
$ spin build 
...
[319/323] Linking static target numpy/_core/libhighway_qsort_16bit.dispatch.h_ASIMDHP.a
```

### ubuntu_clang18_env
Tests failed:
```shell
$ docker compose run ubuntu_clang18_env
$ source venv/bin/activate
$ spin build 
OK
$ spin test
43233 passed, 890 skipped, 2785 deselected, 58 xfailed, 5 xpassed in 100.34s (0:01:40)

=============== FAILURES ===============
_______________ TestDivision.test_floor_division_errors[g] _______________

self = <numpy._core.tests.test_umath.TestDivision object at 0xffff74cf7800>, dtype = 'g'

    @pytest.mark.skipif(hasattr(np.__config__, "blas_ssl2_info"),
            reason="gh-22982")
    @pytest.mark.skipif(IS_WASM, reason="fp errors don't work in wasm")
    @pytest.mark.parametrize('dtype', np.typecodes['Float'])
    def test_floor_division_errors(self, dtype):
        fnan = np.array(np.nan, dtype=dtype)
        fone = np.array(1.0, dtype=dtype)
        fzer = np.array(0.0, dtype=dtype)
        finf = np.array(np.inf, dtype=dtype)
        # divide by zero error check
        with np.errstate(divide='raise', invalid='ignore'):
            assert_raises(FloatingPointError, np.floor_divide, fone, fzer)
        with np.errstate(divide='ignore', invalid='raise'):
            np.floor_divide(fone, fzer)

        # The following already contain a NaN and should not warn
        with np.errstate(all='raise'):
>           np.floor_divide(fnan, fone)
E           FloatingPointError: invalid value encountered in floor_divide

dtype      = 'g'
finf       = array(inf, dtype=float128)
fnan       = array(nan, dtype=float128)
fone       = array(1., dtype=float128)
fzer       = array(0., dtype=float128)
self       = <numpy._core.tests.test_umath.TestDivision object at 0xffff74cf7800>

numpy/_core/tests/test_umath.py:680: FloatingPointError

_______________ TestRemainder.test_float_remainder_errors[remainder-g] _______________

self = <numpy._core.tests.test_umath.TestRemainder object at 0xffff746a5640>, dtype = 'g', fn = <ufunc 'remainder'>

    @pytest.mark.skipif(hasattr(np.__config__, "blas_ssl2_info"),
            reason="gh-22982")
    @pytest.mark.skipif(IS_WASM, reason="fp errors don't work in wasm")
    @pytest.mark.xfail(sys.platform.startswith("darwin"),
           reason="MacOS seems to not give the correct 'invalid' warning for "
                  "`fmod`.  Hopefully, others always do.")
    @pytest.mark.parametrize('dtype', np.typecodes['Float'])
    @pytest.mark.parametrize('fn', [np.fmod, np.remainder])
    def test_float_remainder_errors(self, dtype, fn):
        fzero = np.array(0.0, dtype=dtype)
        fone = np.array(1.0, dtype=dtype)
        finf = np.array(np.inf, dtype=dtype)
        fnan = np.array(np.nan, dtype=dtype)

        # The following already contain a NaN and should not warn.
        with np.errstate(all='raise'):
            with pytest.raises(FloatingPointError,
                    match="invalid value"):
                fn(fone, fzero)
            fn(fnan, fzero)
>           fn(fzero, fnan)
E           FloatingPointError: invalid value encountered in remainder

dtype      = 'g'
finf       = array(inf, dtype=float128)
fn         = <ufunc 'remainder'>
fnan       = array(nan, dtype=float128)
fone       = array(1., dtype=float128)
fzero      = array(0., dtype=float128)
self       = <numpy._core.tests.test_umath.TestRemainder object at 0xffff746a5640>

numpy/_core/tests/test_umath.py:827: FloatingPointError
=============== short test summary info ===============
FAILED numpy/_core/tests/test_umath.py::TestDivision::test_floor_division_errors[g] - FloatingPointError: invalid value encountered in floor_divide
FAILED numpy/_core/tests/test_umath.py::TestRemainder::test_float_remainder_errors[remainder-g] - FloatingPointError: invalid value encountered in remainder
=============== 2 failed, 43231 passed, 890 skipped, 2785 deselected, 58 xfailed, 5 xpassed in 193.05s (0:03:13) ===============
```

### ubuntu_clang18_hwasan_env
Compiler is going down:
```
$ docker compose run ubuntu_clang18_hwasan_env
$ source venv/bin/activate
$ spin build 
[208/323] Compiling C++ object numpy/_core/libhighway_qsort.dispatch.h_SVE.a.p/src_npysort_highway_qsort.dispatch.cpp.o
FAILED: numpy/_core/libhighway_qsort.dispatch.h_SVE.a.p/src_npysort_highway_qsort.dispatch.cpp.o
clang++ -Inumpy/_core/libhighway_qsort.dispatch.h_SVE.a.p -Inumpy/_core -I../numpy/_core -Inumpy/_core/include -I../numpy/_core/include -I../numpy/_core/src/common -I../numpy/_core/src/multiarray -I../numpy/_core/src/npymath -I../numpy/_core/src/umath -I../numpy/_core/src/highway -I/usr/include/python3.12 -I/usr/include/aarch64-linux-gnu/python3.12 -I/src/build/meson_cpu -fcolor-diagnostics -Wall -Winvalid-pch -std=c++17 -O2 -g -ftrapping-math -DNPY_HAVE_CLANG_FPSTRICT -g -O0 -fsanitize=hwaddress -shared-libsan -g -O0 -fsanitize=hwaddress -shared-libsan -fPIC -DNPY_INTERNAL_BUILD -DHAVE_NPY_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -D__STDC_VERSION__=0 -fno-exceptions -fno-rtti -O3 -DNPY_HAVE_NEON_VFPV4 -DNPY_HAVE_NEON_FP16 -DNPY_HAVE_NEON -DNPY_HAVE_ASIMD -DNPY_HAVE_ASIMDHP -DNPY_HAVE_SVE -march=armv8.2-a+sve+fp16 -DNPY_MTARGETS_CURRENT=SVE -MD -MQ numpy/_core/libhighway_qsort.dispatch.h_SVE.a.p/src_npysort_highway_qsort.dispatch.cpp.o -MF numpy/_core/libhighway_qsort.dispatch.h_SVE.a.p/src_npysort_highway_qsort.dispatch.cpp.o.d -o numpy/_core/libhighway_qsort.dispatch.h_SVE.a.p/src_npysort_highway_qsort.dispatch.cpp.o -c ../numpy/_core/src/npysort/highway_qsort.dispatch.cpp
fatal error: error in backend: Invalid size request on a scalable vector.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: clang++ -Inumpy/_core/libhighway_qsort.dispatch.h_SVE.a.p -Inumpy/_core -I../numpy/_core -Inumpy/_core/include -I../numpy/_core/include -I../numpy/_core/src/common -I../numpy/_core/src/multiarray -I../numpy/_core/src/npymath -I../numpy/_core/src/umath -I../numpy/_core/src/highway -I/usr/include/python3.12 -I/usr/include/aarch64-linux-gnu/python3.12 -I/src/build/meson_cpu -fcolor-diagnostics -Wall -Winvalid-pch -std=c++17 -O2 -g -ftrapping-math -DNPY_HAVE_CLANG_FPSTRICT -g -O0 -fsanitize=hwaddress -shared-libsan -g -O0 -fsanitize=hwaddress -shared-libsan -fPIC -DNPY_INTERNAL_BUILD -DHAVE_NPY_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -D__STDC_VERSION__=0 -fno-exceptions -fno-rtti -O3 -DNPY_HAVE_NEON_VFPV4 -DNPY_HAVE_NEON_FP16 -DNPY_HAVE_NEON -DNPY_HAVE_ASIMD -DNPY_HAVE_ASIMDHP -DNPY_HAVE_SVE -march=armv8.2-a+sve+fp16 -DNPY_MTARGETS_CURRENT=SVE -MD -MQ numpy/_core/libhighway_qsort.dispatch.h_SVE.a.p/src_npysort_highway_qsort.dispatch.cpp.o -MF numpy/_core/libhighway_qsort.dispatch.h_SVE.a.p/src_npysort_highway_qsort.dispatch.cpp.o.d -o numpy/_core/libhighway_qsort.dispatch.h_SVE.a.p/src_npysort_highway_qsort.dispatch.cpp.o -c ../numpy/_core/src/npysort/highway_qsort.dispatch.cpp
1.	<eof> parser at end of file
2.	Optimizer
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libLLVM.so.18.1      0x0000ffff7eead398 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 84
1  libLLVM.so.18.1      0x0000ffff7eeab5a8 llvm::sys::RunSignalHandlers() + 116
2  libLLVM.so.18.1      0x0000ffff7edfb17c
3  libLLVM.so.18.1      0x0000ffff7edfb128
4  libLLVM.so.18.1      0x0000ffff7eea7fcc llvm::sys::Process::Exit(int, bool) + 52
5  clang++              0x0000aaaaaad32560
6  libLLVM.so.18.1      0x0000ffff7ee08a20 llvm::report_fatal_error(llvm::Twine const&, bool) + 248
7  libLLVM.so.18.1      0x0000ffff7ee08928 llvm::report_fatal_error(llvm::Twine const&, bool) + 0
8  libLLVM.so.18.1      0x0000ffff7ee62334 llvm::TypeSize::operator unsigned long() const + 0
9  libLLVM.so.18.1      0x0000ffff7ee6235c llvm::TypeSize::operator unsigned long() const + 40
10 libLLVM.so.18.1      0x0000ffff7fa12940 llvm::memtag::StackInfoBuilder::isInterestingAlloca(llvm::AllocaInst const&) + 276
11 libLLVM.so.18.1      0x0000ffff7fa124f0 llvm::memtag::StackInfoBuilder::visit(llvm::Instruction&) + 136
12 libLLVM.so.18.1      0x0000ffff7fb474e0
13 libLLVM.so.18.1      0x0000ffff7fb47210 llvm::HWAddressSanitizerPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) + 6552
14 libLLVM.so.18.1      0x0000ffff7f03a09c llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) + 332
15 libclang-cpp.so.18.1 0x0000ffff86f72fe0
16 libclang-cpp.so.18.1 0x0000ffff86f6b918 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) + 1844
17 libclang-cpp.so.18.1 0x0000ffff87285f58 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) + 1180
18 libclang-cpp.so.18.1 0x0000ffff85eea5b0 clang::ParseAST(clang::Sema&, bool, bool) + 572
19 libclang-cpp.so.18.1 0x0000ffff87c9fa34 clang::FrontendAction::Execute() + 112
20 libclang-cpp.so.18.1 0x0000ffff87c30590 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 744
21 libclang-cpp.so.18.1 0x0000ffff87d18e4c clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 616
22 clang++              0x0000aaaaaad321c4 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 3360
23 clang++              0x0000aaaaaad2fbac
24 libclang-cpp.so.18.1 0x0000ffff8792a950
25 libLLVM.so.18.1      0x0000ffff7edfb0f8 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) + 168
26 libclang-cpp.so.18.1 0x0000ffff8792a1bc clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const + 352
27 libclang-cpp.so.18.1 0x0000ffff878f8d3c clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const + 756
28 libclang-cpp.so.18.1 0x0000ffff878f8f4c clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const + 136
29 libclang-cpp.so.18.1 0x0000ffff879112f4 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) + 324
30 clang++              0x0000aaaaaad2f344 clang_main(int, char**, llvm::ToolContext const&) + 9756
31 clang++              0x0000aaaaaad3ae40 main + 92
32 libc.so.6            0x0000ffff7dcf84c4
33 libc.so.6            0x0000ffff7dcf8598 __libc_start_main + 152
34 clang++              0x0000aaaaaad2c970 _start + 48
clang++: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Ubuntu clang version 18.1.3 (1ubuntu1)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang++: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/highway_qsort-02f1d0.cpp
clang++: note: diagnostic msg: /tmp/highway_qsort-02f1d0.sh
clang++: note: diagnostic msg:

********************
[223/323] Compiling C++ object numpy/_core/_multiarray_umath.cpython-312-aarch64-linux-gnu.so.p/src_npysort_timsort.cpp.o
ninja: build stopped: subcommand failed.
```

### ubuntu_clang19_env
Tests failed:
```shell
$ docker compose run ubuntu_clang19_env
$ spin build
OK
$ spin test
=============== FAILURES ===============
_______________ TestDivision.test_floor_division_errors[g] _______________

self = <numpy._core.tests.test_umath.TestDivision object at 0xffff6c7af5f0>, dtype = 'g'

    @pytest.mark.skipif(hasattr(np.__config__, "blas_ssl2_info"),
            reason="gh-22982")
    @pytest.mark.skipif(IS_WASM, reason="fp errors don't work in wasm")
    @pytest.mark.parametrize('dtype', np.typecodes['Float'])
    def test_floor_division_errors(self, dtype):
        fnan = np.array(np.nan, dtype=dtype)
        fone = np.array(1.0, dtype=dtype)
        fzer = np.array(0.0, dtype=dtype)
        finf = np.array(np.inf, dtype=dtype)
        # divide by zero error check
        with np.errstate(divide='raise', invalid='ignore'):
            assert_raises(FloatingPointError, np.floor_divide, fone, fzer)
        with np.errstate(divide='ignore', invalid='raise'):
            np.floor_divide(fone, fzer)

        # The following already contain a NaN and should not warn
        with np.errstate(all='raise'):
>           np.floor_divide(fnan, fone)
E           FloatingPointError: invalid value encountered in floor_divide

dtype      = 'g'
finf       = array(inf, dtype=float128)
fnan       = array(nan, dtype=float128)
fone       = array(1., dtype=float128)
fzer       = array(0., dtype=float128)
self       = <numpy._core.tests.test_umath.TestDivision object at 0xffff6c7af5f0>

numpy/_core/tests/test_umath.py:680: FloatingPointError
_______________ TestRemainder.test_float_remainder_errors[remainder-g] _______________

self = <numpy._core.tests.test_umath.TestRemainder object at 0xffff6c165430>, dtype = 'g', fn = <ufunc 'remainder'>

    @pytest.mark.skipif(hasattr(np.__config__, "blas_ssl2_info"),
            reason="gh-22982")
    @pytest.mark.skipif(IS_WASM, reason="fp errors don't work in wasm")
    @pytest.mark.xfail(sys.platform.startswith("darwin"),
           reason="MacOS seems to not give the correct 'invalid' warning for "
                  "`fmod`.  Hopefully, others always do.")
    @pytest.mark.parametrize('dtype', np.typecodes['Float'])
    @pytest.mark.parametrize('fn', [np.fmod, np.remainder])
    def test_float_remainder_errors(self, dtype, fn):
        fzero = np.array(0.0, dtype=dtype)
        fone = np.array(1.0, dtype=dtype)
        finf = np.array(np.inf, dtype=dtype)
        fnan = np.array(np.nan, dtype=dtype)

        # The following already contain a NaN and should not warn.
        with np.errstate(all='raise'):
            with pytest.raises(FloatingPointError,
                    match="invalid value"):
                fn(fone, fzero)
            fn(fnan, fzero)
>           fn(fzero, fnan)
E           FloatingPointError: invalid value encountered in remainder

dtype      = 'g'
finf       = array(inf, dtype=float128)
fn         = <ufunc 'remainder'>
fnan       = array(nan, dtype=float128)
fone       = array(1., dtype=float128)
fzero      = array(0., dtype=float128)
self       = <numpy._core.tests.test_umath.TestRemainder object at 0xffff6c165430>

numpy/_core/tests/test_umath.py:827: FloatingPointError
=============== short test summary info ===============
FAILED numpy/_core/tests/test_umath.py::TestDivision::test_floor_division_errors[g] - FloatingPointError: invalid value encountered in floor_divide
FAILED numpy/_core/tests/test_umath.py::TestRemainder::test_float_remainder_errors[remainder-g] - FloatingPointError: invalid value encountered in remainder
=============== 2 failed, 43231 passed, 890 skipped, 2785 deselected, 58 xfailed, 5 xpassed in 98.56s (0:01:38) ===============
```

### ubuntu_clang19_asan_env
undefined symbol: _ZN3hwy11VectorBytesEv
```shell
$ docker compose run ubuntu_clang19_asan_env
$ spin build
OK
$ spin test
Invoking `build` prior to running tests:
$ /venv/bin/python3 vendored-meson/meson/meson.py compile -C build
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /venv/bin/ninja -C /src/build
ninja: Entering directory `/src/build'
[1/1] Generating numpy/generate-version with a custom command
Saving version to numpy/version.py
$ /venv/bin/python3 vendored-meson/meson/meson.py install --only-changed -C build --destdir ../build-install
$ export PYTHONPATH="/src/build-install/usr/lib/python3/dist-packages"
$ /venv/bin/python3 -P -c 'import numpy'
Traceback (most recent call last):
  File "/src/build-install/usr/lib/python3/dist-packages/numpy/_core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/src/build-install/usr/lib/python3/dist-packages/numpy/_core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/src/build-install/usr/lib/python3/dist-packages/numpy/_core/overrides.py", line 8, in <module>
    from numpy._core._multiarray_umath import (
ImportError: /src/build-install/usr/lib/python3/dist-packages/numpy/_core/_multiarray_umath.cpython-312-aarch64-linux-gnu.so: undefined symbol: _ZN3hwy11VectorBytesEv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/build-install/usr/lib/python3/dist-packages/numpy/__init__.py", line 114, in <module>
    from numpy.__config__ import show as show_config
  File "/src/build-install/usr/lib/python3/dist-packages/numpy/__config__.py", line 4, in <module>
    from numpy._core._multiarray_umath import (
  File "/src/build-install/usr/lib/python3/dist-packages/numpy/_core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.12 from "/venv/bin/python3"
  * The NumPy version is: "2.0.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: /src/build-install/usr/lib/python3/dist-packages/numpy/_core/_multiarray_umath.cpython-312-aarch64-linux-gnu.so: undefined symbol: _ZN3hwy11VectorBytesEv


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/src/build-install/usr/lib/python3/dist-packages/numpy/__init__.py", line 119, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
As a sanity check, we tried to import numpy.
Stopping. Please investigate the build error.
```

### ubuntu_clang19_hwasan_env
Build failed: HWAddressSanitizer: tag-mismatch
```shell
$ docker compose run ubuntu_clang19_hwasan_env
$ spin build
Invoking `build` prior to running tests:
$ /venv/bin/python3 vendored-meson/meson/meson.py compile -C build
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /venv/bin/ninja -C /src/build
ninja: Entering directory `/src/build'
[1/1] Generating numpy/generate-version with a custom command
Saving version to numpy/version.py
$ /venv/bin/python3 vendored-meson/meson/meson.py install --only-changed -C build --destdir ../build-install
$ export PYTHONPATH="/src/build-install/usr/lib/python3/dist-packages"
$ /venv/bin/python3 -P -c 'import numpy'
==3669==ERROR: HWAddressSanitizer: tag-mismatch on address 0xffff923937a0 at pc 0xffff94427ec4
WRITE of size 353 at 0xffff923937a0 tags: ab/00 (ptr/mem) in thread T0
    #0 0xffff94427ec4 in __hwasan_memset (/usr/lib/llvm-19/lib/clang/19/lib/linux/libclang_rt.hwasan-aarch64.so+0x27ec4) (BuildId: 2f010f5286219c795eacb8b5bf9bef0e613730c3)
    #1 0xffff91e86c14 in npy__cpu_init_features /src/build/../numpy/_core/src/common/npy_cpu_features.c:780:5
    #2 0xffff91e86510 in npy_cpu_init /src/build/../numpy/_core/src/common/npy_cpu_features.c:44:5
    #3 0xffff917e62fc in PyInit__multiarray_umath /src/build/../numpy/_core/src/multiarray/multiarraymodule.c:4971:9
    #4 0x66def0 in _PyImport_LoadDynamicModuleWithSpec /usr/src/python3.12-3.12.3-1/build-static/../Python/importdl.c:169:9
    #5 0x66d338 in _imp_create_dynamic_impl /usr/src/python3.12-3.12.3-1/build-static/../Python/import.c:3775:11
    #6 0x66d338 in _imp_create_dynamic /usr/src/python3.12-3.12.3-1/build-static/../Python/clinic/import.c.h:506:20
    #7 0x502d4c in cfunction_vectorcall_FASTCALL /usr/src/python3.12-3.12.3-1/build-static/../Objects/methodobject.c:422:24
    #8 0x5652ac in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1/build-static/Python/bytecodes.c:3254:26
    #9 0x4c2f00 in _PyObject_VectorcallTstate /usr/src/python3.12-3.12.3-1/build-static/../Include/internal/pycore_call.h:92:11
    #10 0x4c2f00 in object_vacall /usr/src/python3.12-3.12.3-1/build-static/../Objects/call.c:850:14
    #11 0x4c4ae4 in PyObject_CallMethodObjArgs /usr/src/python3.12-3.12.3-1/build-static/../Objects/call.c:911:24
    #12 0x58bee8 in import_find_and_load /usr/src/python3.12-3.12.3-1/build-static/../Python/import.c:2779:11
    #13 0x58bee8 in PyImport_ImportModuleLevelObject /usr/src/python3.12-3.12.3-1/build-static/../Python/import.c:2862:15
    #14 0x565f6c in import_name /usr/src/python3.12-3.12.3-1/build-static/../Python/ceval.c:2482:15
    #15 0x565f6c in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1/build-static/Python/bytecodes.c:2135:19
    #16 0x560070 in _PyEval_EvalFrame /usr/src/python3.12-3.12.3-1/build-static/../Include/internal/pycore_ceval.h:89:16
    #17 0x560070 in _PyEval_Vector /usr/src/python3.12-3.12.3-1/build-static/../Python/ceval.c:1683:12
    #18 0x560070 in PyEval_EvalCode /usr/src/python3.12-3.12.3-1/build-static/../Python/ceval.c:578:21
    #19 0x55d264 in builtin_exec_impl /usr/src/python3.12-3.12.3-1/build-static/../Python/bltinmodule.c:1096:17
    #20 0x55d264 in builtin_exec /usr/src/python3.12-3.12.3-1/build-static/../Python/clinic/bltinmodule.c.h:586:20
    #21 0x502a38 in cfunction_vectorcall_FASTCALL_KEYWORDS /usr/src/python3.12-3.12.3-1/build-static/../Objects/methodobject.c:438:24
    #22 0x5652ac in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1/build-static/Python/bytecodes.c:3254:26
    #23 0x4c2f00 in _PyObject_VectorcallTstate /usr/src/python3.12-3.12.3-1/build-static/../Include/internal/pycore_call.h:92:11
    #24 0x4c2f00 in object_vacall /usr/src/python3.12-3.12.3-1/build-static/../Objects/call.c:850:14
    #25 0x4c4ae4 in PyObject_CallMethodObjArgs /usr/src/python3.12-3.12.3-1/build-static/../Objects/call.c:911:24
    #26 0x58bee8 in import_find_and_load /usr/src/python3.12-3.12.3-1/build-static/../Python/import.c:2779:11
    #27 0x58bee8 in PyImport_ImportModuleLevelObject /usr/src/python3.12-3.12.3-1/build-static/../Python/import.c:2862:15
    #28 0x55d754 in builtin___import___impl /usr/src/python3.12-3.12.3-1/build-static/../Python/bltinmodule.c:275:12
    #29 0x55d754 in builtin___import__ /usr/src/python3.12-3.12.3-1/build-static/../Python/clinic/bltinmodule.c.h:107:20
    #30 0x502a38 in cfunction_vectorcall_FASTCALL_KEYWORDS /usr/src/python3.12-3.12.3-1/build-static/../Objects/methodobject.c:438:24
    #31 0x5652ac in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1/build-static/Python/bytecodes.c:3254:26
    #32 0x4c2f00 in _PyObject_VectorcallTstate /usr/src/python3.12-3.12.3-1/build-static/../Include/internal/pycore_call.h:92:11
    #33 0x4c2f00 in object_vacall /usr/src/python3.12-3.12.3-1/build-static/../Objects/call.c:850:14
    #34 0x4c4ae4 in PyObject_CallMethodObjArgs /usr/src/python3.12-3.12.3-1/build-static/../Objects/call.c:911:24
    #35 0x58c120 in PyImport_ImportModuleLevelObject /usr/src/python3.12-3.12.3-1/build-static/../Python/import.c:2931:25
    #36 0x565f6c in import_name /usr/src/python3.12-3.12.3-1/build-static/../Python/ceval.c:2482:15
    #37 0x565f6c in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1/build-static/Python/bytecodes.c:2135:19
    #38 0x560070 in _PyEval_EvalFrame /usr/src/python3.12-3.12.3-1/build-static/../Include/internal/pycore_ceval.h:89:16
    #39 0x560070 in _PyEval_Vector /usr/src/python3.12-3.12.3-1/build-static/../Python/ceval.c:1683:12
    #40 0x560070 in PyEval_EvalCode /usr/src/python3.12-3.12.3-1/build-static/../Python/ceval.c:578:21
    #41 0x55d264 in builtin_exec_impl /usr/src/python3.12-3.12.3-1/build-static/../Python/bltinmodule.c:1096:17
    #42 0x55d264 in builtin_exec /usr/src/python3.12-3.12.3-1/build-static/../Python/clinic/bltinmodule.c.h:586:20
    #43 0x502a38 in cfunction_vectorcall_FASTCALL_KEYWORDS /usr/src/python3.12-3.12.3-1/build-static/../Objects/methodobject.c:438:24
    #44 0x5652ac in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1/build-static/Python/bytecodes.c:3254:26
    #45 0x4c2f00 in _PyObject_VectorcallTstate /usr/src/python3.12-3.12.3-1/build-static/../Include/internal/pycore_call.h:92:11
    #46 0x4c2f00 in object_vacall /usr/src/python3.12-3.12.3-1/build-static/../Objects/call.c:850:14
    #47 0x4c4ae4 in PyObject_CallMethodObjArgs /usr/src/python3.12-3.12.3-1/build-static/../Objects/call.c:911:24
    #48 0x58bee8 in import_find_and_load /usr/src/python3.12-3.12.3-1/build-static/../Python/import.c:2779:11
    #49 0x58bee8 in PyImport_ImportModuleLevelObject /usr/src/python3.12-3.12.3-1/build-static/../Python/import.c:2862:15
    #50 0x55d754 in builtin___import___impl /usr/src/python3.12-3.12.3-1/build-static/../Python/bltinmodule.c:275:12
    #51 0x55d754 in builtin___import__ /usr/src/python3.12-3.12.3-1/build-static/../Python/clinic/bltinmodule.c.h:107:20
    #52 0x502a38 in cfunction_vectorcall_FASTCALL_KEYWORDS /usr/src/python3.12-3.12.3-1/build-static/../Objects/methodobject.c:438:24
    #53 0x5652ac in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1/build-static/Python/bytecodes.c:3254:26
    #54 0x4c2f00 in _PyObject_VectorcallTstate /usr/src/python3.12-3.12.3-1/build-static/../Include/internal/pycore_call.h:92:11
    #55 0x4c2f00 in object_vacall /usr/src/python3.12-3.12.3-1/build-static/../Objects/call.c:850:14
    #56 0x4c4ae4 in PyObject_CallMethodObjArgs /usr/src/python3.12-3.12.3-1/build-static/../Objects/call.c:911:24
    #57 0x58c120 in PyImport_ImportModuleLevelObject /usr/src/python3.12-3.12.3-1/build-static/../Python/import.c:2931:25
    #58 0x565f6c in import_name /usr/src/python3.12-3.12.3-1/build-static/../Python/ceval.c:2482:15
    #59 0x565f6c in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1/build-static/Python/bytecodes.c:2135:19
    #60 0x560070 in _PyEval_EvalFrame /usr/src/python3.12-3.12.3-1/build-static/../Include/internal/pycore_ceval.h:89:16
    #61 0x560070 in _PyEval_Vector /usr/src/python3.12-3.12.3-1/build-static/../Python/ceval.c:1683:12
    #62 0x560070 in PyEval_EvalCode /usr/src/python3.12-3.12.3-1/build-static/../Python/ceval.c:578:21
    #63 0x55d264 in builtin_exec_impl /usr/src/python3.12-3.12.3-1/build-static/../Python/bltinmodule.c:1096:17
    #64 0x55d264 in builtin_exec /usr/src/python3.12-3.12.3-1/build-static/../Python/clinic/bltinmodule.c.h:586:20
    #65 0x502a38 in cfunction_vectorcall_FASTCALL_KEYWORDS /usr/src/python3.12-3.12.3-1/build-static/../Objects/methodobject.c:438:24
    #66 0x5652ac in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1/build-static/Python/bytecodes.c:3254:26
    #67 0x4c2f00 in _PyObject_VectorcallTstate /usr/src/python3.12-3.12.3-1/build-static/../Include/internal/pycore_call.h:92:11
    #68 0x4c2f00 in object_vacall /usr/src/python3.12-3.12.3-1/build-static/../Objects/call.c:850:14
    #69 0x4c4ae4 in PyObject_CallMethodObjArgs /usr/src/python3.12-3.12.3-1/build-static/../Objects/call.c:911:24
    #70 0x58bee8 in import_find_and_load /usr/src/python3.12-3.12.3-1/build-static/../Python/import.c:2779:11
    #71 0x58bee8 in PyImport_ImportModuleLevelObject /usr/src/python3.12-3.12.3-1/build-static/../Python/import.c:2862:15
    #72 0x55d754 in builtin___import___impl /usr/src/python3.12-3.12.3-1/build-static/../Python/bltinmodule.c:275:12
    #73 0x55d754 in builtin___import__ /usr/src/python3.12-3.12.3-1/build-static/../Python/clinic/bltinmodule.c.h:107:20
    #74 0x502a38 in cfunction_vectorcall_FASTCALL_KEYWORDS /usr/src/python3.12-3.12.3-1/build-static/../Objects/methodobject.c:438:24
    #75 0x5652ac in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1/build-static/Python/bytecodes.c:3254:26
    #76 0x4c2f00 in _PyObject_VectorcallTstate /usr/src/python3.12-3.12.3-1/build-static/../Include/internal/pycore_call.h:92:11
    #77 0x4c2f00 in object_vacall /usr/src/python3.12-3.12.3-1/build-static/../Objects/call.c:850:14
    #78 0x4c4ae4 in PyObject_CallMethodObjArgs /usr/src/python3.12-3.12.3-1/build-static/../Objects/call.c:911:24
    #79 0x58bee8 in import_find_and_load /usr/src/python3.12-3.12.3-1/build-static/../Python/import.c:2779:11
    #80 0x58bee8 in PyImport_ImportModuleLevelObject /usr/src/python3.12-3.12.3-1/build-static/../Python/import.c:2862:15
    #81 0x565f6c in import_name /usr/src/python3.12-3.12.3-1/build-static/../Python/ceval.c:2482:15
    #82 0x565f6c in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1/build-static/Python/bytecodes.c:2135:19
    #83 0x560070 in _PyEval_EvalFrame /usr/src/python3.12-3.12.3-1/build-static/../Include/internal/pycore_ceval.h:89:16
    #84 0x560070 in _PyEval_Vector /usr/src/python3.12-3.12.3-1/build-static/../Python/ceval.c:1683:12
    #85 0x560070 in PyEval_EvalCode /usr/src/python3.12-3.12.3-1/build-static/../Python/ceval.c:578:21
    #86 0x55d264 in builtin_exec_impl /usr/src/python3.12-3.12.3-1/build-static/../Python/bltinmodule.c:1096:17
    #87 0x55d264 in builtin_exec /usr/src/python3.12-3.12.3-1/build-static/../Python/clinic/bltinmodule.c.h:586:20
    #88 0x502a38 in cfunction_vectorcall_FASTCALL_KEYWORDS /usr/src/python3.12-3.12.3-1/build-static/../Objects/methodobject.c:438:24
    #89 0x5652ac in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1/build-static/Python/bytecodes.c:3254:26
    #90 0x4c2f00 in _PyObject_VectorcallTstate /usr/src/python3.12-3.12.3-1/build-static/../Include/internal/pycore_call.h:92:11
    #91 0x4c2f00 in object_vacall /usr/src/python3.12-3.12.3-1/build-static/../Objects/call.c:850:14
    #92 0x4c4ae4 in PyObject_CallMethodObjArgs /usr/src/python3.12-3.12.3-1/build-static/../Objects/call.c:911:24
    #93 0x58bee8 in import_find_and_load /usr/src/python3.12-3.12.3-1/build-static/../Python/import.c:2779:11
    #94 0x58bee8 in PyImport_ImportModuleLevelObject /usr/src/python3.12-3.12.3-1/build-static/../Python/import.c:2862:15
    #95 0x565f6c in import_name /usr/src/python3.12-3.12.3-1/build-static/../Python/ceval.c:2482:15
    #96 0x565f6c in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1/build-static/Python/bytecodes.c:2135:19
    #97 0x560070 in _PyEval_EvalFrame /usr/src/python3.12-3.12.3-1/build-static/../Include/internal/pycore_ceval.h:89:16
    #98 0x560070 in _PyEval_Vector /usr/src/python3.12-3.12.3-1/build-static/../Python/ceval.c:1683:12
    #99 0x560070 in PyEval_EvalCode /usr/src/python3.12-3.12.3-1/build-static/../Python/ceval.c:578:21
    #100 0x55d264 in builtin_exec_impl /usr/src/python3.12-3.12.3-1/build-static/../Python/bltinmodule.c:1096:17
    #101 0x55d264 in builtin_exec /usr/src/python3.12-3.12.3-1/build-static/../Python/clinic/bltinmodule.c.h:586:20
    #102 0x502a38 in cfunction_vectorcall_FASTCALL_KEYWORDS /usr/src/python3.12-3.12.3-1/build-static/../Objects/methodobject.c:438:24
    #103 0x5652ac in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1/build-static/Python/bytecodes.c:3254:26
    #104 0x4c2f00 in _PyObject_VectorcallTstate /usr/src/python3.12-3.12.3-1/build-static/../Include/internal/pycore_call.h:92:11
    #105 0x4c2f00 in object_vacall /usr/src/python3.12-3.12.3-1/build-static/../Objects/call.c:850:14
    #106 0x4c4ae4 in PyObject_CallMethodObjArgs /usr/src/python3.12-3.12.3-1/build-static/../Objects/call.c:911:24
    #107 0x58bee8 in import_find_and_load /usr/src/python3.12-3.12.3-1/build-static/../Python/import.c:2779:11
    #108 0x58bee8 in PyImport_ImportModuleLevelObject /usr/src/python3.12-3.12.3-1/build-static/../Python/import.c:2862:15
    #109 0x565f6c in import_name /usr/src/python3.12-3.12.3-1/build-static/../Python/ceval.c:2482:15
    #110 0x565f6c in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1/build-static/Python/bytecodes.c:2135:19
    #111 0x560070 in _PyEval_EvalFrame /usr/src/python3.12-3.12.3-1/build-static/../Include/internal/pycore_ceval.h:89:16
    #112 0x560070 in _PyEval_Vector /usr/src/python3.12-3.12.3-1/build-static/../Python/ceval.c:1683:12
    #113 0x560070 in PyEval_EvalCode /usr/src/python3.12-3.12.3-1/build-static/../Python/ceval.c:578:21
    #114 0x598ddc in run_eval_code_obj /usr/src/python3.12-3.12.3-1/build-static/../Python/pythonrun.c:1722:9
    #115 0x598ddc in run_mod /usr/src/python3.12-3.12.3-1/build-static/../Python/pythonrun.c:1743:19
    #116 0x598ddc in PyRun_StringFlags /usr/src/python3.12-3.12.3-1/build-static/../Python/pythonrun.c:1618:15
    #117 0x67c990 in PyRun_SimpleStringFlags /usr/src/python3.12-3.12.3-1/build-static/../Python/pythonrun.c:480:9
    #118 0x68919c in pymain_run_command /usr/src/python3.12-3.12.3-1/build-static/../Modules/main.c:255:11
    #119 0x68919c in pymain_run_python /usr/src/python3.12-3.12.3-1/build-static/../Modules/main.c:620:21
    #120 0x68919c in Py_RunMain /usr/src/python3.12-3.12.3-1/build-static/../Modules/main.c:709:5
    #121 0x688ca4 in Py_BytesMain /usr/src/python3.12-3.12.3-1/build-static/../Modules/main.c:763:12
    #122 0xffff941284c0 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #123 0xffff94128594 in __libc_start_main csu/../csu/libc-start.c:360:3
    #124 0x5f24ec in _start (/usr/bin/python3.12+0x5f24ec) (BuildId: 18160fe6beb052a7e6830ecc99e313a3498c377d)


Thread: T0 0xeffe00002000 stack: [0xfffffb0da000,0xfffffb8da000) sz: 8388608 tls: [0xffff94ed7460,0xffff94ed8320)
Thread: T1 0xeffe00012000 stack: [0xffff8eb00000,0xffff8f2ff140) sz: 8384832 tls: [0xffff8f2ff140,0xffff8f300000)
Thread: T2 0xeffe00022000 stack: [0xffff8e2f0000,0xffff8eaef140) sz: 8384832 tls: [0xffff8eaef140,0xffff8eaf0000)
Thread: T3 0xeffe00032000 stack: [0xffff8dae0000,0xffff8e2df140) sz: 8384832 tls: [0xffff8e2df140,0xffff8e2e0000)
Thread: T4 0xeffe00042000 stack: [0xffff8d2d0000,0xffff8dacf140) sz: 8384832 tls: [0xffff8dacf140,0xffff8dad0000)
Thread: T5 0xeffe00052000 stack: [0xffff8cac0000,0xffff8d2bf140) sz: 8384832 tls: [0xffff8d2bf140,0xffff8d2c0000)
Thread: T6 0xeffe00062000 stack: [0xffff8c2b0000,0xffff8caaf140) sz: 8384832 tls: [0xffff8caaf140,0xffff8cab0000)
Thread: T7 0xeffe00072000 stack: [0xffff8baa0000,0xffff8c29f140) sz: 8384832 tls: [0xffff8c29f140,0xffff8c2a0000)
Thread: T8 0xeffe00082000 stack: [0xffff8b290000,0xffff8ba8f140) sz: 8384832 tls: [0xffff8ba8f140,0xffff8ba90000)
Thread: T9 0xeffe00092000 stack: [0xffff8aa80000,0xffff8b27f140) sz: 8384832 tls: [0xffff8b27f140,0xffff8b280000)
Thread: T10 0xeffe000a2000 stack: [0xffff8a270000,0xffff8aa6f140) sz: 8384832 tls: [0xffff8aa6f140,0xffff8aa70000)
Thread: T11 0xeffe000b2000 stack: [0xffff89a60000,0xffff8a25f140) sz: 8384832 tls: [0xffff8a25f140,0xffff8a260000)
Thread: T12 0xeffe000c2000 stack: [0xffff89250000,0xffff89a4f140) sz: 8384832 tls: [0xffff89a4f140,0xffff89a50000)
Thread: T13 0xeffe000d2000 stack: [0xffff88a40000,0xffff8923f140) sz: 8384832 tls: [0xffff8923f140,0xffff89240000)

Memory tags around the buggy address (one tag corresponds to 16 bytes):
  0xffff92392f00: 00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
  0xffff92393000: 00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
  0xffff92393100: 00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
  0xffff92393200: 00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
  0xffff92393300: 00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
  0xffff92393400: 00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
  0xffff92393500: 00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
  0xffff92393600: 00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
=>0xffff92393700: 00  00  00  00  00  00  00  00  00  00 [00] 00  00  00  00  00
  0xffff92393800: 00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
  0xffff92393900: 00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
  0xffff92393a00: 00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
  0xffff92393b00: 00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
  0xffff92393c00: 00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
  0xffff92393d00: 00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
  0xffff92393e00: 00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
  0xffff92393f00: 00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
Tags for short granules around the buggy address (one tag corresponds to 16 bytes):
  0xffff92393600: ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
=>0xffff92393700: ..  ..  ..  ..  ..  ..  ..  ..  ..  .. [..] ..  ..  ..  ..  ..
  0xffff92393800: ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
See https://clang.llvm.org/docs/HardwareAssistedAddressSanitizerDesign.html#short-granules for a description of short granule tags
SUMMARY: HWAddressSanitizer: tag-mismatch /src/build/../numpy/_core/src/common/npy_cpu_features.c:780:5 in npy__cpu_init_features
As a sanity check, we tried to import numpy.
Stopping. Please investigate the build error.
```

### Notes
Compiler warnings:
```
[142/323] Compiling C object numpy/_core/_multiarray_umath.cpython-312-aarch64-linux-gnu.so.p/src_multiarray_alloc.c.o
../numpy/_core/src/multiarray/alloc.c: In function ‘PyDataMem_RENEW’:
../numpy/_core/src/multiarray/alloc.c:274:9: warning: pointer ‘ptr’ may be used after ‘realloc’ [-Wuse-after-free]
  274 |         PyTraceMalloc_Untrack(NPY_TRACE_DOMAIN, (npy_uintp)ptr);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../numpy/_core/src/multiarray/alloc.c:272:14: note: call to ‘realloc’ here
  272 |     result = realloc(ptr, size);
      |              ^~~~~~~~~~~~~~~~~~
```
```
[8/323] Generating numpy/generate-version with a custom command
Saving version to numpy/version.py
[141/323] Compiling C object numpy/_core/_multiarray_umath.cpython-312-aarch64-linux-gnu.so.p/src_multiarray_alloc.c.o
../numpy/_core/src/multiarray/alloc.c: In function ‘PyDataMem_RENEW’:
../numpy/_core/src/multiarray/alloc.c:274:9: warning: pointer ‘ptr’ may be used after ‘realloc’ [-Wuse-after-free]
  274 |         PyTraceMalloc_Untrack(NPY_TRACE_DOMAIN, (npy_uintp)ptr);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../numpy/_core/src/multiarray/alloc.c:272:14: note: call to ‘realloc’ here
  272 |     result = realloc(ptr, size);
      |              ^~~~~~~~~~~~~~~~~~
[267/323] Compiling C++ object numpy/_core/_multiarray_umath.cpython-312-aarch64-linux-gnu.so.p/src_umath_stringdtype_ufuncs.cpp.o
In file included from ../numpy/_core/src/umath/stringdtype_ufuncs.cpp:21:
../numpy/_core/src/umath/string_buffer.h:265:23: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  265 |     inline Buffer<enc>()
      |                       ^
../numpy/_core/src/umath/string_buffer.h:265:23: note: remove the ‘< >’
../numpy/_core/src/umath/string_buffer.h:270:23: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  270 |     inline Buffer<enc>(char *buf_, npy_int64 elsize_)
      |                       ^
../numpy/_core/src/umath/string_buffer.h:270:23: note: remove the ‘< >’
[284/323] Compiling C++ object numpy/_core/_multiarray_umath.cpython-312-aarch64-linux-gnu.so.p/src_umath_string_ufuncs.cpp.o
In file included from ../numpy/_core/src/umath/string_ufuncs.cpp:21:
../numpy/_core/src/umath/string_buffer.h:265:23: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  265 |     inline Buffer<enc>()
      |                       ^
../numpy/_core/src/umath/string_buffer.h:265:23: note: remove the ‘< >’
../numpy/_core/src/umath/string_buffer.h:270:23: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  270 |     inline Buffer<enc>(char *buf_, npy_int64 elsize_)
      |                       ^
../numpy/_core/src/umath/string_buffer.h:270:23: note: remove the ‘< >’ 
```

### PR DESCRIPTION
**Pull request by abhishek-iitmadras**
Fixes: #26910 

Reference issue on LLVM related to this : https://github.com/llvm/llvm-project/issues/59924 

**Issue:** When build numpy from source with clang compiler on aarch64 machines, i got the following failure of `test_umath.py` :
```
==================================================================================== FAILURES ====================================================================================
___________________________________________________________________ TestDivision.test_floor_division_errors[g] ___________________________________________________________________

self = <test_umath.TestDivision object at 0xe4d31f7becd0>, dtype = 'g'

    @pytest.mark.skipif(hasattr(np.__config__, "blas_ssl2_info"),
            reason="gh-22982")
    @pytest.mark.skipif(IS_WASM, reason="fp errors don't work in wasm")
    @pytest.mark.parametrize('dtype', np.typecodes['Float'])
    def test_floor_division_errors(self, dtype):
        fnan = np.array(np.nan, dtype=dtype)
        fone = np.array(1.0, dtype=dtype)
        fzer = np.array(0.0, dtype=dtype)
        finf = np.array(np.inf, dtype=dtype)
        # divide by zero error check
        with np.errstate(divide='raise', invalid='ignore'):
            assert_raises(FloatingPointError, np.floor_divide, fone, fzer)
        with np.errstate(divide='ignore', invalid='raise'):
            np.floor_divide(fone, fzer)
    
        # The following already contain a NaN and should not warn
        with np.errstate(all='raise'):
>           np.floor_divide(fnan, fone)
E           FloatingPointError: invalid value encountered in floor_divide

dtype      = 'g'
finf       = array(inf, dtype=float128)
fnan       = array(nan, dtype=float128)
fone       = array(1., dtype=float128)
fzer       = array(0., dtype=float128)
self       = <test_umath.TestDivision object at 0xe4d31f7becd0>

numpy/_core/tests/test_umath.py:679: FloatingPointError
_____________________________________________________________ TestRemainder.test_float_remainder_errors[remainder-g] _____________________________________________________________

self = <test_umath.TestRemainder object at 0xe4d3053aa210>, dtype = 'g', fn = <ufunc 'remainder'>

    @pytest.mark.skipif(hasattr(np.__config__, "blas_ssl2_info"),
            reason="gh-22982")
    @pytest.mark.skipif(IS_WASM, reason="fp errors don't work in wasm")
    @pytest.mark.xfail(sys.platform.startswith("darwin"),
           reason="MacOS seems to not give the correct 'invalid' warning for "
                  "`fmod`.  Hopefully, others always do.")
    @pytest.mark.parametrize('dtype', np.typecodes['Float'])
    @pytest.mark.parametrize('fn', [np.fmod, np.remainder])
    def test_float_remainder_errors(self, dtype, fn):
        fzero = np.array(0.0, dtype=dtype)
        fone = np.array(1.0, dtype=dtype)
        finf = np.array(np.inf, dtype=dtype)
        fnan = np.array(np.nan, dtype=dtype)
    
        # The following already contain a NaN and should not warn.
        with np.errstate(all='raise'):
            with pytest.raises(FloatingPointError,
                    match="invalid value"):
                fn(fone, fzero)
            fn(fnan, fzero)
>           fn(fzero, fnan)
E           FloatingPointError: invalid value encountered in remainder

dtype      = 'g'
finf       = array(inf, dtype=float128)
fn         = <ufunc 'remainder'>
fnan       = array(nan, dtype=float128)
fone       = array(1., dtype=float128)
fzero      = array(0., dtype=float128)
self       = <test_umath.TestRemainder object at 0xe4d3053aa210>

numpy/_core/tests/test_umath.py:826: FloatingPointError
============================================================================ short test summary info =============================================================================
FAILED numpy/_core/tests/test_umath.py::TestDivision::test_floor_division_errors[g] - FloatingPointError: invalid value encountered in floor_divide
FAILED numpy/_core/tests/test_umath.py::TestRemainder::test_float_remainder_errors[remainder-g] - FloatingPointError: invalid value encountered in remainder
=================================================================== 2 failed, 4694 passed, 61 skipped in 8.68s ===================================================================
```

**Change Made:**

Fix floating-point exception (FPE) handling for float128 operations on ARM64 with Clang compiler. Previously, floor division and remainder operations with NaN values would incorrectly trigger floating-point exceptions on this platform.

The fix adds special handling in npy_math_internal.h.src for float128 NaN operations on ARM64 with Clang:
- Bypass additional FPE checks for NaN values
- Let hardware handle NaN division and modulo operations directly
- Only affects ARM64 + Clang + float128 combination

This resolves test failures in TestDivision.test_floor_division_errors and TestRemainder.test_float_remainder_errors when running with float128 on ARM64 platforms using the Clang compiler.

### CODE REVIEW

**Comment by charris** [comment]
I assume this is linux on ARM?

**Comment by abhishek-iitmadras** [comment]
> I assume this is linux on ARM?

Yes


`> uname -a`
Linux ip-xxx.xx.xx.x-aws ~22.04.1-Ubuntu SMP Tue Dec 10 16:31:58 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

**Comment by abhishek-iitmadras** [comment]
@charris @ngoldbaum 

Please help with review this patch

**Comment by ngoldbaum** [comment]
I don’t see an open issue about this. Rather than skipping the test as the first thing, I think it would be better to try to understand why this is happening and fix the bug rather than just xfailing the test. Marking a test as xfail is papering over a bug. That should be a last resort “fix”.

**Comment by abhishek-iitmadras** [comment]
> I don’t see an open issue about this. Rather than skipping the test as the first thing, I think it would be better to try to understand why this is happening and fix the bug rather than just xfailing the test. Marking a test as xfail is papering over a bug. That should be a last resort “fix”.

Issue related to this : https://github.com/numpy/numpy/issues/26910

**Comment by ngoldbaum** [comment]
Why is it important for the tests to pass on aarch64 machines? Are you planning to add aarch64 CI? IMO we should fix these bugs rather than papering over them before adding "official" linux aarch64 support.

**Comment by abhishek-iitmadras** [comment]
> Are you planning to add aarch64 CI? 

Yes

**Comment by ngoldbaum** [comment]
> Issue related to this : #26910

I don't see any analysis about why these errors are happening. I'd like someone to do that before we decide the bug truly can be ignored.

**Comment by abhishek-iitmadras** [comment]
Now instead of marking tests as xfail, I have implemented a more robust approach by addressing FPE handling for float128 dtype on ARM64 with Clang as described in updated commit message.
Please have a look and review this patch.

cc: @charris @ngoldbaum

File: numpy/_core/src/npymath/npy_math_internal.h.src [hunk 1]
```diff
@@ -58,6 +58,10 @@
 #  include <intrin.h>   // for __popcnt
 #endif
 
+#if defined(__aarch64__) && defined(__clang__)
+#define NPY_HANDLE_FPE_ARM64_CLANG 1
+#endif
```
Comment (ngoldbaum) [inline numpy/_core/src/npymath/npy_math_internal.h.src:63]: I think I'd just use the intrinsics directly below rather than defining a macro you only use twice.

Total nitpick, feel free to ignore.

File: numpy/_core/src/npymath/npy_math_internal.h.src [hunk 2]
```diff
@@ -514,6 +518,12 @@ NPY_INPLACE @type@
 npy_remainder@c@(@type@ a, @type@ b)
 {
     @type@ mod;
+#if NPY_HANDLE_FPE_ARM64_CLANG
+    /* Special handling for ARM64 with Clang to avoid FPE with float128 */
```
Comment (ngoldbaum) [inline numpy/_core/src/npymath/npy_math_internal.h.src:522]: Do you happen to have a reference documenting this difference? Is this a clang bug or something?

Also I think this will play more nicely with the branch predictor if you use the UNLIKELY macro here and below, since arguments being NaN is not the common case to optimize for.

File: numpy/_core/src/npymath/npy_math_internal.h.src (hunk 1 above)
Comment (abhishek-iitmadras) [reply numpy/_core/src/npymath/npy_math_internal.h.src]: SGTM, Done as suggested

File: numpy/_core/src/npymath/npy_math_internal.h.src (hunk 2 above)
Comment (abhishek-iitmadras) [reply numpy/_core/src/npymath/npy_math_internal.h.src:518]: > Do you happen to have a reference documenting this difference? Is this a clang bug or something?
> 

Motivated by https://github.com/llvm/llvm-project/issues/59924

> Also I think this will play more nicely with the branch predictor if you use the UNLIKELY macro here and below, since arguments being NaN is not the common case to optimize for.

Done

Comment (ngoldbaum) [reply numpy/_core/src/npymath/npy_math_internal.h.src:518]: Thanks for finding that!

Can you add a link to the LLVM issue in the comment here and below? That way someone in the future when the bug is fixed might look at the LLVM issue, see it's fixed, and remove the special case.

Comment (abhishek-iitmadras) [reply numpy/_core/src/npymath/npy_math_internal.h.src:518]: @ngoldbaum 
SGTM, Added comment with TODO mark and issue link for future reference.
Now we are good to go with this patch. Please approve and merge

**Review by ngoldbaum — APPROVED** [review]
This looks good to me but I'd like @charris or @seberg to double-check this is how we should handle this.

**Review by r-devulap — APPROVED** [review]
LGTM. Just a suggestion: It might be easier to read if we could combine these two conditions into one so that we avoid an extra return statement. 
```
if (NPY_UNLIKELY(sizeof(@type@) == sizeof(long double) && (npy_isnan(a) || npy_isnan(b)))) 

if (NPY_UNLIKELY(!b)) 
```

**Comment by abhishek-iitmadras** [comment]
> LGTM. Just a suggestion: It might be easier to read if we could combine these two conditions into one so that we avoid an extra return statement.
> 
> ```
> if (NPY_UNLIKELY(sizeof(@type@) == sizeof(long double) && (npy_isnan(a) || npy_isnan(b)))) 
> 
> if (NPY_UNLIKELY(!b)) 
> ```

Done as per suggestion

**Comment by r-devulap** [comment]
LGTM. Thanks @abhishek-iitmadras!

**Comment by charris** [comment]
Note that `divmod` was used so that remainder and result would add up correctly, that wasn't always the case when they were computed separately. Unfortunate, as `divmod` is quite slow. We should undo this when the clang error is fixed.
