### PR TITLE
BUG: Fix SystemError when pickling datetime64 array with pickle5

### LINKED ISSUE #12745: ndarray.__reduce_ex__ doesn't check return value of PickleBuffer.__new__
When taking a buffer out of an array fails, `__reduce_ex__` raises SystemError instead of propagating the error:
```python
>>> import numpy as np                                                                                                                                    
>>> d = np.datetime64('2015-07-04 12:59:59.50', 'ns')                                                                                                     
>>> a = np.array([d])                                                                                                                                     
>>> memoryview(a)                                                                                                                                         
Traceback (most recent call last):
  File "<ipython-input-4-dd900d27ccee>", line 1, in <module>
    memoryview(a)
ValueError: cannot include dtype 'M' in a buffer

>>> a.__reduce_ex__(5)                                                                                                                                    
Traceback (most recent call last):
  File "<ipython-input-5-b4bdda9e83c1>", line 1, in <module>
    a.__reduce_ex__(5)
SystemError: <built-in function __import__> returned a result with an error set
```

This is because in the C function `array_reduce_ex`, the result of calling the `PickleBuffer` constructor is not checked for NULL, so the original error is ignored and the interpreter ultimately complains.

(this is related to but distinct from https://github.com/numpy/numpy/issues/4983#issuecomment-441332940)

Note: you need `pickle5` installed to reproduce.

### PR DESCRIPTION
**Pull request by pitrou**
Check for error when calling the `PickleBuffer` constructor in `ndarray.__reduce_ex__`,
and fall back on the regular `__reduce__` implementation for arrays which don't
support taking a buffer.

Also fix some reference leaks.

Fixes gh-12745, gh-12793

### CODE REVIEW

**Comment by pitrou** [comment]
@pierreglaser What are you doing on `_pickle.c`?

**Comment by pierreglaser** [comment]
Dynamic/nested scope objects pickling (See this [python-dev thread](https://mail.python.org/pipermail/python-dev/2018-November/155687.html), been working on this for a little while already), feel free to reach out if you are interested!

**Comment by pitrou** [comment]
I'll note that I get this error after running `numpy/core/tests/test_multiarray.py`:
```
*** Reference count error detected: 
an attempt was made to deallocate 12 (d) ***
```

The error is still there is I disable all pickling tests, though, so it's probably not pickling-related.

File: numpy/core/src/multiarray/methods.c [hunk 1]
```diff
@@ -1723,129 +1723,150 @@ array_reduce(PyArrayObject *self, PyObject *NPY_UNUSED(args))
...
-            /* if the python version is below 3.8, the pickle module does not provide
-             * built-in support for protocol 5. We try importing the pickle5
-             * backport instead */
+    /* if the python version is below 3.8, the pickle module does not provide
+     * built-in support for protocol 5. We try importing the pickle5
+     * backport instead */
 #if PY_VERSION_HEX >= 0x03080000
-            pickle_module = PyImport_ImportModule("pickle");
+    pickle_module = PyImport_ImportModule("pickle");
 #elif PY_VERSION_HEX < 0x03080000 && PY_VERSION_HEX >= 0x03060000
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/methods.c]: A nit: you could drop the `PY_VERSION_HEX < 0x03080000` here, it's implied by the condition above.

Comment (pitrou) [reply numpy/core/src/multiarray/methods.c]: You're right.

File: numpy/core/src/multiarray/methods.c [hunk 2]
```diff
@@ -1723,129 +1723,150 @@ array_reduce(PyArrayObject *self, PyObject *NPY_UNUSED(args))
...
+    descr = PyArray_DESCR(self);
+    if ((protocol < 5) ||
+        (!PyArray_IS_C_CONTIGUOUS((PyArrayObject*)self) &&
+         !PyArray_IS_F_CONTIGUOUS((PyArrayObject*)self)) ||
+        PyDataType_FLAGCHK(descr, NPY_ITEM_HASOBJECT) ||
+        (PyType_IsSubtype(((PyObject*)self)->ob_type, &PyArray_Type) &&
+         ((PyObject*)self)->ob_type != &PyArray_Type) ||
+        PyDataType_ISUNSIZED(descr)) {
+        /* The PickleBuffer class from version 5 of the pickle protocol
+         * can only be used for arrays backed by a contiguous data buffer.
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/methods.c]: The PEP says _"PickleBuffer can wrap any kind of buffer, including non-contiguous buffers."_. Am I missing something?

Comment (pitrou) [reply numpy/core/src/multiarray/methods.c]: Only contiguous buffers are correctly handled by the `pickle` module, though.
(this is something that should probably be improved in the future, but is non-trivial)

Comment (eric-wieser) [reply numpy/core/src/multiarray/methods.c]: Is that mentioned in the PEP, pickle docs, or cpython bug tracker?

File: numpy/core/tests/test_multiarray.py [hunk 3]
```diff
@@ -3769,10 +3769,15 @@ def test_roundtrip(self):
...
 
+            refs = [weakref.ref(a) for a in DATA]
             for a in DATA:
                 assert_equal(
                         a, pickle.loads(pickle.dumps(a, protocol=proto)),
                         err_msg="%r" % a)
+            del a, DATA, carray
+            # check for reference leaks (gh-12793)
+            for ref in refs:
+                assert ref() is None
```
Comment (eric-wieser) [inline numpy/core/tests/test_multiarray.py]: @mattip, this type of test will fail on pypy, right?

File: numpy/core/src/multiarray/methods.c (hunk 2 above)
Comment (pitrou) [reply numpy/core/src/multiarray/methods.c]: No, I have to update the PEP.

File: numpy/core/tests/test_multiarray.py (hunk 3 above)
Comment (pitrou) [reply numpy/core/tests/test_multiarray.py]: Hmm, yes, I should call `gc.collect`.

**Comment by seberg** [comment]
Am on arch linux right now, but not quite sure why it should make a difference... I guess that error message does mean the actual integer `12`. Maybe there are just too many things potentially touching it to make it easy to reproduce :/.

**Comment by pitrou** [comment]
Ok, I bisected the tests manually. The following test is sufficient to reproduce here:
```python
def test_array_interface():
    # Test scalar coercion within the array interface
    class Foo(object):
        def __init__(self, value):
            self.value = value
            self.iface = {'typestr': '=f8'}

        def __float__(self):
            return float(self.value)

        @property
        def __array_interface__(self):
            return self.iface

    f = Foo(0.5)
    f.iface['shape'] = (2,)
    assert_raises(ValueError, np.array, f)
```

**Comment by seberg** [comment]
@pitrou thanks a lot! I can see the refcount decrase, I guess I just don't reach 0 on my system.

**Comment by pitrou** [comment]
The following change seems to solve the issue:
```diff
diff --git a/numpy/core/src/multiarray/ctors.c b/numpy/core/src/multiarray/ctors.c
index 63bf5377a..4724b8472 100644
--- a/numpy/core/src/multiarray/ctors.c
+++ b/numpy/core/src/multiarray/ctors.c
@@ -2503,6 +2503,7 @@ PyArray_FromInterface(PyObject *origin)
     if (ret == NULL) {
         goto fail;
     }
+    dtype = NULL;  /* ref was stolen by PyArray_NewFromDescrAndBase */
     if (data == NULL) {
         if (PyArray_SIZE(ret) > 1) {
             PyErr_SetString(PyExc_ValueError,
```

I'll let someone else handle it, as I don't really know what the surrounding code is doing.

**Comment by seberg** [comment]
Dang, should have checked here earlier, just found that as well :).

**Comment by seberg** [comment]
Thanks @pitrou. I doubt many know that code well, but I figured the same fix, so that seems like a good sign.

File: numpy/core/tests/test_multiarray.py (hunk 3 above)
Comment (charris) [reply numpy/core/tests/test_multiarray.py]: Could skip for pypy. These sorts of tests do tend to be fragile.

**Comment by pitrou** [comment]
No, it should be ready.

File: numpy/core/src/multiarray/methods.c [hunk 4]
```diff
@@ -1723,129 +1723,150 @@ array_reduce(PyArrayObject *self, PyObject *NPY_UNUSED(args))
...
 {
-    int protocol;
-    PyObject *ret = NULL, *numeric_mod = NULL, *from_buffer_func = NULL;
-    PyObject *buffer_tuple = NULL, *pickle_module = NULL, *pickle_class = NULL;
-    PyObject *class_args = NULL, *class_args_tuple = NULL, *unused = NULL;
     PyObject *subclass_array_reduce = NULL;
+    PyObject *ret;
+
+    /* We do not call array_reduce directly but instead lookup and call
+     * the __reduce__ method to make sure that it's possible customize
```
Comment (mattip) [inline numpy/core/src/multiarray/methods.c]: nit "possible **to** customize"

**Comment by mattip** [comment]
one very minor nit. We can check after merge if the new test is flaky on PyPy and skip it in a new PR. LGTM.

**Comment by pierreglaser** [comment]
thanks for working on that @pitrou!

File: numpy/core/src/multiarray/methods.c [hunk 5]
```diff
@@ -1723,129 +1723,150 @@ array_reduce(PyArrayObject *self, PyObject *NPY_UNUSED(args))
...
+         * For all other cases we fallback to the generic array_reduce
+         * method that involves using a temporary bytes allocation. */
+        return array_reduce_ex_regular(self, protocol);
+    }
+    else if (protocol == 5) {
+        return array_reduce_ex_picklebuffer(self, protocol);
     }
     else {
+        PyErr_Format(PyExc_ValueError,
+                     "__reduce_ex__ called with protocol > 5");
```
Comment (jakirkham) [inline numpy/core/src/multiarray/methods.c:1867]: Is there a reason we expect this not to work with a later Python pickle protocol?
