### PR TITLE
BUG: Do not crash on recursive `.dtype` attribute lookup.

### LINKED ISSUE #12982: Passing MagicMock to np.dtype causes a segmentation fault
Passing MagicMock to np.dtype causes a segmentation fault. Original issue raised in [Pandas](https://github.com/pandas-dev/pandas/issues/25332)

### Reproducing code example:

```python
from unittest.mock import MagicMock
import numpy as np

np.dtype(MagicMock())
```

### Error message:

```
$ gdb --args python runtests.py -g --python mytest.py
Starting program: /home/vagrant/numpy/venv3/bin/python runtests.py -g --python mytest.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Building, see build.log...
Build OK
Enabling display of all warnings

Program received signal SIGSEGV, Segmentation fault.
0x000000000059f332 in ?? ()
```

### Numpy/Python version information:
```
1.16.1 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]
```

### PR DESCRIPTION
**Pull request by seberg**
The code path in scalarapi.c which checks dtype on one inheriting
from np.void is especially awkward and was completely untested
previously. So I am not sure we should even support it at all.

Closes gh-12982, gh-3614, and gh-12751

----

Frankly, I am not sure it is actually worth the trouble, but had started on it. The actual error message does not always include the custom message, this seems because the recursion error can also be triggered by the `GetAttr` call (at least when dtype is made a property).

If we attack dtypes in any case, I am afraid adding more band-aids will just make things harder in the long run anyway.

### CODE REVIEW

File: numpy/core/src/multiarray/descriptor.c [hunk 1]
```diff
@@ -90,31 +90,51 @@ _arraydescr_from_ctypes_type(PyTypeObject *type)
...
+        goto fail;
+    }
+
+    if (Py_EnterRecursiveCall(
+            " while trying to convert the given data type from its "
+            "`.dtype` attribute.") != 0) {
+        return 1;
     }
 
-    ret = PyArray_DescrConverter(dtypedescr, &newdescr);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c]: Can we maybe deprecate `.dtype` attributes which are not themselves dtypes?

Honestly, overloading `dtype` to mean "get the dtype of this thing" already seems like a risky thing to do.
The best argument I can see for allowing it is it matches the semantics of `type`, which can be used to both inspect and construct dtypes.

However, I can't see a use case for allowing it to inspect and construct at the same time - that seems like a disaster, which results in this recursion.

File: numpy/core/tests/test_dtype.py [hunk 2]
```diff
@@ -935,6 +935,50 @@ def test_invalid_dtype_string():
...
+        with pytest.raises(RecursionError):
+            np.dtype(dt_instance)
+
+    def test_void_subtype(self):
+        class dt(np.void):
+            # This code path is fully untested before, so it is unclear
+            # what this should be useful for. Note that if np.void is used
+            # numpy will think we are deallocating a base type [1.17, 2019-02].
+            dtype = np.dtype("f,f")
+            pass
```
Comment (eric-wieser) [inline numpy/core/tests/test_dtype.py]: nit: drop this

File: numpy/core/src/multiarray/descriptor.c [hunk 3]
```diff
@@ -90,31 +90,51 @@ _arraydescr_from_ctypes_type(PyTypeObject *type)
...
-        PyErr_Clear();
-        return NULL;
+        goto fail;
     }
 
-    return newdescr;
+    return 1;
+
+  fail:
+    /* Ignore all but recursion errors, to give ctypes a full try. */
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c]: I think it would make sense to let the caller do this, since there's it's more obvious that ctypes is trying next.

File: numpy/core/src/multiarray/descriptor.c [hunk 4]
```diff
@@ -1400,11 +1420,13 @@ PyArray_DescrConverter(PyObject *obj, PyArray_Descr **at)
             check_num = NPY_VOID;
         }
         else {
-            *at = _arraydescr_from_dtype_attr(obj);
-            if (*at) {
-                return NPY_SUCCEED;
+            if (_arraydescr_from_dtype_attr(obj, at)) {
+                /* Fetched dtype attribute, error recursion error possible */
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c]: "error recursion error"?

File: numpy/core/src/multiarray/descriptor.c (hunk 3 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/descriptor.c]: Looking again - it's already a mess, not sure this helps much. Fine to leave as is.

File: numpy/core/src/multiarray/descriptor.c [hunk 5]
```diff
@@ -90,31 +90,51 @@ _arraydescr_from_ctypes_type(PyTypeObject *type)
  * and it can be converted to a dtype object.
  *
  * Returns a new reference to a dtype object, or NULL
- * if this is not possible. When it returns NULL, it does
- * not set a Python exception.
+ * if this is not possible.
+ * When the return value is true, the dtype attribute should have been used
+ * and parsed. Currently the only failure mode for a 1 return is a
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c]: Returning `1` for an error is unusual. Can you return `-1` instead, and use the standard `< 0` check at the call site?

Comment (seberg) [reply numpy/core/src/multiarray/descriptor.c]: Yeah, did that because it actually meant "using the dtype attribute" and not necessarily error, but maybe nicer in any case.

File: numpy/core/src/multiarray/descriptor.c (hunk 1 above)
Comment (seberg) [reply numpy/core/src/multiarray/descriptor.c]: Deprecation sounds like a good idea. I am not actually sure what the real use case here is, so I am wondering if we might be able to go the extra mile and just deprecate the whole logic. Will have a look at it.

Comment (seberg) [reply numpy/core/src/multiarray/descriptor.c]: So `np.format_parser` and record arrays require the dtype lookup. But I guess it actually makes sense to support in any case (in a way it is similar to supporting `np.float64`). f2py has some issues with the deprecation, but I am sure I can patch that.

File: numpy/core/src/multiarray/descriptor.c (hunk 5 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/descriptor.c]: Ah, I get it now. Perhaps just a better docstring - in particular, line 92 is now wrong.  Something like:
```
Returns 1 if getting a dtype was attempted, otherwise 0.
If an attempt was made, `newdescr` will contain the result, or NULL if an error occured and should be propagated.
```
You could also consider returning `PyNone`, but then you have to remember to reference count it which is a bit of a waste of time.

File: numpy/core/src/multiarray/descriptor.c (hunk 1 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/descriptor.c]: > and record arrays require the dtype lookup.

Mind linking to where this happens?

File: numpy/core/src/multiarray/descriptor.c [hunk 6]
```diff
@@ -90,31 +90,67 @@ _arraydescr_from_ctypes_type(PyTypeObject *type)
...
-        PyErr_Clear();
-        return NULL;
+        goto fail;
     }
 
-    return newdescr;
+    if (DEPRECATE("in the future the `.dtype` attribute of a given data"
+                  "type object must be a valid dtype instance. "
+                  "`data_type.dtype` may need to be coerced using "
+                  "`np.dtype(data_type.dtype)`. This will return an error "
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c]: nit: raise an error, not return one

File: numpy/core/src/multiarray/scalarapi.c [hunk 7]
```diff
@@ -471,12 +471,15 @@ PyArray_DescrFromTypeObject(PyObject *type)
...
+            if (conv == NULL) {
+                Py_DECREF(new);
+                return NULL;
+            }
             new->fields = conv->fields;
-            Py_INCREF(new->fields);
+            Py_XINCREF(new->fields);
             new->names = conv->names;
-            Py_INCREF(new->names);
+            Py_XINCREF(new->names);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalarapi.c]: Is this a bug fix?

**Comment by eric-wieser** [comment]
Generally looks good. Perhaps you should split the deprecation into a separate PR - I think this is close to being ready, but with the deprecation in place it would maybe need to hit the mailing list. Would be a shame to block the bug fix on that.

File: numpy/core/src/multiarray/descriptor.c (hunk 5 above)
Comment (seberg) [reply numpy/core/src/multiarray/descriptor.c]: Yeah, PyNone may be a neat idea, it is just one "DECREF on error" in a sense, so maybe nicer than this dance.

About splitting off: Yeah, thought it would be better as well probably, so planning to do that, if I don't get to it today, might be a few days.

File: numpy/core/src/multiarray/scalarapi.c (hunk 7 above)
Comment (seberg) [reply numpy/core/src/multiarray/scalarapi.c]: Yes, although it might be that the bug it fixes is in paths that normal code should not reach.

File: numpy/core/src/multiarray/descriptor.c (hunk 1 above)
Comment (seberg) [reply numpy/core/src/multiarray/descriptor.c]: Format parser is documented to work in the form of: ``dtype = format_parser(formats, names, titles).dtype``, which means passing it directly as a dtype works through attribute lookup and is inviting.

Hmmpf, will hunt down the other thing later.

**Comment by seberg** [comment]
Split off the deprecation (and that funny maintanence of the tests) into gh-13578.

File: numpy/core/src/multiarray/descriptor.c [hunk 8]
```diff
@@ -1595,14 +1620,16 @@ PyArray_DescrConverter(PyObject *obj, PyArray_Descr **at)
...
-            return NPY_FAIL;
+        if (_arraydescr_from_dtype_attr(obj, at)) {
+            /*
+             * Using dtype attribute, *at may be NULL if a
+             * RecursionError occurred.
+             */
+            if (*at == NULL) {
+                goto error;
+            }
+            return success;
```
Comment (mattip) [inline numpy/core/src/multiarray/descriptor.c]: Did you mean `NPY_SUCCEED`?

Comment (seberg) [reply numpy/core/src/multiarray/descriptor.c]: har, yes, fixed...

**Comment by mattip** [comment]
@eric-wieser any more review comments?

**Comment by mattip** [comment]
As an error is better than a segfault, thanks @seberg
