### PR TITLE
BUG: pickle the content of a scalar containing objects, not the address

### LINKED ISSUE #13593: Segfault after loading pickled void objects
The title is self sufficient. I'm getting segmentation faults after unpickling void numpy objects. That's quite easy to reproduce.

### Reproducing code example:

To reproduce the bug two steps a needed. At first dump the void object:
```python
import pickle
import numpy as np

dt = np.dtype([('name', 'O')])
a = np.empty(1, dtype=dt)
a['name'] = 'eman'

with open('b.pickle', 'wb') as file:
    pickle.dump(a[0], file)
```

Then try to load and print the pickled object from *another* interpreter:
```python
import pickle
print(pickle.load(open('b.pickle', 'rb')))
# Segmentation fault here
```

### Error message:
I'm typing the GDB traceback here.

```
Starting program: /home/balodja/tmp/tmpenv/bin/python a.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4df8700 (LWP 19796)]
[New Thread 0x7ffff45f7700 (LWP 19797)]
[New Thread 0x7ffff1df6700 (LWP 19798)]

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007ffff6fdfd78 in PyArray_Item_INCREF (data=0xc57570 "\340\065\a\034S\177", descr=0x7fffec232150) at numpy/core/src/multiarray/refcount.c:39
39      numpy/core/src/multiarray/refcount.c: No such file or directory.
```

### Numpy/Python version information:

```
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.16.3 3.7.3rc1 (default, Mar 13 2019, 11:01:15) 
[GCC 8.3.0]
```

### PR DESCRIPTION
**Pull request by mattip**
Fixes gh-13593

Scalars with a void dtype that contains objects were not pickled properly. Add a test and fix by checking the `NPY_LIST_PICKLE` flag of the dtype.

### CODE REVIEW

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 1]
```diff
@@ -1887,6 +1887,22 @@ gentype_reduce(PyObject *self, PyObject *NPY_UNUSED(args))
...
+        PyArrayIterObject *it = (PyArrayIterObject *)PyArray_IterNew(arr);
+        if (it == NULL) {
+            return NULL;
+        }
+        mod = ((PyArray_Descr *)obj)->f->getitem(it->dataptr, arr);
+        Py_DECREF(it);
+        Py_DECREF(arr);
+        /* XXX N does not incref, O does. What do we want? */
+        PyTuple_SET_ITEM(ret, 1, Py_BuildValue("NO", obj, mod));
+    }
```
Comment (mattip) [inline numpy/core/src/multiarray/scalartypes.c.src]: Does this work properly or did I miss a refcount in the call to `Py_BuildValue` by using `N` ? I copied what is done below.

File: numpy/core/tests/test_records.py [hunk 2]
```diff
@@ -416,6 +416,21 @@ def test_pickle_3(self):
...
+        a['obj'] = data
+        state = a[0].__reduce__()
+        # If the data is bytes, it will pickle the address of the content
+        # which cannot be saved/restored
+        assert not isinstance(state[1][1], bytes)
+        b = state[0](*state[1])
+        assert b[0] == (bytearray(b'eman'),)
+        # got a fresh version, not the original pointers rebuilt
+        assert b[0] is not data
+
```
Comment (mattip) [inline numpy/core/tests/test_records.py]: A round-trip pickling check would require careful deletion of `data` to make sure it was pickling properly

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 3]
```diff
@@ -1887,6 +1887,22 @@ gentype_reduce(PyObject *self, PyObject *NPY_UNUSED(args))
...
+        /* a structured dtype with an object in a field */
+        PyObject *arr = PyArray_FromScalar(self, NULL);
+        if (arr == NULL) {
+            return NULL;
+        }
+        PyArrayIterObject *it = (PyArrayIterObject *)PyArray_IterNew(arr);
+        if (it == NULL) {
+            return NULL;
+        }
+        mod = ((PyArray_Descr *)obj)->f->getitem(it->dataptr, arr);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]: Rather than reusing the unrelated `mod` (module, line 1875), can we rename this to something else? `scalar`? `val`?

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 1 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/scalartypes.c.src]: N is correct, `obj` is a new reference that you want to destroy.

Having said that, you ought to check the return value of `Py_BuildValue` in case it runs out of memory, and propagate the error.

File: numpy/core/tests/test_records.py [hunk 4]
```diff
@@ -416,6 +416,21 @@ def test_pickle_3(self):
...
+    def test_pickle_void(self):
+        # issue gh-13593
+        dt = np.dtype([('obj', 'O')])
+        a = np.empty(1, dtype=dt)
+        data = (bytearray(b'eman'),)
+        a['obj'] = data
+        state = a[0].__reduce__()
+        # If the data is bytes, it will pickle the address of the content
+        # which cannot be saved/restored
+        assert not isinstance(state[1][1], bytes)
```
Comment (eric-wieser) [inline numpy/core/tests/test_records.py]: I don't quite understand the point you're making here.

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 3 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/scalartypes.c.src]: A comment saying what python type this is would be handy too

File: numpy/core/tests/test_records.py [hunk 5]
```diff
@@ -416,6 +416,21 @@ def test_pickle_3(self):
             assert_(pa.flags.writeable)
             assert_(pa.flags.aligned)
 
+    def test_pickle_void(self):
+        # issue gh-13593
+        dt = np.dtype([('obj', 'O')])
```
Comment (eric-wieser) [inline numpy/core/tests/test_records.py]: Can you give this a second field too, just to be sure?

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 1 above)
Comment (mattip) [reply numpy/core/src/multiarray/scalartypes.c.src]: ok, will modify it above as well

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 3 above)
Comment (mattip) [reply numpy/core/src/multiarray/scalartypes.c.src]: ok

File: numpy/core/tests/test_records.py (hunk 4 above)
Comment (mattip) [reply numpy/core/tests/test_records.py]: `state` is now `(<built-in function scalar>, (dtype([('obj', 'O')]), (bytearray(b'eman'),)))`. Before it was `(<built-in function scalar>, (dtype([('obj', 'O')]), b'xxxxxxx'))` where `xxxxxxxx` is the address of data. The result of `__reduce__` is passed to `pickle` for storage.

I tried to say that we need to make sure `a[0]` is not stored as a pointer (the address of `data`, rather it should be `a[0]` itself

File: numpy/core/tests/test_records.py (hunk 5 above)
Comment (mattip) [reply numpy/core/tests/test_records.py]: ok

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 6]
```diff
@@ -1884,8 +1884,32 @@ gentype_reduce(PyObject *self, PyObject *NPY_UNUSED(args))
     PyTuple_SET_ITEM(ret, 0, obj);
     obj = PyObject_GetAttrString((PyObject *)self, "dtype");
     if (PyArray_IsScalar(self, Object)) {
-        mod = ((PyObjectScalarObject *)self)->obval;
-        PyTuple_SET_ITEM(ret, 1, Py_BuildValue("NO", obj, mod));
+        PyObject* val = ((PyObjectScalarObject *)self)->obval;
+        PyObject * tup = Py_BuildValue("NO", obj, val);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]:
```suggestion
        PyObject *tup = Py_BuildValue("NO", obj, val);
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 7]
```diff
@@ -1884,8 +1884,32 @@ gentype_reduce(PyObject *self, PyObject *NPY_UNUSED(args))
     PyTuple_SET_ITEM(ret, 0, obj);
     obj = PyObject_GetAttrString((PyObject *)self, "dtype");
     if (PyArray_IsScalar(self, Object)) {
-        mod = ((PyObjectScalarObject *)self)->obval;
-        PyTuple_SET_ITEM(ret, 1, Py_BuildValue("NO", obj, mod));
+        PyObject* val = ((PyObjectScalarObject *)self)->obval;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]:
```suggestion
        PyObject *val = ((PyObjectScalarObject *)self)->obval;
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 8]
```diff
@@ -1884,8 +1884,32 @@ gentype_reduce(PyObject *self, PyObject *NPY_UNUSED(args))
...
+    }
+    else if (obj && PyDataType_FLAGCHK((PyArray_Descr *)obj, NPY_LIST_PICKLE)) {
+        /* a structured dtype with an object in a field */
+        PyObject *arr = PyArray_FromScalar(self, NULL);
+        if (arr == NULL) {
+            return NULL;
+        }
+        PyArrayIterObject *it = (PyArrayIterObject *)PyArray_IterNew(arr);
+        if (it == NULL) {
+            return NULL;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]: Unless `PyArray_IterNew` has very weird semantics, 
```suggestion
            Py_DECREF(arr);
            return NULL;
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 9]
```diff
@@ -1884,8 +1884,32 @@ gentype_reduce(PyObject *self, PyObject *NPY_UNUSED(args))
...
+        }
+        /* get arr[0] */
+        PyObject *val = ((PyArray_Descr *)obj)->f->getitem(it->dataptr, arr);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]: Slightly less direct, but possibly clearer anyway:
```suggestion
        PyObject *val = PyArray_GETITEM(arr, it->dataptr);
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 10]
```diff
@@ -1884,8 +1884,32 @@ gentype_reduce(PyObject *self, PyObject *NPY_UNUSED(args))
...
+        /* a structured dtype with an object in a field */
+        PyObject *arr = PyArray_FromScalar(self, NULL);
+        if (arr == NULL) {
+            return NULL;
+        }
+        PyArrayIterObject *it = (PyArrayIterObject *)PyArray_IterNew(arr);
+        if (it == NULL) {
+            return NULL;
+        }
+        /* get arr[0] */
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]:
```suggestion
        /* get arr.item() */
```
or perhaps
```suggestion
        /* get arr.item[()] */
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 11]
```diff
@@ -1884,8 +1884,32 @@ gentype_reduce(PyObject *self, PyObject *NPY_UNUSED(args))
...
+        PyObject *val = ((PyArray_Descr *)obj)->f->getitem(it->dataptr, arr);
+        Py_DECREF(it);
+        Py_DECREF(arr);
+        PyObject * tup = Py_BuildValue("NO", obj, val);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]:
```suggestion
        PyObject *tup = Py_BuildValue("NO", obj, val);
```

File: numpy/core/tests/test_records.py (hunk 4 above)
Comment (eric-wieser) [reply numpy/core/tests/test_records.py]: I think then this test would be clearer as
```python
ctor, args = a[0].__reduce__()
# check the contructor is what we expect before interpreting the arguments
assert ctor is np.core.multiarray.scalar
dtype, obj = args
# make sure we did not pickle the address
assert not isinstance(obj, bytes)
```

**Review by eric-wieser — COMMENTED** [review]
Some C style nits, and a missing decref

File: numpy/core/tests/test_records.py (hunk 4 above)
Comment (mattip) [reply numpy/core/tests/test_records.py]: adopted

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 6 above)
Comment (mattip) [reply numpy/core/src/multiarray/scalartypes.c.src]: fixed

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 7 above)
Comment (mattip) [reply numpy/core/src/multiarray/scalartypes.c.src]: fixed

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 8 above)
Comment (mattip) [reply numpy/core/src/multiarray/scalartypes.c.src]: nice. Fixing

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 10 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/scalartypes.c.src]: ^ corrected

Comment (mattip) [reply numpy/core/src/multiarray/scalartypes.c.src]: adopting the latter

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 11 above)
Comment (mattip) [reply numpy/core/src/multiarray/scalartypes.c.src]: fixing

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 10 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/scalartypes.c.src]: Thought about it some more - this is actually the former, since the latter is just `self`

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 9 above)
Comment (mattip) [reply numpy/core/src/multiarray/scalartypes.c.src]: adopting, with a cast `(PyArrayObject *)arr

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 12]
```diff
@@ -1884,8 +1884,33 @@ gentype_reduce(PyObject *self, PyObject *NPY_UNUSED(args))
...
+        PyObject *arr = PyArray_FromScalar(self, NULL);
+        if (arr == NULL) {
+            return NULL;
+        }
+        PyArrayIterObject *it = (PyArrayIterObject *)PyArray_IterNew(arr);
+        if (it == NULL) {
+            Py_DECREF(arr);
+            return NULL;
+        }
+        /* arr[()] */
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]: Sorry for the bad advice
```suggestion
        /* arr.item() */
```
This is specifically casting from a numpy scalar to a python one, in order to allow pickling

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 13]
```diff
@@ -1884,8 +1884,33 @@ gentype_reduce(PyObject *self, PyObject *NPY_UNUSED(args))
...
+        PyObject *val = PyArray_GETITEM((PyArrayObject *)arr, it->dataptr);
+        Py_DECREF(it);
+        Py_DECREF(arr);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]:
```suggestion
        Py_DECREF(arr);
        if (val == NULL) {
            return NULL;
        }
```

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 10 above)
Comment (mattip) [reply numpy/core/src/multiarray/scalartypes.c.src]: so arr.item() ?

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 13 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/scalartypes.c.src]: @mattip: Just this change left I think, unless you can convince me it's not needed

Comment (mattip) [reply numpy/core/src/multiarray/scalartypes.c.src]: good, fixing

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 14]
```diff
@@ -1884,8 +1884,36 @@ gentype_reduce(PyObject *self, PyObject *NPY_UNUSED(args))
...
+            return NULL;
+        }
+        /* arr.item() */
+        PyObject *val = PyArray_GETITEM((PyArrayObject *)arr, it->dataptr);
+        Py_DECREF(it);
+        Py_DECREF(arr);
+        if (val == NULL) {
+            return NULL;
+        }
+        PyObject *tup = Py_BuildValue("NO", obj, val);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]: Sorry, you were right to be concerned here - `PyArray_GETITEM` returns a new reference, so as written this leaks `val`
```suggestion
        PyObject *tup = Py_BuildValue("NN", obj, val);
```

Comment (eric-wieser) [reply numpy/core/src/multiarray/scalartypes.c.src]: Or if these strings are annoying, just
```suggestion
PyObject *tup = PyTuple_Pack(2, obj, val);
Py_DECREF(obj);
Py_DECREF(val):
```

File: numpy/core/src/multiarray/multiarraymodule.c [hunk 15]
```diff
@@ -1891,8 +1891,16 @@ array_scalar(PyObject *NPY_UNUSED(ignored), PyObject *args, PyObject *kwds)
...
         return NULL;
     }
+    if (PyDataType_FLAGCHK(typecode, NPY_LIST_PICKLE)) {
+        if (!PySequence_Check(obj)) {
+            PyErr_SetString(PyExc_TypeError,
+                            "scalar pickle not returning sequence");
+            return NULL;
+        }
+        dptr = &obj;
+    }
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/multiarraymodule.c]: This is not easily testable, right?

**Review by eric-wieser — APPROVED** [review]

File: numpy/core/src/multiarray/multiarraymodule.c (hunk 15 above)
Comment (mattip) [reply numpy/core/src/multiarray/multiarraymodule.c]: Added a test in 2e186ed

File: numpy/core/src/multiarray/multiarraymodule.c [hunk 16]
```diff
@@ -1891,8 +1891,16 @@ array_scalar(PyObject *NPY_UNUSED(ignored), PyObject *args, PyObject *kwds)
                 &PyArrayDescr_Type, &typecode, &obj)) {
         return NULL;
     }
+    if (PyDataType_FLAGCHK(typecode, NPY_LIST_PICKLE)) {
+        if (!PySequence_Check(obj)) {
+            PyErr_SetString(PyExc_TypeError,
+                            "scalar pickle not returning sequence");
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/multiarraymodule.c]: Ah, now your test is there I understand the purpose of this error. Perhaps:
```suggestion
                            "found non-sequence while unpicking scalar with "
                            "NPY_LIST_PICKLE set");
```

File: numpy/core/src/multiarray/multiarraymodule.c (hunk 15 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/multiarraymodule.c]: Nice!

File: numpy/core/src/multiarray/multiarraymodule.c [hunk 17]
```diff
@@ -1891,8 +1891,17 @@ array_scalar(PyObject *NPY_UNUSED(ignored), PyObject *args, PyObject *kwds)
                 &PyArrayDescr_Type, &typecode, &obj)) {
         return NULL;
     }
+    if (PyDataType_FLAGCHK(typecode, NPY_LIST_PICKLE)) {
+        if (!PySequence_Check(obj)) {
+            PyErr_SetString(PyExc_TypeError,
+                            "found non-sequence while unpicking scalar with "
```
Comment (seberg) [inline numpy/core/src/multiarray/multiarraymodule.c]:
```suggestion
                            "found non-sequence while unpickling scalar with "
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 18]
```diff
@@ -1884,8 +1884,36 @@ gentype_reduce(PyObject *self, PyObject *NPY_UNUSED(args))
...
+        if (arr == NULL) {
+            return NULL;
+        }
+        PyArrayIterObject *it = (PyArrayIterObject *)PyArray_IterNew(arr);
+        if (it == NULL) {
+            Py_DECREF(arr);
+            return NULL;
+        }
+        /* arr.item() */
+        PyObject *val = PyArray_GETITEM((PyArrayObject *)arr, it->dataptr);
```
Comment (seberg) [inline numpy/core/src/multiarray/scalartypes.c.src]: Har, fun dance, and all just because PyArray_GETITEM needs a (fake) array object. We need to fix it, but for now its good.

Comment (seberg) [reply numpy/core/src/multiarray/scalartypes.c.src]: Can you delete the iteterator? I do not understand why `PyArray_DATA` will not be just as good here. It should be a 1D array, no?

**Review by seberg — APPROVED** [review]
LGTM, sorry for only going over it now. If you want, ping me and I will see if the iterator removal works.

**Review by mattip — COMMENTED** [review]
Fixed in 838c0e45e
