### PR TITLE
BUG: NaT now sorts to ends of arrays

### LINKED ISSUE #12629: NaT and extended sort order
https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.sort.html#numpy.sort describes how `np.nan` is handled for floating point data. `NaT` and datetime data are not mentioned.

### Reproducing code example:

In the following, `NaN` is sorted to the end, while `NaT` is sorted to the start.

```python
In [32]: arr = np.array([np.nan, 1, 2, 3])

In [33]: arr.sort(); arr
Out[33]: array([ 1.,  2.,  3., nan])

In [34]: dtarr = np.array(['NaT', 1, 2, 3], dtype='datetime64[ns]')

In [35]: dtarr.sort(); dtarr
Out[35]:
array([                          'NaT', '1970-01-01T00:00:00.000000001',
       '1970-01-01T00:00:00.000000002', '1970-01-01T00:00:00.000000003'],
      dtype='datetime64[ns]')
```

So my question: is NaT sorting to the start a bug or deliberate? If it's deliberate, I could add a section to the docs noting that.

### Numpy/Python version information:

1.16.0.dev0+9cc9f01 3.7.1 (default, Nov  6 2018, 18:45:35)
[Clang 10.0.0 (clang-1000.11.45.5)]

### PR DESCRIPTION
**Pull request by tylerjereddy**
Fixes #12629, which is also referenced from a `pandas` PR.

If we ultimately decide that this a bug fix we want to do then probably need:

- [x] `versionchanged` directive in `sort`-related docs
- [x] `1.17` release note of some sort
- [ ] any follow-ups / issues with argmin/max & so-on behaviors / consistency for `NaT`  handling to worry about?
  -  for `_argmin` there's a note in `numpy/core/src/multiarray/arraytypes.c.src` that "NPY_DATETIME_NAT is smaller than every other value"
  - there are separate `TYPE_COMPARE` and `TYPE_LT` style functions in NumPy & I've only touched the latter here as per minimum changes for the specific issue at hand

Other useful notes:
- from around 10 years ago, 717c7acf14d04 contains the original changes to adjust nan sorting to the end, as far as I can tell; the file in question no longer exists
- but `numpy/core/src/multiarray/arraytypes.c.src` contains the comment regarding `np.nan` values being sorted to the end; I initially tried making some changes in there, but it really seems to be the `TYPE_LT` style function that needs adjustment in this case

### CODE REVIEW

**Review by mhvk — COMMENTED** [review]
To me, this seems logical. Not sure how much of a deprecation is needed.

File: numpy/core/src/npysort/npysort_common.h [hunk 1]
```diff
@@ -329,6 +329,16 @@ UNICODE_LT(npy_ucs4 *s1, npy_ucs4 *s2, size_t len)
...
+        b != NPY_DATETIME_NAT) {
+        return 0;
+    }
+
+    if (a != NPY_DATETIME_NAT &&
+        b == NPY_DATETIME_NAT) {
+        return 1;
+    }
+
     return a < b;
```
[the remark this answers is not in the document]
Comment (seberg) [reply numpy/core/src/npysort/npysort_common.h]: Hmm, the last version would make `argsort` unstable for NaT, though. Doesn't sound awfully bad, maybe depends on how much worth the gain is.

**Comment by seberg** [comment]
It seems currently NaT is completely ignored for min/max and argmin/argmax. I wonder if we should push to change that to be identical NaN (NaN is always returned). I guess if it that bites someone, on the up-side it probably will be loud since it points to NaT.

There is also an independend bug for `argmin` when it starts with NaT and has only one not NaT item at the end:
```diff
--- a/numpy/core/src/multiarray/arraytypes.c.src
+++ b/numpy/core/src/multiarray/arraytypes.c.src
@@ -3198,7 +3198,7 @@ static int
         mp = ip[i];
         i++;
     }
-    if (i == n) {
+    if (i - 1 == n) {
         /* All NaTs: return 0 */
         *min_ind = 0;
         return 0;
```

File: numpy/core/src/npysort/npysort_common.h (hunk 1 above)
[the remark this answers is not in the document]
Comment (mhvk) [reply numpy/core/src/npysort/npysort_common.h]: It is `LT`, so I guess to keep sort order equal should evaluate to false; possibly in sorting, it gets called as `LT(next, prev)`?

**Comment by charris** [comment]
> It is LT, so I guess to keep sort order equal should evaluate to false

Agree. If the two quantities are the same, NaT, NaN or not, then one cannot be < the other. That is for sorting only and independent of their "normal" arithmetic.

File: numpy/core/src/npysort/npysort_common.h (hunk 1 above)
[the remark this answers is not in the document]
Comment (seberg) [reply numpy/core/src/npysort/npysort_common.h]: I think I was just imagining things. This looks good, and I think we should use it.

About argmin/argmax, I would tend to not worry too much about it and also change the sort order? As for min/max, change it to return NaT if it exists. We won't find out if anyones code is broken by such changes before trying probably, and now is the perfect time ;).

**Comment by charris** [comment]
Needs a release note.

**Comment by seberg** [comment]
@tylerjereddy, I think separate PRs should be fine. Just need to open an issue with 1.17.0 milestone, because I would hate to not do it all in the same release.

File: numpy/core/src/npysort/npysort_common.h [hunk 2]
```diff
@@ -329,7 +329,7 @@ UNICODE_LT(npy_ucs4 *s1, npy_ucs4 *s2, size_t len)
 NPY_INLINE static int
 DATETIME_LT(npy_datetime a, npy_datetime b)
 {
-    return a < b;
+    return a < b ? a != NPY_DATETIME_NAT : b == NPY_DATETIME_NAT;
```
Comment (charris) [inline numpy/core/src/npysort/npysort_common.h]: I don't think this is correct. If both `a` and `b` are NaT, then the return value should be False, but here is will be True.

Comment (tylerjereddy) [reply numpy/core/src/npysort/npysort_common.h]: Do we have an idiomatic way to probe sort stability of identical array elements at the Python level? I want a test to fail if this is wrong.

For example, the following isn't good enough to detect an issue, but may gave you an idea of what I'm thinking about:

```python
 139     def test_lt_nat_stability(self):
 140         # NaT < NaT should be False internally for sort purposes
 141         arr = np.array(['NaT', 'NaT'], dtype='M8')
 142         ids_expected = id(arr[0]), id(arr[1])
 143         arr.sort()
 144         ids_actual = id(arr[0]), id(arr[1])
 145         assert_equal(ids_actual[0], ids_expected[0])
```

Does anything (pointer, address number exposed somewhere else) change if they swap?

Comment (charris) [reply numpy/core/src/npysort/npysort_common.h]: You cannot tell just sorting the elements, so we rely on argsort. An array of `Nat` should do the trick if you use a stable sort, but you do need different lengths as mergesort fall back on insertion sort for smaller arrays. There are some tests in `test_multiarray.py`, search for `# check that stable argsorts are stable`, but is looks incomplete to me as it should also test arrays of `NaN` and `NaT`. By current standards, the tests aren't all that complete :(

Comment (mhvk) [reply numpy/core/src/npysort/npysort_common.h]: I was going to recommend sorting a structured array with one element the time with `NaT`, and another effectively an index, but `argsort` is more direct (as long as we're sure it follows the same sorting path).

Comment (charris) [reply numpy/core/src/npysort/npysort_common.h]: > as long as we're sure it follows the same sorting path

It should, but of course there could be bugs :) What we are really testing is the `*_LT` macro. I think there are also some tests for NaNs, but I didn't notice any for NaNs and stability combined.

**Comment by tylerjereddy** [comment]
Ok, I restored logic closer to my original instead of one of the reviewer-suggested ternary operators. It is just easier for me to read it. I did apply some of the suggested simplifications to those conditionals.

I added a test for argsort stabillity with all `NaT` values in an array. This seems ok as long as I force mergesort. It looks like the other stability tests also force mergesort. That does make sense of course, but I wonder about the other sorting code paths.

I did notice that some of the sorting algorithms will segfault with NaT if LT implementation is not correct (i.e., some of them would segfault with one of the ternary operators suggested above). That means we don't test the NaT argsort codepaths with other sort algorithms. Do we want something crude parametrized over the sorting `kind`s just to make sure there's no major issue (i.e., all-NaT array in sorts to all-NaT array out)?

**Comment by charris** [comment]
The other sorts will change the relative position of even identical elements, the tests for them is simply that the result be sorted. We will probably want parametrized tests at some point, especially with type specific sorts like the upcoming radix sort. Both `timsort` and `radixsort` should also be stable, so we will need to expand the tests for those.  A new `test_sorting.py` module is looking like the way to go, that whole library has grown over the years.

**Comment by seberg** [comment]
@tylerjereddy do you want to put this in and you/I can do the rest in a followup, or should we/I continue here? Got to resolve the conflicts, but I can do that.

**Comment by tylerjereddy** [comment]
Are we concerned about deprecation? I guess opening a tracking issue for the other things we'd need to do before 1.17 related to this may be useful.

**Comment by seberg** [comment]
Yeah, you are right. It is a bit annoying because it will create FutureWarnings with no good way of silencing them (except manually removing the NaTs, or, I suppose, `view(np.int64)` is a hackish way to do it in a more or less future proof way). For min/max it is a bit "nicer" because at least the result is pretty special.
It all feels painful to deprecate, but I suppose few people will actually hit it.

**Comment by tylerjereddy** [comment]
I'm happy if we want to delay this to 1.18. I think 1.17 is getting quite a lot of stuff already?

**Comment by seberg** [comment]
Sounds OK to me, I do not remember that there was something specific that made it super pressing. Only feel it should keep in sync with the argmin/argmax issue. Moved both milestones.

**Comment by seberg** [comment]
We need to fix up the release notes. We just opened a fixup for the (somewhat, but maybe not exactly) related fixes to min/max and argmin/argmax. So I would like to put this into 1.18.

**Comment by mattip** [comment]
Rebased and reformated release note for 1.18

**Comment by charris** [comment]
Let's put this in and see what feedback we get.

**Comment by charris** [comment]
Thanks Tyler.

**Comment by jorisvandenbossche** [comment]
It seems this only has been done for datetime64, but not for timedelta64 (introducing another inconsistency). That might be something to still consider for 1.8 ?

File: numpy/core/fromnumeric.py [hunk 3]
```diff
@@ -944,6 +944,10 @@ def sort(a, axis=-1, kind=None, order=None):
     'mergesort' and 'stable' are mapped to radix sort for integer data types. Radix sort is an
     O(n) sort instead of O(n log n).
 
+    .. versionchanged:: 1.17.0
```
Comment (tylerjereddy) [inline numpy/core/fromnumeric.py]: Minor point -- I forgot to bump this for `1.18.0`?
