### PR TITLE
BUG: fix thread safety of `array_getbuffer`

### LINKED ISSUE #30648: BUG: data races in `_buffer_get_info` when multiple threads try to access buffer of ndarray
### Describe the issue:

Run the reproducer using a TSAN instrumented build of CPython and numpy.

### Reproduce the code example:

```python
import numpy as np
from threading import Thread, Barrier
import inspect
import random
arr = np.array([1, 2, 3, 4, 5])

flags = [inspect.BufferFlags.STRIDED, inspect.BufferFlags.READ]

barrier = Barrier(4)
def func():
    barrier.wait()
    arr.__buffer__(random.choice(flags))

threads = [Thread(target=func) for _ in range(4)]
for t in threads:
    t.start()
for t in threads:
    t.join()
```

### Error message:

```shell
WARNING: ThreadSanitizer: data race (pid=6155)
  Read of size 8 at 0x000128060100 by thread T1:
    #0 _buffer_get_info <null> (_multiarray_umath.cpython-314t-darwin.so:arm64+0x37c1d8)
    #1 array_getbuffer <null> (_multiarray_umath.cpython-314t-darwin.so:arm64+0x37c5b8)
    #2 _PyMemoryView_FromBufferProc memoryobject.c:838 (libpython3.14t.dylib:arm64+0x122c1c)
    #3 buffer typeobject.c:9688 (libpython3.14t.dylib:arm64+0x1a48b0)
    #4 wrapperdescr_call descrobject.c:570 (libpython3.14t.dylib:arm64+0xa17ac)
    #5 _PyObject_MakeTpCall call.c:242 (libpython3.14t.dylib:arm64+0x8a3ac)
    #6 PyObject_Vectorcall call.c:327 (libpython3.14t.dylib:arm64+0x8af9c)
    #7 _PyEval_EvalFrameDefault generated_cases.c.h:1619 (libpython3.14t.dylib:arm64+0x27cc00)
    #8 _PyEval_Vector ceval.c:2083 (libpython3.14t.dylib:arm64+0x278928)
    #9 _PyFunction_Vectorcall call.c (libpython3.14t.dylib:arm64+0x8b54c)
    #10 method_vectorcall classobject.c:73 (libpython3.14t.dylib:arm64+0x8f9c0)
    #11 context_run context.c:728 (libpython3.14t.dylib:arm64+0x2c3d18)
    #12 method_vectorcall_FASTCALL_KEYWORDS descrobject.c:421 (libpython3.14t.dylib:arm64+0xa21cc)
    #13 PyObject_Vectorcall call.c:327 (libpython3.14t.dylib:arm64+0x8af00)
    #14 _PyEval_EvalFrameDefault generated_cases.c.h:1619 (libpython3.14t.dylib:arm64+0x27cc00)
    #15 _PyEval_Vector ceval.c:2083 (libpython3.14t.dylib:arm64+0x278928)
    #16 _PyFunction_Vectorcall call.c (libpython3.14t.dylib:arm64+0x8b54c)
    #17 method_vectorcall classobject.c:73 (libpython3.14t.dylib:arm64+0x8f9c0)
    #18 _PyObject_Call call.c:348 (libpython3.14t.dylib:arm64+0x8b1c0)
    #19 PyObject_Call call.c:373 (libpython3.14t.dylib:arm64+0x8b234)
    #20 thread_run _threadmodule.c:359 (libpython3.14t.dylib:arm64+0x419b3c)
    #21 pythread_wrapper thread_pthread.h:242 (libpython3.14t.dylib:arm64+0x369a20)

  Previous write of size 8 at 0x000128060100 by thread T4:
    #0 _buffer_info_new <null> (_multiarray_umath.cpython-314t-darwin.so:arm64+0x37dc84)
    #1 _buffer_get_info <null> (_multiarray_umath.cpython-314t-darwin.so:arm64+0x37c110)
    #2 array_getbuffer <null> (_multiarray_umath.cpython-314t-darwin.so:arm64+0x37c5b8)
    #3 _PyMemoryView_FromBufferProc memoryobject.c:838 (libpython3.14t.dylib:arm64+0x122c1c)
    #4 buffer typeobject.c:9688 (libpython3.14t.dylib:arm64+0x1a48b0)
    #5 wrapperdescr_call descrobject.c:570 (libpython3.14t.dylib:arm64+0xa17ac)
    #6 _PyObject_MakeTpCall call.c:242 (libpython3.14t.dylib:arm64+0x8a3ac)
    #7 PyObject_Vectorcall call.c:327 (libpython3.14t.dylib:arm64+0x8af9c)
    #8 _PyEval_EvalFrameDefault generated_cases.c.h:1619 (libpython3.14t.dylib:arm64+0x27cc00)
    #9 _PyEval_Vector ceval.c:2083 (libpython3.14t.dylib:arm64+0x278928)
    #10 _PyFunction_Vectorcall call.c (libpython3.14t.dylib:arm64+0x8b54c)
    #11 method_vectorcall classobject.c:73 (libpython3.14t.dylib:arm64+0x8f9c0)
    #12 context_run context.c:728 (libpython3.14t.dylib:arm64+0x2c3d18)
    #13 method_vectorcall_FASTCALL_KEYWORDS descrobject.c:421 (libpython3.14t.dylib:arm64+0xa21cc)
    #14 PyObject_Vectorcall call.c:327 (libpython3.14t.dylib:arm64+0x8af00)
    #15 _PyEval_EvalFrameDefault generated_cases.c.h:1619 (libpython3.14t.dylib:arm64+0x27cc00)
    #16 _PyEval_Vector ceval.c:2083 (libpython3.14t.dylib:arm64+0x278928)
    #17 _PyFunction_Vectorcall call.c (libpython3.14t.dylib:arm64+0x8b54c)
    #18 method_vectorcall classobject.c:73 (libpython3.14t.dylib:arm64+0x8f9c0)
    #19 _PyObject_Call call.c:348 (libpython3.14t.dylib:arm64+0x8b1c0)
    #20 PyObject_Call call.c:373 (libpython3.14t.dylib:arm64+0x8b234)
    #21 thread_run _threadmodule.c:359 (libpython3.14t.dylib:arm64+0x419b3c)
    #22 pythread_wrapper thread_pthread.h:242 (libpython3.14t.dylib:arm64+0x369a20)

  Thread T1 (tid=67013, running) created by main thread at:
    #0 pthread_create <null> (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x2f708)
    #1 do_start_joinable_thread thread_pthread.h:289 (libpython3.14t.dylib:arm64+0x3686e0)
    #2 PyThread_start_joinable_thread thread_pthread.h:331 (libpython3.14t.dylib:arm64+0x368528)
    #3 do_start_new_thread _threadmodule.c:1868 (libpython3.14t.dylib:arm64+0x4196f0)
    #4 thread_PyThread_start_joinable_thread _threadmodule.c:1991 (libpython3.14t.dylib:arm64+0x41847c)
    #5 cfunction_call methodobject.c:564 (libpython3.14t.dylib:arm64+0x12d450)
    #6 _PyObject_MakeTpCall call.c:242 (libpython3.14t.dylib:arm64+0x8a3ac)
    #7 PyObject_Vectorcall call.c:327 (libpython3.14t.dylib:arm64+0x8af9c)
    #8 _PyEval_EvalFrameDefault generated_cases.c.h:2959 (libpython3.14t.dylib:arm64+0x280794)
    #9 PyEval_EvalCode ceval.c:975 (libpython3.14t.dylib:arm64+0x278504)
    #10 run_mod pythonrun.c:1459 (libpython3.14t.dylib:arm64+0x347380)
    #11 _PyRun_SimpleFileObject pythonrun.c:521 (libpython3.14t.dylib:arm64+0x342a5c)
    #12 _PyRun_AnyFileObject pythonrun.c:81 (libpython3.14t.dylib:arm64+0x3421b0)
    #13 pymain_run_file main.c:429 (libpython3.14t.dylib:arm64+0x383bb0)
    #14 Py_RunMain main.c:775 (libpython3.14t.dylib:arm64+0x382fdc)
    #15 pymain_main main.c:805 (libpython3.14t.dylib:arm64+0x383448)
    #16 Py_BytesMain main.c:829 (libpython3.14t.dylib:arm64+0x38351c)
    #17 main python.c:15 (python3.14:arm64+0x100000714)

  Thread T4 (tid=67016, running) created by main thread at:
    #0 pthread_create <null> (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x2f708)
    #1 do_start_joinable_thread thread_pthread.h:289 (libpython3.14t.dylib:arm64+0x3686e0)
    #2 PyThread_start_joinable_thread thread_pthread.h:331 (libpython3.14t.dylib:arm64+0x368528)
    #3 do_start_new_thread _threadmodule.c:1868 (libpython3.14t.dylib:arm64+0x4196f0)
    #4 thread_PyThread_start_joinable_thread _threadmodule.c:1991 (libpython3.14t.dylib:arm64+0x41847c)
    #5 cfunction_call methodobject.c:564 (libpython3.14t.dylib:arm64+0x12d450)
    #6 _PyObject_MakeTpCall call.c:242 (libpython3.14t.dylib:arm64+0x8a3ac)
    #7 PyObject_Vectorcall call.c:327 (libpython3.14t.dylib:arm64+0x8af9c)
    #8 _PyEval_EvalFrameDefault generated_cases.c.h:3227 (libpython3.14t.dylib:arm64+0x28150c)
    #9 PyEval_EvalCode ceval.c:975 (libpython3.14t.dylib:arm64+0x278504)
    #10 run_mod pythonrun.c:1459 (libpython3.14t.dylib:arm64+0x347380)
    #11 _PyRun_SimpleFileObject pythonrun.c:521 (libpython3.14t.dylib:arm64+0x342a5c)
    #12 _PyRun_AnyFileObject pythonrun.c:81 (libpython3.14t.dylib:arm64+0x3421b0)
    #13 pymain_run_file main.c:429 (libpython3.14t.dylib:arm64+0x383bb0)
    #14 Py_RunMain main.c:775 (libpython3.14t.dylib:arm64+0x382fdc)
    #15 pymain_main main.c:805 (libpython3.14t.dylib:arm64+0x383448)
    #16 Py_BytesMain main.c:829 (libpython3.14t.dylib:arm64+0x38351c)
    #17 main python.c:15 (python3.14:arm64+0x100000714)

SUMMARY: ThreadSanitizer: data race (_multiarray_umath.cpython-314t-darwin.so:arm64+0x37c1d8) in _buffer_get_info+0x154
```

### Python and NumPy Versions:

2.5.0.dev0+git20260114.a90ef57
3.14.2+ free-threading build (heads/3.14:c3fbe28, Dec 12 2025, 18:50:21) [Clang 17.0.0 (clang-1700.4.4.1)]

### Runtime Environment:

[{'numpy_version': '2.5.0.dev0+git20260114.a90ef57',
  'python': '3.14.2+ free-threading build (heads/3.14:c3fbe28, Dec 12 2025, '
            '18:50:21) [Clang 17.0.0 (clang-1700.4.4.1)]',
  'uname': uname_result(system='Darwin', node='Kumars-MacBook-Air.local', release='25.2.0', version='Darwin Kernel Version 25.2.0: Tue Nov 18 21:08:48 PST 2025; root:xnu-12377.61.12~1/RELEASE_ARM64_T8132', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP', 'ASIMDDP'],
                      'not_found': ['ASIMDFHM', 'SVE']}},
 {'ignore_floating_point_errors_in_matmul': True}]

### How does this issue affect you or how did you find it:

_No response_

### PR DESCRIPTION
**Pull request by kumaraditya303**
Fixes https://github.com/numpy/numpy/issues/30648

### CODE REVIEW

**Comment by Harshit-shaw** [comment]
genius

File: numpy/_core/src/multiarray/buffer.c [hunk 1]
```diff
@@ -793,8 +793,10 @@ array_getbuffer(PyObject *obj, Py_buffer *view, int flags)
     }
 
     /* Fill in information (and add it to _buffer_info if necessary) */
+    Py_BEGIN_CRITICAL_SECTION(self);
     info = _buffer_get_info(
             &((PyArrayObject_fields *)self)->_buffer_info, obj, flags);
+    Py_END_CRITICAL_SECTION();
```
Comment (ngoldbaum) [inline numpy/_core/src/multiarray/buffer.c:799]: There's another call to `_buffer_get_info` that's exposed to Python in `void_getbuffer` below. That function is used by the `np.void` scalar type and needs a critical section if this needs a critical section

File: numpy/_core/src/multiarray/buffer.c [hunk 2]
```diff
@@ -793,8 +793,10 @@ array_getbuffer(PyObject *obj, Py_buffer *view, int flags)
     }
 
     /* Fill in information (and add it to _buffer_info if necessary) */
+    Py_BEGIN_CRITICAL_SECTION(self);
     info = _buffer_get_info(
             &((PyArrayObject_fields *)self)->_buffer_info, obj, flags);
```
Comment (ngoldbaum) [inline numpy/_core/src/multiarray/buffer.c:798]: `_buffer_get_info` calls `_buffer_info_new` unconditionally, which in turn allocates space for the buffer linked list using `PyObject_Malloc`. Doesn't that release critical sections?

It also looks like there are a bunch of code paths for void data types that call into the C API in a manner that might release critical sections. I'm referring to the HASFIELDS and HASSUBARRAY code paths. Is that a problem?

Also, It's a preexisting issue in this code, but isn't it incorrect to use `PyObject_Malloc` there? I think it should be using `RawMalloc` instead, since it's not a PyObject subtype.

File: numpy/_core/tests/test_multithreading.py [hunk 3]
```diff
@@ -375,3 +375,15 @@ def replace_list_items(b):
...
+    import inspect
+    arr = np.arange(1000)
+    flags = [inspect.BufferFlags.STRIDED, inspect.BufferFlags.READ]
+
+    def func(b):
+        b.wait()
+        for i in range(100):
+            arr.__buffer__(flags[i % 2])
+
+    run_threaded(func, max_workers=8, pass_barrier=True)
```
Comment (ngoldbaum) [inline numpy/_core/tests/test_multithreading.py:389]: Given the complexity of the code paths in the implementation to handle void data types, I think it makes sense to add a test here that uses np.void.

Maybe look at `numpy/_core/tests/test_scalarbuffer.py::TestScalarPEP3118` for some examples that create buffers from scalars, including void scalars and `numpy/_core/tests/test_multiarray.py::TestPEP3118Dtype` and `TestNewBufferProtocol` in the same file for some examples using this API with nontrivial void dtypes.

**Review by ngoldbaum — COMMENTED** [review]
Some comments and questions inline

File: numpy/_core/src/multiarray/buffer.c (hunk 2 above)
Comment (seberg) [reply numpy/_core/src/multiarray/buffer.c:798]: Yeah, I think I did that for a while. I think it should be `PyMem_Malloc`, since `RawMalloc` won't use the python allocator at all (which we want though, since it is faster).

File: numpy/_core/tests/test_multithreading.py (hunk 3 above)
Comment (kumaraditya303) [reply numpy/_core/tests/test_multithreading.py:389]: I added a test based on `test_void_scalar_structured_data`

File: numpy/_core/src/multiarray/buffer.c (hunk 1 above)
Comment (kumaraditya303) [reply numpy/_core/src/multiarray/buffer.c:799]: fixed

File: numpy/_core/src/multiarray/buffer.c (hunk 2 above)
Comment (kumaraditya303) [reply numpy/_core/src/multiarray/buffer.c:798]: > _buffer_get_info calls _buffer_info_new unconditionally, which in turn allocates space for the buffer linked list using PyObject_Malloc. Doesn't that release critical sections?

memory allocations APIs never release the thread state so the critical sections are never released. 

> It also looks like there are a bunch of code paths for void data types that call into the C API in a manner that might release critical sections. I'm referring to the HASFIELDS and HASSUBARRAY code paths. Is that a problem?

The code is reading values from tuples and converting ints to C ints and vice-versa. All that is safe because any allocated objects is local and not shared across the thread which would cause critical section to get released.

Comment (seberg) [reply numpy/_core/src/multiarray/buffer.c:798]: > All that is safe because any allocated objects is local and not shared across the thread which would cause critical section to get released.

It has puzzled me a bit before when they can get released, but happy if this should be safe.
(It might be cool to have a clearer description in the C-API docs, but that is a different matter. For myself, I decided right now that I'll assume pretty much anything may release it.)

Things might get a bit more complicated if we have an array that is both C- and F-contiguous and is exported both ways.  However, I don't think it changes anything w.r.t. to this.

**Review by seberg — APPROVED** [review]
Thanks @kumaraditya303, looks right to me and the test look good too. Let's get it in!

File: numpy/_core/tests/test_multithreading.py [hunk 4]
```diff
@@ -375,3 +375,28 @@ def replace_list_items(b):
...
+
+def test_void_dtype__buffer__thread_safety():
+    import inspect
+    dt = np.dtype([('name', np.str_, 16), ('grades', np.float64, (2,))])
+    x = np.array(('ndarray_scalar', (1.2, 3.0)), dtype=dt)[()]
+    assert isinstance(x, np.void)
+    flags = [inspect.BufferFlags.STRIDES, inspect.BufferFlags.READ]
+    def func(b):
```
Comment (seberg) [inline numpy/_core/tests/test_multithreading.py:398]:
```suggestion

    def func(b):
```
