### PR TITLE
BUG: Fix ``from_float_positional`` errors for huge pads

### LINKED ISSUE #28068: BUG: `numpy.format_float_positional` causes Segmentaion Fault when accepting a large `pad_left`
### Describe the issue:

I was working on plfuzz, an automatic Python library testing tool, and the tool found that if we pass a large `pad_left` to `numpy.format_float_positional`, NumPy crashes with Segmentation Fault. 

The documentation says:

> pad_left: non-negative integer, optional
Pad the left side of the string with whitespace until at least that many characters are to the left of the decimal point.

It's seams that a large `pad_left` meets the requirement of "non-negative integer", but the `numpy.format_float_positional` crashes.  
I think this is not a serious bug, but it might be a good idea to fix it so that it is more user-friendly in the event of a user error.

### Reproduce the code example:

```python
args= [1.0471, 2, True, True, "k", 2048, int(1e5), 0, 0]
import numpy as np
np.format_float_positional(*args)
```

### Error message:

```shell
(py313) root@a475b702ecc0:~/plfuzz# gdb python
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04.2) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...
(gdb) set args bugs/bug5_pendding.py 
(gdb) r
Starting program: /root/miniconda3/envs/py313/bin/python bugs/bug5_pendding.py 
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7f9250fff640 (LWP 98733)]
[New Thread 0x7f92507fe640 (LWP 98734)]
[New Thread 0x7f924fffd640 (LWP 98735)]
[New Thread 0x7f924f7fc640 (LWP 98736)]
[New Thread 0x7f924effb640 (LWP 98737)]
[New Thread 0x7f924e7fa640 (LWP 98738)]
[New Thread 0x7f924dff9640 (LWP 98739)]
[New Thread 0x7f924d7f8640 (LWP 98740)]
[New Thread 0x7f924cff7640 (LWP 98741)]
[New Thread 0x7f924c7f6640 (LWP 98742)]
[New Thread 0x7f924bff5640 (LWP 98743)]
[New Thread 0x7f924b7f4640 (LWP 98744)]
[New Thread 0x7f924aff3640 (LWP 98745)]
[New Thread 0x7f924a7f2640 (LWP 98746)]
[New Thread 0x7f9249ff1640 (LWP 98747)]
[New Thread 0x7f92497f0640 (LWP 98748)]
[New Thread 0x7f9248fef640 (LWP 98749)]
[New Thread 0x7f92487ee640 (LWP 98750)]
[New Thread 0x7f9247fed640 (LWP 98751)]
[New Thread 0x7f92477ec640 (LWP 98752)]
[New Thread 0x7f9246feb640 (LWP 98753)]
[New Thread 0x7f92467ea640 (LWP 98754)]
[New Thread 0x7f9245fe9640 (LWP 98755)]
[New Thread 0x7f92457e8640 (LWP 98756)]
[New Thread 0x7f9244fe7640 (LWP 98757)]
[New Thread 0x7f92447e6640 (LWP 98758)]
[New Thread 0x7f9243fe5640 (LWP 98759)]
[New Thread 0x7f92437e4640 (LWP 98760)]
[New Thread 0x7f9242fe3640 (LWP 98761)]
[New Thread 0x7f92427e2640 (LWP 98762)]
[New Thread 0x7f9241fe1640 (LWP 98763)]
[New Thread 0x7f92417e0640 (LWP 98764)]
[New Thread 0x7f9240fdf640 (LWP 98765)]
[New Thread 0x7f92407de640 (LWP 98766)]
[New Thread 0x7f923ffdd640 (LWP 98767)]
[New Thread 0x7f923f7dc640 (LWP 98768)]
[New Thread 0x7f923efdb640 (LWP 98769)]
[New Thread 0x7f923e7da640 (LWP 98770)]
[New Thread 0x7f923dfd9640 (LWP 98771)]
[New Thread 0x7f923d7d8640 (LWP 98772)]
[New Thread 0x7f923cfd7640 (LWP 98773)]
[New Thread 0x7f923c7d6640 (LWP 98774)]
[New Thread 0x7f923bfd5640 (LWP 98775)]
[New Thread 0x7f923b7d4640 (LWP 98776)]
[New Thread 0x7f923afd3640 (LWP 98777)]
[New Thread 0x7f923a7d2640 (LWP 98778)]
[New Thread 0x7f9239fd1640 (LWP 98779)]
[New Thread 0x7f92397d0640 (LWP 98780)]
[New Thread 0x7f9238fcf640 (LWP 98781)]
[New Thread 0x7f92387ce640 (LWP 98782)]
[New Thread 0x7f9237fcd640 (LWP 98783)]
[New Thread 0x7f92377cc640 (LWP 98784)]
[New Thread 0x7f9236fcb640 (LWP 98785)]
[New Thread 0x7f92367ca640 (LWP 98786)]
[New Thread 0x7f9235fc9640 (LWP 98787)]
[New Thread 0x7f92357c8640 (LWP 98788)]
[New Thread 0x7f9234fc7640 (LWP 98789)]
[New Thread 0x7f92347c6640 (LWP 98790)]
[New Thread 0x7f9233fc5640 (LWP 98791)]
[New Thread 0x7f92337c4640 (LWP 98792)]
[New Thread 0x7f9232fc3640 (LWP 98793)]
[New Thread 0x7f92327c2640 (LWP 98794)]
[New Thread 0x7f9231fc1640 (LWP 98795)]
before call

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
__memset_evex_unaligned_erms () at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:250
250     ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memset_evex_unaligned_erms () at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:250
#1  0x00007f92d32e2090 in Format_floatbits.constprop.0.isra.0 () from /root/miniconda3/envs/py313/lib/python3.13/site-packages/numpy/_core/_multiarray_umath.cpython-313-x86_64-linux-gnu.so
#2  0x00007f92d32e5d42 in Dragon4_Positional () from /root/miniconda3/envs/py313/lib/python3.13/site-packages/numpy/_core/_multiarray_umath.cpython-313-x86_64-linux-gnu.so
#3  0x00007f92d331020a in dragon4_positional () from /root/miniconda3/envs/py313/lib/python3.13/site-packages/numpy/_core/_multiarray_umath.cpython-313-x86_64-linux-gnu.so
#4  0x0000000000563395 in cfunction_vectorcall_FASTCALL_KEYWORDS (func=0x7f92d3b57010, args=0x7f92d4200120, nargsf=<optimized out>, kwnames=0x7f92d199b0d0) at /usr/local/src/conda/python-3.13.0/Include/cpython/methodobject.h:50
#5  0x0000000000537aa1 in _PyObject_VectorcallTstate (kwnames=0x7f92d199b0d0, nargsf=9223372036854775809, args=0x7f92d4200120, callable=0x7f92d3b57010, tstate=0x8eac80 <_PyRuntime+282976>) at /usr/local/src/conda/python-3.13.0/Include/internal/pycore_call.h:168
#6  PyObject_Vectorcall (callable=0x7f92d3b57010, args=0x7f92d4200120, nargsf=9223372036854775809, kwnames=0x7f92d199b0d0) at /usr/local/src/conda/python-3.13.0/Objects/call.c:327
#7  0x000000000055292b in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at /usr/local/src/conda/python-3.13.0/Python/generated_cases.c.h:1502
#8  0x000000000060902e in PyEval_EvalCode (co=<optimized out>, globals=0x7f92d3c4bac0, locals=<optimized out>) at /usr/local/src/conda/python-3.13.0/Python/ceval.c:596
#9  0x000000000062eedd in run_eval_code_obj (tstate=0x8eac80 <_PyRuntime+282976>, co=0x7f92d3de6af0, globals=0x7f92d3c4bac0, locals=0x7f92d3c4bac0) at /usr/local/src/conda/python-3.13.0/Python/pythonrun.c:1323
#10 0x0000000000629d9d in run_mod (mod=<optimized out>, filename=<optimized out>, globals=0x7f92d3c4bac0, locals=0x7f92d3c4bac0, flags=<optimized out>, arena=<optimized out>, interactive_src=0x0, generate_new_source=0) at /usr/local/src/conda/python-3.13.0/Python/pythonrun.c:1408
#11 0x0000000000648890 in pyrun_file (fp=0x20ce2e0, filename=0x7f92d3ca2100, start=<optimized out>, globals=0x7f92d3c4bac0, locals=0x7f92d3c4bac0, closeit=1, flags=0x7fff78fa0d48) at /usr/local/src/conda/python-3.13.0/Python/pythonrun.c:1241
#12 0x00000000006473fb in _PyRun_SimpleFileObject (fp=0x20ce2e0, filename=0x7f92d3ca2100, closeit=1, flags=0x7fff78fa0d48) at /usr/local/src/conda/python-3.13.0/Python/pythonrun.c:490
#13 0x000000000064711b in _PyRun_AnyFileObject (fp=0x20ce2e0, filename=0x7f92d3ca2100, closeit=1, flags=0x7fff78fa0d48) at /usr/local/src/conda/python-3.13.0/Python/pythonrun.c:77
#14 0x0000000000640b67 in pymain_run_file_obj (skip_source_first_line=0, filename=0x7f92d3ca2100, program_name=0x7f92d3cb8080) at /usr/local/src/conda/python-3.13.0/Modules/main.c:409
#15 pymain_run_file (config=0x8bd378 <_PyRuntime+96344>) at /usr/local/src/conda/python-3.13.0/Modules/main.c:428
#16 pymain_run_python (exitcode=0x7fff78fa0d3c) at /usr/local/src/conda/python-3.13.0/Modules/main.c:696
#17 Py_RunMain () at /usr/local/src/conda/python-3.13.0/Modules/main.c:775
#18 0x00000000005f9509 in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at /usr/local/src/conda/python-3.13.0/Modules/main.c:829
#19 0x00007f92d3f0ad90 in __libc_start_call_main (main=main@entry=0x5f9440 <main>, argc=argc@entry=2, argv=argv@entry=0x7fff78fa0f98) at ../sysdeps/nptl/libc_start_call_main.h:58
#20 0x00007f92d3f0ae40 in __libc_start_main_impl (main=0x5f9440 <main>, argc=2, argv=0x7fff78fa0f98, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff78fa0f88) at ../csu/libc-start.c:392
#21 0x00000000005f885d in _start ()
(gdb)
```

### Python and NumPy Versions:

2.2.1
3.13.0 | packaged by Anaconda, Inc. | (main, Oct  7 2024, 21:29:38) [GCC 11.2.0]

### Runtime Environment:

[{'numpy_version': '2.2.1',
  'python': '3.13.0 | packaged by Anaconda, Inc. | (main, Oct  7 2024, '
            '21:29:38) [GCC 11.2.0]',
  'uname': uname_result(system='Linux', node='a475b702ecc0', release='5.4.0-150-generic', version='#167~18.04.1-Ubuntu SMP Wed May 24 00:51:42 UTC 2023', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX'],
                      'not_found': ['AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'SkylakeX',
  'filepath': '/root/miniconda3/envs/py313/lib/python3.13/site-packages/numpy.libs/libscipy_openblas64_-6bb31eeb.so',
  'internal_api': 'openblas',
  'num_threads': 64,
  'prefix': 'libscipy_openblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.28'}]

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by yakovdan**
This PR adds graceful error handling for `np.format_float_positional ` when provided `pad_left` or `pad_right` arguments are too large, leading to an overflow of the string buffer.  

In such cases, a `ValueError` exception is raised. 
Added tests and updated the doc to describe limits on `pad_left` and `pad_right`

fixes #28068

### CODE REVIEW

**Comment by yakovdan** [comment]
Hi, I'm a new contributor to NumPy and I would appreciate any guidance you may have.

**Review by seberg — COMMENTED** [review]
Introducing the error return looks great.  A few comments, mainly:
* It seems a lot easier to just inline the error.  It would be fine to do a single error for everything, although I would probably inline the error anyway with a `goto buffer_too_small:` or so.
* This fixes the error, but a lot of care needs to be taken about overflows unfortunately:
  * Can be fixed with re-arranging some of the length calculations, another way might be to use `int64` for some of these checks.
  * There are probably a lot more errors here: Every time `maxPrintLen` is checked and a special path taken, the result returned is currently wrong in some way and we need to raise an/the error!
    Would you be up to auditing that code as well? 

For simplicity, I really suggest to just raise one single error as noted in one of the comments.  In practice, no-one will ever see this error (if they did we should just support it...), so we can be lazy and worry about raising a particularly helpful error.
(I suppose the "no-one" should ever see this error makes me lean towards a `RuntimeError`.)

File: numpy/_core/src/multiarray/dragon4.c [hunk 1]
```diff
@@ -1803,38 +1810,57 @@ FormatPositional(char *buffer, npy_uint32 bufferSize, BigInt *mantissa,
...
         }
 
         for ( ; count > 0; count--) {
             buffer[pos++] = ' ';
         }
+
+        /* handle overflow condition safely*/
+        if (NPY_TRUE == right_overflow) {
+            buffer[pos] = '\0';
+            return RIGHT_PADDING_OVERFLOW;
```
[the remark this answers is not in the document]
Comment (yakovdan) [reply numpy/_core/src/multiarray/dragon4.c]: Agreed, fixed

File: numpy/_core/arrayprint.py [hunk 2]
```diff
@@ -1232,10 +1232,14 @@ def format_float_positional(x, precision=None, unique=True,
         Whether to show the sign for positive values.
     pad_left : non-negative integer, optional
         Pad the left side of the string with whitespace until at least that
-        many characters are to the left of the decimal point.
+        many characters are to the left of the decimal point. Total length of 
+        string representation of the floating point value cannot exceed 16384, 
+        including pad_right, if any.
```
[the remark this answers is not in the document]
Comment (yakovdan) [reply numpy/_core/arrayprint.py]: I've simplified this part and moved to a separate section below. Is this what you've meant?

File: numpy/_core/src/multiarray/dragon4.c [hunk 3]
```diff
@@ -1803,38 +1810,57 @@ FormatPositional(char *buffer, npy_uint32 bufferSize, BigInt *mantissa,
...
 
         /* in trim_mode DptZeros, if right padding, add a space for the . */
         if (trim_mode == TrimMode_DptZeros && numFractionDigits == 0
                 && pos < maxPrintLen) {
             buffer[pos++] = ' ';
         }
-
+        
+        /* provided digits_rights is too large, can't create the string required*/
         if (pos + count > maxPrintLen) {
```
[the remark this answers is not in the document]
Comment (yakovdan) [reply numpy/_core/src/multiarray/dragon4.c]: I agree. I've fixed this where it's relevant.

File: numpy/_core/src/multiarray/dragon4.c [hunk 4]
```diff
@@ -3041,13 +3067,31 @@ Dragon4_PrintFloat_IBM_double_double(
...
+                break;\
+            case LEFT_PADDING_OVERFLOW:\
+                error_msg = "Left padding exceeds buffer size of 16384";\
+                break;\
+            default:\
+                error_type = PyExc_RuntimeError;\
+                error_msg = "An unexpected error occurred";\
+                break;\
+        }\
+        PyErr_SetString(error_type, error_msg);\
```
[the remark this answers is not in the document]
Comment (yakovdan) [reply numpy/_core/src/multiarray/dragon4.c]: I've reverted the for this function and and switched to raising errors in `FormatPositional`

File: numpy/_core/tests/test_scalarprint.py [hunk 5]
```diff
@@ -305,6 +306,9 @@ def test_dragon4_interface(self):
                          "1.2" if tp != np.float16 else "1.2002")
             assert_equal(fpos(tp('1.'), trim='-'), "1")
             assert_equal(fpos(tp('1.001'), precision=1, trim='-'), "1")
+                        
+            assert_raises_regex(ValueError, "Left padding exceeds buffer size of 16384", fpos, tp('1.047'), precision=2, pad_left=int(1e5))            
+            assert_raises_regex(ValueError, "Right padding exceeds buffer size of 16384", fpos, tp('1.047'), precision=2, pad_right=int(1e5))
```
[the remark this answers is not in the document]
Comment (yakovdan) [reply numpy/_core/tests/test_scalarprint.py]: I've split it into several lines to match the expected line-length

**Comment by yakovdan** [comment]
Thanks @seberg for your review. I've implemented your suggestions. Is there anything else I should add?

File: numpy/_core/src/multiarray/dragon4.c [hunk 6]
```diff
@@ -1658,14 +1662,15 @@ FormatPositional(char *buffer, npy_uint32 bufferSize, BigInt *mantissa,
...
         if (numDigits <= numWholeDigits) {
             npy_int32 count = numWholeDigits - numDigits;
             pos += numDigits;
 
-            /* don't overflow the buffer */
-            if (pos + count > maxPrintLen) {
-                count = maxPrintLen - pos;
+            /* integer part too long for buffer, avoid overflow */
+            if (count > maxPrintLen - pos) {
+                PyErr_SetString(PyExc_RuntimeError, "String buffer overflow");
```
Comment (seberg) [inline numpy/_core/src/multiarray/dragon4.c:1672]: Small suggestion to write something that is easier to understand for Python programmers.  Maybe along: "float formating result too large." (in all places of course)

File: numpy/_core/src/multiarray/dragon4.c [hunk 7]
```diff
@@ -1823,14 +1837,17 @@ FormatPositional(char *buffer, npy_uint32 bufferSize, BigInt *mantissa,
     if (digits_left > numWholeDigits + has_sign) {
         npy_int32 shift = digits_left - (numWholeDigits + has_sign);
         npy_int32 count = pos;
-
+        
+        /* provided digits_left is too large, can't create the string required*/
         if (count + shift > maxPrintLen) {
```
Comment (seberg) [inline numpy/_core/src/multiarray/dragon4.c:1842]: This is similar to above `shift` is unbounded in size, so `count + shift` might overflow.  So rephrase as `count > maPrintLen - shift`.

File: numpy/_core/tests/test_scalarprint.py [hunk 8]
```diff
@@ -305,6 +306,14 @@ def test_dragon4_interface(self):
...
             assert_equal(fpos(tp('1.'), trim='-'), "1")
             assert_equal(fpos(tp('1.001'), precision=1, trim='-'), "1")
+            
+            #gh-28068            
+            assert_raises_regex(RuntimeError, "String buffer overflow", fpos, 
+                                tp('1.047'), unique=False, precision=int(1e5))
+            assert_raises_regex(RuntimeError, "String buffer overflow", fpos, 
+                                tp('1.047'), precision=2, pad_left=int(1e5))
+            assert_raises_regex(RuntimeError, "String buffer overflow", fpos, 
+                                tp('1.047'), precision=2, pad_right=int(1e5))
```
Comment (seberg) [inline numpy/_core/tests/test_scalarprint.py:316]: Thanks for reflowing.  There is one important thing to do, I think.  And that is we should add a test for all of these with the padding set to `np.iinfo("uint32").max` because this hits those `count + size > maxPrintlen` overflows.
(Ideally you add the tests first and confirm that the test crashes NumPy!)

Then I have a few smaller asks/suggestions that would be great:
* I slightly prefer `10**5` rather than `int(1e5)`.
* It would be much clearer to use `with pytest.raises(...):`
* Very long tests aren't nice, it would be much better to split out the test into its own function.  Ideally, you use `@pytest.mark.parametrize` instead of the loop for `[np.float16, np.float32, np.float64]`.

(You should be able to find good examples for these if you search the NumPy code.)

File: numpy/_core/src/multiarray/dragon4.c [hunk 9]
```diff
@@ -1823,14 +1837,17 @@ FormatPositional(char *buffer, npy_uint32 bufferSize, BigInt *mantissa,
     if (digits_left > numWholeDigits + has_sign) {
         npy_int32 shift = digits_left - (numWholeDigits + has_sign);
         npy_int32 count = pos;
-
+        
+        /* provided digits_left is too large, can't create the string required*/
```
Comment (seberg) [inline numpy/_core/src/multiarray/dragon4.c:1841]: I don't think these comments are needed here because with the Python error text, the code reason is just as clear already, IMO.  So I would slightly prefer if you remove them again.

**Review by seberg — COMMENTED** [review]
Thanks!  You missed one `> maxPrintLen` re-order (I think there are no more, but you could check briefly).  We need to fix that and also add tests for huge input values (please do try if it crashes without the last fix!).

Otherwise, a few smaller things, it would be nice if you can refactor the test a bit more at least.

Personally, I might not document the error at all, but don't care.  Either way, no need to change (I might yet decide to remove it via the "suggests" before merging).

Anyway, almost good to go in, thanks a lot!

File: numpy/_core/tests/test_scalarprint.py (hunk 5 above)
[the remark this answers is not in the document]
Comment (charris) [reply numpy/_core/tests/test_scalarprint.py]: @seberg Preferred line length is now <= 88 for Python code. Clang-format is still at 80, but we should probably increase that. Linux is, IIRC, now <= 90 suggested, but not inforced.

[the remark this answers is not in the document]
Comment (seberg) [reply numpy/_core/tests/test_scalarprint.py]: Yeah, the thing is that the linter job should have complained: I guess it just means adding a specific line length somewhere.

File: numpy/_core/src/multiarray/dragon4.c (hunk 9 above)
Comment (yakovdan) [reply numpy/_core/src/multiarray/dragon4.c]: Agreed, removed comment

File: numpy/_core/tests/test_scalarprint.py (hunk 8 above)
Comment (yakovdan) [reply numpy/_core/tests/test_scalarprint.py]: I've implemented all of your suggestions:

1.  I've refactored the test into several smaller tests
2.  I've parametrized on type
3.  I've switched to 10**5
4. I've added `np.iinfo("int32").max` as a test value, `instead of np.iinfo("uint32").max` because the unsigned value is too large to be passed as `npy_int32' and tests detect this and fail

File: numpy/_core/src/multiarray/dragon4.c (hunk 6 above)
Comment (yakovdan) [reply numpy/_core/src/multiarray/dragon4.c]: Done

**Comment by yakovdan** [comment]
After implementing all suggestions, I see that my PR fails one of the tests - `cygwin_build_test`, probably related to the recent changes made to this test. Is there anything required on my part to pass this test?

File: numpy/_core/arrayprint.py [hunk 10]
```diff
@@ -1247,6 +1247,12 @@ def format_float_positional(x, precision=None, unique=True,
     -------
     rep : string
         The string representation of the floating point value
+    
+    Raises
+    ------
+    RuntimeError
+        If the decimal string representation of the floating point scalar is longer
+        than 16384 characters
```
Comment (seberg) [inline numpy/_core/arrayprint.py:1255]:
```suggestion
```
I'll just remove this, thanks.  But I still feel if someone sees it, we should change it and I don't think it is very informative overall.

(If anyone disgrees, happy to follow up.)

File: numpy/_core/src/multiarray/dragon4.c [hunk 11]
```diff
@@ -1614,8 +1614,12 @@ typedef struct Dragon4_Options {
  *    hasUnequalMargins - is the high margin twice as large as the low margin
  *
  * See Dragon4_Options for description of remaining arguments.
+ *  
+ * Required left or right padding may exceed the size of the string buffer.
+ * Error codes for those conditions are defined below
```
Comment (seberg) [inline numpy/_core/src/multiarray/dragon4.c:1619]:
```suggestion
```
Outdated comment.

File: numpy/_core/src/multiarray/dragon4.c [hunk 12]
```diff
@@ -1658,14 +1662,15 @@ FormatPositional(char *buffer, npy_uint32 bufferSize, BigInt *mantissa,
...
-        numWholeDigits = printExponent+1;
+        numWholeDigits = printExponent+1;        
         if (numDigits <= numWholeDigits) {
             npy_int32 count = numWholeDigits - numDigits;
             pos += numDigits;
 
-            /* don't overflow the buffer */
-            if (pos + count > maxPrintLen) {
-                count = maxPrintLen - pos;
+            /* integer part too long for buffer, avoid overflow */
```
Comment (seberg) [inline numpy/_core/src/multiarray/dragon4.c:1670]:
```suggestion
```
As the other one, don't think this is necessary.

File: numpy/_core/src/multiarray/dragon4.c [hunk 13]
```diff
@@ -1767,9 +1772,13 @@ FormatPositional(char *buffer, npy_uint32 bufferSize, BigInt *mantissa,
              pos < maxPrintLen) {
         /* add trailing zeros up to add_digits length */
         /* compute the number of trailing zeros needed */
+        
         npy_int32 count = desiredFractionalDigits - numFractionDigits;
-        if (pos + count > maxPrintLen) {
-            count = maxPrintLen - pos;
+        
+        /* too many trailing zeros required, avoid buffer overflow */
```
Comment (seberg) [inline numpy/_core/src/multiarray/dragon4.c:1778]:
```suggestion
```

File: numpy/_core/tests/test_scalarprint.py [hunk 14]
```diff
@@ -8,7 +8,8 @@
 
 from tempfile import TemporaryFile
 import numpy as np
-from numpy.testing import assert_, assert_equal, assert_raises, IS_MUSL
+from numpy.testing import assert_, assert_equal, assert_raises
+from numpy.testing import assert_raises_regex, IS_MUSL
```
Comment (seberg) [inline numpy/_core/tests/test_scalarprint.py:12]:
```suggestion
from numpy.testing import (
    assert_, assert_equal, assert_raises, assert_raises_regex, IS_MUSL)
```

**Review by seberg — APPROVED** [review]
Thanks @yakovdan.  The Cygwin failure is indeed universal, I think so let's ignore it for now :crossed_fingers:.

Thanks for cleaning the tests up a bit more than necessary even! Definitely a nice improvement.

Mostly think some of the comments are unnecessary, so will just remove them (and that doc note, just because I lean to it, but others may well disagree).

I think this is all done though, will just apply and merge soon or when the tests pass.
