### PR TITLE
ENH: Add support for flat indexing on flat iterator

### LINKED ISSUE #27342: ENH: Allow for a flatiter index on a flatiter object
### Proposed new feature or change:

Currently, indexing a `flatiter` with an array object and vice-versa is permitted.

```python
In [1]: a = np.arange(9).reshape((3, 3))

In [2]: a
Out[2]:
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]: b = np.array([0, 4, 5, 7])

In [4]: b
Out[4]: array([0, 4, 5, 7])

In [5]: a.flat[b]
Out[5]: array([0, 4, 5, 7])

In [6]: a = np.arange(9)

In [7]: a
Out[7]: array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]: a[b.flat]
Out[8]: array([0, 4, 5, 7])
```

However, indexing a `flatiter` with a `flatiter` results in an exception:

```python
In [9]: a.flat[b.flat]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[9], line 1
----> 1 a.flat[b.flat]

IndexError: unsupported iterator index
```

It would be relatively straightforward to allow `flatiter` objects to be index by other `flatiter` objects as well, and it seems that there's no downsides to this. Thoughts?

### PR DESCRIPTION
**Pull request by lysnikolaou**
Closes #27342.

Obviously a bit of discussion might be needed before this gets accepted. I'm opening the PR as a means to show that the implementation only requires a minimal amount of changes.

### CODE REVIEW

**Comment by jorenham** [comment]
For static type-checking purposes it would help if the [typing stubs](https://github.com/numpy/numpy/blob/32abfe27b0e8c17396dff690a477bdfafdabb5ab/numpy/__init__.pyi#L1354-L1372) would also reflect this change

**Comment by seberg** [comment]
I think this is fine, but it should work by converting to an array via normal `asarray()` logic?  I.e. flat defines `__array__()`.

**Comment by jorenham** [comment]
@seberg [The stubs](https://github.com/numpy/numpy/blob/32abfe27b0e8c17396dff690a477bdfafdabb5ab/numpy/__init__.pyi#L1331C1-L1337) require it to be a integer `Sequence` or an integer `ndarray` at the moment (for multi-indexing), i.e. `SupportsArray` isn't included 🤔

**Comment by seberg** [comment]
I am saying that we shouldn't implement `arr.flat` speficically, but if we do that implement any integer array-like just like normal indexing.

File: numpy/_core/src/multiarray/iterators.c [hunk 1]
```diff
@@ -695,6 +695,25 @@ iter_subscript(PyArrayIterObject *self, PyObject *ind)
         obj = ind;
     }
 
+    if (PyArrayIter_Check(obj)) {
+        PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_FROM_O(obj);
+        if (tmp_arr == NULL) {
+            goto fail;
+        }
+
+        if (PyArray_SIZE(tmp_arr) == 0) {
```
Comment (mhvk) [inline numpy/_core/src/multiarray/iterators.c:704]: Would be good to explicitly test this branch. Should it run only if `obj` was not already an `ndarray`?

**Review by mhvk — COMMENTED** [review]
Yes, makes sense to solve this!

**Comment by ngoldbaum** [comment]
I don't have a problem with the extra `PyArrayIter_Check` in the fast path, that should just be a pointer comparison in the common case I think.

**Comment by lysnikolaou** [comment]
> I am saying that we shouldn't implement `arr.flat` speficically, but if we do that implement any integer array-like just like normal indexing.

Does this mean that we should not do the ` if PyArrayIter_Check`, and instead try to do `PyArray_FROM_O` in the common case?

**Comment by seberg** [comment]
Something like that.  The best thing may be to just call the normal indexing preparation code to ensure we do the same thing.  Not sure if that works, but I suspect it will.
It would probably mean we also allow `arr.flat[0,]`, but that seems fine also?

**Comment by seberg** [comment]
No, not a complete adjustment hopefully, you would call: https://github.com/numpy/numpy/blob/cc9f8aae7bdb9fa7d56bc64bdc47f71839715f6d/numpy/_core/src/multiarray/mapping.c#L277 and then need to use the result of that.  But after it, you don't have to deal with conversion anymore.

**Comment by lysnikolaou** [comment]
> No, not a complete adjustment hopefully, you would call:
> 
> https://github.com/numpy/numpy/blob/cc9f8aae7bdb9fa7d56bc64bdc47f71839715f6d/numpy/_core/src/multiarray/mapping.c#L277
> 
> and then need to use the result of that. But after it, you don't have to deal with conversion anymore.

Would we use `prepare_index` with `self->ao` where `self` is the array iter object? That seems wrong since it's more than possible for the array iter object and the underlying array to not have the same dimensionality.

**Comment by seberg** [comment]
Hmmm, True, so it might not actually work without changes.  It may be that all it needs from the array is the number of dimensions, but not sure.

**Comment by lysnikolaou** [comment]
I gave this a try, but I'm too unfamiliar with this part of the codebase so I didn't have much progress. Maybe it'd be okay for this to go in as-is (after I've added some more tests) and open a follow-up issue to rework `iter_subscript` in general?

**Comment by lysnikolaou** [comment]
Friendly ping.

**Comment by seberg** [comment]
Well, I can see that re-using `mapping.c` is too much hassle/not worthwhile.  But I still think that this can be more generic and just cast to array generally (i.e. be merged with the previous branch).
In `prepare_index` that happens here: https://github.com/numpy/numpy/blob/c045306a188f19d7f919512638bd5f02724c9c7e/numpy/_core/src/multiarray/mapping.c#L413

The only reason not to do that, is that it would fix currently broken cases like:
* `arr.flat[[True, True]]` (incorrectly behaves like `arr.flat[[1, 1]]`)
* `arr.flat[[0.0, 1.0]]` (should just fail)

Which means you can convince me that we don't need to merge it, but I think only if we allow doing it in the future (and deprecate/warn about those).
But it is likely just as easy to add the special path afterwards (i.e. if input was a list, warn and force cast).

**Comment by mattip** [comment]
We looked at this in a triage meeting and would like to see this handle more general array types as @seberg says just above. @lysnikolaou what do you think?

**Comment by lysnikolaou** [comment]
Thanks for the update @mattip and sorry for taking so long to reply here. I'll spend some time on this this week to hopefully get it over the finish line.

**Comment by lysnikolaou** [comment]
Hey folks! Sorry for the delay here, but I came back to this today and I just pushed a commit that I think is closer to what we want. One question I have is what we should do with empty non-integer ndarrays. Should this work for example? (FWIW I think it should)

```python3
a = np.array([1, 2, 3]).flat
b = np.empty(1).flat
a[b]
```

**Comment by lysnikolaou** [comment]
Gentle ping on this, in case anyone has some spare cycles for a review.

**Review by seberg — APPROVED** [review]
I'll approve in the grand-scheme of things.  I haven't quite thought about the non-integer madness here.
(In a sense, I am not sure I think the `size == 0` check matters, since we already accept the empty list and that is what I would worry most about.  But it also seems right, so...)

And yeah, merging with the above only works if we try to start fixing the fact that `arr.flat[[False, True, False]]` returns the wrong thing.  Which we absolutely should do of course

**Comment by ngoldbaum** [comment]
Thanks @lysnikolaou! Could you open the followup issue to track further improvements to `flat` when you have a chance?
