### PR TITLE
BUG: fixes segfault in np.place when vals is empty

### LINKED ISSUE #3195: segmentation fault with numpy.place
Hi, 

On my install at least (see below), I append to find an easy way to make a segmentation fault:

```
a = np.zeros(3,dtype=object)
np.place(a,[0,1,1],[])
```

I understand this is not be the right way to set some elements of an object array to an empty list (sadly), but still it should probably not crash python

os: mac10.6
python: 2.7.3   - with ipython 0.13.1
numpy 1.6.2

### PR DESCRIPTION
**Pull request by behzadnouri**
Closes #3195

### CODE REVIEW

File: numpy/core/src/multiarray/compiled_base.c [hunk 1]
```diff
@@ -415,6 +417,22 @@ arr_insert(PyObject *NPY_UNUSED(self), PyObject *args, PyObject *kwdict)
         goto fail;
     }
     numvals = PyArray_SIZE(avals);
+
+    if (!numvals) {
+        /* nothing to insert! fail unless none of mask is true */
+        PyObject *const any = PyArray_Any(amask, NPY_MAXDIMS, NULL);
```
Comment (jaimefrio) [inline numpy/core/src/multiarray/compiled_base.c]: Interesting approach... Since `amask` is a contiguous array of `npy_intp` type, wouldn't it make more sense to traverse it with a loop directly? Something like:

```
npy_intp amask_size = PyArray_SIZE(amask);
npy_intp *data = PyArray_DATA(amask);
int fail = 0;

while (amask_size-- && !fail) {
    fail = (*data++ != 0);
}
```

**Comment by jaimefrio** [comment]
Thanks. LGTM, but would appreciate another dev opinion on the scan of the mask array for non-zero values. There's really nothing wrong with it I guess, but I did find it surprising.

File: numpy/core/src/multiarray/compiled_base.c [hunk 2]
```diff
@@ -415,6 +417,22 @@ arr_insert(PyObject *NPY_UNUSED(self), PyObject *args, PyObject *kwdict)
...
+        const int fail = any == PyArrayScalar_True;
+        Py_DECREF(any);
+
+        if (fail) {
```
Comment (charris) [inline numpy/core/src/multiarray/compiled_base.c]: Labels and variables are different name spaces, but I'd rather not mix them.

File: numpy/core/src/multiarray/compiled_base.c [hunk 3]
```diff
@@ -415,6 +417,22 @@ arr_insert(PyObject *NPY_UNUSED(self), PyObject *args, PyObject *kwdict)
         goto fail;
     }
     numvals = PyArray_SIZE(avals);
+
+    if (!numvals) {
+        /* nothing to insert! fail unless none of mask is true */
+        PyObject *const any = PyArray_Any(amask, NPY_MAXDIMS, NULL);
+        const int fail = any == PyArrayScalar_True;
```
Comment (charris) [inline numpy/core/src/multiarray/compiled_base.c]: Hmm, does `any` need to be checked for `NULL`? At least should use `Py_XDECREF`. Be best to put `(...)` around the logical expression on the right for clarity.

**Comment by behzadnouri** [comment]
> Since amask is a contiguous array of npy_intp type, wouldn't it make more sense to traverse it with a loop directly?

@jaimefrio I changed the code, but that premise does not seem to be true; in particular, does not capture this:
```python
>>> a = np.arange(3)
>>> m = np.zeros(3, dtype='f16')
>>> m[-1] = 1 << 65
>>> m
array([ 0.0,  0.0,  3.6893488e+19], dtype=float128)
>>> np.place(a, m, [])  # this should throw exception!
>>> a
array([0, 1, 2])
>>> np.place(a, m, [100])
>>> a
array([100, 100, 100])
```

in fact there seems to be more issues here; this is on stable release:
```python
>>> np.__version__
'1.9.2'
>>> a
array([0, 1, 2])
>>> m
array([ 0.0,  0.0,  3.6893488e+19], dtype=float128)
>>> np.place(a, m, [100])
>>> a  # buggy! should not touch the first two!
array([100, 100, 100])
```
I guess the same issues would happen on a 32bit machine w/ 64bit types;

**Comment by jaimefrio** [comment]
You are absolutely right, I misread the code, only object arrays get explicitly cast to `npy_intp`, sorry for the noise. I will review it more detail tonight and merge it.

Unrelated to this PR, but is there any reason that the `mask` array doesn't get force-casted to e.g. `npy_bool`, so that everything becomes infinitely easier from there on?

**Comment by jaimefrio** [comment]
In it goes, thanks!
