### PR TITLE
BUG: random: Generator.integers(2**32) always returned 0.

### LINKED ISSUE #16066: default_rng.integers(2**32) always return 0
### Reproducing code example:

I don't understand why `default_rng.integers(2**32)` always return 0, whereas `2**32-1`, `2**32+1`, `2**40`, etc. return random numbers as expected. The result is a `numpy.int64`, so I expected to be able to generate numbers of up `2**64-1`.

```
$ python3.7 -c 'from numpy.random import default_rng; rng=default_rng(); print([rng.integers(2**32) for _ in range(5)])'
[0, 0, 0, 0, 0]
```

It's fine with `2**40`:

```
$ python3.7 -c 'from numpy.random import default_rng; rng=default_rng(); print([rng.integers(2**40) for _ in range(5)])'
[386296210341, 896689857600, 958588149890, 364800985883, 643738305251]
```

### Numpy/Python version information:

I'm running Fedora 31 with python3-3.7.6-2.fc31.x86_64 and python3-numpy-1.17.4-2.fc31.x86_64:

```
vstinner@apu$ python3.7
Python 3.7.6 (default, Jan 30 2020, 09:44:41) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.17.4 3.7.6 (default, Jan 30 2020, 09:44:41) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
When the input to Generator.integers was `2**32`, the value `2**32-1`
was being passed as the `rng` argument to the 32-bit Lemire method,
but that method requires `rng` be strictly less than `2**32-1`.

The fix was to handle `2**32-1` by calling next_uint32 directly.
This also works for the legacy code without changing the stream
of random integers from `randint`.

Closes gh-16066.

### CODE REVIEW

**Comment by seberg** [comment]
Any chance of the same issue for `2**64` (not through `integers` maybe)?

**Comment by seberg** [comment]
@bashtage would you have time to review this to make sure its good?

**Review by seberg — APPROVED** [review]
LGTM, I think fine to put in as is. It seems to me the test should include also drawing a single sample to cover both paths, though?
Otherwise, will leave it in case Kevin wants to have a look, but lets not hesitate to merge to get 1.18.4 out.

**Comment by WarrenWeckesser** [comment]
@seberg wrote
>It seems to me the test should include also drawing a single sample to cover both paths, though?

The test in there now is a crude regression test.  I'll replace that with a repeatability test for `2**32-1`, `2**32` and `2**32+1`.

**Comment by seberg** [comment]
Right, just need to also cover the path where only a single number is drawn then. The approach is good in any case, I was wondering whether it makes sense to put an assert for this into the Lemirs method. We could just do that, although I doubt it helps much with flushing these issues out.

**Comment by WarrenWeckesser** [comment]
It took a few tries, but the Travis-CI tests on the `s390x` platform finally ran successfully.

I've changed the unit test to a set of repeatability tests for the values `2**32-1`, `2**32` and `2**32+1`. For each value, a test is run with `size=7` and `size=None`.

I also added `assert` calls in the C implementations of the Lemire method to check for the invalid value.

File: numpy/random/src/distributions/distributions.c [hunk 1]
```diff
@@ -1450,22 +1469,34 @@ void random_bounded_uint64_fill(bitgen_t *bitgen_state, uint64_t off,
...
+    /*
+     * The 32-bit Lemire method does not handle rng=0xFFFFFFFF, so we'll
+     * call next_uint32 directly.  This also works when use_masked is True,
+     * so we handle both cases here.
+     */
+    if (rng == 0xFFFFFFFFUL) {
       for (i = 0; i < cnt; i++) {
-        out[i] = off + buffered_bounded_masked_uint32(bitgen_state, rng, mask,
-                                                      &bcnt, &buf);
+        out[i] = off + (uint64_t) next_uint32(bitgen_state);
```
Comment (bashtage) [inline numpy/random/src/distributions/distributions.c:1481]: Is this code used in `RandomState`, and does this preserve the stream guarantee?  RS uses only masked, so intercepting before this might have been called could can an issue. 

Would it be safest to added a test in RandomState too with the same end points?

File: numpy/random/src/distributions/distributions.c [hunk 2]
```diff
@@ -1337,6 +1348,14 @@ uint64_t random_bounded_uint64(bitgen_t *bitgen_state, uint64_t off,
     return off;
   } else if (rng <= 0xFFFFFFFFUL) {
     /* Call 32-bit generator if range in 32-bit. */
+    if (rng == 0xFFFFFFFFUL) {
+      /*
+       * The 32-bit Lemire method does not handle rng=0xFFFFFFFF, so we'll
+       * call next_uint32 directly.  This also works when use_masked is True,
+       * so we handle both cases here.
+       */
+      return off + (uint64_t) next_uint32(bitgen_state);
```
Comment (bashtage) [inline numpy/random/src/distributions/distributions.c:1357]: I think the same would apply here as well.

**Review by bashtage — CHANGES_REQUESTED** [review]
LGTM, modulo checking that the stream in `RandomState` is not affected.

File: numpy/random/src/distributions/distributions.c (hunk 1 above)
Comment (WarrenWeckesser) [reply numpy/random/src/distributions/distributions.c:1481]: This is tested by the test that was added in gh-14501: https://github.com/numpy/numpy/blob/20f10762fc20a29923b6943235c2577b8e3ac9f3/numpy/random/tests/test_randomstate_regression.py#L178

File: numpy/random/src/distributions/distributions.c (hunk 2 above)
Comment (WarrenWeckesser) [reply numpy/random/src/distributions/distributions.c:1357]: Yes, this needs a test.  When calling `randint` with scalar values of `low` and `high`, this path is not reached, even when `size` is `None`.    It turns out that the function `random_bounded_uint64` is called by the code that handles broadcasting for `random.randint`.  I'll add a repeatability test for that.

**Review by bashtage — APPROVED** [review]
Extra test was all I noticed.  It has been added.

**Comment by seberg** [comment]
@WarrenWeckesser cool, thanks for the nice tests. Unfortunately due to 32bit longs, the tests are failing on windows (and presumably 32bit linux).

**Comment by WarrenWeckesser** [comment]
@seberg, yup, just noticed that. Looking into it.

**Comment by WarrenWeckesser** [comment]
For the new `randint` test, I used the same `skipif` decorator as in https://github.com/numpy/numpy/pull/14501.  Tests are all green now.

**Comment by seberg** [comment]
Seems good to just skip. Thanks for tracking it down and fixing it quickly Warren!

**Comment by charris** [comment]
AFAIK, RandomState does not use the Lemire method, only the mask method. For repeatability tests, I used fairly long streams and hashed them, then checked the hash. Takes up a lot less room. 

Repeatability is not guaranteed for the Generator methods. At some point we should have correctness checks, maybe as a separate set of tests.

**Comment by WarrenWeckesser** [comment]
@charris wrote
> Repeatability is not guaranteed for the Generator methods.

My understanding is that we have repeatability tests for  the Generator methods so we can detect a change, and create a release note about the change if turns out that the change is unavoidable.

**Comment by WarrenWeckesser** [comment]
>At some point we should have correctness checks, maybe as a separate set of tests.

Agreed.  The issue gh-15911 that you created looks like a good place to discuss this.

**Comment by iyanmv** [comment]
Was this ever merged to 1.17.x? So, correct me if I'm wrong, but the first version of NumPy that can be used without issues [gh-16066](https://github.com/numpy/numpy/issues/16066) and [gh-14774](https://github.com/numpy/numpy/issues/14774) is 1.18.4, right?

**Comment by bashtage** [comment]
The last 17 branch was released before this PR was merged, so it was never in the 17 branch.  It was backported to 18 and in 19.0.

**Comment by iyanmv** [comment]
Okay, so I guess a bump in requirements-min.txt is needed in my case.
