### PR TITLE
ENH: chain additional exception on ufunc method lookup error

### LINKED ISSUE #7961: sqrt raises AttributeError on unexpected input
``` python
>>> numpy.sqrt(9)
3.0
>>> numpy.sqrt(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: sqrt
```

I expected a TypeError or ValueError, and spent quite some time trying to understand why `sqrt` was "missing"...

### PR DESCRIPTION
**Pull request by mattip**
Fixes #7961. Adds an additional exception to the exception chain when calling the object method fails (only for object inner loops).

### CODE REVIEW

File: numpy/core/src/umath/loops.c.src [hunk 1]
```diff
@@ -571,6 +571,22 @@ PyUFunc_O_O_method(char **args, npy_intp *dimensions, npy_intp *steps, void *fun
         PyObject **out = (PyObject **)op1;
         PyObject *ret = PyObject_CallMethod(in1 ? in1 : Py_None, meth, NULL);
         if (ret == NULL) {
+            PyObject *exc, *val, *tb;
+            PyErr_Fetch(&exc, &val, &tb);
+            if (in1 == NULL) {
+                /* When can this ever happen? */
```
Comment (mattip) [inline numpy/core/src/umath/loops.c.src]: This branch is never hit, not clear to me why it is needed, but it reflects the `in1 ? in1 : Py_None` from above

File: numpy/core/src/umath/loops.c.src [hunk 2]
```diff
@@ -571,6 +571,22 @@ PyUFunc_O_O_method(char **args, npy_intp *dimensions, npy_intp *steps, void *fun
         PyObject **out = (PyObject **)op1;
         PyObject *ret = PyObject_CallMethod(in1 ? in1 : Py_None, meth, NULL);
         if (ret == NULL) {
```
Comment (eric-wieser) [inline numpy/core/src/umath/loops.c.src]: I think we need to catch the lookup error but not the call error - what you have right now will chain onto exceptions thrown by the method itself, and claim that the method didn't exist in the first place. So splitting PyObject_CallMethod into a separate lookup and call.

File: numpy/core/src/umath/loops.c.src (hunk 1 above)
Comment (eric-wieser) [reply numpy/core/src/umath/loops.c.src]: I think `NULL` is intended as a just-in-case alias for None, so the message doesn't need to distinguish them.

File: numpy/core/src/umath/loops.c.src (hunk 2 above)
Comment (mattip) [reply numpy/core/src/umath/loops.c.src]: makes sense

**Comment by mattip** [comment]
@eric-wieser's suggestion to split the lookup and call may slightly speed up the call, since it skips some CPython code connected with arg parsing for the function, which in our case is unecessary.

**Review by seberg — APPROVED** [review]
Looks good to me. I think `NoneType` instead of `None` is slightly more correct, but doesn't really matter. Maybe the comment could be `/* although undocumented, accept NULL for Py_None */`?
I saw `pytest.raises` accepts a `message=regular_expression`, but just a note for the future.

Planning to merge (maybe with those comment/doc changes) in a while.

File: numpy/core/src/umath/loops.c.src [hunk 3]
```diff
@@ -566,16 +566,44 @@ NPY_NO_EXPORT void
 PyUFunc_O_O_method(char **args, npy_intp *dimensions, npy_intp *steps, void *func)
 {
     char *meth = (char *)func;
+    PyObject *tup = PyTuple_New(0);
+    if (tup== NULL) {
```
Comment (eric-wieser) [inline numpy/core/src/umath/loops.c.src]: nit: spacing

File: numpy/core/src/umath/loops.c.src [hunk 4]
```diff
@@ -566,16 +566,44 @@ NPY_NO_EXPORT void
...
     UNARY_LOOP {
         PyObject *in1 = *(PyObject **)ip1;
         PyObject **out = (PyObject **)op1;
-        PyObject *ret = PyObject_CallMethod(in1 ? in1 : Py_None, meth, NULL);
+        PyObject *ret, *func;
+        func = PyObject_GetAttrString(in1 ? in1 : Py_None, meth);
+        if (func == NULL || !PyCallable_Check(func)) {
+            PyObject *exc, *val, *tb;
+            PyErr_Fetch(&exc, &val, &tb);
+            if (in1 == NULL) {
```
Comment (eric-wieser) [inline numpy/core/src/umath/loops.c.src]: Could combine the if branches with `PyObject *type = in1 ? Py_TYPE(in1) : Py_TYPE(Py_None);`

Comment (eric-wieser) [reply numpy/core/src/umath/loops.c.src]: I don't see that in your latest commit. Also, I guess `Py_TYPE(in1 ? in1 : Py_None)` would be shorter.

**Review by eric-wieser — APPROVED** [review]

**Comment by eric-wieser** [comment]
Thanks @mattip for addressing this so quickly. I imagine if we look a little further we can close a few more issues with this.
