### PR TITLE
BUG: einsum needs to check overlap on an out argument

### LINKED ISSUE #10080: The `out` arguments in `numpy.einsum` can not work as expected.
I have two piece codes. The first one is:
    
```
    A = np.arange(3*4*3).reshape(3, 4, 3)
    P = np.arange(1, 4)
    A[:, 1:, :] = np.einsum('j, ijk->ijk', P, A[:, 1:, :])
```
and the result `A` is : 
```

    array([[[  0,   1,   2],
            [  6,   8,  10],
            [ 18,  21,  24],
            [ 36,  40,  44]],
    
           [[ 12,  13,  14],
            [ 30,  32,  34],
            [ 54,  57,  60],
            [ 84,  88,  92]],
    
           [[ 24,  25,  26],
            [ 54,  56,  58],
            [ 90,  93,  96],
            [132, 136, 140]]])
```
The second one is:

```
    A = np.arange(3*4*3).reshape(3, 4, 3)
    P = np.arange(1, 4)
    np.einsum('j, ijk->ijk', P, A[:, 1:, :], out=A[:,1:,:])
```
and the result `A` is :

 ```
   array([[[ 0,  1,  2],
            [ 0,  0,  0],
            [ 0,  0,  0],
            [ 0,  0,  0]],
    
           [[12, 13, 14],
            [ 0,  0,  0],
            [ 0,  0,  0],
            [ 0,  0,  0]],
    
           [[24, 25, 26],
            [ 0,  0,  0],
            [ 0,  0,  0],
            [ 0,  0,  0]]])
```

So the result is different. Here I want to use `out` to save memory. Is it a bug in `numpy.einsum`? Or I missed something?

By the way, my `numpy` version is 1.13.3.

### PR DESCRIPTION
**Pull request by mattip**
Fixes #10080. Couldn't figure out why matmul was not calling `PyArray_SetWritebackIfCopy`, then figured out it was this.

### CODE REVIEW

File: numpy/core/src/multiarray/einsum.c.src [hunk 1]
```diff
@@ -2745,19 +2745,20 @@ PyArray_EinsteinSum(char *subscripts, npy_intp nop,
...
+            ((dtype != NULL) ? 0 : NPY_ITER_COMMON_DTYPE)|
+            NPY_ITER_BUFFERED|
+            NPY_ITER_DELAY_BUFALLOC|
+            NPY_ITER_GROWINNER|
+            NPY_ITER_REDUCE_OK|
+            NPY_ITER_REFS_OK|
+            NPY_ITER_ZEROSIZE_OK;
+    if (out != NULL) {
+        iter_flags |= NPY_ITER_COPY_IF_OVERLAP;
+    }
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/einsum.c.src]: Would be clearer to move `((dtype != NULL) ? 0 : NPY_ITER_COMMON_DTYPE)` out of the ternary and into a similar if

**Comment by mattip** [comment]
I think the comment was reflecting the complicated dance done to detect memory overlap and how that might add even more overhead to `einsum`.

**Comment by seberg** [comment]
My comment there was just that I thought there might be fast paths, e.g. for trivial 1D contiguous inputs or so. But luckily those simply do not seem to exist, so this is nice and easy.

File: numpy/core/src/multiarray/einsum.c.src (hunk 1 above)
Comment (mhvk) [reply numpy/core/src/multiarray/einsum.c.src]: I think once that minor change has been made, this is ready to go in.

**Comment by charris** [comment]
@mattip This is the last thing I'm waiting on before branching 1.15. When you get a moment away from releasing 1.14.5 ...

File: numpy/core/src/multiarray/einsum.c.src (hunk 1 above)
Comment (mattip) [reply numpy/core/src/multiarray/einsum.c.src]: changed

**Comment by charris** [comment]
Thanks Matti.
