### PR TITLE
BUG: safer bincount casting

### LINKED ISSUE #28354: BUG: `np.bincount` casting `uint64` to `int64`
### Describe the issue:

When passing a `uint64` array to `np.bincount`, it appears to try to cast the input (or some internally created array) to `int64`. This in turn raises an exception.

### Reproduce the code example:

```python
import numpy as np

a = np.arange(64, dtype=np.uint64)
np.bincount(a)
```

### Error message:

```python
Traceback (most recent call last):
  File "...", line 4, in <module>
    np.bincount(a)
TypeError: Cannot cast array data from dtype('uint64') to dtype('int64') according to the rule 'safe'
```

### Python and NumPy Versions:

```
2.2.2
3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:32:50) [Clang 16.0.6 ]
```

### Runtime Environment:

```python
[{'numpy_version': '2.2.2',
  'python': '3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:32:50) '
            '[Clang 16.0.6 ]',
  'uname': uname_result(system='Darwin', node='jkirkham-mlt', release='23.6.0', version='Darwin Kernel Version 23.6.0: Thu Sep 12 23:35:29 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_ARM64_T6000', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP'],
                      'not_found': ['ASIMDFHM']}},
 {'architecture': 'VORTEX',
  'filepath': '/Users/jkirkham/miniforge/lib/libopenblas.0.dylib',
  'internal_api': 'openblas',
  'num_threads': 10,
  'prefix': 'libopenblas',
  'threading_layer': 'openmp',
  'user_api': 'blas',
  'version': '0.3.28'},
 {'filepath': '/Users/jkirkham/miniforge/lib/libomp.dylib',
  'internal_api': 'openmp',
  'num_threads': 10,
  'prefix': 'libomp',
  'user_api': 'openmp',
  'version': None}]
```

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by tylerjereddy**
* Fixes #28354

* Allow some uint types to be cast a bit more gracefully for `np.bincount()`.

### CODE REVIEW

**Comment by tylerjereddy** [comment]
The CI failures for the new test case I added are real; `npy_intp` gets used in other places in the control flow as well, so patching locally to account for more explicit type casts alone isn't sufficient.

**Comment by tylerjereddy** [comment]
Briefly discussed at triage meeting this morning--Sebastian suggested forcing a cast to `npy_intp`, even for `uint64` input, since indexing does that as well and it isn't really practical to guard against the unreasonably large ints that would wrap to negative values.

File: numpy/_core/src/multiarray/compiled_base.c [hunk 1]
```diff
@@ -177,6 +177,11 @@ arr_bincount(PyObject *NPY_UNUSED(self), PyObject *const *args,
     }
 
     if (lst == NULL) {
+        PyArray_Descr* local_dtype = PyArray_DescrFromType(NPY_INTP);
+        list = PyArray_FromAny(list, local_dtype, 0, 0, NPY_ARRAY_FORCECAST, NULL);
+        if (list == NULL) {
+            goto fail;
+        }
```
Comment (tylerjereddy) [inline numpy/_core/src/multiarray/compiled_base.c:184]: Neither of the two CI failures look related and I checked that the new regression test indeed fails before/passes after the patch.

I suspect Nathan or Sebastian will have to babysit me on the reference counting/setting for `local_dtype` and/or `list` above perhaps. Anyway, happy to make whatever revisions are requested.

For coercing to `NPY_INTP` we also have `coerce_index` in `iterators.c`, but dropping that in seemed to potentially require a bit more work.

Comment (seberg) [reply numpy/_core/src/multiarray/compiled_base.c:184]: Thanks, there are problems here, but the refcounting is fine :).

1. We shouldn't force-cast everything.  We can get away with force-casting (with some pragmatism) only for integer arrays.  So basically, the logic should be: `PyArray_ISINTEGER(list) ? unsafe-cast : safe-cast` (or similar)
2. `PyArray_FromAny` needs the flags to be passed because the later code relies on them.  I.e. we do need the "Coniguous" part here.  That is, it uses `NPY_ARRAY_DEFAULT` (it is just a one line macro for calling `PyArray_FromAny`).
   (Which after a few unpacking, translates to: contiguous, aligned and writeable.)

The current version should crash hard if you do something like `np.bincount(np.arange(10000)[::2])` and it is a bit scary that we have no test for that!

Comment (seberg) [reply numpy/_core/src/multiarray/compiled_base.c:184]: (Ah, I spoke too fast, the refcounting is indeed not fine, as user input `list` is a borrowed reference normally and you are assigning a strong one and you need to `DECREF` it.  But once you refactor things, that problem probably goes away by itself.)

**Comment by tylerjereddy** [comment]
> We shouldn't force-cast everything. 

Ok, I added a guard for that.

> PyArray_FromAny needs the flags to be passed because the later code relies on them..

I couldn't replicate the need for this because what I did originally was two casting operations instead of one--the `Any` cast was added in the control flow to precede the `PyArray_ContiguousFromAny` after it, mostly because I was being lazy about constructing the appropriate requirements/flags. In any case, I've simplified things to restore to a single casting operation now, with custom `flags` depending on input type, which I suspect is closer to what you'd want?

> The current version should crash hard if you do something like np.bincount(np.arange(10000)[::2])

I couldn't find any evidence of a hard crash with that even when I intentionally made things worse with regards to C contiguity, though it may require i.e., `pytest-repeat` and some patience. In any case, I've added that test case as a "doesn't segfault" test just in case.

**Comment by tylerjereddy** [comment]
@seberg I think I've addressed most of the commits in the latest commit (see commit message).

Covering the array-like case does add a bit of code duplication now I suppose. I didn't follow the empty `uint8` worry, but switched to `PyArray_Check` in any case since I believe I was indeed guessing a bit with `Size` (now in two places, though didn't check we really need it in both).

Note that the test for array-like did fail before/pass after the additional coercion shim just added (I also noticed that our error message for passing in a raw array-like class, rather than instance, to `bincount` seems terrible, but that's probably another matter).

I don't think I followed the deprecation-related concern--I thought I was just coercing for integer type inputs and it was the non-integer cases that were deprecated. It is a bit confusing though, because the deprecation message itself seems simple while the commented discussion a bit higher up seems more confusing...

**Review by seberg — APPROVED** [review]
Thanks, duplicating this seems indeed like the easiest path.

**Comment by seberg** [comment]
FWIW, I think this has been around forever and the issue was just a cupy test, I think.  So I don't care much for backporting, but I also don't think there is a problem with that..

**Comment by jakirkham** [comment]
As `2.2.x` looks pretty active, went ahead and created a backport to `2.2.x` with PR: https://github.com/numpy/numpy/pull/28420

It looks like versions older than that are not seeing much activity. So didn't go further. Please let me know whether that would be worthwhile
