### PR TITLE
DEP: Narrow dtype deprecation subclass handling even further

### LINKED ISSUE #31295: BUG: `recarray` doesn't have a proper `_set_dtype` method ?
### Describe the issue:

I'm trying to get rid of newly found deprecation warnings about `dtype` attribute setters in astropy.
There's one occurence in particular where I don't think we can use a view, so the next best thing would be `_set_dtype`, but it looks like it's not properly set on record arrays (it exists but it's a `None`)

```
self = <astropy.io.fits.hdu.table.BinTableHDU object at 0x10bf5f380>
data = rec.array([([ -939524096,           0],), ([ -637534208,  -939524096],),
           ([ -637534208, -1576992768],), ([ ...     ([-1090519040, -1157431040],), ([ -704643072,  2047082752],)],
          dtype=[('COMPRESSED_DATA', '<i4', (2,))])

    def _init_tbdata(self, data):
        columns = self.columns

        print(type(data))
>       data._set_dtype(data.dtype.newbyteorder(">"))
E       TypeError: 'NoneType' object is not callable

astropy/io/fits/hdu/table.py:212: TypeError
```

### Reproduce the code example:

```python
import numpy as np
a = np.array([1], dtype="float64").view(np.rec.recarray)
a._set_dtype("float64")
```

### Error message:

```shell
Traceback (most recent call last):
  File "/Users/clm/dev/gh/neutrinoceros/astropy-compatibility-checks/numpy-dev/_astropy/t.py", line 3, in <module>
    a._set_dtype("float64")
    ~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

### Python and NumPy Versions:

```
2.5.0.dev0+git20260421.388bd75
3.14.3 (main, Feb  4 2026, 01:51:49) [Clang 21.1.4 ]
```

### Runtime Environment:

_No response_

### How does this issue affect you or how did you find it:

_No response_

### PR DESCRIPTION
**Pull request by seberg**
This goes to a bit extreme lengths, but avoids regressions for weird subclasses.
Is it pretty? No, but the worst of it is just a transition and most subclasses shouldn't implement `dtype` attributes hopefully...

So hopefully this is mainly a hack to make astropy not fail on newer NumPy right away and maybe one more project...

Closes gh-31295 (but does not adjust what is reported in the title; `_set_dtype` should be used as a last resort by subclasses mainly; I'll consider it OK to break weirder things here as one can work around it.  What it *does* prevent is a regression: you will get the DeprecationWarning only.)

CC @mhvk I am tempted to go with this, even though it is rather extreme...  Deprecating `.dtype` attribute setting is a big step, so I am willing to go through extreme lengths to make sure we don't stumble over something.

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
@seberg - I pushed some small changes, mostly to make the default case be what we want for the future. I also split out getting both attributes for brevity. I think this looks good and confirm that in astropy it now gives only deprecation warnings.

File: numpy/_core/src/multiarray/convert.c [hunk 1]
```diff
@@ -526,6 +526,126 @@ PyArray_NewCopy(PyArrayObject *obj, NPY_ORDER order)
...
+    PyObject **_set_dtype, PyObject **sub_dtype)
+{
+    if (PyObject_GetOptionalAttr(
+            (PyObject *)subtype, npy_interned_str._set_dtype,
+            _set_dtype) < 0) {
+        return -1;
+    }
+    if (PyObject_GetOptionalAttr(
+            (PyObject *)subtype, npy_interned_str.dtype, sub_dtype) < 0) {
+        return -1;
```
Comment (seberg) [inline numpy/_core/src/multiarray/convert.c:543]:
```suggestion
        Py_XDECREF(_set_dtype);
        return -1;
```
But the refactor itself looks very nice.  Will wait a at least until tomorrow with merging though.

Comment (mhvk) [reply numpy/_core/src/multiarray/convert.c:543]: Oops, yes, now done.

**Comment by seberg** [comment]
Oh, I hand't merged this yet... Time to get this in if nobody else had an opinion.  Hopefully this is the last of it...
