### PR TITLE
BUG: Fix DeprecationWarning in python 3.8

### LINKED ISSUE #14077: Python 3.8b2 and TestDatetime64Timezone, too many warnings.
Running tests with python3.8b2+ on travis fails with two instead of one warning for TestDatetime64Timezone
```
E           AssertionError: 2 warnings found but 1 expected.
E           {message : DeprecationWarning('parsing timezone aware datetimes is deprecated; this will raise an error in the future'), category : 'DeprecationWarning', filename : '/home/travis/build/numpy/numpy/builds/venv/lib/python3.8/site-packages/numpy/core/tests/test_deprecations.py', lineno : 89, line : None}
E           {message : DeprecationWarning('an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.'), category : 'DeprecationWarning', filename : '/home/travis/build/numpy/numpy/builds/venv/lib/python3.8/site-packages/numpy/core/tests/test_deprecations.py', lineno : 89, line : None}
```
I think this problem is on the Python end in the `timedelta` class. I note that the function on our end looks buggy also, assigning a long to an int. The function where this occurs is deprecated, but until it is removed we should fix it.

EDIT: we might just want to mark it `xfail(python > 3.7)` if the problem really is on the Python end, in which case it should be fixed at some point. But let's wait until the first or second 3.8 rc before taking that step.

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

### PR DESCRIPTION
**Pull request by eric-wieser**
Due to implicit conversion of int. Since `total_seconds` returns a python `float`, its easiest to convert to a C float and do the int conversion there

Fixes gh-14077

### CODE REVIEW

File: numpy/core/src/multiarray/datetime.c [hunk 1]
```diff
@@ -2272,7 +2272,10 @@ convert_pydatetime_to_datetimestruct(PyObject *obj, npy_datetimestruct *out,
             if (tmp == NULL) {
                 return -1;
             }
-            seconds_offset = PyInt_AsLong(tmp);
+            /* Rounding here is no worse than the integer division below.
+             * Only whole minute offsets are supported by numpy anyway.
+             */
+            seconds_offset = (int)PyFloat_AsDouble(tmp);
```
Comment (charris) [inline numpy/core/src/multiarray/datetime.c]: OK, timezone offset in seconds should be safe in an `int`.

**Comment by charris** [comment]
Thanks Eric.
