### PR TITLE
BUG: Fix deepcopy regression for empty arrays.

### LINKED ISSUE #8536: np.array([], dtype=object) triggers error when copied with copy.deepcopy()
The following code fails with numpy 1.12.0 (this is the only version we have tested).

~~~~
>>> arr = np.array([], dtype=object)
>>> copy.deepcopy(arr)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2821, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-e314fe8a32a6>", line 1, in <module>
    copy.deepcopy(arr)
  File "/usr/lib/python3.4/copy.py", line 166, in deepcopy
    y = copier(memo)
ValueError: Iteration of zero-sized operands is not enabled
~~~~

Note that this code already works if the dtype was not object but, e.g., int or str.

### PR DESCRIPTION
**Pull request by charris**
Deepcopy of empty arrays was failing because the nditer was constructed
without the NPY_ITER_ZEROSIZE_OK flag.

Closes #8536.

### CODE REVIEW

**Comment by charris** [comment]
@seberg Could you take a look?

File: numpy/core/src/multiarray/methods.c [hunk 1]
```diff
@@ -1441,43 +1441,45 @@ array_deepcopy(PyArrayObject *self, PyObject *args)
...
+                stride = *strideptr;
+                count = *innersizeptr;
+                while (count--) {
+                    _deepcopy_call(data, data, PyArray_DESCR(copied_array),
+                                   deepcopy, visit);
+                    data += stride;
+                }
+            } while (iternext(iter));
+
             NpyIter_Deallocate(iter);
```
Comment (juliantaylor) [inline numpy/core/src/multiarray/methods.c]: this is not deallocated when the size is zero

Comment (seberg) [inline numpy/core/src/multiarray/methods.c]: Seems good to me, but the iterator clean up and the decrefs needs to be outside of the if block. Actually, another question (one for forwarding), can't the deepcopy inner loop fail, i which case we would have to chicken out?

Comment (charris) [inline numpy/core/src/multiarray/methods.c]: There is no error return in the inner loop. The `_deepcopy_call` function is void, although it calls itself recursively so there are `return`s for failures. It is a bit fishy there.

**Comment by charris** [comment]
OK, should be fixed.

File: numpy/core/src/multiarray/methods.c (hunk 1 above)
Comment (charris) [inline numpy/core/src/multiarray/methods.c]: Although I suppose we could check `PyErr_Occurred()`. It should be at least cleared if not handled...

Comment (seberg) [inline numpy/core/src/multiarray/methods.c]: Well, if the inner loop does not shorten out on error, there is not much point. And if it would shorten out, then I would assume it had an error return.... Sounds like a bug, but probably for another day, since this is a regression anyway.

**Comment by seberg** [comment]
Heh, I am confused if it was ever off ;), since there is this one indentation level more then I thought. Seems good to me, I think the check for iternext == NULL may even be unnecessary if you would check for a > 0 return, but that does not matter.

**Comment by seberg** [comment]
Thanks Chuck. Just waiting for the tests to finish (or you can merge it if you beat me to it), the exception discussion belongs elsewhere in any case.

File: numpy/core/src/multiarray/methods.c (hunk 1 above)
Comment (charris) [inline numpy/core/src/multiarray/methods.c]: Looked at it a bit more. If `_deepcopy_call` checked up top for `PyErr_Occurred()` and returned that would take care of the recursion. Whether or not to short circuit the loop after that is another question. Probably the cleanest fix would be to change the return to int and use that as an error indicator, which should be very quick to check.

Comment (seberg) [inline numpy/core/src/multiarray/methods.c]: Yeah, I think the func needs an error indicator return, dunno if you actually need to check PyErr_Occured specifically or not (NULL return checks may do the trick, dunno). And should all work fine, assuming the array as NULLed out before. But I am good with pushing it to a different PR, that bug has probably be there since forever.

**Comment by charris** [comment]
@seberg Interesting. With size > 0 the `NpyIter_GetIterNext` call should not fail. Of course, that doesn't mean it can't, who knows what else could go wrong...

**Comment by seberg** [comment]
I somewhat think the iternext function can only error on some rare things errors that can happen after the main setting up. IIRC I added that at some point, because of allowing to remove axis (the iterator can be "too large" before removal). If that is the case the size would return -1, so one of the two is good enough for error checking. But its safer to do the check in any case....

Anyway, would have to check the code to be sure, so its a bit of a silly trivia more then useful info....

File: numpy/core/src/multiarray/methods.c (hunk 1 above)
Comment (charris) [inline numpy/core/src/multiarray/methods.c]: Since about 2009... I opened an issue for it.
