### PR TITLE
BUG: Fix lexsort axis check

### LINKED ISSUE #15999: np.lexsort silently accepts illegal axis arguments
### Reproducing code example:

```python
import numpy as np
>>> np.lexsort((np.arange(1),), axis=3)
array([0], dtype=int64)

>>> np.lexsort((np.arange(2),), axis=3)
AxisError: axis 3 is out of bounds for array of dimension 1
```

### Numpy/Python version information:
52c9e6f

Introduced in the fix for #14228

### PR DESCRIPTION
**Pull request by vrakesh**
closes #15999

### CODE REVIEW

File: numpy/core/src/multiarray/item_selection.c [hunk 1]
```diff
@@ -1577,6 +1577,10 @@ PyArray_LexSort(PyObject *sort_keys, int axis)
         if (PyArray_SIZE(mps[0]) > 0) {
             *((npy_intp *)(PyArray_DATA(ret))) = 0;
         }
+
+        if (nd > 0 && check_and_adjust_axis(&axis, nd) < 0) {
```
Comment (seberg) [inline numpy/core/src/multiarray/item_selection.c:1581]: Hmmm, supporting `-1` for 0-D arrays seems actually wrong to me. `np.sort` errors here, maybe we should just change it or deprecate it? Unlike sort, `np.lexsort` does not support `axis=None` (ravel behaviour), although to be honest I am not sad about that :).

File: numpy/core/tests/test_regression.py [hunk 2]
```diff
@@ -452,6 +452,10 @@ def test_lexsort_zerolen_custom_strides_2d(self):
         xs.strides = (16, 16)
         assert np.lexsort((xs,), axis=0).shape[0] == 2
 
+    def test_lexsort_invalid_axis(self):
+        assert_raises(np.AxisError, np.lexsort,(np.arange(1),), axis=2)
+        assert_raises(np.AxisError, np.lexsort,(np.array([]),), axis=1)
```
Comment (seberg) [inline numpy/core/tests/test_regression.py:457]: NIT: Missing space. We may want to test the weird 0-D behaviour as well. I am willing to consider it a bug, but maybe we should deprecate it anyway.
Just a side note: `assert_raises` can be used as a context manager if you prefer, doubt it matters here.

**Review by seberg — APPROVED** [review]
LGTM, maybe style nit. The `nd > 0` logic seems wrong, but if we go with deprecation I am happy to see that as a separate issue.

File: numpy/core/src/multiarray/item_selection.c (hunk 1 above)
Comment (vrakesh) [reply numpy/core/src/multiarray/item_selection.c:1581]: Yeah noticed the axis=-1 issue, hence the nd > 0 check. Was not sure, if it was there for a reason, is there a specific reason we don't support ```axis=None``` for lexsort?

Comment (seberg) [reply numpy/core/src/multiarray/item_selection.c:1581]: I don't know if there is a reason. I suppose you would have to check the shapes match first and then ravel all inputs or so, instead of just raveling indiscriminately. So it may just be inconvenient to implement.
Or `sort` supports it mainly for some ancient back-compat reasons...

Comment (eric-wieser) [reply numpy/core/src/multiarray/item_selection.c:1581]: Can we move this all the way up to line 1564?

Comment (eric-wieser) [reply numpy/core/src/multiarray/item_selection.c:1581]: @seberg: We have some places where we allow `0` and `-1` as special-cases for 0d arrays. I don't particularly like it, but I think until we deprecate that we should do the same thing here.

As written, this also allows nonsense like `axis=1000` for 0d arrays, which isn't sane behavior,

File: numpy/core/src/multiarray/item_selection.c [hunk 3]
```diff
@@ -1577,6 +1577,10 @@ PyArray_LexSort(PyObject *sort_keys, int axis)
...
+            goto fail;
+        }
         goto finish;
     }
     if (check_and_adjust_axis(&axis, nd) < 0) {
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/item_selection.c:1586]: If you move this check up to line 1564, you won't need to call `check_and_adjust_axis` from two different places.

**Review by eric-wieser — CHANGES_REQUESTED** [review]
See my comments above.

File: numpy/core/tests/test_regression.py [hunk 4]
```diff
@@ -452,6 +452,10 @@ def test_lexsort_zerolen_custom_strides_2d(self):
         xs.strides = (16, 16)
         assert np.lexsort((xs,), axis=0).shape[0] == 2
 
+    def test_lexsort_invalid_axis(self):
+        assert_raises(np.AxisError, np.lexsort, (np.arange(1),), axis=2)
+        assert_raises(np.AxisError, np.lexsort, (np.array([]),), axis=1)
```
Comment (eric-wieser) [inline numpy/core/tests/test_regression.py:457]:
```suggestion
        assert_raises(np.AxisError, np.lexsort, (np.array(1),), axis=100)  # 0d array
```

File: numpy/core/src/multiarray/item_selection.c (hunk 3 above)
Comment (vrakesh) [reply numpy/core/src/multiarray/item_selection.c:1586]: @eric-wieser 

We cant move it above the loop check for the following reason

```c
check_and_adjust_axis_msg(int *axis, int ndim, PyObject *msg_prefix)
{
    /* Check that index is valid, taking into account negative indices */
    if (NPY_UNLIKELY((*axis < -ndim) || (*axis >= ndim))) {
        /*
         * Load the exception type, if we don't already have it. Unfortunately
         * we don't have access to npy_cache_import here
         */
        static PyObject *AxisError_cls = NULL;
        PyObject *exc;

        if (AxisError_cls == NULL) {
            PyObject *mod = PyImport_ImportModule("numpy.core._exceptions");

            if (mod != NULL) {
                AxisError_cls = PyObject_GetAttrString(mod, "AxisError");
                Py_DECREF(mod);
            }
        }

        /* Invoke the AxisError constructor */
        exc = PyObject_CallFunction(AxisError_cls, "iiO",
                                    *axis, ndim, msg_prefix);
        if (exc == NULL) {
            return -1;
        }
        PyErr_SetObject(AxisError_cls, exc);
        Py_DECREF(exc);

        return -1;
    }
    /* adjust negative indices */
    if (*axis < 0) {
        *axis += ndim;
    }
    return 0;
}
```

For 0d arrays, axis checks will fail

eg:
```python
np.lexsort((np.array(0),))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in lexsort
numpy.AxisError: axis -1 is out of bounds for array of dimension 0
```

Comment (vrakesh) [reply numpy/core/src/multiarray/item_selection.c:1586]: One thing we could do is not call, axis check when no axis is mentioned i.e axis = -1

```c
    if (axis != -1 && check_and_adjust_axis(&axis, nd) < 0) {
        goto fail;
    }
```

I am however not sure, if it is something we can do. Trying to figure the implications

Comment (eric-wieser) [reply numpy/core/src/multiarray/item_selection.c:1586]: We basically already do that elsewhere:

https://github.com/numpy/numpy/blob/8dfaa4a5e0ca329e16a853d5982ea5af5d044b47/numpy/core/src/multiarray/conversion_utils.c#L289-L299

Comment (eric-wieser) [reply numpy/core/src/multiarray/item_selection.c:1586]: So probably soemthing like:
```C
         /* 
          * Special case letting axis={-1,0} slip through for scalars, 
          * for backwards compatibility reasons. 
          */ 
         if (ndim == 0 && (axis == 0 || axis == -1)) { 
            /* TODO: can we deprecate this? */
         }
         else if (check_and_adjust_axis(&axis, nd) < 0) {
             goto fail;
         }
```

Comment (vrakesh) [reply numpy/core/src/multiarray/item_selection.c]: Thanks for pointing it out will update changes

**Review by eric-wieser — APPROVED** [review]
Looks good now, thanks

**Comment by seberg** [comment]
Thanks @vrakesh and Eric.
