### PR TITLE
ENH: fixing generic error messages to be more specific in multiarray/descriptor.c

### LINKED ISSUE #15316: Replace calls to `_report_generic_error` with a more useful error message.
Right now, many failures of `np.dtype(obj)` go to this path:

https://github.com/numpy/numpy/blob/80fc0f5ac661740b1267a726a37b5bc570903cb4/numpy/core/src/multiarray/descriptor.c#L42-L49

For example

https://github.com/numpy/numpy/blob/80fc0f5ac661740b1267a726a37b5bc570903cb4/numpy/core/src/multiarray/descriptor.c#L443-L446

We should replace some or all of these calls in this file with more helpful error messages, such as in the above case:
```diff
-_report_generic_error();
+PyErr_Format(PyExc_TypeError, "Field elements must be 2-tuples, got %R", item);
```

If we replace all of them, then we should remove the `_report_generic_error` function entirely

### PR DESCRIPTION
**Pull request by ericmariasis**
Closes #15316

### CODE REVIEW

**Comment by eric-wieser** [comment]
If there are no callers left, can you delete the definition of _report_generic_error?

File: numpy/core/src/multiarray/descriptor.c [hunk 1]
```diff
@@ -251,7 +251,7 @@ static PyArray_Descr *
 _convert_from_tuple(PyObject *obj, int align)
 {
     if (PyTuple_GET_SIZE(obj) != 2) {
-        _report_generic_error();
+        PyErr_Format(PyExc_TypeError, "PyTuple must have size 2, got [%d]", PyTuple_GET_SIZE(obj));
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c]: Best to use the python names (tuple, object) rather than the CPython names (PyTuple, PyObject). Same throughout.

File: numpy/core/src/multiarray/descriptor.c [hunk 2]
```diff
@@ -451,18 +451,18 @@ _convert_from_array_descr(PyObject *obj, int align)
         }
         else if (PyTuple_Check(name)) {
             if (PyTuple_GET_SIZE(name) != 2) {
-                _report_generic_error();
+                PyErr_Format(PyExc_TypeError, "PyObject within tuple needs to be a 2-tuple, has [%d] elements", PyTuple_GET_SIZE(name));
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c]: Perhaps _"If a tuple, the first element of a field tuple must have two elements"_, or some similar message that indicates that non-tuples can also be ok.

File: numpy/core/src/multiarray/descriptor.c [hunk 3]
```diff
@@ -451,18 +451,18 @@ _convert_from_array_descr(PyObject *obj, int align)
...
             name = PyTuple_GET_ITEM(name, 1);
             if (!PyBaseString_Check(name)) {
-                _report_generic_error();
+                PyErr_SetString(PyExc_TypeError, "Second element of PyObject within tuple needs to be a base string");
                 goto fail;
             }
         }
         else {
-            _report_generic_error();
+            PyErr_SetString(PyExc_TypeError, "First element of field tuple is neither a tuple nor base string");
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c]:
```suggestion
            PyErr_SetString(PyExc_TypeError, "First element of field tuple is neither a tuple nor str");
```

File: numpy/core/src/multiarray/descriptor.c [hunk 4]
```diff
@@ -483,7 +483,7 @@ _convert_from_array_descr(PyObject *obj, int align)
                 Py_INCREF(name);
             }
             else {
-                _report_generic_error();
+                PyErr_SetString(PyExc_TypeError, "Field names must be non-empty Unicode strings");
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c]:
```suggestion
                PyErr_SetString(PyExc_TypeError, "Field names must be non-empty strings");
```

File: numpy/core/src/multiarray/descriptor.c [hunk 5]
```diff
@@ -727,7 +727,7 @@ _convert_from_commastring(PyObject *obj, int align)
     PyObject *_numpy_internal;
 
     if (!PyUnicode_Check(obj)) {
-        _report_generic_error();
+        PyErr_SetString(PyExc_TypeError, "Object needs to be a Unicode object");
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c]:
```suggestion
        PyErr_SetString(PyExc_TypeError, "Object needs to be a str");
```

File: numpy/core/src/multiarray/descriptor.c (hunk 2 above)
Comment (ericmariasis) [reply numpy/core/src/multiarray/descriptor.c]: Thanks for the suggestion, I will incorporate in my next commit.

File: numpy/core/src/multiarray/descriptor.c (hunk 1 above)
Comment (ericmariasis) [reply numpy/core/src/multiarray/descriptor.c]: Agreed, will change in applicable places.

**Comment by ericmariasis** [comment]
> If there are no callers left, can you delete the definition of _report_generic_error?

I was so close but unfortunately there was one location that I couldn't think of a good replacement for. It was basically if the data type could not be recognized in general.

**Comment by eric-wieser** [comment]
If it's one location, you could just inline the function

**Comment by ericmariasis** [comment]
> If it's one location, you could just inline the function

Done.

File: numpy/core/src/multiarray/descriptor.c [hunk 6]
```diff
@@ -251,7 +242,7 @@ static PyArray_Descr *
 _convert_from_tuple(PyObject *obj, int align)
 {
     if (PyTuple_GET_SIZE(obj) != 2) {
-        _report_generic_error();
+        PyErr_Format(PyExc_TypeError, "Tuple must have size 2, but has size [%d]", PyTuple_GET_SIZE(obj));
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c]:
```suggestion
        PyErr_Format(PyExc_TypeError, "Tuple must have size 2, but has size %d", PyTuple_GET_SIZE(obj));
```

File: numpy/core/src/multiarray/descriptor.c [hunk 7]
```diff
@@ -441,7 +432,7 @@ _convert_from_array_descr(PyObject *obj, int align)
     for (int i = 0; i < n; i++) {
         PyObject *item = PyList_GET_ITEM(obj, i);
         if (!PyTuple_Check(item) || (PyTuple_GET_SIZE(item) < 2)) {
-            _report_generic_error();
+            PyErr_Format(PyExc_TypeError, "Field elements must be 2-tuples, got %R", item);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c]:
```suggestion
            PyErr_Format(PyExc_TypeError, "Field elements must be 2- or 3-tuples, got %R", item);
```

File: numpy/core/src/multiarray/descriptor.c [hunk 8]
```diff
@@ -451,18 +442,20 @@ _convert_from_array_descr(PyObject *obj, int align)
         }
         else if (PyTuple_Check(name)) {
             if (PyTuple_GET_SIZE(name) != 2) {
-                _report_generic_error();
+                PyErr_Format(PyExc_TypeError, 
+				"If a tuple, the first element of a field tuple must have two elements, has [%d] elements",
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c]:
```suggestion
				"If a tuple, the first element of a field tuple must have two elements, not %d",
```

File: numpy/core/src/multiarray/descriptor.c [hunk 9]
```diff
@@ -727,7 +720,7 @@ _convert_from_commastring(PyObject *obj, int align)
     PyObject *_numpy_internal;
 
     if (!PyUnicode_Check(obj)) {
-        _report_generic_error();
+        PyErr_SetString(PyExc_TypeError, "Object needs to be a str");
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c]: This one is unreachable, so perhaps just change this to an `assert`

File: numpy/core/src/multiarray/descriptor.c [hunk 10]
```diff
@@ -1484,7 +1477,7 @@ _convert_from_any(PyObject *obj, int align)
         return _convert_from_dict(obj, align);
     }
     else if (PyArray_Check(obj)) {
-        _report_generic_error();
+        PyErr_SetString(PyExc_TypeError, "Object is an unrecognized array type");
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c]:
```suggestion
        PyErr_SetString(PyExc_TypeError, "Cannot construct a dtype from an array");
```

File: numpy/core/src/multiarray/descriptor.c [hunk 11]
```diff
@@ -1503,7 +1496,7 @@ _convert_from_any(PyObject *obj, int align)
             return ret;
         }
         Py_DECREF(ret);
-        _report_generic_error();
+        PyErr_SetString(PyExc_TypeError, "data type not understood");
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c]: Perhaps clearer as
```suggestion
        PyErr_Format(PyExc_TypeError, "Cannot interpret %R as a data type");
```

File: numpy/core/src/multiarray/descriptor.c [hunk 12]
```diff
@@ -483,7 +476,7 @@ _convert_from_array_descr(PyObject *obj, int align)
                 Py_INCREF(name);
             }
             else {
-                _report_generic_error();
+                PyErr_SetString(PyExc_TypeError, "Field names must be non-empty strings");
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c]:
```suggestion
                PyErr_SetString(PyExc_TypeError, "Field titles must be non-empty strings");
```

File: numpy/core/src/multiarray/descriptor.c [hunk 13]
```diff
@@ -451,18 +442,20 @@ _convert_from_array_descr(PyObject *obj, int align)
...
+                PyErr_Format(PyExc_TypeError, 
+				"If a tuple, the first element of a field tuple must have two elements, not %d",
+			       	PyTuple_GET_SIZE(name));
                 goto fail;
             }
             title = PyTuple_GET_ITEM(name, 0);
             name = PyTuple_GET_ITEM(name, 1);
             if (!PyBaseString_Check(name)) {
-                _report_generic_error();
+                PyErr_SetString(PyExc_TypeError, "Second element of object within tuple needs to be a base string");
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c]:
```suggestion
                PyErr_SetString(PyExc_TypeError, "Field name must be a str");
```

File: numpy/core/src/multiarray/descriptor.c (hunk 9 above)
Comment (ericmariasis) [reply numpy/core/src/multiarray/descriptor.c]: Done.

File: numpy/core/src/multiarray/descriptor.c [hunk 14]
```diff
@@ -1503,7 +1492,7 @@ _convert_from_any(PyObject *obj, int align)
             return ret;
         }
         Py_DECREF(ret);
-        _report_generic_error();
+        PyErr_Format(PyExc_TypeError, "Cannot interpret %R as a data type");
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/descriptor.c]:
```suggestion
        PyErr_Format(PyExc_TypeError, "Cannot interpret %R as a data type", obj);
```

**Review by eric-wieser — APPROVED** [review]
Looks good. Probably doesn't need a test, but it would be great if you could post some example error output in a comment here.

**Comment by ericmariasis** [comment]
> Closes #15316

Example error output:

>>> dtype2 = np.dtype([2,3,4])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: data type not understood

>>> dtype3 = np.dtype((float,))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: data type not understood

-- The above is now updated to give better details of the error.

**Review by seberg — COMMENTED** [review]
@ericmariasis can you paste the error that happens with this patch applied? Thought ticks around '%R' may make sense. I am sure you can always massage the text, but its a nice improvement.

Some of the lines are a bit long, we often use:
```
PyErr_Format(PyExc_TypeError,
        "8 spaces indentation before the message", )
```
style. It does not have to be that style, below 80 characters would be nice though (at least not much over).

File: numpy/core/src/multiarray/descriptor.c [hunk 15]
```diff
@@ -251,7 +242,7 @@ static PyArray_Descr *
 _convert_from_tuple(PyObject *obj, int align)
 {
     if (PyTuple_GET_SIZE(obj) != 2) {
-        _report_generic_error();
+        PyErr_Format(PyExc_TypeError, "Tuple must have size 2, but has size %d", PyTuple_GET_SIZE(obj));
```
[the remark this answers is not in the document]
Comment (seberg) [reply numpy/core/src/multiarray/descriptor.c]: I assume we should have tests exercising the code paths (I agree there is no need to test the exact message).
If you are up into diving into the test a bit. Making sure we have tests for these errors at all could be nice, but not necessary.

[the remark this answers is not in the document]
Comment (ericmariasis) [reply numpy/core/src/multiarray/descriptor.c]: Changing the identation in upcoming commit.

File: numpy/core/src/multiarray/descriptor.c [hunk 16]
```diff
@@ -451,18 +446,23 @@ _convert_from_array_descr(PyObject *obj, int align)
         }
         else if (PyTuple_Check(name)) {
             if (PyTuple_GET_SIZE(name) != 2) {
-                _report_generic_error();
+                PyErr_Format(PyExc_TypeError, 
+				"If a tuple, the first element of a field tuple must have \
+				two elements, not %d",
```
Comment (seberg) [inline numpy/core/src/multiarray/descriptor.c]: Thanks! Sorry for not pointing it out, but this %d is also incorrect. You cannot break the strings like this (if you check the initial whitespace is not gone). The solution is to use string concatenation if you wish to break the line:
```
PyErr_Format(Type,
        "This is a very                                                 long string "
        "which is continued on the next line."
```
One thing to note is the trailing space on the previous line. Also above, I like exactly 8 spaces indentation. You can also align with the `(`, but 8 spaces just gives you much more space to write the message.

Comment (ericmariasis) [reply numpy/core/src/multiarray/descriptor.c]: Good point, thanks for noticing that about the spacing. I just made a new commit updating it. Does that look better?

Comment (seberg) [reply numpy/core/src/multiarray/descriptor.c]: Yeah, thanks, looks nice. You forgot one though :).

Comment (ericmariasis) [reply numpy/core/src/multiarray/descriptor.c]: Found it thanks. I think the rest of the backslash areas are code I didn't modify.

File: numpy/core/src/multiarray/descriptor.c [hunk 17]
```diff
@@ -451,18 +446,23 @@ _convert_from_array_descr(PyObject *obj, int align)
...
             if (!PyBaseString_Check(name)) {
-                _report_generic_error();
+                PyErr_SetString(PyExc_TypeError, "Field name must be a str");
                 goto fail;
             }
         }
         else {
-            _report_generic_error();
+            PyErr_SetString(PyExc_TypeError, 
+			            "First element of field tuple is "
```
Comment (seberg) [inline numpy/core/src/multiarray/descriptor.c]: Could be one line if you fix indentation.

File: numpy/core/src/multiarray/descriptor.c [hunk 18]
```diff
@@ -451,18 +446,23 @@ _convert_from_array_descr(PyObject *obj, int align)
         }
         else if (PyTuple_Check(name)) {
             if (PyTuple_GET_SIZE(name) != 2) {
-                _report_generic_error();
+                PyErr_Format(PyExc_TypeError, 
+				"If a tuple, the first element of a field tuple must have "
+				"two elements, not %zd",
+			       	PyTuple_GET_SIZE(name));
```
Comment (seberg) [inline numpy/core/src/multiarray/descriptor.c]: Could put this on the previous line (and indentation is a bit funny).

Comment (seberg) [reply numpy/core/src/multiarray/descriptor.c]: (Same applies in the above cases)

**Review by seberg — APPROVED** [review]
Thanks, I am good with putting it in now. If someone wants to massage the error messages also great, but most of them are rare, and they read fine to me.
Two more style nitpicks if you are still motivated.

**Comment by ericmariasis** [comment]
Now that all reviewers have approved, is there anything on my part I can do to help this get merged into master?

**Comment by mattip** [comment]
Thanks @ericmariasis
