### PR TITLE
BUG: Fix new DTypes and new string promotion when signature is involved

### LINKED ISSUE #26735: BUG: `new DType in signature not yet supported` with `np.strings.add`
### Describe the issue:

The new `np.strings.add` accepts a `dtype` argument, which works when using `np.str_`, but fails with the new `StringDType`. The error message seems to indicate this is not just "not implemented", but shouldn't happen.

### Reproduce the code example:

```python
import numpy as np

np.strings.add(["num", "doc"], ["py", "umentation"], dtype=np.dtypes.StringDType)
```

### Error message:

```shell
Traceback (most recent call last):
  File "[...]/x.py", line 3, in <module>
    np.strings.add(["num", "doc"], ["py", "umentation"], dtype=np.dtypes.StringDType)
RuntimeError: Internal NumPy error: new DType in signature not yet supported. (This should be unreachable code!)
```

### Python and NumPy Versions:

2.0.0
3.12.3 (main, May 14 2024, 21:44:25) [Clang 15.0.0 (clang-1500.3.9.4)]

### Runtime Environment:

[{'numpy_version': '2.0.0',
  'python': '3.12.3 (main, May 14 2024, 21:44:25) [Clang 15.0.0 '
            '(clang-1500.3.9.4)]',
  'uname': uname_result(system='Darwin', node='jrh', release='23.5.0', version='Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP'],
                      'not_found': ['ASIMDFHM']}}]

### Context for the issue:

I was just experimenting with the new types and expected passing `StringDType` to all functions accepting a `dtype` would work, including `add` where I'd like the arbitrary length strings in the output.

### PR DESCRIPTION
**Pull request by seberg**
Unfortunately, did a bit of cleanup to make this work, so this needs a bit of a careful look.

I.e. the first commit moves the "allow legacy promotion" logic to later, where the signature is more readily available.  That shouldn't change anything else (the only reason it is used earlier is to decide if checking for "should use scalar" makes sense, but that code handles unknown dtypes just fine).

It then fixes the string add promoter to close the issue.

Closes gh-26735

### CODE REVIEW

File: numpy/_core/src/umath/stringdtype_ufuncs.cpp [hunk 1]
```diff
@@ -1028,6 +1028,25 @@ all_strings_promoter(PyObject *NPY_UNUSED(ufunc),
...
+        new_op_dtypes[0] = NPY_DT_NewRef(&PyArray_UnicodeDType);
+        new_op_dtypes[1] = NPY_DT_NewRef(&PyArray_UnicodeDType);
+        new_op_dtypes[2] = NPY_DT_NewRef(&PyArray_UnicodeDType);
+        return 0;
+    }
+    if (signature[0] == &PyArray_UnicodeDType &&
+            signature[1] == &PyArray_UnicodeDType &&
+            signature[2] == &PyArray_UnicodeDType) {
+        /* Unicode forced, but didn't override a string input: invalid */
+        return -1;
```
Comment (seberg) [inline numpy/_core/src/umath/stringdtype_ufuncs.cpp:1048]: This part makes me wonder if I should just check it after the promoter is done and invalidate the result if this is violated.  But it is OK here also.

Comment (ngoldbaum) [reply numpy/_core/src/umath/stringdtype_ufuncs.cpp:1048]: I agree it would be better to enforce that there, if only because IMO DType authors shouldn't have to worry about that case or add code to account for it to write a correct DType.

File: numpy/_core/src/umath/stringdtype_ufuncs.cpp [hunk 2]
```diff
@@ -2532,6 +2551,17 @@ init_stringdtype_ufuncs(PyObject *umath)
...
+    PyArray_DTypeMeta *out_strings_promoter_dtypes[] = {
+        &PyArray_UnicodeDType,
+        &PyArray_UnicodeDType,
+        &PyArray_StringDType,
+    };
+
+    if (add_promoter(umath, "add", out_strings_promoter_dtypes, 3,
+                     all_strings_promoter) < 0) {
+        return -1;
+    }
```
Comment (ngoldbaum) [inline numpy/_core/src/umath/stringdtype_ufuncs.cpp:2563]: Good catch!

File: numpy/_core/tests/test_stringdtype.py [hunk 3]
```diff
@@ -828,6 +828,31 @@ def test_add_promoter(string_list):
         assert_array_equal(op + arr, lresult)
         assert_array_equal(arr + op, rresult)
 
+    # The promoter should be able to handle things if users pass `dtype=`
+    res = np.add("hello", string_list, dtype=StringDType)
```
Comment (ngoldbaum) [inline numpy/_core/tests/test_stringdtype.py:832]: Probably not worth using the `dtype` fixture for this since `na_object` and `coerce` doesn't matter, but maybe worth making `dtype` a parameter of the test that can either by `StringDType` or `StringDType()`. I could also see perhaps defining a `class_or_instance` fixture and using that in a few other places in this file where we just test with `StringDType()` or `"T"`.

File: numpy/_core/src/umath/stringdtype_ufuncs.cpp [hunk 4]
```diff
@@ -1028,6 +1028,25 @@ all_strings_promoter(PyObject *NPY_UNUSED(ufunc),
...
+         * output DType/signature.
+         */
+        new_op_dtypes[0] = NPY_DT_NewRef(&PyArray_UnicodeDType);
+        new_op_dtypes[1] = NPY_DT_NewRef(&PyArray_UnicodeDType);
+        new_op_dtypes[2] = NPY_DT_NewRef(&PyArray_UnicodeDType);
+        return 0;
+    }
+    if (signature[0] == &PyArray_UnicodeDType &&
+            signature[1] == &PyArray_UnicodeDType &&
+            signature[2] == &PyArray_UnicodeDType) {
```
Comment (ngoldbaum) [inline numpy/_core/src/umath/stringdtype_ufuncs.cpp:1046]:
```suggestion
    if ((signature[0] == &PyArray_UnicodeDType &&
         signature[1] == &PyArray_UnicodeDType &&
         signature[2] == &PyArray_UnicodeDType)) {
```

**Review by ngoldbaum — COMMENTED** [review]
I looked at the refactor for `allow_legacy_promotion` for a while. I like the simplification of only needing to worry about that in `dispatching.c` and removing it from `ufunc_object.c` and I think that it should be the same behavior-wise for all callers, so I think the cleanup is OK and probably safe to backport.

File: numpy/_core/tests/test_stringdtype.py (hunk 3 above)
Comment (seberg) [reply numpy/_core/tests/test_stringdtype.py:832]: That doesn't work.  Signatures are DType classes.  It should work at least for `"T"`, but otherwise need to look into logic to say "this is OK".
I am not sure it should be, but it is a different issue in either case.

File: numpy/_core/src/umath/stringdtype_ufuncs.cpp [hunk 5]
```diff
@@ -1028,6 +1028,25 @@ all_strings_promoter(PyObject *NPY_UNUSED(ufunc),
                      PyArray_DTypeMeta *const signature[],
                      PyArray_DTypeMeta *new_op_dtypes[])
 {
+    if (op_dtypes[0] != &PyArray_StringDType &&
+            op_dtypes[1] != &PyArray_StringDType &&
+            op_dtypes[2] != &PyArray_StringDType) {
```
[the remark this answers is not in the document]
Comment (seberg) [reply numpy/_core/src/umath/stringdtype_ufuncs.cpp:1033]: Let's go with it, not sure I like it much more, but it does align.  We should just enforce a style automatically at some point... or maybe over-indent but keep the first line empty :).  I don't know...

File: numpy/_core/tests/test_stringdtype.py (hunk 3 above)
Comment (seberg) [reply numpy/_core/tests/test_stringdtype.py:832]: Yeah, not hat happens much earlier, I explicitly allowed the singleton instancs of legacy dtypes (or maybe all singleton instances, not sure), because otherwise things would be tricky.

But, we have the "give me the DType" now also, which maybe (not sure!) makes `T` work.  It _should_ make `T` work in either case, though.

File: numpy/_core/src/umath/dispatching.c [hunk 6]
```diff
@@ -964,11 +965,20 @@ promote_and_get_ufuncimpl(PyUFuncObject *ufunc,
...
             Py_CLEAR(op_dtypes[i]);
         }
+        /*
+         * If the op_dtype ends up being a non-legacy one, then we cannot use
+         * legacy promotion (unless this is a python scalar).
+         */
+        if (op_dtypes[i] != NULL && !NPY_DT_is_legacy(op_dtypes[i]) && (
+                signature[i] != NULL ||  // signature cannot be a pyscalar
+                !(PyArray_FLAGS(ops[i]) & NPY_ARRAY_WAS_PYTHON_LITERAL))) {
+            allow_legacy_promotion = NPY_FALSE;
```
Comment (mhvk) [inline numpy/_core/src/umath/dispatching.c:975]: Might it be better to call this variable "legacy_promotion_is_possible"? (no big deal, obviously, but since it is now an internal variable, might as well make it as clear as possible)

File: numpy/_core/src/umath/ufunc_object.c [hunk 7]
```diff
@@ -5809,19 +5801,17 @@ ufunc_at(PyUFuncObject *ufunc, PyObject *args)
...
             Py_INCREF(operand_DTypes[1]);
-            allow_legacy_promotion &= NPY_DT_is_legacy(operand_DTypes[1]);
             tmp_operands[2] = tmp_operands[0];
             operand_DTypes[2] = operand_DTypes[0];
             Py_INCREF(operand_DTypes[2]);
 
-            if (allow_legacy_promotion && ((PyArray_NDIM(op1_array) == 0)
-                                           != (PyArray_NDIM(op2_array) == 0))) {
+            if ((PyArray_NDIM(op1_array) == 0)
+                        != (PyArray_NDIM(op2_array) == 0)) {
```
Comment (mhvk) [inline numpy/_core/src/umath/ufunc_object.c:5814]: fix indentation while you are at it? Both of this line and the actual clause.

File: numpy/_core/src/umath/stringdtype_ufuncs.cpp [hunk 8]
```diff
@@ -1028,6 +1028,25 @@ all_strings_promoter(PyObject *NPY_UNUSED(ufunc),
...
+        /*
+         * This promoter was triggered with only unicode arguments, so use
```
Comment (mhvk) [inline numpy/_core/src/umath/stringdtype_ufuncs.cpp:1035]: This seems confusing - should `StringDType` really decide the result for something that does not include itself? Shouldn't that be up to `UnicodeDType`? What happens if we return -1 here?

File: numpy/_core/src/umath/stringdtype_ufuncs.cpp (hunk 1 above)
Comment (mhvk) [reply numpy/_core/src/umath/stringdtype_ufuncs.cpp:1048]: Indeed, it seems strange one would even get here if the signature is already clear that `StringDType` should not be involved.

**Review by mhvk — COMMENTED** [review]
I agree the refactoring is an improvement regardless! But I do wonder about the changes to the promotor - it doesn't feel right for `StringDType` to decide on something that will not in the end lead to a `StringDType` result (but perhaps I am confused...)

File: numpy/_core/src/umath/stringdtype_ufuncs.cpp (hunk 8 above)
Comment (seberg) [reply numpy/_core/src/umath/stringdtype_ufuncs.cpp:1035]: Things would just fail the operation, I am very sure I added it for a reason.  The problem is that you would have to decide that `UU->U` is clearly better than `UU->T`.  But there is nothing to decide that by, so the machinery prefers the promoter, since the promoter has the ability to resolve which one to actual use (also go to `UU->U`).

The other thing you might not like is that it matches at all, but that would need one of two new features (which is fine):
* Always call promoters right away even if there may be much better matches and give them the ability to say "don't know" (i.e. a -1 return might be that without an error set).
* Allow some heuristic for it like, "must contain this DType" as an additional dtype.
* Allow "matching" via a second function.

The other solution for the particular case is that if there wasn't legacy promotion involved, I would like a default promoter that ensures that `ufunc(..., dtype=X)` will search for `ufunc(..., signature=(X, X, X))` as well if there is otherwise no match.  That would do the right thing here.

File: numpy/_core/src/multiarray/abstractdtypes.h [hunk 9]
```diff
@@ -47,6 +47,8 @@ npy_mark_tmp_array_if_pyscalar(
      * a custom DType registered, and then we should use that.
      * Further, `np.float64` is a double subclass, so must reject it.
      */
+    // TODO,NOTE: This function should be changed to do exact long checks
```
[the remark this answers is not in the document]
Comment (seberg) [reply numpy/_core/src/multiarray/abstractdtypes.h:50]: Created a specific one that is milestoned.

**Comment by ngoldbaum** [comment]
I'd like to see this merged to fix the bug. Let's figure out how to improve promoters in followups.

**Comment by ngoldbaum** [comment]
Actually @seberg could you rebase and then merge this assuming the tests pass? Looks like doctests are failing because the merge base is a couple weeks old. I'm sure everything is fine I'd just rather not unintentionally break CI.

File: numpy/_core/src/umath/stringdtype_ufuncs.cpp (hunk 8 above)
Comment (mhvk) [reply numpy/_core/src/umath/stringdtype_ufuncs.cpp:1035]: It was probably good to get this in, but it still feels weird to have a promotor for a given dtype return a result that does not involve that type at all - how can it decide for another type what is acceptable? Two of your solutions sound reasonable: returning the equivalent of `NotImplemented` (your `-1` with no error set), or a default promotor. Maybe worth a new issue?
