### PR TITLE
BUG: Update coordinates in PyArray_ITER_GOTO1D

### LINKED ISSUE #18971: PyArrayNeighborhoodIterObject is left in wrong state after PyArray_ITER_GOTO1D on the underlying iterator
PyArray_ITER_GOTO1D doesn't update coordinates in non contiguous mode, which is used by PyArrayNeighborhoodIterObject to calculate it's own position on PyArrayNeighborhoodIter_Reset, leaving the PyArrayNeighborhoodIterObject pointing to the last position before the call to PyArray_ITER_GOTO1D.

Note that at creation of a new PyArrayNeighborhoodIterObject, if forces a non contiguous mode on the underlying iterator.

### Reproducing code example:

```c
//img is a 2D contiguous array (1200x1200)
PyArrayIterObject *iter = (PyArrayIterObject *) PyArray_IterNew((PyObject*) img);
npy_intp bounds[] = {-1,1,-1,1};
PyArrayNeighborhoodIterObject*neigh_iter = (PyArrayNeighborhoodIterObject*) PyArray_NeighborhoodIterNew(
                  iter, bounds, NPY_NEIGHBORHOOD_ITER_ZERO_PADDING ,0);
PyArray_ITER_GOTO1D(iter,1000);
PyArrayNeighborhoodIter_Reset(neigh_iter);
// At this point, iter is pointing to the 1000th item,
// but neigh_iter is still pointing to the 0th entry on iter
```

### PR DESCRIPTION
**Pull request by ReallyNiceGuy**
BUG: Update coordinates on PyArray_ITER_GOTO1D

Closes #18971

### CODE REVIEW

**Comment by seberg** [comment]
Thanks!  We do have some tests in `numpy/core/src/multiarray/_multiarray_tests.c.src`. If it isn't very tricky, we need to add a test there to ensure we don't introduce a regression again (plus, that would also make it easier to improve the code at some point).

**Comment by ReallyNiceGuy** [comment]
I am sorry, but I don't even know where to begin to integrate a test. If you have someone that can create an skeleton for the test, I can fill it up with the validation code.

If you manage that, write it so that I can check both PyArray_ITER_GOTO1D and PyArray_ITER_GOTO, as they are not checked yet.

**Comment by seberg** [comment]
There are some tests here: https://github.com/numpy/numpy/blob/f473d571f58c78f89979138c8cc79fcf5db05f42/numpy/core/src/multiarray/_multiarray_tests.c.src#L158

Basiclly, you could add a test like:
```
PyObject *
test_neighbourhood_iter_modify_img_goto1d(PyObject *NPY_UNUSED(self), PyObject *img)
{
    /* Do things with image */
   Py_RETURN_NONE;  /* Assuming, e.g. you just modify the image using the iterator */
}

/*  AT the end of the file add after these: */

    {"test_neighborhood_iterator",
        test_neighborhood_iterator,
        METH_VARARGS, NULL},
    {"test_neighborhood_iterator_oob",
        test_neighborhood_iterator_oob,
        METH_VARARGS, NULL},
    /* The following is new: */
    {"test_neighbourhood_iter_modify_img_goto1d"
        test_neighbourhood_iter_modify_img_goto1d,
        METH_O, NULL},
     /* ... */
```
The `METH_O` means that you can use the Python object `img` directly.  There Python tests that use those functions in `numpy/core/tests/test_multiarray.py` (since `test_neighborhood_iterator` is used there we can add your there as well).

Does this make sense?

**Comment by ReallyNiceGuy** [comment]
That is great, I can start with this.
Do you want another pull request for the test or shall I just add to this one?
The test might take a little longer though.

**Comment by seberg** [comment]
Cool, please include the test here, it makes it easier for the review to judge that the change is correct.

**Comment by ReallyNiceGuy** [comment]
Can I inspect the state of PyArrayObject or it must be treated as opaque in the test code?
The problem I am having is on how to prove that my PyArrayObject coordinates match the iterator position after the call to PyArray_ITER_GOTO1D.
Looking this way, the test has nothing to do with the neighborhood iterator, it is just that the neighborhood iterator exposes the bug.

**Comment by seberg** [comment]
Sure, you can inspect it. I thought you might want to just modify the array in the test, but inspecting the position is just as well.  You could raise an error from C, or inspect it and put it into a tuple to be checked from Python.

**Comment by ReallyNiceGuy** [comment]
Ok, I am not versed on this test harness. It is way over my head.
What should be tested is:
1. Create an array (2D at least)
2. Create an iterator on it
3. Create an neighborhood iterator on top of the iterator
4. Use PyArray_ITER_GOTO1D to go somewhere in the middle
5. Do a Reset on the neighborhood iterator
6. Check that it got the correct data point from the original iterator.

Ideally, it should be tested also for PyArray_ITER_GOTO, as the neighborhood implementation is not ideal (neighborhood iterator forces the iterator to think that the underlying data is non contiguous, so it updates the coordinates field).

What brings me to conclude that, if you swap steps 3. and 4., the check will fail. It will only be in sync again after the next base iterator movement, either with Next of one of the GOTO macros.

I am really sorry for throwing down the towel.

**Comment by seberg** [comment]
@ReallyNiceGuy can I give you a bit of pointers to keep you going? It was sounding like you were well on track.

The only thing I would suggest would be to insert a step 5b: Do something with the image (just set a value!).  You could then repeat the same thing thing (setting some arbitrary position) with `GOTO` instead of `GOTO1D`.

Then the `img` that was passed in will be modified and we can check in Python that it is correct.  Especially if you are far enough to compile, etc. can you push your work in progress, then maybe I can help you fill in the blanks.

**Comment by ReallyNiceGuy** [comment]
I got an idea to reuse the `test_neighborhood_iterator` function to do the validation by passing another parameter: the start index for the flattened array. This will allow me to put a call to `PyArray_ITER_GOTO1D` directly there and the python side can check the neighborhood iterator from the beginning and from the middle.

Then I looked at `copy_@name@` and `copy_object` and saw:
```
for (i =0; i < itx->size; ++i) {
        PyArrayNeighborhoodIter_Reset(niterx);
```
This just assumes that the iterator passed to it will be at the beginning.
I want to change it to `for (i = itx->index; i < itx->size; ++i) {` instead. I already checked and the tests still pass, and there is no risk to go beyond the end of the iterator anymore.

Do you want me to open a separate PR just for this change? I might be nice to document it, because it is a small fix in itself.

**Comment by seberg** [comment]
Since its different thing, a new PR can be nice.  But this is just in the test code (`numpy/core/src/multiarray/_multiarray_tests.c.src-`), and if all it is changing that one starting index (or I guess resetting `idx` instead), you can also just do it here.

File: numpy/core/src/multiarray/iterators.c [hunk 1]
```diff
@@ -1772,6 +1772,9 @@ PyArray_NeighborhoodIterNew(PyArrayIterObject *x, const npy_intp *bounds,
      */
     x->contiguous = 0;
 
+    /* update the coordinates */
+    PyArray_ITER_GOTO1D(x, x->index);
```
Comment (seberg) [inline numpy/core/src/multiarray/iterators.c:1776]: NIT: This is necessary when `x` was previously contiguous only, right? Maybe add that to the comment to make it clear?

File: numpy/core/src/multiarray/_multiarray_tests.c.src [hunk 2]
```diff
@@ -161,10 +161,11 @@ test_neighborhood_iterator(PyObject* NPY_UNUSED(self), PyObject* args)
     PyArrayObject *ax, *afill;
     PyArrayIterObject *itx;
     int i, typenum, mode, st;
+    int idxstart = 0;
```
Comment (seberg) [inline numpy/core/src/multiarray/_multiarray_tests.c.src:164]: For your information (this is just a test so, it doesn't matter), using `Py_Ssize_t` and then parsing with `n` is better.  NumPy uses `npy_intp` internally (which can differn unfortunately). But integers are 32bit on 64bit windows, so they are not quite right.

**Review by seberg — DISMISSED** [review]
Thanks, looks good to me, made two nits, but it would look fine to just merge as it is.

File: numpy/core/src/multiarray/iterators.c (hunk 1 above)
Comment (ReallyNiceGuy) [reply numpy/core/src/multiarray/iterators.c:1776]: Shall I rebase the fixes or just apply a new commit?

File: numpy/core/include/numpy/ndarraytypes.h [hunk 3]
```diff
@@ -1225,6 +1225,8 @@ struct PyArrayIterObject_tag {
                 _PyAIT(it)->dataptr = PyArray_BYTES(_PyAIT(it)->ao); \
                 for (__npy_i = 0; __npy_i<=_PyAIT(it)->nd_m1; \
                      __npy_i++) { \
+                        _PyAIT(it)->coordinates[__npy_i] = \
+                                (__npy_ind / _PyAIT(it)->factors[__npy_i]); \
```
Comment (seberg) [inline numpy/core/include/numpy/ndarraytypes.h:1229]: Sorry, shouldn't hvae "dismissed the review".  This had looked a bit weird to me with all the division (and I missed the modulo later).  I still wonder if there isn't a nicer way to do this. But thats a different issue :).

Comment (ReallyNiceGuy) [reply numpy/core/include/numpy/ndarraytypes.h:1229]: I copied what GOTO does.

File: numpy/core/src/multiarray/iterators.c (hunk 1 above)
Comment (seberg) [reply numpy/core/src/multiarray/iterators.c:1776]: Either way works!  If you have large PRs, _not_ rebasing can be nice, so the reviewer can see what changed (but this is small enough it doesn't matter).

For the final merge, rebasing is nicer.  But there is now a "squash and merge" button on github and generally we started caring a bit less about the history.  So there really is no wrong answer here :).

Comment (ReallyNiceGuy) [reply numpy/core/src/multiarray/iterators.c:1776]: Done

File: numpy/core/src/multiarray/_multiarray_tests.c.src (hunk 2 above)
Comment (ReallyNiceGuy) [reply numpy/core/src/multiarray/_multiarray_tests.c.src]: Done

**Comment by ReallyNiceGuy** [comment]
Thank you for holding my hand! ;)

It was a good experience contributing to this project.

**Comment by seberg** [comment]
Thanks, it was a good contribution and I didn't even get to nitpick about code style ;).  Putting this in, it looks right to me and is also in a pretty obscure part of NumPy.

**Comment by ReallyNiceGuy** [comment]
> Thanks, it was a good contribution and I didn't even get to nitpick about code style ;)

I've been burned by that already in another project. :D

**Comment by rgommers** [comment]
Hi all, this is causing a number of test failures in SciPy, see https://github.com/scipy/scipy/issues/14040. The failures are all related to `scipy.signal.correlate`, which uses `PyArray_ITER_NEXT`.

I can't easily tell what the problem is here, but we have a SciPy sprint tomorrow morning and a release split coming up, so I think we should revert this PR until it can be sorted out.

@ReallyNiceGuy would you be able to have a look at what the problem may be? The SciPy bug report has a simple reproducer.

File: numpy/core/src/multiarray/iterators.c (hunk 1 above)
Comment (seberg) [reply numpy/core/src/multiarray/iterators.c:1776]: Maybe this trips scipy? Possibly just because there is another bug...  Scipy was always the real stress test, it just seemed unlikely to actually do things.

Comment (ReallyNiceGuy) [reply numpy/core/src/multiarray/iterators.c:1776]: That is the lead I am following right now.
If this is the reason, there is a deeper problem in scipy itself. Can someone please do the test correlation with another tool and check the results?

Comment (seberg) [reply numpy/core/src/multiarray/iterators.c:1776]: I expect its not unlikely there is either a deeper problem in scipy, or some weird usage...  But, we will have to revert it in NumPy anyway if it is :(.  In the end, this is almost SciPy code put into numpy because it might be useful for someone...

@rgommers we can revert this for the sprint, you may also have to trigger the "nightly" build after that?

Comment (rgommers) [reply numpy/core/src/multiarray/iterators.c:1776]: >  But, we will have to revert it in NumPy anyway if it is

Unfortunately, that's how things have to work, yes

> @rgommers we can revert this for the sprint, you may also have to trigger the "nightly" build after that?

Thanks. It's not actually a nightly build, that's a misnomer - it's running on every PR.

Comment (seberg) [reply numpy/core/src/multiarray/iterators.c:1776]: Yes, a misnomer, but I thought it was bi-weekly...

Comment (rgommers) [reply numpy/core/src/multiarray/iterators.c:1776]: No cron trigger here, just a regular job: https://github.com/scipy/scipy/blob/master/.github/workflows/linux.yml#L55

Comment (ReallyNiceGuy) [reply numpy/core/src/multiarray/iterators.c:1776]: I can't really decide if it is a bug on the original numpy implementation of PyArray_ITER_GOTO1D.
I see that scipy is creating a neighborhood iterator from a neighborhood iterator. But for sure, calling PyArray_ITER_GOTO1D inside PyArray_NeighborhoodIterNew is definitely messing with the scipy expectations. Please revert just the change to PyArray_NeighborhoodIterNew while I try figure out why this is broken.
I ran the tests here and the changes to PyArray_ITER_GOTO1D don't seem to trip scypi.

Comment (ReallyNiceGuy) [reply numpy/core/src/multiarray/iterators.c:1776]: Well, after some tests, I removed `PyArray_ITER_GOTO1D` from the constructor and called it manually outside, at the point of usage: fails the same
I used `PyArray_ITER_GOTO` instead: fails the same
By calling `_PyAIT(curneighx->_internal_iter)->coordinates[i]=0` for each coordinate, it fails, even though the original value was already `0`.
I have no clue why this would be the case, I would appreciate some help from somebody that understands what is going on on the file `./scipy/signal/correlate_nd.c.in`, function `_correlate_nd_imp`.

Comment (ReallyNiceGuy) [reply numpy/core/src/multiarray/iterators.c:1776]: Problem was on my assumption on calling PyArray_ITER_GOTO1D inside PyArray_NeighborhoodIterNew.
