### PR TITLE
BUG: decref of field title caused segfault

### LINKED ISSUE #11507: Python crash after several iterations of np.require
Sample script with all the conditions:

```
import numpy as np

t = np.dtype([(('Some field description', 'f1'), np.float64)])
data = np.zeros(100, t)
for i in xrange(10):
    print(i)
    np.require(data[['f1']], t)
```

Output:
```
0
1
2
3
4
5
6

Process finished with exit code -1073741819 (0xC0000005)
```

### PR DESCRIPTION
**Pull request by mattip**
Fixes #11507. Test added that fails before, passes after the fix.

`git tag --contains 9f27418f48` says it was first released in v1.14.0

### CODE REVIEW

File: numpy/core/src/multiarray/mapping.c [hunk 1]
```diff
@@ -1546,7 +1546,6 @@ _get_field_view(PyArrayObject *arr, PyObject *ind, PyArrayObject **view,
                     Py_DECREF(names);
                     return 0;
                 }
-                Py_DECREF(title);
```
Comment (mhvk) [inline numpy/core/src/multiarray/mapping.c]: Nice catch - `title` is a borrowed reference here. But that means it should also not be `DECREF`d in the failure path just above (l.1543).

Comment (mattip) [reply numpy/core/src/multiarray/mapping.c]: fixed

**Comment by charris** [comment]
Thanks Matti.
