### PR TITLE
BUG: Make scalar function elision check if temp is writeable.

### LINKED ISSUE #9679: ValueError: output array is read-only calling .imag on real valued signal in 1.13.1
When I create a real valued array of certain shape, I get a `ValueError: output array is read-only` when calling .imag and squared on the array.

This happens on:
```
numpy-1.13.1
numpy-1.13.0-p
```

This does not happen on:
```
numpy-1.12.0-p
```

Details to reconstruct are given as follows (here for Anaconda). Create an empty environment with `environment.yml` as follows:
```
name: project_read_only_bug
dependencies:
- python=3.6
- numpy=1.13.1
```

Run:
```
conda env create
```

Run the following Python file:
```
import numpy as np
time_signal = np.random.randn(3, 16000)
time_signal.imag ** 2
```

Expect the following error:
```
Traceback (most recent call last):
  File "read_only_bug.py", line 3, in <module>
    time_signal.imag ** 2
ValueError: output array is read-only
```

In all the following very related cases, the bug does not occur:
```
import numpy as np
time_signal = np.random.randn(3, 16000)
time_signal.imag
```

```
import numpy as np
time_signal = np.random.randn(3, 10)
time_signal.imag ** 2
```

```
import numpy as np
time_signal = np.random.randn(3, 16000)
time_signal.imag + 3
```

### PR DESCRIPTION
**Pull request by charris**
Add checks for writeable and updateifcopy in the can_elide_temp_unary
function.

Closes #9679.

### CODE REVIEW

File: numpy/core/src/multiarray/temp_elide.c [hunk 1]
```diff
@@ -363,6 +363,8 @@ can_elide_temp_unary(PyArrayObject * m1)
     if (Py_REFCNT(m1) != 1 || !PyArray_CheckExact(m1) ||
             !PyArray_ISNUMBER(m1) ||
             !(PyArray_FLAGS(m1) & NPY_ARRAY_OWNDATA) ||
+            !PyArray_ISWRITEABLE(m1) ||
+            PyArray_CHKFLAGS(m1, NPY_ARRAY_UPDATEIFCOPY) ||
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/temp_elide.c]: This line seems to be an unrelated bugfix (with no test?)

Comment (charris) [reply numpy/core/src/multiarray/temp_elide.c]: Both fixes went in together for binary functions. I suspect the updateifcopy check is no longer needed but would like to keep it in until those types of arrays are completely gone. However, they are gone enough that I no longer know how to test it as `a.flat.__array__()` now returns a straight copy.

Comment (eric-wieser) [reply numpy/core/src/multiarray/temp_elide.c]: Also can you change the `PyArray_FLAGS` above to also use PyArray_CHKFLAGS for consistency?
