### PR TITLE
BUG: fix refcount leak in PyArray_AdaptFlexibleDType

### LINKED ISSUE #11951: Memory leak when using astype('unicode')
When converting elements in an numpy array to unicode with numpy.ndarray.astype memory keeps increasing. I am running this on:
OS: Ubuntu 18.04.1 LTS x86_64  
CPU: Intel i5-3570 (4) @ 3.800GHz   
GPU: AMD Radeon HD 7750/8740 
Memory: 2775MiB / 7921MiB
Though I have also seen it on windows machines.

This is the first time I have reported a bug, if there is something that "everyone" know you have to include in a bug report, but that I have missed, just tell me and I will try to provide it.

### Reproducing code example:

When running this file, the memory is increasing.
```python
import numpy as np

def write_file():
    i = 0
    while i < 2e3:
        event = {
            "data": {"country": "us"},
        }

        for j in range(10000):
            values = np.array(list(event.values()))
            values.astype('unicode')

        i += 1

write_file()
```

### Error message:
There is no particular error to report here. But I have made a graph showing memory usage while running the program. Some extensive search with "ps" tool in Kubuntu showed that it was the process belonging to this program causing the increased memory usage. 
image

### Numpy/Python version information:
1.15.1 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0]

### PR DESCRIPTION
**Pull request by mattip**
Fixes #11951. Variable were initialized but never `decref`ed. I am not sure how to write a test since they are new instances that never escape out of the local function, so `sys.get_refcount` cannot see them. Do they somehow show up in the `gc` module on CPython?

### CODE REVIEW

**Comment by charris** [comment]
Labels, labels...

File: numpy/core/src/multiarray/convert_datatype.c [hunk 1]
```diff
@@ -259,6 +254,10 @@ PyArray_AdaptFlexibleDType(PyObject *data_obj, PyArray_Descr *data_dtype,
                              * GetArrayParamsFromObject won't iterate over
                              * array.
                              */
+                            PyArray_Descr *dtype = NULL;
+                            PyArrayObject *arr = NULL;
+                            int result, ndim = 0;
+                            npy_intp dims[NPY_MAXDIMS];
                             list = PyArray_ToList((PyArrayObject *)data_obj);
                             result = PyArray_GetArrayParamsFromObject(
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/convert_datatype.c]: Seems there's another bug here - this doesn't propagate exceptiosn correctly when `result < 0`

Comment (eric-wieser) [reply numpy/core/src/multiarray/convert_datatype.c]: In fact, `PyArray_AdaptFlexibleDType` really ought to have an `int` return value

Comment (eric-wieser) [reply numpy/core/src/multiarray/convert_datatype.c]: Out of scope for this PR though

File: numpy/core/src/multiarray/convert_datatype.c [hunk 2]
```diff
@@ -149,11 +149,6 @@ PyArray_AdaptFlexibleDType(PyObject *data_obj, PyArray_Descr *data_dtype,
 {
     PyArray_DatetimeMetaData *meta;
     int flex_type_num;
-    PyArrayObject *arr = NULL;
-    PyArray_Descr *dtype = NULL;
-    int ndim = 0;
-    npy_intp dims[NPY_MAXDIMS];
-    int result;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/convert_datatype.c]: This was unused? I'm surprised we weren't getting a warning if so.

File: numpy/core/src/multiarray/convert_datatype.c [hunk 3]
```diff
@@ -259,6 +254,10 @@ PyArray_AdaptFlexibleDType(PyObject *data_obj, PyArray_Descr *data_dtype,
                              * GetArrayParamsFromObject won't iterate over
                              * array.
                              */
+                            PyArray_Descr *dtype = NULL;
+                            PyArrayObject *arr = NULL;
+                            int result, ndim = 0;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/convert_datatype.c]: Would prefer not to combine these declarations

File: numpy/core/src/multiarray/convert_datatype.c (hunk 1 above)
Comment (mattip) [reply numpy/core/src/multiarray/convert_datatype.c]: see issue #11969

**Review by eric-wieser — APPROVED** [review]

**Comment by charris** [comment]
Thanks Matti.
