### PR TITLE
BUG: Fix segmentation fault

### LINKED ISSUE #21301: BUG: `matmul.at` segfaults
### Describe the issue:

Calling `matmul.at` on arrays that pass all checks on shape, indices, etc, leads to a segmentation fault.

**Expected result**
Calling other methods of ufuncs with a non-trivial signature raises either a `RuntimeError: Reduction not defined on ufunc with signature` or, in the case of `outer`,  a `TypeError: method outer is not allowed in ufunc with non-trivial signature`. Because `at` is not a reduction, my expectation is getting a `TypeError: method at is not allowed in ufunc with non-trivial signature`. I took the liberty to make the tiny adaption that implements the expected behavior here: https://github.com/dbeutel/numpy/commit/6db8d9649f07836b25edf6f038f9ded7a5e2314a 

### Reproduce the code example:

```python
import numpy as np

arr = np.ones((2, 2, 2))
np.matmul.at(arr, [0], np.ones((1, 2, 2)))
```

### Error message:

```shell
$ gdb --args python-dbg segfault_matmul_at.py
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python-dbg...
(gdb) run
Starting program: /usr/bin/python-dbg segfault_matmul_at.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff45ff640 (LWP 5504)]
[New Thread 0x7ffff3dfe640 (LWP 5505)]
[New Thread 0x7ffff15fd640 (LWP 5506)]
[New Thread 0x7fffecdfc640 (LWP 5507)]
[New Thread 0x7fffea5fb640 (LWP 5508)]
[New Thread 0x7fffe7dfa640 (LWP 5509)]
[New Thread 0x7fffe55f9640 (LWP 5510)]

Thread 1 "python-dbg" received signal SIGSEGV, Segmentation fault.
0x00007ffff707fb00 in DOUBLE_matmul () from /home/dbeutel/.local/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so
(gdb) bt
#0  0x00007ffff707fb00 in DOUBLE_matmul () from /home/dbeutel/.local/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so
#1  0x00007ffff70842e5 in generic_wrapped_legacy_loop () from /home/dbeutel/.local/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so
#2  0x00007ffff7087548 in ufunc_at () from /home/dbeutel/.local/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so
#3  0x00007ffff7cfa81e in method_vectorcall_VARARGS (func=func@entry=0x7ffff7330dd0,  args=args@entry=0x5555555f86d8, nargsf=<optimized out>, kwnames=0x0) at Objects/descrobject.c:311
#4  0x00007ffff7d08f4b in _PyObject_VectorcallTstate (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>, tstate=<optimized out>) at ./Include/cpython/abstract.h:114
#5  PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at ./Include/cpython/abstract.h:123
#6  call_function (tstate=0x55555555e7a0, trace_info=<optimized out>, pp_stack=0x7fffffffe1f0, oparg=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:5867
#7  0x00007ffff7cfec4e in _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x5555555f8570, throwflag=<optimized out>) at Python/ceval.c:4198
#8  0x00007ffff7cfd2eb in _PyEval_EvalFrame (throwflag=0, f=0x5555555f8570, tstate=0x55555555e7a0) at ./Include/internal/pycore_ceval.h:46
#9  _PyEval_Vector (tstate=<optimized out>, con=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=0, kwnames=<optimized out>) at Python/ceval.c:5065
#10 0x00007ffff7d7a1b4 in PyEval_EvalCode (co=0x7ffff739f780, globals=0x7ffff73c15b0, locals=<optimized out>) at Python/ceval.c:1134
#11 0x00007ffff7d948b4 in run_eval_code_obj (tstate=0x55555555e7a0, co=0x7ffff739f780, globals=0x7ffff73c15b0, locals=0x7ffff73c15b0) at Python/pythonrun.c:1291
#12 0x00007ffff7d8c316 in run_mod (mod=<optimized out>, filename=<optimized out>, globals=0x7ffff73c15b0, locals=0x7ffff73c15b0, flags=<optimized out>, arena=<optimized out>) at Python/pythonrun.c:1312
#13 0x00007ffff7c4024f in pyrun_file (fp=fp@entry=0x55555555a4f0, filename=filename@entry=0x7ffff73dc0b0, start=start@entry=257, globals=globals@entry=0x7ffff73c15b0, locals=locals@entry=0x7ffff73c15b0, closeit=closeit@entry=1, flags=0x7fffffffe5c8) at Python/pythonrun.c:1208
#14 0x00007ffff7c3f9fc in _PyRun_SimpleFileObject (fp=0x55555555a4f0, filename=0x7ffff73dc0b0, closeit=1, flags=0x7fffffffe5c8) at Python/pythonrun.c:456
#15 0x00007ffff7c40b2b in _PyRun_AnyFileObject (fp=0x55555555a4f0, filename=0x7ffff73dc0b0, closeit=1, flags=0x7fffffffe5c8) at Python/pythonrun.c:90
#16 0x00007ffff7da4e9c in pymain_run_file_obj (skip_source_first_line=0, filename=0x7ffff73dc0b0, program_name=0x7ffff73c1960) at Modules/main.c:353
#17 pymain_run_file (config=0x555555585550) at Modules/main.c:372
#18 pymain_run_python (exitcode=0x7fffffffe5c4) at Modules/main.c:587
#19 Py_RunMain () at Modules/main.c:666
#20 0x00007ffff7d67efd in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:720
#21 0x00007ffff7999310 in __libc_start_call_main () from /usr/lib/libc.so.6
#22 0x00007ffff79993c1 in __libc_start_main_impl () from /usr/lib/libc.so.6
#23 0x0000555555555045 in _start ()
```

### NumPy/Python version information:

* numpy: 1.22.3
* python: 3.10.2 (main, Apr  5 2022, 14:03:41) [GCC 11.2.0]

### PR DESCRIPTION
**Pull request by JohnnyOu**
BUG: Fixed segmentation fault with numpy.ufunc.at when ufunc has
nontrivial signature, issue #21301.

Test cases were added in numpy/core/tests/test_ufunc.py to show that
when numpy.ufunc.at uses ufunc with nontrivial signature, then
TypeError should be raised, instead of a potential segmentation fault.
Test cases were also added to show that ufunc with trivial signature is
still valid and works as intended. See [issue #21301](https://github.com/numpy/numpy/issues/21301).

### CODE REVIEW

File: numpy/core/src/umath/ufunc_object.c [hunk 1]
```diff
@@ -5888,6 +5888,13 @@ ufunc_at(PyUFuncObject *ufunc, PyObject *args)
 
     NPY_BEGIN_THREADS_DEF;
 
+    if (ufunc->core_enabled) {
+        PyErr_Format(PyExc_TypeError,
+            "numpy.ufunc.at does not support ufunc with non-trivial "\
```
Comment (seberg) [inline numpy/core/src/umath/ufunc_object.c:5893]: Just a nit, but the `\` is not necessary :).

We could probably make the error message friendlier by printing out the ufunc name rather than "numpy.ufunc.at".  The name is far more interesting than the actual core signature!

File: numpy/core/tests/test_ufunc.py [hunk 2]
```diff
@@ -2002,6 +2002,23 @@ def test_inplace_fancy_indexing(self):
...
 
+        # Test ufuncs with non-trivial signature raise a TypeError
+        a = np.ones((2, 2, 2))
+        b = np.ones((1, 2, 2))
+        assert_raises(TypeError, np.matmul.at, a, [0], b)
+
+        a = np.array([[[1, 2], [3, 4]]])
+        assert_raises(TypeError, np.linalg._umath_linalg.det.at, a, [0])
+
+        # Ufunc with None signature should work as intended
```
Comment (seberg) [inline numpy/core/tests/test_ufunc.py:2013]: I guess we should have tests for this already?  So I think you can remove them again.
If you think they add something, just move them above to that long list for now...

File: numpy/core/tests/test_ufunc.py [hunk 3]
```diff
@@ -2002,6 +2002,23 @@ def test_inplace_fancy_indexing(self):
         # Test multiple output ufuncs raise error, gh-5665
         assert_raises(ValueError, np.modf.at, np.arange(10), [1])
 
+        # Test ufuncs with non-trivial signature raise a TypeError
+        a = np.ones((2, 2, 2))
+        b = np.ones((1, 2, 2))
+        assert_raises(TypeError, np.matmul.at, a, [0], b)
+
+        a = np.array([[[1, 2], [3, 4]]])
+        assert_raises(TypeError, np.linalg._umath_linalg.det.at, a, [0])
```
Comment (seberg) [inline numpy/core/tests/test_ufunc.py:2011]: These tests look good.  But single test functions getting too long tends to be inconvenient.  Could you make a new method for these two?  Could just be something mentioning that gufuncs don't support `at` or so...

**Review by seberg — COMMENTED** [review]
Thanks! Looks good to me, just two tiny nitpicks.
We could improve the error a tiny bit (although nobody is likely to read it anyway, and IIRC it was actually copied).

**Comment by JohnnyOu** [comment]
I have modified the functions as requested! The error message is improved, displaying both the ufunc's name and signature, and the test cases (checking that the ufunc.at throws error on nontrivial signatures) were moved to their own method.

**Comment by JohnnyOu** [comment]
When can I expect this to get merged since the issue is fixed?

**Comment by charris** [comment]
@seberg Does this look good to you?

File: numpy/core/src/umath/ufunc_object.c [hunk 4]
```diff
@@ -5888,6 +5888,13 @@ ufunc_at(PyUFuncObject *ufunc, PyObject *args)
 
     NPY_BEGIN_THREADS_DEF;
 
+    if (ufunc->core_enabled) {
+        PyErr_Format(PyExc_TypeError,
+            "numpy.%s.at does not support ufunc with non-trivial signature: %s has signature %s.",
```
Comment (seberg) [inline numpy/core/src/umath/ufunc_object.c:5893]:
```suggestion
            "%s.at does not support ufunc with non-trivial signature: %s has signature %s.",
```
Ufuncs don't necessarily live in NumPy, and functions errors don't usually include the module anyway luckily.

**Comment by seberg** [comment]
Just a tiny fix, but just did that directly with a comment.  Otherwise, I think it is good to go in, though.

**Comment by seberg** [comment]
Thanks @JohnnyOu!

**Comment by InessaPawson** [comment]
Hi-five on merging your first pull request to NumPy, @JohnnyOu! We hope you stick around! Your choices aren’t limited to programming – you can review pull requests, help us stay on top of new and old  issues, develop educational material, work on our website, add or improve graphic design, create marketing materials, translate website content, write grant proposals, and help with other fundraising initiatives. For more info, check out: https://numpy.org/contribute
Also, consider joining our mailing list. This is a great way to connect with other cool people in our community and be part of important conversations that affect the development of NumPy: https://mail.python.org/mailman/listinfo/numpy-discussion
