### PR TITLE
BUG: Support using libunwind for backtrack

### LINKED ISSUE #22084: BUG: unable to build with musl, 'execinfo.h' file not found
### Describe the issue:

Unable to build with musl since 'execinfo.h' not exists.

### Reproduce the code example:

```python
N/A
```

### Error message:

```shell
INFO: clang: numpy/core/src/multiarray/temp_elide.c
numpy/core/src/multiarray/temp_elide.c:85:10: fatal error: 'execinfo.h' file not found
#include <execinfo.h>
                    ^~~~~~~~~~~~
1 error generated.
```
```


### NumPy/Python version information:

1.23

### PR DESCRIPTION
**Pull request by RinCat**
Some system (e.g. musl) do not have "execinfo.h", and the backtracking
is provided by libunwind.

Fix: #22084

### CODE REVIEW

File: numpy/core/src/multiarray/temp_elide.c [hunk 1]
```diff
@@ -82,7 +82,12 @@
 #define NPY_MIN_ELIDE_BYTES (32)
 #endif
 #include <dlfcn.h>
+
+#if defined HAVE_EXECINFO_H
 #include <execinfo.h>
+#elif defined HAVE_LIBUNWIND_H
+#include <libunwind.h>
+#endif
```
Comment (seberg) [inline numpy/core/src/multiarray/temp_elide.c:90]: Thanks, this makes sense to me now, although if neither is found, I guess the whole thing should be disabled (which is #61)

Comment (RinCat) [reply numpy/core/src/multiarray/temp_elide.c:90]: Yes, `HAVE_BACKTRACE` should disabled those include if `backtrack()` not found. Unless new backtracking library showed up, which should throw an error to notice devs.

**Review by rgommers — APPROVED** [review]
The test for `backtrace` we are using is in `numpy/core/feature_detection_misc.h`:
```C
#include <stddef.h>

int backtrace(void **, int);
int madvise(void *, size_t, int);
```
It's not entirely clear to me how `backtrace` ends up usable when including `stddef.h`, but it does seem to work. And `libunwind` indeed has `backtrace`, as an alias to its own `unw_backtrace`: https://github.com/dropbox/libunwind/blob/16bf4e5e498c7fc528256843a4a724edc2753ffd/src/mi/backtrace.c#L58-L79

So this PR looks like an improvement. It solves a build issue, so let's just merge it as is. If we find another case of `backtrace` existing but not being provided by either `execinfo.h` or `libunwind.h`, let's deal with a bigger reshuffle of this code at that point.
