### PR TITLE
BUG: Address interaction between SME and FPSR

### LINKED ISSUE #28687: BUG: wrong errors "divide by zero encountered in matmul" on MacOS
### Describe the issue:

I guess its self explanatory. Following code:

`np.identity(n=784) @ np.identity(n=784)`

produces many wrong runtime warnings.

For small matrices is works as expected, for eg. `np.ones(shape=(1, 1)) @ np.ones(shape=(1, 784))` doesn't produce warning.

### Reproduce the code example:

```python
import numpy as np
np.identity(n=784) @ np.identity(n=784)

# same result for
import numpy as np
np.ones(shape=(1, 2)) @ np.ones(shape=(2, 784))
```

### Error message:

```shell
../test.py:3: RuntimeWarning: divide by zero encountered in matmul
  np.identity(n=784) @ np.identity(n=784)
../test.py:3: RuntimeWarning: overflow encountered in matmul
  np.identity(n=784) @ np.identity(n=784)
../test.py:3: RuntimeWarning: invalid value encountered in matmul
  np.identity(n=784) @ np.identity(n=784)
```

### Python and NumPy Versions:

2.2.4
3.13.2 | packaged by Anaconda, Inc. | (main, Feb  6 2025, 12:55:35) [Clang 14.0.6 ]

### Runtime Environment:

_No response_

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by Developer-Ecosystem-Engineering**
This is intended to resolve https://github.com/numpy/numpy/issues/28687

The root cause is an interaction between Arm Scalable Matrix Extension (SME) and the floating point status register (FPSR).

 As noted in Arm docs for FPSR, "On entry to or exit from Streaming SVE mode, FPSR.{IOC, DZC, OFC, UFC, IXC, IDC, QC} are set to 1 and the remaining bits are set to 0".  This means that floating point status flags are all raised when SME is used, regardless of values or operations performed.

These are manifesting now because Apple Silicon M4 supports SME and macOS 15.4 enables SME codepaths for Accelerate BLAS / LAPACK.  However, SME / FPSR behavior is not specific to Apple Silicon M4 and will occur on non-Apple chips using SME as well.

Changes add compile and runtime checks to determine whether BLAS / LAPACK might use SME (macOS / Accelerate only at the moment).  If so, special handling of floating-point error (FPE) is added, which includes:
- Clearing FPE after some BLAS calls
- Short-circuiting FPE read after some BLAS calls

- All tests pass
- Performance is similar

Another approach would have been to wrap all BLAS / LAPACK calls with save / restore FPE.  However, it added notable overhead for the inner loops that utilize BLAS / LAPACK.  Some benchmarks were 8x slower with that approach.

### CODE REVIEW

**Comment by Developer-Ecosystem-Engineering** [comment]
31s to failure! Is that a record to beat or avoid!? Taking a look!

**Comment by charris** [comment]
The PyPy failure can be ignored.

**Comment by charris** [comment]
I am curious about the reasoning involved in having SME behave like that. I assume there was a good reason ...

**Comment by mattip** [comment]
>  This means that floating point status flags are all raised when SME is used, regardless of values or operations performed

I wonder why we do not see that on other places we use SME. Are we not testing SME or do Highway/intrinsics take care of this for us?

**Comment by Mousius** [comment]
> > This means that floating point status flags are all raised when SME is used, regardless of values or operations performed
> 
> I wonder why we do not see that on other places we use SME. Are we not testing SME or do Highway/intrinsics take care of this for us?

I don't think we've enabled SME anywhere else yet. OpenBLAS doesn't enable it by default, and Highway only supports up to SVE currently.

**Comment by charris** [comment]
Thanks @Developer-Ecosystem-Engineering .

File: numpy/_core/src/common/blas_utils.c [hunk 1]
```diff
@@ -0,0 +1,134 @@
...
+
+    // Parse the version string
+    int major = 0, minor = 0;
+    if(2 > sscanf(osProductVersion, "%d.%d", &major, &minor)) {
+        goto cleanup;
+    }
+
+    if(major >= 15 && minor >= 4){
+        ret = true;
+    }
```
Comment (BertalanD) [inline numpy/_core/src/common/blas_utils.c:48]:
```suggestion
    if(major > 15 || (major == 15 && minor >= 4)){
        ret = true;
    }
```

As written, this comparison will return false for e.g. `26.0`.

**Comment by charris** [comment]
For next time, also use hard line breaks in the commit messages and don't depend on word wrap. The editor should take care of that.

File: numpy/_core/src/common/blas_utils.c (hunk 1 above)
Comment (charris) [reply numpy/_core/src/common/blas_utils.c:48]: I fixed this in the backport.
