### PR TITLE
BUG: Fix memory leaks found by valgrind

### LINKED ISSUE #26581: BUG: Memory leaks/issues in StringDType tests
There are some issues (may update with more) that valgrind finds.  (Unicode objects unfortunately create some false positives.)

1. Running valgrind on the stringdtype tests, it seems that all test which use `"T"` for the dtype end up leaking the instance.

2. Additionally, it looks like the `test_float_casts` is leaking things (all of them, not just the float32 one):
```
**2567719** **********************************************************************
**2567719** build-install/usr/lib/python3.10/site-packages/numpy/_core/tests/test_stringdtype.py::test_float_casts[float32]
**2567719** **********************************************************************
==2567719== 48 (+48) bytes in 2 (+2) blocks are definitely lost in loss record 3,881 of 25,239
==2567719==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2567719==    by 0x2341AE: PyFloat_FromDouble (floatobject.c:137)
==2567719==    by 0x23E818: _PyEval_EvalFrameDefault (ceval.c:1952)
==2567719==    by 0x24CA2B: UnknownInlinedFun (pycore_ceval.h:46)
<snip>

==2567719== 264 (+264) bytes in 11 (+11) blocks are definitely lost in loss record 18,204 of 25,239
==2567719==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2567719==    by 0x2341AE: PyFloat_FromDouble (floatobject.c:137)
==2567719==    by 0x31AE0D: PyFloat_FromString (floatobject.c:230)
==2567719==    by 0x9487120: string_to_pyfloat (casts.c:865)
==2567719==    by 0x9487120: string_to_float32 (casts.c:1040)
==2567719==    by 0x940A7D2: raw_array_assign_array (array_assign_array.c:150)
==2567719==    by 0x940B2B6: PyArray_AssignArray (array_assign_array.c:444)
==2567719==    by 0x94625EF: array_astype (methods.c:865)
==2567719==    by 0x262725: method_vectorcall_FASTCALL_KEYWORDS (descrobject.c:405)
<snip>


<snip> one more issue, but it should be the `dtype="T"` leak </snip>
```
In other words, that tests seems to be leaking 2 float objects created in Python and 11 float objects created from within the cast.  (Note that I didn't run the test individually, sometimes pointers can dangle for a while, meaning that leaks are detected only at a later test/point.)

EDIT: It might be helpful to know that the cfloat casts do not seem to be leaking.

---

Might add more, but it's looking pretty good and it would be nice to fix the first one to have a better signal to noise ratio (otherwise it's easy to miss one).

Ping @ngoldbaum.

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes #26581 (I think).

I'd appreciate it if @seberg could re-run valgrind with these changes to let me know if I got everything. valgrind is so slow on my laptop I didn't have the patience to wait for it to run the full stringdtype tests.

### CODE REVIEW

File: numpy/_core/src/multiarray/descriptor.c [hunk 1]
```diff
@@ -2025,6 +2025,7 @@ arraydescr_dealloc(PyArray_Descr *self)
 {
     Py_XDECREF(self->typeobj);
     if (!PyDataType_ISLEGACY(self)) {
+        Py_TYPE(self)->tp_free((PyObject *)self);
```
Comment (seberg) [inline numpy/_core/src/multiarray/descriptor.c:2028]: Arg, had already fixed this in my (still open) PR.  But I guess it doesn't matter, let's see if it has a collision :).

File: numpy/_core/src/multiarray/arraytypes.c.src [hunk 2]
```diff
@@ -4280,7 +4281,7 @@ PyArray_DescrFromType(int type)
         PyErr_SetString(PyExc_ValueError,
                 "Invalid data-type for array");
     }
-    else {
+    else if (!is_stringdtype) {
```
Comment (seberg) [inline numpy/_core/src/multiarray/arraytypes.c.src:4284]: Can't say I like this control flow, but also don't want to iterate on this PR.

So thanks, let's just put it in.

@ngoldbaum I might rerun valgrind, but let's see (as you know running it this way, the full test suite takes 2 days rather than 2 minutes :)).
