### PR TITLE
BUG: check for overflow when converting a string to an int scalar

### LINKED ISSUE #24066: BUG: creating an integer scalar from a string does not warn about overflow
This behavior is deprecated:

```
in [3]: np.int32(2147483648)
<ipython-input-3-cd4bcbe47c5d>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 2147483648 to int32 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.int32(2147483648)
Out[3]: -2147483648
```

But this doesn't warn and probably should for consistency:

```
In [4]: np.int32('2147483648')
Out[4]: -2147483648
```

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes #24066

### CODE REVIEW

**Comment by seberg** [comment]
The path that everything else currently goes through is this I think: https://github.com/numpy/numpy/blob/6798aa64469233dfdeb609035400532102bad5b2/numpy/_core/src/multiarray/arraytypes.c.src#L175
(Diverging from the `_safe_pyint_setitem` path that I added in the `_SETITEM` call).

But, if you just want to change the scalar constructor this is also OK, to me.

**Comment by ngoldbaum** [comment]
Thanks for the hint, moved the string to int conversion into the scalar setitem.

File: numpy/_core/src/multiarray/arraytypes.c.src [hunk 1]
```diff
@@ -359,7 +359,17 @@ NPY_NO_EXPORT int
     @type@ temp;  /* ensures alignment */
 
 #if @is_int@
-    if (PyLong_Check(op)) {
+    int arg_converted = 0;
+    int is_pylong = PyLong_Check(op);
+    if (!(is_pylong || PyArray_Check(op))) {
```
Comment (ngoldbaum) [inline numpy/_core/src/multiarray/arraytypes.c.src:364]: The `PyArray_Check` here is a little weird but if I don't include it that breaks some tests related to masked arrays. In particular, the default integer mask fill value, 99999, is outside of the range of 8 and 16 bit integers so if you have a masked structured array with (say) an `i1` field, setting the default fill value raises an `OverflowError`. Yuck!

Didn't want to deal with that, so added a carve-out for array-likes. I could also check e.g. subtypes of `PyUnicode_Type` and only convert strings, but it seems better to do this overflow checking on anything that can be converted to a pyint.

File: numpy/f2py/tests/test_array_from_pyobj.py [hunk 2]
```diff
@@ -549,6 +549,10 @@ def test_in_cache_from_2casttype_failure(self):
                 continue
             if t.elsize >= self.type.elsize:
                 continue
+            is_int = np.subdtype(t.dtype, np.integer)
+            if is_int and int(self.num2seq[0]) > np.iinfo(t.dtype).max:
+                # skip test if num2seq would trigger an overflow error
+                continue
```
Comment (ngoldbaum) [inline numpy/f2py/tests/test_array_from_pyobj.py:555]: Before this PR one of the tests that uses this function silently relied on being able to create an int8 array from `['11111', '22222']`.

File: numpy/_core/tests/test_nep50_promotions.py [hunk 3]
```diff
@@ -309,3 +309,24 @@ def test_integer_integer_comparison(comp):
...
+        sctype(iinfo.max + 1)
+
+    with pytest.raises(OverflowError):
+        sctype(str(iinfo.min - 1))
+
+    with pytest.raises(OverflowError):
+        sctype(str(iinfo.max + 1))
+
+    assert sctype(iinfo.min) == iinfo.min
+    assert sctype(iinfo.max) == iinfo.max
```
Comment (seberg) [inline numpy/_core/tests/test_nep50_promotions.py:332]: Would be nice to also have a check for casts and array creation, which the above should cover (at this time).

File: numpy/_core/src/multiarray/arraytypes.c.src (hunk 1 above)
Comment (seberg) [reply numpy/_core/src/multiarray/arraytypes.c.src:364]: ... I was struggling with that quite a bit with NEP 50 too (and it probably may well still crop up in some places).  Don't love the full exceptions for arrays, but I agree with the general approach.

Unless anyone else has a thought: let's just add a comment why we have this exception here?

File: numpy/f2py/tests/test_array_from_pyobj.py (hunk 2 above)
Comment (seberg) [reply numpy/f2py/tests/test_array_from_pyobj.py:555]: OK, probably fine to skip uint8/int8, here.

File: numpy/_core/src/multiarray/arraytypes.c.src [hunk 4]
```diff
@@ -368,6 +381,9 @@ NPY_NO_EXPORT int
         if (@TYPE@_safe_pyint_setitem(op, &temp) < 0) {
             return -1;
         }
```
Comment (seberg) [inline numpy/_core/src/multiarray/arraytypes.c.src:383]: Maybe easier to just duplicate this call so that we don't need `arg_converted`?  Unfortunately, the error return is leaking the `op` reference.

**Review by seberg — APPROVED** [review]
Thanks, looks fine now, good to go when tests passed.
