### PR TITLE
BUG: array interface PyCapsule reference

### LINKED ISSUE #20673: BUG: array interface c-struct memory management, the wrong reference is held
### Describe the issue:

This issue pertains to the c-struct portion of the numpy array interface[[1](https://numpy.org/doc/stable/reference/arrays.interface.html#c-struct-access)]. When numpy makes use of an object's data via the `object.__array_struct__` member, numpy should take a reference to the PyCapsule stored in `object.__array_struct__` [[2](https://numpy.org/doc/stable/reference/arrays.interface.html#object.__array_struct__)]. When numpy releases that reference, the PyCapsule's destructor [[3](https://docs.python.org/dev/c-api/capsule.html#c.PyCapsule_Destructor)] can free the data shared with numpy.

However, numpy takes a reference to the `object` itself[[4](https://github.com/numpy/numpy/blob/48deea3f616c263e262d9147d62db5ae6c284683/numpy/core/src/multiarray/ctors.c#L2108)] rather than the PyCapsule in `object.__array_struct__`, and immediately DECREF's the PyCapsule[[5](https://github.com/numpy/numpy/blob/48deea3f616c263e262d9147d62db5ae6c284683/numpy/core/src/multiarray/ctors.c#L2112)].   This approach is  fine when the data shared with numpy is a pointer to memory directly managed by the object, but is incorrect when a temporary is needed to share the data with numpy because when numpy DECREF's the PyCapsule, the PyCapsule destructor will free the temporary leading to invalid memory accesses when accessed from Python/numpy code.

Numpy should take a reference to the PyCapsule instance in `object.__array_struct__`  rather than to the `object` itself. The PyCapsule's destructor is the only means we have of numpy signaling that numpy is finished with the _specific data_ that was shared with it. When numpy DECREF's the `object` itself, on the C side we can't tell when Numpy is finished, and hence we can't know when to free the _specific data_ that was shared with numpy. This means that any temporary allocated for the purposes of sharing data with numpy needs to persist for the lifetime of the object itself, rather than only the time it is being used by numpy. That's not to hard to orchestrate but it is inefficient and problematic for large arrays.

For instance in my case I want to pass data to numpy that may have been allocated either on a GPU or CPU. In the case that it is allocated on a CPU, the pointer is indeed managed by the object, and numpy's approach of holding a reference to the object works. However, in the case that the data was allocated on a GPU, when sharing with numpy I first need to move the data from the GPU to a temporary allocation on the CPU for numpy. that temporary needs to persist while the corresponding numpy array is alive. this copy exists _only for numpy_, and should not outlive numpy's use of it. if I associate the temporary with the PyCapsule in `object.__array_struct__` there are invalid memory accesses, because numpy decref's the PyCapsule before the memory should be released. If I associate the temporary with the object itself then the temporary ends up staying alive long past numpy's use of it, until the object itself is destroyed. The latter could lead to out of memory conditions and is inefficient.

Holding a reference to both `object` and the PyCapsule in `object.__array_struct__` the would solve the problem and ensure that codes relying on the current implementation continue to function.

### Reproduce the code example:

```python
a small self contained example can be found here:
https://github.com/burlen/test_array_interface
```

### Error message:

```shell
see example above
```

### NumPy/Python version information:

1.19.5 3.9.0 (default, Oct  6 2020, 00:00:00) 
[GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]

### PR DESCRIPTION
**Pull request by burlen**
With this change numpy holds a reference to the PyCapsule by which the
PyArrayInterface is returned in addition to the object which supplied
it. This lets numpy signal (via the PyCapsule destructor) when it is
finished with the data, which may not be managed by the object which
provided the PyCapsule instance. The old behavior of holding a reference
only to the object which provided the PyCapsule is kept to ensure backward
compatibility.

closes gh-20673

### CODE REVIEW

**Comment by burlen** [comment]
there is a small self contained example I've used for testing this change here
https://github.com/burlen/test_array_interface

File: numpy/core/src/multiarray/ctors.c [hunk 1]
```diff
@@ -2105,11 +2105,32 @@ PyArray_FromStructInterface(PyObject *input)
         }
     }
 
+    /* a tuple to hold references */
+    PyObject *refs = PyTuple_New(2);
+    if (!refs) {
+        PyErr_SetString(PyExc_MemoryError, "Failed to allocate a Tuple of size 2");
```
Comment (mattip) [inline numpy/core/src/multiarray/ctors.c:2111]: The error should already be set, and since it is an allocation error the less done after that the better.
```suggestion
```

**Comment by mattip** [comment]
What is printed for the `a.base` before and after this change?

**Comment by mattip** [comment]
The sample seems small enough it could be added as a test, using [testing.extbuild](https://numpy.org/devdocs/reference/testing.html?highlight=extbuild#using-c-code-in-tests) to build a c-extension. This should probably be marked with `@pytest.mark.slow`.

File: numpy/core/src/multiarray/ctors.c (hunk 1 above)
Comment (burlen) [reply numpy/core/src/multiarray/ctors.c]: Ah, OK. Thanks for pointing this out. I made the suggested change.

**Comment by burlen** [comment]
> What is printed for the `a.base` before and after this change?

before:
```
nparr.base = <buffer.buffer; proxy of <Swig Object of type 'buffer *' at 0x7f1186c5a180> >
```
after:
```
nparr.base = (<buffer.buffer; proxy of <Swig Object of type 'buffer *' at 0x7f4183e1a870> >, <capsule object NULL at 0x7f4183e1a900>)
```
The above output was obtained from the example I linked to above.

> The sample seems small enough it could be added as a test

Thanks for the pointers. I added a simplified test based on the example. The test is in a second commit to make it easy to experiment before/after the bug fix patch.

**Comment by mattip** [comment]
Cool. The extension building code is rather new, so suggestions to make the workflow easier would be appreciated.

File: numpy/core/src/multiarray/ctors.c [hunk 2]
```diff
@@ -2105,11 +2105,31 @@ PyArray_FromStructInterface(PyObject *input)
...
+     * access to the data. */
+    PyTuple_SET_ITEM(refs, 1,  attr);
+
+    /* create the numpy array, this call adds a reference to refs */
     PyObject *ret = PyArray_NewFromDescrAndBase(
             &PyArray_Type, thetype,
             inter->nd, inter->shape, inter->strides, inter->data,
-            inter->flags, NULL, input);
-    Py_DECREF(attr);
+            inter->flags, NULL, refs);
```
Comment (seberg) [inline numpy/core/src/multiarray/ctors.c:2129]: (Not much of an opinion on whether this should be backported).  But what do you think about my proposal to change this to:
```C
ctx = PyCapsule_GetContext(attr)
if (ctx == NULL && PyErr_Occurred()) {
    /* error cleanup */
    return NULL;
}
/* ctx should not be NULL, but do not rely on it for now: */ 
ref = ctx != NULL ? ctx : input;
```
I feel like that may be a nice way to achieve the same thing, and makes me more comfortable with the change.

The `copy=NEVER` champions could look into adding something a `ctx == input` check if desired.

Comment (burlen) [reply numpy/core/src/multiarray/ctors.c:2129]: > what do you think about my proposal to change this to 

Two things come to mind. 

Note that the type of the `PyCapsule`'s context field is `void *`, and that the `base` argument to `PyArray_NewFromDescrAndBase`  is type `PyObject*`.
https://github.com/numpy/numpy/blob/1a0d1fba57c76501bd47828ddcafdb924f89eb15/numpy/core/src/multiarray/ctors.c#L948-L951

The proposed change would make memory management of resources other than `PyObject`'s more complicated because it would require the capsule's context field be a `PyObject` but in data shared with numpy from C/C++ the most common use case would be management of temporary buffers allocated with `new` or `malloc`.  See the self contained example I've been using for testing linked to above for an example. With the proposed change, the capsule's context field could no longer be used to track such resources directly, and the capsule's destructor could no longer be used to directly release them. Such resources would instead need to be managed by a secondary object. This could be accomplished, by setting the context field to a second `PyCapsule`, but it is more complicated to do it that way.

There's also a potential type safety issue introduced here because the`PyCapsule`'s context is type `void * `.  It would be easy to misuse this design by inadvertently passing something other than a `PyObject` as the context.  Such accidental misuse would lead to an invalid memory access, and would potentially crash with a segv. There's not a safe way in C to check if the memory pointed to by the `void*` context is in fact a `PyObject*` before numpy uses it. One could argue that it's the responsibility of the sharer of the data, but it's worth noting that this issue isn't present in the original proposal.

I don't know that these two things are necessarily show stoppers for your suggestion, but they might be worth considering.

Comment (seberg) [reply numpy/core/src/multiarray/ctors.c:2129]: > Note that the type of the PyCapsule's context field is void *, and that the base argument to PyArray_NewFromDescrAndBase is type PyObject*.

Hmm, missed that.  I guess the docs specify it must be an object, but this was never really enforced, so it is unclear that we should do it.
I can also see the point that it would limit your flexibility compared to this solution, have to think a bit more about this, but if others want to move forward, please do not worry too much... I suppose in the end we have "flags" we can use to tag on new information to add new information (not ideal but OK).

A small problem would be if there are consumers other than NumPy, but that would only affect your type actually using this.

**Comment by mattip** [comment]
In the latest developer meeting we discussed:
- we should hold on to the PyCapsule reference.
- we should deprecate `__array_struct__`, there are too many interop protocols. See PR #20185 to document them. 
- find a way to allow interop with user-defined dtypes
- find a way to have an interop with data that we can be sure is never copied

@seberg correct me if I misrepresented the discussion. The bottom line is to polish any rough edges in this PR and accept it.

**Comment by seberg** [comment]
Yes, I still don't love it, but that is fine :).  I am unsure if we should backport this, as I think it largly extends the protocol rather than fixing a bug per-se and it changes `arr.base` from something that may often be meaningful, into something hard to make sense of (a tuple).

For "rough edges" beyond my "why :)?": It would be nice to just use `PyTuple_Pack(2, ...)` which will be much shorter code.

**Comment by charris** [comment]
>  it changes arr.base

@seberg Could you expand on this?

**Comment by mattip** [comment]
@charris: before this PR, `a.base` was a reference to the object inside the `PyCapsule`. After this PR, it is a tuple of `(ref-to-object, PyCapsule)`. See [this comment above](https://github.com/numpy/numpy/pull/20674#issuecomment-1002757335)

**Comment by seberg** [comment]
Previously, if I had an object that had an array struct (say JAX implemented it, though they do not):
```
jax_arr = jax.numpy.Array([1, 2, 3, 4])
numpy_arr = np.asarray(jax_arr)
```
Then, before:
```
numpy_arr.base is jax_arr
```
while now we will have:
```
numpy_arr.base == (jax_arr, some_capsule)
```

**Comment by charris** [comment]
> numpy_arr = np.asarray(jax_arr)

Ah, so `jax_arr` is exporting a `PyCapsule` to `np.asarray`?

**Comment by seberg** [comment]
Yes, it would export a capsule containing the same information that `__array_interface__` would contain.  That capsule should keep the data alive (i.e. have co-ownership).  The proposal is to store the capsule as well now.  This enables the capsule to be the sole owner of the data.

This makes the protocol safer, since before passing around an `__array_struct__` might remove it from the actual owner (`__array_interface__` has the problem as well).

I agree with this, and I am starting to agree that from my "long term" thinking, I just shouldn't care about this :).  Long term `__array__()` is probably the only good protocol, and the easiest to expand with additional functionality.

**Comment by mattip** [comment]
Next thing to do is to deprecate `__array_struct__` ...

**Comment by charris** [comment]
I marked for backport, but the changed return type worries me. Is there a good reason to backport this, or should it wait on 1.23?

**Comment by seberg** [comment]
I tend to not backporting, I view this more as an enhancement rather than a bug-fix to begin with.

**Comment by mattip** [comment]
I agree with @seberg

**Comment by charris** [comment]
Thanks. I unmarked it.
