### PR TITLE
ENH: core: More informative error message for broadcast(*args)

### LINKED ISSUE #8345: print nonbroadcastable shapes in np.broadcast_arrays error message
Currently, `np.broadcast_to` prints the nonbroadcastable shapes in its error message, but not `np.broadcast_arrays`:
```
In [1]: np.broadcast_to([1, 2], 3)
<elided>
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,) and requested shape (3,)

In [2]: np.broadcast_arrays([1, 2], [3, 4, 5])
<elided>
ValueError: shape mismatch: objects cannot be broadcast to a single shape
```
It would be mildly helpful if the second error message also reported the incorrect shapes.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
When broadcast(*args) fails because of a shape mismatch, include
in the error message which arguments caused the mismatch and what
their shapes are.

For example, instead of

    >>> np.broadcast([[0, 0, 0]], [[1], [1]], [2, 2])
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ValueError: shape mismatch: objects cannot be broadcast to a
    single shape

we now get

    >>> np.broadcast([[0, 0, 0]], [[1], [1]], [2, 2])
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ValueError: shape mismatch: objects cannot be broadcast to a
    single shape.  Mismatch is between arg 0 with shape (1, 3) and
    arg 2 with shape (2,).

This also affects broadcast_arrays() and broadcast_shapes().

Closes gh-8345.

### CODE REVIEW

File: numpy/core/src/multiarray/iterators.c [hunk 1]
```diff
@@ -1124,6 +1124,35 @@ NPY_NO_EXPORT PyTypeObject PyArrayIter_Type = {
 
 /** END of Array Iterator **/
 
+
+static int
+set_shape_mismatch_exception(PyArrayMultiIterObject *mit, int i1, int i2)
+{
+    PyObject *shape1, *shape2, *msg;
+
+    shape1 = PyObject_GetAttrString((PyObject *) mit->iters[i1]->ao, "shape");
```
Comment (seberg) [inline numpy/core/src/multiarray/iterators.c:1133]: Not really shorter, but an alternative is `PyArray_IntTupleFromIntp`.

File: numpy/core/src/multiarray/iterators.c [hunk 2]
```diff
@@ -1124,6 +1124,35 @@ NPY_NO_EXPORT PyTypeObject PyArrayIter_Type = {
...
+    msg = PyUnicode_FromFormat("shape mismatch: objects cannot be broadcast "
+                               "to a single shape.  Mismatch is between arg %d "
+                               "with shape %S and arg %d with shape %S.",
+                               i1, shape1, i2, shape2);
+    Py_DECREF(shape1);
+    Py_DECREF(shape2);
+    if (msg == NULL) {
+        return -1;
+    }
+    PyErr_SetObject(PyExc_ValueError, msg);
```
Comment (seberg) [inline numpy/core/src/multiarray/iterators.c:1151]: Maybe just use `PyErr_Format` directly?

File: numpy/core/tests/test_numeric.py [hunk 3]
```diff
@@ -3511,6 +3511,12 @@ def test_broadcast_error_kwargs(self):
 
         assert_raises(ValueError, np.broadcast, 1, **{'x': 1})
 
+    def test_shape_mismatch_error_message(self):
+        with pytest.raises(ValueError, match=r"arg 0 with shape \(1, 3\) and "
+                                             r"arg 2 with shape \(2,\)"):
```
Comment (seberg) [inline numpy/core/tests/test_numeric.py:3516]: Might be nicer to write `match = ...` to avoid the split within the string.  But doesn't matter.

File: numpy/core/src/multiarray/iterators.c [hunk 4]
```diff
@@ -1155,12 +1185,10 @@ PyArray_Broadcast(PyArrayMultiIterObject *mit)
...
                     mit->dimensions[i] = tmp;
+                    src_iter = j;
                 }
                 else if (mit->dimensions[i] != tmp) {
-                    PyErr_SetString(PyExc_ValueError,
-                                    "shape mismatch: objects" \
-                                    " cannot be broadcast" \
-                                    " to a single shape");
+                    set_shape_mismatch_exception(mit, src_iter, j);
                     return -1;
```
Comment (seberg) [inline numpy/core/src/multiarray/iterators.c:1192]: Could also `return set_shape_mismatch_exception(mit, src_iter, j);` and always return `-1`.

**Review by seberg — APPROVED** [review]
I don't want to be nailed down on this including the `src_iter` for all eternity (the approach nditer takes may make it harder to provide it I think).  But it is a big improvement to report mismatching shapes!

Otherwise, just some nits/suggestions that are not really important.
