### PR TITLE
MAINT: refactor PyArray_ArgSort and PyArrayArgPartition

### LINKED ISSUE #5469: BUG: partition and argpartition don't bound check kth for some types
For dtypes that do not have a type specific implementation of the introselect algorithm, both `partition` and `argpartition` resort to fully (arg)sorting the input array. When doing so, the `kth` array of elements to partition by is not bound checked:

```
>>> a = np.arange(10)
>>> a.partition(17)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: kth(=17) out of bounds (10)
>>> a.argpartition(17)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: kth(=17) out of bounds (10)

>>> b = np.array(range(10), dtype=object)
>>> b.partition(17)
>>> b.argpartition(17)
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

### PR DESCRIPTION
**Pull request by jaimefrio**
Added three new functions to npy_sort: npy_aquicksort, npy_aheapsort
and npy_amergesort, for generic dtypes, with signature compatible with
PyArray_ArgSortFunc, and refactored PyArray_ArgSort and
PyArray_ArgPartition to use them through a call to _new_argsortlike.

As an added bonus, partly fixes #5469 and adds some tests for it.

### CODE REVIEW

File: numpy/core/src/private/npy_sort.h [hunk 1]
```diff
@@ -190,5 +190,8 @@ int amergesort_timedelta(npy_timedelta *vec, npy_intp *ind, npy_intp cnt, void *
 int npy_quicksort(void *base, size_t num, size_t size, npy_comparator cmp);
 int npy_heapsort(void *base, size_t num, size_t size, npy_comparator cmp);
 int npy_mergesort(void *base, size_t num, size_t size, npy_comparator cmp);
```
Comment (charris) [inline numpy/core/src/private/npy_sort.h]: Might be worth using the same signature for both. I think we are safe for structured types, etc, as the arrays are created with new comparators.

File: numpy/core/src/npysort/quicksort.c.src [hunk 2]
```diff
@@ -361,3 +361,81 @@ npy_quicksort(void *base, size_t num, size_t size, npy_comparator cmp)
     qsort(base, num, size, cmp);
     return 0;
 }
+
+
+int
+npy_aquicksort(char *v, npy_intp* tosort, npy_intp num, PyArrayObject *arr)
+{
+    npy_intp elsize = PyArray_ITEMSIZE(arr);
+    PyArray_CompareFunc *cmp = PyArray_DESCR(arr)->f->compare;
```
Comment (charris) [inline numpy/core/src/npysort/quicksort.c.src]: I forget. Is this a `cmp` or a `rich_compare`?

**Comment by charris** [comment]
I didn't realize that the generic argsorts were not done. At first glance this looks OK to me, I'll take a closer look tomorrow.

File: numpy/core/src/npysort/heapsort.c.src [hunk 3]
```diff
@@ -343,3 +343,54 @@ npy_heapsort(void *base, size_t num, size_t size, npy_comparator cmp)
...
     return 0;
 }
+
+
+int
+npy_aheapsort(char *v, npy_intp *tosort, npy_intp n, PyArrayObject *arr)
+{
+    npy_intp elsize = PyArray_ITEMSIZE(arr);
+    PyArray_CompareFunc *cmp = PyArray_DESCR(arr)->f->compare;
+    npy_intp *a, i,j,l, tmp;
```
Comment (charris) [inline numpy/core/src/npysort/heapsort.c.src]: Space after `,`.

File: numpy/core/src/npysort/heapsort.c.src [hunk 4]
```diff
@@ -343,3 +343,54 @@ npy_heapsort(void *base, size_t num, size_t size, npy_comparator cmp)
...
+        a[i] = tmp;
+    }
+
+    for (; n > 1;) {
+        tmp = a[n];
+        a[n] = a[1];
+        n -= 1;
+        for (i = 1, j = 2; j <= n;) {
+            if (j < n && cmp(v + a[j]*elsize, v + a[j+1]*elsize, arr) < 0)
+                ++j;
```
Comment (charris) [inline numpy/core/src/npysort/heapsort.c.src]: Need braces.

**Comment by charris** [comment]
LGTM modulo a couple of style nitpicks. This is a good start on getting the sort stack cleaned up.

File: numpy/core/src/npysort/quicksort.c.src (hunk 2 above)
Comment (jaimefrio) [inline numpy/core/src/npysort/quicksort.c.src]: For object types, in Python3 it is implemented with two calls to `PyObject_RichCompareBool`, but unless an error is raised it behaves like a compare establishing an ordering. The source is [here](https://github.com/numpy/numpy/blob/maintenance/1.9.x/numpy/core/src/multiarray/arraytypes.c.src#L2590). If an error is raised I think it mistakenly thinks both items compared equal, but the error is caught an raised in `_new_argsortlike`.

File: numpy/core/src/private/npy_sort.h (hunk 1 above)
Comment (jaimefrio) [inline numpy/core/src/private/npy_sort.h]: Which ones are the "both"? I don't think I understand... :-/

**Comment by jaimefrio** [comment]
Have fixed the style, not sure I understand the comment on "same signature" though. Well, I am actually sure: I don't understand it. ;-)

**Comment by charris** [comment]
Not sure I understand it myself ;) What I was thinking was passing the array object instead of the comparison function. The only way these functions are currently exposed is in the `PyArray_ArrFuncs` struct and they seem to get called through the Numpy API, so I think we can safely fool with the signatures without compatibility problems. Maybe we could even hide the PyArray_ArrFunc tables which would allow us to do many things.

**Comment by charris** [comment]
Thanks Jaime.

**Comment by jaimefrio** [comment]
Part of that will come with the refactoring of `PyArray_Sort` and `PyArray_Partition`, soon to follow this one. We can discuss the details there.. But yes, adding a `get_sort_func` and `get_argsort_func` to `npy_sort`, similarly to how `partition` and `searchsorted` do it, would be the way to add a `NPY_SMALLSORT` and potentially a `NPY_TIMSORT` option without breaking ABI compatibility.
