### PR TITLE
BUG: Fix missing NPY_VISIBILITY_HIDDEN on npy_longdouble_to_PyLong

### LINKED ISSUE #10648: BUG: Relocation R_X86_64_PC32 against `npy_longdouble_to_PyLong' can not be used when making a shared object; recompile with -fPIC
I can't really share my build setup, but it's not windows like it usually is. I get the error:
```
numpy/core/src/multiarray/scalartypes.o: relocation R_X86_64_PC32 against `npy_longdouble_to_PyLong' can not be used when making a shared object; recompile with -fPIC
```

This looks like it was a bug I introduced in #9971.

### PR DESCRIPTION
**Pull request by eric-wieser**
Fixes #10648, regression in #9971

NPY_VISIBILITY_HIDDEN is used by memoverlap.{c,h}, so we should be using the same thing here

CircleCI fails because this is based on the commit that introduced the regression

### CODE REVIEW

File: numpy/core/src/private/npy_longdouble.h [hunk 1]
```diff
@@ -11,7 +11,7 @@
  * This performs the same task as PyLong_FromDouble, but for long doubles
  * which have a greater range.
  */
-NPY_NO_EXPORT PyObject *
+NPY_VISIBILITY_HIDDEN PyObject *
```
Comment (eric-wieser) [inline numpy/core/src/private/npy_longdouble.h]: These two things are synonymous, but this makes it match `memoverlap.c`

**Comment by charris** [comment]
Thanks Eric.
