### PR TITLE
BUG: fix datetime/timedelta hash memory leak

### LINKED ISSUE #29397: BUG: Memory leak running hash() on np.datetime64 object
### Describe the issue:

Memory leak, when calling hash() on np.datetime64 instance that is non-empty. gc.collect() does not free memory, no ref counts to python objects leaks found with objgraph library, using show_growth(). Seems the leak is on the C side, possibly in  https://github.com/numpy/numpy/blob/d02611ad99488637b48f4be203f297ea7b29c95d/numpy/_core/src/multiarray/datetime.c#L2832 tracemalloc points at the hash() call.

### Reproduce the code example:

```python
import numpy as np
#dtObj = np.datetime64() #no leak with empty object
dtObj = np.datetime64(10, "Y")
while True:
    hash(dtObj) #leaks here
    print("leak")
```

### Error message:

```shell

```

### Python and NumPy Versions:

Python 3.13.3, numpy 2.2.6

### Runtime Environment:

```
[{'numpy_version': '2.2.6',
  'python': '3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 '
            '64 bit (AMD64)]',
  'uname': uname_result(system='Windows', release='10', version='10.0.17763', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'filepath': 'C:\\Program '
              'Files\\Python\\Python313\\Library\\bin\\libiomp5md.dll',
  'internal_api': 'openmp',
  'num_threads': 6,
  'prefix': 'libiomp',
  'user_api': 'openmp',
  'version': None},
 {'filepath': 'C:\\Program '
              'Files\\Python\\Python313\\Library\\bin\\mkl_rt.2.dll',
  'internal_api': 'mkl',
  'num_threads': 6,
  'prefix': 'mkl_rt',
  'threading_layer': 'intel',
  'user_api': 'blas',
  'version': '2025.1-Product'}]
```

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by kostayScr**
Fixes lack of a Py_DECREF() call in the datetime/timdelta hash function. Closes #29397.

### CODE REVIEW

File: numpy/_core/src/multiarray/scalartypes.c.src [hunk 1]
```diff
@@ -3922,7 +3922,9 @@ static npy_hash_t
     dtype = PyArray_DescrFromScalar(obj);
     meta = get_datetime_metadata_from_dtype(dtype);
```
Comment (ngoldbaum) [inline numpy/_core/src/multiarray/scalartypes.c.src]: While we're at it, let's also fix two other bugs in this function. ~Both of these calls can fail, so we need to check for errors.~ EDIT: applied sebastian's suggestion.

```suggestion
    meta = &((PyDatetimeScalarObject *)obj)->obmeta;
```

**Review by ngoldbaum — COMMENTED** [review]
I noticed some preexisting issues with error handling and suggested a fix.

Also ping @walshb - FYI there were some error checking and reference counting bugs that were missed in the datetime/timedelta hash PR we merged last year.

File: numpy/_core/src/multiarray/scalartypes.c.src (hunk 1 above)
Comment (walshb) [reply numpy/_core/src/multiarray/scalartypes.c.src]: Oh yes, good spot! Thanks.

Comment (seberg) [reply numpy/_core/src/multiarray/scalartypes.c.src]: Actually, please just get the metadata directly from the scalar. Then it also cannot fail.

File: numpy/_core/src/multiarray/scalartypes.c.src [hunk 2]
```diff
@@ -3922,7 +3922,9 @@ static npy_hash_t
...
 
-    return @lname@_hash(meta, val);
+    npy_hash_t res = @lname@_hash(meta, val);
+    Py_DECREF(dtype);
```
Comment (ngoldbaum) [inline numpy/_core/src/multiarray/scalartypes.c.src]:
```suggestion
```

File: numpy/_core/src/multiarray/scalartypes.c.src (hunk 1 above)
Comment (ngoldbaum) [reply numpy/_core/src/multiarray/scalartypes.c.src]: good point! I edited my suggestion. @kostayScr if you're interested in getting this across the finish line, you'll need to apply my suggestions and also delete the now-unnecessary declaration of `dtype` outside the context of the PR, since I can't suggest that from the PR interface.

**Comment by kostayScr** [comment]
Seems to be in order.

File: numpy/_core/src/multiarray/scalartypes.c.src (hunk 1 above)
Comment (kostayScr) [reply numpy/_core/src/multiarray/scalartypes.c.src]: Thanks for explaining, will do.

**Comment by ngoldbaum** [comment]
Thanks for closing the loop on this @kostayScr. This will be backported to the 2.3 release branch and will be included in NumPy 2.3.2.

**Comment by scttstrck** [comment]
Is there any chance to get this back ported into the 2.2.x branch to fix usage with Python 3.10?

**Comment by seberg** [comment]
@scttstrck we could backport if it helps you, but we are not in the habit of making bug-fix releases for `2.n-1`, so by itself that would probably not be helpful?
