### PR TITLE
BUG: Fix np.clip bug NaN handling for Visual Studio 2015

### LINKED ISSUE #7601: [Windows Python 3.5 only] np.clip replace nans with lower bound
```python
import numpy as np

arr = np.array([np.nan, 10])
print(np.clip(arr, -1, 1))
```

Expected output is that nan are left untouched:
```
[ nan   1.]
```

Actual output with Python 3.5 on a Windows VM (numpy 1.11 installed through conda):
```
[-1.  1.]
```

It works as expected with Python 2.7 and 3.4 on the Windows VM. It works as expected with all Python versions on my Ubuntu box.

### PR DESCRIPTION
**Pull request by lesteve**
Fix #7601.

The work-around is to disable the loop vectorization for Visual studio 2015. Let me know if there is a better way to achieve the same results.

I added a test that highlights the issue (only python 3.5).

In a separate branch I made sure that the test was failing without the loop vectorization disabled: [AppVeyor build](https://ci.appveyor.com/project/lesteve/numpy/build/1.0.8).

and that disabling the loop vectorization fixed the problem: [AppVeyor build](https://ci.appveyor.com/project/lesteve/numpy/build/1.0.7).

### CODE REVIEW

**Comment by juliantaylor** [comment]
hm, the bug says this is supposed to be fixed in vs2015, is 1900 the 2015 version?

**Comment by lesteve** [comment]
> hm, the bug says this is supposed to be fixed in vs2015, is 1900 the 2015 version?

Short answer is yes.

Long answer: from https://msdn.microsoft.com/en-us/library/b0084kay.aspx about _MSC_VER:

> For example, if the version number of the Visual C++ compiler is 17.00.51106.1, the _MSC_VER macro evaluates to 1700. Type cl /? at the command line to view the compiler's version number.

cl /? in a Developer Command Prompt for VS2015 gives:
```
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23918 for x86
```

**Comment by juliantaylor** [comment]
but this disables vectorization for 2015 then which is supposed to be fixed.

**Comment by lesteve** [comment]
> but this disables vectorization for 2015 then which is supposed to be fixed.

Hmm, where do you get the impression that vectorization is supposed to be fixed in VS 2015? 

According to the ticket I opened at connect.microsoft.com [there](https://connect.microsoft.com/VisualStudio/feedback/details/2723801/unexpected-nan-handling-in-vectorized-loop), one person from Microsoft acknowledged that there was a bug in the latest version of the compiler:

> I’m sorry, after sending the previous message I saw that I didn’t test your repro accurately. I can repro the bug even in the latest version, so I am re-opening this Connect and will continue to investigate.

**Comment by juliantaylor** [comment]
> Thanks for the excellent bug report and repro. Fortunately, this bug was found and fixed and should be available from VS2015 and later versions; I tested your repro to confirm. So upgrading to the latest version of the compiler should address this issue.

**Comment by lesteve** [comment]
The message you copied and pasted was posted 40 minutes before mine. Confusingly the latest message is at the top in their bug tracker ...

**Comment by juliantaylor** [comment]
oh, that is a bit confusing.

Looks good then, thanks for investigating and reporting the issue.

**Comment by juliantaylor** [comment]
@charris probably worth a backport to 11.1, low risk and having it in a stable release soon  helps with appveyor tests of other projects

**Comment by lesteve** [comment]
> @charris probably worth a backport to 11.1, low risk and having it in a stable release soon helps with appveyor tests of other projects

That would be great indeed!

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 1]
```diff
@@ -3763,6 +3763,12 @@ static void
         }
     }
     else {
+// Visual Studio 2015 loop vectorizer handles NaN in an unexpected manner, see:
```
Comment (charris) [inline numpy/core/src/multiarray/arraytypes.c.src]: Need to fix the C++ comments. I'll do that.

**Comment by charris** [comment]
Microsoft report at https://connect.microsoft.com/VisualStudio/feedback/details/2723801/unexpected-nan-handling-in-vectorized-loop

**Comment by charris** [comment]
Does the pragma only apply to the following `for` loop, or are all loops after affected?

**Comment by Flamefire** [comment]
I have encountered a similar issue on POWER9 with GCC 9.3.0 and numpy 1.16.6 (Python 2) where GCC misoptimizes https://github.com/numpy/numpy/issues/7601#issuecomment-218704015 so it yields the upper bound on NaN at `-O1`
