### PR TITLE
BUG: non-integers can end up in dtype offsets

### LINKED ISSUE #8059: Error when offsets in construction of dtype are given as int32
When one constructs a dtype and gives the offsets as int32 (or int16), a subsequent use of the dtype leads to a crash.

The following example shows the construction of two dtypes: one with offsets as a list of python int's, the socond as a list of int32's.

```python
offsets1 = [0]
offsets2 = [np.int32(o) for o in offsets1]

dtype1 = np.dtype(dict(
    names=['f0'],
    itemsize=4,
    offsets=offsets1,
    formats=['u4']
))

dtype2 = np.dtype(dict(
    names=['f0'],
    itemsize=4,
    offsets=offsets2,
    formats=['u4']
))
```

When using the first dtype the result is as expected:

```python
>>> np.fromstring(b"\x00"*4, dtype1, count=1)
array([(0,)], 
      dtype=[('f0', '<u4')])
```

Using the second dtype leads to a crash:

```python
>>> np.fromstring(b"\x00"*4, dtype2, count=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anton/anaconda2/envs/py3/lib/python3.5/site-packages/numpy/core/numeric.py", line 1807, in array_repr
    ', ', "array(")
  File "/home/anton/anaconda2/envs/py3/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 447, in array2string
    separator, prefix, formatter=formatter)
  File "/home/anton/anaconda2/envs/py3/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 325, in _array2string
    _summaryEdgeItems, summary_insert)[:-1]
  File "/home/anton/anaconda2/envs/py3/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 496, in _formatArray
    word = format_function(a[-1])
  File "/home/anton/anaconda2/envs/py3/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 235, in repr_format
    return repr(x)
  File "/home/anton/anaconda2/envs/py3/lib/python3.5/site-packages/numpy/core/numeric.py", line 1869, in array_str
    return array2string(a, max_line_width, precision, suppress_small, ' ', "", str)
  File "/home/anton/anaconda2/envs/py3/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 438, in array2string
    x = a.item()
SystemError: <built-in method item of numpy.ndarray object at 0x7f5aab26d940> returned NULL without setting an error
```

Python Version: 3.5.2 |Anaconda 4.1.1 (64-bit)
Numpy Version: 1.11.1

### PR DESCRIPTION
**Pull request by ahaldane**
Fix is to convert offsets to python ints at dtype creation.
Fixes #8059

### CODE REVIEW

File: numpy/core/src/multiarray/descriptor.c [hunk 1]
```diff
@@ -1072,7 +1072,13 @@ _convert_from_dict(PyObject *obj, int align)
                 goto fail;
             }
             offset = PyInt_AsLong(off);
-            PyTuple_SET_ITEM(tup, 1, off);
+            if (PyErr_Occurred()) {
```
Comment (seberg) [inline numpy/core/src/multiarray/descriptor.c]: `if ((offset == -1) && PyErr_Occured()) {` avoids the check most of the time I think.

Comment (seberg) [inline numpy/core/src/multiarray/descriptor.c]: Two rather unrelated side points I am not sure about:
 1. What about floats, etc.? Maybe it would make sense to use the Index conversion stuff?
 2. Where do we check `int` size? We only support integer sized offsets (since dtype is limited to int).

Comment (ahaldane) [inline numpy/core/src/multiarray/descriptor.c]: what is the index conversion stuff? I don't think I'm familiar and searching didn't help.

Comment (ahaldane) [inline numpy/core/src/multiarray/descriptor.c]: also `PyInt_AsLong` takes care of floats etc

Comment (seberg) [inline numpy/core/src/multiarray/descriptor.c]: I mean our own (or the python version we mostly call there) NpyPyIntAsIntp (or whate it was), which specificially does not allow floats.

**Comment by ahaldane** [comment]
Got it, and updated. 

I also added a check that `offset` is positive - previously negative was allowed and I could read far back in memory! Also I made the conversion of `itemsize` safer.

**Comment by seberg** [comment]
Nice. Hmmmpff, I may have thought too little about my comments, though. At least if we want to backport this, the more strict integer conversion could be a regression (though maybe it cannot be, because this is almost always only called indirectly).

**Comment by ahaldane** [comment]
Anyone trying to use weird non-integer offsets would probably cause numpy to blow up in other ways ...probably.

Also, I checked and #8059 is not a new bug I introduced, it is old. I checked in 1.8.0 and 1.10.0 and the examples raise exceptions back then too.

Personally I would not worry about a backport, I think, since this is such an old and obscure oversight.

**Comment by seberg** [comment]
OK, then I think I am happy. Thanks.
