### PR TITLE
BUG: fix build issue on icc 2016

### LINKED ISSUE #14059: NumPy 1.17 RC fails to compile with Intel C Compile 2016
Compiling NumPy 1.17.0rc2 sources with Intel C Compiler 2016, which does not yet implement `__builtin_cpu_supports("avx512f")` fails with compilation error:

```
icc: numpy/core/src/umath/cpuid.c
numpy/core/src/umath/cpuid.c(63): catastrophic error: invalid use of '__builtin_cpu_supports'
compilation aborted for numpy/core/src/umath/cpuid.c (code 1)
```

Recent Intel C compiler (2019) proceeds just fine.

There is config test to probe compiler for support of `__builtin_cpu_supports`, but the the test does not discriminate between supported arguments.

### PR DESCRIPTION
**Pull request by r-devulap**
Fixes #14059: Test if compiler supports _builtin_supports("avx512f") before calling it

### CODE REVIEW

File: numpy/core/src/umath/cpuid.c [hunk 1]
```diff
@@ -57,10 +57,10 @@ npy_cpu_supports(const char * feature)
 {
 #ifdef HAVE___BUILTIN_CPU_SUPPORTS
     if (strcmp(feature, "avx512f") == 0) {
-#if defined(__GNUC__) && (__GNUC__ < 5)
```
Comment (charris) [inline numpy/core/src/umath/cpuid.c]: Do we still need this? I don't see it checked elsewhere.

Comment (r-devulap) [reply numpy/core/src/umath/cpuid.c]: not really, that line existed for the same reason as the bug this PR is fixing. GCC < 5 didn't support `__builtin_cpu_supports("avx512f")`. The preprocessor macro `HAVE___AVX512F_BUILTIN_CPU_SUPPORTS `handles that now.

**Comment by charris** [comment]
Have you been able to verify that this fixes the problem?

**Comment by r-devulap** [comment]
Pretty sure it should fix it, but safer if @oleksandr-pavlyk could test it out at his end and confirm.

**Comment by oleksandr-pavlyk** [comment]
Yes, this fixes the compilation breakage. I actually made the same commit locally independently, but named the preprocessor variable `HAVE__BUILTIN_CPU_SUPPORTS_AVS512F`. I think it is more consistent. 

Thank you for the fix, @r-devulap

**Comment by charris** [comment]
@oleksandr-pavlyk I like that better.

**Comment by r-devulap** [comment]
fixed the name.

**Comment by charris** [comment]
Thanks @r-devulap .
