### PR TITLE
MAINT: Adjust NumPy float hashing to Python's slightly changed hash

### LINKED ISSUE #18833: Possible excessive hash collisions from hash of nan
A potential performance issue relating to hash collisions from distinct NaNs was recently [reported and fixed](https://bugs.python.org/issue43475) in core Python. In brief, the fact that all NaNs hash to `0` makes it easy to accidentally invoke quadratic-time behaviour from NaNs going into a set or dictionary. The fix involved changing the hash of a `float` NaN to match the usual object hash.

The core issue affects NumPy, too (and in fact one of the examples given in the Python bug report to demonstrate the issue used `np.float64` rather than `float`); NumPy may want to consider changing the hash of floating-point NaNs, both to address the potential performance issue, and to remain compatible with  Python.

### Reproducing code example:

The following code takes several hours to execute on my machine:

```python
>>> import collections, numpy as np
>>> x = np.full(1000000, np.nan)
>>> c = collections.Counter(x)
```

The cause is that (a) the `float64` NaN objects realised from the array all have distinct `id`, and so are considered unequal for the purposes of dict and set membership, together with (b) all of those NaNs have the same hash value of `0`. Then we get a perfect storm of hash collisions while building the dictionary underlying the `Counter` object.

### NumPy/Python version information:

```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.20.2 3.9.4 (default, Apr  6 2021, 11:23:37) 
[Clang 11.0.3 (clang-1103.0.32.62)]
```

### PR DESCRIPTION
**Pull request by seberg**
This is necessary, since we use the Python double hash and the
semi-private function to calculate it in Python has a new signature
to return the identity-hash when the value is NaN.

closes gh-18833, gh-18907

---

It seems we had no tests at all, so I added some.  I honestly did *not* test this on 3.10b1, since I did not  yet bother to get a Py 3.10 version running locally.

### CODE REVIEW

**Comment by seberg** [comment]
OK, I did compile against dev python (which includes the patch) and it works.  (I did not run the test suit)

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 1]
```diff
@@ -3172,22 +3172,20 @@ static npy_hash_t
...
 }
 
 /* borrowed from complex_hash */
 static npy_hash_t
 c@lname@_arrtype_hash(PyObject *obj)
 {
     npy_hash_t hashreal, hashimag, combined;
-    hashreal = _Py_HashDouble((double)
-            PyArrayScalar_VAL(obj, C@name@).real);
+    hashreal = Npy_HashDouble(obj, (double)PyArrayScalar_VAL(obj, C@name@).real);
```
Comment (charris) [inline numpy/core/src/multiarray/scalartypes.c.src:3183]: This is a hair long.

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 2]
```diff
@@ -3159,7 +3159,7 @@ static npy_hash_t
     return y;
 }
 #endif
-/**end repeat**/
+/**end repeat**/y
```
Comment (charris) [inline numpy/core/src/multiarray/scalartypes.c.src:3162]: Stray `y`?

Comment (charris) [reply numpy/core/src/multiarray/scalartypes.c.src:3162]: Probably disappears when the file is generated, so no error.

**Comment by charris** [comment]
Nitpicks: Couple of long lines in C code.

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 1 above)
Comment (seberg) [reply numpy/core/src/multiarray/scalartypes.c.src:3183]: yeah, how strict are we about the 79 chars? Lately, I have started to not worry if it I figure the meaning is clear even if you don't see the last few chars.

Happy to change though.

Comment (charris) [reply numpy/core/src/multiarray/scalartypes.c.src]: We aren't limited by the terminal these days, so we could probably increase the line length as long as readability is good, say 85 characters. Might be worth discussing, especially with C++ in the future, C++ tends to long lines.

**Comment by charris** [comment]
Thanks Sebastian.
