### PR TITLE
BUG: handle case when StringDType na_object is nan in float to string cast

### LINKED ISSUE #28157: BUG: `StringDType`: `na_object` ignored in `full`
### Describe the issue:

Creating a `StringDType` ndarray with `na_object` using `full` (and `full_like`) coerces the `nan` sentinel to a string. 

I can work around this using `arr[:] = np.nan`, but think the behavior is unexpected.

### Reproduce the code example:

```python
import numpy as np

arr1 = np.full((1,), fill_value=np.nan, dtype=np.dtypes.StringDType(na_object=np.nan))

arr2 = np.full_like(arr1, fill_value=np.nan)

assert arr1.item() is np.nan
assert arr2.item() is np.nan
```

### Error message:

```python traceback
Traceback (most recent call last):
  File "/Users/goldbaum/Documents/numpy/../numpy-experiments/test.py", line 7, in <module>
    assert arr1.item() is np.nan
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

### Python and NumPy Versions:

2.2.1
3.12.8 | packaged by conda-forge | (main, Dec  5 2024, 14:24:40) [GCC 13.3.0]

### Runtime Environment:

[{'numpy_version': '2.2.1',
  'python': '3.12.8 | packaged by conda-forge | (main, Dec  5 2024, 14:24:40) '
            '[GCC 13.3.0]',
  'uname': uname_result(system='Linux', node='poisson', release='6.8.0-51-generic', version='#52~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Dec  9 15:00:52 UTC 2', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL',
                                    'AVX512_SPR']}},
 {'architecture': 'Haswell',
  'filepath': '/home/mathause/.conda/envs/regionmask_dev/lib/libopenblasp-r0.3.28.so',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.28'}]

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes #28157.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Unfortunately I don't think this can be easily backported without re-doing the PR inside the macro in the `casts.c.src` file that used to implement this operation. If anyone wants to do that, feel free, but given that this can be worked around I don't mind waiting for 2.3 to release this fix.

File: numpy/_core/src/multiarray/stringdtype/casts.cpp [hunk 1]
```diff
@@ -1208,14 +1208,35 @@ float_to_string(
...
+            }
+            if (na_cmp) {
+                Py_DECREF(scalar_val);
+                if (NpyString_pack_null(allocator, (npy_packed_static_string *)out) < 0) {
+                    PyErr_SetString(PyExc_MemoryError,
+                                    "Failed to pack null string during float "
+                                    "to string cast");
+                    goto fail;
+                }
+                goto next_step;
```
Comment (mhvk) [inline numpy/_core/src/multiarray/stringdtype/casts.cpp:1231]: I'd tend to just move the old code into an `else {` clause and thus avoid the `goto` here.

**Review by mhvk — APPROVED** [review]
Looks good. I only have a nitpick for the implementation, so approving.
