### PR TITLE
BUG: Fix use-after-free in boolean indexing

### LINKED ISSUE #13714: Use-after-free in boolean indexing with list
Valgrind reports a use-after-free when running the following code.

I can see where the error is coming from and will submit a patch.

### Reproducing code example:

```python
import numpy as np

np.zeros((1, 3))[..., [True, False, True]]
```

Run with `PYTHONMALLOC=malloc valgrind --log-file=memcheck.log python bool-idx.py`

### Error message:

Relevant Valgrind message:
```
==15177== Invalid read of size 8
==15177==    at 0x7036339: PyArray_DIM (ndarraytypes.h:1502)
==15177==    by 0x7036339: prepare_index (mapping.c:634)
==15177==    by 0x7039633: array_subscript (mapping.c:1600)
==15177==    by 0x506B38: _PyEval_EvalFrameDefault (in /home/bmerry/tmp/ve3/bin/python3)
==15177==    by 0x504C27: ??? (in /home/bmerry/tmp/ve3/bin/python3)
==15177==    by 0x506392: PyEval_EvalCode (in /home/bmerry/tmp/ve3/bin/python3)
==15177==    by 0x634D51: ??? (in /home/bmerry/tmp/ve3/bin/python3)
==15177==    by 0x634E09: PyRun_FileExFlags (in /home/bmerry/tmp/ve3/bin/python3)
==15177==    by 0x6385C7: PyRun_SimpleFileExFlags (in /home/bmerry/tmp/ve3/bin/python3)
==15177==    by 0x639159: Py_Main (in /home/bmerry/tmp/ve3/bin/python3)
==15177==    by 0x4A6F0F: main (in /home/bmerry/tmp/ve3/bin/python3)
==15177==  Address 0x1914a510 is 32 bytes inside a block of size 80 free'd
==15177==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15177==    by 0x703661B: prepare_index (mapping.c:614)
==15177==    by 0x7039633: array_subscript (mapping.c:1600)
==15177==    by 0x506B38: _PyEval_EvalFrameDefault (in /home/bmerry/tmp/ve3/bin/python3)
==15177==    by 0x504C27: ??? (in /home/bmerry/tmp/ve3/bin/python3)
==15177==    by 0x506392: PyEval_EvalCode (in /home/bmerry/tmp/ve3/bin/python3)
==15177==    by 0x634D51: ??? (in /home/bmerry/tmp/ve3/bin/python3)
==15177==    by 0x634E09: PyRun_FileExFlags (in /home/bmerry/tmp/ve3/bin/python3)
==15177==    by 0x6385C7: PyRun_SimpleFileExFlags (in /home/bmerry/tmp/ve3/bin/python3)
==15177==    by 0x639159: Py_Main (in /home/bmerry/tmp/ve3/bin/python3)
==15177==    by 0x4A6F0F: main (in /home/bmerry/tmp/ve3/bin/python3)
==15177==  Block was alloc'd at
==15177==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15177==    by 0x6F49D61: array_alloc (arrayobject.c:1767)
==15177==    by 0x6FAB301: PyArray_NewFromDescr_int (ctors.c:1003)
==15177==    by 0x6FAEEBF: PyArray_NewFromDescrAndBase (ctors.c:1181)
==15177==    by 0x6FAEEBF: PyArray_NewFromDescr (ctors.c:1166)
==15177==    by 0x6FAEEBF: PyArray_FromAny (ctors.c:1877)
==15177==    by 0x7036403: prepare_index (mapping.c:514)
==15177==    by 0x7039633: array_subscript (mapping.c:1600)
==15177==    by 0x506B38: _PyEval_EvalFrameDefault (in /home/bmerry/tmp/ve3/bin/python3)
==15177==    by 0x504C27: ??? (in /home/bmerry/tmp/ve3/bin/python3)
==15177==    by 0x506392: PyEval_EvalCode (in /home/bmerry/tmp/ve3/bin/python3)
==15177==    by 0x634D51: ??? (in /home/bmerry/tmp/ve3/bin/python3)
==15177==    by 0x634E09: PyRun_FileExFlags (in /home/bmerry/tmp/ve3/bin/python3)
==15177==    by 0x6385C7: PyRun_SimpleFileExFlags (in /home/bmerry/tmp/ve3/bin/python3)
```

I tracked this down because a production system was occasionally reporting errors like this, although I've not seen it from this test.
```
IndexError: boolean index did not match indexed array along dimension 1; dimension is 1225 but corresponding boolean dimension is 94868053792976
```

### Numpy/Python version information:

```
1.16.4 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
```

It's been around since at least 1.15.3.

### PR DESCRIPTION
**Pull request by bmerry**
The index array is decrefed before extracting the shape to construct the
`indices` array. If the caller does not hold a reference (which happens
when the caller passed a list from which a temporary array was
constructed, for example), this leads to a use-after-free.

Closes #13714.

### CODE REVIEW

File: numpy/core/src/multiarray/mapping.c [hunk 1]
```diff
@@ -624,6 +624,7 @@ prepare_index(PyArrayObject *self, PyObject *index,
                 for (i=0; i < n; i++) {
                     Py_DECREF(nonzero_result[i]);
                 }
+                Py_DECREF(arr);
                 goto failed_building_indices;
```
Comment (bmerry) [inline numpy/core/src/multiarray/mapping.c]: Incidentally, are there any race concerns with putting a `Py_DECREF` after the `PyErr_SetString`? I don't use the C API much, but I vaguely recall admonishments that any time you decref it can allow Python to be re-entered via finalizers. I put it here for now to be next to the other decref.

**Comment by bmerry** [comment]
I haven't added a regression test since I don't have a way to reliably reproduce the bug. I couldn't see if there is any automated run of valgrind (which would detect the bug).

File: numpy/core/src/multiarray/mapping.c (hunk 1 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/mapping.c]: I think this should be fine, finalizers stash exceptions that are currently in flight while they are running.

**Review by eric-wieser — APPROVED** [review]
Looks correct, thanks. I agree that there's no way you can really test this.

**Comment by seberg** [comment]
@bmerry, it must be a code path we never tested though, even if a fringe one. A regression test would be much appreciated. Me (and others) do run the test suit through valgrind fairly regularly, and certainly before a release. So we have a few tests which will only show visible errors within valgrind (or in this case maybe also a python debug build).

Thanks so much for tracking this down!

**Comment by seberg** [comment]
Hehe, I see Eric is fine without a test as well. I won't press on it if it does not seem pretty to you.

**Comment by bmerry** [comment]
@seberg I can add a test tomorrow. Can you tell me what command you use to run the tests under valgrind, so that I can verify the test before and after the fix is applied?

**Comment by seberg** [comment]
I usually just use something lke:
```
PYTHONMALLOC=malloc valgrind python3 runtests.py -vv -g -- --continue-on-collection-errors
```
You will want to add the `-t test_file_to_run` after the `-g`. The `-- --continue-on-collection-errors` is not necessary for most files, but in general it is.

I once started on some other machinery, to make it real tests, but there is not much point. There are 1 or two tests that are known to cause warnings in errors (at least one is marked, but it should be in a different file anyway).

**Comment by bmerry** [comment]
I've pushed a test, and confirmed that when run without the fix it triggers the use-after-free warning from valgrind.

**Comment by seberg** [comment]
Thanks a lot @bmerry!
