### PR TITLE
BUG: Ensure equality/identity comparison with `__array_function__`

### LINKED ISSUE #21033: BUG: `np.full` with `like` argument does not trigger `__array_function__` interface
### Describe the issue:

Calling `np.full(shape, x, like=x)` seems to try to trigger the __array_function__ interface, but is not found in the class that implements it. Am I missing something ?

### Reproduce the code example:

```python
import numpy as np
class Toto():
    
    def __init__(self, value):
        self.value = value
        
    def __array_function__(self, func, types, args, kwargs):
        if func not in HANDLED_FUNCTIONS:
            return NotImplemented
        return HANDLED_FUNCTIONS[func](*args, **kwargs)
    
HANDLED_FUNCTIONS = {}

def wrapped_sum(x, *args, **kwargs):
    return Toto(np.sum(x.value, *args, **kwargs))

def wrapped_full(shape, x, *args, **kwargs):
    return Toto(np.full(shape, x.value, *args, **kwargs))

HANDLED_FUNCTIONS[np.sum] = wrapped_sum
HANDLED_FUNCTIONS[np.full] = wrapped_full

print(np.sum(Toto([1, 2, 3]))) # works as expected
print(np.full((3,3), Toto(28), like=Toto(28))) # raise TypeError no implementation found for 'numpy.full' on types that implement __array_function__: [<class '__main__.Toto'>]
```

### Error message:

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/5k/bf4syt7x1zjbhc6b28srzzym0000gn/T/ipykernel_57970/4259881689.py in <module>
     28 
     29 print(np.sum(Toto([1, 2, 3])))
---> 30 print(np.full((3,3), Toto(28), like=Toto(28)))

/opt/anaconda3/lib/python3.9/site-packages/numpy/core/numeric.py in full(shape, fill_value, dtype, order, like)
    336     """
    337     if like is not None:
--> 338         return _full_with_like(shape, fill_value, dtype=dtype, order=order, like=like)
    339 
    340     if dtype is None:

<__array_function__ internals> in full(*args, **kwargs)

TypeError: no implementation found for 'numpy.full' on types that implement __array_function__: [<class '__main__.Toto'>]
```

### NumPy/Python version information:

1.21.4 3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ]

### PR DESCRIPTION
**Pull request by pentschev**
Special-casing is needed to ensure the correct public API is passed to `__array_function__` when `like=` kwarg is present.

Fixes #21033 .

### CODE REVIEW

File: numpy/core/src/multiarray/arrayfunction_override.c [hunk 1]
```diff
@@ -357,11 +358,24 @@ array_implement_array_function(
...
+     * If `like=` kwarg was removed, `implementation` points to the NumPy
+     * public API, as `public_api` is in that case the wrapper dispatcher
+     * function. For example, in the `np.full` case, `implementation` is
+     * `np.full`, whereas `public_api` is `_full_with_like`. This is done
+     * to ensure `__array_function__` implementations can do equality/identity
+     * comparisons when `like=` is present.
+     */
+    if (like_removed)
+        res = array_implement_array_function_internal(
+            implementation, relevant_args, args, kwargs);
```
Comment (seberg) [inline numpy/core/src/multiarray/arrayfunction_override.c:375]: Could you add braces, we always put them in NumPy.

This is a surprisingly small change!  Could also use `public_api = implementation` with a comment above, but this is OK with me.  I do wonder a bit if it might not be nicer to handle this differently, but so long we have the special case here to drop `like`, I agree that this is completely fine.

Thanks!

**Comment by seberg** [comment]
Agreed, this is a great practical (and minimal) solution as long as we have this `like=` special case here.  Will put in once the tests path, thanks.

I suppose we could backport it, but I doubt it is super important.

**Comment by pentschev** [comment]
> I suppose we could backport it, but I doubt it is super important.

I'll leave that up to you, it's not important for CuPy and Dask at least, not sure about other use cases.

**Comment by pentschev** [comment]
And thanks for review and merging @seberg !
