### PR TITLE
BUG: Use ``__array__`` during dimension discovery

### LINKED ISSUE #13958: Regression: Change in behaviour for `np.array()` on class that defines __array__
An issue has been raised for numpy 1.17rc in astropy (https://github.com/astropy/astropy/issues/8976), which after a bit of digging boils down to the change below in bahaviour for classes that define `__array__` as well as a `__len__` and `__getitem__`. I must admit I think the behaviour in both cases is strange, as it doesn't simply use `__array__` but rather seems to iterate, but the behaviour in 1.17 definitely makes (even) less sense than that in 1.16.

```
import numpy as np
class A:
    """A recarray mimic in which one indexes items by order not name"""
    def __init__(self, item):
        self.item = item
    def __array__(self, dtype=None):
        return self.item
    def __len__(self):
        return len(self.item.dtype.names)
    def __getitem__(self, item):
        return self.item[self.item.dtype.names[item]]

dtype = np.dtype([('a', 'f'), ('b', 'i')])
rec1 = A(np.array((1., 1), dtype=dtype))
rec2 = A(np.array((2., 2), dtype=dtype))
np.array([rec1, rec2], dtype=object)
# numpy 1.16
# array([[array(1., dtype=float32), array(1, dtype=int32)],
#        [array(2., dtype=float32), array(2, dtype=int32)]], dtype=object)
# numpy 1.17rc
# array([[(1.0, 1), (1.0, 1)],
#        [(2.0, 2), (2.0, 2)]], dtype=object)
```
Note that the following do not depend on version:
```
len(rec1)
# 2
rec1[0]
# array(1., dtype=float32)
np.array(rec1)
# array((1., 1), dtype=[('a', '<f4'), ('b', '<i4')])
```

### PR DESCRIPTION
**Pull request by seberg**
``__array__`` was previously not used during dimension discovery,
while bein gused during dtype discovery (if dtype is not given),
as well as during filling of the resulting array.

This would lead to inconsistencies with respect to array likes
that have a shape including a 0 (typically as first dimension).
Thus a shape of ``(0, 1, 1)`` would be found as ``(0,)`` because
a nested list/sequence cannot represent empty shapes, except 1-D.

This uses the `_array_from_array_like` function, which means that
some coercions may be tiny bit slower, at the gain of removing
a lot of complex code.

(this also reverts commit d0d250a3c9d7d90e75701c32d7d435640e6b02eb)

Closes gh-13958

---

I am a bit confused as to why I thought before that just adding `__array__` would not simply solve this. I think it does. I could add the use of `_array_from_array_like` in `common.h` during dtype discovery.

Note that this changes behaviour, so testing against pandas may be in order. And I suppose it needs a release note, I will probably add those tonight.

### CODE REVIEW

File: numpy/core/src/multiarray/ctors.c [hunk 1]
```diff
@@ -513,29 +513,28 @@ setArrayFromSequence(PyArrayObject *a, PyObject *s,
         goto fail;
     }
 
-    slen = PySequence_Length(s);
-    if (slen < 0) {
+    /* Try __array__ before using s as a sequence */
+    PyObject *tmp = _array_from_array_like(
+            s, /*dtype*/ NULL, /*writeable*/ 0, /*context*/ NULL);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/ctors.c]: nit: Tempting to change this to match the other call exactly, either as `_array_from_array_like(obj, NULL, NPY_FALSE, NULL);` here or this way there.

Comment (seberg) [reply numpy/core/src/multiarray/ctors.c]: Sure, presonally I now use an IDE which actually adds hints for the names here, giving it double...

File: numpy/core/src/multiarray/ctors.c [hunk 2]
```diff
@@ -782,108 +781,32 @@ discover_dimensions(PyObject *obj, int *maxndim, npy_intp *d, int check_it,
         return 0;
     }
 
-    /* obj is a PEP 3118 buffer */
-    /* PEP 3118 buffer interface */
-    if (PyObject_CheckBuffer(obj) == 1) {
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/ctors.c]: Does the removal of this indicate that it gets checked anyway as part of the `_array_from_array_like` code path?

If so, does this fix the dtype inference from a list of ctypes? I'll try and find the issue...

Comment (eric-wieser) [reply numpy/core/src/multiarray/ctors.c]: #13628

Comment (seberg) [reply numpy/core/src/multiarray/ctors.c]: Thanks, I have to run some errands, but will look at it. That might be a reason for just doing the simple thing and using it in the dtype discovery as well.

File: numpy/core/src/multiarray/ctors.c [hunk 3]
```diff
@@ -782,108 +781,32 @@ discover_dimensions(PyObject *obj, int *maxndim, npy_intp *d, int check_it,
...
-        if (nd >= 0) {
-            return 0;
-        }
-    }
-    else if (PyErr_Occurred()) {
-        PyErr_Clear(); /* TODO[gh-14801]: propagate crashes during attribute access? */
     }
+    else if (e != NULL) {
+        /*
+         * This branch is identical to the array one above except for using e
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/ctors.c]: Can you extract the bit that is the same to a helper function?
```python
void _discover_dimensions_array(PyArrayObject *att, int *maxndim, npy_intp *d) {
    int i;
    if (PyArray_NDIM(arr) < *maxndim) {
        *maxndim = PyArray_NDIM(arr);
    }
    for (int i = 0; i < *maxndim; i++) {
        d[i] = PyArray_DIM(arr,i);
    }
}
````
Making this just
```python
_discover_dimensions_array((PyArrayObject *)e, maxndim, d);
Py_DECREF(e);
return 1;
```

File: numpy/core/src/multiarray/ctors.c (hunk 1 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/ctors.c]: I've seen a former coworker use that before, it looked pretty cool

**Comment by eric-wieser** [comment]
Is a backport intended here?

**Comment by charris** [comment]
> Is a backport intended here?

There was already a reversion in 1.17, but not in master. I had a reversion for the 1.18 release, but it was defective. This fixes the failed reversion with a new approach for 1.18.

File: numpy/core/src/multiarray/ctors.c (hunk 2 above)
Comment (seberg) [reply numpy/core/src/multiarray/ctors.c]: Hmm, no. If I plug that in into the dtype discovery, all that changes is that the warning is given more times...

Comment (eric-wieser) [reply numpy/core/src/multiarray/ctors.c]: The warning is expected - but you still get the `ValueError`?

Comment (seberg) [reply numpy/core/src/multiarray/ctors.c]: Yeah

File: numpy/core/src/multiarray/ctors.c [hunk 4]
```diff
@@ -782,111 +783,24 @@ discover_dimensions(PyObject *obj, int *maxndim, npy_intp *d, int check_it,
...
-                        PyErr_SetString(PyExc_RuntimeError,
-                                "Invalid shape in __array_interface__");
-                        Py_DECREF(e);
-                        return -1;
-                    }
-                }
-            }
-        }
+    else if (e != NULL) {
+        _discover_dimensions_array((PyArrayObject *)obj, maxndim, d);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/ctors.c]: Shouldn't this be `e` not `obj`?
```suggestion
        _discover_dimensions_array((PyArrayObject *)e, maxndim, d);
```

Comment (seberg) [reply numpy/core/src/multiarray/ctors.c]: That explains why I now have an issue when running the pandas test suit, har...

File: numpy/core/src/multiarray/ctors.c (hunk 2 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/ctors.c]: > Does the removal of this indicate that it gets checked anyway as part of the `_array_from_array_like` code path?

Just checked, this does take the other code path. It's a little slower because it constructs the full array for PEP3118 types, but its still O(1), and if we can get caching working then that won't matter.

File: numpy/core/tests/test_regression.py [hunk 5]
```diff
@@ -2484,6 +2484,27 @@ class T(object):
...
+
+            def __getitem__(self, idx):
+                raise AssertionError("__getitem__ was called")
+
+            def __len__(self):
+                return 0
+
+
+        t = T()
+        #gh-13659, would raise in broadcasting [x=t for x in result]
```
Comment (eric-wieser) [inline numpy/core/tests/test_regression.py]: PEP8
```suggestion
        # gh-13659, would raise in broadcasting [x=t for x in result]
```

**Comment by eric-wieser** [comment]
Overall looks like some nice cleanup, especially if you can get it to pass CI

**Comment by seberg** [comment]
Passing our CI should not be a problem. Pandas seems to be acting up a bit though, I have to investigate if its us or them (or just bad tests).

File: numpy/core/src/multiarray/ctors.c (hunk 2 above)
Comment (seberg) [reply numpy/core/src/multiarray/ctors.c]: I have similar code paths with caching in my dtypemeta branch, but it is a bit different (and needs cleanups right now). But we can definitely do it. One note about caching: It does mean holding possibly a bit more things in memory.

**Comment by seberg** [comment]
@jbrockmendel, @superbobry maybe you can help me out understand pandas a bit better here? On the new branch pandas tests fail which do:
```
df1 = pd.DataFrame({"a": [1, 2, 3], "b": [3, 4, 5]})
df2 = pd.DataFrame([df1, df1])
```
The code seems to call `np.asarray([df1, df1])` (so far so good). Which now would return a 3-D array, and that trips pandas (I have difficulty saying how bad that actually is, a DeprecationWarning would be nice, but tricky with the project interplay maybe).

The part that I would like to understand is why it currently works (in some weird twisted way), when `np.asarray([df1, df1])` actually raises an error. I cannot see where that error is caught and replaced by an `dtype=object` kind coercion path?

**Comment by eric-wieser** [comment]
I think it's here:

https://github.com/pandas-dev/pandas/blob/ea2e26ae7d700d7fd363ea5bfc05d2fe3fb8a5ee/pandas/core/internals/construction.py#L249-L283

**Comment by seberg** [comment]
Yeah, but I think it should call `np.asarray([df1, df1])` which should raise an error. And I was too stupid to see why that error would not be propagated to the user...

**Comment by eric-wieser** [comment]
These lines also look relevant: https://github.com/pandas-dev/pandas/blob/ea2e26ae7d700d7fd363ea5bfc05d2fe3fb8a5ee/pandas/core/dtypes/cast.py#L1381-L1385

**Comment by seberg** [comment]
Oh man, thanks yeah. I saw that function being used, but somehow did not expect it to be hit in one branch vs. the other... 

<details> <summar>Error with this branch</summary>

```python
In [1]: import pandas as pd
^[[A
In [2]: df1 = pd.DataFrame({"a": [1, 2, 3], "b": [3, 4, 5]})

In [3]: pd.DataFrame([df1, df1])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-91cf2bad0f2e> in <module>()
----> 1 pd.DataFrame([df1, df1])

/home/sebastian/.local/lib/python3.7/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    462                     mgr = arrays_to_mgr(arrays, columns, index, columns, dtype=dtype)
    463                 else:
--> 464                     mgr = init_ndarray(data, index, columns, dtype=dtype, copy=copy)
    465             else:
    466                 mgr = init_dict({}, index, columns, dtype=dtype)

/home/sebastian/.local/lib/python3.7/site-packages/pandas/core/internals/construction.py in init_ndarray(values, index, columns, dtype, copy)
    169     # by definition an array here
    170     # the dtypes will be coerced to a single dtype
--> 171     values = prep_ndarray(values, copy=copy)
    172 
    173     if dtype is not None:

/home/sebastian/.local/lib/python3.7/site-packages/pandas/core/internals/construction.py in prep_ndarray(values, copy)
    293         values = values.reshape((values.shape[0], 1))
    294     elif values.ndim != 2:
--> 295         raise ValueError("Must pass 2-d input")
    296 
    297     return values

ValueError: Must pass 2-d input
```

</details>

Without this branch it returns a Dataframe with dataframes as entries, which is silly, but... Anyway, I will have a closer look if pandas can do something. But could be nice to have feedback from pandas whether they care about this or think its OK to error out...

**Comment by eric-wieser** [comment]
Can you run `%debug pd.core.internals.construction.prep_ndarray([pd, pd])` in ipython and step through to see the code path that initialized `values`?

**Comment by seberg** [comment]
whoops, I think I misread the code at the very start, its `not isinstance(...)`, so it goes into the try/except branch of `prep_ndarray` of course.

**Comment by charris** [comment]
Pushing this off. Will fix up the reversion which will also probably mess up the merge.

**Comment by seberg** [comment]
Yeah, I was starting to figure the same. I can do the fixup if you prefer.

**Comment by seberg** [comment]
I would like to try this early after the split then, so that we can see if pandas is OK/can keep up with it.

**Comment by eric-wieser** [comment]
> # following convert does nothing

@seberg, the way I read it `convert` called `construct_1d_object_array_from_listlike`

**Comment by seberg** [comment]
@eric-wieser yeah, but the new path that is taken with this never tries calling `convert` on the(now 3D) array (which was a ValueError before). In any case, while I would prefer this change, and I think pandas should probably be OK with it. I do not feel like pushing something that might cause an avalanche a few days before the release.

I have opened pandas issue at https://github.com/pandas-dev/pandas/issues/29978

**Comment by mattip** [comment]
there are merge conflicts now

**Comment by mattip** [comment]
@seberg ping

**Comment by seberg** [comment]
OK, updated and release notes added. Maybe we should just try and see where it brings us with respect to pandas? I assume they are the largest "users" of this behaviour, and it seemed like all of the test failures they have is nonsense behaviour that they should be deprecating anyway.

In the end, it is hard to test unless someone from the pandas side is willing to get this branch, so I would be for moving forward and reverting if necessary?

File: numpy/core/src/multiarray/ctors.c [hunk 6]
```diff
@@ -1574,6 +1508,96 @@ _array_from_buffer_3118(PyObject *memoryview)
...
+ *          or NULL with an error set.
+ */
+static PyObject *
+_array_from_array_like(PyObject *op,
+        PyArray_Descr *requested_dtype, npy_bool writeable, PyObject *context) {
+    PyObject* tmp;
+
+    /* If op supports the PEP 3118 buffer interface */
+    if (!PyBytes_Check(op) && !PyUnicode_Check(op)) {
+        PyObject *memoryview = PyMemoryView_FromObject(op);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/ctors.c]: This comment is a bit misleading - perhaps it should be something like
```
/* Skip unicode, which we know will fail, and bytes, which we want to treat as a scalar not a buffer */
```

It's tempting to remove the `PyUnicode_Check`

File: numpy/core/src/multiarray/ctors.c [hunk 7]
```diff
@@ -1574,6 +1508,96 @@ _array_from_buffer_3118(PyObject *memoryview)
...
+        }
+        else {
+            tmp = _array_from_buffer_3118(memoryview);
+            Py_DECREF(memoryview);
+            if (tmp == NULL) {
+                return NULL;
+            }
+
+            if (writeable
+                && PyArray_FailUnlessWriteable((PyArrayObject *) tmp, "PEP 3118 buffer") < 0) {
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/ctors.c]:
```suggestion
                && PyArray_FailUnlessWriteable((PyArrayObject *)tmp, "PEP 3118 buffer") < 0) {
```

File: numpy/core/src/multiarray/ctors.c [hunk 8]
```diff
@@ -1574,6 +1508,96 @@ _array_from_buffer_3118(PyObject *memoryview)
...
+            return tmp;
+        }
+    }
+
+    /* If op supports the __array_struct__ or __array_interface__ interface */
+    tmp = PyArray_FromStructInterface(op);
+    if (tmp == NULL) {
+        return NULL;
+    }
+    if (tmp == Py_NotImplemented) {
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/ctors.c]: Is this not a new reference? If it's not, a comment would be good. If it is, please add a `Py_DECREF`!

**Comment by jbrockmendel** [comment]
> it is hard to test unless someone from the pandas side is willing to get this branch

I'll pull this and run our npdev build against it now.

File: numpy/core/src/multiarray/ctors.c (hunk 8 above)
Comment (seberg) [reply numpy/core/src/multiarray/ctors.c]: No, it is a new reference. Could be an old bug, most likely it just broke during the merge.

File: numpy/core/src/multiarray/ctors.c [hunk 9]
```diff
@@ -1574,6 +1508,96 @@ _array_from_buffer_3118(PyObject *memoryview)
...
+    if (!writeable && tmp == Py_NotImplemented) {
+        tmp = PyArray_FromArrayAttr(op, requested_dtype, context);
+        if (tmp == NULL) {
+            return NULL;
+        }
+    }
+
+    if (tmp != Py_NotImplemented) {
+        if (writeable
+            && PyArray_FailUnlessWriteable((PyArrayObject *) tmp,
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/ctors.c]:
```suggestion
            && PyArray_FailUnlessWriteable((PyArrayObject *)tmp,
```

File: numpy/core/src/multiarray/ctors.c [hunk 10]
```diff
@@ -678,12 +700,24 @@ discover_itemsize(PyObject *s, int nd, int *itemsize, int string_type)
...
 
+
 typedef enum {
     DISCOVERED_OK = 0,
     DISCOVERED_RAGGED = 1,
     DISCOVERED_OBJECT = 2
 } discovered_t;
 
+
+void _discover_dimensions_array(PyArrayObject *arr, int *maxndim, npy_intp *d) {
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/ctors.c]:
```suggestion
static void
_discover_dimensions_array(PyArrayObject *arr, int *maxndim, npy_intp *d) {
```

File: numpy/core/src/multiarray/ctors.c [hunk 11]
```diff
@@ -1574,6 +1508,96 @@ _array_from_buffer_3118(PyObject *memoryview)
...
+ *
+ * * an object implementing the PEP 3118 buffer interface;
+ * * an object with __array_struct__ or __array_interface__ attributes;
+ * * an object with an __array__ function.
+ *
+ * @param op The object to convert to an array
+ * @param requested_type a requested dtype instance, may be NULL; The result
+ *                       DType may be used, but is not enforced.
+ * @param writeable whether the result must be writeable.
+ * @param context Unused parameter, must be NULL (should be removed later).
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/ctors.c]: Can we remove this now? It's already NULL at all the call-sites

File: numpy/core/src/multiarray/ctors.c [hunk 12]
```diff
@@ -1574,6 +1508,96 @@ _array_from_buffer_3118(PyObject *memoryview)
...
+     * If op supplies the __array__ function.
+     * The documentation says this should produce a copy, so
+     * we skip this method if writeable is true, because the intent
+     * of writeable is to modify the operand.
+     * XXX: If the implementation is wrong, and/or if actual
+     *      usage requires this behave differently,
+     *      this should be changed!
+     */
+    if (!writeable && tmp == Py_NotImplemented) {
+        tmp = PyArray_FromArrayAttr(op, requested_dtype, context);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/ctors.c]: Possible leak of `NotImplemented` here too.

File: numpy/core/src/multiarray/ctors.c (hunk 8 above)
Comment (seberg) [reply numpy/core/src/multiarray/ctors.c]: Hmmm, I guess its not a new reference.. . that code predates my changes (it was reverted), so had not checked too carefully, but annoyingly enough:
 * `PyArray_FromStructInterface`
 * `PyArray_FromInterface`
 * `PyArray_HasArrayInterface`
 * `PyArray_HasArrayInterfaceType `

 returns `NotImplemented` **without** adding a reference :(.

An evil thought: Deprecate all of them later :).

**Comment by seberg** [comment]
Did some style fixups and comment expansion (sorry, I did not mean to, but my muscle reflexes force pushed). The refcounting was correct, since it actually is a borrowed reference until the end of that function (public API, cannot be changed, I added a comment, which may be a bit long but...).

@jbrockmendel thanks for checking! Good to know that you think those pandas tests can be simply fixed up and should not be a problem.

**Comment by seberg** [comment]
Release notes pushed (forgot to add it to the commit).

**Comment by seberg** [comment]
Fixed the merge conflict, and tweaked the release note a bit. Do we have to discuss whether this should go in as a bug fix. *If* this is changes behaviour for some (arguably buggy code), I feel that in almost all cases it should lead to quick crashes, or at least very obvious wrong results.

**Comment by mattip** [comment]
Thanks @seberg
