### PR TITLE
BUG: Fixes np.put receiving empty array causes endless loop

### LINKED ISSUE #25744: BUG: numpy.put causes endless loop if array is empty
### Describe the issue:

In my project I want to use `numpy.put` and `numpy.take` to wrap-around a variable to safely access an array.

If the array is empty, numpy.take throws a "IndexError: cannot do a non-empty take from an empty axes." exception. I did expect that `numpy.put` also throws an exception. But instead it keeps running.

And the docs does not state that the array must not be empty :)

### Reproduce the code example:

```python
import numpy as np

array = np.asarray(list())
np.put(array, 1, 1, mode="wrap")
```

### Error message:

```shell
None - np.put keeps running and refuses to get killed by Ctrl+C
```

### Python and NumPy Versions:

Python 3.11.6
Numpy 1.26.3

### Runtime Environment:

_No response_

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by iquelli**
Closes #25744.

The bug issue was in the np.put function, specifically when an empty array was passed in wrap mode, causing an endless loop. During the investigation of the bug, it was observed that a similar problem occurred when using an empty array in clip mode, resulting in a core dump.

To address both issues simultaneously, I propose the following solution: In the implementation of the put function in C, I check whether the array is empty at the beginning of the function. If it is indeed empty, the implementation should raise an IndexError, providing a more informative and accurate error handling mechanism.

  Now all these code snippets work as intended:
```python
import numpy as np 
array = np.asarray(list())
np.put(array, 1, 1, mode="wrap")`
```

```python
import numpy as np 
array = np.asarray(list())
np.put(array, 1, 1, mode="clip")`
```

```python
import numpy as np 
a = np.zeros((5, 5, 0))
a.put(100, 0)
```

I also added a unit test for this issue.

### CODE REVIEW

File: numpy/_core/src/multiarray/item_selection.c [hunk 1]
```diff
@@ -384,6 +384,12 @@ PyArray_PutTo(PyArrayObject *self, PyObject* values0, PyObject *indices0,
         return NULL;
     }
 
+    if (PyArray_Size((PyObject *)self) == 0) {
```
Comment (eendebakpt) [inline numpy/_core/src/multiarray/item_selection.c:387]: With the check at this position the following code will fail even though it is valid in current numpy:
```
np.put(a, [], 2, mode='wrap')
```
Maybe move the check down a bit and replace it with 
```
if ( (ni > 0) && (PyArray_Size((PyObject *)self) == 0) ) {
```
(`ni` is the number of indices specified)

File: numpy/_core/tests/test_multiarray.py [hunk 2]
```diff
@@ -3501,6 +3501,12 @@ def test_put(self):
         bad_array = [1, 2, 3]
         assert_raises(TypeError, np.put, bad_array, [0, 2], 5)
 
+        # when calling np.put, make sure an 
+        # IndexError is raised if the 
+        # array is empty
+        empty_array = np.asarray(list())
+        assert_raises(IndexError, np.put, empty_array, 1, 1, mode="wrap")
```
Comment (eendebakpt) [inline numpy/_core/tests/test_multiarray.py:3508]:
```suggestion
        assert_raises(IndexError, np.put, empty_array, 1, 1, mode="wrap")
        assert_raises(IndexError, np.put, empty_array, 1, 1, mode="clip")
```

File: numpy/_core/src/multiarray/item_selection.c (hunk 1 above)
Comment (iquelli) [reply numpy/_core/src/multiarray/item_selection.c:387]: Workinng on it. Thanks for the suggestion.

File: numpy/_core/tests/test_multiarray.py (hunk 2 above)
Comment (iquelli) [reply numpy/_core/tests/test_multiarray.py:3508]: Will add

**Comment by iquelli** [comment]
@eendebakpt  any reason the pipeline might be failing right now? I am a bit lost as to why.

**Comment by iquelli** [comment]
@eendebakpt  already applied the changes. Any reason why the pipeline might be failing right now? I am a bit lost.

**Comment by eendebakpt** [comment]
> @eendebakpt already applied the changes. Any reason why the pipeline might be failing now? I am a bit lost. It passes the spin test in my machine.

The failing tests seem unrelated to this PR, so I think you can ignore them. (but this is up to the numpy developers to decide)

**Comment by eendebakpt** [comment]
I also found out that:
```
import numpy as np
x=np.array([1])
np.put(x, -4, 2) # fails with IndexError: index -4 is out of bounds for axis 0 with size 1
np.put(x, -1, 2) # sets x[0] to 2,
```
I would have expected for either -1 and -4 to both succeed, or both fail. This is not documented in `np.put`, nor in `x.flat`. It is not clear to be whether this is a bug in the implementation or intended behaviour.

File: numpy/_core/src/multiarray/item_selection.c [hunk 3]
```diff
@@ -394,6 +394,11 @@ PyArray_PutTo(PyArrayObject *self, PyObject* values0, PyObject *indices0,
         goto fail;
     }
     ni = PyArray_SIZE(indices);
+    if ((ni > 0) && (PyArray_Size((PyObject *)self) == 0)) {
+        PyErr_SetString(PyExc_IndexError, 
+                        "put: cannot do a non empty put on an empty array");
```
Comment (eendebakpt) [inline numpy/_core/src/multiarray/item_selection.c:399]:
```suggestion
                        "numpy.put: cannot do a non empty put on an empty array");
```

**Comment by seberg** [comment]
> I would have expected for either -1 and -4 to both succeed, or both fail. 

Only with `mode="wrap"` which indexing dosen't have.

File: numpy/_core/src/multiarray/item_selection.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (iquelli) [reply numpy/_core/src/multiarray/item_selection.c]: Thank you for the feedback.
Already updated the error message

File: numpy/_core/tests/test_multiarray.py [hunk 4]
```diff
@@ -3501,6 +3501,13 @@ def test_put(self):
...
+        assert_raises(IndexError, np.put, empty_array, 1, 1, mode="clip")
```
[the remark this answers is not in the document]
Comment (iquelli) [reply numpy/_core/tests/test_multiarray.py]: Updated the tests as well.
Thank you once again :)

**Comment by ngoldbaum** [comment]
Thanks @iquelli.
