### PR TITLE
MAINT: Deprecated PyObject_Compare in favor of PyObject_RichCompareBool. Fixes #6265

### LINKED ISSUE #6265: MANT: Replace PyObject_Compare with PyObject_RichCompareBool
See https://github.com/numpy/numpy/pull/6236#issuecomment-133768265. Since our oldest supported Python version is 2.6, there is no longer a need for separate compilation paths for Python 2.x and 3.x, for Python object comparison, since both provide `PyObject_RichCompareBool`. It may also be a good idea to get rid of the `Pyobject_Cmp` function, defined for Python 3.x in [`npy_3kcompat.h`](https://github.com/numpy/numpy/blob/maintenance/1.10.x/numpy/core/include/numpy/npy_3kcompat.h#L324), which was recently discovered to be broken by @pv, see https://github.com/numpy/numpy/issues/6229#issuecomment-133458966.

I'll try to put a PR together for this shortly, unless someone else wants the glory for themselves.

### PR DESCRIPTION
**Pull request by yashmehrotra**
@jaimefrio I made the changes as discussed in #6265 . I ran all tests for Python2 and Python3 through `python runtests.py` / `python3 runtests.py` and did not encounter any failure.

As far as the `PyObject_Cmp` function in `npy_3kcompat.h` goes, I did not change that. I although did fix the only part of code base that uses it with `PyObject_RichCompareBool`. 
As far as `PyObject_Cmp` goes, should I remove it or add a deprecation warning ?

### CODE REVIEW

File: numpy/core/src/umath/loops.c.src [hunk 1]
```diff
@@ -2618,32 +2618,33 @@ OBJECT_@kind@(char **args, npy_intp *dimensions, npy_intp *steps, void *NPY_UNUS
 NPY_NO_EXPORT void
 OBJECT_sign(char **args, npy_intp *dimensions, npy_intp *steps, void *NPY_UNUSED(func))
 {
-#if defined(NPY_PY3K)
     PyObject *zero = PyLong_FromLong(0);
+    PyObject *one = PyLong_FromLong(1);
+    PyObject *minus_one = PyLong_FromLong(-1);
```
Comment (jaimefrio) [inline numpy/core/src/umath/loops.c.src]: Either `one` or `minus_one` is not going to be returned, and should therefore have its refcount decreased before returning, similarly to what happens with `zero`.

Comment (yashmehrotra) [inline numpy/core/src/umath/loops.c.src]: So should I decrease both `one` and `minus_one`'s refcount in the end ?

File: numpy/core/src/umath/loops.c.src [hunk 2]
```diff
@@ -2618,32 +2618,33 @@ OBJECT_@kind@(char **args, npy_intp *dimensions, npy_intp *steps, void *NPY_UNUS
...
     UNARY_LOOP {
         PyObject *in1 = *(PyObject **)ip1;
         PyObject **out = (PyObject **)op1;
-        int v;
+        int is_eq, is_gt;
         PyObject *ret;
-        if (PyObject_Cmp(in1 ? in1 : Py_None, zero, &v) == -1) {
+
+        is_gt = PyObject_RichCompareBool(in1 ? in1 : Py_None, zero, Py_GT);
+        is_eq = PyObject_RichCompareBool(in1 ? in1 : Py_None, zero, Py_EQ);
```
Comment (jaimefrio) [inline numpy/core/src/umath/loops.c.src]: We shouldn't do a second comparison if the first already figure out the correct return. I kind of like the internal structure of `PyObject_Cmp`: unless you can come up with a better approach, I'd suggest replicating that here. But of course, fixing the errors discussed in #6229.

**Comment by jaimefrio** [comment]
As commented inline, fixing this will also close #6229, so please add a "closes #6229" somewhere in the commit message. And if you could also add a test for that failure it would be perfect.

File: numpy/core/src/umath/loops.c.src (hunk 2 above)
Comment (yashmehrotra) [inline numpy/core/src/umath/loops.c.src]: I am doing a second comp because, if the no. is not greater than zero, how would we know if its equal to or less than zero ?

**Comment by yashmehrotra** [comment]
@jaimefrio I didn't quite understand the test part, what exactly would the test case be checking ?

File: numpy/core/src/umath/loops.c.src (hunk 1 above)
Comment (jaimefrio) [inline numpy/core/src/umath/loops.c.src]: All except the one you assign to `out`.

**Comment by yashmehrotra** [comment]
@jaimefrio For reference count, I removed the `one` and `minus_one` as they were more of noise than signal. For issue #6229 , I did add the fix and the test case, although there is not much use of the fix as `PyObject_Cmp` is now not being used anywhere. 
Are there any other changes I need to make to make this PR merge-ready ?

**Comment by jaimefrio** [comment]
The body of the `OBJECT_sign` function should be something like this:

```
PyObject *zero = PyLong_FromLong(0);

UNARY_LOOP {
    PyObject *in1 = *(PyObject **)ip1;
    PyObject **out = (PyObject **)op1;
    PyObject *ret = NULL;
    int v;

    if (in1 == NULL) {
        in1 = Py_None;
    }
    v = PyObject_RichCompareBool(in1, zero, Py_LT);
    if (v == 1) {
        ret = PyLong_FromLong(-1);
    }
    else if (v == 0) {
        v = PyObject_RichCompareBool(in1, zero, Py_GT);
        if (v == 1) {
            ret = PyLong_FromLong(1);
        }
        else if (v == 0) {
            v = PyObject_RichCompareBool(in1, zero, Py_EQ);
            if (v == 1) {
                ret = PyLong_FromLong(0);
            }
        }
    }
    if (v < 0) {
        Py_DECREF(zero);
        return;
    }
    Py_XDECREF(*out);
    *out = ret;
}
Py_DECREF(zero);
}
```

Feel free to rewrite it as you see fit, but beware of the subtleties: if we cannot get a positive comparison using `Py_LT`, `Py_GT` or `Py_EQ`, it is considered an error and we bail out early.

File: numpy/core/include/numpy/npy_3kcompat.h [hunk 3]
```diff
@@ -325,7 +325,7 @@ PyObject_Cmp(PyObject *i1, PyObject *i2, int *cmp)
 {
     int v;
     v = PyObject_RichCompareBool(i1, i2, Py_LT);
-    if (v == 0) {
+    if (v == 1) {
```
Comment (jaimefrio) [inline numpy/core/include/numpy/npy_3kcompat.h]: There are two more instances of this mistake, right after the next two calls to `PyObject_RichCompareBool` below.

File: numpy/core/tests/test_umath.py [hunk 4]
```diff
@@ -935,6 +935,12 @@ def test_sign(self):
             assert_equal(res, tgt)
             assert_equal(out, tgt)
 
+    def test_sign_dtype_object(self):
```
Comment (jaimefrio) [inline numpy/core/tests/test_umath.py]: We typically add a comment back to the relevant issue, e.g. `# gh-6229` in this case.

**Comment by yashmehrotra** [comment]
@jaimefrio I have the changes as suggested by you. Thanks for the help. Are there any other things I need to do ?

File: numpy/core/src/umath/loops.c.src [hunk 5]
```diff
@@ -2618,41 +2618,48 @@ OBJECT_@kind@(char **args, npy_intp *dimensions, npy_intp *steps, void *NPY_UNUS
...
+                if (v == 1) {
+                    ret = PyLong_FromLong(0);
+                }
+            }
         }
-        ret = PyLong_FromLong(v);
-        if (PyErr_Occurred()) {
+
+        /* In case of error in comparison */
+        if ( v == -1) {
```
Comment (jaimefrio) [inline numpy/core/src/umath/loops.c.src]: Extra space inside parenthesis.

**Comment by yashmehrotra** [comment]
@jaimefrio Extra space around parenthesis removed.

File: numpy/core/src/umath/loops.c.src [hunk 6]
```diff
@@ -2618,41 +2618,48 @@ OBJECT_@kind@(char **args, npy_intp *dimensions, npy_intp *steps, void *NPY_UNUS
...
+        } else if (v == 0) {
+            v = PyObject_RichCompareBool(in1, zero, Py_GT);
+            if (v == 1) {
+                ret = PyLong_FromLong(1);
+            } else if (v == 0) {
+                v = PyObject_RichCompareBool(in1, zero, Py_EQ);
+                if (v == 1) {
+                    ret = PyLong_FromLong(0);
+                }
+            }
```
Comment (jaimefrio) [inline numpy/core/src/umath/loops.c.src]: I think there is a loophole in this logic. Consider the following:

```
>>> a = np.array([np.nan], dtype=object)
>>> a < 0
array([False], dtype=bool)
>>> a == 0
array([False], dtype=bool)
>>> a > 0
array([False], dtype=bool)
``` 

If we have an object that is neither larger, nor smaller, nor equal to `0`, right now we will set the output to `NULL`, which I am not sure is what we really want. Perhaps `None` is the right thing to set it to, but I'll ask on the list for the community wisdom on this one.

Comment (yashmehrotra) [inline numpy/core/src/umath/loops.c.src]: @jaimefrio I read a bit about NaN. In my opinion, comparing integers with NaN should return `False` as the comparison operators result is a boolean, and the comparison wouldn't be `True`.
Also, in JavaScript, all integer comparisons with NaN evaluates to `false`.
Well, that was my opinion. If it is decided to change the result to `None` as per the community decision. Do keep updated on this one.

**Comment by yashmehrotra** [comment]
@jaimefrio Hi Jaime, any updates ?

**Comment by yashmehrotra** [comment]
@jaimefrio Hi Jaime, do you have any updates for this PR ?

File: numpy/core/src/umath/loops.c.src [hunk 7]
```diff
@@ -2618,41 +2618,48 @@ OBJECT_@kind@(char **args, npy_intp *dimensions, npy_intp *steps, void *NPY_UNUS
...
+            ret = PyLong_FromLong(-1);
+        } else if (v == 0) {
+            v = PyObject_RichCompareBool(in1, zero, Py_GT);
+            if (v == 1) {
+                ret = PyLong_FromLong(1);
+            } else if (v == 0) {
+                v = PyObject_RichCompareBool(in1, zero, Py_EQ);
+                if (v == 1) {
+                    ret = PyLong_FromLong(0);
+                }
```
Comment (jaimefrio) [inline numpy/core/src/umath/loops.c.src]: Ok, so according to what seems to be the closest to a consensus, here we should have an `else if (v == 0)` that raises a `TypeError`, not sure what the right message should be. Thoughts?

Comment (yashmehrotra) [inline numpy/core/src/umath/loops.c.src]: @jaimefrio I have already implemented the above and its working as expected. For the error message, I was gonna ask you, what it should be :stuck_out_tongue: . 

How about we go with the error message you suggested in the mailing list or how about we just explicitly tell the user that the exception is due to NaN. Like  `TypeError: Trying to compare NaN` (Something like this).

Comment (yashmehrotra) [inline numpy/core/src/umath/loops.c.src]: @jaimefrio Any thoughts on the error message or should I send a PR with error message `TypeError: unorderable types ...etc`

**Comment by yashmehrotra** [comment]
@jaimefrio Any feedback for the error message ?

**Comment by yashmehrotra** [comment]
@jaimefrio Can you please take a look at the new commit ?

**Comment by yashmehrotra** [comment]
@charris Hi Charles, it seems that Jaime is busy these days and I couldn't get any feedback on this PR. Can you please take a look at this.

**Comment by yashmehrotra** [comment]
@charris @jaimefrio How about merging this PR, its been pending for days. Is there any work required by my side to make it merge ready ?

**Comment by ahaldane** [comment]
Just to note, there is a possibility of overhauling `OBJECT_sign` in #6320 in the future. (But it may take a long time since that's waiting on `__numpy_ufunc__` decisions). The implementation there takes care of complex numbers and float/complex `nan` more carefully.

However, this PR also has good cleanups for `OBJECT_compare` and `_equivalent_fields` (which there are no other plans to change), and I think the upgrade to `OBJECT_sign` in this PR is good to have in the short term.

File: numpy/core/src/umath/loops.c.src [hunk 8]
```diff
@@ -2618,41 +2618,51 @@ OBJECT_@kind@(char **args, npy_intp *dimensions, npy_intp *steps, void *NPY_UNUS
...
-            return;
+
+        if (in1 == NULL) {
+            in1 = Py_None;
+        }
+
+        v = PyObject_RichCompareBool(in1, zero, Py_LT);
+        if (v == 1) {
+            ret = PyLong_FromLong(-1);
+        } else if (v == 0) {
```
Comment (charris) [inline numpy/core/src/umath/loops.c.src]: I'd be inclined to do this like
```
        v = PyObject_RichCompareBool(in1, zero, Py_LT);
        if (v == 1) {
            ret = PyLong_FromLong(-1);
            goto done;
        }
        else if (v == -1) {
            goto error;
        }
```
and repeat with minor variations for the other two cases. That avoids the deep indentations and is, IMHO, easier to follow.
Note the style for `else`.

**Comment by yashmehrotra** [comment]
@charris I have made the changes as per your suggestions.

File: numpy/core/src/umath/loops.c.src [hunk 9]
```diff
@@ -2618,41 +2618,64 @@ OBJECT_@kind@(char **args, npy_intp *dimensions, npy_intp *steps, void *NPY_UNUS
...
-        ret = PyLong_FromLong(v);
-        if (PyErr_Occurred()) {
-            Py_DECREF(zero);
-            return;
+
+        v = PyObject_RichCompareBool(in1, zero, Py_LT);
+        if (v == 1) {
+            ret = PyLong_FromLong(-1);
+            goto done;
+        } else if (v == -1) {
```
Comment (charris) [inline numpy/core/src/umath/loops.c.src]: Note style guide `doc/C_STYLE_GUIDE.rst.txt`. The else should be like
```
}
else if {
```

File: numpy/core/src/umath/loops.c.src [hunk 10]
```diff
@@ -2618,41 +2618,64 @@ OBJECT_@kind@(char **args, npy_intp *dimensions, npy_intp *steps, void *NPY_UNUS
...
+
+        v = PyObject_RichCompareBool(in1, zero, Py_EQ);
+        if (v == 1) {
+            ret = PyLong_FromLong(0);
+            goto done;
+        } else if (v == -1) {
+            goto fail;
+        }
+
+        if (v == 0) {
```
Comment (charris) [inline numpy/core/src/umath/loops.c.src]: If you get here you already know `v == 0`.

File: numpy/core/src/umath/loops.c.src [hunk 11]
```diff
@@ -2618,41 +2618,64 @@ OBJECT_@kind@(char **args, npy_intp *dimensions, npy_intp *steps, void *NPY_UNUS
 NPY_NO_EXPORT void
 OBJECT_sign(char **args, npy_intp *dimensions, npy_intp *steps, void *NPY_UNUSED(func))
 {
-#if defined(NPY_PY3K)
     PyObject *zero = PyLong_FromLong(0);
```
Comment (charris) [inline numpy/core/src/umath/loops.c.src]: I doesn't look like zero is used anymore.

File: numpy/core/src/umath/loops.c.src [hunk 12]
```diff
@@ -2618,41 +2618,64 @@ OBJECT_@kind@(char **args, npy_intp *dimensions, npy_intp *steps, void *NPY_UNUS
...
+            goto fail;
+        }
+
+        fail:
+            if (PyErr_Occurred()) {
+                Py_DECREF(zero);
+                return;
+            }
+            /* In case of error in comparison */
+            if (v == -1) {
```
Comment (charris) [inline numpy/core/src/umath/loops.c.src]: I believe this is already covered. `v == -1` -> `PyErr_Occurred`. I think you can simply `Py_DECREF(zero)` and return. In fact, it looks like all of these can simply be replaced by `return` since `zero` goes away. Probably don't need this label anymore, `return` can replace goto.

File: numpy/core/src/umath/loops.c.src (hunk 11 above)
Comment (charris) [inline numpy/core/src/umath/loops.c.src]: Oops, nevermind.

File: numpy/core/src/umath/loops.c.src (hunk 12 above)
Comment (charris) [inline numpy/core/src/umath/loops.c.src]: If so, I think you can move `done` in front of `fail`, something like
```
done:
    Py_XDECREF(*out);
    *out = ret;
fail:
    PyDECREF(zero);
```

File: numpy/core/src/umath/loops.c.src [hunk 13]
```diff
@@ -2618,41 +2618,64 @@ OBJECT_@kind@(char **args, npy_intp *dimensions, npy_intp *steps, void *NPY_UNUS
...
+            goto fail;
+        }
+
+        if (v == 0) {
+            /* In this case, we are dealing with NaN */
+            PyErr_SetString(PyExc_TypeError, "unorderable types for comparison");
+            goto fail;
+        }
+
+        fail:
```
Comment (charris) [inline numpy/core/src/umath/loops.c.src]: Note, labels begin in column 1, no extra indentation needed after.

These labels also do not belong in the `UNARY_LOOP` They are so you can break out of the loop.

File: numpy/core/src/umath/loops.c.src (hunk 12 above)
Comment (charris) [inline numpy/core/src/umath/loops.c.src]: Oops, `done` is inside the loop, `fail` outside. `got fail` can probably be replace by `break`.  Looks like the original was leaking references.

Comment (yashmehrotra) [inline numpy/core/src/umath/loops.c.src]: For this, should this be
```c
if (v == 1) {
        ret = PyLong_FromLong(0);
        goto done;
}
else if (v == -1) {
        break;                                                                                                                                                  
}
done: 
        Py_XDECREF(*out);
        *out = ret;

```
And use `PyDECREF(zero);` outside the `UNARY LOOP` in case of failure ?

**Comment by yashmehrotra** [comment]
@charris I have modified the code as required. I hope its all good now.

**Comment by charris** [comment]
I apologize for getting a bit confused myself. I'll take another look later this evening.

File: numpy/core/src/umath/loops.c.src [hunk 14]
```diff
@@ -2618,41 +2618,54 @@ OBJECT_@kind@(char **args, npy_intp *dimensions, npy_intp *steps, void *NPY_UNUS
...
+
+        /* In this case, we are dealing with NaN */
+        PyErr_SetString(PyExc_TypeError, "unorderable types for comparison");
+        break;
+
+done:
         Py_XDECREF(*out);
         *out = ret;
-    }
+}
```
Comment (charris) [inline numpy/core/src/umath/loops.c.src]: Wrong endentation.

**Comment by charris** [comment]
LGTM modulo nitpick. Another possibility that adds no net lines and get rid of the goto is to replace
```
            ret = PyLong_FromLong(0);
            goto done;
```
by
```
            Py_XDECREF(*out)
            *out = PyLong_FromLong(0);
            continue;
```
etc.

**Comment by yashmehrotra** [comment]
@charris Changes updated. I hope its good now.

**Comment by charris** [comment]
OK, my bad. The other errors need checking. How about
```
NPY_NO_EXPORT void
OBJECT_sign(char **args, npy_intp *dimensions, npy_intp *steps, void *NPY_UNUSED(func))
{
    PyObject *zero = PyLong_FromLong(0);

    UNARY_LOOP {
        PyObject *in1 = *(PyObject **)ip1;
        PyObject **out = (PyObject **)op1;
        PyObject *ret = NULL;
        int v = 0;

        if (in1 == NULL) {
            in1 = Py_None;
        }

        if ((v = PyObject_RichCompareBool(in1, zero, Py_LT)) == 1) {
            ret = PyLong_FromLong(-1);
        }
        else if (v == 0 &&
                (v = PyObject_RichCompareBool(in1, zero, Py_GT)) == 1) {
            ret = PyLong_FromLong(1);
        }
        else if (v == 0 &&
                (v = PyObject_RichCompareBool(in1, zero, Py_EQ)) == 1) {
            ret = PyLong_FromLong(0);
        }
        else if (v == 0) {
            /* in1 is NaN */
            PyErr_SetString(PyExc_TypeError,
                    "unorderable types for comparison");
        }

        if (ret == NULL) {
            break;
        }
        Py_XDECREF(*out);
        *out = ret;
    }
    Py_DECREF(zero);
}
```

**Comment by yashmehrotra** [comment]
@charris I have updated the code. Hope its all good to go now.

File: numpy/core/src/umath/loops.c.src [hunk 15]
```diff
@@ -2618,41 +2618,43 @@ OBJECT_@kind@(char **args, npy_intp *dimensions, npy_intp *steps, void *NPY_UNUS
...
+
+        if (in1 == NULL) {
+            in1 = Py_None;
         }
-        ret = PyLong_FromLong(v);
-        if (PyErr_Occurred()) {
-            Py_DECREF(zero);
-            return;
+
+        v = PyObject_RichCompareBool(in1, zero, Py_LT);
```
Comment (charris) [inline numpy/core/src/umath/loops.c.src]: Don't need this line.

File: numpy/core/src/umath/loops.c.src [hunk 16]
```diff
@@ -2618,41 +2618,43 @@ OBJECT_@kind@(char **args, npy_intp *dimensions, npy_intp *steps, void *NPY_UNUS
...
+        else if (v == 0 &&
+                (v = PyObject_RichCompareBool(in1, zero, Py_GT)) == 1) {
+            ret = PyLong_FromLong(1);
+        }
+        else if (v == 0 &&
+                (v = PyObject_RichCompareBool(in1, zero, Py_EQ)) == 1) {
+            ret = PyLong_FromLong(0);
+        }
+        else if (v == 0) {
+        /* in1 is NaN */
```
Comment (charris) [inline numpy/core/src/umath/loops.c.src]: indent comment.

File: numpy/core/src/umath/loops.c.src [hunk 17]
```diff
@@ -2618,41 +2618,43 @@ OBJECT_@kind@(char **args, npy_intp *dimensions, npy_intp *steps, void *NPY_UNUS
...
+                    "unorderable types for comparison");
+        }
+
+        if (ret == NULL) {
+            break;
         }
         Py_XDECREF(*out);
         *out = ret;
     }
     Py_DECREF(zero);
```
Comment (charris) [inline numpy/core/src/umath/loops.c.src]: Strictly speaking, should probably be `Py_XDECREF` just in case creation of zero failed. Unlikely, as the `0` value should be a singleton.

**Comment by charris** [comment]
Almost there.  When you are ready, squash the commits using `git rebase -i HEAD~n`, where `n` is the number of commits in this PR, then do a force push `git push --force origin HEAD`.

**Comment by yashmehrotra** [comment]
@charris All commits squashed into one.

**Comment by charris** [comment]
LGTM pending tests.

**Comment by charris** [comment]
Thanks @yashmehrotra . If you would like to make a PR against the `maintenance/1.10.x` branch that just fixes `PyObject_Cmp` and add tests for same I would appreciate it. If not, I will do it later today.

**Comment by charris** [comment]
I've backported the ` PyObject_Cmp` fix, so don't do that.
