### PR TITLE
ENH: Implement initial kwarg for ufunc.add.reduce

### LINKED ISSUE #5032: min/max of empty arrays
A similar issue was raised in #2670, however the edge case of (0, ) shape is still not covered. I can go around it with checking for non-zero length in an `if` statement, but it would be more practical if `np.min` could handle this, too.

```
In [24]: [np.min(param[x][1]) for x in fields]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-24-076aa74e3684> in <module>()
----> 1 [np.min(param[x][1]) for x in fields]

/data/wts/pipeline64/python/lib/python2.6/site-packages/numpy/core/fromnumeric.pyc in amin(a, axis, out)
   1893     except AttributeError:
   1894         return _wrapit(a, 'min', axis, out)
-> 1895     return amin(axis, out)
   1896 
   1897 

ValueError: zero-size array to minimum.reduce without identity

In [25]: param[x]
Out[25]: 
{1: array([], dtype=float64),
 2: array([], dtype=float64),
 3: array([], dtype=float64),
 4: array([], dtype=float64)}

In [26]: param[x][1].shape
Out[26]: (0,)
```

### PR DESCRIPTION
**Pull request by hameerabbasi**
As discussed in #5032: Adds an `initial` kwarg for `ufunc.reduce`, plus changes in `min`, `max`, `sum`, `prod`.

This acts as the first item in a reduction. It's useful for empty reductions e.g. `np.min([], initial=np.inf)` reduces to `inf`. It's also useful for starting the reduction with a different value e.g. `np.sum([10], initial=5)` reduces to `15`. (`5` used as starting value rather than the identity `0`).

Explicitly passing the initial value as `None` causes empty reductions to err.

Explicitly passing `np._NoValue` also keeps the default behaviour.

`min`, `max`, `sum` and `prod` only pass on the `initial` kwarg.

`PyUFunc_Reduce` is modified to accept the `initial` kwarg. It then replaces the identity by `initial`.

Changes are made to `normalize_reduce_args` so that it accepts and parses `initial` correctly.

Documentation has been added for all the changes.

Fixes #5032

### CODE REVIEW

**Comment by hameerabbasi** [comment]
@eric-wieser Looking forward to your feedback. 😄

**Comment by hameerabbasi** [comment]
Hmm. I have no idea why the CircleCI build failed, I didn't touch Cython. :/

File: numpy/core/src/umath/ufunc_object.c [hunk 1]
```diff
@@ -2844,7 +2843,9 @@ PyUFunc_Reduce(PyUFuncObject *ufunc, PyArrayObject *arr, PyArrayObject *out,
     }
 
     /* Get the identity */
-    identity = _get_identity(ufunc, &reorderable);
+    if (identity == NULL || identity == Py_None) {
+        identity = _get_identity(ufunc, &reorderable);
+    }
```
Comment (eric-wieser) [inline numpy/core/src/umath/ufunc_object.c]: You need an `else { Py_INCREF(identity); }`, so that the decref at the end is safe.

**Comment by eric-wieser** [comment]
It looks like  you built this patch on an out-of-date master from before we had CircleCI working. If you rebase, the CircleCI error will go away.

File: numpy/core/src/umath/ufunc_object.c (hunk 1 above)
Comment (hameerabbasi) [reply numpy/core/src/umath/ufunc_object.c]: I don't think so, it only checks for `None` and `NULL`. The object is getting passed through.

`identity` is gotten from the `PyArg_ParseTupleAndKeywords`, does this do the `Py_INCREF` call automatically or not?

Comment (eric-wieser) [reply numpy/core/src/umath/ufunc_object.c]: And the other half of the puzzle is that `_get_identity` _does_ increment the reference count - so you want to make them equivalent so the cleanup doesn't need special casing.

**Comment by eric-wieser** [comment]
This is failing because we reparse the arguments for forwarding to __array_ufunc__ - but I don't remember where.

**Comment by ahaldane** [comment]
Somewhat tangent comment: How would this fit in with the dream of turning `reduce` into a gufunc (related to discussions in #8528 #8819)? 

Currently gufuncs have a fixed set of common keyword arguments, `axis`, `dtype`, `casting`, `extobj`, `where` and so on. Should individual gufuncs be allowed to have additional args besides the default ones, as `identity` would be?

Or does the fact that reduce will have an extra `identity` argument mean that it cannot be implemented as a gufunc?

**Comment by ahaldane** [comment]
Maybe the way to think of it is that a `reduce_ufunc(a, out=b)` gufunc treats its "out" parameter also as an input. So if you supply an `out`, that initial value gets read and added on to. 

So maybe ultimately, we would have both a reduce-gufunc, and a reduce method. The reduce method's job is to properly set up the out parameter for the reduce-gufunc. The method would have an "identity" argument, while the ufunc itself would read that value from the out arg.

Sorry for the distraction, we can think about this later outside this PR.

**Comment by charris** [comment]
The explanation of these changes could be much more complete. And please explain it for *all* the functions changed.

**Comment by eric-wieser** [comment]
So, there are two things that worry me here:

* The interface is different to the builtin `max(..., default=0)`, even though it's _roughly_ the same
* `ufunc.reduce(identity=...)` only really makes sense for `maximum`. `minimum`, `fmax`, and `fmin`, where choosing a different domain lets you choose a different identity. For other ufuncs, it produces crazy results (I think `np.add.reduce(np.ones(2,2), identity=10)` will give a surprising result, but I haven't checked).

**Comment by hameerabbasi** [comment]
> The explanation of these changes could be much more complete. And please explain it for all the functions changed.

I'll add more complete docs with examples, if that's what you mean, incorporating @eric-wieser's excellent use cases and insights. :-)

> The interface is different to the builtin max(..., default=0), even though it's roughly the same.

Yes, I thought of that as well, however, plenty of kwargs here are different (`axis`, `keepdims`, etc.). I'll go ahead and assume that we're not following Python's interface here, however, this can still be changed.

However, if it WAS to be changed, I'd say it's more similar to [`functools.reduce`](https://docs.python.org/3/library/functools.html#functools.reduce)'s `initializer` argument, which is much more instructive. This is also in line with your second worry:

> For other ufuncs, it produces crazy results (I think np.add.reduce(np.ones(2,2), identity=10) will give a surprising result, but I haven't checked).

```python
>>> np.add.reduce(np.ones((2, 2)), identity=10)
array([12., 12.])
```

The name `initializer` instead of `identity` is much more instructive and takes care of this worry.

So `initializer` probably makes more sense here. We could add a warning in the docs that non-default initializers could lead to unexpected results.

**Comment by eric-wieser** [comment]
> will give a surprising result, but I haven't checked

There's a more surprising result than that one to be found, I think. Maybe `np.add.reduce(np.ones((2, 2, 2)), axis=(0, 1), identity=10)`?

**Comment by hameerabbasi** [comment]
It gives a quite reasonable result, actually.
```python
>>> np.add.reduce(np.ones((2, 2, 2)), axis=(0, 1), identity=10)
array([14., 14.])
```

**Comment by eric-wieser** [comment]
> The name initializer instead of identity is much more instructive and takes care of this worry.

That's maybe reasonable. Perhaps `ufunc.reduce` should take an `initializer` argument, but the `np.min` shorthand can alias it to `default`?

We'll definitely need to run this by the list before this gets merged, but

**Comment by eric-wieser** [comment]
Non-adjacent axes? `(0, 2)`?

**Comment by hameerabbasi** [comment]
> Non-adjacent axes? `(0, 2)`?

Still works beautifully.

> That's maybe reasonable. Perhaps ufunc.reduce should take an initializer argument, but the np.min shorthand can alias it to default?

The slight problem I see with this is something like the following:

```python
>>> np.minimum.reduce([0.0], identity=-np.inf)
-inf
```

As you can see, it gives a value not in the original set. I guess we could call it `default` but then there are two issues with this:

- The one I mentioned above;
- We're deviating from `ufunc.reduce` norms, which is a bad thing. It doesn't keep uniformity.

**Comment by eric-wieser** [comment]
> Still works beautifully.

Huh, I think my memory of the code is incorrect. I thought that multi-axis `reduce` fell back on repeated single-axis reduce, and so was expecting to get 24 as the result. It seems that's not the case, which is great!

> As you can see, it gives a value not in the original set.

I'm now on board with the argument being called `initializer`, which makes that far less confusing.

The issue in that case is that the caller chose to pass in an initializer that was _not_ the minimum of the set of allowed values. That looks perfectly fine to me.

**Comment by eric-wieser** [comment]
CI is failing because `core/src/umath/override.c@normalize_reduce_args` is missing this argument.

**Comment by hameerabbasi** [comment]
> The issue in that case is that the caller chose to pass in an initializer that was not the minimum of the set of allowed values. That looks perfectly fine to me.

Exactly. We can document a use-case as being reduction of an empty axis.

On that note, I'm going to work and might not be available for the next hours. If you want to fix that on my branch, feel free.

**Comment by hameerabbasi** [comment]
On another note, if we're renaming this to `initializer`, it would make sense to add it to `accumulate` and `reduceat`. Is that best done in another PR or this one?

**Comment by eric-wieser** [comment]
`reduceat` is best untouched - there's an issue about writing a replacement somewhere.

Accumulate would be a better fit for another PR, especially since the use case is less strong.

**Comment by eric-wieser** [comment]
> Edit: I'm willing to take on the task of making reduceat use identity.

#834 should get you started on that rabbit hole. Lets try and wrap up this PR first though!

File: numpy/add_newdocs.py [hunk 2]
```diff
@@ -5874,7 +5880,19 @@ def luf(lamdaexpr, *args, **kwargs):
     >>> np.add.reduce(X, 2)
     array([[ 1,  5],
            [ 9, 13]])
-
+           
+    You can use the initializer argument to initialize the reduction to a
+    different value. It can be used to calculate empty reductions for
+    ufuncs that don't support it as well.
```
Comment (eric-wieser) [inline numpy/add_newdocs.py]: Move this second sentence to just above `np.minimum.reduce` so it's clear what it refers to

File: numpy/core/fromnumeric.py [hunk 3]
```diff
@@ -1827,6 +1827,11 @@ def sum(a, axis=None, dtype=None, out=None, keepdims=np._NoValue):
         `ndarray`, however any non-default value will be.  If the
         sub-class' method does not implement `keepdims` any
         exceptions will be raised.
+    initializer : scalar, optional
+        The initializer for this maximum. Can also be used to compute the
+        minimum of an empty slice.
```
Comment (eric-wieser) [inline numpy/core/fromnumeric.py]: `max`? `min`? This is `sum`

I'd argue that this isn't useful enough to include in the public API here, or in any of these functions. It's niche enough that we probably want the user calling `ufunc.reduce` directly

File: numpy/core/src/umath/ufunc_object.c [hunk 4]
```diff
@@ -3275,7 +3284,7 @@ PyUFunc_Reduceat(PyUFuncObject *ufunc, PyArrayObject *arr, PyArrayObject *ind,
                             op_axes_arrays[2]};
     npy_uint32 op_flags[3];
     int i, idim, ndim, otype_final;
-    int need_outer_iterator;
+    int need_outer_iterator = 0;
```
Comment (eric-wieser) [inline numpy/core/src/umath/ufunc_object.c]: Why this change?

Comment (hameerabbasi) [reply numpy/core/src/umath/ufunc_object.c]: There was a warning in GCC, I wanted to get rid of it.

File: numpy/core/fromnumeric.py (hunk 3 above)
Comment (hameerabbasi) [reply numpy/core/fromnumeric.py]: Hmm. I went to a lot of effort to put it in. :-( Anyway, I'd argue it should stay for the NaN-skipping functions because there's no alternative there.

File: numpy/add_newdocs.py (hunk 2 above)
Comment (hameerabbasi) [reply numpy/add_newdocs.py]: Done!

File: numpy/core/fromnumeric.py (hunk 3 above)
Comment (hameerabbasi) [reply numpy/core/fromnumeric.py]: Additionally, it's useful for specifying the value of an All-NaN slice reduction (although I guess you could just do this):

```python
x_max = np.nanmax(x, ...)
x[np.isnan(x)] = value
```

Comment (eric-wieser) [reply numpy/core/fromnumeric.py]: Here's what I propose:

* `np.some_ufunc.reduce(..., initializer=...)`
* `np.sum(...)`
* `np.prod(...)`
* `np.min(..., default=...)` - forward to initializer, match the py3 API
* `np.nanmin(..., default=...)` as above

**Comment by hameerabbasi** [comment]
Seems like this needs a rebase. I'll push as soon as the few discussions reach a consensus. Locally, all tests pass for me.

File: numpy/core/fromnumeric.py (hunk 3 above)
Comment (eric-wieser) [reply numpy/core/fromnumeric.py]: I take it back, `default` and `initializer` mean different things. `max([0], default=10)` is different to `np.max([0], initializer=10)`

Comment (hameerabbasi) [reply numpy/core/fromnumeric.py]: Exactly, as in the discussion above. But to keep uniformity, we should probably either keep it or remove it everywhere. I prefer users should not have to remember/recall which reductions had this and which didn't, they should just instinctively go for either the reduction or `ufunc.reduce`.

I guess to cater for the `nanmax`, etc. case, we could ask users to reshape, add an extra slice, then undo, but that would be excessive.

Comment (eric-wieser) [reply numpy/core/fromnumeric.py]: nanmax absolutely should have an `initializer` argument, since it needs it to deal with all-nan slices of object dtypes. I'm just not sure they're useful on `sum` and `prod`, but maybe leave them in for now, and consult the list.

Either way, my initial remark here is pointing out that this docstring is copied-and-pasted incorrectly

Comment (hameerabbasi) [reply numpy/core/fromnumeric.py]: That's fixed. I see you noticed it was a copypasta.

**Comment by hameerabbasi** [comment]
Hmm. These last failures have nothing at all to do with my code. :/

File: numpy/core/src/umath/ufunc_object.c (hunk 4 above)
Comment (hameerabbasi) [reply numpy/core/src/umath/ufunc_object.c]: Are the warnings/errors because of this change? Some C++ magic going on? Ideally, adding an intitializer shouldn't change anything.

**Comment by hameerabbasi** [comment]
Okay, this time, I really; truly give up. I now believe these failures had nothing at all to do with my code.

**Comment by eric-wieser** [comment]
There are real errors here that relatedto your code: https://ci.appveyor.com/project/charris/numpy/build/1.0.9149/job/kk5xfpmmnfo0gdd1/tests

File: numpy/core/src/umath/ufunc_object.c [hunk 5]
```diff
@@ -2864,7 +2864,16 @@ PyUFunc_Reduce(PyUFuncObject *ufunc, PyArrayObject *arr, PyArrayObject *out,
...
 
     /* Get the identity */
-    identity = _get_identity(ufunc, &reorderable);
+    if (initializer == NULL || initializer == Py_None) {
+        identity = _get_identity(ufunc, &reorderable);
+    } else {
+        /* Since initializer is passed through from the argument parsing,
+           we must increment the reference counter. */
+        identity = initializer;
+        Py_INCREF(initializer);
```
Comment (eric-wieser) [inline numpy/core/src/umath/ufunc_object.c]: This branch doesn't set `reorderable`, which is what is causing (intermittent) bugs.

File: numpy/core/src/umath/ufunc_object.c (hunk 4 above)
Comment (eric-wieser) [reply numpy/core/src/umath/ufunc_object.c]: The warnings are showing up because there's a failure elsewhere - you're probably just not scrolling down far enough to see the error. I'd probably revert this change, and leave it for a future warning cleanup.

File: numpy/core/src/umath/ufunc_object.c [hunk 6]
```diff
@@ -2864,7 +2864,16 @@ PyUFunc_Reduce(PyUFuncObject *ufunc, PyArrayObject *arr, PyArrayObject *out,
     }
 
     /* Get the identity */
-    identity = _get_identity(ufunc, &reorderable);
+    if (initializer == NULL || initializer == Py_None) {
```
[the remark this answers is not in the document]
Comment (hameerabbasi) [reply numpy/core/src/umath/ufunc_object.c]: That's a toughie. Thing is, we pass through `None` for missing values on many counts. If there was a way to default to `np._NoValue` which would go to `NULL`, I'd be for it.

[the remark this answers is not in the document]
Comment (eric-wieser) [reply numpy/core/src/umath/ufunc_object.c]: Maybe something to defer to the mailing list. Let's get the `reorderable` thing passing first

File: numpy/add_newdocs.py [hunk 7]
```diff
@@ -5787,7 +5787,7 @@ def luf(lamdaexpr, *args, **kwargs):
 
 add_newdoc('numpy.core', 'ufunc', ('reduce',
     """
-    reduce(a, axis=0, dtype=None, out=None, keepdims=False)
+    reduce(a, axis=0, dtype=None, out=None, keepdims=False, initialization=None)
```
Comment (eric-wieser) [inline numpy/add_newdocs.py]: Should say `initializer`

File: numpy/core/_methods.py [hunk 8]
```diff
@@ -22,17 +22,17 @@
 
 # avoid keyword arguments to speed up parsing, saves about 15%-20% for very
 # small reductions
-def _amax(a, axis=None, out=None, keepdims=False):
-    return umr_maximum(a, axis, None, out, keepdims)
+def _amax(a, axis=None, out=None, keepdims=False, initializer=None):
```
Comment (eric-wieser) [inline numpy/core/_methods.py]: Oh, the easy fix here is just to write `initializer=um.maximum.identity`, and avoid having `None` mean default

Comment (hameerabbasi) [reply numpy/core/_methods.py]: Would that potentially break duck arrays? Passing `initializer` when it's not supposed to be passed?

File: numpy/add_newdocs.py (hunk 7 above)
Comment (hameerabbasi) [reply numpy/add_newdocs.py]: Done!

**Comment by hameerabbasi** [comment]
> I think you want:
>```
>...
>```

This (combined with replacing `identity` with `initializer` everywhere below) causes datatype failures. One because it can't add `int` and `str` and one because something that should be `bool` isn't.

File: numpy/core/_methods.py (hunk 8 above)
Comment (hameerabbasi) [reply numpy/core/_methods.py]: It might already be handling this down below.

```
if (initializer != Py_None && PyArray_ISOBJECT(arr) && PyArray_SIZE(arr) != 0) {
        Py_DECREF(initializer);
        initializer = Py_None;
        Py_INCREF(initializer);
    }
```

Comment (eric-wieser) [reply numpy/core/_methods.py]: It would affect `__array_ufunc__`, I suppose.

I think there might be a doc section on that that will need updating too.

Comment (hameerabbasi) [reply numpy/core/_methods.py]: Oh, wait, it wouldn't. I retract my objection, those are handled in `fromnumeric.py`

**Comment by eric-wieser** [comment]
Actually I think `initializer=None` is not supported at a bunch of levels anyway, so I don't think changing the default arguments really made any difference. Perhaps `None` was better after all as a "don't use this" flag

**Comment by hameerabbasi** [comment]
This might be slightly off-topic, but:

- What IDE do you recommend for Python API C++.
- Can I see the built devdocs somewhere?

**Comment by hameerabbasi** [comment]
> Actually I think initializer=None is not supported at a bunch of levels anyway,

I'm not so sure. I used `np._NoValue` as the default rather than `None` everywhere, and only added it to kwargs if it wasn't `np._NoValue`. I don't exactly know how to test this (we'll need #8955 merged to know for sure).

File: numpy/core/src/umath/ufunc_object.c [hunk 9]
```diff
@@ -2865,35 +2865,44 @@ PyUFunc_Reduce(PyUFuncObject *ufunc, PyArrayObject *arr, PyArrayObject *out,
 
     /* Get the identity */
     identity = _get_identity(ufunc, &reorderable);
```
Comment (eric-wieser) [inline numpy/core/src/umath/ufunc_object.c]: You need to check if this returns `NULL` like it did before, because that means that `reorderable` wasn't computed either.

Comment (hameerabbasi) [reply numpy/core/src/umath/ufunc_object.c]: That's already done below; I think. I changed `identity` to `initializer` everywhere below, so all checks are now on `initializer`.

File: numpy/core/src/umath/ufunc_object.c [hunk 10]
```diff
@@ -2865,35 +2865,44 @@ PyUFunc_Reduce(PyUFuncObject *ufunc, PyArrayObject *arr, PyArrayObject *out,
...
+    }
+    else {
+        Py_DECREF(identity);
+        Py_INCREF(initializer);  /* match the reference count in the of above */
+    }
+
+
+    if (initializer == NULL) {
         return NULL;
     }
```
Comment (eric-wieser) [inline numpy/core/src/umath/ufunc_object.c]: This needs to happen _before_ you do the swap, otherwise `identity` might have been `NULL` and `DECREF`'d, which would segfault

Comment (hameerabbasi) [reply numpy/core/src/umath/ufunc_object.c]: I've done it (and no tests fail locally), but just so I understand: Does `NULL` mean that something went wrong and the reduction failed?

Comment (eric-wieser) [reply numpy/core/src/umath/ufunc_object.c]: If a C function returns `NULL`, that usually means it set a python exception. If that happens, the right thing to do is usually to clean up, and then return `NULL` all the way back to the calling function.

Have a look at `_get_identity` to see how it can return `NULL`.

**Comment by hameerabbasi** [comment]
Oh. That fixed the CI as well. Thanks!

**Comment by eric-wieser** [comment]
Something to keep on your radar - this argument can be used to fix some cases in `linalg.norm` that invoke `max`

File: numpy/add_newdocs.py [hunk 11]
```diff
@@ -5843,6 +5843,12 @@ def luf(lamdaexpr, *args, **kwargs):
         the result will broadcast correctly against the original `arr`.
 
         .. versionadded:: 1.7.0
+    initializer : scalar, optional
+        The initializer before starting the reduction. The reduction starts
```
Comment (eric-wieser) [inline numpy/add_newdocs.py]: How about

> The value to which the result is initialized before starting the reduction. If not specified, the identity for this ufunc is used. For ufuncs with no identity like `maximum`, a reduction cannot be performed over an empty axis unless this argument is provided.

**Comment by hameerabbasi** [comment]
Which cases specifically? If you open an issue with a specific case I'll look into it. I can assume you're talking about either the L0 (min) or the Linf (max) norm, but not sure what specific cases you mean.

File: numpy/core/fromnumeric.py [hunk 12]
```diff
@@ -2343,11 +2362,21 @@ def amax(a, axis=None, out=None, keepdims=np._NoValue):
     >>> np.nanmax(b)
     4.0
 
+    You can use an initializer to compute the maximum of an empty slice, or
+    to initialize it to a different value:
+
+    >>> np.max([], initializer=-np.inf)
+    -inf
+    >>> np.max([5], initializer=6)
+    6
```
Comment (eric-wieser) [inline numpy/core/fromnumeric.py]: Comparison to the python 3 `max(default=...)` would be good here. Same for `min`

File: numpy/core/src/umath/ufunc_object.c [hunk 13]
```diff
@@ -2863,37 +2863,47 @@ PyUFunc_Reduce(PyUFuncObject *ufunc, PyArrayObject *arr, PyArrayObject *out,
...
+
+    /* Get the initializer */
+    if (initializer == NULL) {
+        initializer = identity;
+    }
+    else {
+        Py_DECREF(identity);
+        Py_INCREF(initializer);  /* match the reference count in the of above */
```
Comment (eric-wieser) [inline numpy/core/src/umath/ufunc_object.c]: `of` should read `if`

File: numpy/core/src/umath/ufunc_object.c [hunk 14]
```diff
@@ -2863,37 +2863,47 @@ PyUFunc_Reduce(PyUFuncObject *ufunc, PyArrayObject *arr, PyArrayObject *out,
         return NULL;
     }
 
-    /* Get the identity */
+    /* Check if identity makes sense */
```
Comment (eric-wieser) [inline numpy/core/src/umath/ufunc_object.c]: Not really accurate. `_get_identity` only fails if something really bad has happened, either:

* Someone has created an invalid ufunc
* `PyInt_FromLong(1)` failed

I'd prefer to leave the original comment

**Comment by eric-wieser** [comment]
@hameerabbasi: I think both are well-defined? Linf = 0, L0 = inf seem pretty reasonable to me. #10655 tries to fix this in a hacky way, but an approach relying on this PR would be much cleaner.

Just some documentation remarks left, then I'll try to compose a message to the list

**Comment by eric-wieser** [comment]
I'm expecting `np.sum([], initializer=None)` to give an error - I think that's ok, but it would be good to test it.

> We run into the same issue there (although what you're saying is more reasonable than here)

I think that argument isn't valid, because the norms are defined over the real numbers, so the set of allowable values is known. But it's a good point to raise, and one I hadn't thought of. If you want to continue that discussion, create a new issue about it - I can't seem to find the old one.

File: numpy/add_newdocs.py (hunk 11 above)
Comment (hameerabbasi) [reply numpy/add_newdocs.py]: > If None

Would "if not supplied" be better for object arrays in the future?

Comment (eric-wieser) [reply numpy/add_newdocs.py]: My comment above describes what actually happens if `None` is passed, I think - it may not be what we want, but it's what we have right now.

I think the eventual fix here is to provide `np.ufunc.NoIdentity` as a sentinel that we use in place of the current `None`

**Comment by hameerabbasi** [comment]
> I'm expecting np.sum([], initializer=None) to give an error - I think that's ok, but it would be good to test it.

It does.

```python
>>> np.sum([], initializer=None)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/hameerabbasi/PycharmProjects/numpy/numpy/core/fromnumeric.py", line 1905, in sum
    out=out, **kwargs)
  File "/Users/hameerabbasi/PycharmProjects/numpy/numpy/core/_methods.py", line 35, in _sum
    return umr_sum(a, axis, dtype, out, keepdims, initializer)
ValueError: zero-size array to reduction operation add which has no identity
```

I've documented it:

```
If ``None`` is given to a reduction for an empty array, it will raise an error.
```

**Comment by hameerabbasi** [comment]
Let me know when no further changes are desired and I'll commit. Don't want to hog the CI too much.

File: numpy/add_newdocs.py (hunk 11 above)
Comment (hameerabbasi) [reply numpy/add_newdocs.py]: I think that should technically go to #8955.

Comment (eric-wieser) [reply numpy/add_newdocs.py]: One final remark for this docstring
```
If arr.dtype is object, then the initializer is _only_ used when the reduction is empty
```

This is perhaps not ideal, but importantly it _is_ useful enough to fix `linalg.norm`

**Comment by eric-wieser** [comment]
I wouldn't worry too much about the CI - timezones tend to even things out.

File: numpy/add_newdocs.py (hunk 11 above)
Comment (hameerabbasi) [reply numpy/add_newdocs.py]: I expected this to not work for empty `object` arrays at all, but it seems you're right! I've updated the docstring.

```python
>>> class A(object):
...     pass
... 
>>> np.sum(np.array([], dtype=object), initializer=A())
<A object at 0x1023abf28>
```

Comment (eric-wieser) [reply numpy/add_newdocs.py]: I was expecting exactly the same thing, and was half-way through writing about how that was going to be really annoying before realizing we can sort-of get away with it

File: numpy/add_newdocs.py [hunk 15]
```diff
@@ -5844,9 +5844,12 @@ def luf(lamdaexpr, *args, **kwargs):
...
         .. versionadded:: 1.7.0
     initializer : scalar, optional
-        The initializer before starting the reduction. The reduction starts
-        with this value rather than the identity. This can also be used to calculate
-        reductions when the slice is empty.
+        The value to which the result is initialized before starting the reduction.
+        Defaults to the `~numpy.ufunc.identity` of the ufunc.
+        If ``None`` is given, then the first element of the reduction is used,
+        and an error is thrown if the reduction is empty. If ``None`` is given to a
+        reduction for a empty axes, it will raise an error. If ``a.dtype`` is ``object``,
```
Comment (eric-wieser) [inline numpy/add_newdocs.py]: Aren't these two sentences the same?

>  If ``None`` is given, then the first element of the reduction is used, and an error is thrown if the reduction is empty.

and

> If ``None`` is given to a reduction for a empty axes, it will raise an error.

Comment (hameerabbasi) [reply numpy/add_newdocs.py]: Fixed!

**Comment by hameerabbasi** [comment]
> norms are defined over the real numbers

1. They're defined over an arbitrary set of numbers/vectors/complexes/Cayley-Dickson numbers etc.
2. The input set of Linf might actually reduce to a set of reals that's _not_ bounded below by zero. It might be bounded below by some other quantity.
3. L0 doesn't have this issue, it's a sum rather than a min (as I incorrectly assumed).

File: numpy/lib/nanfunctions.py [hunk 16]
```diff
@@ -395,11 +415,12 @@ def nanmax(a, axis=None, out=None, keepdims=np._NoValue):
...
-        mask = np.all(mask, axis=axis, **kwargs)
-        if np.any(mask):
-            res = _copyto(res, np.nan, mask)
-            warnings.warn("All-NaN axis encountered", RuntimeWarning, stacklevel=2)
+        if initializer is np._NoValue:
+            # Check for all-NaN axis
+            mask = np.all(mask, axis=axis, **kwargs)
+            if np.any(mask):
+                res = _copyto(res, np.nan, mask)
+                warnings.warn("All-NaN axis encountered", RuntimeWarning, stacklevel=2)
```
Comment (eric-wieser) [inline numpy/lib/nanfunctions.py]: What if `initializer` is NaN?

File: numpy/core/tests/test_ufunc.py [hunk 17]
```diff
@@ -941,6 +946,27 @@ def test_identityless_reduction_noncontig_unaligned(self):
         a = a[1:, 1:, 1:]
         self.check_identityless_reduction(a)
 
+    def test_initializer_reduction(self):
+        # np.minimum.reduce is an identityless reduction
+
+        # For cases like np.maximum(np.abs(...), identity=0)
```
Comment (eric-wieser) [inline numpy/core/tests/test_ufunc.py]: I think this should say `np.max(np.asb(...), initializer=0)`

File: numpy/lib/nanfunctions.py (hunk 16 above)
Comment (hameerabbasi) [reply numpy/lib/nanfunctions.py]: Hmm. I was unsure what to do there, actually. On one hand, it may mean that the user WANTS `nan` values in the output. On the other, it would give `nan`s.

File: numpy/core/fromnumeric.py [hunk 18]
```diff
@@ -2529,10 +2641,16 @@ def prod(a, axis=None, dtype=None, out=None, keepdims=np._NoValue):
     >>> np.prod(x).dtype == int
     True
 
+    You can also initialize the product by a different value.
```
Comment (eric-wieser) [inline numpy/core/fromnumeric.py]: I'd argue it's "initialize with", not "initialize by"

File: numpy/core/fromnumeric.py [hunk 19]
```diff
@@ -1895,6 +1905,56 @@ def sum(a, axis=None, dtype=None, out=None, keepdims=np._NoValue):
...
+
+    """
+    arr = asanyarray(a)
+    kwargs = {}
+    if keepdims is not np._NoValue:
+        kwargs['keepdims'] = keepdims
+    return arr.any(axis=axis, out=out, **kwargs)
+
+
+def alltrue(a, axis=None, out=None, keepdims=np._NoValue):
```
Comment (eric-wieser) [inline numpy/core/fromnumeric.py]: Bad rebase here

**Review by eric-wieser — DISMISSED** [review]
Something went wrong with your rebase

File: numpy/lib/nanfunctions.py (hunk 16 above)
Comment (eric-wieser) [reply numpy/lib/nanfunctions.py]: Fine as is for now I think.

File: numpy/core/fromnumeric.py [hunk 20]
```diff
@@ -2230,6 +2290,13 @@ def amax(a, axis=None, out=None, keepdims=np._NoValue):
         sub-class' method does not implement `keepdims` any
         exceptions will be raised.
 
+    initializer : scalar, optional
+        The initializer for this maximum. Can also be used to compute the
+        maximum of an empty slice.
```
Comment (eric-wieser) [inline numpy/core/fromnumeric.py]: Perhaps we should say `` See `~numpy.ufunc.reduce` for details`` or something to indicate that this is a simplified summary.

Comment (hameerabbasi) [reply numpy/core/fromnumeric.py]: Done!

File: numpy/core/fromnumeric.py (hunk 18 above)
Comment (hameerabbasi) [reply numpy/core/fromnumeric.py]: Done!

File: numpy/core/tests/test_ufunc.py (hunk 17 above)
Comment (hameerabbasi) [reply numpy/core/tests/test_ufunc.py]: Done!

File: numpy/lib/nanfunctions.py (hunk 16 above)
Comment (eric-wieser) [reply numpy/lib/nanfunctions.py]: Works for me

Comment (hameerabbasi) [reply numpy/lib/nanfunctions.py]: I fixed the potential issue. Wasn't too hard. :-)

File: numpy/core/fromnumeric.py [hunk 21]
```diff
@@ -1895,6 +1905,22 @@ def sum(a, axis=None, dtype=None, out=None, keepdims=np._NoValue):
                          out=out, **kwargs)
 
 
+def product(a, axis=None, dtype=None, out=None, keepdims=np._NoValue, initializer=np._NoValue):
```
Comment (eric-wieser) [inline numpy/core/fromnumeric.py]: This function should be removed - it's now defined with `*args, **kwargs` at the bottom of the file.

File: numpy/lib/nanfunctions.py [hunk 22]
```diff
@@ -644,7 +678,12 @@ def nanprod(a, axis=None, dtype=None, out=None, keepdims=np._NoValue):
 
     """
     a, mask = _replace_nan(a, 1)
-    return np.prod(a, axis=axis, dtype=dtype, out=out, keepdims=keepdims)
+
+    if np.isnan(initializer):
```
Comment (eric-wieser) [inline numpy/lib/nanfunctions.py]: `isnan` doesn't work for `np._NoValue`. I'm not sure it's clear that nanprod` should treat initializer specially, especially since you don't document this. Keep it simple for now, without this check, I'd say.

File: numpy/lib/nanfunctions.py [hunk 23]
```diff
@@ -877,7 +916,7 @@ def _nanmedian1d(arr1d, overwrite_input=False):
     See nanmedian for parameter usage
     """
     arr1d, overwrite_input = _remove_nan_1d(arr1d,
-        overwrite_input=overwrite_input)
+                                            overwrite_input=overwrite_input)
```
Comment (eric-wieser) [inline numpy/lib/nanfunctions.py]: nit: I preferred the previous indentation because it's more robust to variable renames.

Comment (hameerabbasi) [reply numpy/lib/nanfunctions.py]: My IDE's auto-format did it. :/

File: numpy/lib/nanfunctions.py [hunk 24]
```diff
@@ -644,7 +678,12 @@ def nanprod(a, axis=None, dtype=None, out=None, keepdims=np._NoValue):
 
     """
     a, mask = _replace_nan(a, 1)
-    return np.prod(a, axis=axis, dtype=dtype, out=out, keepdims=keepdims)
+
+    if initializer != np._NoValue:
```
Comment (eric-wieser) [inline numpy/lib/nanfunctions.py]: Should use `is not` with `np._NoValue`

File: numpy/lib/nanfunctions.py [hunk 25]
```diff
@@ -616,6 +647,9 @@ def nanprod(a, axis=None, dtype=None, out=None, keepdims=np._NoValue):
         If True, the axes which are reduced are left in the result as
         dimensions with size one. With this option, the result will
         broadcast correctly against the original `arr`.
+    initializer : scalar, optional
+        The value to initialize the product to. See `~numpy.ufunc.reduce`
+        for details.
```
Comment (eric-wieser) [inline numpy/lib/nanfunctions.py]: Missing `.. versionadded`

File: numpy/lib/nanfunctions.py [hunk 26]
```diff
@@ -327,6 +337,12 @@ def nanmax(a, axis=None, out=None, keepdims=np._NoValue):
         does not implement `keepdims` any exceptions will be raised.
 
         .. versionadded:: 1.8.0
+    initializer : scalar, optional
+        The value to initialize the maximum to. This can also be used to compute
+        the maximum of empty slices. If the initializer is given, no warning is
+        issued. See `~numpy.ufunc.reduce` for details.
```
Comment (eric-wieser) [inline numpy/lib/nanfunctions.py]: is issued **for an all-NaN slice**.

File: numpy/core/fromnumeric.py [hunk 27]
```diff
@@ -1827,6 +1827,10 @@ def sum(a, axis=None, dtype=None, out=None, keepdims=np._NoValue):
         `ndarray`, however any non-default value will be.  If the
         sub-class' method does not implement `keepdims` any
         exceptions will be raised.
+    initializer : scalar, optional
+        The initializer for this sum. See `~numpy.ufunc.reduce` for details.
```
Comment (mhvk) [inline numpy/core/fromnumeric.py]: Repeating the term is not helpful for those who do not understand what it does. Maybe
"Starting value for the sum. See..."

File: numpy/core/fromnumeric.py [hunk 28]
```diff
@@ -2230,6 +2239,13 @@ def amax(a, axis=None, out=None, keepdims=np._NoValue):
         sub-class' method does not implement `keepdims` any
         exceptions will be raised.
 
+    initializer : scalar, optional
+        The initializer for this maximum. Can also be used to compute the
```
Comment (mhvk) [inline numpy/core/fromnumeric.py]: See above. Maybe "Minimum value for the maximum. Needs to be present to allow calculation on an empty slice."

File: numpy/core/fromnumeric.py [hunk 29]
```diff
@@ -2282,11 +2298,28 @@ def amax(a, axis=None, out=None, keepdims=np._NoValue):
     >>> np.nanmax(b)
     4.0
 
+    You can use an initializer to compute the maximum of an empty slice, or
+    to initialize it to a different value:
+
+    >>> np.max([], initializer=-np.inf)
+    -inf
+    >>> np.max([50], initializer=25)
```
Comment (mhvk) [inline numpy/core/fromnumeric.py]: Maybe use something a bit more likely here, which shows that the initializer is just included in the comparison. E.g.,
```
np.max([[-50], [10]], axis=-1, initializer=0)
[[0],
 [10]]
```
(guessing at formatting)

File: numpy/core/fromnumeric.py [hunk 30]
```diff
@@ -2282,11 +2298,28 @@ def amax(a, axis=None, out=None, keepdims=np._NoValue):
...
+    50
+
+    Notice that this isn't the same as Python's ``default`` argument.
```
Comment (mhvk) [inline numpy/core/fromnumeric.py]: Be explicit in what is different: "Notice that the initializer is used as one of the elements for which the maximum is determined, unlike for the ``default`` argument Python's `max` function, which is only used for empty iterables."

File: numpy/core/fromnumeric.py [hunk 31]
```diff
@@ -1874,10 +1878,16 @@ def sum(a, axis=None, dtype=None, out=None, keepdims=np._NoValue):
     >>> np.ones(128, dtype=np.int8).sum(dtype=np.int8)
     -128
 
+    You can also use initialize the sum with a different value:
```
Comment (mhvk) [inline numpy/core/fromnumeric.py]: Maybe "You can also start the sum with an initial value other than 0:"

File: numpy/core/fromnumeric.py [hunk 32]
```diff
@@ -2331,6 +2364,12 @@ def amin(a, axis=None, out=None, keepdims=np._NoValue):
         sub-class' method does not implement `keepdims` any
         exceptions will be raised.
 
+    initializer : scalar, optional
+        The initializer for this minimum. Can also be used to compute the
```
Comment (mhvk) [inline numpy/core/fromnumeric.py]: See above (here and below)

File: numpy/core/fromnumeric.py [hunk 33]
```diff
@@ -2472,6 +2529,10 @@ def prod(a, axis=None, dtype=None, out=None, keepdims=np._NoValue):
         `ndarray`, however any non-default value will be.  If the
         sub-class' method does not implement `keepdims` any
         exceptions will be raised.
+    initializer : scalar, optional
+        The initializer for this product. See `~numpy.ufunc.reduce` for details.
```
Comment (mhvk) [inline numpy/core/fromnumeric.py]: See comment above for `sum`

**Review by mhvk — COMMENTED** [review]
This is a nice addition. Some comments on the docstrings, which I think can be clearer. (will continue the review of the rest, but sending this now since changes are being made...)

File: numpy/core/src/umath/ufunc_object.c [hunk 34]
```diff
@@ -2868,32 +2868,42 @@ PyUFunc_Reduce(PyUFuncObject *ufunc, PyArrayObject *arr, PyArrayObject *out,
     if (identity == NULL) {
         return NULL;
     }
+
+    /* Get the initializer */
+    if (initializer == NULL) {
+        initializer = identity;
```
Comment (mhvk) [inline numpy/core/src/umath/ufunc_object.c]: I think the `identity` should only be gotten here, inside the loop. After all, it is not used if an `initializer` is passed on, so one might as well skip getting it.

File: numpy/core/src/umath/ufunc_object.c [hunk 35]
```diff
@@ -2868,32 +2868,42 @@ PyUFunc_Reduce(PyUFuncObject *ufunc, PyArrayObject *arr, PyArrayObject *out,
...
+    }
+    else {
+        Py_DECREF(identity);
```
Comment (mhvk) [inline numpy/core/src/umath/ufunc_object.c]: If we do as suggested above, the `Py_DECREF` can obviously be removed.

File: numpy/core/src/umath/ufunc_object.c [hunk 36]
```diff
@@ -2868,32 +2868,42 @@ PyUFunc_Reduce(PyUFuncObject *ufunc, PyArrayObject *arr, PyArrayObject *out,
...
+
     /*
      * The identity for a dynamic dtype like
      * object arrays can't be used in general
      */
-    if (identity != Py_None && PyArray_ISOBJECT(arr) && PyArray_SIZE(arr) != 0) {
-        Py_DECREF(identity);
-        identity = Py_None;
-        Py_INCREF(identity);
+    if (initializer != Py_None && PyArray_ISOBJECT(arr) && PyArray_SIZE(arr) != 0) {
```
Comment (mhvk) [inline numpy/core/src/umath/ufunc_object.c]: Why do we do this? I think it is actually rather useful to be able to pass on something else than `None` (but can see that this would not be the case with a built-in `identity`)

File: numpy/add_newdocs.py [hunk 37]
```diff
@@ -5874,7 +5882,22 @@ def luf(lamdaexpr, *args, **kwargs):
...
-
+           
+    You can use the initializer argument to initialize the reduction to a
+    different value.
+    
+    >>> np.add.reduce(np.ones((2, 2, 2)), axis=(0, 2), initializer=10)
+    array([14., 14.])
+    >>> np.add.reduce([10], initializer=5)
+    15
+    >>> np.add.reduce(np.ones((2, 2, 2)), axis=(0, 2), initializer=10)
```
[the remark this answers is not in the document]
Comment (hameerabbasi) [reply numpy/add_newdocs.py]: To show that it is only counted once per output element, instead of once per axis.

**Review by mhvk — CHANGES_REQUESTED** [review]
Some small comments about ordering, and a larger one about `dtype=object` -- if one passes in the `initializer`, shouldn't it just be used?

Also, more importantly, to be sure this works for classes that define `__array_ufunc__`, could you add a test case for those? (in `test_umath`, `test_ufunc_override_methods`)

File: numpy/add_newdocs.py (hunk 37 above)
[the remark this answers is not in the document]
Comment (mhvk) [reply numpy/add_newdocs.py]: I'm still confused: this example is exactly the same as that two lines above.

File: numpy/core/src/umath/ufunc_object.c (hunk 34 above)
Comment (hameerabbasi) [reply numpy/core/src/umath/ufunc_object.c]: We need `reorderable`, which we get from the same function. I did that at first but was having failures.

File: numpy/core/src/umath/ufunc_object.c (hunk 35 above)
Comment (hameerabbasi) [reply numpy/core/src/umath/ufunc_object.c]: See comment to above.

File: numpy/core/src/umath/ufunc_object.c (hunk 36 above)
Comment (hameerabbasi) [reply numpy/core/src/umath/ufunc_object.c]: I'm leaving supporting object arrays to #8955, all the object-specific cases will be handled there.

Comment (hameerabbasi) [reply numpy/core/src/umath/ufunc_object.c]: It's the same as the logic before, just on `initializer` instead of identity.

File: numpy/add_newdocs.py (hunk 37 above)
[the remark this answers is not in the document]
Comment (hameerabbasi) [reply numpy/add_newdocs.py]: Ahh... My mistake. Fixed.

File: numpy/core/src/umath/ufunc_object.c (hunk 34 above)
Comment (mhvk) [reply numpy/core/src/umath/ufunc_object.c]: Ah, that makes sense. That's what one gets for coming to the discussion late...

File: numpy/core/src/umath/ufunc_object.c (hunk 36 above)
Comment (mhvk) [reply numpy/core/src/umath/ufunc_object.c]: OK, fair enough. Could you add a comment in the code still?

Comment (hameerabbasi) [reply numpy/core/src/umath/ufunc_object.c]: One is already there. :-)

File: numpy/add_newdocs.py [hunk 38]
```diff
@@ -5874,7 +5882,20 @@ def luf(lamdaexpr, *args, **kwargs):
...
+    You can use the initializer argument to initialize the reduction to a
+    different value.
+    
+    >>> np.add.reduce([10], initializer=5)
+    15
+    >>> np.add.reduce(np.ones((2, 2, 2)), axis=(0, 2), initializer=10)
+    array([14., 14.])
+    
+    The initializer argument can be used to calculate empty reductions for
+    ufuncs that don't support it as well.
```
Comment (eric-wieser) [inline numpy/add_newdocs.py]: Would maybe read better as "allows reductions of empty arrays where they would normally fail" - I don't like the `as well` at the end here.

Could also show how `np.minimum.reduce([])` fails

**Comment by hameerabbasi** [comment]
Is this ready to send to the mailing list?

**Comment by hameerabbasi** [comment]
@ahaldane That is an excellent point. In general, I'm of the view that `gufunc`s themselves should be made as flexible as possible, to allow as many operations to be made into `gufunc`s as possible. Since it was your idea, I think you should open the issue of allowing arbitrary kwargs.

**Comment by eric-wieser** [comment]
Needs rebase

**Comment by hameerabbasi** [comment]
Done rebase.

File: numpy/lib/nanfunctions.py [hunk 39]
```diff
@@ -1190,8 +1229,8 @@ def _nanquantile_1d(arr1d, q, overwrite_input=False, interpolation='linear'):
     Private function for rank 1 arrays. Compute quantile ignoring NaNs.
     See nanpercentile for parameter usage
     """
-    arr1d, overwrite_input = _remove_nan_1d(arr1d,
-        overwrite_input=overwrite_input)
+    arr1d, overwrite_input = _remove_nan_1d(
+        arr1d, overwrite_input=overwrite_input)
```
Comment (eric-wieser) [inline numpy/lib/nanfunctions.py]: I agree with this wrapping, but would prefer to see it left to another PR

File: numpy/lib/tests/test_nanfunctions.py [hunk 40]
```diff
@@ -83,6 +83,17 @@ def test_result_values(self):
...
+    def test_initializer(self):
+        mat1 = np.array([np.nan] * 9).reshape(3, 3)
+        mat2 = mat1.copy()
+        mat2[1] = 1
+
+        assert_equal(np.nanmin(mat1, initializer=5), 5.0)
+        assert_equal(np.nanmax(mat1, initializer=6), 6.0)
+
+        assert_equal(np.nanmin(mat2, initializer=5), 1.0)
+        assert_equal(np.nanmax(mat2, initializer=6), 6.0)
```
Comment (eric-wieser) [inline numpy/lib/tests/test_nanfunctions.py]: Let's not use `mat` to avoid confusion with `np.matrix`. `arr` or `a` is pretty typical in tests

File: numpy/lib/nanfunctions.py (hunk 39 above)
Comment (hameerabbasi) [reply numpy/lib/nanfunctions.py]: Done.

File: numpy/lib/tests/test_nanfunctions.py (hunk 40 above)
Comment (hameerabbasi) [reply numpy/lib/tests/test_nanfunctions.py]: Done.

**Comment by hameerabbasi** [comment]
Hmm, it seems my last commit isn't registering in the diff for some reason. It fixes your comment about line-wrapping.

**Comment by hameerabbasi** [comment]
@eric-wieser Could you somehow re-trigger the diff computation? It seems my last commit wasn't taken into account.

@mhvk Do you still have changes to request? Because I think I met your original questions.

File: numpy/lib/nanfunctions.py (hunk 39 above)
Comment (eric-wieser) [reply numpy/lib/nanfunctions.py]: It's showing in the diff just fine - you just did it in two places, and only reverted it in one

Comment (hameerabbasi) [reply numpy/lib/nanfunctions.py]: Ahh, my bad. Fixed.

File: numpy/core/fromnumeric.py [hunk 41]
```diff
@@ -1905,7 +1913,7 @@ def sum(a, axis=None, dtype=None, out=None, keepdims=np._NoValue):
             return out
         return res
 
-    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims)
+    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims, initializer=initializer)
```
Comment (mhvk) [inline numpy/core/fromnumeric.py]: This line is too long.

File: numpy/core/fromnumeric.py [hunk 42]
```diff
@@ -2286,11 +2301,25 @@ def amax(a, axis=None, out=None, keepdims=np._NoValue):
...
+    maximum is determined, unlike for the default argument Python's max
+    function, which is only used for empty iterables.
+
+    >>> np.max([5], initializer=6)
+    6
+    >>> max([5], default=6)
+    5
     """
-    return _wrapreduction(a, np.maximum, 'max', axis, None, out, keepdims=keepdims)
+    return _wrapreduction(a, np.maximum, 'max', axis, None, out, keepdims=keepdims, initializer=initializer)
```
Comment (mhvk) [inline numpy/core/fromnumeric.py]: Also too long.

File: numpy/core/fromnumeric.py [hunk 43]
```diff
@@ -2234,6 +2242,13 @@ def amax(a, axis=None, out=None, keepdims=np._NoValue):
         sub-class' method does not implement `keepdims` any
         exceptions will be raised.
 
+    initializer : scalar, optional
+        The maximum value of an output element. Must be present to allow
```
Comment (mhvk) [inline numpy/core/fromnumeric.py]: This actually becomes the minimum value the maximum will have, right? Maybe rephrase to make that clearer (and the same for `amin` below).

...

Must admit I cannot easily think of a better way of phrasing this. But at least change maximum -> minimum here.

File: numpy/core/fromnumeric.py [hunk 44]
```diff
@@ -2374,8 +2409,21 @@ def amin(a, axis=None, out=None, keepdims=np._NoValue):
     >>> np.nanmin(b)
     0.0
 
+    >>> np.min([[-50], [10]], axis=-1, initializer=0)
+    array([-50,   0])
+
+    Notice that the initializer is used as one of the elements for which the
+    maximum is determined, unlike for the default argument Python's max
```
Comment (mhvk) [inline numpy/core/fromnumeric.py]: maximum -> minimum, max->min (too much copy&paste...)

File: numpy/core/fromnumeric.py [hunk 45]
```diff
@@ -2374,8 +2409,21 @@ def amin(a, axis=None, out=None, keepdims=np._NoValue):
...
+
+    Notice that this isn't the same as Python's ``default`` argument.
+
+    >>> np.min([6], initializer=5)
+    5
+    >>> min([6], default=5)
+    6
     """
-    return _wrapreduction(a, np.minimum, 'min', axis, None, out, keepdims=keepdims)
+    return _wrapreduction(a, np.minimum, 'min', axis, None, out, keepdims=keepdims, initializer=initializer)
```
Comment (mhvk) [inline numpy/core/fromnumeric.py]: too long

File: numpy/core/fromnumeric.py [hunk 46]
```diff
@@ -2508,8 +2560,12 @@ def prod(a, axis=None, dtype=None, out=None, keepdims=np._NoValue):
     >>> np.prod(x).dtype == int
     True
 
+    You can also start the product with a value other than one:
+
+    >>> np.prod([1, 2], initializer=5)
+    10
     """
-    return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out, keepdims=keepdims)
+    return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out, keepdims=keepdims, initializer=initializer)
```
Comment (mhvk) [inline numpy/core/fromnumeric.py]: line too long

File: numpy/core/src/umath/override.c [hunk 47]
```diff
@@ -123,11 +123,11 @@ normalize_reduce_args(PyUFuncObject *ufunc, PyObject *args,
     npy_intp nargs = PyTuple_GET_SIZE(args);
     npy_intp i;
     PyObject *obj;
-    static char *kwlist[] = {"array", "axis", "dtype", "out", "keepdims"};
+    static char *kwlist[] = {"array", "axis", "dtype", "out", "keepdims", "initializer"};
```
Comment (mhvk) [inline numpy/core/src/umath/override.c]: line seems too long.

File: numpy/core/src/umath/ufunc_object.c [hunk 48]
```diff
@@ -2831,14 +2831,14 @@ reduce_loop(NpyIter *iter, char **dataptrs, npy_intp *strides,
  */
 static PyArrayObject *
 PyUFunc_Reduce(PyUFuncObject *ufunc, PyArrayObject *arr, PyArrayObject *out,
-        int naxes, int *axes, PyArray_Descr *odtype, int keepdims)
+        int naxes, int *axes, PyArray_Descr *odtype, int keepdims, PyObject *initializer)
```
Comment (mhvk) [inline numpy/core/src/umath/ufunc_object.c]: line again seems too long

File: numpy/lib/nanfunctions.py [hunk 49]
```diff
@@ -25,12 +25,11 @@
 import numpy as np
 from numpy.lib import function_base
 
-
 __all__ = [
     'nansum', 'nanmax', 'nanmin', 'nanargmax', 'nanargmin', 'nanmean',
     'nanmedian', 'nanpercentile', 'nanvar', 'nanstd', 'nanprod',
     'nancumsum', 'nancumprod'
-    ]
+]
```
Comment (mhvk) [inline numpy/lib/nanfunctions.py]: Total nitpick: can we either not change this (and not remove the empty line above), or move the `]` to the end of the list, i.e., behind `nancumprod`?

File: numpy/lib/nanfunctions.py [hunk 50]
```diff
@@ -219,6 +218,12 @@ def nanmin(a, axis=None, out=None, keepdims=np._NoValue):
         does not implement `keepdims` any exceptions will be raised.
 
         .. versionadded:: 1.8.0
+    initializer : scalar, optional
+        The maximum value of an output element. Must be present to allow
```
Comment (mhvk) [inline numpy/lib/nanfunctions.py]: See comment above.

File: numpy/lib/nanfunctions.py [hunk 51]
```diff
@@ -380,26 +396,31 @@ def nanmax(a, axis=None, out=None, keepdims=np._NoValue):
...
-        if np.isnan(res).any():
+        if initializer is np._NoValue and np.isnan(res).any():
             warnings.warn("All-NaN slice encountered", RuntimeWarning, stacklevel=2)
     else:
         # Slow, but safe for subclasses of ndarray
         a, mask = _replace_nan(a, -np.inf)
         res = np.amax(a, axis=axis, out=out, **kwargs)
         if mask is None:
             return res
-
```
Comment (mhvk) [inline numpy/lib/nanfunctions.py]: Just keep the line (it is there for `min` as well).

File: numpy/lib/nanfunctions.py [hunk 52]
```diff
@@ -492,7 +513,7 @@ def nanargmax(a, axis=None):
     return res
 
 
-def nansum(a, axis=None, dtype=None, out=None, keepdims=np._NoValue):
+def nansum(a, axis=None, dtype=None, out=None, keepdims=np._NoValue, initializer=np._NoValue):
```
Comment (mhvk) [inline numpy/lib/nanfunctions.py]: line too long

File: numpy/lib/nanfunctions.py [hunk 53]
```diff
@@ -579,10 +604,15 @@ def nansum(a, axis=None, dtype=None, out=None, keepdims=np._NoValue):
 
     """
     a, mask = _replace_nan(a, 0)
-    return np.sum(a, axis=axis, dtype=dtype, out=out, keepdims=keepdims)
+
+    if initializer is not np._NoValue:
+        initializer, mask = _replace_nan(initializer, 0)
```
Comment (mhvk) [inline numpy/lib/nanfunctions.py]: Since the mask is not used, maybe `initializer, _  = _replace_nan(initializer, 0)`

Actually, do we want to bother to replace it at all? Why let the user silently pass in nonsense?

File: numpy/lib/nanfunctions.py [hunk 54]
```diff
@@ -644,7 +678,12 @@ def nanprod(a, axis=None, dtype=None, out=None, keepdims=np._NoValue):
 
     """
     a, mask = _replace_nan(a, 1)
-    return np.prod(a, axis=axis, dtype=dtype, out=out, keepdims=keepdims)
+
+    if initializer is not np._NoValue:
+        initializer, mask = _replace_nan(initializer, 1)
```
Comment (mhvk) [inline numpy/lib/nanfunctions.py]: Same as above - I would remove this altogether.

**Review by mhvk — COMMENTED** [review]
@hameerabbasi - looks very good and all my remaining comments are nitpicks, except for the fact that I don't think we should replace `initializer=np.nan` with `0` - don't silently accept nonsense!

File: numpy/lib/nanfunctions.py (hunk 53 above)
Comment (hameerabbasi) [reply numpy/lib/nanfunctions.py]: The reasoning here is; since these are `nan`-skipping reductions, they should skip the `nan` initializer as well. Otherwise, they won't have the effect of being nan-skipping, would they?

File: numpy/lib/nanfunctions.py (hunk 50 above)
Comment (hameerabbasi) [reply numpy/lib/nanfunctions.py]: Actually, this one is correct. It's for `nanmin`, so it IS the maximum value.

File: numpy/lib/nanfunctions.py (hunk 53 above)
Comment (mhvk) [reply numpy/lib/nanfunctions.py]: But why apply that to the initializer? I just don't see any use case for the increased complexity, and I do see a case for giving an error/warning when input is unexpected! In other words, I think most if not all cases where `initializer=np.nan` are going to be erroneous, and this might as well lead to an error.

Comment (hameerabbasi) [reply numpy/lib/nanfunctions.py]: I'm not sure, but I do agree this is worth discussing. Maybe we can defer to someone else for this case?

File: numpy/lib/nanfunctions.py (hunk 50 above)
Comment (mhvk) [reply numpy/lib/nanfunctions.py]: This mostly referred to the initial comment of asking for a rewording. But I then later realized I did not have a good concrete suggestion... Anyway, at a minimum, just fix the wrong one for maximum above.

File: numpy/lib/nanfunctions.py (hunk 53 above)
Comment (mhvk) [reply numpy/lib/nanfunctions.py]: @eric-wieser - what do you think? Does it make sense to replace `nan` in the initlializer with `0` here, or should we just let things fail for such input?

Comment (eric-wieser) [reply numpy/lib/nanfunctions.py]: We should choose such that

```
func(arr_1, initializer=func(arr_2, initializer=x))
```
is always treated the same as

```
func(concatenate((arr_1, arr_2)), initializer=x)
```

I think this is maintained in either case?

File: numpy/lib/nanfunctions.py (hunk 50 above)
Comment (eric-wieser) [reply numpy/lib/nanfunctions.py]: > Anyway, at a minimum

Unhelpful choice of words...

File: numpy/lib/nanfunctions.py (hunk 53 above)
Comment (hameerabbasi) [reply numpy/lib/nanfunctions.py]: For @mhvk's suggestion, it isn't maintained for `initializer=nan`

File: numpy/lib/tests/test_nanfunctions.py [hunk 55]
```diff
@@ -83,6 +83,17 @@ def test_result_values(self):
...
+    def test_initializer(self):
+        arr1 = np.array([np.nan] * 9).reshape(3, 3)
+        arr2 = arr1.copy()
+        arr2[1] = 1
+
+        assert_equal(np.nanmin(arr1, initializer=5), 5.0)
+        assert_equal(np.nanmax(arr1, initializer=6), 6.0)
+
+        assert_equal(np.nanmin(arr2, initializer=5), 1.0)
+        assert_equal(np.nanmax(arr2, initializer=6), 6.0)
```
Comment (eric-wieser) [inline numpy/lib/tests/test_nanfunctions.py]: Can you add some tests of `np.nanmax([], initializer=np.nan)`, `np.nanmax([np.nan], initializer=np.nan)`, and `np.nanmax([np.nan], initializer=0)`?

Comment (hameerabbasi) [reply numpy/lib/tests/test_nanfunctions.py]: What me and @mhvk differ on is the behavior of `np.nanmax([0], initializer=np.nan)`. I believe this should be zero, he says it should err or warn; and return `nan`.

Comment (hameerabbasi) [reply numpy/lib/tests/test_nanfunctions.py]: And sure, I can add those tests. Not immediately though. It'd be best if you could settle this debate first.

File: numpy/lib/nanfunctions.py (hunk 53 above)
Comment (eric-wieser) [reply numpy/lib/nanfunctions.py]: Do you mean for `x == nan`? Can you show the code that fails that test?

Comment (mhvk) [reply numpy/lib/nanfunctions.py]: If in both cases one gets an exception, that would be fine too!

File: numpy/lib/tests/test_nanfunctions.py (hunk 55 above)
Comment (mhvk) [reply numpy/lib/tests/test_nanfunctions.py]: Just to be clear, in my ideal world `initializer=np.nan` just raises an exception. I haven't checked what it actually does if you remove the turn-it-into-0 stanza.

Comment (eric-wieser) [reply numpy/lib/tests/test_nanfunctions.py]: Perhaps we should leave the nanfunctions to another PR?

Comment (hameerabbasi) [reply numpy/lib/tests/test_nanfunctions.py]: > Perhaps we should leave the nanfunctions to another PR?

I'm okay with that.

> Just to be clear, in my ideal world initializer=np.nan just raises an exception. I haven't checked what it actually does if you remove the turn-it-into-0 stanza.

It will make everything `nan`.

Comment (mhvk) [reply numpy/lib/tests/test_nanfunctions.py]: > It will make everything `nan`.

Not my ideal world, but I think preferable to silently changing it. But maybe it is indeed best to just move the `nanfunctions` to another PR, so we can merge this one.

**Comment by hameerabbasi** [comment]
Are there still changes needed here or can we move the NaN functions to another PR and merge this one?

**Comment by mhvk** [comment]
I'd prefer not touching `nanfunctions` here beyond passing on the `initializer` argument (and even that could be pushed on).

**Comment by eric-wieser** [comment]
Better not to add it to the nanfunctions at all yet, so we're not locked
into an API we regret.

Let's take them out for now, and ask the mailing list for approval for
initializer in the regular reductions.

**Comment by hameerabbasi** [comment]
@eric-wieser Should I do that? I don't know git as well as you.

**Comment by hameerabbasi** [comment]
I've removed the Nan changes and moved them into a separate branch. I'll open another PR once this one is merged.

**Comment by hameerabbasi** [comment]
Any more changes required here? cc @eric-wieser @mhvk

File: numpy/core/tests/test_ufunc.py [hunk 56]
```diff
@@ -941,6 +946,27 @@ def test_identityless_reduction_noncontig_unaligned(self):
...
+
+        # For cases like np.maximum(np.abs(...), initializer=0)
+        # More generally, a supremum over non-negative numbers.
+        assert_equal(np.maximum.reduce([], initializer=0), 0)
+
+        # For cases like reduction of an empty array over the reals.
+        assert_equal(np.minimum.reduce([], initializer=np.inf), np.inf)
+        assert_equal(np.maximum.reduce([], initializer=-np.inf), -np.inf)
+
+        # Rendom tests
```
Comment (eric-wieser) [inline numpy/core/tests/test_ufunc.py]: Typo?

File: numpy/core/tests/test_ufunc.py [hunk 57]
```diff
@@ -941,6 +946,27 @@ def test_identityless_reduction_noncontig_unaligned(self):
...
+        assert_equal(np.minimum.reduce([5], initializer=4), 4)
+        assert_equal(np.maximum.reduce([4], initializer=5), 5)
```
Comment (eric-wieser) [inline numpy/core/tests/test_ufunc.py]: Can you add the other two tests with `minimum` and `maximum` swapped?

File: numpy/core/tests/test_ufunc.py [hunk 58]
```diff
@@ -941,6 +946,27 @@ def test_identityless_reduction_noncontig_unaligned(self):
...
+
+        with assert_raises(ValueError):
+            np.minimum.reduce([])
+
+        with assert_raises(ValueError):
+            np.minimum.reduce([], initializer=None)
```
Comment (eric-wieser) [inline numpy/core/tests/test_ufunc.py]: One-liners like this are often spelt `assert_raises(ValueError, np.minimum.reduce, [], initializer=None)` elsewhere in the test suite. Fine as is though.

File: numpy/add_newdocs.py [hunk 59]
```diff
@@ -5843,6 +5843,14 @@ def luf(lamdaexpr, *args, **kwargs):
         the result will broadcast correctly against the original `arr`.
 
         .. versionadded:: 1.7.0
+    initializer : scalar, optional
+        The value with which to start the reduction.
+        Defaults to the `~numpy.ufunc.identity` of the ufunc.
+        If ``None`` is given, then the first element of the reduction is used,
```
Comment (mhvk) [inline numpy/add_newdocs.py]: This text is confusing for the reader: we state that the default is the identity, but in the top line it notes `initializer=None` and then here it says that for that case the first element is used. Maybe all it needs is "if explicitly given as ``None``"

File: numpy/core/tests/test_ufunc.py [hunk 60]
```diff
@@ -493,6 +493,11 @@ def test_sum_complex(self):
             d += d
             assert_almost_equal(d, 2. + 2j)
 
+    def test_sum_initializer(self):
+        assert_equal(np.sum([3], initializer=2), 5)
+        assert_almost_equal(np.sum(np.ones((2, 3, 5)), axis=(0, 2), initializer=2),
```
Comment (mhvk) [inline numpy/core/tests/test_ufunc.py]: Why `almost_equal` instead of `equal`? This should be exact also for float.

File: numpy/core/tests/test_ufunc.py (hunk 58 above)
Comment (mhvk) [reply numpy/core/tests/test_ufunc.py]: I must admit I find this way much clearer...

**Comment by mhvk** [comment]
Only tiny comments left.

File: numpy/core/tests/test_ufunc.py (hunk 60 above)
Comment (hameerabbasi) [reply numpy/core/tests/test_ufunc.py]: I tend to keep all floating-point stuff `almost_equal`. It's just a habit.

File: numpy/core/tests/test_ufunc.py (hunk 58 above)
Comment (hameerabbasi) [reply numpy/core/tests/test_ufunc.py]: I agree with @mvhk here that this way is clearer, but my desire for uniformity kind of overrules that.

File: numpy/core/tests/test_ufunc.py (hunk 57 above)
Comment (hameerabbasi) [reply numpy/core/tests/test_ufunc.py]: Done!

File: numpy/core/tests/test_ufunc.py (hunk 56 above)
Comment (hameerabbasi) [reply numpy/core/tests/test_ufunc.py]: Fixed!

File: numpy/core/tests/test_ufunc.py (hunk 57 above)
Comment (hameerabbasi) [reply numpy/core/tests/test_ufunc.py]: Added!

File: numpy/core/fromnumeric.py (hunk 43 above)
Comment (hameerabbasi) [reply numpy/core/fromnumeric.py]: Actually, this is correct. It's the maximum value that the minimum can hold.

File: numpy/add_newdocs.py (hunk 59 above)
Comment (eric-wieser) [reply numpy/add_newdocs.py]: "if explicitly given as `None`" is not accurate, since it also implies when `identity is None` and the argument is ommited.

Perhaps _"When `None`, either explicitly or when omitted for a ufunc with no identity, ..."_

Comment (hameerabbasi) [reply numpy/add_newdocs.py]: I have a feeling that the complications in the docs are getting out of hand, and may make them hard to parse. Perhaps keep as-is, since we already mention that it defaults to the identity? And change the signature to say `ufunc.identity` instead of `None`?

Comment (mhvk) [reply numpy/add_newdocs.py]: @hameerabbasi - I was thinking the same thing: the problem is really the signature. It makes sense to change it to `ufunc.identity` to me.

Comment (hameerabbasi) [reply numpy/add_newdocs.py]: Done!

**Comment by hameerabbasi** [comment]
I guess I'll send this to the mailing list this evening.

**Comment by hameerabbasi** [comment]
Submitted, if you want to participate in the discussion. [Link to main thread](https://mail.python.org/pipermail/numpy-discussion/2018-March/077842.html).

**Comment by hameerabbasi** [comment]
@charris This may be a bit late, but I've edited the original comment to explain all the changes I've made.

**Review by eric-wieser — APPROVED** [review]
All looks good to me. Let's leave it on the mailing list for a week, but if there are no opinions, I'm still +1 on merging this. It gives an easy solution to the problem addressed by #10688 too

**Comment by hameerabbasi** [comment]
@mhvk Are the changes good? If so, can you approve them? The red is annoying. :P
@eric-wieser Since this is a change in the core Numpy machinery, I feel opinions are important. I'm not against merging, but I don't want it to get reverted down the road for something we didn't think of. :-)

But you're a core dev, so I think you would know.

File: numpy/core/tests/test_ufunc.py (hunk 60 above)
Comment (mhvk) [reply numpy/core/tests/test_ufunc.py]: It's a nitpick, but I'd like this to be `equal` - it should be exact so we might as well test it as such.

**Review by mhvk — APPROVED** [review]

**Comment by mhvk** [comment]
@hameerabbasi - it all looks good! Only one nitpick that would be nice to address. While you are at it, could you squash the commits into one?

**Comment by hameerabbasi** [comment]
My OCDs didn't agree with me using `assert_equal` with floating point operations like `sum` which may be inexact... So I converted it to `int64`, and added another test for `assert_almost_equal` which is, in fact inexact.

**Comment by mhvk** [comment]
> My OCDs didn't agree with me using `assert_equal` with floating point operations like `sum` which may be inexact... So I converted it to `int64`, and added another test for `assert_almost_equal` which is, in fact inexact.

:smile: - definitely all OK now.

**Comment by eric-wieser** [comment]
Perhaps we should revisit the argument name:

* `functools.reduce` actually calls it `initial`, not `initializer`
* `initializer` hints of a function, not a value, to me
* However, `functools.reduce` also takes no kwargs, so what it calls the argument is somewhat moot

@shoyer suggests `initial_val`, which I think I like more than `initializer`, but less than `initial`.

Is there any name we can use with existing kwarg usage?

**Comment by hameerabbasi** [comment]
I'm +1 on `initial`. If everyone agrees, I'll make the changes.

**Comment by mhvk** [comment]
:+1: for doing the same as `functools.reduce` - even if that is `initializer`! (Indeed, I'd rather change `identity` of the ufuncs to be `initializer`...)

**Comment by seberg** [comment]
The offline help calls it `intial` the online `intitializer` and the function seems to not allow kwargs. As a point for `initial`, to me `initializer` sounds like it would be a function and not a value (my point would be, I find it likely the python guys did not think about it too much, since it is just documentation).

**Comment by eric-wieser** [comment]
> Indeed, I'd rather change identity of the ufuncs to be initializer...

I don't agree with this - `identity` refers to the special value which is a no-op when passed as an initializer, so needs a different name.

**Comment by shoyer** [comment]
Indeed, `initializer` sounds like a function name. For example, that's how TensorFlow uses arguments named `initializer`.

My preference would be for `initial_value`. It's slightly longer than `initial`, but adjectives do not make for good argument names.

**Comment by hameerabbasi** [comment]
How about a shortened version: `initval`?

**Comment by eric-wieser** [comment]
Not a fan of `initval`.

Myargument against `initial_value` is that `value`, while indeed changing it from an adjective to a noun, is a noun that contains no information - we don't use `out_value`, `x_value`, or `where_value`.

My preference order of the suggestions so far, from best to worst, is:

* `initial`
* `initial_value`
* `initial_val`
* `initializer`
* `initval`

**Comment by mhvk** [comment]
For me, either `initial` or `initializer` work -- and I think it should be either of those two for consistency with `functools.reduce`.

**Comment by hameerabbasi** [comment]
It seems `inital` is the most accepted `kwarg`. If everyone is okay with it shall I change to `initial`?

**Comment by mhvk** [comment]
@hameerabbasi - I think it would be best if we had `initial` for `object` dtype as well, and if it is easy to do, might as well do it here. But fine also to push off to another PR.

**Comment by seberg** [comment]
Wait, if you push it off to later, you have to make it an *error* now, that might be an option (if not too nice).

**Comment by hameerabbasi** [comment]
I agree with @seberg, I'd prefer to do it here. If someone can point me to the right bit of code (cc @eric-wieser) I'm perfectly willing to do it now.

**Comment by hameerabbasi** [comment]
Never mind. My bad, must have been blind. The code was right there. I fixed the object dtype. :-)

File: numpy/add_newdocs.py [hunk 61]
```diff
@@ -5884,7 +5891,24 @@ def luf(lamdaexpr, *args, **kwargs):
     >>> np.add.reduce(X, 2)
     array([[ 1,  5],
            [ 9, 13]])
-
+           
+    You can use the initial argument to initialize the reduction with a
```
Comment (mhvk) [inline numpy/add_newdocs.py]: Maybe put double-backquote around `initial` - otherwise "initial argument" reads as if the first argument is meant.

Or avoid it altogether with:
```
You can also start the reduction with a different initial value.
```

**Comment by seberg** [comment]
Can you please make sure that you have tests testing high dimensional arrays (with axis keyword) on both (fast and slow in memory) axes?

**Comment by hameerabbasi** [comment]
@seberg This was discussed above. I tested a 3D array with `axis=(0, 2)` already, and it works fine.

File: numpy/core/src/umath/ufunc_object.c [hunk 62]
```diff
@@ -3061,32 +3063,44 @@ PyUFunc_Reduce(PyUFuncObject *ufunc, PyArrayObject *arr, PyArrayObject *out,
...
+
     /*
      * The identity for a dynamic dtype like
      * object arrays can't be used in general
      */
-    if (identity != Py_None && PyArray_ISOBJECT(arr) && PyArray_SIZE(arr) != 0) {
-        Py_DECREF(identity);
-        identity = Py_None;
-        Py_INCREF(identity);
+    if (!initial_given && initial != Py_None && PyArray_ISOBJECT(arr) && PyArray_SIZE(arr) != 0) {
```
Comment (mhvk) [inline numpy/core/src/umath/ufunc_object.c]: I would move this if statement inside the `if (initial == NULL)` clause above (and then test `identity`), so that you can do without the `initial_given` variable.

**Review by mhvk — COMMENTED** [review]
Looks good, but one small comment on the docstring, and a somewhat larger one on the code. Also, does need test cases for `dtype=object`...

**Comment by mhvk** [comment]
@hameerabbasi - OK, those changes look good! I think this all looks OK now.

File: numpy/add_newdocs.py [hunk 63]
```diff
@@ -5853,6 +5853,13 @@ def luf(lamdaexpr, *args, **kwargs):
         the result will broadcast correctly against the original `arr`.
 
         .. versionadded:: 1.7.0
+    initial : scalar, optional
+        The value with which to start the reduction.
+        Defaults to the `~numpy.ufunc.identity` of the ufunc.
```
[the remark this answers is not in the document]
Comment (hameerabbasi) [reply numpy/add_newdocs.py]: Nice catch! Yes, it's `None` for object arrays.

[the remark this answers is not in the document]
Comment (hameerabbasi) [reply numpy/add_newdocs.py]: If we want to get pedantic we also have to separate the case when the array is empty and `dtype=object`, in which case `ufunc.identity` is used.

[the remark this answers is not in the document]
Comment (seberg) [reply numpy/add_newdocs.py]: Yes, we want to be pendantic. Also be pendantic about `None`? `None` could be a valid "identity" parameter, we should think about checking if the parameter was passed at all (even if it is a bit strange maybe), or use another "default" like NoValue?

[the remark this answers is not in the document]
Comment (hameerabbasi) [reply numpy/add_newdocs.py]: I really can't see a use case for making `None` a valid initial value. We have a way of checking if something is passed.

But your comment does remind me of something else. In `numpy/core/_methods.py`, we're passing `initial` explicitly, which may result in issues with `dtype=object`.

@eric-wieser Any insights into how to solve that? The only one I can see is adopting @seberg's suggestion of defaulting to some sort of no-value.

[the remark this answers is not in the document]
Comment (eric-wieser) [reply numpy/add_newdocs.py]: This was the can of worms I didn't want to open in this PR, but leave till later.

One solution would be to introduce a `np.ufunc.NoIdentity` sentinel, which replaces the current use of None.

[the remark this answers is not in the document]
Comment (hameerabbasi) [reply numpy/add_newdocs.py]: I agree that we should delay it, but also that we need to fix the `_methods` thing. Or I can just revert the recent commits.

[the remark this answers is not in the document]
Comment (hameerabbasi) [reply numpy/add_newdocs.py]: I can introduce a few more lines in there, default it to `np._NoValue`, but that'd make it slow. ☹️

[the remark this answers is not in the document]
Comment (hameerabbasi) [reply numpy/add_newdocs.py]: Or I can just move `None` to be a no-op for now and leave all these issues till later. That seems like the best way forward to me at this point.

**Comment by hameerabbasi** [comment]
Since supporting `dtype=object` is a can of worms (as @eric-wieser so aptly put it), I'd like to revert the object dtype stuff. This will effectively make `initial` equivalent to `default` for `dtype=object`. Or we can follow @seberg's suggestion and make it an error until we can properly support it.

@eric-wieser What would be the best way to make it an error within C code with a nice description?

**Comment by mhvk** [comment]
I think what you, the behaviour for objects is close enough to what the final state should be than what would be the case without those extra commits. So, I would suggest to merge and do a follow-up PR on the details.

**Comment by hameerabbasi** [comment]
+1 for finally merging.

**Comment by seberg** [comment]
Well, I don't know and I do not want to think about it. Close enough for me is close enough, if assuming that someone will use the current behaviour, we can still get to a reasonable final state without problems at some point. I hate adding the next kludge that future us gets annoyed about.

Right now I am a bit confused what you are suggesting as final state for the object support....

**Comment by seberg** [comment]
That said, None as the "Error out" value, is maybe good even for object. Not ideal in some sense but the other solutions seem not much nicer. Plus, I am not sure it would even manoeuvre into a tricky to resolve issue for the future.

File: numpy/add_newdocs.py (hunk 63 above)
[the remark this answers is not in the document]
Comment (eric-wieser) [reply numpy/add_newdocs.py]: > I really can't see a use case for making None a valid initial value

I can - `np.logical_or.reduce(obj_array, initial=None)` picks the first truthy value from a sequence, else returns None.

**Comment by eric-wieser** [comment]
I think the cause of our problems is how the `.identity` is defined, and we'd do better to free ourselves from that constraint. What I'd propose then is:

* Use `.reduce(initial=np._NoValue)` to indicate "no identity"
* Make `.reduce(obj_array, initial=some_value)` use the "initial" logic, not the "default" logic
* Allow `None` to be passed like any other value
* Remove the `initial=ufunc.identity` documentation, and just remark in the documentation of `initial` that _"If the ufunc has no identity or the dtype is object, this default to None - otherwise it defaults to ufunc.identity"_

**Comment by hameerabbasi** [comment]
@eric-wieser Would you happen to know how I'd access `np._NoValue` inside the C code for this check? Doesn't seem terribly hard to do.

File: numpy/core/src/umath/override.c [hunk 64]
```diff
@@ -152,6 +155,9 @@ normalize_reduce_args(PyUFuncObject *ufunc, PyObject *args,
             }
             obj = PyTuple_GetSlice(args, 3, 4);
         }
+        if (i == 5 && obj == NoValue) {
+            continue;
```
Comment (eric-wieser) [inline numpy/core/src/umath/override.c]: A comment saying this is the `initial` argument would be good.

Comment (hameerabbasi) [reply numpy/core/src/umath/override.c]: Sure. Any idea why the Windows build is failing?

**Comment by eric-wieser** [comment]
Last two commit messages are very wrong!

File: numpy/core/src/umath/ufunc_object.c [hunk 65]
```diff
@@ -3036,6 +3036,8 @@ PyUFunc_Reduce(PyUFuncObject *ufunc, PyArrayObject *arr, PyArrayObject *out,
     const char *ufunc_name = ufunc_get_name_cstr(ufunc);
     /* These parameters come from a TLS global */
     int buffersize = 0, errormask = 0;
+    static PyObject *NoValue = NULL;
+    npy_cache_import("numpy", "_NoValue", &NoValue);
```
Comment (eric-wieser) [inline numpy/core/src/umath/ufunc_object.c]: Ah, this should actually be `if (... < 0) { return NULL; }` (wrapped as normal), in case the import fails

File: numpy/core/src/umath/override.c [hunk 66]
```diff
@@ -137,6 +137,9 @@ normalize_reduce_args(PyUFuncObject *ufunc, PyObject *args,
         return -1;
     }
 
+    static PyObject *NoValue = NULL;
```
Comment (eric-wieser) [inline numpy/core/src/umath/override.c]: C90 requires this be declared at the top of the function with the other variables (which is why the test fails)

File: numpy/core/src/umath/ufunc_object.c (hunk 65 above)
Comment (hameerabbasi) [reply numpy/core/src/umath/ufunc_object.c]: `npy_cache_import` has a return type of `void`, so we can't do that.

Comment (eric-wieser) [reply numpy/core/src/umath/ufunc_object.c]: Ah, in that case, I mean you should check that `NoValue != NULL`

**Comment by hameerabbasi** [comment]
I think this now has the desired behavior for all cases. The `np.NoIdentity` thing is a matter for a separate PR, this PR keeps the convention that `None` means "no initial value".

**Comment by seberg** [comment]
Won't look through the code, at least not now. It seems it still needs release notes I guess? So I understand correctly it is now:
 * Initial value for the reduction for all (almost) cases, including object
 * `None` will cause an error (even for object)
 * default is `NoValue` and will cause old behaviour.

Seems good to me as a change.

**Comment by hameerabbasi** [comment]
That's correct:

- `initial` behaves as an initial value in all cases now, even for `dtype=object`. Previously, it would behave as the default value for `dtype=object` and initial value otherwise.
- `None` means "no initial value, err if empty, otherwise use the start of the array". 
- `np._NoValue` causes the old behavior.

I'll add release notes now.

**Comment by hameerabbasi** [comment]
Rebased and tests added for `dtype=object`. Tell me when merging is imminent so I can squash all the commits.

**Comment by mhvk** [comment]
@hameerabbasi - I'd gladly merge this (maybe after one more day for last comments), so do go ahead and squash!

**Comment by hameerabbasi** [comment]
@mhvk Ping. 😀

**Comment by mhvk** [comment]
Merged. Thanks, @hameerabbasi!

**Comment by hameerabbasi** [comment]
Thanks so much to @eric-wieser and @mhvk especially for babying me through my first big PR. I owe you!
