### PR TITLE
BUG: Fixes ndarray.fill to accept maximum uint64 value

### LINKED ISSUE #5612: Python long raises OverflowError while same value as np.uint64 does not.
Trying to assign a value of `2**64 - 1` to an array of dtype `uint64` raises an `OverflowError`, but only if the value is a Python long rather than a Numpy scalar. This seems like a bug to me because the value obviously doesn't overflow and they compare equal.

```python
Python 3.4.2 (default, Jan 12 2015, 11:38:40) 
[GCC 4.9.2 20141224 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.version.version
'1.9.1'
>>> arr = np.empty((1,), dtype=np.uint64)
>>> arr.fill(np.uint64(2**64-1))
>>> arr.fill(2**64-1)                                                                                 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: int too big to convert
>>> np.uint64(2**64-1) == 2**64 - 1                                                                   
True
>>> arr == 2**64-1
array([ True], dtype=bool)
```

### PR DESCRIPTION
**Pull request by johntyree**
This PR changes `np.ndarray.fill` to attempt to convert to `uint64` if its argument is a Python integer and conversion to`int64` fails.  

`np.ndarray.fill` now accepts the Python long `2**64 - 1` as a value. Previously it failed because the value overflows an `int64` and `uint64` was not attempted. Constructing the value as a `uint64` manually and then passing it to fill succeeded.

Fixes #5612

### CODE REVIEW

File: numpy/core/src/multiarray/convert.c [hunk 1]
```diff
@@ -350,16 +350,31 @@ PyArray_FillWithScalar(PyArrayObject *arr, PyObject *obj)
     }
     /* Python integer */
     else if (PyLong_Check(obj) || PyInt_Check(obj)) {
+        /* First attempt long long */
         npy_longlong v = PyLong_AsLongLong(obj);
         if (v == -1 && PyErr_Occurred()) {
-            return -1;
+            /* Long long failed, try unsigned long long */
```
Comment (johntyree) [inline numpy/core/src/multiarray/convert.c]: I'm not particularly happy with the nesting here, but this case is slightly different from the others in that we're mapping from a single Python type to one of several NumPy types. Suggestions welcome.

File: numpy/core/tests/test_multiarray.py [hunk 2]
```diff
@@ -194,6 +194,17 @@ def test_fill(self):
...
 
+    def test_fill_max_uint64(self):
+        x = empty((3, 2, 1), dtype=uint64)
+        y = empty((3, 2, 1), dtype=uint64)
+        value = 2**64 - 1
+        y[...] = value
+        try:
+            x.fill(value)
+        except:
+            raise RuntimeError(getexception())
```
Comment (juliantaylor) [inline numpy/core/tests/test_multiarray.py]: this should not be required, the test should fail on any exception

Comment (johntyree) [inline numpy/core/tests/test_multiarray.py]: I wasn't sure if for some reason it was standard to use RuntimeException or not. I based this on another test up above. I'll pull it out.

**Comment by juliantaylor** [comment]
looks good thanks
can you still squash the commits into one with `git rebase -i master`
as its probably still appropriate for 1.9.2 please also run `git rebase --onto $(git merge-base master origin/maintenance/1.9.x) HEAD^` assuming origin is the remote name of the main numpy repo.

**Comment by johntyree** [comment]
So I think I understood you correctly. There is now a single commit based off of 50afb0fb67b4b9d1bffa3baf4b87332040c54a70.

**Comment by juliantaylor** [comment]
perfect, that allows us to easily merge it into both branches.
thanks

**Comment by johntyree** [comment]
\o/ Thanks
