### PR TITLE
BUG: support nan-like null strings in [l,r]strip

### LINKED ISSUE #26390: BUG: numpy.strings.lstrip/strip/rstrip fails with nulls
### Describe the issue:

When encountering a null value in numpy 2.0 StringDType'd array, we get

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thomasli/opt/miniconda3/envs/pandas-dev/lib/python3.10/site-packages/numpy/_core/strings.py", line 881, in rstrip
    return _rstrip_whitespace(a)
ValueError: Cannot strip null values that are not strings
```

It is expected that the nulls are propagated.

### Reproduce the code example:

```python
import numpy as np
a = np.array(["a", "b", np.nan], dtype=np.dtypes.StringDType(na_object=np.nan))
np.strings.rstrip(a)
np.strings.lstrip(a)
np.strings.strip(a)
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thomasli/opt/miniconda3/envs/pandas-dev/lib/python3.10/site-packages/numpy/_core/strings.py", line 881, in rstrip
    return _rstrip_whitespace(a)
ValueError: Cannot strip null values that are not strings

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thomasli/opt/miniconda3/envs/pandas-dev/lib/python3.10/site-packages/numpy/_core/strings.py", line 926, in strip
    return _strip_whitespace(a)
ValueError: Cannot strip null values that are not strings

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thomasli/opt/miniconda3/envs/pandas-dev/lib/python3.10/site-packages/numpy/_core/strings.py", line 840, in lstrip
    return _lstrip_whitespace(a)
ValueError: Cannot strip null values that are not strings
```

### Python and NumPy Versions:

2.1.0.dev0+git20240424.f8392ce

### Runtime Environment:

_No response_

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes #26390.

It turns out that `strip` has been missing from the stringdtype tests for unary and binary ufuncs and so the tests for null support were never triggered. I fixed that by adding all the strip-like functions to the tests.

Note that this adds another case where we have a `goto next_step` and an extra block to avoid compliation errors about jumping over variable declarations. I'd prefer to go through all of these and rewrite the loops to use for loops instead of `while (N--)`, this just keeps things consistent with the rest of the file.

### CODE REVIEW

File: numpy/_core/src/umath/stringdtype_ufuncs.cpp [hunk 1]
```diff
@@ -1072,28 +1073,46 @@ string_lrstrip_chars_strided_loop(
...
+                    }
+                    goto next_step;
+                }
+            }
             else {
                 npy_gil_error(PyExc_ValueError,
-                              "Cannot strip null values that are not strings");
+                              "Can only strip null values that are strings "
+                              "or NaN-like values");
                 goto fail;
```
Comment (seberg) [inline numpy/_core/src/umath/stringdtype_ufuncs.cpp:1096]: One day might be nice to see if this check isn't common among a few ufuncs and just writing `ufunc-name() cannot support ...` with a single helper?

File: numpy/_core/src/umath/stringdtype_ufuncs.cpp [hunk 2]
```diff
@@ -1169,6 +1189,7 @@ string_lrstrip_whitespace_strided_loop(
         npy_static_string s = {0, NULL};
         int s_isnull = NpyString_load(allocator, ps, &s);
 
+
```
Comment (seberg) [inline numpy/_core/src/umath/stringdtype_ufuncs.cpp:1192]:
```suggestion
```
But doesn't matter.

File: numpy/_core/src/umath/stringdtype_ufuncs.cpp [hunk 3]
```diff
@@ -1072,28 +1073,46 @@ string_lrstrip_chars_strided_loop(
...
+            Buffer<ENCODING::UTF8> buf1((char *)s1.buf, s1.size);
+            Buffer<ENCODING::UTF8> buf2((char *)s2.buf, s2.size);
+            Buffer<ENCODING::UTF8> outbuf(new_buf, s1.size);
+            size_t new_buf_size = string_lrstrip_chars
+                    (buf1, buf2, outbuf, striptype);
 
+            if (NpyString_pack(oallocator, ops, new_buf, new_buf_size) < 0) {
+                npy_gil_error(PyExc_MemoryError, "Failed to pack string in %s",
+                              ufunc_name);
+                goto fail;
```
Comment (seberg) [inline numpy/_core/src/umath/stringdtype_ufuncs.cpp:1110]: Technically, missing the `PyMem_RawFree(new_buf);`?  I probably said that before, but it would seem nice to avoid reallocating a small buffer every time here (maybe directly allocating the result although that isn't possible if the operation is in-place).

File: numpy/_core/tests/test_stringdtype.py [hunk 4]
```diff
@@ -1462,7 +1492,8 @@ def test_setup(self):
         view = self.get_view(self.a)
         sizes = np.where(is_short, view['size_and_flags'] & 0xf,
                          view['size'])
-        assert_array_equal(sizes, np.strings.str_len(self.a))
+        assert_array_equal(sizes, np.strings
+                           .str_len(self.a))
```
Comment (seberg) [inline numpy/_core/tests/test_stringdtype.py:1496]:
```suggestion
        assert_array_equal(sizes, np.strings.str_len(self.a))
```

**Review by seberg — APPROVED** [review]
LGTM, and can just put it in, since it just fixes a bug, comments are "would be nice to improve" really (not sure the OOM error path that looks wrong particularly important but happy to defer).

One other thing that struck me is: lstrip/rstrip should be pretty much identical except for calling a different core function.
That should really be consolidated either via C++ or via static data.  But that is something to look in later I think.

File: numpy/_core/src/umath/stringdtype_ufuncs.cpp (hunk 1 above)
Comment (ngoldbaum) [reply numpy/_core/src/umath/stringdtype_ufuncs.cpp:1096]: There's definitely some code duplication. I added this as a task to https://github.com/numpy/numpy/issues/25693.

File: numpy/_core/src/umath/stringdtype_ufuncs.cpp (hunk 3 above)
Comment (ngoldbaum) [reply numpy/_core/src/umath/stringdtype_ufuncs.cpp:1110]: Yeah, this error path indicates there's memory corruption or a bug in the implementation so a memory leak is the least of your worries if you get here. That said, easy enough to add a `PyMem_RawFree`, thanks for the catch.

**Comment by ngoldbaum** [comment]
> One other thing that struck me is: lstrip/rstrip should be pretty much identical except for calling a different core function.
That should really be consolidated either via C++ or via static data.

Are you talking about the separation between `split_whitespace` and `split_chars`? Because both variants consolidate the `[l,r]strip` distinction into a single strided loop, see the use of STRIPDATA in `stringdtype_ufuncs.cpp`.

If it's `strip_whitespace` and `strip_chars`, I can take a look at is consolidating those two functions for stringdtype if it turns out the reason for the distinction is to support fixed-width strings but if my vague recollections from six months ago about this are correct we needed it because of limitations of the ufunc system around optional arguments.

**Comment by seberg** [comment]
Ah, nvm that part... might be nice to do something anyway, but I somehow had mindslipped into reading the second copy to be rsplit and the first lsplit.

**Comment by ngoldbaum** [comment]
Thanks for giving this a look Sebastian. I'm self-merging because this fixes some tests in pandas (see https://github.com/pandas-dev/pandas/actions/runs/8971939049/job/24638804051?pr=58578 with a bunch of failures related to this) and it would be nice to have this in the RC.
