### PR TITLE
BUG: multifield-indexing adds padding bytes: revert for 1.14.1

### LINKED ISSUE #10344: New in NumPy 1.14: failures in PyTables
In the following snippet:

```python
import numpy as np
data_proper = [(456, b'dbe', 1.2), (2, b'ded', 1.3)]
data_improper = [[456, b'dbe', 1.2], [2, b'ded', 1.3]]
descr = [('f0', '<i4'), ('f1', 'S3'), ('f2', '<f8')]
dtype = np.dtype((np.record, descr))

np.array(data_improper, dtype=dtype)
```

Execution of the last line in 1.13 used to raise:
```
TypeError: a bytes-like object is required, not 'int'
```
which allowed the logic in [numpy/core/records.py#L676](https://github.com/numpy/numpy/blob/master/numpy/core/records.py#L676) to recover and reinterpret the line as `np.array(data_proper, dtype=dtype)`.

The trouble is that in NumPy 1.14
```
ValueError: invalid literal for int() with base 10: b'dbe'
```
is being raised instead, which results in the failure. 

This is a gist of the issue behind numerous test failures in pyTables when used with NumPy 1.14.

### LINKED ISSUE #10387: BUG: structured array indexing dtype and dtype.descr changed in 1.14.0
Running this code on 1.13.x and 1.14.0 yields different outputs:
```
import numpy as np
dt = [('a', int), ('b', float)]
data = np.zeros(1, dtype=dt)
data['a'] = 0
data['b'] = 1
data = data[['a']]
print(data.dtype)
print(data.dtype.descr)
np.save('test.npy', data)
data_read = np.load('test.npy')
print(data_read.dtype)
print(data_read.dtype.descr)
```
On 1.13.x the output is consistent -- for all four print statements it gives:
```
[('a', '<i8')]
```
On 1.14.x it changes to these, the first of which is now dict-like, the second (`descr`) has a new field `('', '|V8')`, the third (round-trip IO) changes `dtype` back to a list, and the fourth (`descr`) changes the blank field name to `''`:
```
{'names':['a'], 'formats':['<i8'], 'offsets':[0], 'itemsize':16}
[('a', '<i8'), ('', '|V8')]
[('a', '<i8'), ('f1', 'V8')]
[('a', '<i8'), ('f1', '|V8')]
```

The real reason I found this bug is because the addition of the blank field name breaks `scipy.io.savemat`:
```
>>> from scipy import io  # on latest dev
>>> io.savemat('test.mat', dict(data=data))
  File "untitled0.py", line 16, in <module>
    io.savemat('test.mat', dict(data=data))
  File "scipy/io/matlab/mio.py", line 219, in savemat
    MW.put_variables(mdict)
  File "scipy/io/matlab/mio5.py", line 846, in put_variables
    self._matrix_writer.write_top(var, asbytes(name), is_global)
  File "scipy/io/matlab/mio5.py", line 587, in write_top
    self.write(arr)
  File "scipy/io/matlab/mio5.py", line 616, in write
    self.write_struct(narr)
  File "scipy/io/matlab/mio5.py", line 735, in write_struct
    self._write_items(arr)
  File "scipy/io/matlab/mio5.py", line 752, in _write_items
    self.write(el[f])
ValueError: no field of name 
```
If these structured dtype changes are intentional and not bugs, I can open a SciPy issue instead (which would either be to avoid writing void data, or write out unknown fields).

### LINKED ISSUE #10409: `.view` no longer works on field selections of structured arrays
See [this SO question](https://stackoverflow.com/questions/48267058/using-np-view-with-changes-to-structured-arrays-in-numpy-1-14)

Since we now return a view rather than a copy from `arr[fields]`, we end up with a dtype with padding. This prevents `.view` being called, even though the memory layout is sufficient to allow it

### PR DESCRIPTION
**Pull request by ahaldane**
Fixes #10387
Fixes #10344
Fixes #10409 

This is a version of #10411 targeting the 1.14.x maintenance branch. It reverts the copy->view change from 1.14.0, aiming to get into 1.14.1.

### CODE REVIEW

File: numpy/core/src/multiarray/mapping.c [hunk 1]
```diff
@@ -1383,15 +1383,57 @@ array_subscript_asarray(PyArrayObject *self, PyObject *op)
...
+/*
+ * Helper function for _get_field_view which turns a multifield
+ * view into a "packed" copy, as done in numpy 1.14 and before.
+ * In numpy 1.15 this function will most likely be removed.
+ */
+NPY_NO_EXPORT int
+_multifield_view_to_copy(PyArrayObject **view) {
+    static PyObject *copyfunc = NULL;
+    PyObject *viewcopy;
+    PyObject *mf_setting = NULL;
```
Comment (charris) [inline numpy/core/src/multiarray/mapping.c]: Seems this variable is no longer used, leading to test errors.

**Comment by charris** [comment]
Thanks Allan.
