### PR TITLE
BUG: Distinguish exact vs. equivalent dtype for C type aliases.

### LINKED ISSUE #1468: BUG: np.asarray does not create new array view when different but compatible type code is passed in the dtype argument (Trac #870)
_Original ticket http://projects.scipy.org/numpy/ticket/870 on 2008-08-01 by trac user damian.eads, assigned to @stefanv._

Examining `ndarray` type codes is common in C extensions before passing array contents to functions expecting `int*` or `long*`. The type codes are ideal ensure the contents can be safely casted to `int*` or `long*` on the host machine. In some cases, the `int` and `long` types are of the same size but their type codes are different. `np.asarray(..., dtype='i')` should be used to create a new array view with the type code the C type code expected by the C extension; however, it does not appear to work when using it for this purpose.

**Problem**
I construct X as a C-long array and then I cast it to a C-int array Y (using `np.asarray`) but the type code does not change. However, when constructing the array from scratch as a C-int (using `np.zeros`), I get the right type code (ie 5).

**Expectation of Behavior**
I assumed that when X gets casted to a C-int, no copying should occur but a new array view should be constructed with the C-int type code.

**Workaround**
Casting from a C-long (type code 7) to a double to a C-int returns an array with the right type code but an ugly double copy occurs.

**Recreation**

```
# Construct X as a C-long.

In [16]: X=numpy.zeros((10,10),dtype='l')

# Now cast X to a C-int.

In [17]: Y=numpy.asarray(X, dtype='i')

# Check X and Y's data type; they are the same.

In [18]: X.dtype
Out[18]: dtype('int32')

In [19]: Y.dtype
Out[19]: dtype('int32')

# Their type codes are the same.

In [20]: X.dtype.num
Out[20]: 7

In [21]: Y.dtype.num
Out[21]: 7

# Constructing with dtype='i', gives the right type code.

In [22]: Z=numpy.zeros((10,10),dtype='i')

In [23]: Z.dtype
Out[23]: dtype('int32')

In [24]: Z.dtype.num
Out[24]: 5
```

Stefan van der Walt observes that the `dtype` objects are compared for equality but not the type codes. This explains why the `asarray` function does not create a new view.

```
In [4]: np.dtype('i') == np.dtype('l')
Out[4]: True

In [5]: np.dtype('i').num == np.dtype('l').num
Out[5]: False
```

**Fix**

Check the type codes for equality, not the `dtype` objects, to decide whether to create a new array view in `np.asarray`.

----

summary @seberg:

This is still true, the array fast-paths to do the no-copy behaviour is correct to not copy, but apparently not aggressive enough with creating views, on 64bit linux:
```
arr = np.array([1, 2, 3, 4], "q")
np.asarray(arr, dtype="l") is arr  # True
np.dtype("l").num == np.dtype("q").num  # not True
```

The good news: This really should be a simple fix!

### PR DESCRIPTION
**Pull request by eirrgang**
For `asarray` and for the `dtype` equality operator,
equivalent dtype aliases were considered exact matches.
This change ensures that the returned array has a descriptor
that exactly matches the requested dtype.

Note: Intended behavior of `np.dtype('i') == np.dtype('l')`
is to test compatibility, not identity. This change does not
affect the behavior of `PyArray_EquivTypes()`, and the
`__eq__` operator for `dtype` continues to map to
`PyArray_EquivTypes()`.

Fixes #1468.

### CODE REVIEW

File: numpy/core/src/multiarray/multiarraymodule.c [hunk 1]
```diff
@@ -1627,12 +1627,30 @@ _array_fromobject_generic(
...
+                     * object. */
+                    Py_INCREF(type);
+                    ret = PyArray_NewFromDescr(
+                            Py_TYPE(op),
+                            type,
+                            PyArray_NDIM(oparr),
+                            PyArray_DIMS(oparr),
+                            PyArray_STRIDES(oparr),
+                            PyArray_DATA(oparr),
+                            PyArray_FLAGS(oparr),
```
Comment (eirrgang) [inline numpy/core/src/multiarray/multiarraymodule.c:1650]: or should this be `type->flags`?

File: numpy/core/src/multiarray/multiarraymodule.c [hunk 2]
```diff
@@ -1627,12 +1627,30 @@ _array_fromobject_generic(
...
             }
         }
-        /* One more chance */
+        /* One more chance for faster exit if user specified the dtype. */
         oldtype = PyArray_DESCR(oparr);
         if (PyArray_EquivTypes(oldtype, type)) {
             if (copy != NPY_COPY_ALWAYS && STRIDING_OK(oparr, order)) {
                 Py_INCREF(op);
-                ret = oparr;
+                if (oldtype == type) {
```
Comment (eirrgang) [inline numpy/core/src/multiarray/multiarraymodule.c:1635]: It seems like either
* this operator is overly strict (or the wrong check), or
* this change fundamentally conflicts with the current notions of `is`

Comment (eirrgang) [reply numpy/core/src/multiarray/multiarraymodule.c:1635]: Maybe this change is too deep. If a user says `asarray(a, dtype='i')`, are there members of https://numpy.org/devdocs/reference/c-api/types-and-structures.html#c.PyArray_Descr that might differ under ordinary circumstances? Might `hash` be uninitialized?

File: numpy/core/src/multiarray/multiarraymodule.c (hunk 1 above)
Comment (seberg) [reply numpy/core/src/multiarray/multiarraymodule.c:1650]: This is right, I guess you don't even need it, the only one would be writeonly, and I think we check the base one for that.  But it doesn't hurt (the owndata flag is removed automatically).

File: numpy/core/src/multiarray/multiarraymodule.c (hunk 2 above)
Comment (seberg) [reply numpy/core/src/multiarray/multiarraymodule.c:1635]: I think this is right, and we just need to rethink the tests that are failing!

**Comment by eirrgang** [comment]
The updates that were necessary for the tests indicate that this change will surprise some users. Some sort of release note is warranted, and perhaps some sort of update to docs related to the `dtype` kwarg.

Suggestions for specific docs files to update?

File: numpy/array_api/tests/test_asarray.py [hunk 3]
```diff
@@ -0,0 +1,24 @@
+import numpy as np
+
+
+def test_fast_return():
+    """"""
+    a = np.array([1, 2, 3], dtype='i')
+    assert np.asarray(a) is a
+    assert np.asarray(a, dtype='i') is a
+    # This may produce a new view or a copy, but is never the same object.
+    assert np.asarray(a, dtype='l') is not a
```
Comment (eric-wieser) [inline numpy/array_api/tests/test_asarray.py:10]: Note that this is only a good test on windows; it's `l` and `q` that clash on Linux, where l`long` is 64 bit

File: numpy/ma/tests/test_core.py [hunk 4]
```diff
@@ -5387,7 +5387,7 @@ def test_ufunc_with_out_varied():
 
 
 def test_astype_mask_ordering():
-    descr = [('v', int, 3), ('x', [('y', float)])]
+    descr = np.dtype([('v', int, 3), ('x', [('y', float)])])
```
Comment (eric-wieser) [inline numpy/ma/tests/test_core.py:5390]: So record dtypes are now nominal not structural? That is, two record types with identical fields are treated differently depending on whether they are at the same memory locations? That seems undesirable to me; although if structured dtypes have mutable state maybe it's the right choice after all.

Either way, it would be good to test this explicitly rather than only accidentally as part of this test

Comment (seberg) [reply numpy/ma/tests/test_core.py:5390]: Well, we can either preserve the array identity check faithfully, or the dtype identity check one, since doing `np.dtype(something)` will give a new dtype each time.

Mutibility is a point (although I don't like it for dtypes).  I guess the structured dtype case is "more equivalent" than for the ones with differing type numbers...
But is there much point in preserving the array identity?

File: numpy/array_api/tests/test_asarray.py (hunk 3 above)
Comment (eirrgang) [reply numpy/array_api/tests/test_asarray.py]: Good point. I have added more permutations to this block so that at least one check would not pass without this patch.

File: numpy/ma/tests/test_core.py (hunk 4 above)
Comment (eirrgang) [reply numpy/ma/tests/test_core.py:5390]: I renamed the new test function to make it (hopefully) more obvious that it includes tests of the new dtype equivalence/identity behavior. Does those assertions seem sufficient?

File: numpy/core/src/multiarray/multiarraymodule.c [hunk 5]
```diff
@@ -1627,12 +1627,31 @@ _array_fromobject_generic(
                 goto finish;
             }
         }
-        /* One more chance */
+        /* One more chance for faster exit if user specified the dtype. */
```
Comment (eirrgang) [inline numpy/core/src/multiarray/multiarraymodule.c:1630]: It seems like the whole conditional (starting at 1612) might be appropriately replaced with a call to `array_astype()`, except that it looks like there are some default behaviors that are different (e.g. forcecopy).

In particular, the use of `PyArray_DescrConverter -> PyArray_AdaptDescriptorToArray` in `methods.c` `array_astype()` has slightly different behavior than the `PyArray_DescrConverter2` -> `PyArray_DescrConverter` here.

It seems like a separate issue, but maybe any associated behavior changes are something that should be considered before release notes are finalized?

Comment (seberg) [reply numpy/core/src/multiarray/multiarraymodule.c:1630]: Its a good point that it may be nice to consolidate the fast-path with `astype`.  But I think its OK to not do it for now.

File: numpy/array_api/tests/test_asarray.py [hunk 6]
```diff
@@ -0,0 +1,45 @@
...
+    assert annotated_int_array.base is int_array
+
+    # These ``asarray()`` calls may produce a new view or a copy,
+    # but never the same object.
+    long_int_array = np.asarray(int_array, dtype='l')
+    assert long_int_array is not int_array
+    assert np.asarray(int_array, dtype='q') is not int_array
+    assert np.asarray(long_int_array, dtype='q') is not long_int_array
+    assert long_int_array is not np.asarray(int_array, dtype='l')
+    assert long_int_array.base is np.asarray(int_array, dtype='l').base
```
Comment (eirrgang) [inline numpy/array_api/tests/test_asarray.py:35]: Oops. This won't be true on 32-bit systems, right?

File: numpy/ma/tests/test_core.py (hunk 4 above)
Comment (eirrgang) [reply numpy/ma/tests/test_core.py:5390]: I think the latest test is pretty thorough and illustrative. If a different test file name would help to find the expression of these identity semantics, please advise.

**Comment by eirrgang** [comment]
> The updates that were necessary for the tests indicate that this change will surprise some users. Some sort of release note is warranted, and perhaps some sort of update to docs related to the `dtype` kwarg.
> 
> Suggestions for specific docs files to update?

I couldn't find any docs that were specific enough to require updating, but I added a release notes doc.

**Comment by seberg** [comment]
Thanks this is awesome.  Those are long docs, if we know a place to put them, we probably should... For the release note, it would be nice to make it much shorter unfortuntely!

**Comment by eirrgang** [comment]
> Thanks this is awesome. Those are long docs, if we know a place to put them, we probably should... For the release note, it would be nice to make it much shorter unfortuntely!
> 
> EDIT: I (or someone else from us) can take a stab at that though!

Better now?

File: doc/release/upcoming_changes/21995.compatibility.rst [hunk 7]
```diff
@@ -0,0 +1,46 @@
...
+    if np.dtype('i') == np.dtype('l'):
+        assert int_array is long_int_array.base
+
+New array views are created with each call to `asarray` with non-identical
+dtype kwarg, but the underlying data is the same.
+
+    assert int_array.dtype is np.dtype('i')
+    long_int_array = np.asarray(int_array, dtype='l')
+    assert long_int_array is not np.asarray(int_array, dtype='l')
+    assert long_int_array.base is np.asarray(int_array, dtype='l').base
```
[the remark this answers is not in the document]
Comment (eirrgang) [reply doc/release/upcoming_changes/21995.compatibility.rst:46]: or replace third paragraph with the following summary:

```
* Resulting array *dtype* members are now guaranteed to pass an identity check (``is``) with the caller-provided dtype.
* Resulting arrays may no longer pass an identity check with the provided *obj* if the provided dtype is compatible, but not identical. However, if copy was avoided, ``result.base is obj``.
```

**Comment by eirrgang** [comment]
> Thanks this is awesome. Those are long docs, if we know a place to put them, we probably should... For the release note, it would be nice to make it much shorter unfortuntely!
> 
> EDIT: I (or someone else from us) can take a stab at that though!

Is my proposed edit better? Or is there an alternative proposal?

File: doc/release/upcoming_changes/21995.compatibility.rst (hunk 7 above)
[the remark this answers is not in the document]
Comment (seberg) [reply doc/release/upcoming_changes/21995.compatibility.rst]: Sorry, I was out for a while and lost track of this.  I pushed an alternative based on your suggestions (opted for an example anyway though).  Would love it shorter, but I hope it is fairly concise.
Maybe you can have a quick look @eirrgang, if you don't like it happy if you revert or suggest changes.

**Comment by mattip** [comment]
Thanks @eirrgang

File: doc/release/upcoming_changes/21995.compatibility.rst [hunk 8]
```diff
@@ -1,46 +1,21 @@
...
+
+In some cases this change means that a *view* rather than the
+input array is returned.
+The following is an example for this on 64bit Linux where ``long``
+and ``longlong`` are the same precision::
+
+    >>> arr = np.array([1, 2, 3], dtype="long")
+    >>> new_dtype = np.dtype("longlong")
+    >>> new = np.asarray(arr, dtype=new_dtype)
+    >>> new.dtype is dtype
```
Comment (eirrgang) [inline doc/release/upcoming_changes/21995.compatibility.rst:15]: Was this supposed to be `new.dtype is new_dtype`?

**Review by eirrgang — COMMENTED** [review]
Sorry. I was away for the weekend and just got caught up. Looks good, but I think there is a typo.

File: doc/release/upcoming_changes/21995.compatibility.rst (hunk 8 above)
Comment (mattip) [reply doc/release/upcoming_changes/21995.compatibility.rst:15]: yes

**Comment by mattip** [comment]
See #22227

**Comment by InessaPawson** [comment]
Hi-five on merging your first pull request to NumPy, @eirrgang! We hope you stick around! Your choices aren’t limited to programming – you can review pull requests, help us stay on top of new and old  issues, develop educational material, work on our website, add or improve graphic design, create marketing materials, translate website content, write grant proposals, and help with other fundraising initiatives. For more info, check out: https://numpy.org/contribute
Also, consider joining our mailing list. This is a great way to connect with other cool people in our community and be part of important conversations that affect the development of NumPy: https://mail.python.org/mailman/listinfo/numpy-discussion

**Comment by rgommers** [comment]
As reported in gh-22233, there is a serious issue with this PR, likely a memory leak that is causing issues for downstream projects like SciPy and MNE-Python.

I will revert this PR. @eirrgang it would be great if you could resubmit this as a new PR, and then we can merge it again once the problem is understood and addressed. Maybe `pytest-leaks` or Valgrind will be helpful here in pointing to the root cause.

**Comment by rgommers** [comment]
Ugh, GitHub: _Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged._

File: numpy/core/src/multiarray/multiarraymodule.c [hunk 9]
```diff
@@ -1627,12 +1627,31 @@ _array_fromobject_generic(
...
+                            Py_TYPE(op),
+                            type,
+                            PyArray_NDIM(oparr),
+                            PyArray_DIMS(oparr),
+                            PyArray_STRIDES(oparr),
+                            PyArray_DATA(oparr),
+                            PyArray_FLAGS(oparr),
+                            op,
+                            op
+                            );
```
Comment (seberg) [inline numpy/core/src/multiarray/multiarraymodule.c:1653]: Oh, either I just didn't think of it, or expected that this steals a reference to `op` for the `base`.  We are missing a DECREF, I will make a PR.

Comment (eirrgang) [reply numpy/core/src/multiarray/multiarraymodule.c:1653]: Yes, I think I originally tried `PyArray_NewFromDescr` with `op` for `*data` and `nullptr` for `*obj`, and `PyArray_SetBaseObject` or something that steals the reference for the base. Anyway, I guess we were sloppy when switching to `PyArray_NewFromDescrAndBase`. Thanks for the quick catch!

**Comment by leofang** [comment]
It is incorrect to add `numpy/array_api/tests/test_asarray.py`. The test itself is not of concern to Array API. It should be moved elsewhere. 

(This is why we need to set up `array_api` namespace owners... cc: @seberg @rgommers)

**Comment by seberg** [comment]
Yes, sorry, I missed where this test was, it should be elsewhere.  I had just thought it looked reasonably thorough.  It might also be split up, but I don't care.

In any case, we need to move this test into `/core/tests/test_<something>` not here. @eirrgang do you want to have a look into that.

**Comment by eirrgang** [comment]
> Yes, sorry, I missed where this test was, it should be elsewhere. I had just thought it looked reasonably thorough. It might also be split up, but I don't care.
> 
> In any case, we need to move this test into `/core/tests/test_<something>` not here. @eirrgang do you want to have a look into that.

Sure. I'll make a new PR. As I recall, there wasn't an obvious good place for the test. I'll look again, and try to come up with something reasonable.

**Comment by seberg** [comment]
Way too long, but `test_multiarray.py` with `TestCreation` might be an option.  Otherwise `test_array_coercion.py` has somewhat related tests so you could just add it in that file.  The only real problem here is that it doesn't belong under `array_api/tests`, but `core/tests`

**Comment by WarrenWeckesser** [comment]
This appears to have broken some tests in `scipy.sparse`.  Ultimately, the problem comes down to the dtype check requiring that the dtypes are the *same object*, instead of being equal in the Python sense.

This shows the essence of the problem:
```
In [27]: a = np.array([10, 20, 30, 40])

In [28]: b = np.asarray(a, dtype=a.dtype.newbyteorder('native'))

In [29]: a is b  # Before this PR, this would be true.
Out[29]: False

In [30]: a.dtype == b.dtype
Out[30]: True
```
The dtypes of `a` and `b` are equal, but `asarray()` still created a view.  There are tests in `scipy.sparse` that expect `a is b` to be True.

**Comment by eirrgang** [comment]
> `a.dtype.newbyteorder('native')` creates a new dtype instance, but the new dtype is equal to (i.e. `==`) `a.dtype`. So the dtypes of `a` and `b` are equal, but `asarray()` still created a view. There are tests in `scipy.sparse` that expect `a is b` to be True.

Yes. My understanding from @seberg is that this is the intended behavior, and it is reflected in the updates to the numpy tests and release notes. Please advise if you find contradictions in the documentation. Some documentation was trimmed, so you might find the commit history of the PR informative. See also https://github.com/numpy/numpy/pull/21995/files#r922726648

**Comment by seberg** [comment]
@WarrenWeckesser, yeah, that was intentional but that doesn't mean it was the best thing to do.  Please do followup if you think we should consider undoing (parts) of this.
