### PR TITLE
BUG: three string ufunc bugs, one leading to segfault

### LINKED ISSUE #25513: BUG: A segfault in chararray (2.0.0dev0 regression)
### Describe the issue:

Astropy's tests against numpy's dev branch are currently choking on a segfault.
The issue can be boiled down to a pure numpy reproducer.

I wasn't able to setup my dev env properly to provide the full stack trace information yet (I'm working on it), but I could bisect the problem to https://github.com/numpy/numpy/commit/19396d298beca3f56d93d59e18b6965853c9eebc (https://github.com/numpy/numpy/pull/25171)

### Reproduce the code example:

```python
import numpy as np

carr = np.chararray((2,), itemsize=25)
carr[:] = [b'  4.52173913043478315E+00', b'  4.95652173913043548E+00']
carr.replace(b"E", b"D")
```

### Error message:

_No response_

### Python and NumPy Versions:

2.0.0.dev0+git20231230.ee3124b
3.12.0 (main, Oct 27 2023, 11:50:57) [Clang 15.0.0 (clang-1500.0.40.1)]

### Runtime Environment:

```
[{'numpy_version': '2.0.0.dev0+git20231231.f1fac82',
  'python': '3.12.1 (main, Dec 11 2023, 18:41:50) [Clang 15.0.0 '
            '(clang-1500.0.40.1)]',
  'uname': uname_result(system='Darwin', node='kwanzaabot.home', release='23.2.0', version='Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP'],
                      'not_found': ['ASIMDFHM']}}]
None
```

### Context for the issue:

https://github.com/astropy/astropy/issues/15797

### PR DESCRIPTION
**Pull request by mhvk**
#25171 added string ufuncs, but unfortunately did not properly update the rather sparse test suite for `chararray`, in particular failing to test the various fast paths that were created. While one bug was fixed in #25484, not all were: as noted in #25513, the present version causes segfaults in `astropy`. It turned out there were multiple mistakes:
1. The `memchr` version of `findchar` always returns 0 for the offset;
2. In replacements, the length of the remaining buffer is not tracked, leading to buffer overflow.
3. The fast-track code for "no replacement possible" gives empty strings instead of a copy of the input;
These 3 commits fix those bugs, adding tests to avoid regressions.

I note that this only increases test coverage for these cases; a larger addition seems warranted.

Fixes #25513

EDIT: ordering changed.

### CODE REVIEW

File: numpy/_core/src/umath/string_fastsearch.h [hunk 1]
```diff
@@ -62,7 +62,7 @@ findchar(Buffer<enc> s, Py_ssize_t n, npy_ucs4 ch)
     Buffer<enc> p = s, e = s + n;
 
     if (n > MEMCHR_CUT_OFF) {
-        p = s.buffer_memchr(ch, n);
+        p = p.buffer_memchr(ch, n);
```
Comment (mhvk) [inline numpy/_core/src/umath/string_fastsearch.h:65]: This solution works, but it sort-of works around the fact that `buffer_memchr` updates the position of the buffer in-place. My C++ skills were insufficient to trivially solve that.

**Comment by rgommers** [comment]
Thanks for the fixes @mhvk!

> I note that this only increases test coverage for these cases; a larger addition seems warranted.

In the meantime, would it be useful/practical to run the AstroPy test suite (ideally only the relevant subset of it, so it doesn't take forever) when more string ufuncs are added?

Cc @lysnikolaou as the author of these new ufuncs.

**Comment by mhvk** [comment]
> In the meantime, would it be useful/practical to run the AstroPy test suite (ideally only the relevant subset of it, so it doesn't take forever) when more string ufuncs are added?

I'm not sure that we do enough with strings to make that worthwhile - astropy checking with the nightlies is probably good enough. I think what happened here is understandable - one replaces one way of doing it with another, which is like a refactoring, so it is not illogical to assume the test coverage passing is good enough. The part missed was that the replacement here included quite a lot of special cases which were not tested. Ideally, this would have been asked in review.
Or, better still, it is noticed by test coverage runs, though I don't know how well coverage works for templated C++ code...

Actually, now having had to go over the code, a question for @lysnikolaou - I noticed special paths also for more complicated and very large strings. Are those covered by tests?

File: numpy/_core/src/umath/string_fastsearch.h (hunk 1 above)
Comment (lysnikolaou) [reply numpy/_core/src/umath/string_fastsearch.h:65]: That's true. I think it'd be preferrable to fix `buffer_memchr` to return a new buffer without side effects on the calling one.

This would do it probably:

```c
inline Buffer<enc>
buffer_memchr(npy_ucs4 ch, int len)
{
    Buffer<enc> newbuf = *this;
    switch (enc) {
    case ENCODING::ASCII:
        newbuf.buf = (char *) memchr(buf, ch, len);
        break;
    case ENCODING::UTF32:
        newbuf.buf = (char *) wmemchr((wchar_t *) buf, ch, len);
        break;
    }
    return newbuf;
}
```

File: numpy/_core/src/umath/string_ufuncs.cpp [hunk 2]
```diff
@@ -343,29 +343,27 @@ string_replace(Buffer<enc> buf1, Buffer<enc> buf2, Buffer<enc> buf3, npy_int64 c
     npy_int64 len2 = buf2.num_codepoints();
     npy_int64 len3 = buf3.num_codepoints();
 
-    if (len1 < len2
-        || (len2 == 0 && len3 == 0)
-        || count == 0
-        || buf2.strcmp(buf3) == 0) {
-        out.buffer_fill_with_zeros_after_index(0);
-        return;
-    }
```
Comment (lysnikolaou) [inline numpy/_core/src/umath/string_ufuncs.cpp:352]: Is this refactoring needed? If so, could you explain the difference?

**Review by lysnikolaou — COMMENTED** [review]
Thanks @mhvk! Left two comments, but this looks good in general. Also, I don't think the different fast paths are tested well enough (or maybe at all?) here, but I'm planning to add more tests after we move everything to `np.strings`.

**Review by matheussouza88 — APPROVED** [review]

File: numpy/_core/src/umath/string_ufuncs.cpp (hunk 2 above)
Comment (mhvk) [reply numpy/_core/src/umath/string_ufuncs.cpp:352]: Yes, before you returned an empty out if, e.g., the input string is shorter than the replacement string, so cannot possibly match. But in this case, the input string should unchanged, i.e., copied to the output. So, for any of those cases where it is obvious no match will be found, I now fall through directly to copying the input to the output.

Comment (lysnikolaou) [reply numpy/_core/src/umath/string_ufuncs.cpp:352]: Of course! Thanks for the explanation!

File: numpy/_core/src/umath/string_fastsearch.h (hunk 1 above)
Comment (mhvk) [reply numpy/_core/src/umath/string_fastsearch.h:65]: Yes, that makes more sense, and seems to work.

File: numpy/_core/src/umath/string_ufuncs.cpp (hunk 2 above)
Comment (mhvk) [reply numpy/_core/src/umath/string_ufuncs.cpp:352]: Aside, while looking through `strcmp` just to see whether a `(len2 == len3)` would be useful (it is and I'll include it), I noticed that the case for a longer `buf3` would return the wrong sign. Almost certainly never matters, but maybe for a next fix: https://github.com/numpy/numpy/blob/d4a66a3d7e827b99067acd8b47cba4309ace6b42/numpy/_core/src/umath/string_buffer.h#L299-L306 (I don't think I should do it here, but can if you'd like me to).

File: numpy/_core/src/umath/string_fastsearch.h (hunk 1 above)
Comment (mhvk) [reply numpy/_core/src/umath/string_fastsearch.h]: OK, the first commit now changes `buffer_memchr` like you suggested.

File: numpy/_core/src/umath/string_ufuncs.cpp (hunk 2 above)
Comment (mhvk) [reply numpy/_core/src/umath/string_ufuncs.cpp:352]: While looking through the commits, I refactored this a little further. Hopefully, the intent of the `if` statement is clearer now.

**Comment by ngoldbaum** [comment]
It looks like this fixes another regression I ran into:

```
import numpy as np

string_list = ['AbcAbcAbc']

o_dtype = np.str_

oarr = np.array(string_list, dtype=o_dtype)

oarr2 = np.array([s + "2" for s in string_list], dtype=o_dtype)


op = np.greater

ores = op(oarr, oarr2)


print(ores)
print(str(oarr[0]) > str(oarr2[0]))
```

(adapted from the stringdtype tests). On current `main` this incorrectly prints `[True]\nFalse`, but on this PR I get the correct answer.

**Comment by ngoldbaum** [comment]
Pulling this in. Thanks @mhvk!

I know at one point recently we had a bot commenting about missing C coverage but I haven't seen it in a while, having that available would probably also help. I see @lysnikolaou has already pushed some string ufunc tests to his other PR adding an `np.strings` namespace.

If we add more ufuncs in the future I'll look at the C coverage manually before merging, keeping in mind that the `np.char` and `chararray` tests are patchy at best.

**Comment by ngoldbaum** [comment]
> but on this PR I get the correct answer.

Actually not quite right, I think the test code I shared earlier is flaky due to memory corruption, will have a followup PR incoming...

**Comment by mhvk** [comment]
@ngoldbaum - sounds all good! The fact that the answer is not right perhaps is due to what I noted in https://github.com/numpy/numpy/pull/25515#discussion_r1439548201 (which I did not touch here since it seemed out of scope)
