### PR TITLE
BUG: Correctly refcount array descr in empty_like

### LINKED ISSUE #25853: BUG: empty_like crashes when passing in a dtype that cannot be allocated
### Describe the issue:

When passing an invalid dtype to `empty_like`, like `S-1`, it crashes the interpreter because of refcounting issues.

My understanding is that `empty_like` calls `PyArray_NewLikeArrayWithShape`, which eventually uses the array descriptor to set a `numpy._core._exceptions._ArrayMemoryError`. The same descriptors get XDECREF'd after failure, which leads to a crash.

`empty` OTOH does not XDECREF anything, neither on failure nor on success, which might also be wrong. 

### Reproduce the code example:

```python
np.empty_like(np.array(b"abc"), shape=(2, 2), dtype="S-1")
```

### Error message:

```shell
Python 3.11.3 (tags/v3.11.3:f3909b8bc8, May 29 2023, 12:51:44) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.empty_like(np.array(b"abc"), shape=(2, 2), dtype="S-1")
Python/ceval.c:2888: _Py_NegativeRefcount: Assertion failed: object has negative ref count
<object at 0x101ddca40 is freed>
Fatal Python error: _PyObject_AssertFailed: _PyObject_AssertFailed
Python runtime state: initialized

Current thread 0x00000001e4a79000 (most recent call first):
  File "/Users/lysnikolaou/repos/python/numpy/build-install/usr/lib/python3.11/site-packages/numpy/_core/_exceptions.py", line 121 in __init__

Extension modules: numpy._core._multiarray_umath, numpy._core._multiarray_tests, numpy.linalg._umath_linalg (total: 3)
zsh: abort      python -m spin python
```

### Python and NumPy Versions:

2.0.0.dev0+git20240213.8395a91
3.11.3 (tags/v3.11.3:f3909b8bc8, May 29 2023, 12:51:44) [Clang 14.0.3 (clang-1403.0.22.14.1)]

### Runtime Environment:

_No response_

### Context for the issue:

Discovered while writing string ufuncs for `np.strings`.

### PR DESCRIPTION
**Pull request by lysnikolaou**
Closes #25853.

### CODE REVIEW

File: numpy/_core/src/multiarray/multiarraymodule.c [hunk 1]
```diff
@@ -2047,23 +2047,19 @@ array_empty_like(PyObject *NPY_UNUSED(ignored),
...
     }
     /* steals the reference to dt_info.descr if it's not NULL */
+    if (dt_info.descr != NULL) {
+        Py_INCREF(dt_info.descr);
+    }
     ret = (PyArrayObject *)PyArray_NewLikeArrayWithShape(
             prototype, order, dt_info.descr, dt_info.dtype,
             shape.len, shape.ptr, subok);
     npy_free_cache_dim_obj(shape);
-    if (!ret) {
```
Comment (charris) [inline numpy/_core/src/multiarray/multiarraymodule.c:2054]: Is `ret` known not to be `NULL`.

Comment (lysnikolaou) [reply numpy/_core/src/multiarray/multiarraymodule.c:2054]: Νο, it can be NULL. This `if` however only serves the purpose of skipping refcounting for `dt_info.desc`, which we don't want now.

**Comment by ngoldbaum** [comment]
Yikes, this should raise an error:

```
In [1]: import numpy as np

In [2]: np.dtype("S-1")
Out[2]: dtype('S-1')
```

(unless there's some use for this elsewhere?!?!)

**Review by ngoldbaum — APPROVED** [review]
increfing before a function that steals a reference makes sense and it's nice we can refactor the cleanup to be simpler.

**Comment by charris** [comment]
Thanks @lysnikolaou .
