### PR TITLE
BUG: Raise correct errors in boolean indexing fast path

### LINKED ISSUE #16997: "ValueError: operands could not be broadcast together with shapes" error on invalid boolean array index
In some instances, when indexing an array with a boolean array index, instead of getting an `IndexError`, you instead get a `ValueError: operands could not be broadcast together with shapes ...` error.  It seems to happen when the product of the array and index shapes are the same (but the shapes to not match).

### Reproducing code example:

```python
>>> import numpy as np
>>> a = np.empty((3, 3))
>>> a[np.empty((1, 9), dtype=bool)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: operands could not be broadcast together with shapes (3,3) (1,9)
```

Compare the usual case:

```py
>>> a = np.empty((3, 4))
>>> a[np.empty((1, 9), dtype=bool)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 1
```

Another example to back my theory that this only happens when the array sizes match

```py
>>> a = np.empty((2, 2, 4))
>>> a[np.empty((1, 4, 4), dtype=bool)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: operands could not be broadcast together with shapes (2,2,4) (1,4,4)
>>> a[np.empty((1, 2, 4), dtype=bool)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 1
```

Obviously, `ValueError` is the incorrect error for an invalid index, but aside from this, an error mentioning broadcasting of the array shape and the index shape is very confusing since (unless I am mistaken), this never actually happens.

### Numpy/Python version information:

NumPy master:

```py
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.20.0.dev0+8f60522 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16)
[Clang 9.0.1 ]
```

### PR DESCRIPTION
**Pull request by asmeurer**
Previously the logic assumed that an index was valid if the size was the same
as the indexed array, rather than the shape. This resulted in an index being
incorrectly allowed if the index was all False, like np.empty((3, 3))[np.full((1, 9),
False)], or incorrectly giving a ValueError about broadcasting if the index
was not all False (like np.empty((3, 3))[np.full((1, 9), True)]). Now these
examples both give IndexError with the usual error message.

Fixes #16997.

(not really sure about the NumPy commit message flags, or which one should apply to this. Is this considered an API break?)

### CODE REVIEW

**Comment by seberg** [comment]
Probably wouldn't use API, considering how small the change is. But a compatibility release note is necessary, at least for the wrong result → error change.  The comment should now be changed to say that the shape check is always an error, and only there to ensure the same error message as in the generic path (the generic path sets it a bit later, because it may have to expand Ellipsis, etc. so it does not know at that point which dimension the index acts on).

**Comment by asmeurer** [comment]
I'm still a little shaky on the logic in that function, so you'll have to tell me if my updated comments are correct.

File: numpy/core/src/multiarray/mapping.c [hunk 1]
```diff
@@ -539,22 +539,23 @@ prepare_index(PyArrayObject *self, PyObject *index,
...
-                 * If ndim and size match, this can be optimized as a single
-                 * boolean index. The size check is necessary only to support
-                 * old non-matching sizes by using fancy indexing instead.
-                 * The reason for that is that fancy indexing uses nonzero,
-                 * and only the result of nonzero is checked for legality.
+                 * If shapes match exactly, this can be optimized as a single
+                 * boolean index. The reason for that is that fancy indexing
+                 * uses nonzero, and only the result of nonzero is checked for
+                 * legality. Otherwise, if the shapes don't match and it isn't
+                 * the scalar case checked below, it should be an error.
```
Comment (seberg) [inline numpy/core/src/multiarray/mapping.c:553]: The nonzero reference is not useful here, and I doubt its correct. Historically, it *was* correct, but that is a different issue. Maybe:

```suggestion
                 * boolean index. When the dimensions are identical but the shapes are not,
                 * this is always an error. The check ensures that these errors are raised
                 * and match those of the generic path.
```

**Comment by asmeurer** [comment]
I added a changelog entry. I can't figure out how to build the docs (git submodule is doing something stupid), so I hope it renders OK.

**Comment by seberg** [comment]
@asmeurer no need, it seems fine, and most errors should be noted. You can actually press the `ci/circleci: build artifact` link and go to the page, which is: https://15017-908607-gh.circle-artifacts.com/0/doc/build/html/release/1.20.0-notes.html?highlight=release%20notes#boolean-array-indices-with-mismatching-shapes-now-properly-give-indexerror

Looks good to me. A comment for the tests might be nice, they are hard to understand why the different `indx1`, etc. are all wrong in slightly different ways.  The last one is broadcastable but shape mismatch?

For anyone interested: I am planning to put this in.  It does change a corner case of an all False boolean index of matching size but not shape into an error.  It also changes some ValueError → IndexError, but I think we have been pretty liberal about such changes in the past.

**Review by eric-wieser — APPROVED** [review]

**Comment by asmeurer** [comment]
> The last one is broadcastable but shape mismatch?

I guess that's what the difference is. I just found that it gives a different error, `ValueError: non-broadcastable operand with shape (1,1,2) doesn't match the broadcast shape (1,2,2)`, so it presumably goes through a different code path.

**Comment by seberg** [comment]
Thanks @asmeurer, also for adding the final comments to the tests!
