### PR TITLE
MAINT: ssize_t -> Py_ssize_t and other fixes for Python v3.10.0

### LINKED ISSUE #18888: Building with 3.10a7 on windows fails
The 3.10 alpha 7 fails to build for me on windows, see below for the warnings and errors. It seems we should not be using `ssize_t` rather `Py_ssize_t`. On windows, `ssize_t` is not defined anymore in CPython3.10 alpha7 after python/cpython#24479 in response to [issue 17717](https://bugs.python.org/issue11717) from 2011, which was merged March 1.

<details>

```
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Ibuild\src.win-amd64-3.10\numpy\core\src\common -Ibuild\src.win-amd64-3.10\numpy\core\src\umath -Inumpy\core\include -Ibuild\src.win-amd64-3.10\numpy\core\include/numpy -Ibuild\src.win-amd64-3.10\numpy\distutils\include -Inumpy\core\src\common -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -Inumpy\core\src\_simd -Id:\Python310_a7\include -Id:\Python310_a7\include -Ibuild\src.win-amd64-3.10\numpy\core\src\common -Ibuild\src.win-amd64-3.10\numpy\core\src\npymath -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcnumpy\core\src\multiarray\array_method.c /Fobuild\temp.win-amd64-3.10\Release\numpy\core\src\multiarray\array_method.obj
  array_method.c
  numpy\core\include\numpy/npy_3kcompat.h(254): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
  C:\Users\matti\AppData\Local\Temp\pip-install-vn2k2e06\numpy_44d206bb97d8420d8fd6c8185b4fa774\numpy\core\src\multiarray\common.h(240): warning C4244: 'return': conversion from 'npy_uintp' to 'int', possible loss of data
  numpy\core\src\multiarray\array_method.c(394): error C2065: 'ssize_t': undeclared identifier
  numpy\core\src\multiarray\array_method.c(394): error C2146: syntax error: missing ';' before identifier 'length'
  numpy\core\src\multiarray\array_method.c(394): error C2065: 'length': undeclared identifier
  numpy\core\src\multiarray\array_method.c(394): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
  numpy\core\src\multiarray\array_method.c(395): error C2065: 'length': undeclared identifier
```

### PR DESCRIPTION
**Pull request by mattip**
Fixes #18888 

It would be good to get a CI run with the 3.10.0a7 candidate. It seems the easiest way to do that is via the github action setup-python, but all our windows CI runs are on azure pipelines.

### CODE REVIEW

File: numpy/core/include/numpy/npy_3kcompat.h [hunk 1]
```diff
@@ -251,7 +251,7 @@ npy_PyFile_Dup2(PyObject *file, char *mode, npy_off_t *orig_pos)
     if (ret == NULL) {
         return NULL;
     }
-    fd2 = PyNumber_AsSsize_t(ret, NULL);
+    fd2 = (int)PyNumber_AsSsize_t(ret, NULL);
```
Comment (mattip) [inline numpy/core/include/numpy/npy_3kcompat.h:254]: Maybe this should be
```
Py_ssize_t tmp = PyNumber_AsSsize_t(ret, NULL);
if (tmp > INT_MAX || tmp < INT_MIN) {
    /* set an error and return NULL */
}
fd2 = (int)tmp;
```

Comment (eric-wieser) [reply numpy/core/include/numpy/npy_3kcompat.h:254]: This should also check `PyErr_Occurred`, as otherwise if `os.dup` returns non-integer nonsense (someone monkey-patched it) then you probably segfault or `SystemError`.

Comment (mattip) [reply numpy/core/include/numpy/npy_3kcompat.h]: added the check and added a test that monkey-patches `os.dup` to trip failures.

File: numpy/core/tests/test_multiarray.py [hunk 2]
```diff
@@ -5047,6 +5047,19 @@ def test_fromfile_offset(self):
...
+            return 'abc'
+
+        def dup_bigint(fd):
+            return 2*68
+        
+        old_dup = os.dup
+        with open(self.filename, 'wb') as f:
+            self.x.tofile(f)
+            for dup in (dup_str, dup_bigint):
+                assert_raises(OSError, np.fromfile, f)
```
Comment (seberg) [inline numpy/core/tests/test_multiarray.py:5061]:
```suggestion
        old_dup = os.dup
        try:
            with open(self.filename, 'wb') as f:
                self.x.tofile(f)
                for dup in (dup_str, dup_bigint):
                    os.dup = dup
                    assert_raises(OSError, np.fromfile, f)
        finally:
            os.dup = old_dup
```
The monkeypatching part of the test seems to be missing? (I am a bit surprised not more tests are failing though).

Comment (mattip) [reply numpy/core/tests/test_multiarray.py:5061]: thanks

File: numpy/core/tests/test_multiarray.py [hunk 3]
```diff
@@ -5047,6 +5047,23 @@ def test_fromfile_offset(self):
                     np.fromfile, self.filename, dtype=self.dtype,
                     sep=",", offset=1)
 
+    def test_fromfile_bad_dup(self):
+        def dup_str(fd):
+            return 'abc'
+
+        def dup_bigint(fd):
+            return 2*68
```
Comment (seberg) [inline numpy/core/tests/test_multiarray.py:5055]:
```suggestion
            return 2**68
```
I guess... Is that the reason why windows crashes hard?!

**Comment by mattip** [comment]
Skipped the test on PyPy and reported [the issue upstream](https://foss.heptapod.net/pypy/pypy/-/issues/3456)

**Comment by seberg** [comment]
Thanks Matti.  (I am still confused about why this matters, but the changes look good.)

**Comment by charris** [comment]
> Skipped the test on PyPy and reported the issue upstream

Is this going to affect the PyPy wheels?

**Comment by mattip** [comment]
> Is this going to affect the PyPy wheels?

The problem only manifests If `os.dup` returns something that cannot be converted to an `int`, which was broken (but not tested) before this PR. We did not receive bug reports about this problem, so I assume it was not detected in the wild.

**Comment by mattip** [comment]
@seberg: On windows, `ssize_t` is not defined anymore (since python/cpython#24479, in response to issue 17717 from 2011, which was merged March 1 and is now part of Python3.10). The changes needed to support this exposed problems with the error path in the use of `os.dup`, so the PR pivoted to fixing this bug as well, which then overshadowed the original fix of `ssize_t` -> Py_ssize_t`
