### PR TITLE
BUG: fix time cast-safety for `factor*unit` e.g. in `10**6*ms == 1*s`

### LINKED ISSUE #19631: can_cast behaves oddly on unusual datetime units
### Reproducing code example:
I would expect these two to give the same result, since 1000ns = 1us:
```python
import numpy as np
np.can_cast('M8[1000ns]', 'M8[us]', casting='safe')  # False
np.can_cast('M8[us]', 'M8[us]', casting='safe')  # True
```

### NumPy/Python version information:

* 1.19.4
* 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]

### PR DESCRIPTION
**Pull request by tylerjereddy**
Fixes #19631

* for `datetime64` units smaller than `s`, handle some
common/reasonable "metrix prefix" casting conversions like
1000 ns == 1 us

* this adds support specifically for equivalencies that span
10^3 and 10^6 fold, but there are even more beyond that, and if
we want to handle them all we may want to abstract to a handler
function

* that said, this still seems like a solid improvement that covers
some of the more common cases?

### CODE REVIEW

**Comment by tylerjereddy** [comment]
The problem with supporting `10^9` is that we could only do it partially--the 32-bit signed integer means that the following will happen with the integer datetime arithmetic:

```
np.can_cast('M8[2000000000ps]', 'M8[2ms]', casting='safe') # True
np.can_cast('M8[3000000000ps]', 'M8[3ms]', casting='safe') # False
```

The source file already has a few notes like this `TODO: If meta->num is really big, there could be overflow`. Maybe that's what you mean by reorganization in that file.

I can try to deal with that as well--not sure how far reaching the consequences of using a longer integer would be. If that isn't addressed here, we should probably at least make sure an issue is open. Maybe you and Eric can let me know what you prefer.

**Comment by seberg** [comment]
Ah, I had not realized the problem of the integer size.  With reorganization I meant that IIRC some of the code in `datetime.c` was written to report only whether a cast is safe or not, but we want a bit more information now.  And was also only written to deal with `low unit -> high unit` (and not factor) and not the other way around.

I am not sure we should change it from 32 to 64 bits (is it truly private, it may well be?), but it seems that:
```
In [4]: np.dtype('M8[3000000000ps]')
Out[4]: dtype('<M8[-1294967296ps]')
```
should just error out anyway, though.

**Comment by tylerjereddy** [comment]
Ok, I pushed in a revision that adds basic support for 10^9 handling, but raises an error for values greater than `INT_MAX`.

I'm a little concerned about portability though--it works locally with the test I added, but `long int` may need to be `long long int` to force the size for 32-bit systems?

Surprisingly, the code was taking a `long int` from a standard C function and typecasting it to `int` to store the value.

One other note is that I didn't write a custom error message, I just reused one of the current ones, but could if you want since it is not exactly specific at the moment:

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    np.dtype('M8[3000000000ps]')
TypeError: Invalid datetime metadata string "[3000000000ps]" at position 1
```

File: numpy/core/src/multiarray/datetime.c [hunk 1]
```diff
@@ -3775,7 +3781,18 @@ time_to_time_resolve_descriptors(
...
+        // 1000 fold conversions
+        ((meta2->base >= 7) && (meta1->base - meta2->base == 1)
+          && ((meta1->num / meta2->num) == 1000)) ||
+        // 10^6 fold conversions
+        ((meta2->base >= 7) && (meta1->base - meta2->base == 2)
+          && ((meta1->num / meta2->num) == 1000000)) ||
+        // 10^9 fold conversions
+        ((meta2->base >= 7) && (meta1->base - meta2->base == 3)
+          && ((meta1->num / meta2->num) == 1000000000))
+        )  {
```
Comment (seberg) [inline numpy/core/src/multiarray/datetime.c:3795]: I would prefer the numpy-style over-indent (if you prefer the closing `)` on the new-line, I can live with it :).

File: numpy/core/tests/test_datetime.py [hunk 2]
```diff
@@ -137,6 +138,23 @@ def test_datetime_casting_rules(self):
...
+        assert np.can_cast('M8[5000ns]', 'M8[5us]', casting='safe')
+        assert np.can_cast('M8[2000ps]', 'M8[2ns]', casting='safe')
+        assert np.can_cast('M8[9000fs]', 'M8[9ps]', casting='safe')
+        assert np.can_cast('M8[1000as]', 'M8[1fs]', casting='safe')
+        # 10^6 conversions
+        assert np.can_cast('M8[2000000ps]', 'M8[2us]', casting='safe')
+        assert np.can_cast('M8[1000000as]', 'M8[1ps]', casting='safe')
+        # 10^9 conversions below 32-bit overflow limit
+        assert np.can_cast('M8[2000000000ps]', 'M8[2ms]', casting='safe')
+        assert np.can_cast('M8[1000000000as]', 'M8[1ns]', casting='safe')
```
Comment (seberg) [inline numpy/core/tests/test_datetime.py:156]: Could you start a new function for this and test both directions?  These only test smaller unit to larger unit.  Or is that the only thing we fix?

**Review by seberg — COMMENTED** [review]
Just some comments/question.   The error is not ideal, but I won't sweat it.  It was always clearly wrong and still nobody apparently noticed...

I still wonder a bit if this change duplicates logic from `datetime_metadata_divides`, but it probably doesn't matter.  If @eric-wieser likes it (since he brought this up), I am happy enough.  It is a step in the right direction.

File: numpy/core/tests/test_datetime.py (hunk 2 above)
Comment (tylerjereddy) [reply numpy/core/tests/test_datetime.py]: Sure, I drafted in a test that does bidirectional casting checks instead of just small units to large units. Let me know what you think. Luckily, the other direction "just worked" for the cases I already had there.

File: numpy/core/src/multiarray/datetime.c (hunk 1 above)
Comment (tylerjereddy) [reply numpy/core/src/multiarray/datetime.c]: I tried to change the whitespace--not sure if I got it perfect yet.

**Comment by tylerjereddy** [comment]
I switched to `long long int` as well, CI caught that point I was worried about above. Hopefully that forces the sizing on windows/32-bit

File: numpy/core/src/multiarray/datetime.c (hunk 1 above)
Comment (seberg) [reply numpy/core/src/multiarray/datetime.c]: Oh, most code in NumPy indents the second row of if statements (and function calls) by 8 spaces, to offset it from the code block below.  That was what I meant.  I guess that is starting to be less common these days in general, though...

Comment (tylerjereddy) [reply numpy/core/src/multiarray/datetime.c]: Like this?

```diff
diff --git a/numpy/core/src/multiarray/datetime.c b/numpy/core/src/multiarray/datetime.c
index 59155e059..7454bf1a7 100644
--- a/numpy/core/src/multiarray/datetime.c
+++ b/numpy/core/src/multiarray/datetime.c
@@ -3782,16 +3782,16 @@ time_to_time_resolve_descriptors(
     assert(meta2 != NULL);
 
     if ((meta1->base == meta2->base && meta1->num == meta2->num) ||
-        // handle some common metric prefix conversions
-        // 1000 fold conversions
-        ((meta2->base >= 7) && (meta1->base - meta2->base == 1)
-        && ((meta1->num / meta2->num) == 1000)) ||
-        // 10^6 fold conversions
-        ((meta2->base >= 7) && (meta1->base - meta2->base == 2)
-        && ((meta1->num / meta2->num) == 1000000)) ||
-        // 10^9 fold conversions
-        ((meta2->base >= 7) && (meta1->base - meta2->base == 3)
-        && ((meta1->num / meta2->num) == 1000000000))) {
+            // handle some common metric prefix conversions
+            // 1000 fold conversions
+            ((meta2->base >= 7) && (meta1->base - meta2->base == 1)
+            && ((meta1->num / meta2->num) == 1000)) ||
+            // 10^6 fold conversions
+            ((meta2->base >= 7) && (meta1->base - meta2->base == 2)
+            && ((meta1->num / meta2->num) == 1000000)) ||
+            // 10^9 fold conversions
+            ((meta2->base >= 7) && (meta1->base - meta2->base == 3)
+            && ((meta1->num / meta2->num) == 1000000000))) {
         if (byteorder_may_allow_view) {
             return NPY_NO_CASTING | byteorder_may_allow_view;
         }

```

Comment (seberg) [reply numpy/core/src/multiarray/datetime.c]: Yeah.  The additional space you had for the `&&` was good IMO.

File: numpy/core/src/multiarray/datetime.c [hunk 3]
```diff
@@ -722,9 +722,15 @@ parse_datetime_extended_unit_from_string(char const *str, Py_ssize_t len,
 {
     char const *substr = str, *substrend = NULL;
     int den = 1;
+    long long int true_meta_num;
```
Comment (tylerjereddy) [inline numpy/core/src/multiarray/datetime.c:725]: I may need `int64_t` or similar here to force a fixed-width integer of the size I want

Comment (seberg) [reply numpy/core/src/multiarray/datetime.c]: Hmmpf,
```
typedef struct {
    NPY_DATETIMEUNIT base;
    int num;
} PyArray_DatetimeMetaData;
```
defines it as an `int`, unfortunately, that is defined in the public header.

I don't see how changing the type will help, but maybe using `NumPyOS_strtoll` will.  I guess that function is also a bit wrong: It sets `errno` on overflow, but we never check for that, for example in `np.fromstring`…  I would no be surprised if it is easier to go via `PyLong_FromString `

Comment (tylerjereddy) [reply numpy/core/src/multiarray/datetime.c]: On platforms that treat `long int` as 64 bit integer it helps because the C function `strtol` used to return the value here uses that type, so I can check the "true value" before the typecast to shorter integer.

Unfortunately, on platforms where that is not true, it won't matter what I set the temporary check value to if the overflow has already happened, which may be what you are getting at (I wasn't trying to change the type of the public value, just the `true_meta_num` temporary storage value I check for overflow).

I had considered `PyLong_FromString`, I may indeed have to do something like that..

File: numpy/core/src/multiarray/datetime.c [hunk 4]
```diff
@@ -728,6 +728,22 @@ parse_datetime_extended_unit_from_string(char const *str, Py_ssize_t len,
...
+        // check for 32-bit integer overflow
+        char subs_digits[20];
+        strcpy(subs_digits, substr);
+        uint64_t idx;
+        for(idx=0; idx<strlen(substr); idx++) {
+            if(isdigit(substr[idx]) == 0) {
+                break;
+            }
+        }
+        subs_digits[idx] = '\0';
```
[the remark this answers is not in the document]
Comment (tylerjereddy) [reply numpy/core/src/multiarray/datetime.c]: I tried pushing in an adjustment to use `NumPyOS_strtoll`; haven't checked the `1_000` or negative value stuff yet, if that is still important.

[the remark this answers is not in the document]
Comment (tylerjereddy) [reply numpy/core/src/multiarray/datetime.c]: For the other two queries, negative values seem to work on this feature branch but not i.e., `2_000`:

```
--- a/numpy/core/tests/test_datetime.py
+++ b/numpy/core/tests/test_datetime.py
@@ -144,6 +144,8 @@ def test_datetime_prefix_conversions(self):
         # attoseconds for bidirectional conversions
         smaller_units = ['M8[7000ms]',
                          'M8[2000us]',
+                         'M8[2_000us]',
+                         'M8[-2000us]',
                          'M8[1000ns]',
                          'M8[5000ns]',
                          'M8[2000ps]',
@@ -155,6 +157,8 @@ def test_datetime_prefix_conversions(self):
                          'M8[1000000000as]']
         larger_units = ['M8[7s]',
                         'M8[2ms]',
+                        'M8[2ms]',
+                        'M8[-2ms]',
                         'M8[us]',
                         'M8[5us]',
                         'M8[2ns]',
```

`python runtests.py -t "numpy/core/tests/test_datetime.py"`

`1 failed, 246 passed, 4 xfailed in 0.90s`

`E   TypeError: Invalid datetime unit in metadata string "[2_000us]"`

I don't have strong opinions on what should happen on those cases. For negative values I kind of get what I would expect (?), moving backwards from the UNIX epoch, but not sure if that is intended or not:

```python
print("arr:", np.array([2], dtype='M8[-3ps]'))
# arr: ['1969-12-31T23:59:59.999999999994']
```

I'm happy to encode the desired behaviors in unit tests if you want to stipulate what they should be.

[the remark this answers is not in the document]
Comment (tylerjereddy) [reply numpy/core/src/multiarray/datetime.c]: I guess you also mentioned non-exact transitions on the units. I'd have to think more about that--I suppose I was somewhat naively hoping that fixing a subset of bad behaviors and encoding the fixes in unit tests would be a step forward, though if this stuff isn't super thoroughly tested I could also see that changing *de facto* behaviors might be annoying even if they are not detected by the current test suite.

[the remark this answers is not in the document]
Comment (tylerjereddy) [reply numpy/core/src/multiarray/datetime.c]: Well, I should clarify that with negative values we don't have bidirectional casting yet as far as I can tell:

```python
import numpy as np
print(np.can_cast('M8[-2000ns]', 'M8[-2us]')) # True
print(np.can_cast('M8[-2us]', 'M8[-2000ns]')) # False
```

On `main`, both are currently `False`--do you want me to try to get the second one `True` in this PR as well?

[the remark this answers is not in the document]
Comment (seberg) [reply numpy/core/src/multiarray/datetime.c]: Have to check the rest, but I would just not worry about negative?  It seems we should just deprecate (or even just make them an error) anyway, I don't see a point, except to confuse users accidentally creating it.

[the remark this answers is not in the document]
Comment (tylerjereddy) [reply numpy/core/src/multiarray/datetime.c]: @seberg Not sure if you want it, but I've at least temporarily made the negative `M8` `dtype` a `TypeError` + regression test for that.

```python
np.array(1, dtype='M8[-1s]')
```

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    np.array(1, dtype='M8[-1s]')
TypeError: Invalid datetime metadata string "[-1s]" at position 1
```

**Review by seberg — APPROVED** [review]
Thanks @tylerjereddy, I think I like this approach and the removal of negative time factors (in principle ideal or not, both seem like the practical choice to me).

For me, this PR can go in, if anyone would prefer e.g. a release note, please make a comment.  Otherwise, we should just merge it soon.

**Comment by seberg** [comment]
Thanks Tyler, if since no one else voiced an opion.  Lets put it in!  My only concern would be someone actually using negative time scales, and frankly that seems weird enough (and plausibly buggy enough) that we should just ignore it.
