### PR TITLE
BUG: allow division between object-dtype arrays and timedelta objects

### LINKED ISSUE #30025: BUG: truediv with object array and timedelta64 raises
### Describe the issue:

Dividing a NumPy array of object dtype holding Python timedeltas by `np.timedelta64` raises an exception, where as dividing elementwise is successful. I would have expected the op to act elementwise successfully.

### Reproduce the code example:

```python
from datetime import timedelta
import numpy as np

arr = np.array([timedelta(seconds=1)], dtype="object")
scalar = np.timedelta64(1, 's')

print(arr[0] / scalar)
# 1.0

print(arr / 2)
# [datetime.timedelta(microseconds=500000)]

print(arr / scalar)
# numpy._core._exceptions._UFuncBinaryResolutionError: ufunc 'divide' cannot use operands with types dtype('O') and dtype('<m8[s]')
```

### Error message:

```shell

```

### Python and NumPy Versions:

Python 3.11.13
numpy 2.3.4

### Runtime Environment:

_No response_

### Context for the issue:

Encountered in https://github.com/pandas-dev/pandas/issues/62712

cc @seberg

### PR DESCRIPTION
**Pull request by riku-sakamoto**
Closes #30025 

Fixes a bug where dividing an object-dtype array containing Python timedelta objects by a NumPy timedelta64 scalar would raise a `_UFuncBinaryResolutionError`. The operation now falls back to the generic object ufunc loop, enabling elementwise Python evaluation consistent with other object operations.

* Example

```python
arr = np.array([timedelta(seconds=1)], dtype="object")
scalar = np.timedelta64(10, 's')
arr / scalar 
# Used to be _UFuncBinaryResolutionError
# Now returns array([0.1]) dtype=object
```

* Notes

Other arithmetic ops ( `+`, `-`, `*` ) have similar inconsistencies. I plan to open follow-up MRs if needed.

### CODE REVIEW

File: numpy/_core/src/umath/ufunc_type_resolution.c [hunk 1]
```diff
@@ -1328,6 +1328,14 @@ PyUFunc_DivisionTypeResolver(PyUFuncObject *ufunc,
...
         }
     }
+    else if (PyTypeNum_ISOBJECT(type_num1) || PyTypeNum_ISOBJECT(type_num2)) {
+        /* Delegate to the default resolver. 
+        * This selects the generic O->O object loop (elementwise Python op),
+        * allowing operations with Python timedelta objects inside object arrays.
+        */
+        return PyUFunc_DefaultTypeResolver(ufunc, casting, operands,
+                    type_tup, out_dtypes);
+    }
```
Comment (seberg) [inline numpy/_core/src/umath/ufunc_type_resolution.c]: Looks good, small preference: Can we handle this at the very top to keep the "use default" paths together?

File: numpy/_core/tests/test_ufunc.py [hunk 2]
```diff
@@ -726,6 +727,54 @@ def test_true_divide(self):
...
+    )
+    def test_true_divide_object_by_timedelta(
+        self,
+        inputs: np.ndarray | type[np.generic],
+        divisor: np.ndarray | type[np.generic],
+        expected: np.ndarray,
+    ):
+        # gh-30025
+        results = inputs / divisor
+        assert_array_equal(results, expected)
```
Comment (seberg) [inline numpy/_core/tests/test_ufunc.py]: I would also slightly prefer to move this to `test_datetime.py` since it's very datetime specific.

**Review by seberg — COMMENTED** [review]
Looks good, thanks.  Two small code style nits.

File: numpy/_core/src/umath/ufunc_type_resolution.c (hunk 1 above)
Comment (riku-sakamoto) [reply numpy/_core/src/umath/ufunc_type_resolution.c]: Sure! I changed it as you suggested.

File: numpy/_core/tests/test_ufunc.py (hunk 2 above)
Comment (riku-sakamoto) [reply numpy/_core/tests/test_ufunc.py]: I moved it to `test_datetime.py`.

**Comment by riku-sakamoto** [comment]
@seberg Thank you for the review! One CI job is currently failing, but it seems unrelated to these changes.
I'll check it just in case.

(Update)
This CI error has already been reported.
https://github.com/numpy/numpy/issues/29953

**Review by seberg — APPROVED** [review]
Thanks @riku-sakamoto , LGTM.

**Comment by ngoldbaum** [comment]
Thanks for the fix and expanded test coverage!
