### PR TITLE
BUG: longdouble with elsize 12 is never uint alignable

### LINKED ISSUE #12607: 1.6.0rc1 3.7 debug: test failure: test_multiarray.py::TestAlignment::test_various_alignments Aborted
Hello,
when running the test suite on i386 wit python3.7 in the debug flavor we get this abort:

```
-- running tests for 3.7 debug --
NumPy version 1.16.0rc1
NumPy relaxed strides checking option: True
============================= test session starts ==============================
platform linux -- Python 3.7.2rc1, pytest-3.10.1, py-1.7.0, pluggy-0.8.0 -- /usr/bin/python3.7-dbg
cachedir: .pytest_cache
rootdir: /<<PKGBUILDDIR>>, inifile: pytest.ini
collecting ... collected 7336 items / 167 deselected
...
tmp/usr/lib/python3/dist-packages/numpy/core/tests/test_multiarray.py::TestAlignment::test_various_alignments Aborted
```

could you have a look?

thanks!

### PR DESCRIPTION
**Pull request by mattip**
Fix #12607 

It seems we hit an alignment assert on 32bit linux with longdouble dtype (which has elsize 12). Fix it in two stages (the first commit only extends CI to test asserts):

1. Add `-UNDEBUG` to the `CFLAGS` so that the assert statements are checked (debug mode)
2. Find and fix the underlying alignment issue

### CODE REVIEW

**Comment by mattip** [comment]
Commit 1 succeeded - the [32 bit test run crashed](https://dev.azure.com/numpy/numpy/_build/results?buildId=1416). 

Fix added for `longdouble` in the next commit and tests are passing, but I am not sure it belongs there since `longdouble` is not a `uint`.

**Comment by mattip** [comment]
@ahaldane The end result is that any dtype with a non-power-of-two `elsize` (like longdouble on platforms where it is 12) will always be non-aligned? Is that the desired outcome?

File: numpy/core/src/common/array_assign.c [hunk 1]
```diff
@@ -125,9 +125,13 @@ raw_array_is_aligned(int ndim, npy_intp *shape,
 
         return npy_is_aligned((void *)align_check, alignment);
     }
-    else {
+    else if (alignment == 1) {
         return 1;
     }
+    else {
+        /* always return false for alignment == 0, which means unaligned */
+        return 0;
```
Comment (eric-wieser) [inline numpy/core/src/common/array_assign.c]: Why is `alignment == 0` even a legal argument to this function?

File: numpy/core/src/common/array_assign.h [hunk 2]
```diff
@@ -88,7 +88,8 @@ broadcast_strides(int ndim, npy_intp *shape,
 /*
  * Checks whether a data pointer + set of strides refers to a raw
  * array whose elements are all aligned to a given alignment.
- * alignment should be a power of two.
+ * alignment should be a power of two, or may be the sentinel value 0 to mean
+ * unaligned, in which case false is always returned.
```
Comment (eric-wieser) [inline numpy/core/src/common/array_assign.h]: This comment confuses me - I read this as saying that `is_aligned(..., alignment = 0)` means `is_unaligned(...)`

File: numpy/core/src/common/array_assign.c (hunk 1 above)
Comment (ahaldane) [reply numpy/core/src/common/array_assign.c]: Maybe there is a better way to organize it... but the idea is that `npy_uint_alignment`, which normally returns the uint alignment, returns 0 if the type is not uint-alignable.

Then, it turned out to be convenient to allow the result of `npy_uint_alignment` to be passed directly to `raw_array_is_aligned`. 

An alternative would be to check the return value of `npy_uint_alignment` explicitly everywhere it is used. But since it is pretty much always used as an arg to `raw_array_is_aligned` it seemed less complicated this way.

**Comment by ahaldane** [comment]
> The end result is that any dtype with a non-power-of-two elsize (like longdouble on platforms where it is 12) will always be non-aligned? Is that the desired outcome?

That's the idea, except to be precise it will be non-*uint* aligned.

The logic is that the aligned copy code in `lowelevel_strided_loops.c.src` can only handle datatypes whose elsize is a power of two, as it does something like `(*((uint64 *)dst)) = *((uint64 *)src);`. See https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/lowlevel_strided_loops.c.src#L133

Actually, it now occurs to me this might be relaxed a bit: An elsize of 12 could be uint-aligned to 4 bytes, so we could use a `uint32` to copy such a type, maybe.

File: numpy/core/src/common/array_assign.h (hunk 2 above)
Comment (ahaldane) [reply numpy/core/src/common/array_assign.h]: If I am not misreading you, that is what the comment is meant to say. If you pass an alignment of 0, the function always returns "not aligned". Do you mean I should say "not aligned" instead of "unaligned"?

Comment (eric-wieser) [reply numpy/core/src/common/array_assign.h]: Right. the return value means "not aligned", but the meaning of the `alignment` argument is closer to "unalignable"

**Comment by mattip** [comment]
> this might be relaxed a bit: An elsize of 12 could be uint-aligned to 4 bytes, so we could use a uint32 to copy such a type

Let's leave this as a bugfix, and think about enhancements for another PR.

File: numpy/core/src/common/array_assign.h (hunk 2 above)
Comment (mattip) [reply numpy/core/src/common/array_assign.h]: fixing

File: numpy/core/src/common/array_assign.c (hunk 1 above)
Comment (mattip) [reply numpy/core/src/common/array_assign.c]: changed the comment

**Review by eric-wieser — APPROVED** [review]
Looks good to me now

**Comment by eric-wieser** [comment]
Can we add a test case for this in any easy way? Does the `V12` dtype show this problem too?

**Comment by eric-wieser** [comment]
Nope, what you have is fine - I missed that the 32-bit build now catches the problem. Was just wondering if there's a platform-agnostic way this bug manifested itself.

**Comment by charris** [comment]
Thanks Matti, Alan.

**Comment by charris** [comment]
It is easier to backport these things if (internal) merges are done fast forward. Putting the test last, or at least squashed with the fix,  is also helpful if a bisect needs to be done in the future.

**Comment by ahaldane** [comment]
I think the merge was done automatically by github on Matti's github repo which I made a PR to. I'm not sure what the best way is for us to collaborate on PRs.

**Comment by charris** [comment]
During the work on `__array_ufunc__` I would periodically rebase so that the merges were fast forward. In this case, I ended up checking out the pr and a simple rebase, took care of the merge. Not sure why it works, but I'm happy.
