### PR TITLE
BUG: Fix iteration over reversed subspaces in mapiter_@name@

### LINKED ISSUE #8264: BUG: Indexed slicing of views resulting in a segmentation fault
```Python
import numpy as np

arro = np.zeros((4, 4))
arr = arro[::-1, ::-1]

slices = [slice(None), [0, 1]]
arr[slices] = 10

print np.__version__
print arr
```

Output from numpy master:
```
1.13.0.dev0+0268680
[[ 10.  10.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]
Segmentation fault (core dumped)
```

This worked in earlier versions of numpy:
```
1.8.2
[[ 10.  10.   0.   0.]
 [ 10.  10.   0.   0.]
 [ 10.  10.   0.   0.]
 [ 10.  10.   0.   0.]]
```

Note:  The code behaves as expected if we use the original array (i.e. arr = arro).  It also works if we do not take a reversed view of the original (i.e. arr = arro[::1, ::1]).

### PR DESCRIPTION
**Pull request by rainwoodman**
This PR will fix 8264. It is a WIP.

### CODE REVIEW

File: numpy/core/src/multiarray/lowlevel_strided_loops.c.src [hunk 1]
```diff
@@ -1707,10 +1712,22 @@ mapiter_@name@(PyArrayMapIterObject *mit)
                 }
 
                 /*
-                 * Resetting is slow, so skip if the subspace iteration has
-                 * only a single inner loop.
+                 * Resetting is slow, so skip if the subspace iteration is
```
Comment (rainwoodman) [inline numpy/core/src/multiarray/lowlevel_strided_loops.c.src]: @seberg I am not sure if the prediction works correctly for higher dimensional subspace.
Saying the fastest dimension has strides == +-itemsize, but the last-fastest dimension doesn't. Not sure if I can quickly come up with a test case.

**Comment by rainwoodman** [comment]
Linking the PR to #8264

File: numpy/core/src/multiarray/lowlevel_strided_loops.c.src (hunk 1 above)
Comment (seberg) [inline numpy/core/src/multiarray/lowlevel_strided_loops.c.src]: Let me try to explain nditer a bit, I think it will make things clear why it should work. I am not sure it might help but...

The advanced iterator will always do some "iteration", after each of these there is an inner loop optimization. This inner loop can be iterated trivially by a single stride. Now in principle the inner stride you need can change of course.
This is why there is the check that the innerloop is actually the complete iteration. If the innerloop spans the whole iteration there is no reason for the innermost stride to change later on (assuming no buffering, buffering might add weirdness). The only reason why this could happen is if the strided layout is different for different "subspaces/inner iteration positions", but that is not compatible to numpy's memory layout.
All in all, even if you change the iterator to do a different iteration order, these things should still work as far as I can tell.

Comment (seberg) [inline numpy/core/src/multiarray/lowlevel_strided_loops.c.src]: Yes, precisely. And no, I don't know a nice word for that property, since its not contiguous....

File: numpy/core/src/multiarray/lowlevel_strided_loops.c.src [hunk 2]
```diff
@@ -1724,6 +1741,10 @@ mapiter_@name@(PyArrayMapIterObject *mit)
                         NPY_AUXDATA_FREE(transferdata);
                         return -1;
                     }
+                    if(subspace_ptrs[0] == self_ptr &&
+                       subspace_ptrs[1] == mit->extra_op_ptrs[0]) {
+                        skip <<= 1;
```
Comment (seberg) [inline numpy/core/src/multiarray/lowlevel_strided_loops.c.src]: Not sure why two iterations without checking closer, but can't the bit shift overflow to 0?

File: numpy/core/src/multiarray/lowlevel_strided_loops.c.src (hunk 1 above)
Comment (rainwoodman) [inline numpy/core/src/multiarray/lowlevel_strided_loops.c.src]: We probably want to give it a name to properly refer to it. I see code appears to be dealing with this in numpy.reshape too.

File: numpy/core/src/multiarray/lowlevel_strided_loops.c.src (hunk 2 above)
Comment (rainwoodman) [inline numpy/core/src/multiarray/lowlevel_strided_loops.c.src]: For the second part of your question: shifting stops after skip == 4 -- if skip started with 1. Otherwise skip started with 0 and shifting never do anything. So it won't overflow.  

The first part of your question I don't really understand.

Comment (rainwoodman) [inline numpy/core/src/multiarray/lowlevel_strided_loops.c.src]: skip = 1(fit the offset), 2 (twice, fit the stride), 4(the linear model is fitted, use predictions from this point on)

Comment (rainwoodman) [inline numpy/core/src/multiarray/lowlevel_strided_loops.c.src]: I think you are right. I changed it to 1 and all tests passes too. The offset from selfptr and the first iteration is always a constant, and we can calculate it on the first iteration.

File: numpy/core/src/multiarray/lowlevel_strided_loops.c.src [hunk 3]
```diff
@@ -1632,7 +1632,8 @@ mapiter_@name@(PyArrayMapIterObject *mit)
         char *subspace_baseptrs[2];
         char **subspace_ptrs = mit->subspace_ptrs;
         npy_intp *subspace_strides = mit->subspace_strides;
-        int skip = 0;
+        int is_reset_trivial = 1;
+        npy_intp reset_offsets[2];
```
Comment (seberg) [inline numpy/core/src/multiarray/lowlevel_strided_loops.c.src]: Should be initialized to avoid compile time warning.

File: numpy/core/src/multiarray/lowlevel_strided_loops.c.src [hunk 4]
```diff
@@ -1666,10 +1667,12 @@ mapiter_@name@(PyArrayMapIterObject *mit)
         }
 
         counter = NpyIter_GetInnerLoopSizePtr(mit->subspace_iter);
-        if (*counter == PyArray_SIZE(mit->subspace)) {
-            skip = 1;
+        if (*counter != PyArray_SIZE(mit->subspace)) {
+           /*
+            * if the subspace iterator skips, we cannot avoid resetting
+            */
```
Comment (seberg) [inline numpy/core/src/multiarray/lowlevel_strided_loops.c.src]: Remembered the word, its "trivially iterable" (at least within much of our code). Just trying to make it a bit clearer (only some thougths): If the subspace iterator is not trivially iterable (so not in a single stride), it has to be reset to the correct start point in every outer iteration. If it is trivially iterable we can avoid using it alltogether (the actual loop does nothing).

File: numpy/core/src/multiarray/lowlevel_strided_loops.c.src [hunk 5]
```diff
@@ -1707,10 +1710,21 @@ mapiter_@name@(PyArrayMapIterObject *mit)
...
+                 * if the subspace iteration is non-skipping.
+                 *
+                 * Resetting is avoided iif the next pointer points to
+                 * the correct location (identical to resetting).
+                 *
+                 * Also notice skip is kept as a `global` outside of the loop,
+                 * because the internal iteration of each external iterations,
+                 * share the same structure, if we are correct once we know
+                 * future iterations we are always correct.
+                 *
```
Comment (seberg) [inline numpy/core/src/multiarray/lowlevel_strided_loops.c.src]: No need for extra blank line. The comment is outdated with this version of the code.

File: numpy/core/src/multiarray/lowlevel_strided_loops.c.src [hunk 6]
```diff
@@ -1724,10 +1738,20 @@ mapiter_@name@(PyArrayMapIterObject *mit)
                         NPY_AUXDATA_FREE(transferdata);
                         return -1;
                     }
+                    if (is_reset_trivial != 0) {
+                        /* resetting is trivial, calculate the offsets */
+                        reset_offsets[0] = subspace_ptrs[0] - self_ptr;
+                        reset_offsets[1] = subspace_ptrs[1] - mit->extra_op_ptrs[0];
+                        /* use the faster adjustment */
+                        is_reset_trivial ++;
```
Comment (seberg) [inline numpy/core/src/multiarray/lowlevel_strided_loops.c.src]: Nitpick: I wouldn't put the space, though I guess it really does not matter, nor am I sure its part of any style guideline.

File: numpy/core/src/multiarray/lowlevel_strided_loops.c.src [hunk 7]
```diff
@@ -1724,10 +1738,20 @@ mapiter_@name@(PyArrayMapIterObject *mit)
...
+                    }
                 }
                 else {
-                    subspace_ptrs[0] = self_ptr;
-                    subspace_ptrs[1] = mit->extra_op_ptrs[0];
+                    /*
+                     * will avoid resetting if the reset is trival.
```
Comment (seberg) [inline numpy/core/src/multiarray/lowlevel_strided_loops.c.src]: Possibly could try to expand this a little along the same lines as above, especially an example might help. If the inner/subspace iterator is trivially iterable, we still may need to calculate the correct starting point of the iteration. The offset is typically zero unless reversing the iteration is more efficient (originally a negative stride)  in reversed order in which case this is the offset to the last item.

File: numpy/core/tests/test_indexing.py [hunk 8]
```diff
@@ -497,6 +497,14 @@ def test_indexing_array_weird_strides(self):
         zind = np.zeros(4, dtype=np.intp)
         assert_array_equal(x2[ind, zind], x2[ind.copy(), zind])
 
+    def test_indexing_array_weird_strides_8264(self):
```
Comment (seberg) [inline numpy/core/tests/test_indexing.py]: Does not matter, but maybe negative strides explicitly is nicer ;).

**Review by seberg — COMMENTED** [review]
Looks good. It seems that defining `reset_offsets` (or maybe we can even think of a new name) is pretty understandable. It would be cool if we can make the comments a bit clearer, I tried to suggest/drop some words, maybe you can think of something nicer too.

File: numpy/core/src/multiarray/lowlevel_strided_loops.c.src (hunk 3 above)
Comment (rainwoodman) [inline numpy/core/src/multiarray/lowlevel_strided_loops.c.src]: Is it proper numpy C to initialize with {}?

File: numpy/core/src/multiarray/lowlevel_strided_loops.c.src (hunk 5 above)
Comment (rainwoodman) [inline numpy/core/src/multiarray/lowlevel_strided_loops.c.src]: updated

**Comment by seberg** [comment]
Thanks, looks all good. If you can squash it, I will put this in.

**Comment by rainwoodman** [comment]
squashed.

**Comment by charris** [comment]
The summary line could be improved, something like
```
BUG: Fix iteration over subspaces in mapiter_@name@.
```
Then put the `Fixes #8264` at the bottom of the commit message,

**Comment by charris** [comment]
Also more explanation of what the problem was, e.g., visible failure. Currently is all `what` and no `why`.

**Comment by rainwoodman** [comment]
Indeed. Poorly written. How does it look now?

**Comment by charris** [comment]
LGTM. I'll let @seberg finish it up.

**Comment by seberg** [comment]
LGTM, thanks a lot @rainwoodman.

**Comment by rainwoodman** [comment]
my pleasure!
