### PR TITLE
DEP: FutureWarning for void.item(): Will return bytes

### LINKED ISSUE #8129: Constructing object array from void array leads to use-after-free
If you do this:

```
np.array(np.zeros(3, 'i4'), object)
```

You get an array of 3 objects, where each is a (reference to an) integer.  However, if you do this:

```
np.array(np.zeros(3, 'V4'), object)
```

You get an array of 3 `read-write buffer ptr` objects, for example:

```
array([<read-write buffer ptr 0x19965d0, size 4 at 0x7f556a3568f0>,
       <read-write buffer ptr 0x19965d4, size 4 at 0x7f556a356930>,
       <read-write buffer ptr 0x19965d8, size 4 at 0x7f556a3568b0>], dtype=object)
```

And while these buffers do allow you to access the void data, they do not hold any reference to it.  This leads to use-after-free memory access violations, like this:

```
va = np.zeros(300000, 'V4')
oa = np.array(va, object)
del va
print(oa[0][0], oa[-1][-1])
```

That often causes a segmentation fault on my machine (Linux).

This is also the root cause of a crash in Pandas: https://github.com/pydata/pandas/issues/14349

I'm using NumPy 1.10.2 and 1.11.1 on Python 3.5.

### PR DESCRIPTION
**Pull request by ahaldane**
This PR holds off on the changes of #8157  (to fix #8129), and instead issues a FutureWarning if anyone calls `void.item()`. We would push off #8157 to 1.15.

### CODE REVIEW

**Comment by eric-wieser** [comment]
I don't like the idea of an unconditional warning, especially when numpy has a habit of calling `.item` internally.

**Comment by ahaldane** [comment]
While it would be ideal to make it configurable, it also seems tricky, and the cost/benefit ratio of coding it up seems high.

Some points in favor of an unconditional warning: 1. Even *internal* uses of `void.item()` are probably bugs which we would want to hear about. 2. None of the test code ever use `void.item()`, even internally. 3. Any casting or other code that tried to do `arr.setitem(void.getitem())` already fails since buffers can't be converted to voids.

**Comment by eric-wieser** [comment]
Running `int(np.void(b'10'))` results in `void.item` being called, but maybe that's a bug too.

**Comment by ahaldane** [comment]
I'm not sure it's a bug, but I'd also add that it raises an error like in my case 3. (In fact, it gives different errors in Python3 and Python2).

It might not be a bug because once we switch to returning `bytes` it will "work".

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 1]
```diff
@@ -729,6 +731,23 @@ VOID_getitem(void *input, void *vap)
         PyArray_UpdateFlags((PyArrayObject *)ret, NPY_ARRAY_UPDATE_ALL);
         return (PyObject *)ret;
     }
+    
+    if (!future_warning_emitted){
+        /* 2017-11-17, 1.14 */
+        if (DEPRECATE_FUTUREWARNING(
+                "the `.item()` method of unstructured void types will return "
+                "an immutable `bytes` object in the near future instead of the "
+                "mutable memoryview or integer array returned in numpy 1.13.")
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/arraytypes.c.src]: Maybe worth noting that this is already possible with `bytes(void_obj)` and/or `bytearray(void_obj)`

**Comment by charris** [comment]
Let's go with the `FutureWarning`, that will at least get us some feedback.

File: numpy/core/tests/test_regression.py [hunk 2]
```diff
@@ -2233,7 +2233,15 @@ def test_scalar_copy(self):
             item = sctype(values.get(sctype, 1))
             item2 = copy.copy(item)
             assert_equal(item, item2)
-
+    def test_void_item_memview(self):
```
Comment (eric-wieser) [inline numpy/core/tests/test_regression.py]: Missing newline

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 3]
```diff
@@ -730,6 +732,24 @@ VOID_getitem(void *input, void *vap)
...
+                "returned by `bytes(void_obj)`, instead of the mutable "
+                "memoryview or integer array returned in numpy 1.13.")
+                < 0) {
+            return NULL;
+        }
+        future_warning_emitted = 1;
+    }
+    /*
+     * In the future all the code below will be replaced by
+     *     // For unstructured void types like V4, return a bytes object (copy).
```
Comment (charris) [inline numpy/core/src/multiarray/arraytypes.c.src]: No C++ comments.

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 4]
```diff
@@ -730,6 +732,24 @@ VOID_getitem(void *input, void *vap)
         return (PyObject *)ret;
     }
 
+    if (!future_warning_emitted){
```
Comment (charris) [inline numpy/core/src/multiarray/arraytypes.c.src]: Hmm, Is this restriction needed? For that matter, is it wanted? What if someone wants to find all the places that need fixing?

File: numpy/core/src/multiarray/arraytypes.c.src (hunk 3 above)
Comment (ahaldane) [reply numpy/core/src/multiarray/arraytypes.c.src]: Technically this is not a C++ comment :)  I'll fix it though.

**Comment by ahaldane** [comment]
Yeah I think I should remove the `filter_waring_emitted` as you said.

As to the question of how to turn off the warning if it is not needed, I think the user should just use `warnings.filterwarnings` - the warnings module already provides a way of silencing it.

**Comment by charris** [comment]
Merged, thanks Allan. We'll see how it goes ...
