### PR TITLE
ENH: Restore TypeError cleanup in array function dispatching

### LINKED ISSUE #23029: BUG: array-function wrapped functions use dispatcher name in traceback (currently)
I noticed that gh-21731 (the test there is subtly wrong) is broken by gh-23020.  This is somewhat more tedious to get right in C, so I think I would prefer fixing it as a follow-up.

EDIT: Just to note, in general it is a bit nicer, because moving things to C removes the confusing `<array-function-internals>` stack from the traceback.

_Originally posted by @seberg in https://github.com/numpy/numpy/issues/23020#issuecomment-1385803808_

### PR DESCRIPTION
**Pull request by seberg**
When the dispatcher raises a TypeError and it starts with the dispatchers name (or actually __qualname__ not that it normally matters), then it is nicer for users if we just raise a new error with the public symbol name.

Python does not seem to normalize exception and goes down the unicode path, but I assume that e.g. PyPy may not do that.  And there might be other weirder reason why we go down the full path.  I have manually tested it by forcing Normalization.

Closes gh-23029

### CODE REVIEW

File: numpy/core/src/multiarray/arrayfunction_override.c [hunk 1]
```diff
@@ -428,10 +431,72 @@ dispatcher_dealloc(PyArray_ArrayFunctionDispatcherObject *self)
...
+    if (cmp <= 0) {
+        Py_DECREF(message);
+        goto restore_error;
+    }
+    Py_SETREF(message, PyUnicode_Replace(
+            message, self->dispatcher_name, self->public_name, 1));
+    if (message == NULL) {
+        goto restore_error;
+    }
+    PyErr_SetObject(PyExc_TypeError, message);
```
Comment (charris) [inline numpy/core/src/multiarray/arrayfunction_override.c:487]: What happens to the original error?

**Comment by charris** [comment]
The reference counting here is a tangle :)

File: numpy/core/src/multiarray/arrayfunction_override.c (hunk 1 above)
Comment (seberg) [reply numpy/core/src/multiarray/arrayfunction_override.c:487]: The message was mutated, the original error/traceback is assumed to be irrelevant (i.e. something like `TypeError: _median() doesn't have a keyword argument '...'` when it should be `median()`.

Comment (charris) [reply numpy/core/src/multiarray/arrayfunction_override.c:487]: I'm probably confused here, but isn't the original error still there and this  sets a new error?

Comment (seberg) [reply numpy/core/src/multiarray/arrayfunction_override.c:487]: `PyErr_Fetch` clears the original error.  Although I think `PyErr_SetObject` would do so also if the error was still in progress.
