### PR TITLE
BUG: maximum, minimum no longer emit warnings on NAN

### LINKED ISSUE #12038: numpy.maximum since 1.15 raises RuntimeWarning when encountering a NaN even though the docs say it should propagate NaNs
`numpy.maximum` now raises a RuntimeWarning when encountering a NaN, but the documentation says it propagates NaNs and even goes to the trouble of saying exactly how they are propagated, which makes it seem like it shouldn't give a warning.

### Reproducing code example:
```python
In [1]: import numpy as np

In [2]: x = np.array([1, 2, np.nan], dtype=float)

In [3]: np.maximum(x, x)
/home/tudor/anaconda3/bin/ipython:1: RuntimeWarning: invalid value encountered in maximum
  #!/home/tudor/anaconda3/bin/python
Out[3]: array([ 1.,  2., nan])

```

### Numpy/Python version information:

```python
In [6]: import sys, numpy; print(numpy.__version__, sys.version)
1.15.1 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 17:14:51)
[GCC 7.2.0]
```

### PR DESCRIPTION
**Pull request by mattip**
Fixes #12038.

Starting with the sse code in simd.inc.src in PR #3419, then completed in PRs #9020, #11043, #11595, we adopted behaviour that warned when encountering a NAN on `np.maximum`, `np.minimum`, as well as ensuring we return a NAN value. This PR reverts emitting a warning, while preserving the tests to show we always propogate the NAN value to the output.

### CODE REVIEW

File: numpy/core/src/umath/loops.c.src [hunk 1]
```diff
@@ -2195,14 +2190,11 @@ HALF_@kind@(char **args, npy_intp *dimensions, npy_intp *steps, void *NPY_UNUSED
...
+        const npy_half in1 = *(npy_half *)ip1;
         const npy_half in2 = *(npy_half *)ip2;
-        in1 = (@OP@(in1, in2) || npy_half_isnan(in1)) ? in1 : in2;
-        if (npy_half_isnan(in1)) {
-            npy_set_floatstatus_invalid();
-        } 
-        *((npy_half *)op1) = in1;
+        *((npy_half *)op1) = (@OP@(in1, in2) || npy_half_isnan(in1)) ? in1 : in2;
     }
+    /* npy_half_isnan will never set floatstatus_invalid, so do not clear */
```
Comment (shoyer) [inline numpy/core/src/umath/loops.c.src]: when *do* we set floatstatus_invalid? is that set at the C level?

**Review by shoyer — APPROVED** [review]

File: numpy/core/src/umath/loops.c.src (hunk 1 above)
Comment (mattip) [reply numpy/core/src/umath/loops.c.src]: Yes, the non-SSE code sets it in `a > b` comparisons. which is why I need to clear it in the float-type loops at line 1849, and the complex-type loops at line 2763,

Comment (eric-wieser) [reply numpy/core/src/umath/loops.c.src]: Well, set at the FPU level, not at the C level.

Can't we just reorder the comparisons to do the nan checks first, rather than messing with the FPU flags?

Comment (mattip) [reply numpy/core/src/umath/loops.c.src]: trying, let's see what CI finds

Comment (mattip) [reply numpy/core/src/umath/loops.c.src]: It turns out simd code also sets it, in a way that it is impossible to avoid the clear after the loop finishes.

Comment (mattip) [reply numpy/core/src/umath/loops.c.src]: Rearranging the order still sets the flag since only one value is checked. It seems cheaper to me to clear the flag than to check both values. In changeset 46452b360 I added back the call to clear the flags, now tests are passing.

**Review by shoyer — APPROVED** [review]

File: numpy/core/src/umath/loops.c.src (hunk 1 above)
Comment (charris) [reply numpy/core/src/umath/loops.c.src]: I don't think instruction ordering is safe with modern compilers, at least without some work to make the order stick.

**Comment by charris** [comment]
Thanks Matti.
