### PR TITLE
BUG: correct irfft with n=1 on larger input

### LINKED ISSUE #25661: BUG: np.fft.hfft on main segfaults when n=1
### Describe the issue:

With the current nightly release, `np.fft.hfft` segfaults when `n=1`

### Reproduce the code example:

```python
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '2.0.0.dev0+git20240120.6bd3abf'

In [3]: x = np.arange(10)

In [4]: np.fft.hfft(x, n=1)
Segmentation fault: 11
```

### Error message:

```shell
Segmentation fault: 11
```

### Python and NumPy Versions:

```python
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
2.0.0.dev0+git20240120.6bd3abf
3.9.6 (default, May  7 2023, 23:32:44) 
[Clang 14.0.3 (clang-1403.0.22.14.1)]
```

### Runtime Environment:

```python
>>> import numpy; print(numpy.show_runtime())
[{'numpy_version': '2.0.0.dev0+git20240120.6bd3abf',
  'python': '3.9.6 (default, May  7 2023, 23:32:44) \n'
            '[Clang 14.0.3 (clang-1403.0.22.14.1)]',
  'uname': uname_result(system='Darwin', node='jmdg-macbookpro.roam.internal', release='23.2.0', version='Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP'],
                      'not_found': ['ASIMDFHM']}}]
```

### Context for the issue:

I found this through nightly tests of JAX against upstream NumPy; this failure began to appear in the last few days, so this is likely due to a recent change to `fft`.

### LINKED ISSUE #25679: BUG: np.fft.hfft results differ from previous release when n > len(arr)
### Describe the issue:

I'm not sure whether this is related to #25661, but this is an incorrect output rather than a segfault, so I thought I'd file a separate issue.

### Reproduce the code example:

```python
import numpy as np
print(f"{np.__version__=}")

x = np.arange(5) + 1j * np.ones(5)
print(np.fft.hfft(x, n=10))
```

### Error message:

Output with numpy 1.23.5
```
np.__version__='1.23.5'
[ 20.           0.68323112  -5.           4.92522101  -5.
   4.          -5.           2.0190509   -5.         -11.62750303]
```
Output with recent nightly build:
```
np.__version__='2.0.0.dev0+git20240123.877ca75'
[ 20.          -0.49233939  -3.09788697   3.02310798  -3.8244295
   4.          -6.1755705    3.92116393  -6.90211303 -10.45193252]
```
I would expect these outputs to be consistent across numpy versions.

### Python and NumPy Versions:

```python
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
2.0.0.dev0+git20240120.6bd3abf
3.9.6 (default, May  7 2023, 23:32:44) 
[Clang 14.0.3 (clang-1403.0.22.14.1)]
```

### Runtime Environment:

```python
>>> import numpy; print(numpy.show_runtime())
[{'numpy_version': '2.0.0.dev0+git20240120.6bd3abf',
  'python': '3.9.6 (default, May  7 2023, 23:32:44) \n'
            '[Clang 14.0.3 (clang-1403.0.22.14.1)]',
  'uname': uname_result(system='Darwin', node='jmdg-macbookpro.roam.internal', release='23.2.0', version='Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP'],
                      'not_found': ['ASIMDFHM']}}]
```

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by mhvk**
Fixes #25661
Fixes #25679

### CODE REVIEW

**Comment by asmeurer** [comment]
I can confirm this fixes the segfault.

**Comment by mhvk** [comment]
@seberg - would you be able to review the correction to #25536. Note that I also decided to include the missing release note that you asked for in https://github.com/numpy/numpy/pull/25536#issuecomment-1900754887

**Comment by mhvk** [comment]
p.s. I skipped ci on the release note addition, but you can still see that the tests passed for the actual code commit.

File: numpy/fft/_pocketfft_umath.c [hunk 1]
```diff
@@ -235,15 +240,17 @@ irfft_loop(char **args, npy_intp const *dimensions, npy_intp const *steps, void
...
-            double *last = (double *)(ip + (ncopied + 1) * step_in);
-            op_double[ncopied * 2 + 1] = last[0];
-            if (npts % 2 == 1) {  /* For odd n, we still imag real of the last point */
-                op_double[ncopied * 2 + 2] = last[1];
+            npy_intp i_last = (npts / 2  < nin - 1 ? npts / 2 : nin - 1);
+            double *last = (double *)(ip + i_last * step_in);
+            if (i_last > 0) {
+                op_double[i_last * 2 - 1] = last[0];  /* real of the last point */
+            }
+            if (npts % 2 == 1) {  /* For odd n, we still imag of the last point */
```
Comment (seberg) [inline numpy/fft/_pocketfft_umath.c:252]: Comment is mangled slightly, but OK.

**Review by seberg — APPROVED** [review]
This looks right to me, but honestly I find few things more confusing than these FFT lengths (considering how simple it is in some sense).
@ngoldbaum maybe you (or someone else) also can have a quick look?

File: numpy/fft/_pocketfft_umath.c (hunk 1 above)
Comment (mhvk) [reply numpy/fft/_pocketfft_umath.c:252]: I'll try to get it. And might as well add a comment about what FFTPACK format actually is, since it helps to understand what is done...

Comment (charris) [reply numpy/fft/_pocketfft_umath.c:252]: I think of it in terms of the real transform taking advantage of the Hermitian symmetry of the spectrum to only include the lower half. The question is then how to reconstruct the full spectrum, which depends on whether the center of symmetry is at the highest frequency, or half a sample to the right. This same sort of question involving reflection symmetry turns up in many places.

**Comment by mhvk** [comment]
Yikes, that took me long to realize I was just making things *far* too complicated. But now it is finally OK.

File: numpy/fft/_pocketfft_umath.c [hunk 2]
```diff
@@ -233,17 +238,24 @@ irfft_loop(char **args, npy_intp const *dimensions, npy_intp const *steps, void
...
         char *op_or_buff = buff == NULL ? op : buff;
         double *op_double = (double *)op_or_buff;
-        /* Copy complex input to buffer in FFTpack order */
-        op_double[0] = ((double *)ip)[0];
-        if (nin > 1) {
-            copy_data(ip + step_in, step_in, nin - 2,
-                      (char *)&op_double[1], sizeof(npy_cdouble), npts / 2 - 1,
+        /*
+         * Copy complex input to buffer in FFTpack order:
+         * R0,R1,I1,...Rn-1,In-1,Rn[,In] (last for npts odd)
```
Comment (ngoldbaum) [inline numpy/fft/_pocketfft_umath.c:243]: I got tripped up reading this that there's no `I0`, maybe a comment explicitly saying that the first entry is defined to be real?

Comment (charris) [reply numpy/fft/_pocketfft_umath.c:243]: The data is often packed a bit further in the even case, `R0, RN, R1, I1 ...` .  Don't know what fftpack did, but the form NumPy uses differed from the form SciPy returned back in the day. Having all complex numbers in the proper order and alignment is much less confusing.

Comment (mhvk) [reply numpy/fft/_pocketfft_umath.c:243]: Yes, the order @charris mentions is that used in Numerical Recipes, which I agree is nicer. But that's not what pocketfft and fftpack do...

Anyway, yes, happy to add a comment!  Since this code is for an irfft, by the assumption that the input values to the forward fft were real, the zero frequency element, which is just the sum of all the input elements, must be real too. For even number of points, by symmetry, the Nyquist frequency is also real (and of course just by counting the number of degrees of freedom one reaches the same conclusion).

**Comment by ngoldbaum** [comment]
It looks like you checked in an old submodule state, that's causing the CI failure.

**Comment by ngoldbaum** [comment]
LGTM now, feel free to self-merge once the CI is green!

**Comment by mhvk** [comment]
OK, thanks! Indeed, somehow the submodules got messed up. Will merge once CI passes!
