### PR TITLE
BUG: Fix that reduce-likes honor out always (and live in the future)

### LINKED ISSUE #20739: BUG: Cache failure for reducelikes with output casting
The test:
```
numpy/core/tests/test_ufunc.py::TestUfunc::test_reducelike_out_promotes
```
currently fails when running only `numpy/core/tests/test_ufunc.py` and not the full test suite.  Presumably, I have a caching logic error somewhere in the ufunc dispatching.

### PR DESCRIPTION
**Pull request by seberg**
Reducelikes should have lived in the future where the `out` dtype
is correctly honoured always and used as one of the *inputs*.
However, when legacy fallback occurs, this leads to problems because
the legacy code path has 0-D fallbacks.

There are two probable solutions to this:
* Live with weird value-based stuff here even though it was never
  actually better especially for reducelikes.
  (enforce value-based promotion)
* Avoid value based promotion completely.

This does the second one, using a terrible hack by just mutating
the dimension of `out` to tell the resolvers that value-based logic
cannot be used.

Is that hack safe?  Yes, so long nobody has super-crazy custom type
resolvers (the only one I know is PyGEOS and pyerfa and they are fine).
It also relies on the GIL of course, but...

The future? We need to ditch this value-based stuff, do annoying
acrobatics with dynamically created DType classes, or something similar
(so ditching seems best, it is topping my TODO list currently).

Testing this is tricky, running the test:
```
python runtests.py -t numpy/core/tests/test_ufunc.py::TestUfunc::test_reducelike_out_promotes
```
triggers it, but because reducelikes do not enforce value-based promotion
the failure can be "hidden" (which is why the test succeeds in a full test
run).

Closes gh-20739

---

@mhvk could you take a moment and see if this makes enough sense to you?

### CODE REVIEW

**Comment by charris** [comment]
Does this need a backport? The issue is marked for 1.22.1

**Comment by seberg** [comment]
Yes, it needs a backport.  Optimistically, we can all pull together in one direction on removing value-based promotion and pull a plug on all of this by the next release.

File: numpy/core/src/umath/ufunc_object.c [hunk 1]
```diff
@@ -2719,6 +2719,20 @@ reducelike_promote_and_resolve(PyUFuncObject *ufunc,
      * cannot quite handle the correct ops (e.g. a NULL first item if `out`
      * is NULL) so we pass `arr` instead in that case.
      */
+    /*
```
Comment (mhvk) [inline numpy/core/src/umath/ufunc_object.c:2722]: I'd keep the comment on `ops` above together with the definition, i.e., below this stanza.  Alternatively, since this is only executed when `out` is defined, and since only links to `out` are used, maybe put this part inside the `if (out != NULL)` below?

**Review by mhvk — COMMENTED** [review]
It is a pretty evil hack, but also really nicely localized, so I think it is OK.

I guess to make it less hacky, one could take a view as a 1-dim, 1-element array (in which case it should not be moved, obviously). But it seems extra work for little benefit - in a way, it is *good* that this is clearly a hack,

File: numpy/core/src/umath/ufunc_object.c (hunk 1 above)
Comment (seberg) [reply numpy/core/src/umath/ufunc_object.c:2724]: Thanks, moved the `ops` initialization in between these comments again.  Moving around more may help, but didn't really see it being much better.

**Review by mhvk — APPROVED** [review]
Looks good to me.

**Comment by charris** [comment]
Well, let's give this a shot., Thanks Sebastian.
