### PR TITLE
BUG: Memory Leak in _GenericBinaryOutFunction

### LINKED ISSUE #6672: memory leak in np.clip()
I found a usage pattern under which np.clip() leaks memory.
You can reproduce it with the following code:

    In [1]: import numpy as np
    
    In [2]: a = np.arange(10).reshape(5,2)
    
    In [3]: a
    Out[3]:
    array([[0, 1],
           [2, 3],
           [4, 5],
           [6, 7],
           [8, 9]])
    
    In [4]: b = np.array([[3,5],[0,6]])
    
    In [5]: np.clip(a, b[:,0], b[:,1])
    Out[5]:
    array([[3, 1],
           [3, 3],
           [4, 5],
           [5, 6],
           [5, 6]])
    
    In [6]: for i in xrange(10000000): np.clip(a, b[:,0], b[:,1], a)

This problem was already present in numpy 1.9.0 (installed from `numpy-1.9.0-win32-superpack-python2.7.exe`), and I was now able to reproduce it in numpy 1.10.1 (installed from Christoph Gohlke's [`numpy-1.10.1+mkl-cp27-none-win32.whl`](http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy) Windows binary), as well as in Linux (numpy 1.10.1, local compile through pip).

### PR DESCRIPTION
**Pull request by simongibbons**
_GenericBinaryOutFunction was leaking constructing a string
each time it was called which wasn't deallocated on some
versions of python (due to string interning rules). This
fixes this by storing the **kwargs that are passed into
the op statically so that they are only constructed
the first time that _GenericBinaryOutFunction is called.

Credit to @seberg for finding the location of the
bug and providing an initial version of the fix.

Fixes #6672

### CODE REVIEW

**Comment by simongibbons** [comment]
Oh given this bug is a memory leak (and a small one at that) I'm not entirely sure how to write a regression test for this. Any ideas?

File: numpy/core/src/multiarray/calculation.c [hunk 1]
```diff
@@ -830,28 +830,38 @@ _GenericBinaryOutFunction(PyArrayObject *m1, PyObject *m2, PyArrayObject *out,
...
 
-        args = Py_BuildValue("OOO", m1, m2, out);
-        if (args == NULL) {
-            return NULL;
-        }
-        kw = PyDict_New();
         if (kw == NULL) {
-            Py_DECREF(args);
-            return NULL;
+            kw = PyDict_New();
```
Comment (jaimefrio) [inline numpy/core/src/multiarray/calculation.c]: Why not build the dictionary with `Py_BuildValue` and spare ourselves all the trouble? 

```C
kw = Py_BuildValue("{s:s}", "casting", "unsafe");
```

**Comment by simongibbons** [comment]
Yup you're right - that really does simplify things. I'm not sure why I thought `Py_BuildValue` could only create tuples.

**Comment by jaimefrio** [comment]
It is not very explicit in the prose of the documentation, which mostly discusses single objects vs tuples, but it lets you build single objects, tuples `()`, lists `[]` or dicts `{}`.

**Comment by simongibbons** [comment]
Right, looks like the build is passing with that change. Like I said a test for this is tricky - if you're ok without putting one in for this then I think this may be ready for merging. It just needs me to squash the commits (and clean up the fairly horrendous english in the commit message - really should have proof read that!)

**Comment by jaimefrio** [comment]
I would like to know if using `Py_BuildValue` without a making the dict `static` we still have the leak: I don't fully understand what the "different string interning rules" that @seberg figured were the cause of the leak mean exactly, which makes me a little uneasy.

But it probably makes sense making that dict `static` regardless, so we don't have to recreate it every time. So go ahead and leave it squashed an ready to merge, and if no one comes up with a good explanation or testing idea we'll put it in as is.

**Comment by seberg** [comment]
The string interning is not really the cause of the leak, it is just the cause of the reference leak being visible as a memory leak in some python versions and not in others.

**Comment by charris** [comment]
@seberg Is more needed here?
