### PR TITLE
BUG: Fixed file handle leak in array_tofile.

### LINKED ISSUE #17589: array_tofile does not close file when PyArray_ToFile fails
When an open file is passed to `numpy.save` and the save fails, then file is then undeletable because numpy still has the file open.

### Reproducing code example:
Firstly create a small partition F that has < 200Mb of space 
```python
import numpy as np
import os

a = np.zeros((100000000, 3), dtype=float)
filename = 'F:\\array.npy'
try:
    with open(filename, 'wb') as f:
        np.save(f, a)
except Exception as e:
    if os.path.exists(filename):
        os.remove(filename)  # This fails

```

### Error message:

Traceback (most recent call last):
  File "S:/scripts/numpy_bug.py", line 9, in <module>
    np.save(f, a)
  File "<__array_function__ internals>", line 6, in save
  File "S:\Leapfrog\components\py3_win64\lib\site-packages\numpy\lib\npyio.py", line 553, in save
    pickle_kwargs=pickle_kwargs)
  File "S:\Leapfrog\components\py3_win64\lib\site-packages\numpy\lib\format.py", line 687, in write_array
    array.tofile(fp)
OSError: 300000000 requested and 0 written   # We expect this
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "S:/scripts/numpy_bug.py", line 12, in <module>
    os.remove(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'F:\\array.npy'

### NumPy/Python version information:

1.18.1 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]
1.19.2 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]

### PR DESCRIPTION
**Pull request by simon-graham**
Closes #17589

If the ```PyArray_ToFile``` call inside ```array_tofile``` fails for any reason, we leak a dup-ed file handle. This causes problems especially on Windows OS, where any subsequent attempt to delete the file will fail because NumPy is still holding an open handle.

This update ensures that we always close the handle.

The added test case forces ```PyArray_ToFile``` to fail, which triggers the original problem.

### CODE REVIEW

File: numpy/core/src/multiarray/methods.c [hunk 1]
```diff
@@ -619,10 +619,9 @@ array_tofile(PyArrayObject *self, PyObject *args, PyObject *kwds)
...
-    if (PyArray_ToFile(self, fd, sep, format) < 0) {
-        goto fail;
-    }
-    if (npy_PyFile_DupClose2(file, fd, orig_pos) < 0) {
+    res1 = PyArray_ToFile(self, fd, sep, format);
+    res2 = npy_PyFile_DupClose2(file, fd, orig_pos);
+    if (res1 < 0 || res2 < 0) {
         goto fail;
     }
     if (own && npy_PyFile_CloseFile(file) < 0) {
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/methods.c:627]: if `res2 < 0`, you still should close this file

File: numpy/core/src/multiarray/methods.c [hunk 2]
```diff
@@ -619,10 +619,9 @@ array_tofile(PyArrayObject *self, PyObject *args, PyObject *kwds)
...
     }
-    if (PyArray_ToFile(self, fd, sep, format) < 0) {
-        goto fail;
-    }
-    if (npy_PyFile_DupClose2(file, fd, orig_pos) < 0) {
+    res1 = PyArray_ToFile(self, fd, sep, format);
+    res2 = npy_PyFile_DupClose2(file, fd, orig_pos);
+    if (res1 < 0 || res2 < 0) {
         goto fail;
     }
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/methods.c:626]: I suspect this might be unsafe - if the first throws an exception, it's not safe to call back into python code before catching it - and `npy_PyFile_DupClose2` looks like it can call back in. You might need to use
```suggestion
    int res_write = PyArray_ToFile(self, fd, sep, format);
    {
        PyObject *type, *value, *traceback;
        PyErr_Fetch(&type, &value, &traceback);
        int res_close = npy_PyFile_DupClose2(file, fd, orig_pos);
        npy_PyErr_ChainExceptions(type, value, traceback);
        if (res_write < 0 || res_close < 0) {
            return NULL;
        }
    }
```
which also means you'll get chained exceptions

File: numpy/core/src/multiarray/methods.c [hunk 3]
```diff
@@ -585,8 +585,9 @@ array_tostring(PyArrayObject *self, PyObject *args, PyObject *kwds)
 static PyObject *
 array_tofile(PyArrayObject *self, PyObject *args, PyObject *kwds)
 {
-    int own;
+    int own, res_write, res_close;
     PyObject *file;
+    PyObject *err_type = NULL, *err_value = NULL, *err_traceback = NULL;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/methods.c:590]: We use C99, so I'd prefer it if you put these declarations at their point of use:

```suggestion
    int own;
    PyObject *file;
```

File: numpy/core/src/multiarray/methods.c [hunk 4]
```diff
@@ -617,23 +618,29 @@ array_tofile(PyArrayObject *self, PyObject *args, PyObject *kwds)
...
+        return NULL;
     }
-    if (npy_PyFile_DupClose2(file, fd, orig_pos) < 0) {
-        goto fail;
+    res_write = PyArray_ToFile(self, fd, sep, format);
+    PyErr_Fetch(&err_type, &err_value, &err_traceback);
+
+    res_close = npy_PyFile_DupClose2(file, fd, orig_pos);
+    if (res_close < 0) {
+        npy_PyErr_ChainExceptions(err_type, err_value, err_traceback);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/methods.c:629]:
```suggestion
    int res_write = PyArray_ToFile(self, fd, sep, format);
    PyObject *err_type, *err_value, *err_traceback;
    PyErr_Fetch(&err_type, &err_value, &err_traceback);

    int res_close = npy_PyFile_DupClose2(file, fd, orig_pos);
    if (res_close < 0) {
        npy_PyErr_ChainExceptions(err_type, err_value, err_traceback);
```
There's also no need to initialize the `err_*` variables, `PyErr_Fetch` is guaranteed to write to them.

**Comment by eric-wieser** [comment]
Thanks for the patch. I think the error handling is still generally wrong in this function. I think we need to aim for the C equivalent of:

```python
file = ...
try:
    fd = npy_PyFile_Dup2(file)
    try:
        PyArray_ToFile(fd)
    finally:
        npy_PyFile_DupClose2(fd)
finally:
    if own:
        npy_PyFile_CloseFile(file)
```
This would almost certainly be much easier to get right if the contents of the outer `try` were extracted to a helper function. A `finally` clause is a `PyErr_Fetch` followed by an _unconditional_ call to `npy_PyErr_ChainExceptions`.

File: numpy/core/src/multiarray/methods.c (hunk 1 above)
Comment (simon-graham) [reply numpy/core/src/multiarray/methods.c:632]: Thanks @eric-wieser. I've updated it now so that it closes ```file``` even if ```npy_PyFile_DupClose2``` fails.

File: numpy/core/src/multiarray/methods.c [hunk 5]
```diff
@@ -617,23 +617,31 @@ array_tofile(PyArrayObject *self, PyObject *args, PyObject *kwds)
...
+    int res_write = PyArray_ToFile(self, fd, sep, format);
+    PyObject *err_type, *err_value, *err_traceback;
+    PyErr_Fetch(&err_type, &err_value, &err_traceback);
+
+    int res_close = npy_PyFile_DupClose2(file, fd, orig_pos);
+    if (res_close < 0) {
+        npy_PyErr_ChainExceptions(err_type, err_value, err_traceback);
     }
+
     if (own && npy_PyFile_CloseFile(file) < 0) {
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/methods.c:633]: I think `npy_PyFile_CloseFile` is also unsafe to call here - you need to fetch the exception _again_, in case `npy_PyFile_DupClose2` created one. See my comment in https://github.com/numpy/numpy/pull/17598#issuecomment-713902244, this becomes much easier to follow if you extract a helper function.

Comment (simon-graham) [reply numpy/core/src/multiarray/methods.c]: Thanks @eric-wieser, appreciate your patience. I didn't quite manage to refactor it into a helper function, but have updated it so that is now hopefully exception safe, and not too horrific to read.

File: numpy/core/src/multiarray/methods.c [hunk 6]
```diff
@@ -616,24 +616,36 @@ array_tofile(PyArrayObject *self, PyObject *args, PyObject *kwds)
...
+            failed = 1;
+        }
+        PyErr_Fetch(&err_type, &err_value, &err_traceback);
+        if (npy_PyFile_DupClose2(file, fd, orig_pos) < 0) {
+            failed = 1;
+        }
+        npy_PyErr_ChainExceptions(err_type, err_value, err_traceback);
+    } else {
+        failed = 1;
     }
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/methods.c:633]: Would you mind extracting these to a helper function? Perhaps
```C
/* Like PyArray_ToFile but takes the file as a python object */
static int
PyArray_ToFileObject(PyArrayObject *self, PyObject *file, char *sep, char *sep)
{
    npy_off_t orig_pos = 0;
    FILE *fd = npy_PyFile_Dup2(file, "wb", &orig_pos);
    if (fd == NULL) {
        return -1;
    }
    int write_ret = PyArray_ToFile(self, fd, sep, format);
    PyObject *err_type, *err_value, *err_traceback;
    PyErr_Fetch(&err_type, &err_value, &err_traceback);
    int close_ret = npy_PyFile_DupClose2(file, fd, orig_pos);
    npy_PyErr_ChainExceptions(err_type, err_value, err_traceback);
    if (write_ret || close_ret) {
        return -1;
    }
    return 0;
}
```

File: numpy/core/tests/test_multiarray.py [hunk 7]
```diff
@@ -5048,6 +5048,14 @@ def test_tofile_format(self):
...
         assert_equal(s, '1.51,2.00,3.51,4.00')
 
+    def test_tofile_cleanup(self):
+        x = np.zeros((10), dtype=object)
+        with open(self.filename, 'wb') as f:
+            assert_raises(IOError, lambda: x.tofile(f, sep=''))
+
+        # Dup-ed file handle should be closed or remove will fail.
+        os.remove(self.filename)
+
```
Comment (eric-wieser) [inline numpy/core/tests/test_multiarray.py:5058]: Can you repeat this test with `x.tofile(self.filename)`, to check it closes both the python handle and the fd?

Comment (simon-graham) [reply numpy/core/tests/test_multiarray.py]: This second check is now added.

**Comment by simon-graham** [comment]
Hi @eric-wieser, is there anything else to address for this PR? I believe I've implemented all of your review feedback. Thanks.

**Review by eric-wieser — APPROVED** [review]
Sorry for forgetting about this - looks good, thanks!

**Comment by mattip** [comment]
Thanks @simon-graham
