### PR TITLE
BUG: fixed dtype alignment for array of structs in case of converting from tuple descr

### LINKED ISSUE #663: Alignment doesn't work for array of structs (Trac #2211)
_Original ticket http://projects.scipy.org/numpy/ticket/2211 on 2012-09-05 by trac user Ihor.Melnyk, assigned to unknown._

array of subtype alignment

```
t = np.dtype([('a', '|i1'), ('b', [('f0', '<i2'), ('f1', '<f4')], 2)], align=True)
```

actual dtype

```
[('a', '|i1'), ('b', [('f0', '<i2'), ('f1', '<f4')], (2,))]
```

expected dtype

```
[('a', '|i1'), (_, '|V3'), ('b', [('f0', '<i2'), (_, '|V2'), ('f1', '<f4')], 2)]
```

### PR DESCRIPTION
**Pull request by ihormelnyk**
Descr of array of subtype with alignment
t = np.dtype([('a', '|i1'), ('b', [('f0', '<i2'), ('f1', '<f4')], 2)], align=True)

actual dtype:
[('a', '|i1'), ('b', [('f0', '<i2'), ('f1', '<f4')], (2,))]

expected dtype:
[('a', '|i1'), (_, '|V3'), ('b', [('f0', '<i2'), (_, '|V2'), ('f1', '<f4')], 2)]

Fixes #663.

### CODE REVIEW

File: numpy/core/src/multiarray/descriptor.c [hunk 1]
```diff
@@ -252,9 +252,16 @@ _convert_from_tuple(PyObject *obj)
     if (PyTuple_GET_SIZE(obj) != 2) {
         return NULL;
     }
-    if (!PyArray_DescrConverter(PyTuple_GET_ITEM(obj,0), &type)) {
-        return NULL;
-    }
+	if (align) {
```
Comment (ahaldane) [inline numpy/core/src/multiarray/descriptor.c]: all the tab characters here should be four spaces. (no tabs allowed in numpy code!)

**Comment by ahaldane** [comment]
Looks good, thanks for the PR!

I have two requests, and after that I think it will be good to merge:

1. In the commit message body, put the exact words "Fixes #663". This helps us keep track, and also auto-closes the issue on github.

2. Add a unit test. This should go in the file `numpy/core/tests/test_dtype.py`, and you can choose an appropriate place inside. For instance, you could add a new function somewhere like the other ones there, for instance right after `test_aligned_size`. Or, perhaps you should just add some code at the end of `test_aligned_size`. Either way, I think you just need to add a few lines like in your comment above, using `assert_equal` to check you get the expected value.

**Comment by ahaldane** [comment]
Everything else looks good.

**Comment by ihormelnyk** [comment]
Fixed lines length.

**Comment by ahaldane** [comment]
Great, thanks a lot @ihormelnyk !

This was a pretty annoying bug, I'm glad it's fixed. Merging now...
