### PR TITLE
BUG: Check for exception in sort functions

### LINKED ISSUE #9404: BUG: np.array([0, datetime.now()], dtype=object).sort() can raise on cmp(), but exception ignored
the various functions in quicksort.c.src do not check ``PyErr_Occurred()`` before returning, when the tp_compare fails no exception is raised. The exception is thrown later by any random C-API call, but the error originated in the sort function
```
python -c "import numpy as np; from datetime import datetime as dt; \
                 a = np.array([1, 2, dt.now(), 0, 3], dtype=object); \
                 np.sort(a); print a"
numpy/core/fromnumeric.py:822: RuntimeWarning: tp_compare didn't return -1 or -2 for exception
  a.sort(axis=axis, kind=kind, order=order)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "numpy/core/numeric.py", line 1942, in array_str
    return array2string(a, max_line_width, precision, suppress_small, ' ', "")
  File "numpy/core/arrayprint.py", line 397, in wrapper
    return f(self, *args, **kwargs)
  File "numpy/core/arrayprint.py", line 529, in array2string
    separator, prefix, formatter=formatter)
  File "numpy/core/arrayprint.py", line 373, in _array2string
    _summaryEdgeItems, summary_insert)[:-1]
  File "numpy/core/arrayprint.py", line 565, in _formatArray
    for i in range(leading_items):
TypeError: can't compare datetime.datetime to int
```

FWIW, on PyPy we detect that a C-API function raised an exception but returns a valid value, which
is how I found the problem

### PR DESCRIPTION
**Pull request by mattip**
fixes #9404 by checking if exception occurred and returning appropriate value

Test added. Old behaviour was to emit a warning during the call to array_sort, and not
clear the exception, which would be raised at some other call to a C-API function.

### CODE REVIEW

File: numpy/core/src/npysort/quicksort.c.src [hunk 1]
```diff
@@ -518,6 +526,8 @@ stack_pop:
     }
 
     free(vp);
+    if (PyErr_Occurred())
```
Comment (jaimefrio) [inline numpy/core/src/npysort/quicksort.c.src]: I don't think that any of the previous `PyErr_Occurred() ` can ever be triggered. Certainly not for the numeric sorts, which could run with the GIL released as far as i can tell, extremely unlikely for the string sorts, which call `PyArray_ITEMSIZE` which is a struct access which is extremely unlikely to ever fail. Even more, since, `PyArray_Sort` releases the GIL when calling these functions if the dtype doesn't require it, that call to `PyErr_Occurred` without reacquiring the GIL is likely to crash the interpreter.

**Comment by jaimefrio** [comment]
Thanks for putting this together!

See my inline comment, I think it explains the segfaults happening in your tests.

You should add the same check to the other sorting methods, and test them as well.

**Comment by eric-wieser** [comment]
The fix is much simpler than this. There's an `#if defined(NPY_PY3K)` in `_new_sortlike` that should be running on python 2 as well.

**Comment by mattip** [comment]
@eric-wieser your fix works and passes the additional tests of other sorting methods.

Note this changes behaviour and will cause at least one test in pandas to be tweaked, they currently expect a warning which is no longer emitted

File: numpy/core/src/multiarray/item_selection.c [hunk 2]
```diff
@@ -885,12 +883,10 @@ _new_sortlike(PyArrayObject *op, int axis, PyArray_SortFunc *sort,
             npy_intp i;
             for (i = 0; i < nkth; ++i) {
                 ret = part(bufptr, N, kth[i], pivots, &npiv, op);
-#if defined(NPY_PY3K)
                 /* Object comparisons may raise an exception in Python 3 */
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/item_selection.c]: This comment is misleading. Comparisons can always raise an exception.

File: numpy/core/src/multiarray/item_selection.c [hunk 3]
```diff
@@ -869,12 +869,10 @@ _new_sortlike(PyArrayObject *op, int axis, PyArray_SortFunc *sort,
 
         if (part == NULL) {
             ret = sort(bufptr, N, op);
-#if defined(NPY_PY3K)
             /* Object comparisons may raise an exception in Python 3 */
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/item_selection.c]: Same as below

**Comment by charris** [comment]
I added a `backport candidate` label, even if its causes pandas to need to tweak a test. Seems pretty harmless.

**Comment by eric-wieser** [comment]
Interestingly, there's a `NPY_ECOMP` in `npy_sort.h`, which was presumably intended to signal errors during comparison. Unfortunately, [`descr->f->compare`](https://docs.scipy.org/doc/numpy/reference/c-api.types-and-structures.html#c.PyArray_ArrFuncs.compare) is not documented as having a way to signal errors, so this turns out not to be useful.

This patch looks good to me

**Comment by eric-wieser** [comment]
I've rebased this for easy backporting - if no one objects, I'll merge this into both 1.14 and 1.13.2 tomorrow

**Comment by mattip** [comment]
Maybe merge into 1.14 only since pandas has a test that requires tweaking for this change and the _np_version_under attribute only has minor (not revision) resolution

**Comment by eric-wieser** [comment]
Can you link to the test?

**Comment by mattip** [comment]
https://github.com/pandas-dev/pandas/blob/master/pandas/tests/test_algos.py#L125

**Comment by eric-wieser** [comment]
Am I right in thinking this patch fixes #3879?

**Comment by eric-wieser** [comment]
That test looks broken to me - why would you explicitly test for a bug in a downstream project?

Seems that that should just be suppressing the warnings, not asserting that it happens

**Comment by mattip** [comment]
I could argue that results, warnings and errors are all ouputs of 
a given function using given inputs, but I would prrefer the practical
 argument that we should not knowingly break a test in a downstream project via a
revision release, and so this should be on NumPy 1.14 at the earliest

**Comment by eric-wieser** [comment]
Let's merge this into 1.14, and decide about 1.13.2 later. @charris, are you still in favor of the backport, or has @mattip convinced you otherwise

**Comment by eric-wieser** [comment]
Actually, we should add a test for #3879 first

**Review by eric-wieser — CHANGES_REQUESTED** [review]
Ok, #3879 still fails, with:

```
...
SystemError                     Traceback (most recent call last)
SystemError: <class 'TypeError'> returned a result with an error set

During handling of the above exception, another exception occurred:

SystemError                     Traceback (most recent call last)
SystemError: <class 'TypeError'> returned a result with an error set

During handling of the above exception, another exception occurred:
```

**Comment by mattip** [comment]
added a test and a fix for #3879: rather than try to abort the sort simply return from OBJECT_compare if an error occurred to avoid raising again. When the sort finishes the original exception will be raised

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 4]
```diff
@@ -2748,6 +2748,15 @@ OBJECT_compare(PyObject **ip1, PyObject **ip2, PyArrayObject *NPY_UNUSED(ap))
...
      * here.
      */
+
+    int ret;
+    /*
+     * work around gh-3879, we cannot abort an in-progress quicksort
+     * so at least do not raise again
+     */
+    if (PyErr_Occurred()) {
+        return 1;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/arraytypes.c.src]: Rationale for choosing this over `0`? I'd worry a sort could hang if 1 is returned, since the comparisons become inconsistent (`cmp(a, b) == cmp(b, a) == 1`)

**Comment by mattip** [comment]
changed workaround to return 0 if error was detected

**Review by eric-wieser — APPROVED** [review]

**Comment by eric-wieser** [comment]
Interestingly, compare seems to only ever be used here as `cmp(...) < 0`, so I guess that didn't matter.

It'd be nice if we could use the `NPY_ECOMP` macro, but realistically that's a lot more work, and might be an API incompatibility (I don't know how public that is).

So this looks like a pretty reasonable workaround.

The only danger is that user-implemented `compare` functions (still) need to contain the same logic.

**Comment by eric-wieser** [comment]
Let's put this in - I've opened a follow-up issue (#9443) about documenting how this fix is needed in user code too

**Comment by eric-wieser** [comment]
Thanks @mattip!
