### PR TITLE
BUG: void .item() doesn't hold reference to original array

### LINKED ISSUE #8129: Constructing object array from void array leads to use-after-free
If you do this:

```
np.array(np.zeros(3, 'i4'), object)
```

You get an array of 3 objects, where each is a (reference to an) integer.  However, if you do this:

```
np.array(np.zeros(3, 'V4'), object)
```

You get an array of 3 `read-write buffer ptr` objects, for example:

```
array([<read-write buffer ptr 0x19965d0, size 4 at 0x7f556a3568f0>,
       <read-write buffer ptr 0x19965d4, size 4 at 0x7f556a356930>,
       <read-write buffer ptr 0x19965d8, size 4 at 0x7f556a3568b0>], dtype=object)
```

And while these buffers do allow you to access the void data, they do not hold any reference to it.  This leads to use-after-free memory access violations, like this:

```
va = np.zeros(300000, 'V4')
oa = np.array(va, object)
del va
print(oa[0][0], oa[-1][-1])
```

That often causes a segmentation fault on my machine (Linux).

This is also the root cause of a crash in Pandas: https://github.com/pydata/pandas/issues/14349

I'm using NumPy 1.10.2 and 1.11.1 on Python 3.5.

### PR DESCRIPTION
**Pull request by ahaldane**
Fixes #8129 by making `void.item()` return a memoryview which holds a reference to the original array.

Note this has very poor performance (eg in the example in #8129). The problem is that the only way I can see to create a `memoryview` that holds a reference to the base object is with `PyMemoryView_FromObject` (and not `PyMemoryView_FromMemory` or `PyMemoryView_FromBuffer`). So I am forced to create a size-1 ndarray for every element of the array to pass to `PyMemoryView_FromObject` and convert it to a memoryview, which is slow. 

Is there a better way? If not, hopefully this is a rare enough scenario that we don't need to care too much about performance.

Here is a list of relevant docs, for reference:
- [py3 buffer docs](https://docs.python.org/3/c-api/buffer.html), 
- [py3 memoryview docs](https://docs.python.org/3/c-api/memoryview.html), and [code](https://github.com/python/cpython/blob/c30098c8c6014f3340a369a31df9c74bdbacc269/Objects/memoryobject.c)
- [py2 buffer+memoryview docs](https://docs.python.org/2/c-api/buffer.html)
- [Python issue](https://bugs.python.org/issue15821) discussing how Python's current memoryview C api is unsatisfactory.

### CODE REVIEW

**Comment by charris** [comment]
Hmm, looks like you have researched the problem pretty deeply. Maybe @pv has some ideas.

**Comment by charris** [comment]
Wow, that issue died as a python issue long ago. Maybe give them a ping.

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 1]
```diff
@@ -709,47 +707,32 @@ VOID_getitem(void *input, void *vap)
...
-        descr = PyArray_DescrNewFromType(NPY_BYTE);
-        u = (PyArrayObject *)PyArray_NewFromDescr(&PyArray_Type,
-                             descr, 1, dims, strides, ip,
+        PyObject *ret, *u;
+
+        /* first create a size-1 view of this element */
+        npy_intp dims[1];
+        dims[0] = 1;
+        Py_INCREF(descr);
+        u = PyArray_NewFromDescr(&PyArray_Type, descr, 1, dims, NULL, ip,
```
Comment (charris) [inline numpy/core/src/multiarray/arraytypes.c.src]: Could make this PEP8 compliant. Starting a new line after the opening `(` might be the easiest way.

File: numpy/core/tests/test_regression.py [hunk 2]
```diff
@@ -2225,6 +2225,13 @@ def test_reshape_size_overflow(self):
             new_shape = (2, 7, 7, 43826197)
         assert_raises(ValueError, a.reshape, new_shape)
 
+    def test_void_item_memview(self):
+        # gh-8129
+        va = np.zeros(300000, 'V4')
+        x = va[:1].item()
+        del va
+        x.tobytes()  # segfault?
```
Comment (charris) [inline numpy/core/tests/test_regression.py]: Always segfaults, or just now and then? Might move the trailing comment onto its own line above.

**Comment by charris** [comment]
LGTM modulo some nits. I wonder a bit if returning memoryviews could cause backward compatibility problems, although it isn't clear that things were working before. I leaning to  put this off to the next release so that things have a chance to settle. Maybe we should warn in the release notes?

**Comment by ahaldane** [comment]
Yeah, I want to think a little more anyway, and I also want to try running pandas/astropy/scipy unit tests with this change.

There might be a workaround to the performance problem through the fact that numpy usually considers unstructured void scalars to be "immutable", so often makes them copies instead of views. So maybe I can avoid the call to `PyArray_NewFromDescr` by making a cheap copy of the element of some sort. Eg, getting a void-scalar might be cheaper than getting a view.

**Comment by ahaldane** [comment]
Rebased.

Also, realized a simple solution to the problems above: Just return a memoryview of `ap`. I think this PR is ready now.

Note this PR will have a significant effect on the string representation of `V` arrays, since `V` items will now always show up as `<memoryview>`:

Old str behavior:
```python
>>> np.zeros(6, 'V4')
array([, , , , , ], 
      dtype='|V4')
```

New behavior:
```python
>>> np.zeros(6, 'V4')
array([<memory at 0x7fd9bd3a6808>, <memory at 0x7fd9bd3a6808>,
       <memory at 0x7fd9bd3a6808>, <memory at 0x7fd9bd3a6808>,
       <memory at 0x7fd9bd3a6808>, <memory at 0x7fd9bd3a6808>],
      dtype='|V4')
```

I suggest that the new behavior is more correct, although wordier. This way we don't risk cluttering the terminal with invalid characters, and we don't end up with mystery spaces like in the old representation.

**Comment by eric-wieser** [comment]
Does the following work fine under this patch?

```
dt = np.dtype([('i', int), ('v', 'V0')])
np.zeros(6, dt)
```

**Comment by ahaldane** [comment]
Your example is just printed differently:
```python
>>> dt = np.dtype([('i', int), ('v', 'V0')])
>>> np.zeros(6, dt)
array([(0, <memory at 0x7ffa3f09d240>), (0, <memory at 0x7ffa3f09d240>),
       (0, <memory at 0x7ffa3f09d240>), (0, <memory at 0x7ffa3f09d240>),
       (0, <memory at 0x7ffa3f09d240>), (0, <memory at 0x7ffa41accb70>)],
      dtype=[('i', '<i8'), ('v', 'V')])
```

(also, this example uses a structured type, but this patch mainly affects unstructured void types)

**Comment by eric-wieser** [comment]
My concern was handling of `V0`, but it seems it was without reason.

Sure looks like a bug in python, the way that `memoryview` is being shown - shouldn't that show the address of the memory it points to, not the address of the pyobject holding it?

**Comment by eric-wieser** [comment]
Also, I don't agree with your old behaviour - on python 3, I get:
```
>>> np.zeros(6, 'V4')
array([[0 0 0 0], [0 0 0 0], [0 0 0 0], [0 0 0 0], [0 0 0 0], [0 0 0 0]], 
      dtype='|V4')
```

Are you using 2.7?

**Comment by ahaldane** [comment]
It *is* showing the address being pointed to.

The problem is that during the process of printing the array, numpy makes a temporary copy of the memory and shows that instead.

More in detail, numpy goes through each element, and makes a void scalar from it, and unstructured void scalars (unlike structured voids) always make a copy (not a view) of the array element they correspond to. So the printed memory refer's to an unstructured void scalar's buffer.

We might fix that (in another PR?) by making unstructured void scalars point to the original array's memory (be views). That would also fix the problem that writing to an unstructured void scalar's memory currently doesn't affect the original array, unlike structured void scalars.

The place where this all happens is in [PyArray_Scalar](https://github.com/numpy/numpy/blob/58a9900e10a64d44de4c288ef2867ecd0d09a206/numpy/core/src/multiarray/scalarapi.c#L826).

**Comment by ahaldane** [comment]
I'm using Python 3.6.0 in the printout above.... curious yours is different.

**Comment by eric-wieser** [comment]
> It is showing the address being pointed to.

Can you prove that to me with:

```
arr = np.zeros(6, 'V4')
x = arr[0]
print(repr(x))
print(object.__repr__(x))
```

**Comment by ahaldane** [comment]
```python
>>> arr = np.zeros(6, 'V4')
...: x = arr[0]
...: print(repr(x))
...: print(object.__repr__(x))
...: 
<memory at 0x7f22d876b240>
<numpy.void object at 0x7f22d8790570>
```

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 3]
```diff
@@ -720,53 +718,15 @@ VOID_getitem(void *input, void *vap)
...
-    else {
-        u = (PyArrayObject *)PyBuffer_FromMemory(ip, itemsize);
-    }
-#endif
-
-    if (u == NULL) {
-        return NULL;
-    }
-    return (PyObject *)u;
+    return PyMemoryView_FromObject((PyObject*)ap);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/arraytypes.c.src]: Seems to me like this needs a `if (input != PyArray_DATA(ap)) {error();}`, just in case

**Comment by ahaldane** [comment]
I want to leave this for after #8981, in case we want to reconsider whether we want to return a memoryview or a bytes object.

**Comment by ahaldane** [comment]
Rebased, and heavily simplified.

I decided that memoryview is the wrong thing to return because it doesn't round-trip through `np.void(voidscalar.item())`, eg if `voidscalar = np.array(0, dtype='i8').view('V8')`. Instead I now return a bytes object.

So this PR can now be summarized as: Return a `bytes` object for `void.item()`, thus avoiding the reference count issues we had before when returning a buffer.

**Comment by eric-wieser** [comment]
> memoryview is the wrong thing to return because it doesn't round-trip

Note that it didn't roundtrip before either.

If I try the following on python 3, I get a hang:

```
a = np.array(b'test', dtype='V8')
am = memoryview(a)
np.void(am)
```

Orthogonal to this choice, I think making `np.void(memoryview)` work is desirable

> Return a bytes object for void.item()

Sounds good - that's consistent with use returning a `tuple` for `structured_void.item`, which is also immutable despite `void` being mutable.

File: numpy/core/tests/test_regression.py [hunk 4]
```diff
@@ -2234,6 +2234,13 @@ def test_scalar_copy(self):
             item2 = copy.copy(item)
             assert_equal(item, item2)
 
+    def test_void_item_memview(self):
+        # gh-8129
+        va = np.zeros(10, 'V4')
+        x = va[:1].item()
+        del va
+        assert_equal(x, b'\x00\x00\x00\x00')
```
Comment (eric-wieser) [inline numpy/core/tests/test_regression.py]: Might be nice to set `va[0][0] = 1` above or something, to make this a slightly more thorough test.

**Comment by ahaldane** [comment]
Update the test.

> Sounds good - that's consistent with use returning a tuple for structured_void.item, which is also immutable despite void being mutable.

Just to clarify, actually only structured-void scalars are mutable. Unstructured-void scalars are copies of the data (see `scalarapi.c:814`). I originally in this PR  I made unstructured-void scalars into views too, but got rid of that after I decided to get rid of the memoryview behavior.

**Comment by ahaldane** [comment]
Reverted the last changed test. I should have read my own comment: The structured scalars here are immutable, so we can't do `va[0][0] = 1` in the test.

**Comment by eric-wieser** [comment]
Just do `va[0] = '\x00\x01\x02\x03'` then?

**Comment by ahaldane** [comment]
Ah, fair enough, done.

File: doc/release/1.14.0-notes.rst [hunk 5]
```diff
@@ -416,6 +416,10 @@ The printing style of ``np.void`` arrays is now independently customizable
 using the ``formatter`` argument to ``np.set_printoptions``, using the
 ``'void'`` key, instead of the catch-all ``numpystr`` key as before.
 
+unstructured void array's ``.item`` method now returns a bytes object
+---------------------------------------------------------------------
+``.item`` now returns a ``bytes`` object instead of a buffer or byte array.
```
Comment (eric-wieser) [inline doc/release/1.14.0-notes.rst]: It's probably worth drawing attention to the fact that this new object is readonly, unlike the previous buffer or byte array that was read/write

Comment (eric-wieser) [reply doc/release/1.14.0-notes.rst]: For that reason, this maybe should be under `Compatibility`

Comment (ahaldane) [reply doc/release/1.14.0-notes.rst]: On the other hand, the previous buffer or byte array wasn't a view or the original array or scalar. So writing to it had no effect. I'll add a note though.

Comment (eric-wieser) [reply doc/release/1.14.0-notes.rst]: Indeed, but it means that users who expected to get a mutable scratch buffer no longer do so.

I suppose the alternative would be to return a `bytearray` object.

Comment (ahaldane) [reply doc/release/1.14.0-notes.rst]: I considered that too. But I suspect we would actually be causing bugs/confusion if we return a bytearray, since it vaguely implies it is a view when it isn't. Returning an immutable `bytes` makes clear you only got a copy.

Updated the note, by the way.

**Review by eric-wieser — APPROVED** [review]
LGTM, but I'd like someone else's opinion on whether changing the mutability is too backwards-incompatible.

**Comment by charris** [comment]
I have no idea if the change in mutability will have much impact. Probably the only way to find out is to try. I suppose we could issue a `FutureWarning` first.

**Comment by ahaldane** [comment]
I doubt it will have much impact, since the old behavior was almost totally non-functional: 

`void.item()` gave back different types objects in python 2 vs python 3 (memoryview vs array), easily caused segfaults, and, confusingly, appeared to be a view (since it was mutable) but was actually just a mutable copy, thus making it usually pointless to modify.

**Comment by eric-wieser** [comment]
So, the choice comes down to picking between

* Return `bytes`, which could break old code using `np.void` as a scratch pad, but accurately indicates that the object is not a view
* Return `bytearray`, which is (fully?) compatible with old code, but gives the illusion that it might be a view (just like it always did)

Either of these is better than leaving things how they are.

**Comment by eric-wieser** [comment]
As an aside, this change make `int(np.array(b'10', np.void))` work, for better or worse

**Comment by ahaldane** [comment]
If there is any doubt, then it's probably safest to issue a DeprecationWarning for 1.14 and leave the behavior alone, and then do the actual change to `bytes` in 1.15. There are definitely times I wish I had been more cautious and warned first in the past!

I just tried adding the warning, and running `runtests.py --raise-warnings develop`, and I don't get any warnings, so adding a warning doesn't seem too noisy.

**Comment by eric-wieser** [comment]
I don't see a good way to give a silenceable warning here

**Comment by charris** [comment]
I pushed this off to 1.15, will go with the warning first.

**Comment by charris** [comment]
@ahaldane  Needs rebase. I'm looking to branch 1.15 pretty soon, should we push this off to the next release to allow the FutureWarning more time or just go ahead. I had the impression that this change was not expected to cause problems.

**Comment by ahaldane** [comment]
whoops, what happened here?

**Comment by eric-wieser** [comment]
@charris: To be clear, you want this to target 1.16?

**Comment by ahaldane** [comment]
I think @charris was asking me to rebase for 1.15, which I did. So this can stay tagged for 1.15.

**Comment by charris** [comment]
OK, I'm looking to put this in. @ahaldane @eric-wieser  Is that OK with you?

**Comment by charris** [comment]
Thanks Allan.

**Comment by ahaldane** [comment]
Thanks Chuck! Yes it was OK.
