### PR TITLE
BUG: Add error-checking versions of strided casts.

### LINKED ISSUE #15790: ndarray.astype Call Raises SystemError
I'm currently trying to hunt down a `SystemError`, and could use some help. Basically, it occurs when attempting certain failing conversions from unicode to string arrays:

```py
import numpy as np

CHAR = "\x80"  # Anything >= 0x80, so we raise a UnicodeEncodeError.
CHAIN = 1  # How many errors will be chained together.
ITEMSIZE = 3  # dtype itemsize, anything except 0, 1, 2, or 4.

nasty = np.array([CHAR] * (128 * CHAIN + 1), dtype=f"U{ITEMSIZE}")
nasty.astype("S")
```

To recap, the error only happens with:
- A total array size of 129 or more (shape doesn't matter). Every additional 128 elements adds a new chained exception.
- A unicode itemsize not equal to 0, 1, 2, or 4.

On CPython 3.9.0a4 and NumPy 1.18.2, the above gives me:

```
UnicodeEncodeError: 'ascii' codec can't encode character '\x80' in position 0: ordinal not in range(128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  ...
SystemError: <class 'UnicodeEncodeError'> returned a result with an error set
```

I've spent quite a while digging around `dtype_transfer.c`, but I'm afraid that I can't find exactly where this is happening. My hunch is that an error raised during processing of a 128-element block isn't caught until all other blocks are finished as well. If several blocks fail, Python complains that the previous exceptions aren't being handled.

If somebody could help me figure out exactly what's going on here (or even provide a good guess), I would definitely appreciate it.

### PR DESCRIPTION
**Pull request by brandtbucher**
Closes #15790.

### CODE REVIEW

**Comment by brandtbucher** [comment]
CI failure looks unrelated, due to #15796.

File: numpy/core/src/multiarray/dtype_transfer.c [hunk 1]
```diff
@@ -375,11 +375,11 @@ static NpyAuxData *_align_wrap_data_clone(NpyAuxData *data)
...
 }
 
-static void
-_strided_to_strided_contig_align_wrap(char *dst, npy_intp dst_stride,
+static inline void
+_strided_to_strided_contig_align_wrap_helper(char *dst, npy_intp dst_stride,
                         char *src, npy_intp src_stride,
                         npy_intp N, npy_intp src_itemsize,
-                        NpyAuxData *data)
+                        NpyAuxData *data, int init_dest, int safe)
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/dtype_transfer.c]: I wonder if we can start using `bool` here. Thoughts, @seberg, @mattip?
```suggestion
                        NpyAuxData *data, bool init_dest, bool safe)
```

Comment (seberg) [reply numpy/core/src/multiarray/dtype_transfer.c]: Sure, sounds good to me, this is private anyway. `safe` is a good word here, or should it be `needs_api` or `force_api` or so?

File: numpy/core/src/multiarray/dtype_transfer.c [hunk 2]
```diff
@@ -521,7 +527,13 @@ wrap_aligned_contig_transfer_function(
                 NPY_LOWLEVEL_BUFFER_BLOCKSIZE*src_itemsize;
 
     /* Set the function and data */
-    if (init_dest) {
+    if (init_dest && out_needs_api) {
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/dtype_transfer.c]: nit: This block might be clearer as:
```C
    if (init_dest) {
        if(out_needs_api) {
            *out_stransfer = &_strided_to_strided_contig_align_wrap_init_dest_safe;
        }
        else {
            *out_stransfer = &_strided_to_strided_contig_align_wrap_init_dest;
        }
    }
    else {
        if (out_needs_api) {
            *out_stransfer = &_strided_to_strided_contig_align_wrap_safe;
        }
        else {
           *out_stransfer = &_strided_to_strided_contig_align_wrap;
        }
    }
```
or perhaps
```C
*out_stransfer = init_dest ? out_needs_api ? &_strided_to_strided_contig_align_wrap_init_dest_safe
                                           : &_strided_to_strided_contig_align_wrap_init_dest
                           : out_needs_api ? &_strided_to_strided_contig_align_wrap_safe
                                           : &_strided_to_strided_contig_align_wrap;
```
Let's see what other reveiwers think

Comment (eric-wieser) [reply numpy/core/src/multiarray/dtype_transfer.c]: Or perhaps the real answer here is to add two fields to `_align_wrap_data`, and then all the branches dissappear.

File: numpy/core/src/multiarray/dtype_transfer.c (hunk 1 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/dtype_transfer.c]: `needs_api` or even `uses_api` would probably be a better name.

File: numpy/core/src/multiarray/dtype_transfer.c [hunk 3]
```diff
@@ -397,6 +397,10 @@ _strided_to_strided_contig_align_wrap(char *dst, npy_intp dst_stride,
             tobuffer(bufferin, inner_src_itemsize, src, src_stride,
                                     NPY_LOWLEVEL_BUFFER_BLOCKSIZE,
                                     src_itemsize, todata);
+            if (init_dest) {
+                memset(bufferout, 0,
+                        dst_itemsize*NPY_LOWLEVEL_BUFFER_BLOCKSIZE);
+            }
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/dtype_transfer.c]: I suppose the idea of this was to avoid paying the cost of the branch during casting. However, it only runs for every `NPY_LOWLEVEL_BUFFER_BLOCKSIZE == 128` elements, so that's probably not a big deal.

File: numpy/core/src/multiarray/dtype_transfer.c (hunk 2 above)
Comment (brandtbucher) [reply numpy/core/src/multiarray/dtype_transfer.c]: Part of the reason I wrote it this way was because the deep nesting and giant function names result in long lines (which are hard to wrap since they're each just an assignment). One option could just be to rename the functions...

I like the idea of adding them to `_align_wrap_data` too, but I'll defer to your judgement here.

File: numpy/core/src/multiarray/dtype_transfer.c (hunk 3 above)
Comment (brandtbucher) [reply numpy/core/src/multiarray/dtype_transfer.c]: Yeah, and it's easily predicted too (if the compiler doesn't take care of it already).

File: numpy/core/src/multiarray/dtype_transfer.c (hunk 2 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/dtype_transfer.c]: To me adding to `_align_wrap_data` makes the most sense

Comment (brandtbucher) [reply numpy/core/src/multiarray/dtype_transfer.c]: That's nice, because it then makes a lot of other code disappear. I'll have something up soon.

File: numpy/core/src/multiarray/dtype_transfer.c (hunk 1 above)
Comment (brandtbucher) [reply numpy/core/src/multiarray/dtype_transfer.c]: Where is the best place to `#include <stdbool.h>`? I assume it's somewhere outside of this file?

Comment (eric-wieser) [reply numpy/core/src/multiarray/dtype_transfer.c]: Maybe best just to use `npy_bool` for now and `NPY_FALSE`/`NPY_TRUE` - we can switch everything over to real bools at some later date.

**Comment by brandtbucher** [comment]
Thanks @eric-wieser! CI is passing, ready for another review.

File: numpy/core/src/multiarray/dtype_transfer.c [hunk 4]
```diff
@@ -488,7 +457,8 @@ wrap_aligned_contig_transfer_function(
             PyArray_StridedUnaryOp *wrapped, NpyAuxData *wrappeddata,
             int init_dest,
             PyArray_StridedUnaryOp **out_stransfer,
-            NpyAuxData **out_transferdata)
+            NpyAuxData **out_transferdata,
+            int out_needs_api)
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/dtype_transfer.c]:
```suggestion
            npy_bool out_needs_api)
```

File: numpy/core/src/multiarray/dtype_transfer.c [hunk 5]
```diff
@@ -488,7 +457,8 @@ wrap_aligned_contig_transfer_function(
             PyArray_StridedUnaryOp *wrapped, NpyAuxData *wrappeddata,
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/dtype_transfer.c]: Documentation comment above should be updated with this new argument

File: numpy/core/src/multiarray/dtype_transfer.c (hunk 4 above)
Comment (eric-wieser) [inline numpy/core/src/multiarray/dtype_transfer.c]: Let's put the out arguments last, and insert this new one right after `init_dest`.

Comment (brandtbucher) [reply numpy/core/src/multiarray/dtype_transfer.c]: How far would we want this change to bubble up the call stack?

Comment (eric-wieser) [reply numpy/core/src/multiarray/dtype_transfer.c]: Let's just declare it out of scope for now.

Comment (eric-wieser) [reply numpy/core/src/multiarray/dtype_transfer.c]: Opened gh-15814

File: numpy/core/tests/test_regression.py [hunk 6]
```diff
@@ -1408,6 +1408,11 @@ def test_unicode_to_string_cast(self):
                      dtype='U')
         assert_raises(UnicodeEncodeError, np.array, a, 'S4')
 
+    def test_unicode_to_string_cast_error(self):
+        # Ticket #15790.
```
Comment (eric-wieser) [inline numpy/core/tests/test_regression.py]:
```suggestion
        # gh-15790.
```

"Ticket" refers to an old non-github issue tracker.

Comment (brandtbucher) [reply numpy/core/tests/test_regression.py]: Should I update the commit messages too? They use "#15790".

Comment (seberg) [reply numpy/core/tests/test_regression.py]: I guess we/I like `gh-` but its also a bit of a lost cause :). So if you are motivated, sure. The word "Ticket" explicitly feels like the very old Ticket system...

Comment (eric-wieser) [reply numpy/core/tests/test_regression.py]: Indeed, the real danger is the word `Ticket`. #NNN vs gh-NNN isn't quite so big an issue, but the former is a little more future-proof, and looks better than `# #15790` in a comment.

Comment (brandtbucher) [reply numpy/core/tests/test_regression.py]: I probably won't update the commit messages just because I don't like changing history in the middle of a PR.

I'll update this, though.

Comment (eric-wieser) [reply numpy/core/tests/test_regression.py]: If you're concerned about a nice history, it might be neat to rewrite these commits - start wiht the `MAINT` commit first which eliminates a bunch of code, and then the `BUG`/`TST` second.

Comment (brandtbucher) [reply numpy/core/tests/test_regression.py]: Sorry, are you saying I *should* rewrite/reorder the commits? I can if that would help, but I just want to clarify first.

Comment (eric-wieser) [reply numpy/core/tests/test_regression.py]: If you don't, I'll probably just squash them into a single commit, and I'm fine with doing that.

In the context of a merged PR, I find it's good for commits to tell a story of the shortest path from start to finish, not the longer path that was taken in response to review feedback. Adding a bunch of code only to simplify it and remove it again just creates noise for people walking back through the blame.

Comment (brandtbucher) [reply numpy/core/tests/test_regression.py]: Gotcha. I'll take a second and do that then, since this is a pretty simple patch.

I just know that other projects don't like force-pushed changes (since it can mess up the review), so I wanted to check first!

Comment (brandtbucher) [reply numpy/core/tests/test_regression.py]: I’ve completed the rebase. Everything looks good!

Comment (eric-wieser) [reply numpy/core/tests/test_regression.py]: One last request - can you move the `TST` commit after the `MAINT` commit so that the `MAINT` commit would pass by itself?

Comment (brandtbucher) [reply numpy/core/tests/test_regression.py]: Hmm... It looks like that's just a display issue in the PR. If you go to my branch (or check it out locally), you can see that the commits are in the [right order](https://github.com/brandtbucher/numpy/commits/unsafe-cast).

I've seen similar things happen on GitHub with complicated rebases and force-pushes before.

Comment (eric-wieser) [reply numpy/core/tests/test_regression.py]: Haven't seen that one in a while, thanks for the reminder!

**Review by eric-wieser — APPROVED** [review]

**Comment by eric-wieser** [comment]
Thanks for an excellent first contribution @brandtbucher

**Comment by brandtbucher** [comment]
Thanks for your guidance @eric-wieser. Definitely looking forward to contributing more here!

**Comment by eric-wieser** [comment]
If you're after a similar bug, #15502 looks like a good candidate.

**Comment by seberg** [comment]
Very cool, thanks, this is a necessary start! Next thing will be to also fix:
```
a = np.array([u'\x80'] * 129 * 10, dtype='U3').reshape(-1, 10)
a[:-1, :-1].astype("S")
```
:). But that touches much deeper and more code unfortunately.

**Comment by brandtbucher** [comment]
@seberg I actually think the fix for your case is simple. We can just move the error check we added from line 418 to 401, so it fires at the start of every loop.

I can make a quick PR with a test if that sounds good to you.

**Comment by seberg** [comment]
Right, we can do that. But I do not really like doing that everywhere :), so I really want to propagate the error flag out. Which is not to say we couldn't just do that for now, the performance implication (in most cases) is probably minor.

**Comment by brandtbucher** [comment]
Shall I open a PR with the change, and see what everyone thinks? For what it's worth, I've run:

```py
In [1]: import numpy as np
In [2]: a = np.array(['X'] * 10_000_000, "U3").reshape(-1, 200)
In [3]: %timeit a.astype("S")
```
...and I don't see any performance difference between code which checks for errors every loop, and the old code with no error checking.

**Comment by brandtbucher** [comment]
Ah, didn't see your edit. I'll go ahead and propose this, then.
