### PR TITLE
FIX: protect stolen ref by PyArray_NewFromDescr in array_empty

### LINKED ISSUE #8179: Refcount of dtype drops to zero in array_empty.
On numpy-1.11.1 and numpy-1.11.2

test.py:
```
import numpy
a = numpy.empty(0, 'f4')
b = numpy.empty(0, (a.dtype, 3))
```

Run
```
valgrind --vgdb=yes --vgdb-error=0 python3 test.py
```
and attach gdb, then
```
==4214== Memcheck, a memory error detector
==4214== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==4214== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==4214== Command: python3 test.py
==4214== 
==4214== (action at startup) vgdb me ... 
==4214== 
==4214== TO DEBUG THIS PROCESS USING GDB: start GDB like this
==4214==   /path/to/gdb python3
==4214== and then give GDB the following command
==4214==   target remote | /usr/lib64/valgrind/../../bin/vgdb --pid=4214
==4214== --pid is optional if only one valgrind process is running
==4214== 
==4214== Invalid read of size 1
==4214==    at 0xD7FA907: PyArray_Empty (ctors.c:2898)
==4214==    by 0xD8BB317: array_empty (multiarraymodule.c:1814)
==4214==    by 0x4EE4E38: PyCFunction_Call (methodobject.c:98)
==4214==    by 0x4F5BDC6: call_function (ceval.c:4684)
==4214==    by 0x4F5BDC6: PyEval_EvalFrameEx (ceval.c:3209)
==4214==    by 0x4F5D752: _PyEval_EvalCodeWithName (ceval.c:3995)
==4214==    by 0x4F5D832: PyEval_EvalCodeEx (ceval.c:4016)
==4214==    by 0x4F5D85A: PyEval_EvalCode (ceval.c:797)
==4214==    by 0x4F7CD83: run_mod (pythonrun.c:970)
==4214==    by 0x4F7F324: PyRun_FileExFlags (pythonrun.c:923)
==4214==    by 0x4F7F494: PyRun_SimpleFileExFlags (pythonrun.c:396)
==4214==    by 0x4F9602B: run_file (main.c:318)
==4214==    by 0x4F9602B: Py_Main (main.c:768)
==4214==    by 0x108B6F: main (python.c:69)
==4214==  Address 0xf6e243b is 27 bytes inside a block of size 96 free'd
==4214==    at 0x4C2CD5A: free (vg_replace_malloc.c:530)
==4214==    by 0xD8122B9: arraydescr_dealloc (descriptor.c:1666)
==4214==    by 0xD7F308E: _update_descr_and_dimensions (ctors.c:292)
==4214==    by 0xD7F4E1F: PyArray_NewFromDescr_int (ctors.c:915)
==4214==    by 0xD7F595A: PyArray_NewFromDescr (ctors.c:1137)
==4214==    by 0xD7FA8EC: PyArray_Empty (ctors.c:2891)
==4214==    by 0xD8BB317: array_empty (multiarraymodule.c:1814)
==4214==    by 0x4EE4E38: PyCFunction_Call (methodobject.c:98)
==4214==    by 0x4F5BDC6: call_function (ceval.c:4684)
==4214==    by 0x4F5BDC6: PyEval_EvalFrameEx (ceval.c:3209)
==4214==    by 0x4F5D752: _PyEval_EvalCodeWithName (ceval.c:3995)
==4214==    by 0x4F5D832: PyEval_EvalCodeEx (ceval.c:4016)
==4214==    by 0x4F5D85A: PyEval_EvalCode (ceval.c:797)
==4214==  Block was alloc'd at
==4214==    at 0x4C2BBAD: malloc (vg_replace_malloc.c:299)
==4214==    by 0x4EE9BD4: _PyObject_Alloc.isra.0 (obmalloc.c:1376)
==4214==    by 0x4EE702C: _PyObject_New (object.c:263)
==4214==    by 0xD811DC6: PyArray_DescrNew (descriptor.c:1592)
==4214==    by 0xD811230: PyArray_DescrNewFromType (descriptor.c:1241)
==4214==    by 0xD80E7AC: _convert_from_tuple (descriptor.c:324)
==4214==    by 0xD81187D: PyArray_DescrConverter (descriptor.c:1471)
==4214==    by 0x4F6BE29: convertsimple (getargs.c:1219)
==4214==    by 0x4F6BE29: convertitem (getargs.c:519)
==4214==    by 0x4F6DE35: vgetargskeywords (getargs.c:1562)
==4214==    by 0x4F6ED3D: _PyArg_ParseTupleAndKeywords_SizeT (getargs.c:1361)
==4214==    by 0xD8BB2C4: array_empty (multiarraymodule.c:1794)
==4214==    by 0x4EE4E38: PyCFunction_Call (methodobject.c:98)
==4214== 
```

I suspect it should be a trivial fix: we just need to secure a reference to the dtype passed in till the function returns. 

Is it possible to include a test case like this? The difficulty is that it won't actually segfault unless another thread claims the memory used by the old descr.

### PR DESCRIPTION
**Pull request by rainwoodman**
This fixes #8179.

Valgrind warning is gone.

I checked other uses of PyArray_NewFromDescr in ctor.c all look healthy.

### CODE REVIEW

**Comment by ahaldane** [comment]
LGTM.

The description of `PyArray_NewFromDescr` makes clear it sometimes immediately decrefs the `descr`, eg when a subarray is involved.

**Comment by ahaldane** [comment]
I don't think a test is needed, but @charris may want the commit message to say "BUG" instead of "FIX", see our [standard prefixes](https://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html#writing-the-commit-message), so I'll leave that to him.

File: numpy/core/src/multiarray/ctors.c [hunk 1]
```diff
@@ -2895,20 +2895,25 @@ PyArray_Empty(int nd, npy_intp *dims, PyArray_Descr *type, int is_f_order)
     PyArrayObject *ret;
 
     if (!type) type = PyArray_DescrFromType(NPY_DEFAULT_TYPE);
+
+    /* PyArray_NewFromDescr steals a ref,
+     * but we need to look at type later. */
```
Comment (seberg) [inline numpy/core/src/multiarray/ctors.c]: While we are at nitpicking, the comment end should be formatted:
```
/*
 * Text here
 * more text
 */
```

Comment (seberg) [inline numpy/core/src/multiarray/ctors.c]: or keep it on a single line ;)

**Comment by seberg** [comment]
Should try your valgrind commands, or is there some speical setup needed? For some reason, running numpy/python stuff through valgrind does not work for me anymore since a while....

**Comment by seberg** [comment]
Out of curiosity, did you run with a specially compiled python or do those valgrind options hide the typical python allocation spam?

**Comment by rainwoodman** [comment]
@seberg For one, I updated to Fedora 24 and all of the allocation spam are gone. gdb supports python too. If that counts towards an answer...

**Comment by rainwoodman** [comment]
@ahaldane messages updated.

**Comment by rainwoodman** [comment]
@seberg : according to the changelog at http://koji.fedoraproject.org/koji/buildinfo?buildID=809980, Fedora has been compiling Python with valgrind support for a few years. The support may have just gotten better in 3.5, I guess.

**Comment by seberg** [comment]
Dunno, was using debian/ubuntu, it always worked (though I had to add suppressions, which probably would have hidden cases such as this one as well), have not tried it in a bit, but more recently things always crashed. But no worries, seems like other people run the testsuit through valgrind once in a while nowadays ;). I'll leave the merge to @ahaldane.

**Comment by ahaldane** [comment]
Great, merging. Thanks @rainwoodman for the valgrind tests!

**Comment by rainwoodman** [comment]
no problems!
