### PR TITLE
BUG: np.arange: Allow `stop` not `start` as sole kwargs. 

### LINKED ISSUE #17764: BUG: Using start/step as keywords only has incorrect behaviour
Did version 1.18.5 break numpy.arange??
```
import numpy as np
print(np.__version__)
arr3 = np.arange(start=5)
print(arr3)
arr4 = np.arange(stop=8)
print(arr4)

1.18.5
[0 1 2 3 4]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-11be2fcdeb56> in <module>
      3 arr3 = np.arange(start=5)
      4 print(arr3)
----> 5 arr4 = np.arange(stop=8)
      6 print(arr4)

TypeError: arange() missing required argument 'start' (pos 1)
```

### PR DESCRIPTION
**Pull request by MaiaKaplan**
Fixes gh-17764

* Of note: Removes requirement for `start` argument in argparse format string
* Behaviour change: Avoids `arange(start=4)` returning a range from 0 to 4
* Behaviour change:  Allows `arange(stop=4)` to run without error, to return range from 0 to 4

### CODE REVIEW

File: numpy/core/src/multiarray/multiarraymodule.c [hunk 1]
```diff
@@ -2940,6 +2940,33 @@ array_arange(PyObject *NPY_UNUSED(ignored), PyObject *args, PyObject *kws) {
...
+        PyObject *start_str = PyUnicode_FromString("start");
+        PyObject *stop_str = PyUnicode_FromString("stop");
+        if (PyDict_Contains(kws, start_str) == 1 &&
+                PyDict_Contains(kws, stop_str) == 0){
+            PyErr_SetString(PyExc_TypeError,
+                    "arange() requires 'stop' if 'start' is specified.");
+            Py_DECREF(start_str);
+            Py_DECREF(stop_str);
+            return NULL;
+        } else if (PyDict_Contains(kws, start_str) == 0 &&
```
Comment (seberg) [inline numpy/core/src/multiarray/multiarraymodule.c:2959]: Nitpick: We usually put the `else` on a new lin from the closing bracket `}`.

File: numpy/core/tests/test_function_base.py [hunk 2]
```diff
@@ -407,3 +407,29 @@ def test_round_negative(self):
         y = linspace(-1, 3, num=8, dtype=int)
         t = array([-1, -1, 0, 0, 1, 1, 2, 3], dtype=int)
         assert_array_equal(y, t)
+
+
+class TestArange:
+    def test_require_range(self):
+        import pytest
```
Comment (seberg) [inline numpy/core/tests/test_function_base.py:414]: The pytest import should be top-level, if it is not already.

(I am a bit surprised by the codecov comments, since those lines seem covered by these tests...)

File: numpy/core/tests/test_function_base.py [hunk 3]
```diff
@@ -407,3 +407,29 @@ def test_round_negative(self):
...
+            arange(start=4)
+
+    def test_start_stop_kwarg(self):
+        keyword_stop = arange(stop=3)
+        keyword_zerotostop = arange(start=0, stop=3)
+        keyword_start_stop = arange(start=3, stop=9)
+
+        assert len(keyword_stop) == 3
+        assert len(keyword_zerotostop) == 3
+        assert (keyword_stop == keyword_zerotostop).all()
```
Comment (seberg) [inline numpy/core/tests/test_function_base.py:434]: Just FYI, we also have a `assert_arrays_equal`, which checks also shape/dtype (difference that `all()` might miss). It doesn't matter here though.

**Review by seberg — COMMENTED** [review]
Thanks Maia!  I think the logic can be simplified if you check for positional arguments instead of `kwarg`. I.e. if args are passed in and there is at least one element, you know that `start` was passed by position and not by name (that also avoids the slightly annoying dictionary keyword creation, etc. which just makes me want to micro-optimize it ;)):

If `o_stop == NULL`:
* If `args != NULL && PyTuple_GET_SIZE(args) > 0` (not sure args can be NULL...):
  * `start` must have been passed by position.
  * `o_stop = o_start; o_start = NULL`
* Else: `raise TypeError(...)`

**Comment by mattip** [comment]
I am not sure about the micro-optimization. I think the function is most likely to be called without kwargs, so `if (kws != NULL)` is more likely to be false than `args != NULL && PyTuple_GET_SIZE(args) > 0`. The fact that the function has been around since the beginning of time before someone noticed the logical error supports my theory.

**Comment by seberg** [comment]
Good point, but I still think it will make for much simpler/shorter code.  I guess you could keep the `if (kwds == NULL)` to make it `kwds == NULL || args != NULL && PyTuple_GET_SIZE(args) > 0`.

**Comment by seberg** [comment]
Ah, looking at it again. The C-level function handles `stop == NULL` (meaning start is stop), but not not `start == NULL`, so the swapping is the other way around and it is a bit more complicated than I thought:

```
if o_stop == NULL:
    # start is used as stop, but we reject this if it is passed by keyword
    if kwds != NULL and (args == NULL or len(args) == 0):
        # If keywords were used and no positional argument passed,
        # start was passed by keyword and cannot be used as stop.
        raise TypeError("uhoh, stop not passed!")
else if o_start == NULL:
    # Pass stop as NULL to indicate that start is stop
    o_start = o_stop
    o_stop = NULL    
```

**Comment by MaiaKaplan** [comment]
> Ah, looking at it again. The C-level function handles `stop == NULL` (meaning start is stop), but not not `start == NULL`, so the swapping is the other way around and it is a bit more complicated than I thought:
> 
> ```
> if o_stop == NULL:
>     # start is used as stop, but we reject this if it is passed by keyword
>     if args == NULL or len(args) == 0:  # could check `kwds != NULL` first 
>         # If keywords were used and no positional argument passed,
>         # start was passed by keyword and cannot be used as stop.
>         raise TypeError("uhoh, stop not passed!")
> else if o_start == NULL:
>     # Pass stop as NULL to indicate that start is stop
>     o_start = o_stop
>     o_stop = NULL    
> ```

**Comment by MaiaKaplan** [comment]
Thanks for the comments and the suggestion! please also delight with me in my closing/reopening the ticket -- proper newcomer :) I have a few questions:

1. I think the downstream C-function takes care of swapping o_stop for o_start if o_start is not provided, if I am reading it correctly? If so, I would then leave the block out. 

2. I also want to confirm then that is not an enhancement: that the goal is also to keep the current behaviour of not allowing `arange(stop=4)` currently:
```
> np.arange(3)
array([0, 1, 2])
> np.arange(stop=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: arange() missing required argument 'start' (pos 1)
```
3. Confirming that the tests are in the appropriate spot? I wasn't able to find any arange tests so I'm not confident in where I put these. I'll hope that when I update the ^ code, the coverage issue will go away. 

re:
> Ah, looking at it again. The C-level function handles `stop == NULL` (meaning start is stop), but not not `start == NULL`, so the swapping is the other way around and it is a bit more complicated than I thought:
> 
> ```
> if o_stop == NULL:
>     # start is used as stop, but we reject this if it is passed by keyword
>     if args == NULL or len(args) == 0:  # could check `kwds != NULL` first 
>         # If keywords were used and no positional argument passed,
>         # start was passed by keyword and cannot be used as stop.
>         raise TypeError("uhoh, stop not passed!")
> else if o_start == NULL:
>     # Pass stop as NULL to indicate that start is stop
>     o_start = o_stop
>     o_stop = NULL    
> ```

**Comment by seberg** [comment]
About point 1. I am not sure the called function supports `start = NULL` with `stop` given, so in that case we probably have to swap (which happens if `step=...` is passed as kwarg).

About 2. my working assumption was you meant to allow `arange(stop=4)` to be the same as `arange(4)` and `arange(0, stop=4)`. But, I am happy with whatever you prefer (and it can easily be extended later).

About the test location. It is fine by me, maybe someone has a better idea. I guess there isn't a perfect place :(. `test_multiarray.py` might seem a bit closer to right, but it is also an annoyingly large and random file. The `test_function_base.py` is probably paired with `function_base.py` though. OTOH, it does contain functions that are similar in scope to `arange`.
What matters more to me is the `TestArange` class, which is a great addition!

**Comment by seberg** [comment]
Thanks Maia! If you are still wondering about the codecov, I expect it is just due to compiler optimizing pretty much everything away.

File: numpy/core/src/multiarray/multiarraymodule.c [hunk 4]
```diff
@@ -2940,6 +2940,18 @@ array_arange(PyObject *NPY_UNUSED(ignored), PyObject *args, PyObject *kws) {
         return NULL;
     }
 
+    if (o_stop == NULL) {
+        if (args == NULL || PyTuple_GET_SIZE(args) == 0){
+            PyErr_SetString(PyExc_TypeError,
+                "arange() requires stop to be specified.");
+            return NULL;
```
Comment (seberg) [inline numpy/core/src/multiarray/multiarraymodule.c:2947]: Sorry, I a bit of a sloppy day for me... I just noticed that this branch is missing the `Py_XDECREF(typecode);`

One reason why I am sloppy about these things though, is that nowadays reference count checkers catch these bugs pretty  well most of the time (Unrelated note for anyone who wonders: No I have not run `pytest-leaks` on master/1.20 after branching, only valgrind which is typically not sensitive enough for this type of leak usually.)

Comment (mattip) [reply numpy/core/src/multiarray/multiarraymodule.c:2947]: Maybe a short note in the docs about how to check this would be good. Is there a way to run a checker only on a single test like `python <some command> test_start_stop_kwarg`?

Comment (MaiaKaplan) [reply numpy/core/src/multiarray/multiarraymodule.c:2947]: Follow up https://github.com/numpy/numpy/pull/17966
