### PR TITLE
BUG: Fix build of third-party extensions with Py_LIMITED_API

### LINKED ISSUE #13784: TEST: make sure third parties can define Py_LIMITED_API
We should have a test something like the detail in [this comment](https://github.com/numpy/numpy/pull/13725#issuecomment-501648950) to make sure downstream consumers of the NumPy C-API can use Py_LIMITED_API. The test should make sure we do not add a CPython API to the headers that breaks Py_LIMITED_API.

### PR DESCRIPTION
**Pull request by lpsinger**
Fixes #13784.

This PR consists of two commits:
* The first commit fixes the regression of Py_LIMITED_API support that snuck in with #20315.
* The second commit adds the test.

### CODE REVIEW

File: numpy/core/include/numpy/ufuncobject.h [hunk 1]
```diff
@@ -173,7 +173,11 @@ typedef struct _tagPyUFuncObject {
          * but this was never implemented. (This is also why the above
          * selector is called the "legacy" selector.)
          */
-        vectorcallfunc vectorcall;
+        #ifndef Py_LIMITED_API
+            vectorcallfunc vectorcall;
```
Comment (seberg) [inline numpy/core/include/numpy/ufuncobject.h:177]: Maybe we should keep the version check as well as the Py_LIMITED_API one?  Something like:
```
#if !defined(Py_LIMITED_API) || Py_LIMITED_API >= 0x03080000 
```
because I would expect `vectorcallfunc` to be part of the limited API, just not in 3.6 of course.

Comment (lpsinger) [reply numpy/core/include/numpy/ufuncobject.h:177]: > Maybe we should keep the version check as well as the Py_LIMITED_API one? Something like:
> 
> ```
> #if !defined(Py_LIMITED_API) || Py_LIMITED_API >= 0x03080000 
> ```
> 
> because I would expect `vectorcallfunc` to be part of the limited API, just not in 3.6 of course.

According to the Python documentation and the latest cpython header files, `vectorcallfunc` is not part of the limited API at all --- in any version of Python. It's possible that it may be added to the limited API in a future version of Python, but I don't know how to guard against that.

> EDIT: As far as I understand, we need it so that an extension can be designed to be used on, e.g. Python 3.6 with an old version of NumPy, but _also_ on Python 3.8 with a new version (if compiled against that)?

Yes, but it's even more than that: third-party packages that use the limited API can build a single wheel targeting all Python versions for a given operating system (the `abi3` tag, see [PEP 425](https://www.python.org/dev/peps/pep-0425/)). I am the author of a package that does this (ligo.skymap - see wheels at https://pypi.org/project/ligo.skymap/#files). It's pretty slick!

> 
> EDIT2: We could probably also rename the `reserved2` to `vectorcall`. We are not lieing in the header, the user just doesn't know what the type is.

:+1: I'll make that change.

Comment (lpsinger) [reply numpy/core/include/numpy/ufuncobject.h:177]: Done.

Comment (seberg) [reply numpy/core/include/numpy/ufuncobject.h:177]: OK, thanks I had not expected it to be never part of the limited API.  LGTM then, @mattip may have an opinion about the test, we could potentially considering making it real test that runs in CI.

**Review by seberg — APPROVED** [review]
Thanks, LGTM!

Not sure if we want to move the test somewhere else (I don't think it is run in CI?), but I do not mind if we don't get it.  So it looks good as is, but maybe Matti has an idea for the test.

**Comment by seberg** [comment]
@lpsinger it looks good, however the debug tests are failing.  I am not sure I understand why?  I now realize that yes, this gets run as a test so that is all good, anyway, and I was just silly.

But this extension must not be compiled if we are running in debug mode... Although, I am not clear why this many tests are failing.

**Comment by lpsinger** [comment]
> @lpsinger it looks good, however the debug tests are failing. I am not sure I understand why? I now realize that yes, this gets run as a test so that is all good, anyway, and I was just silly.
> 
> But this extension must not be compiled if we are running in debug mode... Although, I am not clear why this many tests are failing.

Understood. I'll split the example project into two projects so that we can build them in separate tests, and apply something like the skipif statement from https://github.com/numpy/numpy/blob/main/numpy/tests/test_public_api.py#L468-L475 to it.

**Comment by lpsinger** [comment]
> > @lpsinger it looks good, however the debug tests are failing. I am not sure I understand why? I now realize that yes, this gets run as a test so that is all good, anyway, and I was just silly.
> > But this extension must not be compiled if we are running in debug mode... Although, I am not clear why this many tests are failing.
> 
> Understood. I'll split the example project into two projects so that we can build them in separate tests, and apply something like the skipif statement from https://github.com/numpy/numpy/blob/main/numpy/tests/test_public_api.py#L468-L475 to it.

Note, I found that on my Mac, `Py_DEBUG` was defined as `0`, not `None`. https://github.com/numpy/numpy/blob/main/numpy/tests/test_public_api.py#L468-L475 may be buggy...

**Comment by lpsinger** [comment]
OK, the debug build is passing now.

**Comment by lpsinger** [comment]
> * Should the test be marked "slow" so people who run `np.test()` will not run it?

I don't think so. The old cython test that I adapted this from wasn't marked as slow. In any case, that could be a separate PR.

> * You might want take a look at the new [extbuild](https://numpy.org/devdocs/reference/testing.html?highlight=extbuild#using-c-code-in-tests) function to build modules. It is used in the [`test_mem_policy` tests](https://github.com/numpy/numpy/blob/main/numpy/core/tests/test_mem_policy.py). Maybe it is overkill for this use case?

Oh, very slick. I'll try that.

**Comment by lpsinger** [comment]
> > * You might want take a look at the new [extbuild](https://numpy.org/devdocs/reference/testing.html?highlight=extbuild#using-c-code-in-tests) function to build modules. It is used in the [`test_mem_policy` tests](https://github.com/numpy/numpy/blob/main/numpy/core/tests/test_mem_policy.py). Maybe it is overkill for this use case?
> 
> Oh, very slick. I'll try that.

Unfortunately, `numpy.testing.extbuild.build_and_import_extension` won't work for this use case. There is no way to inject the `#define` early enough in the code that it generates, because the first line is always `#include <Python.h>` and it adds the prologue _after_ that. Let's stick with the current implementation of the test, shall we?

**Comment by seberg** [comment]
Lets put it in than, thanks!
