### PR TITLE
BUG: fix timedelta arithmetic with invalid values or NaTs

### LINKED ISSUE #6274: Invalid timedelta division on ARMv7l
On x86:

```
>>> np.timedelta64(1) / 0.0
__main__:1: RuntimeWarning: divide by zero encountered in true_divide
__main__:1: RuntimeWarning: invalid value encountered in true_divide
numpy.timedelta64('NaT')
>>> np.timedelta64(1) / 0
numpy.timedelta64('NaT')
```

On a Raspberry Pi 2 (with the numpy package from Anaconda):

```
>>> np.timedelta64(1) / 0.0
__main__:1: RuntimeWarning: divide by zero encountered in true_divide
__main__:1: RuntimeWarning: invalid value encountered in true_divide
numpy.timedelta64(-1)
>>> np.timedelta64(1) / 0
numpy.timedelta64('NaT')
```

Note that it triggers with float division but not integer division.

```
$ uname -a
Linux raspberrypi 3.18.14-v7+ #2 SMP PREEMPT Thu May 28 18:17:59 UTC 2015 armv7l GNU/Linux
```

### PR DESCRIPTION
**Pull request by pitrou**
Timedelta multiplication and division relied on undefined behaviour for some
inputs, which would give the expected results on x86 but not on armv7l
(e.g. Raspberry Pi 2).  Closes #6274.

### CODE REVIEW

File: numpy/core/src/umath/loops.c.src [hunk 1]
```diff
@@ -1286,11 +1286,17 @@ TIMEDELTA_md_m_multiply(char **args, npy_intp *dimensions, npy_intp *steps, void
...
         const double in2 = *(double *)ip2;
-        if (in1 == NPY_DATETIME_NAT || npy_isnan(in2)) {
+        if (in1 == NPY_DATETIME_NAT) {
             *((npy_timedelta *)op1) = NPY_DATETIME_NAT;
         }
         else {
-            *((npy_timedelta *)op1) = (npy_timedelta)(in1 * in2);
+            double result = in1 * in2;
+            if (npy_isfinite(result)) {
+                *((npy_timedelta *)op1) = (npy_timedelta)(result);
```
Comment (jaimefrio) [inline numpy/core/src/umath/loops.c.src]: No parenthesis needed around `result`. I'd argue also not around `(npy_timedelta *)op1`, but that seems to be everywhere, so better to leave it as is.

File: numpy/core/src/umath/loops.c.src [hunk 2]
```diff
@@ -1301,11 +1307,17 @@ TIMEDELTA_dm_m_multiply(char **args, npy_intp *dimensions, npy_intp *steps, void
...
         const npy_timedelta in2 = *(npy_timedelta *)ip2;
-        if (npy_isnan(in1) || in2 == NPY_DATETIME_NAT) {
+        if (in2 == NPY_DATETIME_NAT) {
             *((npy_timedelta *)op1) = NPY_DATETIME_NAT;
         }
         else {
-            *((npy_timedelta *)op1) = (npy_timedelta)(in1 * in2);
+            double result = in1 * in2;
+            if (npy_isfinite(result)) {
+                *((npy_timedelta *)op1) = (npy_timedelta)(result);
```
Comment (jaimefrio) [inline numpy/core/src/umath/loops.c.src]: Also here.

File: numpy/core/src/umath/loops.c.src [hunk 3]
```diff
@@ -1337,11 +1349,11 @@ TIMEDELTA_md_m_divide(char **args, npy_intp *dimensions, npy_intp *steps, void *
         }
         else {
             double result = in1 / in2;
-            if (npy_isnan(result)) {
-                *((npy_timedelta *)op1) = NPY_DATETIME_NAT;
+            if (npy_isfinite(result)) {
+                *((npy_timedelta *)op1) = (npy_timedelta)(result);
```
Comment (jaimefrio) [inline numpy/core/src/umath/loops.c.src]: And here.

**Comment by jaimefrio** [comment]
LGTM, pending Travis and a minor style nitpick.

**Comment by pitrou** [comment]
For the record, I've fixed the style issue.

**Comment by jaimefrio** [comment]
Thanks Antoine.
