### PR TITLE
BUG: fixes for three related stringdtype issues

### LINKED ISSUE #26420: BUG: Passing a stringdtype array to np.where can lose string data
### Describe the issue:

Similar to #26147 and #26317 it looks like `np.where` should be doing a copy instead of a view for `StringDType`.

### Reproduce the code example:

```python
import numpy as np
a = np.array(["a"*25, "b", np.nan], dtype=np.dtypes.StringDType(na_object=np.nan))
print(repr(np.where(a, a, a)))
```

### Result:

```shell
# prints:
array(['', 'b', nan], dtype=StringDType(na_object=nan))

# should print:
array(['aaaaaaaaaaaaaaaaaaaaaaaaa', 'b', nan],
      dtype=StringDType(na_object=nan))
```

### Python and NumPy Versions:

Current `main` branch, python 3.12.2.

### Runtime Environment:

_No response_

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes #26420.

While working on the issue with `where` found in #26240, I noticed two other related issues. Since the fix for where depends on the other two fixes, I figured it would make sense to send them all as one PR.

First, it turns out that advanced indexing was broken for indexing any entry in an array that needs a heap allocation. On current main, this leads to errors or segfaults:

```
>>> import numpy as np
>>> a = np.array(["a", "c", "h"*25], dtype=np.dtypes.StringDType(na_object=None))
>>> a[[1,2]]
... elide traceback ...
MemoryError: Failed to load string in StringDType getitem
```

The fix is to properly set the output descriptor in the casting setup in `array_subscript`.

Second, I noticed that the `nonzero` function completely ignores nulls. I also noticed that the string to bool cast assumed all nulls are truthy and ignored the existence of nulls like `None` that should be falsey, following the behavior of object array:

```
>>> import numpy as np
>>> np.nonzero(np.array(['hello', np.nan, 'world'], dtype=object))
(array([0, 1, 2]),)
>>> np.nonzero(np.array(['hello', None, 'world'], dtype=object))
(array([0, 2]),)
```

This updates both `nonzero` and the string to bool cast to account for this and makes sure they behave identically.

Finally, the issue with `where` is also caused by not setting the input and output descriptors properly in the cast setup in `PyArray_Where`. The casting code here dates back to https://github.com/numpy/numpy/pull/23770, which was before stringdtype had an arena allocator. With the arena allocator, we need to be more careful about bookkeeping on input and output descriptors. This means we also need to setup a separate cast for the second input descriptor.

Also adds tests for all three fixed issues.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Hmm, looks like this breaks some other things, will investigate and update.

File: numpy/_core/src/multiarray/multiarraymodule.c [hunk 1]
```diff
@@ -3286,9 +3287,19 @@ PyArray_Where(PyObject *condition, PyObject *x, PyObject *y)
...
+    PyArray_Descr *x_dt, *y_dt;
+    int has_ref = PyDataType_REFCHK(common_dt);
+    if (has_ref) {
+        x_dt = PyArray_DESCR(op_in[2]);
+        y_dt = PyArray_DESCR(op_in[3]);
+    }
+    else {
+        x_dt = common_dt;
+        y_dt = common_dt;
+    }
```
Comment (ngoldbaum) [inline numpy/_core/src/multiarray/multiarraymodule.c:3299]: For `has_ref` we do an explicit cast and don't let the iterator handle the cast for us. Otherwise, the iterator handles the cast.

Maybe I should add the above text as a comment?

**Comment by ngoldbaum** [comment]
> Hmm, looks like this breaks some other things, will investigate and update.

Should be good now.

File: numpy/_core/src/multiarray/multiarraymodule.c (hunk 1 above)
Comment (seberg) [reply numpy/_core/src/multiarray/multiarraymodule.c:3299]: A comment would make sense I think.  In principle, whenever we don't use the fast-path below, doing this probably makes sense (not casting in the iterator).

I am not sure that "has-ref" is in practice the right check, or whether it shouldn't be the "may create a new dtype on copy" (although in practice has-ref covers that).

**Review by seberg — APPROVED** [review]
Thanks, changes look good, I am not sure the has-ref logic is quite spot on and if we should refine it.
Adding that comment would be nice.

File: numpy/_core/src/multiarray/multiarraymodule.c (hunk 1 above)
Comment (seberg) [reply numpy/_core/src/multiarray/multiarraymodule.c:3299]: With a bit clearer head, maybe let me clarify:

My comment about checking for "may create a new dtype on copy" seems incorrect.  We assume that `has_ref` is sufficient to say that we are allowed to trivially copy the data.
I think it is safe to say that a dtype which does spawn new instance here must ensure that trivial copies are still allowed so that we are fine.
(For fresh clones of the dtype anyway, one could imagine mutable categoricals.)

I still think if it doesn't clutter things: it would be nice to fully align casting to `common_dt` to whether we can use the trivial-copy fast paths or not.
But as I said, I am happy with just a comment explaining it.

File: numpy/_core/src/multiarray/multiarraymodule.c [hunk 2]
```diff
@@ -3305,8 +3316,6 @@ PyArray_Where(PyObject *condition, PyObject *x, PyObject *y)
 
     npy_intp itemsize = common_dt->elsize;
 
-    int has_ref = PyDataType_REFCHK(common_dt);
-
     NPY_ARRAYMETHOD_FLAGS transfer_flags = 0;
 
     npy_intp transfer_strides[2] = {itemsize, itemsize};
```
Comment (seberg) [inline numpy/_core/src/multiarray/multiarraymodule.c:3321]:
```suggestion
    /* Single element copy; `itemsize, itemsize` is just a guess at contiguous. */
    npy_intp transfer_strides[2] = {itemsize, itemsize};
```
Just stumbled a second here because the first `itemsize` is now a random guess.  Maybe a comment makes sense (not that it changed and I am not sure).  Or just change it to `0, 0` I doubt it matters in practice.

**Comment by ngoldbaum** [comment]
Also thanks so much for the careful review! I completely missed the issue with the strides.

File: numpy/_core/src/multiarray/multiarraymodule.c (hunk 1 above)
Comment (seberg) [reply numpy/_core/src/multiarray/multiarraymodule.c:3302]: Thanks for the update, about the strides, they really doen't matter, but it is a bit nicer to fix maybe.

I think your old logic of checking the `has_ref` on the common type makes a bit more sense actually?  since that is what we are arguing about being a "trivial copy"?

If anything, I was wondering about moving a:
```
int no_trivial_loop = has_ref || ((itemsize != 16) && (itemsize != 8) && (itemsize != 4) &&
                    (itemsize != 2) && (itemsize != 1))
```
to early on to reuse it.

In either case, this is good though!

**Review by seberg — APPROVED** [review]
Thanks for the follow-ups, I like them!
