### PR TITLE
BUG: test, fix matmul, dot for vector array with stride[i]=0

### LINKED ISSUE #12156: Numpy passes invalid arguments to DGEMV when stride = 0
When performing a `numpy.matmul` with a vector, whose `stride` is 0, Numpy will pass an invalid argument to the LAPACK function `DGEMV`. More specifically, the `incx` argument of `DGEMV` cannot be 0.

### Reproducing code example:

```python
import numpy as np
a = np.array([[1., 1., 1., 1.], [1., 1., 1., 1.]])
b = np.broadcast_to(1., (4, 1))
np.matmul(a, b)
```

### Error message:

I tested it on 2 platforms (see the version section below).

On 1.15.2 Linux:

```
Traceback (most recent call last):
  File "tmp.py", line 4, in <module>
    np.matmul(a, b)
ValueError: On entry to DGEMV parameter number 8 had an illegal value
```

On 1.13.3 Windows:

```
 ** On entry to DGEMV  parameter number  8 had an illegal value
```

### Numpy/Python version information:

```
1.15.2 3.6.6 (default, Sep 12 2018, 18:26:19)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
```

and

```
1.13.3 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
```

### PR DESCRIPTION
**Pull request by mattip**
Fixes #12156. 

- Test added for 0-strided vector array
- Fixed new matmul logic to detect this condition by adding logic from assert inside `@typ@_gemv` to checks before calling `@typ@_gemv
- Fixed old dot logic to check for this condition in helper function
- Verified (by using gdb) that `gemv` is used where possible in `matmul`, and that copying is done as necessary in `dot`

### CODE REVIEW

File: numpy/core/src/common/cblasfuncs.c [hunk 1]
```diff
@@ -196,6 +197,9 @@ _bad_strides(PyArrayObject *ap)
         if ((strides[i] < 0) || (strides[i] % itemsize) != 0) {
             return 1;
         }
+        if ((strides[i] == 0 && dims[i] >1)) {
```
Comment (charris) [inline numpy/core/src/common/cblasfuncs.c]:
```suggestion
        if ((strides[i] == 0 && dims[i] > 1)) {
```

File: numpy/core/tests/test_multiarray.py [hunk 2]
```diff
@@ -2713,6 +2713,20 @@ def test_arr_mult(self, func):
             assert_equal(func(edf, edf.T), eddtf)
             assert_equal(func(edf.T, edf), edtdf)
 
+    @pytest.mark.parametrize('func', (np.dot, np.matmul))
+    def test_no_dgemv(self, func):
```
Comment (charris) [inline numpy/core/tests/test_multiarray.py]: Any reason to just check doubles?

Comment (charris) [reply numpy/core/tests/test_multiarray.py]: I'm thinking `f, d, c, z`, maybe separately for the two inputs. That way can also test the promotion. The advantage is that if the code gets refactored and introduces new code paths. Maybe those cases are already tested somewhere for the usual case?

File: numpy/core/src/common/cblasfuncs.c [hunk 3]
```diff
@@ -188,6 +188,7 @@ _bad_strides(PyArrayObject *ap)
     int itemsize = PyArray_ITEMSIZE(ap);
     int i, N=PyArray_NDIM(ap);
     npy_intp *strides = PyArray_STRIDES(ap);
+    npy_intp *dims = PyArray_DIMS(ap);
 
     if (((npy_intp)(PyArray_DATA(ap)) % itemsize) != 0) {
```
Comment (eric-wieser) [inline numpy/core/src/common/cblasfuncs.c]: Do we need this condition for matmul too? Or does the ufunc machinery ensure this?

File: numpy/core/tests/test_multiarray.py (hunk 2 above)
Comment (mattip) [reply numpy/core/tests/test_multiarray.py]: It is difficult to test blas functionality
- we have no external indication whether blas is used or not
- we do not get a warning/error if blas is called incorrectly (the `xerblas` mechanism is not working correctly). Perhaps it is worthwhile opening an issue for this but the working assumption is we cannot call blas incorrectly.

I determined that my fix works by manually setting a breakpoint at the blas calls and verifying, via `runtests.py -vv` and manually examining dimensions and strides that the calls were correct, and by noticing that xerblas error messages do not appear on stderr.

While it would be simple to add the other blas-able cases, what would the expected error vs. non-error output be? It is not clear to me there is added value in quadrupling the test.

File: numpy/core/src/common/cblasfuncs.c (hunk 3 above)
Comment (eric-wieser) [reply numpy/core/src/common/cblasfuncs.c]: I mean specifically the `((npy_intp)(PyArray_DATA(ap)) % itemsize) != 0` condition

Comment (mattip) [reply numpy/core/src/common/cblasfuncs.c]: The ufunc flag NPY_ITER_ALIGNED handles this for us. I added a test and checked that 
- the unaligned ndarrays are copied in [`nditer_const.c:2914`](https://github.com/numpy/numpy/blob/v1.15.4/numpy/core/src/multiarray/nditer_constr.c#L2915) and
- when entering `@typ@_matmul` pointers are always aligned

File: numpy/core/tests/test_multiarray.py (hunk 2 above)
Comment (mattip) [reply numpy/core/tests/test_multiarray.py]: Since I was expanding the tests anyway I added the other BLAS dtypes and `int` as well for good measure.

Comment (mattip) [reply numpy/core/tests/test_multiarray.py]: > I added the other BLAS dtypes and `int` as well for good measure

I see you requested **combinations** of dtypes. This is covered in other tests of the ufunc machinery, that it promotes and copies input where needed.

**Comment by mattip** [comment]
Windows Python 3.7 32 bit build is failing when using `gemv` for `complex64`. I don't understand the failure, and why other 32 bit platforms do not fail:
```
self = <numpy.core.tests.test_multiarray.TestMethods object at 0x0D0C1630>
2018-12-07T08:19:50.7125582Z func = <ufunc 'matmul'>, dtype = 'F'
2018-12-07T08:19:50.7125616Z 
2018-12-07T08:19:50.7125667Z     @pytest.mark.parametrize('func', (np.dot, np.matmul))
2018-12-07T08:19:50.7126208Z     @pytest.mark.parametrize('dtype', 'ifdFD')
2018-12-07T08:19:50.7126804Z     def test_no_dgemv(self, func, dtype):
2018-12-07T08:19:50.7127050Z         # check vector arg for contiguous before gemv
2018-12-07T08:19:50.7127203Z         # gh-12156
2018-12-07T08:19:50.7127623Z         a = np.arange(8.0, dtype=dtype).reshape(2, 4)
2018-12-07T08:19:50.7127845Z         b = np.broadcast_to(1., (4, 1))
2018-12-07T08:19:50.7128281Z         ret1 = func(a, b)
2018-12-07T08:19:50.7129082Z         ret2 = func(a, b.copy())
2018-12-07T08:19:50.7129236Z         assert_equal(ret1, ret2)
2018-12-07T08:19:50.7129461Z     
2018-12-07T08:19:50.7129721Z         ret1 = func(b.T, a.T)
2018-12-07T08:19:50.7130045Z         ret2 = func(b.T.copy(), a.T)
2018-12-07T08:19:50.7130444Z         assert_equal(ret1, ret2)
2018-12-07T08:19:50.7130665Z     
2018-12-07T08:19:50.7131076Z         # check for unaligned data
2018-12-07T08:19:50.7131452Z         dt = np.dtype(dtype)
2018-12-07T08:19:50.7132169Z         a = np.zeros(8 * dt.itemsize // 2 + 1, dtype='int16')[1:].view(dtype)
2018-12-07T08:19:50.7132497Z         a = a.reshape(2, 4)
2018-12-07T08:19:50.7132760Z         b = a[0]
2018-12-07T08:19:50.7133483Z         # make sure it is not aligned
2018-12-07T08:19:50.7133879Z         assert_(a.__array_interface__['data'][0] % dt.itemsize != 0)
2018-12-07T08:19:50.7134239Z         ret1 = func(a, b)
2018-12-07T08:19:50.7134999Z >       ret2 = func(a.copy(), b.copy())
2018-12-07T08:19:50.7135319Z E       RuntimeWarning: invalid value encountered in matmul
2018-12-07T08:19:50.7135488Z 
2018-12-07T08:19:50.7135841Z a          = array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
2018-12-07T08:19:50.7136034Z        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]], dtype=complex64)
2018-12-07T08:19:50.7136848Z b          = array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j], dtype=complex64)
2018-12-07T08:19:50.7137141Z dt         = dtype('complex64')
2018-12-07T08:19:50.7137451Z dtype      = 'F'
2018-12-07T08:19:50.7137809Z func       = <ufunc 'matmul'>
2018-12-07T08:19:50.7138322Z ret1       = array([0.+0.j, 0.+0.j], dtype=complex64)
2018-12-07T08:19:50.7138798Z ret2       = array([[ 6.+0.j, 22.+0.j]])
2018-12-07T08:19:50.7139740Z self       = <numpy.core.tests.test_multiarray.TestMethods object at 0x0D0C1630>
```

**Comment by charris** [comment]
I'm rerunning the azure tests, that warning has turned up (once) before and I was thinking something wasn't properly suppressing warnings and they were slipping through from some other spot. We will see if it  is repeatable.

**Comment by charris** [comment]
Here is the other test failure: https://dev.azure.com/numpy/numpy/_build/results?buildId=1133. Different test, Same error, 32 bits, matmul. Are we testing matmul with invalid values anywhere?

**Comment by tylerjereddy** [comment]
The other failure cited is Python 3.6 vs. 3.7 reported here, but both indeed involve matmul with both operands `complex64` it seems.

32-bit Linux Azure is likely using an older openblas backend for now, since it uses apt-get to install the libs (until I sync that with wheels approach), so that may explain Linux vs. Win here.

**Comment by charris** [comment]
I'm going to put this in as I suspect that the problem isn't directly due to matmul and looks difficult to pin down. Note that the 32 bit code is likely compiled for a different FPU than the 64 bit code. The warning itself looks harmless, if annoying.

Thanks Matti.
