### PR TITLE
BUG: numpy.einsum indexing arrays now accept numpy int type

### LINKED ISSUE #15961: Einsum indexing very fragile, because it tests for int (and int64 is not int)
The index arrays for einsum do not accept the output of any numpy array, because these datatypes cannot be ints (see #2951; #12322). The test should be modified to accept numpy ints, because converting the datatype to 'int' explicitly is counter-intuitive and unnecessary.

Though easy to circumvent, this will incur a lot of unnecessary debugging time, as it appears to break abstraction boundaries, has strange interactions with `tolist`, and indices that work in test environments fail when constructed programatically.

### Reproducing code example:

```python
import numpy as np
X = np.arange(9).reshape(3,3)

# each of these results in an identical list [0] as far as equality test is concerned 
idx1 = [0]                # list[ int ] 
idx2 = np.unique(idx1)    # np.array [int64]
idx3 = idx2.tolist()      # list [int]
idx3 = list(idx2)         # list [int64]

np.einsum(X, [0], idx1 ) # succeeds
np.einsum(X, [0], idx2 ) # fails
np.einsum(X, [0], idx3 ) # succeeds
np.einsum(X, [0], idx4 ) # fails

```

### Error message:

ValueError: each subscript must be either an integer or an ellipsis

Full error message if `optimize_arg` is `False`:

```
<__array_function__ internals> in einsum(*args, **kwargs)

~/.local/lib/python3.6/site-packages/numpy/core/einsumfunc.py in einsum(*operands, **kwargs)
   1354     # If no optimization, run pure einsum
   1355     if optimize_arg is False:
-> 1356         return c_einsum(*operands, **kwargs)
   1357 
   1358     valid_einsum_kwargs = ['out', 'dtype', 'order', 'casting']

ValueError: each subscript must be either an integer or an ellipsis
```
Full error message when `optimize_arg` is `True`:
```
<__array_function__ internals> in einsum(*args, **kwargs)

~/.local/lib/python3.6/site-packages/numpy/core/einsumfunc.py in einsum(*operands, **kwargs)
   1377     # Build the contraction list and operand
   1378     operands, contraction_list = einsum_path(*operands, optimize=optimize_arg,
-> 1379                                              einsum_call=True)
   1380 
   1381     handle_out = False
```
### Numpy/Python version information:

1.17.3 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]

### PR DESCRIPTION
**Pull request by rlintott**
Fixes #15961.

All current tests pass. I didn't write any new tests for this though, but perhaps I should do that?

### CODE REVIEW

File: numpy/core/src/multiarray/multiarraymodule.c [hunk 1]
```diff
@@ -2459,46 +2458,48 @@ einsum_list_to_subscripts(PyObject *obj, char *subscripts, int subsize)
             subscripts[subindex++] = '.';
             ellipsis = 1;
         }
-        /* Subscript */
-        else if (PyInt_Check(item) || PyLong_Check(item)) {
-            long s = PyInt_AsLong(item);
-            npy_bool bad_input = 0;
+        else {
+            long s = PyLong_AsLong(item);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/multiarraymodule.c:2462]: What error message does this give if you pass a float? If it doesn't error at all, you might need to change to the following:
```suggestion
            Py_ssize s = PyNumber_Index(item);
```

Comment (rlintott) [reply numpy/core/src/multiarray/multiarraymodule.c]: You're right it didn't give an error on floats. I think I have fixed that now. Hopefully 

`item = PyNumber_Index(item);` 

is OK? Since it just modifies the object. I'm very new to the C Python API.

Comment (eric-wieser) [reply numpy/core/src/multiarray/multiarraymodule.c]: Oh, I guess I forgot the return type. I think we might have a helper function that does what we need here, perhaps `PyArray_IntAsIntp` or something similar.

Comment (seberg) [reply numpy/core/src/multiarray/multiarraymodule.c]: Yes, which is much the same as `PyNumber_AsSsize_t ` but rejects bools.

Comment (rlintott) [reply numpy/core/src/multiarray/multiarraymodule.c]: I have edited the function to use `PyArray_PyIntAsIntp` instead, which is what I believe you were referencing. It did used to accept bools before, but now it doesn't.

Comment (seberg) [reply numpy/core/src/multiarray/multiarraymodule.c]: Yeah, I am not quite sure. Doesn't feel quite right to switch over silently, but on the other hand it seems not like a much used corner and then a corner case of that.

Can you add those new tests in either case? They are necessary whether or not we let bools pass.

**Comment by rlintott** [comment]
Please let me know what you think of this new commit! I had to change `einsumfunc.py` as I did not realise there were two implementations until I started running tests. It does reject bools now. I also changed a valueerror to a typeerror as it seemed more appropriate (and it was causing my tests to fail)

File: numpy/core/tests/test_einsum.py [hunk 2]
```diff
@@ -93,6 +93,10 @@ def test_einsum_errors(self):
                 a = np.ones((3, 3, 4, 5, 6))
                 b = np.ones((3, 4, 5))
                 np.einsum('aabcb,abc', a, b)
+            
+            #do not accept bools in subscript list
```
Comment (eric-wieser) [inline numpy/core/tests/test_einsum.py:97]:
```suggestion
            # do not accept bools in subscript list
```
PEP8

File: numpy/core/tests/test_einsum.py [hunk 3]
```diff
@@ -274,6 +278,13 @@ def check_einsum_sums(self, dtype, do_opt=False):
             assert_equal(np.einsum(a, [0, 0], optimize=do_opt),
                          np.trace(a).astype(dtype))
 
+            #ticket #15961: should accept numpy int64 type in subscript list
```
Comment (eric-wieser) [inline numpy/core/tests/test_einsum.py:281]:
```suggestion
            # gh-15961: should accept numpy int64 type in subscript list
```
"Ticket" refers to a previous issue tracker

File: numpy/core/einsumfunc.py [hunk 4]
```diff
@@ -576,7 +577,7 @@ def _parse_einsum_input(operands):
             for s in sub:
                 if s is Ellipsis:
                     subscripts += "..."
-                elif isinstance(s, int):
+                elif isinstance(operator.index(s), int) and not isinstance(s, bool):
```
[the remark this answers is not in the document]
Comment (seberg) [reply numpy/core/einsumfunc.py:580]: yes, exposing the c converter for these privately seems fine to me. I am also OK with just accepting bools for now here, doing the same in C,,, Its auper important for indexing-like things, oherwise I still like it, but it seams not too important,

[the remark this answers is not in the document]
Comment (eric-wieser) [reply numpy/core/einsumfunc.py:580]: I'd also be ok with being inconsistent about accepting bools for now between C and python, and then fix that type of issue numpy-wide later.

File: numpy/core/einsumfunc.py [hunk 5]
```diff
@@ -590,11 +592,13 @@ def _parse_einsum_input(operands):
...
-                elif isinstance(operator.index(s), int) and not isinstance(s, bool):
-                    subscripts += einsum_symbols[s]
                 else:
-                    raise TypeError("For this input type lists must contain "
-                                    "either int or Ellipsis")
+                    try:
+                        s = operator.index(s)
+                    except TypeError as e:
+                        raise TypeError("For this input type lists must contain "
+                                        "either int or Ellipsis")
```
Comment (eric-wieser) [inline numpy/core/einsumfunc.py:600]:
```suggestion
                                        "either int or Ellipsis") from e
```

File: numpy/core/einsumfunc.py [hunk 6]
```diff
@@ -577,11 +577,13 @@ def _parse_einsum_input(operands):
...
```
Comment (eric-wieser) [inline numpy/core/einsumfunc.py:585]:
```suggestion
                                        "either int or Ellipsis") from e
```

File: numpy/core/tests/test_einsum.py [hunk 7]
```diff
@@ -274,6 +274,13 @@ def check_einsum_sums(self, dtype, do_opt=False):
             assert_equal(np.einsum(a, [0, 0], optimize=do_opt),
                          np.trace(a).astype(dtype))
 
+            # gh-15961: should accept numpy int64 type in subscript list
+            np_array = np.asarray([0, 0])
+            assert_equal(np.einsum(a, np_array, optimize=do_opt),
+                         np.trace(a).astype(dtype))
+            assert_equal(np.einsum(a, list(np_array), optimize=do_opt),
```
Comment (anirudh2290) [inline numpy/core/tests/test_einsum.py:281]: Are we testing for other opt_types for np.int64 and optimize values which are not False. This may be useful to trigger einsum_path code path and ensure _parse_einsum_input is correct.

**Review by anirudh2290 — COMMENTED** [review]
Thanks for working on this, overall looks good !

**Comment by charris** [comment]
Could you add a release note for this under `Improvements`.

File: numpy/core/tests/test_einsum.py (hunk 7 above)
Comment (rlintott) [reply numpy/core/tests/test_einsum.py:281]: Sorry, what do you mean by other opt_types? I am very new to working on numpy

But it does test for both optimize=False and optimize=True, and goes through both the C and Python implementation if that is what you mean

Comment (anirudh2290) [reply numpy/core/tests/test_einsum.py:281]: apologies for the delay in reply, what i meant is adding a `self.check_einsum_sums('i8', True)` for `test_einsum_sums_int64`. by other opt_types i mean other options for optimize (False, True, greedy, optimal) (likely False, True, check may suffice).

Comment (rlintott) [reply numpy/core/tests/test_einsum.py:281]: Ahh, I think I see. It seems like `_parse_einsum_input` is called in all cases if optimization is turned on, so I think the test coverage is complete. I have put the subscript list test in `self.check_einsum_sums` itself so that it is tested with all dtypes and opt_types that were being tested before. Hopefully this is OK

Comment (anirudh2290) [reply numpy/core/tests/test_einsum.py:281]: Yes, on a second look I think this test handles other values for optimize and I think it should be fine.

**Review by anirudh2290 — APPROVED** [review]

File: numpy/core/src/multiarray/multiarraymodule.c [hunk 8]
```diff
@@ -2459,46 +2458,49 @@ einsum_list_to_subscripts(PyObject *obj, char *subscripts, int subsize)
...
             ellipsis = 1;
         }
-        /* Subscript */
-        else if (PyInt_Check(item) || PyLong_Check(item)) {
-            long s = PyInt_AsLong(item);
-            npy_bool bad_input = 0;
+        else {
+            npy_intp s = PyArray_PyIntAsIntp(item);
+            /* Subscript */
+            if (!PyErr_Occurred()) {
```
Comment (seberg) [inline numpy/core/src/multiarray/multiarraymodule.c:2464]:
```suggestion
            if (!error_converting(s)) {
```
A bit of a micro optimization, but its good to use generally and the more places use it, the more likely we don't forget it... (These functions return -1 on failure, so checking that first skips the `PyErr_Occured()` check in most cases).

Anyway, only glanced over but Anirudh and Eric had a look, so planning on merging it later. (I will apply this change myself).

File: numpy/core/src/multiarray/multiarraymodule.c [hunk 9]
```diff
@@ -2459,46 +2458,49 @@ einsum_list_to_subscripts(PyObject *obj, char *subscripts, int subsize)
...
-            else if (s < 26) {
-                subscripts[subindex++] = 'A' + (char)s;
-            }
-            else if (s < 2*26) {
-                subscripts[subindex++] = 'a' + (char)s - 26;
-            }
-            else {
-                bad_input = 1;
-            }
+                if ( s < 0 ) {
```
Comment (seberg) [inline numpy/core/src/multiarray/multiarraymodule.c:2474]:
```suggestion
                if (s < 0) {
```
Ah, was there before... but I think I will commit it anyway...

File: numpy/core/src/multiarray/multiarraymodule.c (hunk 8 above)
Comment (seberg) [reply numpy/core/src/multiarray/multiarraymodule.c:2464]: It might be a bit nicer to move the error into this if rather than the opposite way and then keep the rest unindented (as it was). I also feel its a bit more standard pattern handle the error immediately.

**Review by seberg — COMMENTED** [review]
Just some nits, I may just commit those suggestions and merge in a day or so. If you have some time, happy if you finish it off though (and please see if moving the error creation looks better)!

**Comment by seberg** [comment]
Thanks Ryan, lets put it in before I wonder if it was nicer before ;).
