### PR TITLE
BUG,DEP: Make `scalar.__round__()` behave like pythons round

### LINKED ISSUE #15297: Output type of round is inconsistent with python built-in
[Based on official python doc](https://docs.python.org/3/library/functions.html#round), the output of `round` function is integer when ndigits is omitted. However, numpy does not follow this rule, and the output of rounded numpy still is a float. I think this behavior cause bugs!

### Reproducing code example:

```python
>>> for x in np.linspace(0,1,5):
...     print(round(x * 5.))
... 
0.0
1.0
2.0
4.0
5.0
>>> for x in map(float,np.linspace(0,1,5)):
...     print(round(x * 5.))
... 
0
1
2
4
5
```

### Numpy/Python version information:
1.18.1 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609]

### PR DESCRIPTION
**Pull request by hameerabbasi**
Fixes #15297.

### CODE REVIEW

**Comment by hameerabbasi** [comment]
cc @mattip for review.

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 1]
```diff
@@ -1549,6 +1549,16 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
 }
 /**end repeat**/
 
+static PyObject *
+dunder_round(PyObject *self, PyObject *args, PyObject *kwds)
+{
+    PyObject *obj = gentype_round(self, args, kwds);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]: Does this upcast int to float,  losing precision?

Comment (hameerabbasi) [reply numpy/core/src/multiarray/scalartypes.c.src]: No, it's equivalent to `scalar.round`.

```python
>>> type(np.int64(5).round())
<class 'numpy.int64'>
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 2]
```diff
@@ -2058,7 +2068,7 @@ static PyMethodDef gentype_methods[] = {
         METH_VARARGS | METH_KEYWORDS, NULL},
     /* Hook for the round() builtin */
     {"__round__",
-        (PyCFunction)gentype_round,
+        (PyCFunction)dunder_round,
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]:
```suggestion
        (PyCFunction)gentyp_dunder_round,
```
Or perhaps
```suggestion
        (PyCFunction)gentype___round__,
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 3]
```diff
@@ -1549,6 +1549,16 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
 /**end repeat**/
 
+static PyObject *
+dunder_round(PyObject *self, PyObject *args, PyObject *kwds)
+{
+    PyObject *obj = gentype_round(self, args, kwds);
+    if (obj == NULL) return NULL;
+    PyObject * tup = PyTuple_Pack(1, obj);
+    if (tup == NULL) return NULL;
+    return PyObject_Call((PyObject *)(&PyLong_Type), tup, NULL);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]:
```suggestion
    return PyObject_CallObjAegs((PyObject *)(&PyLong_Type), obj, NULL);
```

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 2 above)
Comment (hameerabbasi) [reply numpy/core/src/multiarray/scalartypes.c.src]: It's not generated though -- Would that still be appropriate?

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 3 above)
Comment (hameerabbasi) [reply numpy/core/src/multiarray/scalartypes.c.src]: Thanks, wasn't aware of this.

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 2 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/scalartypes.c.src]: `gentype_something` refers to `np.generic.something` in this file

File: numpy/core/tests/test_numeric.py [hunk 4]
```diff
@@ -140,6 +140,12 @@ def test_round(self):
         tgt = [1.6, 72.5, 6.4, 3.2]
         assert_equal(np.around(arr, decimals=1), tgt)
 
+        s = np.float64(1.)
+        assert_(isinstance(round(s), int))
+        assert_(isinstance(s.round(), np.generic))
```
Comment (eric-wieser) [inline numpy/core/tests/test_numeric.py]: Let's be precise here
```suggestion
        assert_(isinstance(s.round(), np.float64))
```

File: numpy/core/tests/test_numeric.py [hunk 5]
```diff
@@ -140,6 +140,12 @@ def test_round(self):
...
+        assert_equal(s.round(), 1.)
+        assert_equal(round(s), 1)
+
```
Comment (eric-wieser) [inline numpy/core/tests/test_numeric.py]: Worth a test that precision is not lost I think
```suggestion
        s = np.uint64(2**64-1)
        assert_equal(round(s), 2**64-1)
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 6]
```diff
@@ -1549,6 +1549,14 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
 }
 /**end repeat**/
 
+static PyObject *
+dunder_round(PyObject *self, PyObject *args, PyObject *kwds)
+{
+    PyObject *obj = gentype_round(self, args, kwds);
+    if (obj == NULL) return NULL;
+    return PyObject_CallFunctionObjArgs((PyObject *)(&PyLong_Type), obj, NULL);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]:
```suggestion
    return PyNumber_Long(obj);
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 7]
```diff
@@ -1549,6 +1549,14 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
 }
 /**end repeat**/
 
+static PyObject *
+dunder_round(PyObject *self, PyObject *args, PyObject *kwds)
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]: What do `args` and `kwds` hold here?

Comment (hameerabbasi) [reply numpy/core/src/multiarray/scalartypes.c.src]: https://docs.python.org/3/library/functions.html#round

Probably `ndigits`. I should check that it's not present before passing it on.

File: doc/source/release/1.19.0-notes.rst [hunk 8]
```diff
@@ -4,3 +4,10 @@
 NumPy 1.19.0 Release Notes
 ==========================
 
+Compatibility notes
+===================
+
+- Output of the ``__round__`` dunder method and consequently the Python
+  built-in ``round`` has been changed to be a Python ``int`` to be consistent
+  with calling it on Python ``float`` objects. Previously, it would return
+  a scalar of the ``dtype`` that was passed in.
```
Comment (eric-wieser) [inline doc/source/release/1.19.0-notes.rst]: This should go in `doc/release/upcoming_changes`

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 7 above)
Comment (hameerabbasi) [reply numpy/core/src/multiarray/scalartypes.c.src]: I changed this to make it consistent with Python, too. It now emits a `float` with the second argument provided, even if it's `0`.

File: numpy/core/tests/test_numeric.py [hunk 9]
```diff
@@ -140,6 +140,20 @@ def test_round(self):
...
+        assert_(isinstance(s.round(), np.float64))
+        assert_equal(s.round(), 1.)
+        assert_equal(round(s), 1)
+
+        s = np.uint64(2**64-1)
+        assert_equal(round(s), 2**64-1)
+
+        f = np.float64(5.1 * 10**73)
+        assert_(isinstance(round(f, -73), float))
+        assert_allclose(round(f, -73), 5.0 * 10**73)
```
Comment (eric-wieser) [inline numpy/core/tests/test_numeric.py]: Perhaps better to just test directly against the python behavior
```suggestion
        assert_allclose(round(f, -73), round(float(f), -73))
```

Comment (hameerabbasi) [reply numpy/core/tests/test_numeric.py]: Doesn't always work unfortunately.

```python
>>> round(f, -75) == round(float(f), -73)
False
```

We would need to change the implementation significantly, depending on the dtype.

Comment (eric-wieser) [reply numpy/core/tests/test_numeric.py]: Did you try using 73 on both sides and not just on the right?

Comment (hameerabbasi) [reply numpy/core/tests/test_numeric.py]:
```python
>>> round(f, -73) == round(float(f), -73)
False
```

Comment (eric-wieser) [reply numpy/core/tests/test_numeric.py]: Can you add an `xfail` test that checks for consistency against python then?

Comment (hameerabbasi) [reply numpy/core/tests/test_numeric.py]: Done.

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 10]
```diff
@@ -1549,6 +1549,19 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
+gentype_dunder_round(PyObject *self, PyObject *args, PyObject *kwds)
+{
+    PyObject *obj = gentype_round(self, args, kwds);
+    if (obj == NULL) return NULL;
+
+    if (PyTuple_Size(args) == 0 &&
+        (kwds == NULL || PyDict_Size(kwds) == 0))
+        return PyNumber_Long(obj);
+    else
+        return PyNumber_Float(obj);
```
Comment (seberg) [inline numpy/core/src/multiarray/scalartypes.c.src]: This will downcast a `float128`, etc. which is incorrect. The result should be either a python integer or the old type. The second branch should thus not do anything

Furthermore, you need to go to a python integer for all of the following incarnations:
  * `round(scalar)` (done here)
  * `round(scalar, None)`
  * `round(scalar, ndigits=None)`

On the nitpicking front: Please add all braces, NumPy never leaves them out (I would probably be OK when it is on one line if someone wants to argue for it, but we currently are pretty strict on that style).

File: doc/release/upcoming_changes/15840.compatibility.rst [hunk 11]
```diff
@@ -0,0 +1,7 @@
+Change output of ``__round__`` to be consistent with Python
+-----------------------------------------------------------
+
+Output of the ``__round__`` dunder method and consequently the Python
+built-in ``round`` has been changed to be a Python ``int`` to be consistent
+with calling it on Python ``float`` objects. Previously, it would return
+a scalar of the ``dtype`` that was passed in.
```
Comment (seberg) [inline doc/release/upcoming_changes/15840.compatibility.rst]: Could try and rephrase it to include the `default` (integral) rounding has been changed... But, it is probably fine and I am not quite sure how to phrase it better right now. The "default" word is the only idea I have right now.

**Review by seberg — COMMENTED** [review]
Thanks for getting this going! Looks pretty good, actually getting it right with `None` being passed could be slightly annoying (i.e. require parsing – could be fast pathed, although it may be that it does not matter: parsing no arguments is pretty fast).

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 10 above)
Comment (hameerabbasi) [reply numpy/core/src/multiarray/scalartypes.c.src]: > This will downcast a float128, etc. which is incorrect. The result should be either a python integer or the old type. The second branch should thus not do anything

This would produce very inconsistent results: Python scalars in one case and NumPy scalars in another case. I'd prefer to stick with one, either one is fine by me.

**Comment by hameerabbasi** [comment]
> Looks pretty good, actually getting it right with None being passed could be slightly annoying (i.e. require parsing – could be fast pathed, although it may be that it does not matter: parsing no arguments is pretty fast).

Yes, this was, indeed, annoying. The error checking and `ndigits` for `round` vs `decimals` for `np.round` made it impossible to pass the same arguments forward, so I had to handle that corner case, and that of course, introduced a lot of error handling.

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 12]
```diff
@@ -1549,6 +1549,61 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
 
+static PyObject *
+gentype_dunder_round(PyObject *self, PyObject *args, PyObject *kwds)
+{
+    static char *kwlist[] = {"ndigits", NULL};
+    PyObject *ndigits = NULL;
+    PyObject *obj = NULL;
+    PyObject *tup = NULL;
+    PyObject *ret = NULL;
+    if (!PyArg_ParseTupleAndKeywords(args, kwds, "|O", kwlist, &ndigits))
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]:
```suggestion
    if (!PyArg_ParseTupleAndKeywords(args, kwds, "|O:__round__", kwlist, &ndigits))
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 13]
```diff
@@ -1549,6 +1549,61 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
+    }
+    
+    if (ndigits == Py_None || ndigits == NULL)
+    {
+        tup = PyTuple_Pack(0);
+    }
+    else
+    {
+        tup = PyTuple_Pack(1, ndigits);
+    }
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]: Style we use is normally:
```suggestion
    if (ndigits == Py_None || ndigits == NULL) {
        tup = PyTuple_Pack(0);
    }
    else {
        tup = PyTuple_Pack(1, ndigits);
    }
```
Applies elsewhere too

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 14]
```diff
@@ -1549,6 +1549,61 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
+    if (tup == NULL)
+    {
+        goto fail;
+    }
+
+    obj = gentype_round(self, tup, NULL);
+    if (obj == NULL)
+    {
+        goto fail;
+    };
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]:
```suggestion
    }
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 15]
```diff
@@ -1549,6 +1549,61 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
 }
 /**end repeat**/
 
+static PyObject *
+gentype_dunder_round(PyObject *self, PyObject *args, PyObject *kwds)
+{
+    static char *kwlist[] = {"ndigits", NULL};
+    PyObject *ndigits = NULL;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]: Why not initialize this to `Py_None`? Then you can remove the `NULL` checks below.

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 16]
```diff
@@ -1549,6 +1549,61 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
+    PyObject *obj = NULL;
+    PyObject *tup = NULL;
+    PyObject *ret = NULL;
+    if (!PyArg_ParseTupleAndKeywords(args, kwds, "|O", kwlist, &ndigits))
+    {
+        goto fail;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]:
```suggestion
        return NULL;
```
nothing to clean up here

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 17]
```diff
@@ -1549,6 +1549,61 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
+    }
+    else
+    {
+        tup = PyTuple_Pack(1, ndigits);
+    }
+
+    if (tup == NULL)
+    {
+        goto fail;
+    }
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]:
```suggestion
    if (tup == NULL)
    {
        return NULL;
    }
```
also nothing to clean up here

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 18]
```diff
@@ -1549,6 +1549,61 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
+
+    obj = gentype_round(self, tup, NULL);
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]: I think you're leaking `tup` here:
```suggestion
    obj = gentype_round(self, tup, NULL);
    Py_DECREF(tup);
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 19]
```diff
@@ -1549,6 +1549,61 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
+    };
+
+    if (ndigits == Py_None || ndigits == NULL)
+    {
+        ret = PyNumber_Long(obj);
+    }
+    else
+    {
+        ret = PyNumber_Float(obj);
+    }
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]:
```suggestion
    }
    Py_DECREF(obj);
```

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 15 above)
Comment (hameerabbasi) [reply numpy/core/src/multiarray/scalartypes.c.src]: Will that cause a `Py_DECREF` inside `PyArg_ParseTupleAndKeywords`?

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 20]
```diff
@@ -1549,6 +1549,61 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
+        goto fail;
+    }
+
+    return ret;
+
+    fail:
+    Py_XDECREF(tup);
+    Py_XDECREF(obj);
+    Py_XDECREF(ret);
+    return NULL;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]: Nothing left to clean up
```suggestion
    return ret;
```

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 15 above)
Comment (eric-wieser) [reply numpy/core/src/multiarray/scalartypes.c.src]: No, `PyArg_ParseTupleAndKeywords` does not look at the values of the passed pointers, it only sets them.

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 21]
```diff
@@ -1549,6 +1549,50 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
+static PyObject *
+gentype_dunder_round(PyObject *self, PyObject *args, PyObject *kwds)
+{
+    static char *kwlist[] = {"ndigits", NULL};
+    PyObject *ndigits = Py_None;
+    PyObject *obj = NULL;
+    PyObject *tup = NULL;
+    PyObject *ret = NULL;
+    if (!PyArg_ParseTupleAndKeywords(args, kwds, "|O:__round__", kwlist, &ndigits))
+    {
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]:
```suggestion
    if (!PyArg_ParseTupleAndKeywords(args, kwds, "|O:__round__", kwlist, &ndigits)) {
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 22]
```diff
@@ -1549,6 +1549,52 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
+        return NULL;
+    }
+    
+    if (ndigits == Py_None || ndigits == NULL)
+    {
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]:
```suggestion
    if (ndigits == Py_None) {
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 23]
```diff
@@ -1549,6 +1549,52 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
+        tup = PyTuple_Pack(0);
+    }
+    else {
+        tup = PyTuple_Pack(1, ndigits);
+    }
+
+    if (tup == NULL)
+    {
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]:
```suggestion
    if (tup == NULL) {
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 24]
```diff
@@ -1549,6 +1549,52 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
+        return NULL;
+    }
+
+    obj = gentype_round(self, tup, NULL);
+    Py_DECREF(tup);
+    tup = NULL;
+    if (obj == NULL)
+    {
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]:
```suggestion
    if (obj == NULL) {
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 25]
```diff
@@ -1549,6 +1549,52 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
+        return NULL;
+    }
+
+    if (ndigits == Py_None || ndigits == NULL)
+    {
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]:
```suggestion
    if (ndigits == Py_None || ndigits == NULL)
    {
```
```suggestion
    if (ndigits == Py_None) {
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 26]
```diff
@@ -1549,6 +1549,47 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
+        tup = PyTuple_Pack(1, ndigits);
+    }
+
+    if (tup == NULL) {
+        return NULL;
+    }
+
+    obj = gentype_round(self, tup, NULL);
+    Py_DECREF(tup);
+    tup = NULL;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]:
```suggestion
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 27]
```diff
@@ -1549,6 +1549,47 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
 }
 /**end repeat**/
 
+static PyObject *
+gentype_dunder_round(PyObject *self, PyObject *args, PyObject *kwds)
+{
+    static char *kwlist[] = {"ndigits", NULL};
+    PyObject *ndigits = Py_None;
+    PyObject *obj = NULL;
+    PyObject *tup = NULL;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]: Nit:: move this to line 1563 and remove the = NULL

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 28]
```diff
@@ -1549,6 +1549,46 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
 }
 /**end repeat**/
 
+static PyObject *
+gentype_dunder_round(PyObject *self, PyObject *args, PyObject *kwds)
+{
+    static char *kwlist[] = {"ndigits", NULL};
+    PyObject *ndigits = Py_None;
+    PyObject *obj = NULL;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]: Nit: move to line 1575

File: .gitignore [hunk 29]
```diff
@@ -125,6 +125,7 @@ numpy/core/include/numpy/multiarray_api.txt
 numpy/core/include/numpy/ufunc_api.txt
 numpy/core/lib/
 numpy/core/src/common/npy_binsearch.h
+numpy/core/src/common/npy_cpu_features.c
```
Comment (eric-wieser) [inline .gitignore]: Doesn't really belong in this PR.

**Review by eric-wieser — DISMISSED** [review]

File: doc/release/upcoming_changes/15840.compatibility.rst [hunk 30]
```diff
@@ -0,0 +1,7 @@
+Change output of ``__round__`` to be consistent with Python
```
Comment (eric-wieser) [inline doc/release/upcoming_changes/15840.compatibility.rst]:
```suggestion
Change output of ``__round__`` on scalars to be consistent with Python
```

File: .gitignore (hunk 29 above)
Comment (hameerabbasi) [reply .gitignore]: Should I break it out into a separate commit?

File: doc/release/upcoming_changes/15840.compatibility.rst [hunk 31]
```diff
@@ -0,0 +1,7 @@
...
+-----------------------------------------------------------
+
+Output of the ``__round__`` dunder method and consequently the Python
+built-in ``round`` has been changed to be a Python ``int`` to be consistent
```
Comment (eric-wieser) [inline doc/release/upcoming_changes/15840.compatibility.rst]:
```suggestion
built-in `round` has been changed to be a Python ``int`` to be consistent
```
Should result in a link

File: .gitignore (hunk 29 above)
Comment (eric-wieser) [reply .gitignore]: Yeah, that sounds good - can keep it in the same PR for simplicity.

Comment (mattip) [reply .gitignore]: why is this needed? That file (and some of the others here) should be generated in the `build/` directory, not in the main directory

File: doc/release/upcoming_changes/15840.compatibility.rst (hunk 30 above)
Comment (mattip) [reply doc/release/upcoming_changes/15840.compatibility.rst]: 80 column wrapping ...

File: .gitignore (hunk 29 above)
Comment (hameerabbasi) [reply .gitignore]: When you do `python setup.py develop` for local testing it creates that file in this directory.

File: doc/release/upcoming_changes/15840.compatibility.rst (hunk 30 above)
Comment (hameerabbasi) [reply doc/release/upcoming_changes/15840.compatibility.rst]: It's 71 columns for me.

Comment (mattip) [reply doc/release/upcoming_changes/15840.compatibility.rst]: ok, thanks

File: numpy/core/src/multiarray/scalartypes.c.src (hunk 10 above)
Comment (seberg) [reply numpy/core/src/multiarray/scalartypes.c.src]: Sorry, but to be clear, I do not think it is inconsistent result is is simply the *correct* result. `round` must be able to be a no-op given enough precision! The behaviour is only special for "round to integer" (even there I think it would be fine to return a non-python integer in principle, but python integers are awesome. Maybe I should have put this example immediately:
```
import decimal
round(decimal.Decimal("3.14"), 0)
# Decimal("3")
```
Everything else will basically destroy any precision we have.

Another thing we may have to think about are complex numbers, `round` is not defined for python complex, but we do define it. Maybe we should not implement `__round__`.

Comment (hameerabbasi) [reply numpy/core/src/multiarray/scalartypes.c.src]: We already implement it, removing it would be a huge break.

Comment (seberg) [reply numpy/core/src/multiarray/scalartypes.c.src]: Fair point about complex. We would have to deprecate the `dnigits=None` version. This now still adds the cast to integer, which for NumPy scalars, will give a warning and discard the imaginary part, while it gave a "reasonable" result before.

Comment (hameerabbasi) [reply numpy/core/src/multiarray/scalartypes.c.src]: I don't think a deprecation is necessary given this is the builtin `round` and not `np.round`. I would be happy to move the `__round__` method to `np.integer` and `np.floating`, and remove it from all others, in another PR.

Comment (seberg) [reply numpy/core/src/multiarray/scalartypes.c.src]: I don't want to slow you down, but, we have to be clear on what we want here.

1. Return the original type if `ndigits` is given (not `None`)
2. This currently, in theory, breaks working complex code by losing the complex part of the number (with a warning). A Deprecation to get rid of the `ndigits=None`, or `__round__` completely seems actually be more gentle to me.
3. I am not quite sure if `round(integer_type)` should not just keep returning the original integer type.

We decided to be bold enough to switch over to a (python) integer result for the default round. And yes it is new, but new is still many years old. I do not think we have actually made the decisions on those three points (or maybe I am just not aware). And my feeling is:

1. Absolutely, I am -10 on anything that casts to `float`.
2. My gut feeling is just deprecating is probably simpler.
3. I think returning the original integer type is probably just as well or better.

Which means in my view it would make more sense to limit this PR to `np.floating` and follow up with "whatever to do with complex" rather than the other way around.

Comment (seberg) [reply numpy/core/src/multiarray/scalartypes.c.src]: OTOH, I am not sure about point 2. maybe just returning a Python integer (similar to an `__index__()` call) is just as well. I am not sure I care either way much. I think it would be OK to return something as long as it supports `__index__()` and is an `numbers.Integral` but maybe there is no reason for _not_ converting it to a python int.

Comment (hameerabbasi) [reply numpy/core/src/multiarray/scalartypes.c.src]:
```python
>>> round(5, 0)
5.0
```

So returning the original integer type would be a violation of the API. I'd be okay special-casing `np.inexact` to return the original type and also all others to return `np.float64`, but I'm unsure how I'd make that change.

Comment (seberg) [reply numpy/core/src/multiarray/scalartypes.c.src]: @hameerabbasi which python version are you using? On my python 3.7 and 3.8 that returns an integer, I think that must have been a bug in Python?

Comment (hameerabbasi) [reply numpy/core/src/multiarray/scalartypes.c.src]: Wait, you're right... I muscle-memory typed `python` without activating my environment, my bad.

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 32]
```diff
@@ -1549,6 +1549,45 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
+    PyObject *ret;
+    if (ndigits == Py_None) {
+        ret = PyNumber_Long(obj);
+    }
+    else {
+        return obj;
+    }
+    Py_DECREF(obj);
+
+    return ret;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]: It would make more sense to me to either put these lines in the `if` above, or move the line within the if down to here.

**Comment by seberg** [comment]
@eric-wieser do you have a quick feeling about `complex` numbers? I am not sure I like that they will return `int(complex_number) != complex_number` when the number is already an integral value (in both real and complex part). I.e. it also is a loss of precision of sorts, while right now it returns the unmodified number.
Since `int(complex_number)` is not really sensible, I think I would prefer to just directly go with a deprecation of the "round to int" implementation, or even deprecate `round` entirely.

**Comment by hameerabbasi** [comment]
I assume you're talking about this inconsistency:
```python
>>> import numpy as np
>>> round(complex(5))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: type complex doesn't define __round__ method
>>> round(np.complex128(5))
<stdin>:1: ComplexWarning: Casting complex values to real discards the imaginary part
5
```

**Comment by hameerabbasi** [comment]
> deprecate `round` entirely.

This would be hard, `round` would need to be moved down to the other scalr classes, as returning `NotImplemented` doesn't work currently:

```python
>>> class A:
...     def __round__(self):
...         return NotImplemented
...
>>> round(A())
NotImplemented
```

Which, to be fair, is a Python bug (as of 3.8.1).

**Comment by seberg** [comment]
I think we should just raise an `TypeError` manually, or actually not implement it. We already raise a TypeError for types such as `void`. Now we could limit that to the "integer result" round, not sure that makes sense though.

What truly bothers me is the fact that we would start *dropping* the imaginary part. And yes, one solution is to deprecate `round` entirely for complex and bring it in line with Python. We could add the information to the error message that `np.round` is defined and does component-wise rounding.

**Comment by seberg** [comment]
I do not think it is a Python bug, `NotImplemented` is really only be meant to be used for `binary` operators to indicate that the operation should be deferred to the other operand.

**Comment by hameerabbasi** [comment]
> Now we could limit that to the "integer result" round, not sure that makes sense though.

It doesn't, `complex` straight-up _doesn't implement_ `__round__`. I'd be okay raising a `TypeError`, but how would I check for "self is complex" in NumPy's C-API?

**Comment by seberg** [comment]
Well, we could convert the `gentype` round into a general error (first deprecation warning before returning a successful result), and then add `round` manually to `floating` and `integer` for example? Its all a bit messy, but that should work (I do not know immediately whether those define actual structs on their own, we can just as well add it to all float and integer scalars manually).

There is also a `PyArray_IsScalar` macro though.

**Comment by eric-wieser** [comment]
> Well, we could convert the `gentype` round into a general error (first deprecation warning before returning a successful result), and then add `round` manually to `floating` and `integer` for example?

That sounds sensible to me. You could even add the deprecation directly to `complexfloating`, and remove `generic.__round__`, which would give a better error on types which are already broken like `str_`, `datetime`, etc.

**Comment by seberg** [comment]
There is still the question of what to do with integers, and I am still not sure, could leave them as is in a first step and consider again, likely that is what we want in any case.

**Comment by hameerabbasi** [comment]
> There is still the question of what to do with integers, and I am still not sure, could leave them as is in a first step and consider again, likely that is what we want in any case.

I'd prefer consistency, if we're going with Python `int`s for `np.floating`, we should for `np.integer`, too.

**Comment by eric-wieser** [comment]
I think there's a bug here on integers - a case like`round(intmax, math.ceil(math.log10(intmax))` will overflow

**Comment by hameerabbasi** [comment]
I think you mean `round(intmax, -math.ceil(math.log10(intmax))`, but no, both cases seem fine:

```python
>>> import numpy as np
>>> import math
>>> intmax = np.int32(2 ** 31 - 1)
>>> round(intmax, math.ceil(math.log10(intmax)))
2147483647
>>> round(intmax, -math.ceil(math.log10(intmax)))
0
```

**Comment by eric-wieser** [comment]
Sorry, I mean `round(np.int32(intmax), 1-math.ceil(math.log10(intmax)))`

**Comment by hameerabbasi** [comment]
Still all fine.

```python
>>> import numpy as np
>>> import math
>>> intmax = np.int32(2 ** 31 - 1)
>>> round(np.int32(intmax), 1-math.ceil(math.log10(intmax)))
2000000000
```

**Comment by hameerabbasi** [comment]
It would be weird if that were the case -- I'm not doing anything mathy at all. If there was an issue it'd be in NumPy's existing implementation.

**Comment by eric-wieser** [comment]
Well, if I don't use numpy I get:
```
>>> intmax = 2**32-1
>>> round(intmax, 1-math.ceil(math.log10(intmax)))
4000000000
```
So something is wrong here.

**Comment by hameerabbasi** [comment]
> So something is wrong here.

Yes, you're using `2 ** 32` and not `2 ** 31`... To hold that, we'd need `uint32`. But to show you all the cases:

```python
>>> round(np.uint32(2**32 - 1), 1-math.ceil(math.log10(2**32 - 1))) # Okay
4000000000
>>> round(np.int64(2**63 - 1), 1-math.ceil(math.log10(2**63 - 1))) # Okay
9000000000000000000
>>> round(np.uint64(2**64 - 1), 1-math.ceil(math.log10(2 ** 64 - 1))) # Fails, out of range of `uint64`
0
```

**Comment by eric-wieser** [comment]
Let me try one more time. How about `round(2**31-1, -1)`?

**Comment by hameerabbasi** [comment]
```python
>>> round(2**31-1, -1)
2147483650
>>> round(np.int32(2**31-1), -1)
-2147483648
```

Yep, that fails, and is a bug in `np.round`, we should file that.

**Comment by eric-wieser** [comment]
It's not really a bug in `np.round`, because `np.round` returns an `int32`, so the result is impossible to represent.

But if `__round__` is going to return a true integer, then we don't have that excuse.

**Comment by hameerabbasi** [comment]
So we have two choices here:
* Cast all integers to Python `int` before returning the result.
  * This makes the implementation diverge for `np.integer` and `np.floating`.
* Leave it as-is (it returns a `np.int32` currently)

**Comment by seberg** [comment]
I am OK with either probably (or at least was unable to make up my mind yet). For now I think leaving integers as is seems fine, it would be nice to make a clear decision for 1.9, but really only because once we fix it for floats its a bit less neat to change it for integers later.

File: numpy/core/src/common/npy_cpu_features.c [hunk 33]
```diff
@@ -0,0 +1,727 @@
+#line 1 "numpy/core/src/common/npy_cpu_features.c.src"
+
+/*
+ *****************************************************************************
+ **       This file was autogenerated from a template  DO NOT EDIT!!!!      **
+ **       Changes should be made to the original source (.src) file         **
+ *****************************************************************************
+ */
```
Comment (eric-wieser) [inline numpy/core/src/common/npy_cpu_features.c]: This should not be committed, right?

I'd suggest you just spawn a separate PR to ignore this, so we can get it out of the way.

Comment (hameerabbasi) [reply numpy/core/src/common/npy_cpu_features.c]: Yes, that was a mistake.

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 34]
```diff
@@ -2129,6 +2161,18 @@ static PyMethodDef @name@type_methods[] = {
...
+ */
+static PyMethodDef @name@type_methods[] = {
+    /* Hook for the round() builtin */
+    {"__round__",
+        (PyCFunction)generic_dunder_round,
+        METH_VARARGS | METH_KEYWORDS, NULL},
+    {NULL, NULL, 0, NULL} /* sentinel */
+};
+/**end repeat**/
+
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src]: Do we want a `np.complexfloating.__round__` that preserves the old behavior with a warning?

Comment (hameerabbasi) [reply numpy/core/src/multiarray/scalartypes.c.src]: I tried adding that... I do not know how to suppress the existing warning, and `DeprecationTestCase` doesn't work with two warnings (even though the code is there, it doesn't function).

Comment (hameerabbasi) [reply numpy/core/src/multiarray/scalartypes.c.src]: I'd be okay with just removing it, although I can try some more or push incomplete code for help.

Comment (seberg) [reply numpy/core/src/multiarray/scalartypes.c.src]: I would like one that preserves the old behaviour with a warning. Just going to an error directly seems undesirable to me. `DeprecationTestCase` should work with multiple warnings, but you have to tell it that there are multiple warnings.
Unless there is a warning of a different kind, in which case you may have to ignore that using pytest (or possibly `suppress_warnings` just because that is how `DeprecationTestCase` was originally written).

File: numpy/core/tests/test_numeric.py [hunk 35]
```diff
@@ -11,7 +11,7 @@
 from numpy.testing import (
     assert_, assert_equal, assert_raises, assert_raises_regex,
     assert_array_equal, assert_almost_equal, assert_array_almost_equal,
-    assert_warns, HAS_REFCOUNT
+    assert_warns, assert_allclose, HAS_REFCOUNT
```
Comment (seberg) [inline numpy/core/tests/test_numeric.py:14]: Do you still need the `assert_allclose` now that you are not returning python floating point numbers? Rounding should be defined very closely, but I guess it can have minor errors. How about using `assert_array_max_ulp`?

File: numpy/core/tests/test_numeric.py [hunk 36]
```diff
@@ -140,6 +140,36 @@ def test_round(self):
...
+        i = np.int64(501)
+        assert_(isinstance(round(i, -2), np.int64))
+        assert_allclose(round(i, -2), 500)
+        assert_(isinstance(round(i, ndigits=-2), np.int64))
+        assert_allclose(round(i, ndigits=-2), 500)
+
+    @pytest.mark.xfail
+    def test_round_py_consistency(self):
+        f = 5.1 * 10**73
+        assert_equal(round(np.float64(f), -73), round(f, -73))
```
Comment (seberg) [inline numpy/core/tests/test_numeric.py:171]: Interesting, any idea why we are getting a different result?

File: numpy/core/tests/test_numeric.py [hunk 37]
```diff
@@ -140,6 +140,36 @@ def test_round(self):
...
+        assert_(isinstance(round(f, -73), np.float64))
+        assert_allclose(round(f, -73), 5.0 * 10**73)
+        assert_(isinstance(round(f, ndigits=-73), np.float64))
+        assert_allclose(round(f, ndigits=-73), 5.0 * 10**73)
+
+        i = np.int64(501)
+        assert_(isinstance(round(i, -2), np.int64))
+        assert_allclose(round(i, -2), 500)
+        assert_(isinstance(round(i, ndigits=-2), np.int64))
+        assert_allclose(round(i, ndigits=-2), 500)
```
Comment (seberg) [inline numpy/core/tests/test_numeric.py:166]: Looks good to me, could be nice to parameterize for a couple of types. (and/or split up into multiple tests since they have not much to do with each other)

**Review by seberg — COMMENTED** [review]
LGTM, mainly nitpicks and a few suggestions most of which you can choose to ignore. Checking whether the warning was turned into an error in the C-code is the major thing that needs fixing.

File: numpy/core/tests/test_numeric.py (hunk 36 above)
Comment (hameerabbasi) [reply numpy/core/tests/test_numeric.py:186]: None, unfortunately. This is a bug in `np.round`, possibly a floating-point error.

File: numpy/core/tests/test_numeric.py (hunk 35 above)
Comment (hameerabbasi) [reply numpy/core/tests/test_numeric.py]: > `assert_array_max_ulp`

This works! Did not know about this, thanks.

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 38]
```diff
@@ -1549,6 +1549,55 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
+                 "scalar.round instead.", 0);
+#endif
+    
+    PyObject *tup;
+    if (ndigits == Py_None) {
+        tup = PyTuple_Pack(0);
+    }
+    else {
+        tup = PyTuple_Pack(1, ndigits);
+    }
```
[the remark this answers is not in the document]
Comment (hameerabbasi) [reply numpy/core/src/multiarray/scalartypes.c.src:1580]: Another PR sometime, maybe? It'd require adding it to `ndarray.round`, which this dispatches to.

File: numpy/core/tests/test_numeric.py [hunk 39]
```diff
@@ -139,6 +140,50 @@ def test_round(self):
...
+        assert_(isinstance(round(f, ndigits=-73), np.float64))
+        assert_array_max_ulp(round(f, ndigits=-73), 5.0 * 10**73)
+
+        i = np.int64(501)
+        assert_(isinstance(round(i, -2), np.int64))
+        assert_array_max_ulp(round(i, -2), 500)
+        assert_(isinstance(round(i, ndigits=-2), np.int64))
+        assert_array_max_ulp(round(i, ndigits=-2), 500)
+
+    @pytest.mark.xfail
```
Comment (eric-wieser) [inline numpy/core/tests/test_numeric.py:183]: We should open a tracking issue for this
```suggestion
    @pytest.mark.xfail(AssertionError, reason="gh-XXXX")
```

File: numpy/core/tests/test_deprecations.py [hunk 40]
```diff
@@ -577,3 +577,27 @@ def test_not_deprecated(self):
         for scalar_type in [type, dict, list, tuple]:
             # Typical python types are coerced to object currently:
             self.assert_not_deprecated(np.dtype, args=(scalar_type,))
+
+
+class BuiltInRoundComplexDType(_DeprecationTestCase):
+    # 2020-03-31 1.19.0
+    deprecated_types = [np.complex64, np.complex128]
```
[the remark this answers is not in the document]
Comment (hameerabbasi) [reply numpy/core/tests/test_deprecations.py:584]: Whoops, missed this one.

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 41]
```diff
@@ -1549,6 +1549,58 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
+    if (!PyArg_ParseTupleAndKeywords(args, kwds, "|O:__round__", kwlist, &ndigits)) {
+        return NULL;
+    }
+
+#if @complex@
+    if (PyErr_WarnEx(PyExc_DeprecationWarning,
+                 "The Python built-in `round` is deprecated for complex "
+                 "scalars, and will raise a `TypeError` in a future release. "
+                 "Use `np.round` or `scalar.round` instead.", 0) < 0)
+        return NULL;
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src:1571]:
```suggestion
                 "Use `np.round` or `scalar.round` instead.", 0) < 0) {
        return NULL;
    }
```

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 42]
```diff
@@ -1549,6 +1549,58 @@ gentype_@name@(PyObject *self, PyObject *args, PyObject *kwds)
...
+@name@type_dunder_round(PyObject *self, PyObject *args, PyObject *kwds)
+{
+    static char *kwlist[] = {"ndigits", NULL};
+    PyObject *ndigits = Py_None;
+    if (!PyArg_ParseTupleAndKeywords(args, kwds, "|O:__round__", kwlist, &ndigits)) {
+        return NULL;
+    }
+
+#if @complex@
+    if (PyErr_WarnEx(PyExc_DeprecationWarning,
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/scalartypes.c.src:1567]: Can you use the `DEPRECATE` macro here instead?

File: numpy/core/tests/test_deprecations.py (hunk 40 above)
[the remark this answers is not in the document]
Comment (eric-wieser) [reply numpy/core/tests/test_deprecations.py:584]: Perhaps clearer as
```suggestion
    deprecated_types = [np.csingle, np.cdouble, np.clongdouble]
```

File: numpy/core/tests/test_deprecations.py [hunk 43]
```diff
@@ -577,3 +577,27 @@ def test_not_deprecated(self):
...
+    not_deprecated_types = [
+        np.int8, np.int16, np.int32, np.int64,
+        np.uint8, np.uint16, np.uint32, np.uint64,
+        np.float16, np.float32, np.float64,
+    ]
+
+    def test_deprecated(self):
+        for scalar_type in self.deprecated_types:
+            scalar = scalar_type(0)
+            self.assert_deprecated(round, args=(scalar,), ignore_others=True)
```
Comment (seberg) [inline numpy/core/tests/test_deprecations.py:594]: Sorry, but I guess I forgot to ask, and now quickly before I forget again. Why is the `ignore_others=True` necessary here? I could not get another error on my system when trying briefly?

Comment (hameerabbasi) [reply numpy/core/tests/test_deprecations.py:594]: This was when I erroneously forgot to remove the conversion to `int` for complex... Shouldn’t be necessary now.

**Comment by hameerabbasi** [comment]
Travis failure is unrelated.

```
jobs.include.arch: unknown value aarch64
jobs.include.arch: unknown value aarch64 
```

**Comment by mattip** [comment]
That seems like a travis glitch, since the aarch64 builds have been around since Jan 2020.

**Review by seberg — COMMENTED** [review]
OK, had a quick glance over it, and I think this is in good shape now, and I will merge it soon.

This PR makes it so that `round(int64)` returns a python integer, and `round(int64, 0)` returns an `int64`. I am just saying that here for everyone to read. I am happy with this choice.

Could you add a deprecation fragment additionally for the complex case? I am considering if not mentioning `__round__` in the title is better (since it is arguable an implementation detail that not all users have to know about), but cannot think of how to reword it concisely immediately.

**Comment by seberg** [comment]
Thanks @hameerabbasi, lets put this in, it seems good to me with the last modifications, thanks for staying with this, its always a bit more complicated than anticipated :).

**Comment by WeatherGod** [comment]
Would this change have impacted how `np.round()` treats scalars? I am trying to chase down a bug where `np.round([x])` is producing a different value sometimes from `np.round(x)`.

**Comment by hameerabbasi** [comment]
No, we didn't change `np.round`, only `ndarray.__round__`.

**Comment by seberg** [comment]
@WeatherGod do you have a reproducer or similar?  One thing is that round seems to call multiple, and `true_divide` internally with double precision numbers. So for the scalar case, we are likely using double precision calculations, but for `[x]` we would be using single precision in those calculations.

**Comment by WeatherGod** [comment]
Still waiting for the actual data from my co-worker, but we have figured out that the problem is not in `np.round()`, but apparently different rules for upcasting calculations involving numpy scalars versus numpy arrays. I'll dig a bit more and see if a new bug report is warranted.
