### PR TITLE
BUG: Remove temporary change of descr/flags in VOID functions

### LINKED ISSUE #15387: threads + integer array indexing into array of structured dtype -> memory corruption
Hi!

I'm hitting an issue that seems to be an interaction between fancy indexing (using a 1D integer array) into a 1D array with structured dtype.  It results in a range of unpredictable behaviours ranging from confusing error messages to SIGABRT to segfaults.

### Reproducing code example:

```python
from concurrent.futures import ThreadPoolExecutor
import numpy as np

my_dtype = np.dtype(
    [
        ("i0", np.int32),
        ("i1", np.int32),
        ("i2", np.int32),
        ("i3", np.int32),
    ]
)

tpe = ThreadPoolExecutor(max_workers=8)

# For size 100, no problems
# For size 1000, problems sometimes (but if one iteration below succeeds they all tend to)
# For size 8000, fails pretty much every time
arr = np.zeros([1000], dtype=my_dtype)

# populate a field with random data to use for selecting entries
arr["i0"] = np.random.randint(0, 1000, arr["i0"].shape)
arr["i1"] = np.random.randint(0, 1000, arr["i1"].shape)


def get_part_of_array(a):
    # For some reason, random indices here doesn't seem to cause the problem,
    # unless the number of selected indices is >> the size of the array being indexed,
    # which is clearly not the case in the np.nonzero case.  So that might be a different
    # issue, not sure.

    # No problem
    # i = np.random.randint(0, arr.shape[0], 100)

    # Problem
    # i = np.random.randint(0, arr.shape[0], 1000)

    # The original problem
    i = np.nonzero(a["i0"] < 500)
    return a[i]


for i in range(10):
    futures = [tpe.submit(get_part_of_array, arr) for _ in range(10)]
    for f in futures:
        f.result()

```

### Error message:

Various:

```
  File "test2.py", line 36, in get_part_of_array
    i = np.nonzero(a["i0"] < 500)
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

```
  File "test2.py", line 36, in get_part_of_array
    i = np.nonzero(a["i0"] < 500)
ValueError: no field of name i0
```

And sometimes it explodes with a SIGABRT or a segfault:

```
  File "test2.py", line 36, in get_part_of_array
    i = np.nonzero(a["i0"] < 500)
ValueError: no field of name i0
*** Error in `python': malloc(): memory corruption: 0x00007ff348006c20 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7dd7d)[0x7ff3a2431d7d]
/lib64/libc.so.6(__libc_malloc+0x4c)[0x7ff3a243410c]
python(PyObject_Malloc+0x15f)[0x55db446c10af]
python(+0x15c070)[0x55db44710070]
python(_PyDict_DelItem_KnownHash+0x17b)[0x55db4472415b]
python(_PyObject_GenericSetAttrWithDict+0x87)[0x55db4476c127]
python(PyObject_SetAttr+0x67)[0x55db4476ce47]
python(_PyEval_EvalFrameDefault+0x2491)[0x55db44777051]
python(_PyFunction_FastCallKeywords+0xfb)[0x55db4471468b]
python(_PyEval_EvalFrameDefault+0x6a0)[0x55db44775260]
python(_PyFunction_FastCallKeywords+0xfb)[0x55db4471468b]
python(_PyEval_EvalFrameDefault+0x6a0)[0x55db44775260]
python(_PyFunction_FastCallDict+0x10b)[0x55db446cf73b]
python(_PyObject_Call_Prepend+0x63)[0x55db446ea943]
python(PyObject_Call+0x6e)[0x55db446ddb9e]
python(+0x215af7)[0x55db447c9af7]
python(+0x1d2e18)[0x55db44786e18]
/lib64/libpthread.so.0(+0x7e25)[0x7ff3a277ee25]
/lib64/libc.so.6(clone+0x6d)[0x7ff3a24ac34d]
```

When running under gdb and catching one of the SIGABRTs:

```
Thread 1 "python" received signal SIGABRT, Aborted.
0x00007fb9a00f71f7 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007fb9a00f71f7 in raise () from /lib64/libc.so.6
#1  0x00007fb9a00f88e8 in abort () from /lib64/libc.so.6
#2  0x00007fb9a0136f47 in __libc_message () from /lib64/libc.so.6
#3  0x00007fb9a013e619 in _int_free () from /lib64/libc.so.6
#4  0x00007fb998b4787c in PyDataMem_FREE (ptr=0x7fb93000ae10) at numpy/core/src/multiarray/alloc.c:273
#5  _npy_free_cache (dealloc=0x7fb998b47ae0 <PyDataMem_FREE>, cache=0x7fb9990e0260 <datacache>, msz=1024, nelem=<optimized out>, p=0x7fb93000ae10) at numpy/core/src/multiarray/alloc.c:112
#6  npy_free_cache (p=0x7fb93000ae10, sz=<optimized out>) at numpy/core/src/multiarray/alloc.c:147
#7  0x00007fb998b4afe7 in array_dealloc (self=0x7fb95a884030) at numpy/core/src/multiarray/arrayobject.c:530
#8  0x0000564f3b53fa87 in dict_dealloc (mp=0x7fb95a882b90) at /tmp/build/80754af9/python_1578510683607/work/Objects/dictobject.c:1905
#9  0x0000564f3b5c9fb0 in subtype_dealloc (
    self=<Future(_condition=<Condition at remote 0x7fb95a879a10>, _state='FINISHED', _result=<numpy.ndarray at remote 0x7fb95a884030>, _exception=None, _waiters=[], _done_callbacks=[]) at remote 0x7fb95a8799d0>)
    at /tmp/build/80754af9/python_1578510683607/work/Objects/typeobject.c:1263
#10 0x0000564f3b53f682 in list_dealloc (op=0x7fb95a873960) at /tmp/build/80754af9/python_1578510683607/work/Objects/listobject.c:324
#11 0x0000564f3b52fdfb in free_keys_object (keys=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Objects/dictobject.c:559
#12 PyDict_Clear (op=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Objects/dictobject.c:1644
#13 0x0000564f3b52feca in dict_tp_clear (op=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Objects/dictobject.c:2997
#14 0x0000564f3b551b74 in delete_garbage (old=0x564f3b7675c0 <_PyRuntime+448>, collectable=0x7ffd61581760) at /tmp/build/80754af9/python_1578510683607/work/Modules/gcmodule.c:761
#15 collect (generation=<optimized out>, n_collected=0x0, n_uncollectable=0x0, nofail=1) at /tmp/build/80754af9/python_1578510683607/work/Modules/gcmodule.c:913
#16 0x0000564f3b63b20a in _PyGC_CollectNoFail () at /tmp/build/80754af9/python_1578510683607/work/Modules/gcmodule.c:1602
#17 0x0000564f3b5cbb1c in PyImport_Cleanup () at /tmp/build/80754af9/python_1578510683607/work/Python/import.c:526
#18 0x0000564f3b641367 in Py_FinalizeEx () at /tmp/build/80754af9/python_1578510683607/work/Python/pylifecycle.c:1195
#19 0x0000564f3b653d93 in pymain_main (pymain=0x7ffd615819c0) at /tmp/build/80754af9/python_1578510683607/work/Modules/main.c:3416
#20 0x0000564f3b6540bc in _Py_UnixMain (argc=<optimized out>, argv=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Modules/main.c:3449
#21 0x00007fb9a00e3c05 in __libc_start_main () from /lib64/libc.so.6
#22 0x0000564f3b5fc990 in _start () at ../sysdeps/x86_64/elf/start.S:103
```

and one of the SIGSEGVs:

```
(gdb) bt
#0  0x00007ff1714cc418 in _int_free () from /lib64/libc.so.6
#1  0x00007ff169ed587c in PyDataMem_FREE (ptr=0x7ff11c014820) at numpy/core/src/multiarray/alloc.c:273
#2  _npy_free_cache (dealloc=0x7ff169ed5ae0 <PyDataMem_FREE>, cache=0x7ff16a46e260 <datacache>, msz=1024, nelem=<optimized out>, p=0x7ff11c014820) at numpy/core/src/multiarray/alloc.c:112
#3  npy_free_cache (p=0x7ff11c014820, sz=<optimized out>) at numpy/core/src/multiarray/alloc.c:147
#4  0x00007ff169ed8fe7 in array_dealloc (self=0x7ff12bc0ad00) at numpy/core/src/multiarray/arrayobject.c:530
#5  0x00007ff169ed9107 in array_dealloc (self=0x7ff12bc0da30) at numpy/core/src/multiarray/arrayobject.c:522
#6  0x000055603cd6abc7 in tupledealloc (op=0x7ff16a4fea10) at /tmp/build/80754af9/python_1578510683607/work/Objects/tupleobject.c:246
#7  0x000055603cd5a948 in frame_dealloc (f=Frame 0x7ff16a5de590, for file test2.py, line 37, in get_part_of_array ()) at /tmp/build/80754af9/python_1578510683607/work/Objects/frameobject.c:470
#8  0x000055603cd72772 in function_code_fastcall (globals=<optimized out>, nargs=<optimized out>, args=<optimized out>, co=0x7ff171b6a270) at /tmp/build/80754af9/python_1578510683607/work/Objects/call.c:291
#9  _PyFunction_FastCallDict (func=<optimized out>, args=<optimized out>, nargs=<optimized out>, kwargs=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Objects/call.c:322
#10 0x000055603ce199f5 in do_call_core (kwdict={}, callargs=(<numpy.ndarray at remote 0x7ff12bc093f0>,), func=<function at remote 0x7ff171b1c680>) at /tmp/build/80754af9/python_1578510683607/work/Python/ceval.c:4645
#11 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Python/ceval.c:3191
#12 0x000055603cdb768b in function_code_fastcall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Objects/call.c:283
#13 _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x7ff12bbef9f0, nargs=1, kwnames=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Objects/call.c:408
#14 0x000055603ce18260 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1578510683607/work/Python/ceval.c:4616
#15 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Python/ceval.c:3110
#16 0x000055603cd7273b in function_code_fastcall (globals=<optimized out>, nargs=4, args=<optimized out>, co=0x7ff171a9b9c0) at /tmp/build/80754af9/python_1578510683607/work/Objects/call.c:283
#17 _PyFunction_FastCallDict (func=<optimized out>, args=0x7ff12bbfccc8, nargs=4, kwargs=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Objects/call.c:322
#18 0x000055603ce199f5 in do_call_core (kwdict={}, callargs=(<weakref at remote 0x7ff12bbfcd70>, <_queue.SimpleQueue at remote 0x7ff16a5032f0>, None, ()), func=<function at remote 0x7ff16a4fa9e0>)
    at /tmp/build/80754af9/python_1578510683607/work/Python/ceval.c:4645
#19 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Python/ceval.c:3191
#20 0x000055603cdb768b in function_code_fastcall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Objects/call.c:283
#21 _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x7ff11c000a70, nargs=1, kwnames=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Objects/call.c:408
#22 0x000055603ce18260 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1578510683607/work/Python/ceval.c:4616
#23 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Python/ceval.c:3110
#24 0x000055603cdb768b in function_code_fastcall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Objects/call.c:283
#25 _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x7ff12bc081c8, nargs=1, kwnames=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Objects/call.c:408
#26 0x000055603ce18260 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1578510683607/work/Python/ceval.c:4616
#27 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Python/ceval.c:3110
#28 0x000055603cd7273b in function_code_fastcall (globals=<optimized out>, nargs=1, args=<optimized out>, co=0x7ff16a4d6a50) at /tmp/build/80754af9/python_1578510683607/work/Objects/call.c:283
#29 _PyFunction_FastCallDict (func=<optimized out>, args=0x7ff12b208e20, nargs=1, kwargs=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Objects/call.c:322
#30 0x000055603cd8d943 in _PyObject_Call_Prepend (callable=<function at remote 0x7ff16a4e40e0>, obj=<optimized out>, args=(), kwargs=0x0) at /tmp/build/80754af9/python_1578510683607/work/Objects/call.c:908
#31 0x000055603cd80b9e in PyObject_Call (callable=<method at remote 0x7ff171bcfcd0>, args=<optimized out>, kwargs=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Objects/call.c:245
#32 0x000055603ce6caf7 in t_bootstrap (boot_raw=0x7ff12bc2b450) at /tmp/build/80754af9/python_1578510683607/work/Modules/_threadmodule.c:994
#33 0x000055603ce29e18 in pythread_wrapper (arg=<optimized out>) at /tmp/build/80754af9/python_1578510683607/work/Python/thread_pthread.h:174
#34 0x00007ff17181ae25 in start_thread () from /lib64/libpthread.so.0
#35 0x00007ff17154834d in clone () from /lib64/libc.so.6
```

### Numpy/Python version information:

```
$ python -c 'import sys, numpy; print(numpy.__version__, sys.version)'
1.18.1 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0]
```

### PR DESCRIPTION
**Pull request by seberg**
This is done using a hack around stack allocated arrays, which
requires some dark magic with respect to the setting the base
object (we skip normal arrays and INCREF/DECREF during base setting,
which _does_ work for such static arrays, but only if we give them
a (not quite) fake refcount of 1 and set the base and their type
correctly to PyArrayType.

Closes gh-15387

---

This fixes the issue (should get the initial bug report example as a test), but it got more annoying than I thought, since setting the `arr->base` has to keep work correctly, which currently requires faking a reference count (and adding type+base information, which seems fine). (We mainly need to fake the reference count because our `SetBaseObject` function insists on stealing a reference...

### CODE REVIEW

**Comment by seberg** [comment]
Hmmm, forgetting to unset the OWNDATA flag did not actually create a failure locally, although maybe the windows failure was due to that...

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 1]
```diff
@@ -38,6 +38,40 @@
...
+        Py_TYPE(&__dummy_array_fields) = &PyArray_Type;             \
+        Py_REFCNT(&__dummy_array_fields) = 1;                       \
+        __dummy_array_fields.base = (PyObject *)arr;                \
+        *(dummy_array) = (PyArrayObject *)&__dummy_array_fields
+
+#ifndef NDEBUG
+    /* Fill data with bad value to error if free'd */
+    #define MAKE_DUMMY_STACK_ARRAY(arr, dummy_array)                \
+            _MAKE_DUMMY_STACK_ARRAY(arr, dummy_array);              \
+            __dummy_array_fields.data = 0xDEADBEEF
```
Comment (seberg) [inline numpy/core/src/multiarray/arraytypes.c.src]: Makes the tests reliably segfault in debug mode (before seems it was limited to windows when I forgot the removal of owndata).

**Comment by seberg** [comment]
The only alternative to this I can see right away would be to generally not allow threading for VOID dtypes probably...

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 2]
```diff
@@ -38,6 +38,40 @@
 #include "npy_cblas.h"
 #include "npy_buffer.h"
 
+
+/*
+ * Define array fields with only the flags set. The flags are set to preserve
```
Comment (seberg) [inline numpy/core/src/multiarray/arraytypes.c.src]: Whoops, outdated, will update as soon as anyone says this seems not completely unreasonable ;).

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 3]
```diff
@@ -38,6 +38,39 @@
...
+ *   3. base, reference count, and type are set because these are used
+ *      during setting of the base object. Setting all ensures that
+ *      the dummy array will be skipped when setting the base.
+ *      (i.e. the dummy arrays `base` is used instead).
+ *
+ * In debug mode fill in the `data` field to ensure a crash if the object
+ * is incorrectly deallocated.
+ */
+#define _MAKE_DUMMY_STACK_ARRAY(arr, dummy_array)                   \
+        PyArrayObject_fields __dummy_array_fields;                  \
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/arraytypes.c.src]: Good practice to wrap this in `do { ... } while(0)` so it consumes semicolons correctly.

Comment (eric-wieser) [reply numpy/core/src/multiarray/arraytypes.c.src]: Oh, that won't work, because this is on the stack - nevermind

Comment (seberg) [reply numpy/core/src/multiarray/arraytypes.c.src]: Hmmm, wouldn't that kill scoping of the PyArrayObject_fields structure? To be honest, probably depends on what the C standard says, so no clue.

Comment (eric-wieser) [reply numpy/core/src/multiarray/arraytypes.c.src]: You're correct

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 4]
```diff
@@ -38,6 +38,26 @@
...
 #include "npy_buffer.h"
 
+
+/*
+ * Define a stack allocated dummy array with only the minimum information set:
+ *   1. The descr, the main field interesting here.
+ *   2. The flags, which are needed for alignment;.
+ *   3. The type is set to NULL and the base is the original array, if this
+ *      is used within a subarray getitem to create a new view, the base
+ *      must be walked until the type is not NULL.
```
Comment (seberg) [inline numpy/core/src/multiarray/arraytypes.c.src]: OK, this got more complex, but for now seemed like the easiest. The third point is only necessary for `VOID_getitem` recursion, so it would be plausible to create two versions for creating the stack array...

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 5]
```diff
@@ -879,18 +908,22 @@ VOID_setitem(PyObject *op, void *input, void *vap)
...
+        /*
+         * Note we set no base object here, as to not rely on the input
+         * being a valid object for base setting. `ret` nevertheless does
+         * does not own its data, this is generally not good, but localized.
+         */
+        PyArrayObject *ret = (PyArrayObject *)PyArray_NewFromDescrAndBase(
                 &PyArray_Type, descr->subarray->base,
                 shape.len, shape.ptr, NULL, ip,
-                PyArray_FLAGS(ap), NULL, (PyObject *)ap);
+                PyArray_FLAGS(ap), NULL, NULL);
```
Comment (seberg) [inline numpy/core/src/multiarray/arraytypes.c.src]: I think this is really fine, as the note says, it is strange, but localized...

File: numpy/core/src/multiarray/arraytypes.c.src (hunk 4 above)
Comment (seberg) [reply numpy/core/src/multiarray/arraytypes.c.src]: I initially thought that the base iteration is handled implicitly in the normal base setting code, but, there are always cases that do not work (when subclasses are involved).

This is probably better anyway, keep the strangeness confined to a single place...

**Comment by seberg** [comment]
Hmmm, `VOID_setitem` and `getitem` always must have the GIL in any case... So not sure the dance is very useful there. So it may be better to limit this to `nonzero` and `copyswap(n)` (and maybe double check that there is no other reason why we should require the GIL, I assume the dict iteration is OK, at least if we assume that dtypes are immutable – which of course they are not quite).

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 6]
```diff
@@ -629,56 +649,49 @@ OBJECT_setitem(PyObject *op, void *ov, void *NPY_UNUSED(ap))
     return PyErr_Occurred() ? -1 : 0;
 }
 
+
 /* VOID */
 
 static PyObject *
 VOID_getitem(void *input, void *vap)
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/arraytypes.c.src]: How hard would it be to change `vap` to be a `dtype` instead of an `ndarray`? Would that remove the need for these hacks?

Comment (seberg) [reply numpy/core/src/multiarray/arraytypes.c.src]: That is my vision for the future. For many we may also need to pass in `aligned`. But at least in principle this is visible/public API through `descriptor->f->getitem`.
While visible API, the SciPy uses `copyswap`, I am not sure anyone else uses anything.

Comment (eric-wieser) [reply numpy/core/src/multiarray/arraytypes.c.src]: Does scipy call or implement copyswap? If we loosened the spec to "pass either an array or dtype", then the callers wouldn't notice - only the implementers, which I suspect is just us and `quaternion`.

Comment (seberg) [reply numpy/core/src/multiarray/arraytypes.c.src]: It calls `descr->f->copyswap(..., NULL)`...

Comment (eric-wieser) [reply numpy/core/src/multiarray/arraytypes.c.src]: If that's all it does, then scipy won't even notice if we change that from a null array to a null dtype.

Comment (seberg) [reply numpy/core/src/multiarray/arraytypes.c.src]: True, the question is whether we want to be so bold and mess with this "public" API. The thing about it is mostly:
`descr->f->method` is a lot on the`descr`, I currently enivision `Py_TYPE(descr)->method` (or maybe one more indirection, similar to pythons `nb_...` slots). At which point we can deprecate/hide `->f` completely, and finally remove it.

The downside being that even after replacing, we have to keep supporting them with these types of hacks for a (fairly long) time.

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 7]
```diff
@@ -38,6 +38,26 @@
...
+ *   3. The type is set to NULL and the base is the original array, if this
+ *      is used within a subarray getitem to create a new view, the base
+ *      must be walked until the type is not NULL.
+ *
+ * The following should create errors in debug mode (if deallocated
+ * incorrectly), since base would be incorrectly decref'd as well.
+ */
+#define MAKE_DUMMY_STACK_ARRAY(arr, dummy_array)                    \
+        PyArrayObject_fields __dummy_array_fields;                  \
+        __dummy_array_fields.flags = PyArray_FLAGS(arr);            \
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/arraytypes.c.src]: Any reason for preserving the flags?

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 8]
```diff
@@ -38,6 +38,26 @@
...
+ *   1. The descr, the main field interesting here.
+ *   2. The flags, which are needed for alignment;.
+ *   3. The type is set to NULL and the base is the original array, if this
+ *      is used within a subarray getitem to create a new view, the base
+ *      must be walked until the type is not NULL.
+ *
+ * The following should create errors in debug mode (if deallocated
+ * incorrectly), since base would be incorrectly decref'd as well.
+ */
+#define MAKE_DUMMY_STACK_ARRAY(arr, dummy_array)                    \
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/arraytypes.c.src]: Maybe instead
```
static PyArrayObject_fields dummy_stack_array(PyArrayObject *orig) {
    PyArrayObject_fields fields;
    fields.flags = PyArray_FLAGS(orig);
    Py_TYPE(&fields) = NULL;
    fields.base = (PyObject *)orig;
    return fields;
}
```
then at the call site
```
PyArrayObject_fields dummy_fields = dummy_stack_array(arr);
PyArrayObject *dummy_array = (PyArrayObject *)dummy_fields;
```
which is almost certainly optimized to the same code, and feels less hacky

File: numpy/core/src/multiarray/arraytypes.c.src (hunk 7 above)
Comment (seberg) [reply numpy/core/src/multiarray/arraytypes.c.src]: copyswapn needed the "aligned" one IIRC, but it is not needed in GETITEM/SETITEM I think. So I could set it only in the one place.

**Comment by charris** [comment]
What is the current status of this?

**Comment by seberg** [comment]
Thanks for the ping. I think we should move forward, I made it an inline function so that it is prettier. Added a test with ThreadPoolExecutor, but only for nonzero for now, I can add one (am somewhat planning) to add one closer to the original (which tests `copyswapn` through indexing.

**Comment by seberg** [comment]
OK, this should be good for review. The long comment about/at the base walking bit is maybe annoying. That function must hold the GIL, so strictly speaking it is safe, still feels a bit better to not modify the original array object, but it would avoid the dance with the base.
In any case, maybe it is simply a step in the right direction...

**Review by mattip — COMMENTED** [review]
LGTM.

**Comment by eric-wieser** [comment]
Would calling `PyArray_View` and just paying the slight extra cost be reasonable here? Or is that extra cost very high?

In principle, "downstream dtypes" (if any exist) could be using the full set of array attributes, and the only way that could actually work is if we created real views here.

Perhaps worth exploring in a different PR, and then comparing profile results.

Am I right in reading that this only effects `GETITEM` (`.item()`) and `SETITEM` (`arr[0] = something`)?

**Comment by seberg** [comment]
My quite certain guess is that the cost is high, at least for getitem/setitem, since you may do that for every single item in a large array. Same for copyswap(n) which can potentially be called many times in advanced indexing. But if you think it is ugly enough, I can make sure with some timing...

My opinion about user datatypes is that we must move away from passing the whole array, so doing that now seems easier than doing it later. Yes, in theory it is broken, in practice we do actually create views like this (not static) for casting already.

I can actually leave GETITEM and SETITEM alone in principle, they must hold the GIL, so the modification is safe to some degree. `nonzero` and `copyswap(n)` are the actual problems (which is why they have tests).

**Comment by seberg** [comment]
This actually already has a 1/3 performance hit in 1-D advanced indexing into structured datatypes...

File: numpy/core/src/multiarray/arraytypes.c.src (hunk 6 above)
Comment (mattip) [reply numpy/core/src/multiarray/arraytypes.c.src]: What is the resolution: are we leaving this for later?

File: numpy/core/src/multiarray/arraytypes.c.src (hunk 7 above)
Comment (mattip) [reply numpy/core/src/multiarray/arraytypes.c.src]: @seberg did you wan to remove the flags from here and move to copyswapn?

**Comment by mattip** [comment]
> This actually already has a 1/3 performance hit ..

Can you clarify that statement? Which benchmarks are changed and by how much: 30% or 300%

**Comment by seberg** [comment]
Sorry, it is:
```
In [1]: arr = np.arange(10000).view([("", np.intp)])                                                                    
In [2]: %timeit arr[np.arange(10000)] 
```
that changes, that uses `copyswap(n)` set of functions internally, changes from around 15µs to 20µs for me. If we would be creating a whole array object, I expect it would make a much bigger difference.

File: numpy/core/src/multiarray/arraytypes.c.src (hunk 6 above)
Comment (seberg) [reply numpy/core/src/multiarray/arraytypes.c.src]: I do not think I want to go there right now.

File: numpy/core/src/multiarray/arraytypes.c.src (hunk 7 above)
Comment (seberg) [reply numpy/core/src/multiarray/arraytypes.c.src]: Hmm, can do, not that it matters much. The main thing that would matter here is if we decide to leave setitem/getitem the way they are since they hold the GIL for sure.

**Comment by charris** [comment]
I've removed the backport-candidate label because the 1.19 branch is only 3-4 weeks out. It would be nice to have this resolved before that branch.

**Comment by seberg** [comment]
I agree, do I need to think more about if/how to avoid the stack arrays, or try to minize the change to setitem/getitem (since they always hold the GIL), or is this pretty much settled and we are just a bit hesitant about putting it in?

**Comment by seberg** [comment]
Can we do this, or should I undo getitem/setitem since only copyswapn is truly problematic (getitem/setitem must have the GIL)? Or does anyone have a better idea then this? Might be nice to finish up for 1.19?

**Comment by mattip** [comment]
@seberg is this meant to be part of the dtype reworking for 1.20 or do we let it slide to a future release?

**Comment by seberg** [comment]
Rebased, but no. This fixes a rare race condition causing the crash report in gh-15387. But it is largely orthogonal to DTypes.

(I guess in the grand schemes, the only vital for dtypes is really my big PR, some of these are nuisances which would be nice to stop worrying about, but not central.)

**Comment by charris** [comment]
@eric-wieser Look good to you?

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 9]
```diff
@@ -42,6 +42,31 @@
...
+ * incorrectly), since base would be incorrectly decref'd as well.
+ * This is especially important for nonzero and copyswap, which may run with
+ * the GIL released.
+ */
+static NPY_INLINE PyArrayObject_fields
+get_dummy_stack_array(PyArrayObject *orig)
+{
+    PyArrayObject_fields new_fields;
+    new_fields.flags = PyArray_FLAGS(orig);
+    Py_TYPE(&new_fields) = NULL;
```
Comment (mattip) [inline numpy/core/src/multiarray/arraytypes.c.src:64]:
```suggestion
    /* Set to NULL so the dummy object can be distinguished from the real one */
    Py_TYPE(&new_fields) = NULL;
```

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 10]
```diff
@@ -2303,29 +2342,26 @@ VOID_copyswapn (char *dst, npy_intp dstride, char *src, npy_intp sstride,
...
-                ((PyArrayObject_fields *)arr)->descr = descr;
                 return;
             }
-            /*
-             * TODO: temporarily modifying the array like this
-             *       is bad coding style, should be changed.
-             */
-            ((PyArrayObject_fields *)arr)->descr = new;
+
+            ((PyArrayObject_fields *)dummy_arr)->descr = new;
```
Comment (mattip) [inline numpy/core/src/multiarray/arraytypes.c.src:2360]:
```suggestion
            dummy_fields->descr = new;
```

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 11]
```diff
@@ -2396,26 +2431,24 @@ VOID_copyswap (char *dst, char *src, int swap, PyArrayObject *arr)
...
             if (_unpack_field(value, &new, &offset) < 0) {
-                ((PyArrayObject_fields *)arr)->descr = descr;
                 return;
             }
-            /*
-             * TODO: temporarily modifying the array like this
-             *       is bad coding style, should be changed.
-             */
-            ((PyArrayObject_fields *)arr)->descr = new;
+            ((PyArrayObject_fields *)dummy_arr)->descr = new;
```
Comment (mattip) [inline numpy/core/src/multiarray/arraytypes.c.src:2447]:
```suggestion
            dummy_fields->descr = new;
```

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 12]
```diff
@@ -2439,20 +2472,19 @@ VOID_copyswap (char *dst, char *src, int swap, PyArrayObject *arr)
...
-        ((PyArrayObject_fields *)arr)->descr = new;
         subitemsize = new->elsize;
         if (subitemsize == 0) {
             /* There cannot be any elements, so return */
             return;
         }
+
+        PyArrayObject_fields dummy_fields = get_dummy_stack_array(arr);
+        PyArrayObject *dummy_arr = (PyArrayObject *)&dummy_fields;
+        ((PyArrayObject_fields *)dummy_arr)->descr = new;
```
Comment (mattip) [inline numpy/core/src/multiarray/arraytypes.c.src:2483]:
```suggestion
        dummy_fields->descr = new;
```

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 13]
```diff
@@ -2722,26 +2754,20 @@ VOID_nonzero (char *ip, PyArrayObject *ap)
...
                 continue;
             }
-            /*
-             * TODO: temporarily modifying the array like this
-             *       is bad coding style, should be changed.
-             */
-            ((PyArrayObject_fields *)ap)->descr = new;
-            ((PyArrayObject_fields *)ap)->flags = savedflags;
+
+            ((PyArrayObject_fields *)dummy_arr)->descr = new;
```
Comment (mattip) [inline numpy/core/src/multiarray/arraytypes.c.src:2758]:
```suggestion
            dummy_fields->descr = new;
```

**Review by mattip — COMMENTED** [review]
Some small style suggestions, can be ignored.

While this looks good to me, I think it might be too risky to put in just before the release cut.

**Comment by charris** [comment]
@seberg Compilation errors.

**Comment by mattip** [comment]
LGTM. Anyone else want to take a look?

**Comment by seberg** [comment]
There was a ping on the issue, so rebased this.

**Comment by mattip** [comment]
I am inclined to put this in. Do any of our benchmarks show a significant change?

**Comment by seberg** [comment]
By now it is all a bit weird, since it mainly affects `copyswap(n)` which is public API, but I would like to cut out using the normal cast functionality everywhere (i.e. the arraymethod – and there, it might be interesting to look into "single item" optimizations at some point).

I rand them for sports and did not notice a change in benchmarks due to this (computer was not as stable as it should have been).  But I don't think we even _have_ benchmarks that can be affected...

File: numpy/core/src/multiarray/arraytypes.c.src [hunk 14]
```diff
@@ -42,6 +42,32 @@
...
+ *   1. The descr, the main field interesting here.
+ *   2. The flags, which are needed for alignment;.
+ *   3. The type is set to NULL and the base is the original array, if this
+ *      is used within a subarray getitem to create a new view, the base
+ *      must be walked until the type is not NULL.
+ *
+ * The following should create errors in debug mode (if deallocated
+ * incorrectly), since base would be incorrectly decref'd as well.
+ * This is especially important for nonzero and copyswap, which may run with
+ * the GIL released.
```
Comment (mattip) [inline numpy/core/src/multiarray/arraytypes.c.src:57]: If this singleton can be used with the GIL released, it can be modified by other threads, no?

Comment (seberg) [reply numpy/core/src/multiarray/arraytypes.c.src:57]: No, it is stack local to the function call using it.

Comment (mattip) [reply numpy/core/src/multiarray/arraytypes.c.src:57]: Ahh, right, not `static PyArrayObject_fields`, just `PyArrayObject_fields`.

**Comment by mattip** [comment]
Thanks @seberg

**Comment by charris** [comment]
@seberg Made this a backport candidate.

**Comment by seberg** [comment]
Oh, OK. Sounds fine with me. I will have another brief look at the backport PR just to be sure then.

**Comment by charris** [comment]
@seberg Backport at  #18462.
