### PR TITLE
MAINT: refactor PyArray_AdaptFlexibleDType to return a meaningful value

### LINKED ISSUE #11969: BUG: errors and PyArray_AdaptFlexibleDType
`PyArray_AdaptFlexibleDType` does not return an error status. It seems the third argument, `flex_type` is set to `NULL` if an error occurs, but the value is not checked after a call to the function. Apparently our test suite does not trigger errors in the function. We should
- return a value from the function to indicate an error occurred
- check the value at all calls to the function
- devise tests that make the function fail, preferably in a way that requires the checks in order to prevent incorrect results or crashes
- make sure we exit the function on errors, for instance from the call to `PyArray_GetArrayParamsFromObject`.

### PR DESCRIPTION
**Pull request by mattip**
Fixes #11969 by changing the signature and adding checks.

I added a check for `PyArray_GetArrayParamsFromObject` returning an error, but could not build a test to check it. The function will hit the [`PySequenceCheck`](https://github.com/numpy/numpy/blob/v1.15.2/numpy/core/src/multiarray/ctors.c#L1658) branch, and then can only fail on memory error, or if `PyArray_DescrFromType()` fails, which it never does.

### CODE REVIEW

**Comment by mattip** [comment]
ping

File: numpy/core/src/multiarray/convert_datatype.c [hunk 1]
```diff
@@ -130,48 +130,46 @@ PyArray_GetCastFunc(PyArray_Descr *descr, int type_num)
...
-                    "NumPy AdaptFlexibleDType was called with NULL flex_dtype "
-                    "but no error set");
-        }
-        return;
+    if (flex_dtype == NULL) {
+        return retval;
     }
 
-    flex_type_num = (*flex_dtype)->type_num;
+    flex_type_num = (flex_dtype)->type_num;
```
Comment (seberg) [inline numpy/core/src/multiarray/convert_datatype.c]: No need for thre brackets.

File: numpy/core/src/multiarray/convert_datatype.c [hunk 2]
```diff
@@ -262,9 +259,16 @@ PyArray_AdaptFlexibleDType(PyObject *data_obj, PyArray_Descr *data_dtype,
...
                             result = PyArray_GetArrayParamsFromObject(
                                     list,
-                                    *flex_dtype,
+                                    retval,
                                     0, &dtype,
                                     &ndim, dims, &arr, NULL);
+                            if (result < 0) {
+                                Py_XDECREF(dtype);
+                                Py_XDECREF(arr);
+                                Py_DECREF(list);
```
Comment (seberg) [inline numpy/core/src/multiarray/convert_datatype.c]: Might it be nicer to DECREF arr and list uncoditionally before and remove it from the end?

File: numpy/core/src/multiarray/convert_datatype.c [hunk 3]
```diff
@@ -326,41 +328,38 @@ PyArray_AdaptFlexibleDType(PyObject *data_obj, PyArray_Descr *data_dtype,
...
-            return;
+            Py_DECREF(retval);
+            return NULL;
         }
     }
     /* Flexible type with generic time unit that adapts */
     else if (flex_type_num == NPY_DATETIME ||
                 flex_type_num == NPY_TIMEDELTA) {
-        meta = get_datetime_metadata_from_dtype(*flex_dtype);
+        meta = get_datetime_metadata_from_dtype(flex_dtype);
```
Comment (seberg) [inline numpy/core/src/multiarray/convert_datatype.c]: Look like there should be a DECREF right aftr this call. Also removes the need for the decref's later.

File: numpy/core/src/multiarray/convert_datatype.c [hunk 4]
```diff
@@ -130,48 +130,46 @@ PyArray_GetCastFunc(PyArray_Descr *descr, int type_num)
...
+    if (flex_dtype == NULL) {
+        return retval;
     }
 
-    flex_type_num = (*flex_dtype)->type_num;
+    flex_type_num = (flex_dtype)->type_num;
 
     /* Flexible types with expandable size */
-    if (PyDataType_ISUNSIZED(*flex_dtype)) {
+    retval = flex_dtype;
```
Comment (seberg) [inline numpy/core/src/multiarray/convert_datatype.c]: Wonder if this is easier to read as an `else` clause at the end, since it is guaranteed to be set in most of the code.

File: numpy/core/src/multiarray/ctors.c [hunk 5]
```diff
@@ -1816,11 +1816,9 @@ PyArray_FromAny(PyObject *op, PyArray_Descr *newtype, int min_depth,
     }
 
     /* If the requested dtype is flexible, adapt it */
-    if (newtype != NULL) {
-        PyArray_AdaptFlexibleDType(op,
+    newtype = PyArray_AdaptFlexibleDType(op,
                     (dtype == NULL) ? PyArray_DESCR(arr) : dtype,
-                    &newtype);
-    }
+                    newtype);
```
Comment (seberg) [inline numpy/core/src/multiarray/ctors.c]: There is no need for an error check here?

**Review by seberg — COMMENTED** [review]
Looks good to me, one DECREF missing I think and a question only.

File: numpy/core/src/multiarray/nditer_constr.c [hunk 6]
```diff
@@ -1101,8 +1101,8 @@ npyiter_prepare_one_operand(PyArrayObject **op,
             /* We just have a borrowed reference to op_request_dtype */
             Py_INCREF(op_request_dtype);
             /* If the requested dtype is flexible, adapt it */
-            PyArray_AdaptFlexibleDType((PyObject *)(*op), PyArray_DESCR(*op),
-                                        &op_request_dtype);
+            op_request_dtype = PyArray_AdaptFlexibleDType((PyObject *)(*op), PyArray_DESCR(*op),
+                                        op_request_dtype);
```
Comment (seberg) [inline numpy/core/src/multiarray/nditer_constr.c]: Style nit: I think we normally indent this more, except for things such as Exception strings (or start a new line before).

File: numpy/core/src/multiarray/convert_datatype.c (hunk 1 above)
Comment (mattip) [reply numpy/core/src/multiarray/convert_datatype.c]: fixed

File: numpy/core/src/multiarray/convert_datatype.c (hunk 2 above)
Comment (mattip) [reply numpy/core/src/multiarray/convert_datatype.c]: adopted

File: numpy/core/src/multiarray/convert_datatype.c (hunk 3 above)
Comment (mattip) [reply numpy/core/src/multiarray/convert_datatype.c]: adopted

File: numpy/core/src/multiarray/ctors.c (hunk 5 above)
Comment (mattip) [reply numpy/core/src/multiarray/ctors.c]: yes, fixed

File: numpy/core/src/multiarray/nditer_constr.c (hunk 6 above)
Comment (mattip) [reply numpy/core/src/multiarray/nditer_constr.c]: fixed

**Comment by seberg** [comment]
@mattip still working on this, or did you forget to push the changes?

**Comment by mattip** [comment]
working on it. There is a segfault

File: numpy/core/src/multiarray/convert_datatype.c [hunk 7]
```diff
@@ -47,11 +47,12 @@ PyArray_CastToType(PyArrayObject *arr, PyArray_Descr *dtype, int is_f_order)
...
 
     /* If the requested dtype is flexible, adapt it */
-    PyArray_AdaptFlexibleDType((PyObject *)arr, PyArray_DESCR(arr), &dtype);
-    if (dtype == NULL) {
-        return NULL;
+    if (dtype != NULL) {
+        dtype = PyArray_AdaptFlexibleDType((PyObject *)arr, PyArray_DESCR(arr), dtype);
+        if (dtype == NULL) {
+            return NULL;
+        }
```
Comment (seberg) [inline numpy/core/src/multiarray/convert_datatype.c]: Hmm, seems ok, did I ask for this to be changed? Seems that dtype cannot be possibly NULL in this function, or things would go down in flames?

File: numpy/core/src/multiarray/convert_datatype.c (hunk 3 above)
Comment (seberg) [reply numpy/core/src/multiarray/convert_datatype.c]: I am confused what I had thought here, but the code looks right...

File: numpy/core/src/multiarray/convert_datatype.c (hunk 7 above)
Comment (mattip) [reply numpy/core/src/multiarray/convert_datatype.c]: removed exuberant check

File: numpy/core/src/multiarray/convert_datatype.c (hunk 3 above)
Comment (mattip) [reply numpy/core/src/multiarray/convert_datatype.c]: This was the segfault. When removing the `retval = flex_dtype` at the top of the function and moving it to an else clause at the end, I didn't take into account the implied `else` cases in this block. You had suggested moving the `Py_DECREF(flex_type)` out to here, but instead I moved `retval = flex_type` here and left the `Py_DECREF`s in place.

**Comment by seberg** [comment]
Thanks @mattip, in it goes!
