### PR TITLE
BUG: fix potential buffer overflow(#18939)

### LINKED ISSUE #18939: Potential buffer overflow in PyArray_NewFromDescr_int of ctors.c
### Reproducing code example:
**Snippet**:
PyArray_NewFromDescr_int(...., **int nd**,......)
{
    ............... 
    if (descr->subarray) {
        PyObject *ret;
        npy_intp **newdims**[2*NPY_MAXDIMS];
        npy_intp *newstrides = NULL;
        **memcpy**(newdims, dims, nd*sizeof(npy_intp));
        if (strides) {
            newstrides = newdims + NPY_MAXDIMS;
            **memcpy**(newstrides, strides, nd*sizeof(npy_intp));
        }
        ........
}

### Error message:
When we run our analysis tool on NumPy,  a potential buffer-overflow problem was reported. See details below: 
**File**: numpy/core/src/multiarray/ctors.c
**Function**: PyArray_NewFromDescr_int
**Details** in [description](https://github.com/Daybreak2019/IssueReport/blob/master/Numpy/case-9532/9532.png)

Possible call path:
**1**. array_new -> PyArray_NewFromDescr_int
**2**. PyArray_Zeros -> PyArray_NewFromDescr_int
**3**. array_fromfile -> PyArray_FromFile -> PyArray_NewFromDescr_int

### NumPy/Python version information:
The main branch of NumPy

### PR DESCRIPTION
**Pull request by yetanothercheer**
Fix #18939

### CODE REVIEW

**Review by mattip — APPROVED** [review]
LGTM, once CI passes

File: numpy/core/src/multiarray/ctors.c [hunk 1]
```diff
@@ -668,6 +668,14 @@ PyArray_NewFromDescr_int(
     int i;
     npy_intp nbytes;
 
+    if ((unsigned int)nd > (unsigned int)NPY_MAXDIMS) {
```
Comment (eric-wieser) [inline numpy/core/src/multiarray/ctors.c:671]: This is quite a strange way to compare greater than zero, but I guess it works
