### PR TITLE
BUG: datetime64/timedelta64 comparisons return NotImplemented

### LINKED ISSUE #17017: BUG: datetime64, timedelta64 comparisons do not return NotImplemented
I expected datetime64 and timedelta64 comparison methods to return NotImplemented when operating with pd.NaT, which has `__array_priority__ = 100`.

```
import numpy as np
import pandas as pd

ts = np.datetime64("now", "ns")
td = np.timedelta64(0, "ns")

assert pd.NaT.__array_priority__ == 100

>>> ts.__lt__(pd.NaT)
array(False)

>>> td.__lt__(pd.NaT)
array(False)
```

### PR DESCRIPTION
**Pull request by jbrockmendel**
Closes #17017

### CODE REVIEW

File: numpy/core/src/multiarray/scalartypes.c.src [hunk 1]
```diff
@@ -1078,6 +1079,18 @@ gentype_richcompare(PyObject *self, PyObject *other, int cmp_op)
...
+            PyObject_HasAttrString(self, "__array_priority__")) {
+
+        self_prio = PyArray_GetPriority(self, NPY_SCALAR_PRIORITY);
+        other_prio = PyArray_GetPriority(other, NPY_SCALAR_PRIORITY);
+        if (other_prio > self_prio) {
+            Py_INCREF(Py_NotImplemented);
+            return Py_NotImplemented;
+        }
+    }
+
```
Comment (seberg) [inline numpy/core/src/multiarray/scalartypes.c.src:1093]:
```suggestion
   RICHCMP_GIVE_UP_IF_NEEDED(self, other);

```
Thanks for looking into this!  I think we should be able to just use this macro.  Now that I look at it, I am surprised it is not already used.

Comment (jbrockmendel) [reply numpy/core/src/multiarray/scalartypes.c.src]: definitely nicer to not re-implement.  Would my way have worked?  I was pretty proud of figuring out where/how to do this.

Comment (seberg) [reply numpy/core/src/multiarray/scalartypes.c.src]: Yeah, this is mostly right.  `RICHCMP_GIVE_UP_IF_NEEDED` does a little bit more, because it also/first checks `__array_ufunc__`, and it has a bit of short-cutting for builtin Python types/fast-paths, although I am not sure how important that part is.

I guess the `HasAttrString` was unnecessary, since `PyArray_GetPriority` should do that right (although IIRC it swallows a bit many errors I think, but not much too many).

The macro also makes sure we do not defer if we are a superclass, because in that case the other object already had a chance, but I am not sure that matters here.

**Comment by seberg** [comment]
Perfect, LGTM and thanks for the nice new test @jbrockmendel.

**Comment by jbrockmendel** [comment]
booyah, thanks for the quick turnaround.  im looking forward to un-xfailing the relevant pandas tests!

**Comment by charris** [comment]
Should this be backported?

**Comment by seberg** [comment]
I would have leaned to not backport, since it is a very long-standing issue and maybe a bit subtle.  But if it helps pandas, it should also be OK to do.

**Comment by jbrockmendel** [comment]
im on a hotstreak, want to take a shot at the various .astpye(object) and .item() issues for dt64.

My best guess (figuring out where things are defined in numpy is _hard_) for a culprit is DATETIME_getitem in arraytypes.c.src, which calls `convert_datetime_to_pyobject`, which can return an int or datetime or date depending on values.

So I want to create a np.datetime64 object and return it from within convert_datetime_to_pyobject.  My best guess here looks something like

```
NPY_NO_EXPORT PyObject *
convert_datetime_to_pyobject(npy_datetime dt, PyArray_DatetimeMetaData *meta)
{
    PyDatetimeScalarObject* dt64_obj;

    dt64_obj->obval = dt;
    dt64_obj->obmeta = meta;

    return (PyObject*)dt64_obj;
}
```

but im not seeing any way to actually initialize dt64_obj here.  Is there a constructor somewhere?

**Comment by seberg** [comment]
> but im not seeing any way to actually initialize dt64_obj here. Is there a constructor somewhere?

It is not a great function, but you can just use `PyArray_Scalar()` in getitem (the other function can be deleted).  That seems to be the closest we got to a constructor.

The main issue is really all the fallout that might happen afterwards (like things magically working because NumPy converts the datetime to a python one).

**Comment by jbrockmendel** [comment]
Thanks.  I successfully got .item() and .astype(object) to work as expected!  ... and got a segfault in test_array_coercion.  But we're getting somewhere!

**Comment by jbrockmendel** [comment]
minimal reproducer for the segfault:

```
td = np.timedelta64(123, "ns")
arr = np.array(0)
arr[()] = td  # <- segfault
```

troubleshooting...
