### PR TITLE
BUG: Fix searchsorted and CheckFromAny byte-swapping logic

### LINKED ISSUE #28190: BUG: np.searchsorted segfaults on structured arrays in 2.2.2
### Describe the issue:

The reproducer below succeeded on numpy 2.2.1 

- https://github.com/ratt-ru/xarray-ms/actions/runs/12827528711/job/35769680579

but fails on numpy 2.2.2

- https://github.com/ratt-ru/xarray-ms/actions/runs/12859992829/job/35851244780

### Reproduce the code example:

```python
import numpy as np
from numpy.testing import assert_array_equal

rng = np.random.default_rng(seed=42)

time = np.arange(20.0, dtype=np.float64)[:, None]
ant1, ant2 = (a.astype(np.int32)[None, :] for a in np.triu_indices(na, 1))
named_arrays = [("time", time), ("antenna1", ant1), ("antenna2", ant2)]
names, arrays = zip(*named_arrays)
arrays = tuple(a.ravel() for a in np.broadcast_arrays(*arrays))
structured_dtype = np.dtype([(n, a.dtype) for n, a in zip(names, arrays)])

carray = np.zeros(arrays[0].size, structured_dtype)
for n, a in zip(names, arrays):
  carray[n] = a

choice = rng.choice(np.arange(carray.size), 10)

sarray = np.zeros(choice.size, structured_dtype)

sarray["time"] = carray["time"][choice]
sarray["antenna1"] = carray["antenna1"][choice]
sarray["antenna2"] = carray["antenna2"][choice]

idx = np.searchsorted(carray, sarray)
assert_array_equal(carray[idx], sarray)
```

### Error message:

```shell
Fatal Python error: Segmentation fault

Current thread 0x00007c21e7cad080 (most recent call first):
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/_pytest/terminal.py", line 463 in write_ensure_prefix
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/_pytest/terminal.py", line 633 in pytest_runtest_logreport
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/_pytest/runner.py", line 246 in call_and_report
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/_pytest/runner.py", line 132 in runtestprotocol
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/_pytest/runner.py", line 113 in pytest_runtest_protocol
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/_pytest/main.py", line 362 in pytest_runtestloop
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/_pytest/main.py", line 337 in _main
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/_pytest/main.py", line 283 in wrap_session
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/_pytest/main.py", line 330 in pytest_cmdline_main
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 175 in main
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 201 in console_main
  File "/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/bin/py.test", line 8 in <module>

Extension modules: numpy._core._multiarray_umath, numpy.linalg._umath_linalg, pyarrow.lib, arcae.lib.arrow_tables, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pyarrow._compute, pandas._libs.ops, pandas._libs.hashing, pandas._libs.arrays, pandas._libs.tslib, pandas._libs.sparse, pandas._libs.internals, pandas._libs.indexing, pandas._libs.index, pandas._libs.writers, pandas._libs.join, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.json, pandas._libs.parsers, pandas._libs.testing, yaml._yaml, psutil._psutil_linux, psutil._psutil_posix, markupsafe._speedups, tornado.speedups, numcodecs.compat_ext, numcodecs.blosc, numcodecs.zstd, numcodecs.lz4, numcodecs._shuffle, msgpack._cmsgpack, numcodecs.jenkins, numcodecs.vlen, numcodecs.fletcher32 (total: 68)
Segmentation fault (core dumped)
```

### Python and NumPy Versions:

2.2.2
3.11.11 (main, Dec  4 2024, 08:55:08) [GCC 13.2.0]

### Runtime Environment:

[{'numpy_version': '2.2.2',
  'python': '3.11.11 (main, Dec  4 2024, 08:55:08) [GCC 13.2.0]',
  'uname': uname_result(system='Linux', node='simon-t14', release='6.8.0-51-generic', version='#52-Ubuntu SMP PREEMPT_DYNAMIC Thu Dec  5 13:09:44 UTC 2024', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/home/simon/.cache/pypoetry/virtualenvs/xarray-ms-jDhc3Ane-py3.11/lib/python3.11/site-packages/numpy.libs/libscipy_openblas64_-6bb31eeb.so',
  'internal_api': 'openblas',
  'num_threads': 12,
  'prefix': 'libscipy_openblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.28'}]

### Context for the issue:

This isn't high priority for me as the test case where this failed demonstrates an idea rather than core functionality.

- https://github.com/ratt-ru/xarray-ms/blob/9664cbc82bc4799a87424c45013c75e11316a98d/tests/test_basic.py#L1-L30

### PR DESCRIPTION
**Pull request by seberg**
This closes gh-28190 and fixes another issue in the initial code that triggered the regression.

Note that we may still want to avoid this, since this does lead to constructing (view compatible) structured dtypes unnecessarily here.

It would also compactify the dtype.  For building unnecessary dtypes, the better solution may be to just introduce a "canonical" flag to the dtypes (now that we have the space).

---

Actually, the bug may be going back to when the `_int` version was added (and started using borrowed references rather than stealing).  Somehow, it seems we got away with that for a suprisingly long time.

### CODE REVIEW

File: numpy/_core/src/multiarray/ctors.c [hunk 1]
```diff
@@ -1806,26 +1806,30 @@ PyArray_CheckFromAny(PyObject *op, PyArray_Descr *descr, int min_depth,
...
  * references to the descriptor and dtype.
  */
-
 NPY_NO_EXPORT PyObject *
 PyArray_CheckFromAny_int(PyObject *op, PyArray_Descr *in_descr,
                          PyArray_DTypeMeta *in_DType, int min_depth,
                          int max_depth, int requires, PyObject *context)
 {
     PyObject *obj;
+    Py_XINCREF(in_descr);  /* take ownership as we may replace it */
```
Comment (ngoldbaum) [inline numpy/_core/src/multiarray/ctors.c:1815]: I'm a little bowled over we've gotten away with this for so long. That said, perhaps not so surprising because there aren't a lot of all sites for either `CheckFromAny` or `CheckFromAny_int`.

Can you double-check that the use of `CheckFromAny` in `iter_ass_subscript` is correct? It looks correct to me but I just want to make sure you agree.

File: numpy/_core/src/multiarray/item_selection.c [hunk 2]
```diff
@@ -2138,26 +2137,20 @@ PyArray_SearchSorted(PyArrayObject *op1, PyObject *op2,
...
         Py_DECREF(dtype);
-        /* refs to dtype we own = 0 */
         return NULL;
     }
 
-    /* need ap2 as contiguous array and of right type */
-    /* refs to dtype we own = 1 */
-    Py_INCREF(dtype);
-    /* refs to dtype we own = 2 */
+    /* need ap2 as contiguous array and of right dtype (steals and may be replace it) */
```
Comment (mhvk) [inline numpy/_core/src/multiarray/item_selection.c:2144]: `replace it` -> `replace dtype` (since "it" could also refer to `ap2`, the array).

Actually, with my comment below, I think this can just be
```
/* need ap2 as contiguous array and of right dtype (note: steals dtype reference) */

File: numpy/_core/src/multiarray/item_selection.c [hunk 3]
```diff
@@ -2138,26 +2137,20 @@ PyArray_SearchSorted(PyArrayObject *op1, PyObject *op2,
...
                                 0, 0,
                                 NPY_ARRAY_CARRAY_RO | NPY_ARRAY_NOTSWAPPED,
                                 NULL);
-    /* refs to dtype we own = 1, array creation steals one even on failure */
     if (ap2 == NULL) {
-        Py_DECREF(dtype);
-        /* refs to dtype we own = 0 */
         return NULL;
     }
+    /* dtype was stolen, replace it in case the array creation replaced it. */
```
Comment (mhvk) [inline numpy/_core/src/multiarray/item_selection.c:2152]: Combine with l.2162? And write there,
```
/*
 * The dtype reference we had was used for creating ap2, which may have
 * replaced it with another. So here we copy the dtype of ap2 and use it for `ap1`.
 */
dtype = (PyArray_Descr *)Py_NewRef(PyArray_DESCR(ap2));
```

File: numpy/_core/src/multiarray/ctors.c (hunk 1 above)
Comment (mhvk) [reply numpy/_core/src/multiarray/ctors.c:1815]: Just to be sure: the comment is still correct? That at the end of the day the ref-count to `in_descr` is one down?

**Review by mhvk — COMMENTED** [review]
Wow.  The simplification in `item_selection` is worth it even if there hadn't been a bug!

Inline some suggestions that may help clarity.

File: numpy/_core/src/multiarray/ctors.c (hunk 1 above)
Comment (mhvk) [reply numpy/_core/src/multiarray/ctors.c:1815]: Sorry, I meant the comment at l.1807 for the function as a whole.

**Review by mhvk — APPROVED** [review]
Looks all good to me, although still a small query of the just-in-case variety.

File: numpy/_core/src/multiarray/ctors.c (hunk 1 above)
Comment (seberg) [reply numpy/_core/src/multiarray/ctors.c:1815]: yes, it's correct.  it borrows it, it doesn't steal it.

**Comment by mhvk** [comment]
Might as well get this in, I think!
